/* ============================================================
 * CPE Prep — C2 字彙卡 (60 items)
 * front = word/phrase, pos = part of speech,
 * def = English definition, example, zh = 繁中釋義
 * ============================================================ */

var VOCAB = [
  { front: "ubiquitous", pos: "adj.", def: "seeming to be everywhere at once", example: "Smartphones have become so ubiquitous that their absence is now what we notice.", zh: "無所不在的" },
  { front: "ephemeral", pos: "adj.", def: "lasting for only a very short time", example: "Online fame is notoriously ephemeral.", zh: "短暫的、稍縱即逝的" },
  { front: "quintessential", pos: "adj.", def: "being the most typical or perfect example of something", example: "The village pub is the quintessential English institution.", zh: "典型的、精髓的" },
  { front: "exacerbate", pos: "v.", def: "to make a bad situation worse", example: "Cutting the budget would only exacerbate the staffing crisis.", zh: "使惡化、加劇" },
  { front: "tenuous", pos: "adj.", def: "weak, thin, or easily challenged (of a link or argument)", example: "The connection between the two events is tenuous at best.", zh: "薄弱的、牽強的" },
  { front: "underpin", pos: "v.", def: "to form the basis or support of something", example: "Mutual trust underpins any successful negotiation.", zh: "支撐、構成…的基礎" },
  { front: "salient", pos: "adj.", def: "most noticeable or important", example: "She summarised the salient points of the report in two minutes.", zh: "顯著的、最重要的" },
  { front: "pernicious", pos: "adj.", def: "having a harmful effect, especially gradually or subtly", example: "The pernicious influence of rumour spread through the office.", zh: "有害的（尤指潛移默化地）" },
  { front: "at loggerheads", pos: "idiom", def: "in strong disagreement with someone", example: "The two ministries have been at loggerheads over funding for years.", zh: "爭執不下、意見嚴重不合" },
  { front: "a moot point", pos: "idiom", def: "a matter that is debatable or no longer of practical relevance", example: "Whether he intended to resign is now a moot point.", zh: "有爭議（或已無實質意義）的問題" },
  { front: "gloss over", pos: "phr. v.", def: "to avoid discussing something unpleasant by treating it briefly", example: "The report glosses over the project's early failures.", zh: "掩飾、輕描淡寫帶過" },
  { front: "watershed", pos: "n.", def: "an event marking a decisive turning point", example: "The trial proved a watershed in press regulation.", zh: "分水嶺、轉捩點" },
  { front: "precarious", pos: "adj.", def: "not securely held; dangerously uncertain", example: "Freelancers often live in precarious financial circumstances.", zh: "不穩固的、岌岌可危的" },
  { front: "entrench", pos: "v.", def: "to establish something so firmly that change is difficult", example: "The reforms merely entrenched the privileges they were meant to abolish.", zh: "使根深蒂固" },
  { front: "spurious", pos: "adj.", def: "false, although seeming to be genuine or logical", example: "The advertisement rested on a spurious claim of scientific backing.", zh: "似是而非的、虛假的" },
  { front: "conducive to", pos: "adj. + prep.", def: "providing conditions that make something possible or likely", example: "Open-plan offices are not always conducive to concentration.", zh: "有助於…的" },
  { front: "on the cusp of", pos: "idiom", def: "at the point when something is about to change or begin", example: "The industry is on the cusp of a fundamental transformation.", zh: "正處於…的邊緣／轉折點" },
  { front: "galvanise", pos: "v.", def: "to shock or excite someone into taking action", example: "The scandal galvanised parliament into passing the bill.", zh: "激起、刺激（使行動）" },
  { front: "intransigent", pos: "adj.", def: "refusing to change one's position or attitude", example: "Negotiations stalled in the face of both sides' intransigent demands.", zh: "不妥協的、固執的" },
  { front: "a foregone conclusion", pos: "idiom", def: "a result that is obvious before it happens", example: "With such a majority, the vote was a foregone conclusion.", zh: "早已注定的結果" },
  { front: "run the gamut", pos: "idiom", def: "to include the whole range of something", example: "Reactions ran the gamut from delight to outright fury.", zh: "涵蓋（從…到…的）全部範圍" },
  { front: "nebulous", pos: "adj.", def: "vague and lacking clear form or definition", example: "The proposal remains nebulous on the question of funding.", zh: "模糊不清的" },
  { front: "extol", pos: "v.", def: "to praise something enthusiastically", example: "The brochure extols the virtues of rural living.", zh: "讚頌、頌揚" },
  { front: "disparate", pos: "adj.", def: "essentially different in kind; not able to be compared", example: "The coalition unites disparate groups with little in common.", zh: "迥異的、異質的" },
  { front: "flout", pos: "v.", def: "to openly disregard a rule or convention", example: "Drivers routinely flout the speed limit on this stretch.", zh: "公然藐視（規則）" },
  { front: "insidious", pos: "adj.", def: "spreading gradually and harmfully without being noticed", example: "Burnout is insidious; by the time you notice it, it has taken hold.", zh: "潛伏的、不知不覺加劇的" },
  { front: "gravitas", pos: "n.", def: "seriousness of manner that commands respect", example: "She brings a certain gravitas to even the most trivial proceedings.", zh: "莊重、威嚴氣度" },
  { front: "eschew", pos: "v.", def: "to deliberately avoid or abstain from", example: "He eschews social media entirely, to the bafflement of his colleagues.", zh: "刻意避開、戒絕" },
  { front: "veneer", pos: "n.", def: "a superficial appearance concealing the true nature of something", example: "Beneath the veneer of civility, the rivalry was ferocious.", zh: "表面假象、虛飾" },
  { front: "bear the brunt of", pos: "idiom", def: "to suffer the worst part of something unpleasant", example: "Small businesses bore the brunt of the downturn.", zh: "首當其衝、承受最重打擊" },
  { front: "in the throes of", pos: "idiom", def: "in the middle of a difficult or painful process", example: "The company is in the throes of a painful restructuring.", zh: "正處於…的煎熬／劇變中" },
  { front: "a double-edged sword", pos: "idiom", def: "something with both favourable and unfavourable consequences", example: "Publicity proved a double-edged sword for the little bakery.", zh: "雙面刃" },
  { front: "grapple with", pos: "phr. v.", def: "to struggle to deal with or understand a difficult problem", example: "Regulators are still grappling with the implications of the technology.", zh: "努力應對、與…纏鬥" },
  { front: "panacea", pos: "n.", def: "a supposed remedy for all problems", example: "Technology is no panacea for educational inequality.", zh: "萬靈丹" },
  { front: "lambast", pos: "v.", def: "to criticise someone or something harshly", example: "Critics lambasted the film as two hours of expensive noise.", zh: "痛批、猛烈抨擊" },
  { front: "propensity", pos: "n.", def: "a natural tendency to behave in a particular way", example: "He has a propensity for exaggeration that undermines his credibility.", zh: "（行為）傾向、癖性" },
  { front: "relinquish", pos: "v.", def: "to give up something unwillingly, especially power or control", example: "She refused to relinquish control of the family firm.", zh: "（不情願地）放棄、交出" },
  { front: "unequivocal", pos: "adj.", def: "leaving no doubt; completely clear", example: "The board issued an unequivocal denial of the allegations.", zh: "毫不含糊的、明確的" },
  { front: "mitigate", pos: "v.", def: "to make something less severe or harmful", example: "Planting trees can mitigate the effects of urban heat.", zh: "緩解、減輕" },
  { front: "harbinger", pos: "n.", def: "a sign that announces the approach of something", example: "Falling orders were a harbinger of the recession to come.", zh: "先兆、預兆" },
  { front: "squander", pos: "v.", def: "to waste something valuable in a careless way", example: "The government squandered a rare opportunity for reform.", zh: "揮霍、浪費" },
  { front: "ostensibly", pos: "adv.", def: "apparently or supposedly, but perhaps not actually", example: "He called the meeting ostensibly to discuss the budget.", zh: "表面上、名義上" },
  { front: "curtail", pos: "v.", def: "to reduce or restrict something", example: "New rules will sharply curtail the agency's powers.", zh: "削減、限制" },
  { front: "plight", pos: "n.", def: "a difficult or unfortunate situation", example: "The documentary drew attention to the plight of seasonal workers.", zh: "困境、苦境" },
  { front: "vindicate", pos: "v.", def: "to prove that someone or something was right after doubt", example: "The findings vindicated her much-mocked predictions.", zh: "證明…正確、平反" },
  { front: "egregious", pos: "adj.", def: "outstandingly bad; shocking", example: "The report catalogued a series of egregious safety violations.", zh: "極其惡劣的" },
  { front: "permeate", pos: "v.", def: "to spread through every part of something", example: "A quiet anxiety permeates the whole novel.", zh: "瀰漫、滲透" },
  { front: "stopgap", pos: "n.", def: "a temporary solution used until something better is found", example: "The loan was only ever intended as a stopgap.", zh: "權宜之計" },
  { front: "fathom", pos: "v.", def: "to understand something after much thought", example: "I cannot fathom why he turned the offer down.", zh: "理解、猜透" },
  { front: "untenable", pos: "adj.", def: "impossible to defend or maintain (of a position or argument)", example: "After the leak, his position as chairman became untenable.", zh: "站不住腳的、難以維持的" },
  { front: "a fine line between", pos: "idiom", def: "a subtle distinction between two similar things", example: "There is a fine line between confidence and arrogance.", zh: "一線之隔" },
  { front: "hamper", pos: "v.", def: "to prevent progress or free movement", example: "Rescue efforts were hampered by torrential rain.", zh: "妨礙、阻礙" },
  { front: "incessant", pos: "adj.", def: "continuing without pause, usually annoyingly", example: "The incessant notifications made sustained work impossible.", zh: "不停的、無休止的" },
  { front: "allude to", pos: "phr. v.", def: "to mention something indirectly", example: "She alluded to difficulties at home without going into detail.", zh: "間接提及、暗指" },
  { front: "trepidation", pos: "n.", def: "a feeling of fear or anxiety about something that may happen", example: "It was with some trepidation that I opened the examiner's letter.", zh: "惶恐、忐忑" },
  { front: "bolster", pos: "v.", def: "to support or strengthen something", example: "The new evidence bolstered the defence's case considerably.", zh: "支持、增強" },
  { front: "myriad", pos: "adj./n.", def: "an extremely large number of something", example: "The reform failed for a myriad of reasons, none of them secret.", zh: "無數的、大量" },
  { front: "elusive", pos: "adj.", def: "difficult to find, catch, define or achieve", example: "A precise definition of consciousness remains elusive.", zh: "難以捉摸／達成的" },
  { front: "reconcile", pos: "v.", def: "to make two conflicting things compatible; to accept a disagreeable situation (reconcile oneself to)", example: "It is hard to reconcile his public statements with his private conduct.", zh: "調和、使一致；甘心接受" },
  { front: "take something with a pinch of salt", pos: "idiom", def: "to doubt the accuracy or truth of something", example: "Take his sales figures with a pinch of salt.", zh: "對…持保留態度、半信半疑" }
];

if (typeof module !== 'undefined') {
  module.exports = { VOCAB: VOCAB };
}
