(function () {
var BANK = [
  { id: "f-lis3-01", title: "Radio Interview: The Marathon Grandmother", kind: "dialogue",
    script: "Presenter: With me in the studio this morning is Barbara Quinn, who last Sunday, at the age of seventy-one, completed her tenth marathon. Barbara, congratulations.\nBarbara: Thank you very much. Though I should say straight away, I was nearly the last to finish. Six hours and forty minutes. The man who packs up the barriers was walking along beside me at the end.\nPresenter: But you finished, which is more than most of us can say. Now, you didn't start running until quite late in life, is that right?\nBarbara: That's right, I was sixty-two. My doctor told me my blood pressure was creeping up and suggested gentle exercise, you know, swimming or walking. Running was actually my granddaughter's idea. She was training for a five-kilometre charity race and wanted company, and I think she expected me to give up after one lap of the park.\nPresenter: And clearly you didn't.\nBarbara: Well, I nearly did! That first month was awful. Everything ached. But I'm stubborn, always have been, and once I could run for twenty minutes without stopping, something changed. It stopped being a punishment and became the best part of my day.\nPresenter: You've raised quite a lot of money along the way, I believe.\nBarbara: Just over thirty thousand pounds now, all for the heart research charity. That's honestly what keeps me going when training gets miserable in February. It's not about my times, at my age it can't be. It's about the sponsorship forms.\nPresenter: And what do your family think? Any worries?\nBarbara: My son thinks I'm mad and keeps sending me articles about knee injuries. My granddaughter, the one who started it all, ran beside me on Sunday for the last three miles. That shut him up, I can tell you.\nPresenter: Wonderful. And is number eleven in the diary?\nBarbara: Officially, I've retired. Unofficially — ask me again in the spring.",
    questions: [
      { q: "What does Barbara say about last Sunday's marathon?", options: ["She finished it very close to the back of the field.", "She achieved her fastest ever time.", "She had to stop before the finish line.", "She completed it faster than her granddaughter."], answer: 0, explanation: "Barbara says \"I was nearly the last to finish\" in six hours forty minutes, with the barrier man walking beside her at the end." },
      { q: "Why did Barbara originally take up exercise?", options: ["Her doctor was concerned about her health.", "She wanted to raise money for charity.", "Her son suggested it would help her knees.", "She had always dreamed of running a marathon."], answer: 0, explanation: "Her doctor \"told me my blood pressure was creeping up and suggested gentle exercise\" - a health concern started it; the charity came later." },
      { q: "Whose idea was it for Barbara to start running rather than another sport?", options: ["Her doctor's.", "Her granddaughter's.", "Her son's.", "Her own."], answer: 1, explanation: "She says \"Running was actually my granddaughter's idea\" because the girl was training for a charity race and wanted company." },
      { q: "What motivates Barbara to keep training in difficult months?", options: ["Improving her finishing times.", "The money she raises for charity.", "Proving her son wrong.", "Her doctor's continued advice."], answer: 1, explanation: "She says the thirty thousand pounds for heart research is \"honestly what keeps me going when training gets miserable in February... It's about the sponsorship forms\"." },
      { q: "What does Barbara suggest about running another marathon?", options: ["She has definitely retired from racing.", "She has already entered next year's race.", "She may well change her mind about retiring.", "Her family have forbidden her to enter again."], answer: 2, explanation: "She says \"Officially, I've retired. Unofficially - ask me again in the spring\", hinting strongly that she may change her mind." }
    ] },
  { id: "f-lis3-02", title: "First Shift at the Ice-Cream Van", kind: "monologue",
    script: "So people always laugh when I tell them my summer job was driving an ice-cream van, but honestly, it taught me more than any classroom ever has. My uncle owns two vans, and last June his regular helper broke his ankle playing football, so I got a phone call asking if I fancied earning some money. I said yes before he'd even finished the sentence, and then spent the whole night panicking, because I'd never worked a single day in my life.\nMy first shift was at the seafront on a hot Saturday, which my uncle later admitted was like learning to swim by jumping into the deep end. The queue never dropped below ten people for six hours straight. I got orders wrong, I gave a man a screwdriver — that's a type of ice cream, by the way, not the tool — when he'd asked for a strawberry split, and at two o'clock the soft ice-cream machine jammed with about thirty children watching me.\nHere's the thing, though: nobody was angry. People on a beach in the sunshine are the most patient customers in the world. A woman in the queue actually talked me through fixing the machine because she'd worked in a van herself thirty years ago.\nBy August I could handle the Saturday rush on my own, calculate change without thinking, and keep smiling at hour eight. The money was decent, but what I really took away was confidence. If you can serve two hundred melting ice creams to two hundred hot children without crying, a job interview holds no fear whatsoever. My uncle's already booked me for next summer, and honestly, I can't wait.",
    questions: [
      { q: "How did the speaker get the job?", options: ["He replied to an advertisement.", "His uncle needed a replacement helper.", "He asked his uncle for work.", "A friend recommended him."], answer: 1, explanation: "His uncle's regular helper \"broke his ankle playing football\", so the uncle phoned to offer him the work." },
      { q: "How did the speaker feel the night before starting?", options: ["Confident because of his experience.", "Anxious because he had never worked before.", "Excited about driving the van.", "Annoyed about losing his free summer."], answer: 1, explanation: "He \"spent the whole night panicking, because I'd never worked a single day in my life\"." },
      { q: "What went wrong during his first shift?", options: ["He crashed the van at the seafront.", "He served a customer the wrong item.", "He ran out of strawberry ice cream.", "He closed the van six hours early."], answer: 1, explanation: "He \"gave a man a screwdriver... when he'd asked for a strawberry split\", as well as struggling with the jammed machine." },
      { q: "Who helped him when the machine jammed?", options: ["His uncle, over the phone.", "A customer with experience of van work.", "One of the children watching.", "The regular helper, from home."], answer: 1, explanation: "\"A woman in the queue actually talked me through fixing the machine because she'd worked in a van herself thirty years ago\"." },
      { q: "What does the speaker say he mainly gained from the job?", options: ["Enough money for the year.", "A permanent job with his uncle.", "Greater self-confidence.", "An ambition to run his own business."], answer: 2, explanation: "He says \"what I really took away was confidence\" - after the van, \"a job interview holds no fear whatsoever\"." }
    ] },
  { id: "f-lis3-03", title: "Choosing a Present for Coach Willis", kind: "dialogue",
    script: "Amy: Right, Dan, we need to sort out Coach Willis's leaving present today. He finishes at the end of the month and we've done absolutely nothing.\nDan: I know, I know. How much have we actually collected from the team?\nAmy: Ninety-four pounds. Everyone chipped in except Robbie, and he's promised his share on Friday, so call it a hundred.\nDan: Okay, that's decent. My first thought was a watch. Something engraved, you know, classy.\nAmy: A hundred pounds doesn't buy a classy watch, though. It buys a watch that stops working in March. And he already wears that ancient one his wife gave him — he'd never take it off anyway.\nDan: Fair enough. What about football boots? He's always moaning that his leak.\nAmy: I thought about that, but sizes are a nightmare. If we get them wrong he'd have to go and exchange them himself, which ruins the whole thing.\nDan: Hmm. Okay, listen to my other idea. You know how he keeps saying the best day of his life was watching the cup final at Wembley in 1998? There's a company that frames old match tickets and programmes. My cousin found the actual programme from that final online for thirty quid.\nAmy: Oh, that's brilliant. Programme, frame, and a little plaque with all our names on it. That's personal, that's the kind of thing you keep forever.\nDan: And it leaves enough money for flowers for his wife, because let's be honest, she's washed the team kit for fifteen years.\nAmy: She absolutely has. Right, you order the programme tonight, I'll sort the framing in town, and we present it at the last training session. Not the match — he'll be too stressed at the match.\nDan: Agreed. Last training session. And Amy — not a word to anyone outside the team. If Robbie's little brother finds out, the whole town knows by Tuesday.",
    questions: [
      { q: "What is the situation at the start of the conversation?", options: ["The coach has already left the club.", "They have collected money but not chosen a gift.", "They cannot agree on how much to collect.", "The team has refused to contribute."], answer: 1, explanation: "Amy says the coach finishes at the end of the month and \"we've done absolutely nothing\" about the present, though ninety-four pounds is already collected." },
      { q: "Why does Amy reject the idea of a watch?", options: ["Their budget would only buy a poor-quality one.", "The coach has said he dislikes watches.", "Engraving would take too long.", "His wife has already bought him one this year."], answer: 0, explanation: "Amy says \"A hundred pounds doesn't buy a classy watch... It buys a watch that stops working in March\", and he'd never stop wearing his old one anyway." },
      { q: "What is the problem with buying football boots?", options: ["The coach never wears boots at training.", "They might buy the wrong size.", "Good boots cost more than they have.", "The coach has just bought new ones."], answer: 1, explanation: "Amy says \"sizes are a nightmare. If we get them wrong he'd have to go and exchange them himself\"." },
      { q: "Why do they choose the framed programme?", options: ["It is the cheapest option available.", "It connects to a day the coach treasures.", "The coach collects old football programmes.", "It was suggested by the coach's wife."], answer: 1, explanation: "The programme is from the 1998 Wembley cup final, which the coach \"keeps saying... was the best day of his life\" - it's personal and connected to a treasured memory." },
      { q: "When will they give the coach his present?", options: ["At his final match.", "At the last training session.", "On Friday when Robbie pays.", "At a party at his house."], answer: 1, explanation: "Amy says they'll present it \"at the last training session. Not the match - he'll be too stressed at the match\", and Dan agrees." }
    ] },
  { id: "f-lis3-04", title: "Talk: Behind the Scenes at the Aquarium", kind: "monologue",
    script: "Good afternoon, everyone, and welcome to our behind-the-scenes talk here at Westport Aquarium. I'm Lauren, one of the senior aquarists, and for the next half hour I'll be showing you what visitors normally never see.\nFirst, a question I get every single day: what's the hardest part of the job? People expect me to say the sharks. Actually, the sharks are the easy ones — they're fed twice a week on a strict routine and they're remarkably calm animals, whatever the films tell you. The genuinely difficult residents are the octopuses. They're escape artists. Our current octopus, Doris, once got out of her tank overnight, crossed the floor, and was found in a neighbouring tank, having eaten several of the crabs we were keeping there. We now weigh down her lid with rocks, and she still watches us putting them on, working out the arrangement.\nSecond thing people don't realise: most of our day is cleaning and cooking. Every animal has a diet sheet, and the kitchen here prepares restaurant-quality seafood — honestly, better than what I eat at home. The food budget is the biggest single cost in the building, bigger than staff wages or electricity.\nA quick word about what we're for, because it matters. Aquariums used to be about entertainment, full stop. These days, breeding programmes are the heart of it. Last year we successfully bred seahorses, which are threatened in the wild, and sent forty juveniles to other aquariums so that nobody has to take them from the sea.\nRight — if you'd like to follow me through this grey door, please don't touch anything wet, and do keep your voices down near the quarantine tanks. The new arrivals are settling in, and stress is the biggest danger for them in their first weeks.",
    questions: [
      { q: "What does Lauren say about the sharks?", options: ["They are more dangerous than people think.", "They are easier to care for than expected.", "They are fed every day on a strict routine.", "They frequently try to escape."], answer: 1, explanation: "She says \"the sharks are the easy ones - they're fed twice a week on a strict routine and they're remarkably calm animals\"." },
      { q: "Why does Lauren describe Doris as difficult?", options: ["She refuses to eat her prepared food.", "She once escaped and ate other animals.", "She attacks the staff during cleaning.", "She hides whenever visitors appear."], answer: 1, explanation: "Doris \"once got out of her tank overnight... and was found in a neighbouring tank, having eaten several of the crabs\"." },
      { q: "What does Lauren say is the aquarium's biggest expense?", options: ["Staff wages.", "Electricity.", "The animals' food.", "New tanks and equipment."], answer: 2, explanation: "She says \"The food budget is the biggest single cost in the building, bigger than staff wages or electricity\"." },
      { q: "According to Lauren, how have aquariums changed?", options: ["They now focus on breeding threatened species.", "They have become purely entertainment venues.", "They no longer keep large animals.", "They send most animals back to the sea."], answer: 0, explanation: "She says aquariums \"used to be about entertainment, full stop\" but now \"breeding programmes are the heart of it\", citing the seahorse successes." },
      { q: "What does Lauren ask visitors to do near the quarantine tanks?", options: ["Take photographs of the new arrivals.", "Keep quiet to avoid stressing the animals.", "Wash their hands before entering.", "Stay behind the yellow line."], answer: 1, explanation: "She says \"do keep your voices down near the quarantine tanks\" because \"stress is the biggest danger\" for new arrivals." }
    ] },
  { id: "f-lis3-05", title: "Housemates and the Leaking Ceiling", kind: "dialogue",
    script: "Priya: Sam, have you seen the bathroom ceiling? There's a brown stain the size of a dinner plate, and it definitely wasn't there on Monday.\nSam: Yeah, I noticed it this morning. And when I pressed it — gently, before you say anything — it felt damp. I think it's coming from the flat upstairs.\nPriya: Great. So what do we do, knock on their door?\nSam: I already tried at lunchtime. No answer. I think the guy works nights, so hammering on his door at midday probably isn't winning us any friends.\nPriya: Okay, then we go straight to the letting agency. It's their job, and honestly, after they took six weeks to fix the oven, they owe us a quick one.\nSam: I emailed them this afternoon, actually. Photos attached, floor plan, the lot. But you know what they're like — if we just wait for a reply, we'll be swimming by Friday.\nPriya: So phone them first thing tomorrow and refer to the email. Put it in writing first, then chase by phone. My sister's a solicitor, that's literally her advice for everything.\nSam: Good plan. There's one more thing, though. My laptop lives on the shelf right under that stain. If the ceiling actually gives way—\nPriya: Move it tonight. And we should probably put a bucket in the bath and take photos every day, so there's a record of it getting worse. If our stuff gets damaged, we'll need proof of when we reported it.\nSam: You're scarily good at this.\nPriya: Second time it's happened to me. In my last house we ignored a stain exactly like that for a month, and one Sunday the whole corner of the ceiling ended up in the washing basket. I'm not doing that again.\nSam: Right. Bucket, photos, phone call at nine. And I'll try upstairs again on Saturday morning, when a normal human being might actually be awake.",
    questions: [
      { q: "What problem have Priya and Sam discovered?", options: ["Their oven has stopped working again.", "There is a damp stain on the bathroom ceiling.", "The flat upstairs has flooded completely.", "Their washing basket has been damaged."], answer: 1, explanation: "Priya describes \"a brown stain the size of a dinner plate\" on the bathroom ceiling, which Sam found damp to the touch." },
      { q: "Why couldn't Sam speak to the upstairs neighbour?", options: ["The neighbour refused to open the door.", "There was no answer, probably because he works nights.", "The neighbour is away on holiday.", "The agency told him not to make contact."], answer: 1, explanation: "Sam says \"I already tried at lunchtime. No answer. I think the guy works nights\"." },
      { q: "Why does Priya mention the oven?", options: ["To show the agency has been slow in the past.", "To suggest the oven caused the leak.", "To remind Sam to cook dinner.", "To explain why the agency owes them money."], answer: 0, explanation: "She says the agency \"took six weeks to fix the oven\", using it as evidence of their slowness and why they \"owe us a quick one\"." },
      { q: "What does Priya recommend they do about contacting the agency?", options: ["Wait patiently for a reply to the email.", "Visit the agency's office in person.", "Follow up the written report with a phone call.", "Ask her sister to write a legal letter."], answer: 2, explanation: "She says \"Put it in writing first, then chase by phone\" - phone the next morning and refer to Sam's email." },
      { q: "Why does Priya know how to handle the situation?", options: ["Her sister is dealing with the case.", "She has experienced a similar problem before.", "She used to work for a letting agency.", "She read about it in the tenancy agreement."], answer: 1, explanation: "She says it's the \"second time it's happened to me\" - in her last house an ignored stain ended with the ceiling collapsing." }
    ] },
  { id: "f-lis3-06", title: "Podcast: The Truth About Memory Tricks", kind: "monologue",
    script: "Hello and welcome back to Brainwaves, the podcast about how your mind actually works. I'm Dr Femi Adeyemi, and today we're looking at memory techniques — the tricks that promise to help you remember names, dates and exam facts. Do any of them genuinely work?\nLet's start with the one everybody's heard of: repetition. Reading your notes over and over feels productive, but the research here is brutal. Rereading is one of the least effective ways to learn, because your brain confuses recognising something with actually knowing it. The page looks familiar, so you feel prepared — right up until the exam, when the familiar page isn't there to help you.\nWhat does work, then? Testing yourself. Closing the book and forcing your brain to drag the information out is uncomfortable, and that's exactly why it works. The effort of retrieving a memory strengthens it, a bit like a muscle. In one study, students who tested themselves remembered around fifty per cent more a week later than students who spent the same time rereading.\nSecond, spacing. Ten minutes of practice a day for six days beats one hour the night before, every single time, even though it's the same total amount. Your brain treats information it meets repeatedly over time as important, and information it meets once in a panic as disposable.\nAnd what about the famous memory palace, where you imagine placing facts around a building you know well? It genuinely works — champions use it to memorise entire decks of cards — but here's my honest advice: for most students, it's more effort than it's worth for everyday revision. Save it for lists that simply refuse to stick.\nSo, the boring truth: test yourself, space it out, and stop rereading. Next week — why we forget people's names within seconds of hearing them. Until then, be kind to your brain.",
    questions: [
      { q: "What is the main purpose of this podcast episode?", options: ["To examine whether memory techniques really work.", "To explain why people forget names.", "To advertise a memory training course.", "To describe how memory champions train."], answer: 0, explanation: "Dr Adeyemi says today's topic is memory techniques and asks \"Do any of them genuinely work?\"; forgetting names is next week's topic." },
      { q: "Why does rereading notes fail as a study method?", options: ["It takes far longer than other methods.", "It makes learners mistake familiarity for knowledge.", "It only works for very short texts.", "It strains the eyes before an exam."], answer: 1, explanation: "He says \"your brain confuses recognising something with actually knowing it\" - the page looks familiar so you feel prepared without truly knowing the content." },
      { q: "Why is self-testing effective, according to the speaker?", options: ["It is more relaxing than rereading.", "The effort of retrieving memories strengthens them.", "It requires no books or materials.", "It shortens total revision time by half."], answer: 1, explanation: "He explains \"The effort of retrieving a memory strengthens it, a bit like a muscle\", which is why the discomfort of testing works." },
      { q: "What point does the speaker make about spacing?", options: ["Short daily sessions beat one long session.", "Studying should happen only at night.", "Six hours of study a day is ideal.", "Spacing works only for language learning."], answer: 0, explanation: "He says \"Ten minutes of practice a day for six days beats one hour the night before, every single time, even though it's the same total amount\"." },
      { q: "What is the speaker's opinion of the memory palace technique?", options: ["It has been proved not to work.", "It is useful but too demanding for everyday revision.", "It is the best method for all students.", "It only works for memorising cards."], answer: 1, explanation: "He says \"It genuinely works... but... for most students, it's more effort than it's worth for everyday revision\" - effective yet too demanding for routine use." }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
