(function () {
var BANK = [
  { id: "f-lis4-01", title: "Radio Interview: Photographing the Storm", kind: "dialogue",
    script: "Presenter: My guest today is Kasia Nowak, whose photographs of thunderstorms have just won a national award. Kasia, how does somebody end up chasing storms with a camera?\nKasia: Completely by accident, actually. Five years ago I was a wedding photographer. One June afternoon the couple postponed everything because this enormous storm was rolling in, and instead of packing up, I stood in the hotel car park and photographed the sky for an hour. Those pictures got more attention than anything I'd ever shot at a wedding, and that was that.\nPresenter: It looks dangerous. Is it?\nKasia: Less than people imagine, if you're sensible. My absolute rule is that I never stop the car anywhere without first working out my way out. Before I even lift the camera, I know exactly which road takes me away from the storm and how long I need. If there's no clear exit, I don't stop, however beautiful the sky is.\nPresenter: And what should we actually be afraid of?\nKasia: Honestly? The driving. Everyone worries about lightning, but statistically the risky part is being on wet, dark roads with other drivers who can't see properly. That's where I'm most careful.\nPresenter: What separates a good storm photo from a great one?\nKasia: Waiting. People think it's luck or fast reactions, but I might sit in one field for four hours for a single frame. The storm decides the schedule, not me.\nPresenter: Any advice for beginners?\nKasia: Don't buy anything yet. Spend a season learning to read forecasts and clouds first — your own window is a fine place to start. The camera is the least important part of the whole business.",
    questions: [
      { q: "How did Kasia become a storm photographer?", options: ["A wedding was postponed because of a storm.", "She studied weather science at university.", "A magazine commissioned storm pictures.", "She won a national photography award."], answer: 0, explanation: "A couple postponed their wedding when a storm rolled in, and the pictures she took of the sky that afternoon 'got more attention than anything I'd ever shot at a wedding'." },
      { q: "What safety rule does Kasia always follow?", options: ["She never photographs alone.", "She plans her escape route before stopping.", "She stays at least ten kilometres from a storm.", "She only works in daylight hours."], answer: 1, explanation: "She says 'I never stop the car anywhere without first working out my way out' - if there's no clear exit, she doesn't stop." },
      { q: "What does Kasia say is the most dangerous part of her work?", options: ["Being struck by lightning.", "Standing in open fields.", "Driving in poor conditions.", "Sudden flooding on country roads."], answer: 2, explanation: "She says 'the risky part is being on wet, dark roads with other drivers who can't see properly', not the lightning everyone worries about." },
      { q: "According to Kasia, what makes a great storm photograph possible?", options: ["Expensive professional equipment.", "Very fast reactions.", "Pure luck with the weather.", "Being prepared to wait for hours."], answer: 3, explanation: "She says the key is 'waiting' - she might sit in one field for four hours for a single frame, because 'the storm decides the schedule'." },
      { q: "What does Kasia advise beginners to do first?", options: ["Buy a weatherproof camera.", "Learn to understand forecasts and clouds.", "Join an organised storm-chasing trip.", "Practise at weddings and events."], answer: 1, explanation: "She says 'Don't buy anything yet' and recommends spending a season 'learning to read forecasts and clouds first'." }
    ] },
  { id: "f-lis4-02", title: "Talk: Getting Started with Stargazing", kind: "monologue",
    script: "Good evening, everyone, and welcome to the community centre's science month. Tonight: stargazing for absolute beginners, and I want to start by stopping you making the classic mistake. Almost everyone who gets interested in the night sky goes straight out and buys a telescope, and almost every one of those telescopes ends up in a cupboard by February. Please don't. Your eyes, a deckchair and a little patience will show you meteors, satellites, planets and whole constellations, and a cheap pair of binoculars will show you the craters of the Moon. The telescope can wait a year.\nThe real enemy of stargazing isn't equipment at all — it's light. Streetlamps, car parks, your neighbour's security light. If you can get even twenty minutes outside town, the sky you'll see is astonishing compared with the one above your garden. And here's the part nobody tells beginners: your eyes need at least twenty minutes in darkness before they work properly at night. One glance at a phone screen and you're back to the beginning, so put the phone face-down in your pocket and leave it there.\nWhen should you go out? People assume winter is best because the nights are long, but honestly the thing that matters far more is the Moon. A full moon washes out everything around it, so plan your sessions for the nights when the Moon is new or below the horizon, whatever the season.\nFinally, when you do feel ready for a telescope, don't guess. Our local astronomy club runs open evenings on the first Friday of every month where you can look through six or seven different instruments and ask their owners what they'd buy again. One evening there will teach you more than any catalogue. Leaflets are by the door.",
    questions: [
      { q: "What is the speaker's main advice about equipment?", options: ["Buy the largest telescope you can afford.", "Delay buying a telescope until later.", "Borrow equipment rather than buying it.", "Always buy from a specialist shop."], answer: 1, explanation: "He says almost every beginner's telescope 'ends up in a cupboard by February' and that 'the telescope can wait a year'." },
      { q: "What does the speaker call the real enemy of stargazing?", options: ["Cloudy weather.", "Cheap binoculars.", "Artificial light.", "Cold winter nights."], answer: 2, explanation: "He says the real enemy 'isn't equipment at all - it's light': streetlamps, car parks and security lights." },
      { q: "Why should stargazers avoid looking at their phones?", options: ["The screen destroys their night vision.", "The apps give inaccurate star maps.", "The light disturbs other observers.", "Cold weather damages the battery."], answer: 0, explanation: "Eyes need at least twenty minutes in darkness, and 'one glance at a phone screen and you're back to the beginning'." },
      { q: "According to the speaker, what matters most when planning a session?", options: ["Choosing a winter month.", "The length of the night.", "The phase of the Moon.", "The direction of the wind."], answer: 2, explanation: "He says the Moon 'matters far more' than the season: a full moon washes everything out, so choose nights when the Moon is new or below the horizon." },
      { q: "Why does the speaker recommend the astronomy club's open evenings?", options: ["Members sell second-hand telescopes cheaply.", "Visitors can try different telescopes before buying.", "The club offers free membership to beginners.", "The evenings include a course on photography."], answer: 1, explanation: "At the open evenings 'you can look through six or seven different instruments and ask their owners what they'd buy again'." }
    ] },
  { id: "f-lis4-03", title: "Deciding on the Class Trip", kind: "dialogue",
    script: "Maya: Right, Josh, Miss Carter wants our recommendation for the class trip by Friday, so we need to actually decide. We've got three options left: the theme park, the science museum, or the coastal study centre.\nJosh: Well, I ran that survey you suggested. Twenty-three people answered, and I'll be honest — the theme park won easily. Fourteen votes.\nMaya: I knew it would. But did you see the coach quote? It's nearly twice our budget just to get there, before we've even bought a single ticket. It's a hundred and forty kilometres away, Josh.\nJosh: Yeah, the money kills it. Which is a shame, because now whatever we pick, most of the class starts off disappointed.\nMaya: There's also the thing Miss Carter said, remember? Whatever we choose has to connect to something we're studying this term, or the head won't approve the day off timetable.\nJosh: Which the theme park was never going to pass anyway, unless screaming counts as physics. So, museum or coast?\nMaya: Here's my thinking. The museum is fine, but half of us went there in primary school. The coastal centre does the rocky shore session in the morning — that lines up perfectly with the ecosystems unit — and then the afternoon is free time on the beach and the cliff walk. It's studying and a day out.\nJosh: And it's forty minutes away, so the coach cost basically disappears. Okay, you've convinced me. But if we just announce it, the theme park fourteen will revolt.\nMaya: So we don't announce it. We put both remaining options up on Thursday with the real costs next to each one, let the class vote, and let the numbers do the arguing.\nJosh: Deal. I'll do the cost sheet tonight and you talk to Miss Carter tomorrow.",
    questions: [
      { q: "Why is the theme park no longer a realistic option?", options: ["Most students voted against it.", "Transport would cost far too much.", "Miss Carter has banned theme parks.", "It is closed during term time."], answer: 1, explanation: "Maya says the coach quote is 'nearly twice our budget just to get there', because the park is 140 kilometres away." },
      { q: "What condition did Miss Carter set for the trip?", options: ["It must be within forty minutes of school.", "It must relate to their current studies.", "It must cost less than last year's trip.", "It must be approved by a class vote."], answer: 1, explanation: "Maya reminds Josh the trip 'has to connect to something we're studying this term, or the head won't approve the day off timetable'." },
      { q: "What did Josh's survey reveal?", options: ["The class was evenly split.", "The theme park was clearly the favourite.", "The museum was the most popular choice.", "Most students didn't want a trip at all."], answer: 1, explanation: "Josh says twenty-three people answered and 'the theme park won easily' with fourteen votes." },
      { q: "Why does Maya prefer the coastal centre to the museum?", options: ["It combines coursework with free time.", "It is cheaper to enter than the museum.", "The museum is too far away.", "The class visited the coast last year."], answer: 0, explanation: "The morning rocky shore session 'lines up perfectly with the ecosystems unit' and the afternoon offers beach free time - 'studying and a day out'; the museum was already visited in primary school." },
      { q: "How do Maya and Josh plan to handle the final decision?", options: ["Ask Miss Carter to choose for the class.", "Announce the coastal centre immediately.", "Hold a class vote with the costs displayed.", "Give the theme park voters a separate trip."], answer: 2, explanation: "Maya says they'll put both options up 'with the real costs next to each one, let the class vote, and let the numbers do the arguing'." }
    ] },
  { id: "f-lis4-04", title: "My Weekend Backstage at the Festival", kind: "monologue",
    script: "So last month I spent three days working at the Greenvale music festival, and before you're impressed, I should explain how it happened. Tickets were ninety pounds, which I simply didn't have, but the festival runs a volunteer scheme: three six-hour shifts in exchange for free entry and meals. I applied thinking I'd be handing out wristbands near a stage, soaking up the music while I worked.\nInstead, the confirmation email said: lost property tent. I won't pretend I wasn't gutted. The lost property tent is about as far from the main stage as you can get without leaving the site, and I spent the first hour of my first shift sulking behind a table of abandoned raincoats.\nThen the people started arriving, and honestly, it became the best seat at the festival. A man came in at midnight looking for one wellington boot — just the left one. A woman had lost her engagement ring and cried on my shoulder for ten minutes, and when we found it inside a glove in the wrong box, she cried for ten more. You hear a hundred little stories a day in that tent, and by Sunday I knew I'd been luckier than the wristband people.\nThe genuinely hard part wasn't the work itself, it was the shifts. Six hours is a long time on your feet on a floor of wooden boards, and my trainers were completely wrong for it. Which leads to my one piece of advice if you're thinking of volunteering next summer: never mind the waterproof jacket everyone tells you to pack — spend the money on proper boots instead. Your feet do the volunteering; the rest of you is just there to keep them company. I've already signed up for next year, same tent, by request.",
    questions: [
      { q: "Why did the speaker volunteer at the festival?", options: ["She could not afford a ticket.", "She wanted experience for her CV.", "A friend persuaded her to apply.", "She hoped to meet the performers."], answer: 0, explanation: "Tickets were ninety pounds, 'which I simply didn't have', so she volunteered in exchange for free entry and meals." },
      { q: "How did she feel when she learned her assignment?", options: ["Relieved it wasn't a harder job.", "Disappointed with the role she was given.", "Excited to be near the main stage.", "Confused about what the job involved."], answer: 1, explanation: "She 'won't pretend I wasn't gutted' about the lost property tent and spent her first hour 'sulking behind a table of abandoned raincoats'." },
      { q: "What changed her opinion of the lost property tent?", options: ["She was moved closer to the music.", "The stories of the people who came in.", "The shifts were shortened to four hours.", "She was allowed to keep unclaimed items."], answer: 1, explanation: "She says 'you hear a hundred little stories a day in that tent', like the man with one boot and the woman's found ring, and it became 'the best seat at the festival'." },
      { q: "What did she find hardest about volunteering?", options: ["Dealing with upset visitors.", "Working late at night.", "Standing for six hours at a time.", "The poor quality of the meals."], answer: 2, explanation: "The hard part was the shifts: 'six hours is a long time on your feet on a floor of wooden boards', made worse by the wrong shoes." },
      { q: "What advice does she give future volunteers?", options: ["Pack a good waterproof jacket.", "Request a shift near the main stage.", "Invest in suitable footwear.", "Volunteer with a friend for company."], answer: 2, explanation: "She says to skip the waterproof jacket and 'spend the money on proper boots instead', because 'your feet do the volunteering'." }
    ] },
  { id: "f-lis4-05", title: "Taking the Headphones Back", kind: "dialogue",
    script: "Assistant: Good morning. How can I help?\nLeo: Hi. I bought these headphones here about three weeks ago, and the left ear has started crackling. It comes and goes, but once you've noticed it, it's all you can hear.\nAssistant: Ah, that's annoying. Let me plug them into our test unit... yes, I can hear it. There's definitely a fault in the left driver. Do you have your receipt?\nLeo: That's the thing — I've looked everywhere and I can't find it. I paid by card, though, and I've got the payment showing on my banking app, with the shop name and the date. Is that any good?\nAssistant: That's fine, actually. A bank statement counts as proof of purchase, as long as I can match the amount, and I can see it's the right price there. So, you've got three options. We can send them for repair, but I'll be honest, that's running at about two weeks at the moment.\nLeo: Two weeks is a problem. I'm flying to Canada on Monday and I bought them for the flight in the first place.\nAssistant: Understood. Second option is a straight replacement, but that colour is out of stock — the delivery's due Friday morning. Or third, a full refund today.\nLeo: Hmm. I do actually like them when they work. If the delivery comes Friday, could I pick a replacement up that afternoon?\nAssistant: You could, or — better — I can have the new pair couriered to your home on Friday, free of charge, and you hand these ones to the courier. Then you're not making a second trip before your flight.\nLeo: That's perfect. Let's do that.\nAssistant: Great. I'll set that up now and you'll get a text with the delivery slot on Thursday evening.",
    questions: [
      { q: "What is wrong with Leo's headphones?", options: ["The right ear has stopped working.", "One side makes a crackling sound.", "They no longer connect to his phone.", "The battery runs out too quickly."], answer: 1, explanation: "Leo says 'the left ear has started crackling', and the assistant confirms a fault in the left driver on the test unit." },
      { q: "How does Leo prove he bought the headphones at the shop?", options: ["He shows the payment on his banking app.", "He presents the original receipt.", "He shows the box with the shop's label.", "The assistant remembers serving him."], answer: 0, explanation: "He cannot find the receipt but shows the card payment in his banking app, which the assistant accepts as proof of purchase." },
      { q: "Why does Leo reject the repair option?", options: ["It would not be free of charge.", "He no longer trusts the brand.", "It would take too long before his trip.", "The shop cannot repair that model."], answer: 2, explanation: "Repairs take 'about two weeks' and Leo is 'flying to Canada on Monday' - he bought the headphones for the flight." },
      { q: "Why can't Leo take a replacement pair home immediately?", options: ["The replacement costs more than he paid.", "That model is out of stock until Friday.", "The manager must approve the exchange.", "Replacements are only sent by post."], answer: 1, explanation: "The assistant says that colour is 'out of stock - the delivery's due Friday morning'." },
      { q: "What arrangement do they finally agree on?", options: ["Leo will collect the new pair on Friday afternoon.", "Leo accepts a full refund today.", "A new pair will be delivered to Leo's home.", "The faulty pair will be posted for repair."], answer: 2, explanation: "The assistant offers to have the new pair 'couriered to your home on Friday, free of charge', with the faulty pair handed to the courier, and Leo agrees." }
    ] },
  { id: "f-lis4-06", title: "Podcast: Why Teenagers Can't Wake Up", kind: "monologue",
    script: "Welcome back to Body Clock, the show about the science of everyday life. I'm Dr Sam Reyes, and today we're tackling a question every parent has shouted up the stairs: why can't teenagers get out of bed?\nHere's the first thing to understand: it isn't laziness. During adolescence, the body's internal clock genuinely shifts later, by around two hours. The hormone that makes you sleepy is simply released later in the evening, so a teenager told to sleep at ten is being asked to do something their biology is actively resisting. They're not being difficult; they're being sixteen. The tiredness is real, though — most teenagers need nine hours and are running on seven.\nNow, the tempting fix is the weekend lie-in, and here's the uncomfortable news: it backfires. Sleeping until noon on Sunday drags your body clock even later — scientists call it social jetlag — and it makes Monday morning feel like stepping off a long-haul flight. The catching-up actually deepens the problem you're trying to solve.\nWhat about naps? Fine, with one rule: keep them under half an hour. A twenty-minute nap after school is refreshing. A two-hour nap steals sleep from that night and pushes the whole cycle later still.\nSo what actually helps? If you change just one thing, make it this: get up at the same time every day, weekends included, give or take an hour. A steady wake-up time anchors the entire clock. And pair it with light — ten minutes of bright morning light, ideally outdoors, tells your brain the day has started and pulls tonight's sleepiness earlier. Curtains open, breakfast by the window, walk to school if you can.\nNext week: why you always wake up just before your alarm. Until then, sleep well.",
    questions: [
      { q: "What is the speaker's main point about teenage sleep patterns?", options: ["They are caused by a biological change, not laziness.", "They result from too much evening screen time.", "They show teenagers need less sleep than adults.", "They can be cured by earlier bedtimes."], answer: 0, explanation: "He says 'it isn't laziness' - during adolescence the internal clock 'genuinely shifts later, by around two hours'." },
      { q: "What does the speaker say about weekend lie-ins?", options: ["They help repay lost sleep from the week.", "They make the underlying problem worse.", "They are only harmful for younger children.", "They should be limited to one hour."], answer: 1, explanation: "He says the lie-in 'backfires': it drags the body clock later, causing 'social jetlag' and deepening the problem." },
      { q: "What rule does the speaker give about naps?", options: ["Take them only at weekends.", "Avoid them completely after school.", "Keep them shorter than thirty minutes.", "Take them just before studying."], answer: 2, explanation: "Naps are fine 'with one rule: keep them under half an hour' - a two-hour nap steals sleep from the night." },
      { q: "According to the speaker, what single change helps most?", options: ["Going to bed at exactly the same time.", "Waking at a consistent time every day.", "Drinking nothing after eight in the evening.", "Doing exercise late in the afternoon."], answer: 1, explanation: "He says if you change one thing, 'get up at the same time every day, weekends included' - a steady wake-up time anchors the clock." },
      { q: "Why does the speaker recommend morning light?", options: ["It signals the brain to start the day earlier.", "It provides vitamins that improve sleep.", "It replaces the need for an alarm clock.", "It makes breakfast more enjoyable."], answer: 0, explanation: "Ten minutes of bright morning light 'tells your brain the day has started and pulls tonight's sleepiness earlier'." }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
