(function () {
var BANK = [
  { id: "f-lis1-01", title: "Radio Interview: The Teenage App Developer", kind: "dialogue",
    script: "Interviewer: Good morning, everyone. Today I'm delighted to welcome Maya Torres, who's just seventeen and has already launched an app that's been downloaded over half a million times. Maya, welcome to the show.\nMaya: Thanks for having me. It's a bit surreal, to be honest.\nInterviewer: So tell us, how did StudyBuddy come about?\nMaya: Well, it started as a school project, actually. Our computing teacher asked us to design something useful, and I kept forgetting my homework deadlines, so I thought, you know, why not build a reminder app that actually understands a school timetable? Most calendar apps are made for office workers, not students.\nInterviewer: And it took off from there?\nMaya: Not immediately, no. The first version was honestly terrible. It crashed constantly. My classmates tested it and, well, they weren't shy about telling me what was wrong. That feedback was painful but it was the most valuable thing I got.\nInterviewer: A lot of people assume you must have coded since you were tiny.\nMaya: That's what everyone thinks, but no, I only started coding two years ago. I learned mostly from free videos online. What I did have was patience — I'd spend whole weekends fixing one tiny bug.\nInterviewer: And now companies are approaching you. Are you tempted to sell?\nMaya: I've had offers, and my parents think I should take one, but I'm not ready. It's not really about the money for me. I want to finish school first and keep the app free for students. Maybe later, who knows.\nInterviewer: Wise words. Finally, any advice for young listeners?\nMaya: Just start something small and expect it to fail the first time. Honestly, the failing part is where you learn everything.",
    questions: [
      { q: "Why did Maya originally create the app?", options: ["It was part of a school assignment.", "A company asked her to design it.", "Her teacher kept forgetting deadlines.", "She wanted to earn money for university."], answer: 0, explanation: "Maya 說「it started as a school project」，是電腦老師出的作業，因此答案是學校作業，而非公司邀請或賺錢。" },
      { q: "What does Maya say about the first version of the app?", options: ["It was an instant success.", "It had serious technical problems.", "Her classmates refused to test it.", "It was designed for office workers."], answer: 1, explanation: "她說「The first version was honestly terrible. It crashed constantly」，表示初版有嚴重技術問題；office workers 是干擾項。" },
      { q: "How did Maya learn to code?", options: ["From lessons she took as a small child.", "From a weekend course at school.", "From free online videos.", "From her parents, who are programmers."], answer: 2, explanation: "Maya 說「I only started coding two years ago. I learned mostly from free videos online」，可知她靠免費線上影片自學。" },
      { q: "How does Maya feel about selling the app?", options: ["She has already accepted an offer.", "She agrees with her parents' opinion.", "She refuses to ever sell it.", "She prefers to wait until later."], answer: 3, explanation: "她說「I'm not ready... Maybe later, who knows」，表示目前不賣但未來未定，不是永遠拒絕，也沒接受任何報價。" },
      { q: "What is Maya's main advice to young listeners?", options: ["Spend money on proper training first.", "Begin with something small and learn from failure.", "Avoid projects that might fail.", "Ask companies for support early on."], answer: 1, explanation: "結尾她說「start something small and expect it to fail... the failing part is where you learn everything」，強調從小處著手並從失敗中學習。" }
    ] },
  { id: "f-lis1-02", title: "My Homestay Year in Osaka", kind: "monologue",
    script: "So, people keep asking me about my homestay year in Japan, and honestly, it's hard to sum up. I was sixteen when I arrived in Osaka, and I remember standing at the airport thinking, what on earth have I done? I'd studied Japanese for two years at school, but the moment my host mother spoke to me, I understood basically nothing. She spoke so fast, and with a local accent that wasn't in any of my textbooks.\nThe family was lovely, though. There was the mum, Keiko, the dad, who worked long hours so I mostly saw him at weekends, and two younger kids who treated me like a new toy, to be honest. The first month was the hardest — not because of the language, actually, but the food. I know everyone imagines sushi every day, but it was more like grilled fish for breakfast, which, well, took some getting used to. Now I actually miss it, funnily enough.\nSchool was another shock. I had to wear a uniform for the first time in my life, and students clean their own classrooms there — no cleaners. At first I thought that was strange, but I came to see the point of it. You respect a place more when you look after it yourself.\nIf I had to pick the most valuable thing, it wouldn't be the language, even though my Japanese did improve massively. It would be learning to be comfortable when everything around you is unfamiliar. Before the trip I was quite a nervous person, you know, someone who needed a plan for everything. Now I sort of trust that I'll cope. My advice? Say yes to everything your host family suggests, even the weird stuff. Especially the weird stuff, actually.",
    questions: [
      { q: "How did the speaker feel when she first arrived in Osaka?", options: ["Confident because of her language studies.", "Doubtful about her decision to come.", "Excited to meet her host family.", "Annoyed by the long journey."], answer: 1, explanation: "她說「I remember standing at the airport thinking, what on earth have I done?」，顯示她懷疑自己的決定。" },
      { q: "Why couldn't she understand her host mother at first?", options: ["She had never studied Japanese before.", "Her host mother refused to speak slowly.", "The accent and speed were unfamiliar.", "Her textbooks were written in English."], answer: 2, explanation: "她說 host mother「spoke so fast, and with a local accent that wasn't in any of my textbooks」，語速和口音是關鍵原因。" },
      { q: "What was the most difficult part of the first month?", options: ["Getting used to the food.", "Communicating in Japanese.", "Missing her own family.", "The father's long working hours."], answer: 0, explanation: "她明說「The first month was the hardest — not because of the language, actually, but the food」，因此是飲食問題，語言是干擾項。" },
      { q: "What does she now think about students cleaning classrooms?", options: ["It should be done by professional cleaners.", "It is a strange custom she never accepted.", "It teaches respect for the place.", "It made the uniform rule unnecessary."], answer: 2, explanation: "她說「I came to see the point of it. You respect a place more when you look after it yourself」，表示她理解並認同這個做法。" },
      { q: "According to the speaker, what was the most valuable result of the year?", options: ["Her big improvement in Japanese.", "Learning to cope with unfamiliar situations.", "Making friends with the host children.", "Discovering new foods she loved."], answer: 1, explanation: "她說最有價值的「wouldn't be the language... It would be learning to be comfortable when everything around you is unfamiliar」，語言進步是干擾項。" }
    ] },
  { id: "f-lis1-03", title: "Planning Dad's Surprise Party", kind: "dialogue",
    script: "Jess: Right, so Dad's fiftieth is in three weeks and we still haven't sorted anything. Tom, please tell me you've at least thought about a venue.\nTom: Well, I did look at that Italian place he likes, but honestly, it's tiny. If we invite all his golf friends plus the family, we're talking forty people, easily.\nJess: Forty? I was thinking more like twenty-five. You know Dad, he hates big crowds. Remember his birthday two years ago? He spent half the evening hiding in the kitchen.\nTom: Fair point. Okay, twenty-five it is. So what about having it at home, then? We could do the garden, put up some lights.\nJess: In March? It'll be freezing. And if it rains, we're finished.\nTom: Hmm, true. What about the golf club itself? They've got that function room, and he'd never suspect a thing because he's there every Saturday anyway.\nJess: Oh, that's actually clever. And Mum could get him there without any excuse needed. I'll ring them tomorrow about prices.\nTom: Great. Now, the cake. I was going to order one shaped like a golf ball, but they want eighty pounds. Eighty!\nJess: That's ridiculous. Look, Aunt Carol bakes brilliantly, and she'd be offended if we didn't ask her, honestly. She did Grandma's cake and everyone raved about it.\nTom: Fine, you ask her though — she still hasn't forgiven me for missing her concert.\nJess: Coward. Okay, last thing: keeping it secret. Dad reads Mum's messages over her shoulder, like, constantly. So no details in the family chat, agreed?\nTom: Agreed. We'll set up a separate group without them. And I'll tell everyone the fake story — that we're just having a quiet dinner.\nJess: Perfect. Honestly, if we pull this off, it'll be a miracle.",
    questions: [
      { q: "What is the problem with the Italian restaurant?", options: ["Their father doesn't like the food there.", "It is too small for the guests.", "It is fully booked in three weeks.", "It is too far from the golf club."], answer: 1, explanation: "Tom 說「it's tiny. If we invite all his golf friends plus the family, we're talking forty people」，場地太小是問題。" },
      { q: "Why does Jess want a smaller guest list?", options: ["Their father dislikes big crowds.", "It will cost too much money.", "The kitchen at home is too small.", "Most golf friends can't come."], answer: 0, explanation: "Jess 說「You know Dad, he hates big crowds」並提到爸爸曾躲在廚房，所以她想縮小人數。" },
      { q: "Why does Jess reject the idea of a garden party?", options: ["The neighbours would complain.", "Their father would suspect something.", "The weather in March is a risk.", "They don't have enough lights."], answer: 2, explanation: "Jess 說「In March? It'll be freezing. And if it rains, we're finished」，是天氣風險的問題。" },
      { q: "Why do they decide the golf club is a good venue?", options: ["It offers the cheapest function room.", "Their father won't find it suspicious.", "Aunt Carol works there at weekends.", "It can hold forty guests easily."], answer: 1, explanation: "Tom 說「he'd never suspect a thing because he's there every Saturday anyway」，重點是爸爸不會起疑。" },
      { q: "What do Jess and Tom agree about at the end?", options: ["To order the golf ball cake anyway.", "To announce the party in the family chat.", "To let their mother organise the secret.", "To use a separate chat group for the plan."], answer: 3, explanation: "兩人同意「no details in the family chat」並「set up a separate group without them」，即另開群組保密。" }
    ] },
  { id: "f-lis1-04", title: "Welcome to Harwick Castle", kind: "monologue",
    script: "Good morning, everyone, and welcome to Harwick Castle. My name's Derek, and I'll be your guide for the next ninety minutes. Before we set off, just a few things, so, well, bear with me.\nFirst, the practical stuff. The tour covers the great hall, the tower, and the underground kitchens. I should warn you now, the tower involves a hundred and twenty steps up a narrow spiral staircase, so if anyone would rather skip that part, there's a lovely café at the base where you can wait — and honestly, their scones alone are worth the visit.\nNow, a quick word on photography. You're welcome to take pictures almost everywhere, but not in the portrait gallery, I'm afraid. It's not us being difficult — the flash genuinely damages the paintings, some of which are over four hundred years old. Outside in the gardens, snap away as much as you like.\nA little history before we go in. People often assume the castle was built for a king, but actually it was built by a wool merchant, believe it or not, back in the fourteenth century. Wool was like the oil of its day — enormous money in it. The royal connection came later, when Queen Isabella stayed here for one single night in 1502, and, well, the family never stopped talking about it. You'll see the so-called Queen's Room upstairs, which, between you and me, she probably never even slept in.\nOne last thing — the floors. They're original stone, seven centuries old, and they get slippery, especially near the kitchens where it's damp. So please, no running, and hold the handrails on the stairs. We lost a visitor's phone down a well last month; let's not lose a visitor.\nRight then, if everyone's ready, follow me through the main gate, and mind the step.",
    questions: [
      { q: "What is the purpose of the guide's opening remarks?", options: ["To explain the castle's ticket prices.", "To give practical information before the tour.", "To advertise the castle's gift shop.", "To describe the full history of the region."], answer: 1, explanation: "Derek 一開始說「Before we set off, just a few things」，接著講樓梯、拍照等注意事項，屬於行前實用說明。" },
      { q: "What does Derek suggest for people who don't want to climb the tower?", options: ["Waiting in the café at the base.", "Visiting the underground kitchens instead.", "Taking a lift to the top.", "Joining a shorter tour group."], answer: 0, explanation: "他說「if anyone would rather skip that part, there's a lovely café at the base where you can wait」，可在塔下咖啡廳等候。" },
      { q: "Why is photography banned in the portrait gallery?", options: ["The gallery is private property.", "Visitors block the narrow corridors.", "Flash can harm the old paintings.", "The paintings are being restored."], answer: 2, explanation: "Derek 解釋「the flash genuinely damages the paintings, some of which are over four hundred years old」，是閃光燈傷害畫作。" },
      { q: "What does Derek say about the castle's origins?", options: ["It was built as a royal palace.", "It was constructed by a rich merchant.", "It was a gift from Queen Isabella.", "It was originally a wool warehouse."], answer: 1, explanation: "他說「actually it was built by a wool merchant」，並指出大家常誤以為是為國王而建，王室僅是後來的關聯。" },
      { q: "What is Derek's attitude towards the story of the Queen's Room?", options: ["He is doubtful that the queen slept there.", "He is proud of the royal visit.", "He is certain the story is true.", "He is annoyed that visitors ask about it."], answer: 0, explanation: "他說「between you and me, she probably never even slept in」，語氣帶懷疑，認為女王可能根本沒睡過那房間。" }
    ] },
  { id: "f-lis1-05", title: "Podcast: Why Your Houseplants Keep Dying", kind: "monologue",
    script: "Hello and welcome back to Green Fingers, the podcast for people who love plants but, let's be honest, keep killing them. I'm Priya, and today we're tackling the number one question in my inbox: why do my houseplants keep dying?\nSo, here's the thing that surprises everyone. The most common cause of death isn't neglect — it's love. Or rather, too much of it. People water their plants every single day, thinking they're being kind, and the poor roots basically drown. Most houseplants want the soil to dry out a bit between waterings. My rule? Stick your finger two centimetres into the soil. If it's dry, water. If it's damp, walk away. Seriously, just walk away.\nNumber two on the killer list is light — or the wrong idea about it. People see the phrase low-light plant on a label and think, brilliant, that dark corner of my hallway will do. But low light doesn't mean no light. No plant survives in genuine darkness; they're not furniture. What that label really means is the plant tolerates less light than most, not that it enjoys it.\nAnd then there's the repotting panic. Someone buys a plant, gets home, and immediately moves it into a bigger, prettier pot. Well, here's the thing — moving house is stressful for plants too. A new plant is already adjusting to your home's temperature and humidity. Give it a month or so to settle before you disturb the roots.\nOne last myth to bust before we go: misting. Spraying water on the leaves feels very professional, doesn't it? But for most plants the effect lasts about twenty minutes and does, well, pretty much nothing. If your plant genuinely needs humidity, group it with other plants or use a tray of wet pebbles instead.\nRight, next week we're talking about herbs on windowsills. Until then, water less, worry less.",
    questions: [
      { q: "What is the main topic of this podcast episode?", options: ["How to choose plants for dark rooms.", "Why houseplants often die at home.", "How to grow herbs on windowsills.", "The best pots for new plants."], answer: 1, explanation: "Priya 開頭說本集回答「why do my houseplants keep dying?」，即家中植物為何一直死掉；香草是下週主題。" },
      { q: "According to Priya, what is the most common way people kill their plants?", options: ["Forgetting to water them for weeks.", "Keeping them in cold hallways.", "Giving them water too often.", "Using the wrong type of soil."], answer: 2, explanation: "她說「People water their plants every single day... and the poor roots basically drown」，澆水太頻繁才是主因，忽略是干擾項。" },
      { q: "What does the label \"low-light plant\" actually mean?", options: ["The plant can survive in total darkness.", "The plant tolerates less light than most.", "The plant should be kept in a hallway.", "The plant needs direct sunlight daily."], answer: 1, explanation: "她說「What that label really means is the plant tolerates less light than most, not that it enjoys it」，並強調沒有植物能活在全黑處。" },
      { q: "What does Priya advise about repotting a new plant?", options: ["Wait about a month before repotting.", "Repot it immediately into a bigger pot.", "Never move it from its original pot.", "Repot it only in the summer."], answer: 0, explanation: "她說「Give it a month or so to settle before you disturb the roots」，建議約一個月後再換盆。" },
      { q: "What is Priya's opinion of misting plants?", options: ["It is the best way to raise humidity.", "It should be done twice a day.", "It works well for most houseplants.", "It has almost no real effect."], answer: 3, explanation: "她說噴霧的效果「lasts about twenty minutes and does... pretty much nothing」，認為幾乎沒有實際作用。" }
    ] },
  { id: "f-lis1-06", title: "At the Bike Shop: A Repair Gone Complicated", kind: "dialogue",
    script: "Owner: Morning! Ah, you're here about the blue road bike, right? Come through.\nCustomer: That's me. Your message said there was, um, a complication?\nOwner: Yeah, sorry about that. So, you brought it in for the gears slipping, and that part's straightforward — the cable's stretched, we can sort that today, no problem. But while my apprentice had it on the stand, he spotted a crack in the frame, just under the seat. Small, but it's there.\nCustomer: A crack? Seriously? I only bought it two years ago.\nOwner: I know, and look, it's not your fault. That model had a known issue with that exact spot. To be fair to the maker, they extended the warranty on the frame to five years because of it. Most people never heard about that, mind you.\nCustomer: So, wait — you're saying it might be covered?\nOwner: That's what I'm saying. If you've still got your proof of purchase, I can send the photos off to the distributor today. Usually takes about two weeks, and if they approve it, you get a brand-new frame for nothing.\nCustomer: Two weeks without a bike, though. I cycle to work every day, that's the thing.\nOwner: Hmm. Well, we do have loan bikes. Nothing fancy — an old commuter, bit heavy — but it'll get you to work. Ten pounds a week, and honestly I'll knock that off your final bill anyway.\nCustomer: Oh, that changes things. Okay, let's do it. Should I email you the receipt this afternoon?\nOwner: Perfect. And I'll still fix the gears today so the loan period starts tomorrow, if that suits.\nCustomer: Great. You know, I nearly took it to that big chain store by the station instead.\nOwner: Ha! Well, I'm glad you didn't — they'd have fixed the gears and sent you off riding a cracked frame. Right, let me grab the paperwork.",
    questions: [
      { q: "Why did the customer originally bring the bike to the shop?", options: ["The frame had a visible crack.", "The gears were not working properly.", "The brakes needed replacing.", "It needed a full yearly service."], answer: 1, explanation: "店主說「you brought it in for the gears slipping」，原本是為了變速器滑齒的問題，裂痕是後來才發現的。" },
      { q: "Who discovered the crack in the frame?", options: ["The customer noticed it while cycling.", "The shop owner saw it at first glance.", "The apprentice found it during the check.", "The distributor reported the fault."], answer: 2, explanation: "店主說「while my apprentice had it on the stand, he spotted a crack in the frame」，是學徒在檢查時發現的。" },
      { q: "Why might the repair be free for the customer?", options: ["The maker extended the frame warranty.", "The shop caused the damage itself.", "The bike is less than one year old.", "The owner is offering a special discount."], answer: 0, explanation: "店主說該型號有已知問題，「they extended the warranty on the frame to five years」，所以可能由原廠保固支付。" },
      { q: "What is the customer's main worry about the warranty claim?", options: ["Finding the proof of purchase.", "The cost of the new frame.", "Being without a bike for two weeks.", "Sending photos to the distributor."], answer: 2, explanation: "顧客說「Two weeks without a bike, though. I cycle to work every day」，擔心兩週沒車可騎去上班。" },
      { q: "How is the problem of the waiting period solved?", options: ["The customer will use a loan bike.", "The repair will be finished the same day.", "The customer will take the bus to work.", "The chain store will lend a bicycle."], answer: 0, explanation: "店主提供「loan bikes... it'll get you to work」，顧客回答「Okay, let's do it」，同意借用代步車解決等待期問題。" }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
