(function () {
var BANK = [
  { id: "f-lis2-01", title: "A Day in the Life of a Beach Lifeguard", kind: "monologue",
    script: "People always assume being a lifeguard is glamorous, you know, like the TV shows — running along the sand in slow motion. The reality? My alarm goes off at half past five, and the first hour of my day is basically paperwork and equipment checks. Every morning we test the rescue boards, the radios, the first-aid kits, all of it, before a single swimmer arrives. It's boring, honestly, but if a radio fails during a rescue, someone could drown, so we never skip it.\nThe funny thing is, most people think our main job is pulling swimmers out of the water. Actually, ninety per cent of what I do is prevention. I spend hours just watching — reading the water, spotting rip currents, moving the flags when conditions change. If I've done my job well, nothing dramatic happens all day. A quiet shift is a successful shift, that's what my supervisor always says, and I've come to agree with her.\nThe hardest part isn't the physical side, believe it or not. I trained for months to pass the swim tests, but what really wears you out is the concentration. Try staring at moving water for four hours without letting your mind wander. Your eyes ache. We rotate positions every hour precisely because attention drops if you don't.\nAnd then there's dealing with the public. Last week a man argued with me for ten minutes because I asked him to swim between the flags. He said he'd been swimming here for thirty years. Well, fine, but the sandbank shifted last winter, and there's a rip current exactly where he wanted to swim. Most people are lovely, though, I should say.\nWould I recommend the job? Absolutely — but only if you can handle responsibility. When you're on that chair, every person in the water is, in a sense, yours to look after. That feeling never quite goes away, even on your day off.",
    questions: [
      { q: "What is the speaker's main purpose in this talk?", options: ["To describe what lifeguard work is really like.", "To explain how to pass the lifeguard swim tests.", "To warn swimmers about rip currents.", "To complain about a rude member of the public."], answer: 0, explanation: "開頭他就對比電視印象與現實「The reality? My alarm goes off at half past five...」，整段都在說明救生員工作的真實樣貌。" },
      { q: "Why does the speaker never skip the morning equipment checks?", options: ["His supervisor watches him do them.", "A faulty radio during a rescue could cost a life.", "Swimmers arrive very early at the beach.", "The paperwork must be finished by six."], answer: 1, explanation: "他說「if a radio fails during a rescue, someone could drown, so we never skip it」，設備故障可能致命。" },
      { q: "According to the speaker, what does most of his work involve?", options: ["Pulling swimmers out of the water.", "Running along the sand on patrol.", "Watching the water to prevent accidents.", "Repairing the rescue boards."], answer: 2, explanation: "他說「ninety per cent of what I do is prevention. I spend hours just watching」，主要工作是觀察與預防，救人反而是少數。" },
      { q: "What does the speaker find most tiring about the job?", options: ["The demanding physical training.", "Rotating positions every hour.", "The long early-morning shifts.", "Keeping his concentration on the water."], answer: 3, explanation: "他說「what really wears you out is the concentration. Try staring at moving water for four hours」，最累的是持續專注，體能反而不是重點。" },
      { q: "What is the speaker's attitude towards the man who argued with him?", options: ["He thinks experience does not remove the danger.", "He accepts the man knew the beach better.", "He believes most beach visitors behave like him.", "He regrets moving the flags that day."], answer: 0, explanation: "他說「Well, fine, but the sandbank shifted last winter, and there's a rip current exactly where he wanted to swim」，表示三十年經驗也擋不住新的危險。" }
    ] },
  { id: "f-lis2-02", title: "Choosing a Science Fair Project", kind: "dialogue",
    script: "Leo: Okay, Sara, the science fair sign-up closes on Friday, so we really need to pick something today. Any ideas?\nSara: Loads, actually. I was thinking we could build a small wind turbine and measure how blade shape affects the power output.\nLeo: Hmm, a turbine sounds impressive, but my cousin did one last year and said the 3D printing alone took three weeks. We've only got a month, and that's including writing everything up.\nSara: Fair enough. Okay, second idea: testing which natural materials filter dirty water best — sand, charcoal, gravel, that sort of thing.\nLeo: Oh, I like that. It's cheap, too. My worry is that half the school does water filters every single year. The judges must be so bored of them.\nSara: True, Mr. Okafor literally rolled his eyes when someone mentioned filters last term. Right, what about your ideas, then? I've done two, your turn.\nLeo: Well, don't laugh, but I've been reading about how music affects plant growth. We could grow three trays of cress — one with classical music, one with rock, one in silence — and measure them daily.\nSara: I'm not laughing, I just... hasn't that been sort of disproved? The judges love proper method more than a wow result, though. If we're careful about keeping light and water identical, even a boring result is good science.\nLeo: Exactly! A result of no difference is still a result. And cress grows in like a week, so we could actually run the whole experiment twice.\nSara: Repeating it twice would seriously impress Mr. Okafor. Okay, you've convinced me — cress it is. But I want to design the measuring system, because last time you eyeballed everything with a bent ruler.\nLeo: That's... painfully true. Deal. You handle measurements, I'll set up the speakers and the trays, and we'll both do the write-up.\nSara: Perfect. I'll grab the sign-up form at lunch tomorrow before the list fills up.",
    questions: [
      { q: "Why do they reject the wind turbine idea?", options: ["It would cost too much to build.", "The preparation would take too long.", "Sara's cousin already did it this year.", "The judges dislike engineering projects."], answer: 1, explanation: "Leo 說堂哥做過，「the 3D printing alone took three weeks. We've only got a month」，時間不夠是主因。" },
      { q: "What is Leo's objection to the water filter project?", options: ["Too many students have done it before.", "The materials are too expensive.", "It is too difficult to measure results.", "Dirty water is not allowed in school."], answer: 0, explanation: "Leo 說「half the school does water filters every single year. The judges must be so bored of them」，是題目太常見的問題，便宜反而是優點。" },
      { q: "What does Leo suggest they investigate?", options: ["How light affects the growth of cress.", "Whether plants can survive in silence.", "Whether music influences plant growth.", "How judges react to surprising results."], answer: 2, explanation: "Leo 提議「how music affects plant growth」，用三盤水芹分別放古典樂、搖滾樂與無聲對照。" },
      { q: "What does Sara say the judges value most?", options: ["A dramatic and surprising result.", "A carefully controlled method.", "Projects finished ahead of schedule.", "Experiments using living plants."], answer: 1, explanation: "Sara 說「The judges love proper method more than a wow result」，嚴謹的方法比驚人結果重要。" },
      { q: "What do Leo and Sara finally agree on?", options: ["Sara will set up the speakers and trays.", "Leo will design the measuring system.", "They will each write a separate report.", "Sara will manage measuring and Leo the set-up."], answer: 3, explanation: "結尾分工是 Sara 說「I want to design the measuring system」，Leo 回「You handle measurements, I'll set up the speakers and the trays」，報告則兩人合寫。" }
    ] },
  { id: "f-lis2-03", title: "Radio Feature: Inside the City's Lost-and-Found Office", kind: "monologue",
    script: "You're listening to City Stories, and today we're visiting a place most of you hope you'll never need: the central lost-and-found office at Riverside Station. I'm standing in a basement room the size of a tennis court, and every single shelf is full.\nMarta Klein has run this office for eleven years, and she tells me the numbers are staggering. Around two hundred items arrive every day. Phones and umbrellas top the list, obviously, but it's the strange things that stay with you. Last month alone: a wedding dress, a tuba, and, believe it or not, a full-sized garden gnome. Marta's personal favourite? A box containing a hand-written novel, six hundred pages, no name anywhere on it. She kept it aside for a year, hoping. Nobody ever came.\nNow, here's the part that genuinely surprised me. You'd expect maybe half of these things to find their way home. In fact, only about one item in five is ever claimed. And it's not the cheap stuff people abandon — expensive laptops sit here unclaimed for months. Marta reckons people simply assume anything valuable must have been stolen, so they never even ask. They buy a replacement instead, which she finds quietly heartbreaking.\nSo what happens to the rest? After three months, unclaimed clothing goes to homeless shelters, electronics are wiped and auctioned for charity, and, well, the gnome is still here, standing guard by the door. Staff have named him Gerald.\nIf you've lost something on the city's buses or trains, don't just give up. The office is open weekdays until six, and you can now search the catalogue online before you come in — a system Marta fought five years to get funded. Describe one detail that isn't visible in the photos, and it's yours again. As Marta puts it, the best part of this job isn't the objects. It's the faces of the people getting them back.",
    questions: [
      { q: "What is this radio feature mainly about?", options: ["How Riverside Station was built.", "The work of a lost-property office.", "A novel that was never published.", "How to avoid losing items on trains."], answer: 1, explanation: "開頭主持人說「today we're visiting... the central lost-and-found office at Riverside Station」，整篇介紹失物招領處的運作。" },
      { q: "Which items arrive at the office most often?", options: ["Phones and umbrellas.", "Laptops and cameras.", "Wedding dresses and instruments.", "Clothing and garden ornaments."], answer: 0, explanation: "Marta 提到「Phones and umbrellas top the list, obviously」，手機和雨傘數量最多，其餘是奇特案例。" },
      { q: "What surprised the reporter most about the office?", options: ["How large the basement storage room is.", "That two hundred items arrive daily.", "How few items are ever claimed.", "That a novel was left with no name."], answer: 2, explanation: "他說「here's the part that genuinely surprised me... only about one item in five is ever claimed」，認領率之低最令他意外。" },
      { q: "Why does Marta think valuable items often go unclaimed?", options: ["Owners assume they were stolen.", "The owners cannot afford the claim fee.", "Electronics are wiped after one month.", "People prefer newer replacements anyway."], answer: 0, explanation: "Marta 認為「people simply assume anything valuable must have been stolen, so they never even ask」，失主以為被偷所以不來詢問。" },
      { q: "What does Marta say is the best part of her job?", options: ["Discovering unusual objects on the shelves.", "Running the online catalogue she funded.", "Sending old clothing to shelters.", "Seeing people's reactions when items return."], answer: 3, explanation: "結尾引用她的話「the best part of this job isn't the objects. It's the faces of the people getting them back」，重點是物歸原主時人們的表情。" }
    ] },
  { id: "f-lis2-04", title: "Interviewing Uncle Ray About His Food Truck", kind: "dialogue",
    script: "Nina: Okay, Uncle Ray, this is for my school careers project, so pretend I'm a proper journalist. First question: why did you leave your restaurant job to start a food truck?\nRay: Ha, straight in with the big one. Well, everyone assumed it was about being my own boss, but honestly? It was the menu. At the restaurant I cooked the same twelve dishes for nine years. With the truck, if I invent something on Tuesday, I'm selling it on Wednesday. That freedom, that's what I couldn't get anywhere else.\nNina: Was the beginning as fun as it sounds?\nRay: Oh, it was a disaster, love. My first week, I parked outside the football stadium thinking, easy crowds, right? Turned out you need a special permit for that whole street, and I got fined before I'd sold a single taco. First lesson: the cooking is maybe half the job. The rest is permits, parking rules, insurance, all the boring paper stuff nobody warns you about.\nNina: So how did you find your regular spot by the river?\nRay: Pure luck, actually. My engine broke down there one lunchtime, and while I waited for the mechanic, office workers kept knocking on the window asking if I was open. I did a full day's takings without moving an inch. I've been back every weekday since.\nNina: What's the hardest part now, after four years?\nRay: People guess the early mornings, but I'm a morning person, always have been. It's the weather, no question. One rainy week in November and your income just vanishes. You can be the best cook in the city — nobody queues outside in a storm.\nNina: Last question. Mum says you work twice the hours for half the money. Is she right?\nRay: Your mum exaggerates... but only a little. The hours part is true, I won't pretend otherwise. The money's actually better than the restaurant now, though it took three years to get there. Would I go back? Not for anything. Put that in your project — in capital letters.",
    questions: [
      { q: "Why did Ray really leave his restaurant job?", options: ["He wanted the freedom to change his menu.", "He wanted to become his own boss.", "He was tired of working nine years for low pay.", "He was offered a truck by a friend."], answer: 0, explanation: "Ray 說大家以為是想當老闆，「but honestly? It was the menu... That freedom, that's what I couldn't get anywhere else」，重點是菜單自由。" },
      { q: "What went wrong in Ray's first week?", options: ["His tacos failed to sell at the stadium.", "He was fined for parking without a permit.", "His truck broke down outside the stadium.", "His insurance was cancelled unexpectedly."], answer: 1, explanation: "他說「you need a special permit for that whole street, and I got fined before I'd sold a single taco」，是沒許可證被罰款。" },
      { q: "How did Ray discover his spot by the river?", options: ["A mechanic recommended the location.", "Office workers invited him to park there.", "His truck happened to break down there.", "He researched where lunch crowds gather."], answer: 2, explanation: "他說「My engine broke down there one lunchtime」，引擎剛好在那裡拋錨，等修車時客人自己上門，純屬運氣。" },
      { q: "What does Ray say is the hardest part of the job now?", options: ["Getting up so early every day.", "Competing with the best cooks in the city.", "Queuing for permits every November.", "Losing income when the weather is bad."], answer: 3, explanation: "他說大家猜是早起，但「It's the weather, no question. One rainy week in November and your income just vanishes」，天氣才是最難的。" },
      { q: "How does Ray respond to his sister's claim about hours and money?", options: ["He says both parts of it are completely wrong.", "He admits the hours are long but says the pay is now better.", "He agrees he earns half of what he used to.", "He refuses to discuss money in the interview."], answer: 1, explanation: "他說「The hours part is true, I won't pretend otherwise. The money's actually better than the restaurant now」，承認工時長但否認錢變少。" }
    ] },
  { id: "f-lis2-05", title: "New Member Talk at Summit Point Climbing Gym", kind: "monologue",
    script: "Hi everyone, welcome to Summit Point, and congratulations on your new memberships. I'm Dana, head instructor, and this short talk is the one thing every new member has to sit through, so, well, thanks for your patience — I promise it's worth ten minutes.\nFirst, the layout. The tall walls with ropes are on the left; that whole area needs a harness and a partner. The right-hand side is the bouldering zone — shorter walls, no ropes, thick mats underneath. New members always drift towards bouldering because it looks simpler, and it is, but don't be fooled: most of our injuries actually happen there, not on the ropes. People forget that falling from three metres onto a mat still needs proper technique. So please, take the free falling workshop before your first bouldering session. It runs every evening at six, takes twenty minutes, and it's genuinely the most useful thing we teach.\nSecond, the colour system. Every route is marked with coloured holds — green routes are the easiest, then blue, then red, and black is for the fearless. Here's my honest advice, and I say this to every group: stay on green for at least two weeks, even if it feels too easy. Climbing isn't about strong arms, whatever you've seen online. It's about footwork, and footwork only develops on routes that don't scare you. The members who rush to red in their first month are the same ones I see at the physio.\nThird, chalk. Loose chalk powder isn't allowed on the main floor — it gets into the ventilation. Chalk balls are fine, and the shop sells them for three pounds.\nLastly, the social side. Wednesday nights are beginner meet-ups, and honestly, climbing with the same people each week will improve you faster than any private lesson. This sport looks individual, but nobody gets good alone. Right — any questions, grab me by the front desk. Otherwise, enjoy the walls, and remember: green routes, six o'clock workshop.",
    questions: [
      { q: "What is the main purpose of Dana's talk?", options: ["To introduce new members to the gym's rules and layout.", "To advertise private climbing lessons.", "To explain how the gym was built.", "To recruit instructors for the workshops."], answer: 0, explanation: "她說這是「the one thing every new member has to sit through」，內容涵蓋場地配置、路線分級與規定，是新會員說明。" },
      { q: "What does Dana say about the bouldering zone?", options: ["It requires a harness and a partner.", "It is where most injuries happen.", "It is only open to experienced members.", "It has taller walls than the rope area."], answer: 1, explanation: "她說「most of our injuries actually happen there, not on the ropes」，抱石區看似簡單，其實最多人受傷。" },
      { q: "Why does Dana recommend staying on green routes at first?", options: ["The other routes are usually crowded.", "Green holds are easier to see.", "Footwork develops on routes that feel safe.", "New members are not insured on red routes."], answer: 2, explanation: "她說「footwork only develops on routes that don't scare you」，在不嚇人的簡單路線上才能練好腳法。" },
      { q: "What is the rule about chalk on the main floor?", options: ["All chalk is completely banned.", "Chalk may only be used on black routes.", "Chalk must be bought from the gym shop.", "Only chalk balls are permitted, not loose powder."], answer: 3, explanation: "她說「Loose chalk powder isn't allowed on the main floor... Chalk balls are fine」，禁散粉但允許粉球，商店販售只是補充資訊。" },
      { q: "What is Dana's opinion about improving at climbing?", options: ["Climbing regularly with others helps most.", "Private lessons are the fastest route.", "Strong arms matter more than technique.", "Progress mainly depends on natural talent."], answer: 0, explanation: "她說「climbing with the same people each week will improve you faster than any private lesson... nobody gets good alone」，固定與他人一起攀爬最有效。" }
    ] },
  { id: "f-lis2-06", title: "Neighbours Planning the Street Car-Boot Sale", kind: "dialogue",
    script: "Priya: Morning, Bill! Got a minute? It's about the car-boot sale for the street. The residents' meeting voted yes, so apparently you and I are now the organisers. Lucky us.\nBill: Ha! That'll teach us to miss a meeting. Right, well, first things first — when? I'd say the last Sunday of August. The school car park's free then, and we'd catch families before the holidays end.\nPriya: See, I'd have gone for early September, when everyone's back and clearing out kids' clothes for the new term. But you're right about the car park, that settles it. August it is.\nBill: Good. Now, pitches. The car park fits about thirty cars if we're sensible with the rows. Do we charge sellers?\nPriya: We have to, I think. Not to make a profit — but the school wants a donation for the caretaker's time, and we'll need signs, tape, that sort of thing. Ten pounds a pitch?\nBill: Ten feels steep for a street event. Make it five, and I bet we fill all thirty spots within a week. Half-empty at ten pounds looks worse than full at five.\nPriya: Hmm... okay, five, but sellers bring their own tables. I'm not hauling furniture around at my age.\nBill: Agreed. What about food? Sandra at number twelve mentioned doing a cake stall for the school roof fund.\nPriya: Oh, perfect, and honestly, don't let anyone talk us into a barbecue. My brother ran one at his street sale, and the insurance forms nearly finished him off. Cakes and a tea urn, nothing with flames.\nBill: Fine by me. Now, the bit I'm dreading — publicity. Posters?\nPriya: Posters, yes, but the local online noticeboard matters more these days. My daughter posted her sofa on there and had five replies within the hour. I'll ask her to handle the online side.\nBill: Brilliant. Then I'll do posters and book the car park with the school office tomorrow. Shall we compare notes on Friday?\nPriya: Friday, my kitchen, ten o'clock. Bring biscuits and the booking confirmation.",
    questions: [
      { q: "Why are Priya and Bill organising the sale?", options: ["They were chosen while absent from a meeting.", "They volunteered at the residents' meeting.", "The school asked them to run it.", "They organised the same event last year."], answer: 0, explanation: "Priya 說會議投票通過後「apparently you and I are now the organisers」，Bill 回「That'll teach us to miss a meeting」，兩人缺席才被指派。" },
      { q: "Why does Priya accept Bill's choice of date?", options: ["Families will still be on holiday then.", "September is too cold for an outdoor sale.", "The school car park is available in August.", "Kids' clothes sell better in August."], answer: 2, explanation: "她原本偏好九月初，但說「you're right about the car park, that settles it」，是停車場八月有空檔說服了她。" },
      { q: "Why does Bill want a lower pitch fee?", options: ["The school refused to accept donations.", "A full car park looks better than a half-empty one.", "Sellers cannot afford ten pounds.", "The signs and tape cost less than expected."], answer: 1, explanation: "Bill 說「Half-empty at ten pounds looks worse than full at five」，收五鎊能填滿三十個攤位，場面更好看。" },
      { q: "What is Priya's attitude towards having a barbecue?", options: ["She thinks it would raise money for the roof fund.", "She wants her brother to run it again.", "She would allow it if Sandra agrees.", "She is against it because of the insurance burden."], answer: 3, explanation: "她說「don't let anyone talk us into a barbecue」，因為哥哥辦過，「the insurance forms nearly finished him off」，堅決反對。" },
      { q: "What do they agree about publicity?", options: ["Priya's daughter will manage the online posting.", "Bill will post the event on the noticeboard.", "Posters are no longer worth making.", "Priya will book the car park on Friday."], answer: 0, explanation: "Priya 說線上佈告欄更重要，「I'll ask her to handle the online side」由女兒負責網路宣傳，Bill 則做海報並訂場地。" }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
