/* FCE Prep extra bank: part2 wave 4 */
(function () {
  var BANK = [
    { text: "The success of the festival depends largely ____ the weather that weekend.", answers: ["on", "upon"], explanation: "The verb 'depend' is always followed by the preposition 'on' (or the more formal 'upon')." },
    { text: "She apologised ____ arriving late to the rehearsal.", answers: ["for"], explanation: "We apologise 'for' doing something; the preposition introduces the reason for the apology." },
    { text: "Our new flat is quite different ____ the one we rented in Lisbon.", answers: ["from", "to"], explanation: "'Different from' is the standard collocation; British English also accepts 'different to'." },
    { text: "He insisted ____ paying for everyone's dinner, even though it was expensive.", answers: ["on", "upon"], explanation: "'Insist' takes the preposition 'on' before a noun or -ing form." },
    { text: "The museum is famous ____ its collection of ancient coins.", answers: ["for"], explanation: "'Famous for' expresses the reason for something's fame." },
    { text: "I'm not very keen ____ horror films, to be honest.", answers: ["on"], explanation: "The adjective 'keen' is followed by 'on' when talking about likes and interests." },
    { text: "This medicine may protect you ____ catching the flu this winter.", answers: ["from", "against"], explanation: "We protect someone 'from' or 'against' a danger or illness." },
    { text: "The company is fully aware ____ the risks involved in the project.", answers: ["of"], explanation: "'Aware' is always followed by the preposition 'of'." },
    { text: "There has been a sharp rise ____ the number of cyclists in the city centre.", answers: ["in"], explanation: "We talk about a rise, fall or increase 'in' something." },
    { text: "The lecture will focus mainly ____ renewable sources of energy.", answers: ["on", "upon"], explanation: "The verb 'focus' takes the preposition 'on' (or formal 'upon')." },
    { text: "The plane couldn't take ____ because of thick fog at the airport.", answers: ["off"], explanation: "The phrasal verb 'take off' means to leave the ground and begin flying." },
    { text: "I came ____ some old photographs while I was tidying the attic.", answers: ["across", "upon"], explanation: "'Come across' means to find something by chance; 'come upon' is a more literary alternative." },
    { text: "Could you turn the music ____ a little? The neighbours are complaining.", answers: ["down"], explanation: "'Turn down' means to reduce the volume; the complaint shows the music is too loud." },
    { text: "We had to put ____ the meeting until everyone had read the report.", answers: ["off", "back"], explanation: "'Put off' (or 'put back') means to postpone something to a later time." },
    { text: "She takes ____ her mother — they have exactly the same sense of humour.", answers: ["after"], explanation: "'Take after' means to resemble an older family member in character or appearance." },
    { text: "It took him months to get ____ the disappointment of losing the final.", answers: ["over"], explanation: "'Get over' means to recover from an illness, shock or disappointment." },
    { text: "The detective promised to look ____ the matter as soon as possible.", answers: ["into"], explanation: "'Look into' means to investigate or examine a problem." },
    { text: "Don't give ____ now — you've almost finished the marathon.", answers: ["up", "in"], explanation: "'Give up' means to stop trying; 'give in' (surrender) also fits the encouragement here." },
    { text: "The old cinema was pulled ____ to make way for a supermarket.", answers: ["down"], explanation: "'Pull down' means to demolish a building." },
    { text: "I really must cut ____ on sugary snacks before the summer.", answers: ["down", "back"], explanation: "'Cut down on' or 'cut back on' means to reduce the amount you consume." },
    { text: "The hotel ____ we stayed last summer has been completely renovated.", answers: ["where"], explanation: "'Where' is the relative adverb used for places; note there is no preposition after 'stayed'." },
    { text: "The author, ____ novels have sold millions of copies, rarely gives interviews.", answers: ["whose"], explanation: "'Whose' is the possessive relative pronoun: the novels belong to the author." },
    { text: "Is that the man ____ dog keeps barking all night?", answers: ["whose"], explanation: "Possession (the man's dog) requires the relative pronoun 'whose'." },
    { text: "It was raining heavily, ____ is why the match was abandoned.", answers: ["which"], explanation: "'Which' refers back to the whole previous clause in a non-defining relative clause." },
    { text: "Nobody knows exactly ____ the fire started in the warehouse.", answers: ["how", "why", "when", "where"], explanation: "An indirect question needs a question word; 'how', 'why', 'when' and 'where' all make sense." },
    { text: "You can borrow my laptop as ____ as you promise to return it tomorrow.", answers: ["long"], explanation: "'As long as' means 'on condition that' and introduces a condition." },
    { text: "____ soon as the gates opened, the crowd rushed towards the stage.", answers: ["as"], explanation: "'As soon as' means immediately after something happens." },
    { text: "I'll lend you the money on condition ____ you pay it back by Friday.", answers: ["that"], explanation: "The fixed expression 'on condition that' introduces a requirement." },
    { text: "We decided to walk home, ____ though it was nearly midnight.", answers: ["even"], explanation: "'Even though' is an emphatic way of saying 'although'." },
    { text: "She speaks French fluently, ____ she has never lived in France.", answers: ["although", "though", "yet"], explanation: "A contrast link is needed; 'although', 'though' and 'yet' all express the unexpected contrast." },
    { text: "There isn't ____ point in booking now; the tickets are all sold out.", answers: ["any", "much"], explanation: "In a negative sentence we use 'any' (or 'much') before 'point in doing something'." },
    { text: "____ of the twins wants to share a bedroom any longer.", answers: ["neither"], explanation: "'Neither of' + plural noun takes a singular verb ('wants') and means 'not one and not the other'." },
    { text: "Very ____ people realise how much water a single cotton T-shirt requires.", answers: ["few"], explanation: "'Few' is used with plural countable nouns like 'people' to mean 'not many'." },
    { text: "He has visited ____ every country in South America.", answers: ["almost", "nearly", "virtually", "practically"], explanation: "An adverb meaning 'not quite all' fits before 'every'; 'almost' and 'nearly' are the most common." },
    { text: "____ of the information on that website turned out to be false.", answers: ["much", "some", "most", "all"], explanation: "'Information' is uncountable, so quantifiers like 'much', 'some', 'most' or 'all' work here." },
    { text: "The two proposals are similar; ____ of them would solve the parking problem.", answers: ["either", "both", "each"], explanation: "'Either of them' means one or the other; 'both' and 'each' also fit the meaning." },
    { text: "I've looked everywhere, but my keys are nowhere to ____ found.", answers: ["be"], explanation: "The fixed expression 'nowhere to be found' uses a passive infinitive." },
    { text: "She earns twice as much as her brother, ____ works longer hours.", answers: ["who"], explanation: "A non-defining relative clause about a person needs 'who' as its subject." },
    { text: "Hardly ____ in the village supported the plan to build the motorway.", answers: ["anyone", "anybody"], explanation: "'Hardly anyone' means almost nobody; 'hardly' cannot combine with 'no one'." },
    { text: "Take an extra jumper with you ____ case the evening turns cold.", answers: ["in"], explanation: "'In case' introduces a precaution against something that might happen." },
    { text: "The bridge ____ been closed for repairs since early March.", answers: ["has"], explanation: "'Since' with a starting point requires the present perfect: 'has been closed'." },
    { text: "By next June, they will ____ been married for twenty-five years.", answers: ["have"], explanation: "The future perfect ('will have been') describes a duration completed by a future point." },
    { text: "A new sports centre is ____ built on the edge of town.", answers: ["being"], explanation: "The present continuous passive is formed with 'is being' + past participle." },
    { text: "You ____ better book a table; that restaurant is always full.", answers: ["had"], explanation: "'Had better' + bare infinitive gives strong advice." },
    { text: "Little ____ he know that his letter would change everything.", answers: ["did"], explanation: "After negative adverbials like 'little', the auxiliary 'did' comes before the subject (inversion)." },
    { text: "Seldom ____ the committee reached a decision so quickly.", answers: ["has"], explanation: "'Seldom' at the start of a sentence triggers inversion with the auxiliary 'has'." },
    { text: "The suspect denied ____ anywhere near the bank on the day of the robbery.", answers: ["being"], explanation: "'Deny' is followed by the -ing form; 'being' completes 'denied being near the bank'." },
    { text: "You ____ not have watered the plants — it rained all afternoon anyway.", answers: ["need"], explanation: "'Needn't have done' means the action was done but was unnecessary." },
    { text: "All visitors ____ wear a helmet while on the construction site.", answers: ["must", "should", "shall"], explanation: "A modal of obligation fits here; 'must' is the natural choice for safety rules." },
    { text: "If the printer breaks down again, it will have to ____ replaced.", answers: ["be"], explanation: "'Have to' is followed by a passive infinitive: 'to be replaced'." },
    { text: "If I ____ you, I would accept the offer without hesitation.", answers: ["were"], explanation: "'If I were you' is the standard second conditional phrase for giving advice." },
    { text: "____ it not been for your warning, we would have missed the flight.", answers: ["had"], explanation: "'Had it not been for' is an inverted third conditional meaning 'without your warning'." },
    { text: "I wish I ____ speak Italian as well as my cousin does.", answers: ["could"], explanation: "'Wish' + 'could' expresses a present ability the speaker does not have." },
    { text: "If only she ____ listened to the doctor's advice earlier.", answers: ["had"], explanation: "'If only' + past perfect ('had listened') expresses regret about the past." },
    { text: "Suppose you ____ offered the job abroad — would you take it?", answers: ["were"], explanation: "'Suppose' + past passive ('were offered') sets up a hypothetical situation." },
    { text: "He talks about the sea as ____ he had sailed around the world.", answers: ["if", "though"], explanation: "'As if' or 'as though' introduces an unreal comparison." },
    { text: "____ you require any further assistance, please contact reception.", answers: ["should", "if"], explanation: "Formal conditionals can begin with inverted 'should' ('Should you require') or plain 'if'." },
    { text: "I'd rather you ____ not smoke inside the apartment.", answers: ["did"], explanation: "'Would rather' + another subject takes the past simple: 'I'd rather you did not smoke'." },
    { text: "Unless the rain stops soon, the parade will ____ to be cancelled.", answers: ["have", "need"], explanation: "'Will have to be cancelled' expresses future obligation in the passive." },
    { text: "It's high time the council ____ something about the potholes.", answers: ["did"], explanation: "'It's high time' is followed by the past simple even though it refers to the present." },
    { text: "____ spite of her injury, she completed the climb in record time.", answers: ["in"], explanation: "The fixed expression 'in spite of' means 'despite'." },
    { text: "The flight was delayed; ____, we still made our connection in Dubai.", answers: ["however", "nevertheless", "nonetheless"], explanation: "A contrast adverb such as 'however' or 'nevertheless' links the two clauses." },
    { text: "He kept training every day ____ the freezing temperatures.", answers: ["despite", "notwithstanding"], explanation: "'Despite' + noun phrase expresses contrast without needing 'of'." },
    { text: "____ the fact that he had no experience, they gave him the job.", answers: ["despite"], explanation: "'Despite the fact that' introduces a contrasting clause; 'in spite of' would need two words." },
    { text: "I couldn't decide ____ to order the fish or the pasta.", answers: ["whether"], explanation: "Before an infinitive and with 'or', we use 'whether', not 'if'." },
    { text: "You won't improve your accent ____ you listen to native speakers regularly.", answers: ["unless"], explanation: "'Unless' means 'if ... not': improvement depends on listening regularly." },
    { text: "My sister loves crowded markets, ____ I prefer quiet bookshops.", answers: ["whereas", "while", "whilst", "but"], explanation: "'Whereas' and 'while' contrast two people's different preferences." },
    { text: "No ____ how tired she is, she never misses her evening run.", answers: ["matter"], explanation: "'No matter how' means 'regardless of how' and is a fixed expression." },
    { text: "The concert went ahead ____ planned, despite the technical problems.", answers: ["as"], explanation: "'As planned' means 'in the way that had been planned'." },
    { text: "____ far as I know, the deadline hasn't been changed.", answers: ["as"], explanation: "'As far as I know' is a fixed phrase meaning 'according to my information'." },
    { text: "She managed to finish the report ____ time for the board meeting.", answers: ["in"], explanation: "'In time for' means early enough for a particular event." },
    { text: "The keys must be handed in ____ the end of your stay.", answers: ["by", "before", "at"], explanation: "'By' means no later than a deadline; 'before' and 'at' are also grammatically possible." },
    { text: "____ average, the factory produces three hundred bicycles a day.", answers: ["on"], explanation: "'On average' is the fixed expression for talking about typical figures." },
    { text: "The village has changed beyond recognition ____ the new road was built.", answers: ["since"], explanation: "'Since' + past simple marks the starting point of a change continuing to now." },
    { text: "I haven't seen my old classmates ____ we left school ten years ago.", answers: ["since"], explanation: "The present perfect negative combines with 'since' + a past event." },
    { text: "The recipe serves four people, ____ least according to the cookbook.", answers: ["at"], explanation: "'At least' limits the claim to the source of the information." },
    { text: "____ first sight, the two paintings look absolutely identical.", answers: ["at"], explanation: "'At first sight' means when you see something for the first time." },
    { text: "He solved the crossword ____ no time at all, which amazed everyone.", answers: ["in"], explanation: "'In no time (at all)' means extremely quickly." },
    { text: "The shop is closed ____ further notice owing to flooding.", answers: ["until", "till"], explanation: "'Until further notice' means for an unspecified period from now." },
    { text: "____ from a slight headache, I feel perfectly fine today.", answers: ["apart", "aside"], explanation: "'Apart from' (or 'aside from') means 'except for'." },
    { text: "This suitcase is far ____ heavy for me to carry up the stairs.", answers: ["too"], explanation: "'Too' + adjective + 'for someone to do' shows something exceeds a limit." },
    { text: "The coffee was ____ hot that I burnt my tongue.", answers: ["so"], explanation: "'So' + adjective + 'that' expresses result; 'such' would need a noun." },
    { text: "It was ____ a boring lecture that half the audience fell asleep.", answers: ["such"], explanation: "'Such' + a/an + adjective + noun + 'that' expresses result." },
    { text: "The harder you train, ____ better your results will become.", answers: ["the"], explanation: "The double comparative pattern 'the harder ..., the better ...' links two changes." },
    { text: "Their new album isn't nearly as good ____ their first one.", answers: ["as"], explanation: "Comparisons of equality use 'as ... as'; the second 'as' is missing here." },
    { text: "My laptop is three years older ____ yours, but it still works well.", answers: ["than"], explanation: "Comparative adjectives like 'older' are followed by 'than'." },
    { text: "The exam wasn't easy ____ for most students to finish on time.", answers: ["enough"], explanation: "'Enough' follows the adjective: 'easy enough for someone to do something'." },
    { text: "____ more you practise, the easier the piece becomes.", answers: ["the"], explanation: "This is the 'the more ..., the easier ...' double comparative structure." },
    { text: "She is by ____ the most talented dancer in the whole academy.", answers: ["far"], explanation: "'By far' emphasises a superlative adjective." },
    { text: "The new stadium holds twice as ____ spectators as the old one.", answers: ["many"], explanation: "'Spectators' is a plural countable noun, so we need 'as many ... as'." },
    { text: "____ seems to be a problem with the heating in my room.", answers: ["there"], explanation: "'There seems to be' introduces the existence of something." },
    { text: "I find ____ hard to believe that he built the boat himself.", answers: ["it"], explanation: "'It' is a dummy object before the adjective: 'find it hard to believe that ...'." },
    { text: "____ used to be a bakery on this corner when I was a child.", answers: ["there"], explanation: "'There used to be' describes something that existed in the past but no longer does." },
    { text: "It's ____ use complaining; the decision has already been made.", answers: ["no"], explanation: "'It's no use' + -ing means an action is pointless." },
    { text: "My grandfather is getting used ____ living on his own.", answers: ["to"], explanation: "'Get used to' is followed by 'to' + -ing, meaning to become accustomed to something." },
    { text: "Do you mind ____ I open the window a little?", answers: ["if"], explanation: "'Do you mind if I ...?' is a polite way of asking for permission." },
    { text: "I'd rather stay in tonight ____ go to another noisy party.", answers: ["than"], explanation: "'Would rather do X than do Y' compares two options with bare infinitives." },
    { text: "It was Marta ____ first suggested cycling across the island.", answers: ["who", "that"], explanation: "In a cleft sentence ('It was X who/that ...'), the pronoun refers back to the person emphasised." },
    { text: "What I admire most about her ____ her endless patience.", answers: ["is"], explanation: "A 'what' clause acts as a singular subject, so the verb is 'is'." },
    { text: "On ____ way home, we stopped to watch the street performers.", answers: ["our", "the"], explanation: "'On our way home' (or 'on the way home') describes something happening during a journey." }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part2 = QUESTIONS.part2.concat(BANK);
})();
