/* FCE Prep extra bank: part2 wave 3 */
(function () {
  var BANK = [
    // --- Dependent prepositions ---
    { text: "Local residents strongly disapprove ____ the plan to build a car park on the meadow.", answers: ["of"], explanation: "The verb 'disapprove' takes the preposition 'of': you disapprove of something." },
    { text: "The soup tasted odd, so I complained ____ the waiter about it.", answers: ["to"], explanation: "You complain TO a person ABOUT a problem. The person addressed takes 'to'." },
    { text: "The animal shelter relies entirely ____ donations from local businesses.", answers: ["on", "upon"], explanation: "'Rely on/upon' is a fixed verb + preposition combination meaning to depend on." },
    { text: "She was so absorbed ____ her book that she missed her stop.", answers: ["in"], explanation: "'Absorbed in something' means completely concentrated on it." },
    { text: "He blamed the delay ____ the unusually heavy traffic.", answers: ["on"], explanation: "The pattern is 'blame something ON something/someone' — the cause takes 'on'." },
    { text: "The town is famous ____ its hot springs and medieval castle.", answers: ["for"], explanation: "'Famous for' introduces the thing that makes a place or person well known." },
    { text: "I'm terrible ____ remembering birthdays, so I set reminders on my phone.", answers: ["at"], explanation: "Adjectives describing skill — good, bad, terrible, hopeless — take 'at' before an activity." },
    { text: "After a long discussion, the committee finally agreed ____ a date for the village fair.", answers: ["on", "upon"], explanation: "'Agree on/upon something' means to reach a shared decision about it." },
    { text: "Thousands of fans queued overnight ____ tickets to the reunion concert.", answers: ["for"], explanation: "You queue FOR the thing you want to obtain; 'for' expresses purpose here." },
    { text: "The article draws attention ____ the working conditions of delivery riders.", answers: ["to"], explanation: "The fixed phrase is 'draw attention to something' — to make people notice it." },
    { text: "My aunt has finally recovered ____ the operation on her knee.", answers: ["from"], explanation: "You recover FROM an illness, injury or difficult experience." },
    { text: "The witness's account differed sharply ____ the driver's version of events.", answers: ["from"], explanation: "'Differ from' is the standard pattern: one thing differs from another." },
    { text: "The museum's collection consists mainly ____ objects donated by local families.", answers: ["of"], explanation: "'Consist of' means to be made up of; the parts follow 'of'." },
    { text: "The motorist was arrested and charged ____ dangerous driving.", answers: ["with"], explanation: "In legal English you are 'charged with' a crime." },
    { text: "The company provides all new staff ____ a laptop and a travel pass.", answers: ["with"], explanation: "The pattern is 'provide someone WITH something'; the thing given takes 'with'." },
    { text: "She was awarded a medal ____ bravery after rescuing the swimmer.", answers: ["for"], explanation: "'For' introduces the reason for a prize or punishment: a medal for bravery." },
    { text: "There is a growing demand ____ affordable housing in the region.", answers: ["for"], explanation: "The noun 'demand' takes 'for': demand for a product or service." },
    { text: "He has no intention ____ apologising, however long you wait.", answers: ["of"], explanation: "The noun 'intention' is followed by 'of' + -ing: no intention of doing something." },
    { text: "The instructor warned us ____ the dangers of hiking alone in winter.", answers: ["of", "about", "against"], explanation: "'Warn someone of/about/against something' are all correct ways to mention a danger." },
    { text: "This year's vaccine protects you ____ the most common strains of flu.", answers: ["against", "from"], explanation: "'Protect against/from' both work: protection is directed at the threat." },
    { text: "You should insure the parcel ____ loss or damage before posting it.", answers: ["against"], explanation: "You insure something 'against' a possible misfortune such as loss, theft or fire." },
    { text: "The final decision rests ____ the panel of judges, not the audience.", answers: ["with"], explanation: "'The decision rests with someone' means that person has the responsibility for deciding." },
    { text: "The bad weather resulted ____ several flights being diverted to other airports.", answers: ["in"], explanation: "'Result in' introduces the consequence; 'result from' would introduce the cause." },
    { text: "Her success owes much ____ years of quiet, patient practice.", answers: ["to"], explanation: "'Owe something to something' credits the cause: her success is largely due to practice." },
    { text: "There's no excuse ____ arriving late twice in the same week.", answers: ["for"], explanation: "The noun 'excuse' takes 'for' + -ing: an excuse for doing something." },
    { text: "I mistook the actor ____ his brother; they're incredibly alike.", answers: ["for"], explanation: "'Mistake someone for someone else' means to wrongly think one person is another." },
    { text: "Their new flat is quite similar ____ ours, only slightly bigger.", answers: ["to"], explanation: "The adjective 'similar' takes 'to': one thing is similar to another." },
    { text: "The two villages are within easy reach ____ each other by bicycle.", answers: ["of"], explanation: "The fixed phrase is 'within (easy) reach of something' — close enough to get to." },

    // --- Phrasal verbs ---
    { text: "In the end, success in this job comes ____ to confidence and careful preparation.", answers: ["down"], explanation: "'Come down to something' means to depend essentially on that thing." },
    { text: "The village is completely cut ____ from the outside world whenever it snows heavily.", answers: ["off"], explanation: "'Cut off' means isolated or separated, often by weather or distance." },
    { text: "It took me ages to work ____ what the abbreviation stood for.", answers: ["out"], explanation: "'Work out' means to solve or understand something after some effort." },
    { text: "Could you look ____ my cat while I'm away at the conference?", answers: ["after"], explanation: "'Look after' means to take care of a person, animal or thing." },
    { text: "The meeting dragged ____ for three hours without reaching any decision.", answers: ["on"], explanation: "'Drag on' means to continue for longer than necessary in a boring way." },
    { text: "Our car broke ____ on the motorway, miles from the nearest garage.", answers: ["down"], explanation: "'Break down' means to stop working, used especially of vehicles and machines." },
    { text: "She came up ____ a brilliant slogan for the campaign in a matter of minutes.", answers: ["with"], explanation: "'Come up with' means to think of or produce an idea or solution." },
    { text: "I simply couldn't put the novel ____ until I had finished the final chapter.", answers: ["down"], explanation: "'Put a book down' means to stop reading it; a gripping book is hard to put down." },
    { text: "We've decided to do ____ with the old filing system and store everything digitally.", answers: ["away"], explanation: "'Do away with something' means to get rid of or abolish it." },
    { text: "The smoke alarm went ____ in the middle of the night for no apparent reason.", answers: ["off"], explanation: "'Go off' describes an alarm ringing or a bomb exploding." },
    { text: "The council has promised to look ____ the complaints about street lighting.", answers: ["into"], explanation: "'Look into' means to investigate or examine a problem." },
    { text: "Don't let one bad review put you ____ applying again next year.", answers: ["off"], explanation: "'Put someone off (doing) something' means to discourage them from it." },
    { text: "She takes ____ extra responsibilities at work without ever complaining.", answers: ["on"], explanation: "'Take on' means to accept extra work, duties or responsibility." },
    { text: "We had to check ____ of the hotel by ten o'clock on the day of departure.", answers: ["out"], explanation: "'Check out of a hotel' means to pay the bill and leave; the opposite is 'check in'." },
    { text: "We'd better set ____ before sunrise if we want to avoid the midday heat.", answers: ["off", "out"], explanation: "'Set off' and 'set out' both mean to begin a journey." },
    { text: "The manager eventually talked me ____ accepting the night shift.", answers: ["into"], explanation: "'Talk someone into doing something' means to persuade them to do it." },
    { text: "I dug ____ an old diary of my grandfather's while tidying the attic.", answers: ["out", "up"], explanation: "'Dig out/up' means to find something after searching, often something long forgotten." },
    { text: "The concert was sold ____ within minutes of tickets going on sale.", answers: ["out"], explanation: "'Sold out' means all the tickets or goods have been sold." },
    { text: "The caterpillar eventually turns ____ a butterfly inside its cocoon.", answers: ["into"], explanation: "'Turn into' means to change and become something different." },

    // --- Auxiliaries, modals and verb forms ---
    { text: "Judging by his accent, he ____ well come from somewhere near Glasgow.", answers: ["may", "might", "could"], explanation: "'May/might/could well' expresses a strong possibility about the present." },
    { text: "You ____ have told me the meeting was cancelled; I waited for a whole hour!", answers: ["could", "should", "might"], explanation: "'Could/should/might have done' criticises someone for not doing something in the past." },
    { text: "The lights are all off, so they ____ have gone to bed already.", answers: ["must"], explanation: "'Must have + past participle' expresses a logical deduction about the past." },
    { text: "The doctor recommended that the patient ____ given a second scan immediately.", answers: ["be", "was"], explanation: "After verbs like 'recommend', the subjunctive 'be' is used; 'was' is also possible in informal British English." },
    { text: "A new bypass is currently ____ constructed to ease traffic through the village.", answers: ["being"], explanation: "The present continuous passive is formed with 'is being + past participle'." },
    { text: "The castle is said to ____ haunted by a seventeenth-century duchess.", answers: ["be"], explanation: "The passive reporting structure 'is said to be' needs the bare infinitive 'be' after 'to'." },
    { text: "Had I realised the tickets were free, I ____ have invited the whole class.", answers: ["would"], explanation: "This is an inverted third conditional: 'Had I realised..., I would have...'." },
    { text: "He can't ____ finished the report already; he only started it an hour ago.", answers: ["have"], explanation: "'Can't have + past participle' expresses certainty that something did NOT happen." },
    { text: "The results ____ being checked at this very moment, so please be patient.", answers: ["are"], explanation: "The present continuous passive needs 'are' before 'being checked' with a plural subject." },
    { text: "When the inspector arrived, the kitchen ____ not been cleaned for days.", answers: ["had"], explanation: "The past perfect passive 'had not been cleaned' describes a state before a past moment." },
    { text: "____ you require any further information, please contact our office.", answers: ["should", "if"], explanation: "Formal conditional inversion uses 'Should you require...' = 'If you (should) require...'." },
    { text: "Under no circumstances ____ passengers open the doors while the train is moving.", answers: ["should", "must", "may"], explanation: "After a negative opening phrase, subject and modal invert: 'Under no circumstances should/must/may passengers...'." },
    { text: "So absorbed ____ she in her painting that she forgot to eat lunch.", answers: ["was"], explanation: "When 'so + adjective' begins the sentence, subject and verb invert: 'So absorbed was she...'." },
    { text: "Only after the guests had left ____ we discover the broken vase.", answers: ["did"], explanation: "After 'Only after...' at the start, the main clause inverts with the auxiliary 'did'." },
    { text: "The stone bridge ____ still being repaired when the floods struck again.", answers: ["was"], explanation: "The past continuous passive 'was being repaired' describes an unfinished action in the past." },
    { text: "By the time the guests arrived, the cake ____ been iced and decorated.", answers: ["had"], explanation: "'By the time' + past event requires the past perfect: 'had been iced'." },
    { text: "Since when ____ you been interested in astronomy?", answers: ["have"], explanation: "'Since when' asks about duration up to now, so the present perfect 'have you been' is needed." },
    { text: "The missing hiker is thought to ____ taken shelter in a mountain hut.", answers: ["have"], explanation: "'Is thought to have done' reports a belief about a past action." },
    { text: "Neither of us ____ ever flown before that trip to Iceland.", answers: ["had"], explanation: "'Before that trip' places the experience earlier in the past, so the past perfect 'had flown' is required." },
    { text: "The parcel ____ have been delivered next door by mistake; there's a note on our doormat.", answers: ["must", "might", "may", "could"], explanation: "Modal + 'have been delivered' speculates about the past; the note makes 'must' the strongest deduction." },
    { text: "Everyone insisted that the old tradition ____ continue for another generation.", answers: ["should", "must"], explanation: "After 'insist that', 'should' (or 'must') expresses what people demanded." },
    { text: "A number of rare coins ____ stolen from the museum overnight.", answers: ["were"], explanation: "'A number of' takes a plural verb, so the past passive is 'were stolen'." },
    { text: "According to the sign in the window, English ____ spoken in this shop.", answers: ["is"], explanation: "The present simple passive 'is spoken' describes a general fact." },
    { text: "____ it not been for the lifeguard, the boy might have drowned.", answers: ["had"], explanation: "'Had it not been for...' is an inverted conditional meaning 'If it had not been for...'." },

    // --- Articles, quantifiers and pronouns ---
    { text: "She plays ____ violin in an amateur orchestra every Thursday evening.", answers: ["the"], explanation: "Musical instruments normally take the definite article: play the violin." },
    { text: "He's training to become ____ engineer, just like his mother.", answers: ["an"], explanation: "Jobs take the indefinite article, and 'engineer' begins with a vowel sound, so 'an'." },
    { text: "We had ____ wonderful time at the school reunion last weekend.", answers: ["a"], explanation: "The fixed expression 'have a wonderful/great time' requires the indefinite article." },
    { text: "____ the players nor the coach was willing to talk to reporters.", answers: ["neither"], explanation: "'Neither... nor...' joins two negative alternatives: neither the players nor the coach." },
    { text: "There are plenty of chairs, so ____ of you needs to stand.", answers: ["none"], explanation: "'None of you' means not a single one of a group of three or more." },
    { text: "____ candidate must bring photographic identification to the examination.", answers: ["each", "every"], explanation: "'Each' or 'every' before a singular noun refers to all members of a group individually." },
    { text: "Very ____ of the original furniture has survived, sadly.", answers: ["little"], explanation: "'Little' is used with uncountable nouns; 'very little' means almost none." },
    { text: "I've tried both remedies, but ____ made the slightest difference.", answers: ["neither"], explanation: "'Neither' as a pronoun means 'not one and not the other' of two things." },
    { text: "Is there ____ else you'd like to add before we close the meeting?", answers: ["anything"], explanation: "In questions, 'anything else' asks whether some additional point exists." },
    { text: "The house felt strangely quiet with ____ at home all afternoon.", answers: ["nobody"], explanation: "'With nobody at home' means without any person present." },
    { text: "Help ____ to biscuits; there are plenty in the tin.", answers: ["yourself", "yourselves"], explanation: "'Help yourself/yourselves to something' is a fixed reflexive expression meaning 'take freely'." },
    { text: "Rather than hire a decorator, we painted the whole flat ____.", answers: ["ourselves"], explanation: "The reflexive pronoun 'ourselves' emphasises that we did it without help." },
    { text: "My phone battery lasts twice as long as ____ used to.", answers: ["it"], explanation: "The pronoun 'it' refers back to the battery: as long as it used to last." },
    { text: "____ seems to be some confusion over who booked the meeting room.", answers: ["there"], explanation: "'There seems to be' introduces the existence of something, like 'there is'." },
    { text: "If these headphones don't suit you, we have several other ____ in stock.", answers: ["ones"], explanation: "'Ones' replaces a plural countable noun already mentioned — here, headphones." },
    { text: "Is this scarf ____ , or does it belong to your sister?", answers: ["yours"], explanation: "The possessive pronoun 'yours' stands alone without a noun: 'Is this yours?'." },
    { text: "The examiners will check that the essay is entirely your ____ work.", answers: ["own"], explanation: "'Your own' emphasises that the work belongs to and was produced by you alone." },
    { text: "The twins are so close that they finish ____ other's sentences all the time.", answers: ["each"], explanation: "'Each other's' is the possessive form of the reciprocal pronoun 'each other'." },
    { text: "Hardly ____ of the shops were open on the public holiday.", answers: ["any"], explanation: "'Hardly any' means almost none; 'any' is used after the near-negative 'hardly'." },
    { text: "There's ____ much noise in this café that I can't hear you properly.", answers: ["so"], explanation: "'So much + uncountable noun + that' expresses cause and result." },
    { text: "I had never seen ____ a crowded beach in all my life.", answers: ["such"], explanation: "'Such a + adjective + noun' intensifies the noun phrase: such a crowded beach." },
    { text: "Very ____ people know that the town once had its own airport.", answers: ["few"], explanation: "'Few' is used with plural countable nouns; 'very few' means almost no people." },
    { text: "____ who wish to attend the workshop should sign up by Friday.", answers: ["those"], explanation: "'Those who' means 'the people who' and is common in formal notices." },
    { text: "____ two snowflakes are exactly alike, or so scientists claim.", answers: ["no"], explanation: "'No' before a plural noun means 'not any': no two snowflakes are identical." },

    // --- Relative clauses ---
    { text: "The scientist ____ research led to the vaccine was awarded the Nobel Prize.", answers: ["whose"], explanation: "'Whose' shows possession in a relative clause: the research belonging to the scientist." },
    { text: "The hotel offers a free shuttle bus, ____ makes getting to the airport very easy.", answers: ["which"], explanation: "'Which' refers to the whole previous idea in a non-defining relative clause." },
    { text: "Is there a good reason ____ the invoice still hasn't been paid?", answers: ["why"], explanation: "After the noun 'reason', the relative adverb 'why' introduces the explanation." },
    { text: "The little café ____ we used to meet has turned into a bookshop.", answers: ["where"], explanation: "'Where' refers to a place in a relative clause: the café in which we met." },
    { text: "She's the kind of manager ____ everyone feels able to talk to.", answers: ["who", "whom", "that"], explanation: "The relative pronoun is the object of 'talk to', so 'who', 'whom' or 'that' all work." },
    { text: "Much of ____ he said in the interview turned out to be pure invention.", answers: ["what"], explanation: "'What' means 'the thing(s) that' and acts as both object and clause introducer." },
    { text: "The day ____ the results were announced, the whole school gathered in the hall.", answers: ["when", "that"], explanation: "After a time expression like 'the day', 'when' (or informally 'that') introduces the clause." },
    { text: "____ of the two routes you choose, allow at least three hours for the walk.", answers: ["whichever"], explanation: "'Whichever' means 'it doesn't matter which one' of a limited set of options." },
    { text: "He has three sisters, all of ____ live abroad.", answers: ["whom"], explanation: "After a preposition in a non-defining clause, 'whom' is required for people: all of whom." },
    { text: "The film wasn't nearly as good as the novel on ____ it was based.", answers: ["which"], explanation: "After a preposition, 'which' is used for things: the novel on which it was based." },

    // --- Conjunctions and linkers ---
    { text: "____ having very little experience, she handled the crisis brilliantly.", answers: ["despite"], explanation: "'Despite + -ing' introduces a contrast: although she had little experience." },
    { text: "I'll text you as soon ____ the plumber arrives.", answers: ["as"], explanation: "The conjunction 'as soon as' means 'immediately when'." },
    { text: "The play lasted over three hours, ____ nobody in the audience seemed to mind.", answers: ["but", "yet", "though", "although"], explanation: "A contrast linker is needed: 'but', 'yet' or '(al)though' all fit here." },
    { text: "____ we hurry, we'll never catch the last ferry to the mainland.", answers: ["unless"], explanation: "'Unless' means 'if... not': if we don't hurry, we'll miss the ferry." },
    { text: "He speaks slowly and clearly, ____ that everyone in the audience can follow.", answers: ["so"], explanation: "'So that' introduces purpose: he speaks slowly in order for people to follow." },
    { text: "____ delicious the dessert looked, I was far too full to try it.", answers: ["however"], explanation: "'However + adjective' means 'no matter how delicious it looked'." },
    { text: "It's ages ____ we last went camping together.", answers: ["since"], explanation: "'It's ages since + past simple' measures time from a past event until now." },
    { text: "I'd finished the crossword ____ the train even left the station.", answers: ["before"], explanation: "'Before' links the earlier completed action to the later event." },
    { text: "____ do we eat out during the week, but Fridays are an exception.", answers: ["rarely", "seldom"], explanation: "Negative adverbs like 'rarely/seldom' at the start of a sentence trigger inversion: 'Rarely do we...'." },
    { text: "You may borrow the drill ____ long as you bring it back by the weekend.", answers: ["as", "so"], explanation: "'As/so long as' means 'on condition that'." },
    { text: "____ than complain about the mess, why not offer to help clear it up?", answers: ["rather"], explanation: "'Rather than + infinitive' presents a preferred alternative action." },
    { text: "The show will go ahead ____ or not the lead singer recovers in time.", answers: ["whether"], explanation: "'Whether or not' means that the result is the same in either case." },
    { text: "The mountain road may be closed, in ____ case we should allow extra time.", answers: ["which"], explanation: "'In which case' refers back to the possible situation just mentioned." },
    { text: "The recipe couldn't be simpler; ____ you need is flour, eggs and a little patience.", answers: ["all", "what"], explanation: "'All you need is...' (or 'what you need is...') means the only requirement is this." },

    // --- Fixed phrases ---
    { text: "The old farmhouse is ____ from luxurious, but it has bags of charm.", answers: ["far"], explanation: "'Far from + adjective' means 'not at all': far from luxurious = definitely not luxurious." },
    { text: "The results this year were, ____ average, ten per cent better than last year's.", answers: ["on"], explanation: "The fixed phrase 'on average' describes a typical or mean figure." },
    { text: "The train strike brought the entire capital ____ a standstill.", answers: ["to"], explanation: "'Bring something to a standstill' means to make it stop completely." },
    { text: "He learned the entire speech ____ heart in a single evening.", answers: ["by"], explanation: "'Learn something by heart' means to memorise it completely." },
    { text: "It's high ____ the council did something about the potholes in our street.", answers: ["time"], explanation: "'It's high time + past simple' means something should already have been done." },
    { text: "It's entirely ____ to you whether we eat in or go out tonight.", answers: ["up"], explanation: "'It's up to you' means the decision is yours to make." },
    { text: "It's no ____ crying over spilt milk, as my grandmother always says.", answers: ["use", "good"], explanation: "'It's no use/good + -ing' means the action will not achieve anything." },
    { text: "The library will remain closed ____ further notice while the roof is repaired.", answers: ["until", "till"], explanation: "'Until further notice' means for an indefinite period, until a new announcement." },
    { text: "The maritime museum is well ____ a visit if you're ever in town.", answers: ["worth"], explanation: "'Be (well) worth + noun/-ing' means something deserves the time or effort." },
    { text: "____ a matter of fact, I've never actually read any of her novels.", answers: ["as"], explanation: "'As a matter of fact' introduces a surprising or corrective piece of information." },
    { text: "The older the cheese gets, ____ stronger it tastes.", answers: ["the"], explanation: "The double comparative 'the older..., the stronger...' shows two things changing together." }
  ];

  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part2 = QUESTIONS.part2.concat(BANK);
})();
