/* FCE Prep extra bank: part2 wave 2 */
(function () {
  var BANK = [
    /* ---------- dependent prepositions ---------- */
    { text: "The success of the whole project depends largely ____ how quickly we can secure the funding.", answers: ["on", "upon"], explanation: "The verb 'depend' is always followed by the preposition 'on' (or the more formal 'upon')." },
    { text: "She apologised ____ arriving late to the rehearsal, blaming the roadworks in the town centre.", answers: ["for"], explanation: "We apologise FOR something or for doing something; 'for' introduces the reason for the apology." },
    { text: "This cough medicine is not suitable ____ children under the age of six.", answers: ["for"], explanation: "The adjective 'suitable' takes the preposition 'for': suitable for someone/something." },
    { text: "Grandad insisted ____ paying for everyone's meal, even though the restaurant was terribly expensive.", answers: ["on", "upon"], explanation: "'Insist' is followed by 'on' (or formal 'upon') plus a noun or -ing form: insist on paying." },
    { text: "The documentary deals ____ the effects of mass tourism on small island communities.", answers: ["with"], explanation: "'Deal with' means to be about or to handle a topic; the fixed preposition is 'with'." },
    { text: "I'm not very familiar ____ this part of the city, so let's keep the map handy.", answers: ["with"], explanation: "A person is familiar WITH something; compare 'familiar to', which means known by someone." },
    { text: "Her latest novel is loosely based ____ events from her own childhood in Ireland.", answers: ["on", "upon"], explanation: "The passive expression 'be based on/upon something' takes this fixed preposition." },
    { text: "The airline was accused ____ misleading its customers with hidden booking fees.", answers: ["of"], explanation: "The pattern is 'accuse somebody OF doing something'; 'of' is the required preposition." },
    { text: "After months of trying, he finally succeeded ____ persuading his parents to let him study abroad.", answers: ["in"], explanation: "'Succeed' is followed by 'in' plus the -ing form: succeed in doing something." },
    { text: "The lecture gave us a fascinating insight ____ how the human brain stores memories.", answers: ["into"], explanation: "The noun 'insight' takes the preposition 'into': an insight into a subject." },
    { text: "There has been a sharp rise ____ the number of people cycling to work in recent years.", answers: ["in"], explanation: "We talk about a rise, fall or increase IN something; 'in' links the change to what is changing." },
    { text: "The two neighbouring countries had been ____ war with each other for nearly a decade.", answers: ["at"], explanation: "'At war' is a fixed expression, like 'at peace' or 'at risk'; no article is used." },
    { text: "We arrived ____ the airport with barely twenty minutes to spare before check-in closed.", answers: ["at"], explanation: "We arrive AT a building or point (the airport, the station) but arrive IN a city or country." },
    { text: "The ruined abbey dates ____ to the twelfth century, when the region was constantly under attack.", answers: ["back"], explanation: "'Date back to' is a fixed phrase meaning to have existed since a particular time." },
    { text: "My cousin has just got engaged ____ a marine biologist she met while travelling in Portugal.", answers: ["to"], explanation: "You get engaged or married TO a person, not 'with' a person, in standard English." },
    { text: "This crisp white wine goes particularly well ____ grilled fish or seafood.", answers: ["with"], explanation: "'Go (well) with' means to match or combine well; the preposition 'with' is fixed." },
    { text: "The minister refused to comment ____ the rumours surrounding her sudden resignation.", answers: ["on", "upon"], explanation: "'Comment' as a verb takes 'on' (or formal 'upon'): comment on a situation." },
    { text: "The recipe calls ____ fresh basil, but dried herbs will do at a pinch.", answers: ["for"], explanation: "'Call for' is a phrasal verb meaning to require or demand something." },
    { text: "There's simply no accounting ____ taste, as my grandmother always used to say.", answers: ["for"], explanation: "'There's no accounting for taste' is a fixed idiom meaning people's preferences can't be explained." },
    { text: "The valley suffered badly ____ flooding twice in the same winter.", answers: ["from"], explanation: "'Suffer from' is the standard pattern for experiencing something unpleasant such as illness or damage." },
    { text: "The twins look so alike that hardly anyone can tell one ____ the other.", answers: ["from"], explanation: "'Tell one thing FROM another' means to distinguish between them." },
    { text: "Apart ____ the ending, which felt a little rushed, I thoroughly enjoyed the film.", answers: ["from"], explanation: "'Apart from' means 'except for'; the two words form a fixed expression." },
    { text: "The audience burst ____ laughter the moment the comedian walked on stage.", answers: ["into"], explanation: "'Burst into laughter/tears/flames' is a fixed expression describing a sudden start." },
    { text: "The team lost the final on penalties, much ____ the disappointment of their loyal supporters.", answers: ["to"], explanation: "'Much to somebody's disappointment/surprise/delight' is a fixed pattern with 'to'." },
    { text: "When we opened the workshop, tools were scattered all ____ the floor.", answers: ["over", "across", "around"], explanation: "'All over' (or 'across/around') describes something spread everywhere on a surface." },
    { text: "The new tunnel runs directly ____ the river, linking the two halves of the city.", answers: ["under", "beneath", "below"], explanation: "'Under' (or 'beneath/below') expresses position lower than something else — here, the riverbed." },
    { text: "She takes great pride ____ growing all her own fruit and vegetables.", answers: ["in"], explanation: "The fixed pattern is 'take pride IN something/doing something'." },
    { text: "The two sides finally reached an agreement, though only ____ great difficulty.", answers: ["with"], explanation: "'With difficulty' (or 'with great difficulty') describes the manner in which something is achieved." },

    /* ---------- phrasal verbs ---------- */
    { text: "The plane eventually took ____ two hours late because of thick fog over the runway.", answers: ["off"], explanation: "'Take off' means to leave the ground; it is the standard phrasal verb for planes departing." },
    { text: "The staff meeting has been put ____ until next Thursday because the director is unwell.", answers: ["off", "back"], explanation: "'Put off' (or 'put back') means to postpone something to a later time." },
    { text: "I can't figure ____ how to change the language settings on this new phone.", answers: ["out"], explanation: "'Figure out' means to understand or solve something after thinking about it." },
    { text: "She turned ____ the promotion because it would have meant relocating to another country.", answers: ["down"], explanation: "'Turn down' means to refuse or reject an offer, invitation or application." },
    { text: "The old cinema was pulled ____ last year to make room for a shopping centre.", answers: ["down"], explanation: "'Pull down' means to demolish a building; 'knock down' has the same meaning." },
    { text: "My mother grew ____ in a fishing town where everybody knew everybody else.", answers: ["up"], explanation: "'Grow up' means to spend one's childhood and develop from child to adult." },
    { text: "The firefighters finally managed to put ____ the flames after battling them for six hours.", answers: ["out"], explanation: "'Put out' means to extinguish a fire, cigarette or light." },
    { text: "Please carry ____ with your rehearsal; I didn't mean to interrupt you.", answers: ["on"], explanation: "'Carry on' means to continue doing something, often after an interruption." },
    { text: "The pay negotiations broke ____ after neither side would compromise on overtime rates.", answers: ["down"], explanation: "'Break down' means to fail or collapse, used of talks, relationships and machines." },
    { text: "She fainted in the heat but came ____ after a few minutes in the shade.", answers: ["round", "to", "around"], explanation: "'Come round/to' means to regain consciousness after fainting." },
    { text: "The whole story was made ____ from beginning to end; none of it ever happened.", answers: ["up"], explanation: "'Make up' means to invent something untrue, such as a story or excuse." },
    { text: "Could you fill ____ this registration form and hand it back to reception, please?", answers: ["in", "out"], explanation: "'Fill in' (British) or 'fill out' (American) means to complete a form with information." },

    /* ---------- auxiliaries, modals and verb forms ---------- */
    { text: "By the end of this month, I will ____ been working at the hospital for exactly ten years.", answers: ["have"], explanation: "The future perfect continuous is formed with 'will + have + been + -ing'." },
    { text: "The missing documents ____ discovered in a locked drawer two weeks after the trial ended.", answers: ["were"], explanation: "A past passive with a plural subject ('documents') needs 'were' plus the past participle." },
    { text: "A brand-new sports centre is currently ____ built on the edge of town.", answers: ["being"], explanation: "The present continuous passive is formed with 'is/are + being + past participle'." },
    { text: "You ____ have seen my brother yesterday; he's been in Japan all month.", answers: ["can't", "cannot", "couldn't"], explanation: "'Can't/couldn't have + past participle' expresses certainty that something was impossible in the past." },
    { text: "To be honest, I ____ rather stay in tonight than go to another noisy party.", answers: ["would"], explanation: "'Would rather + infinitive... than' expresses a preference between two options." },
    { text: "We ____ better reserve a table now; that place is always packed on Friday evenings.", answers: ["had"], explanation: "'Had better + bare infinitive' gives strong advice; it is often shortened to 'we'd better'." },
    { text: "Never before ____ the town witnessed such a spectacular carnival procession.", answers: ["had", "has"], explanation: "After negative adverbials like 'never before', the auxiliary and subject invert: 'never before had/has the town...'." },
    { text: "Only later ____ I realise how lucky we had been to escape unhurt.", answers: ["did"], explanation: "When a sentence opens with 'only later/then', the auxiliary 'did' comes before the subject (inversion)." },
    { text: "Little ____ the guests know that the whole party was being filmed for television.", answers: ["did"], explanation: "'Little did somebody know' is an inverted structure meaning they had no idea." },
    { text: "Seldom ____ you meet someone with such genuine enthusiasm for their work.", answers: ["do", "will", "can"], explanation: "The negative adverb 'seldom' at the start of a sentence triggers inversion with an auxiliary." },
    { text: "Our flight ____ already boarding by the time we finally got through security.", answers: ["was"], explanation: "The past continuous 'was boarding' describes an action in progress at a past moment." },
    { text: "Where on earth ____ you been all afternoon? I've phoned you three times.", answers: ["have", "had"], explanation: "The present perfect question 'Where have you been?' asks about an unfinished period up to now." },
    { text: "You ____ to have asked permission before borrowing my bike.", answers: ["ought"], explanation: "'Ought to have + past participle' criticises a past action that should have been different." },
    { text: "When I was a student, I ____ only afford to eat out about once a month.", answers: ["could"], explanation: "'Could' expresses general past ability, here with 'afford' to talk about money." },
    { text: "Passengers ____ not lean out of the windows while the train is in motion.", answers: ["must", "may", "should"], explanation: "'Must not' expresses prohibition in formal notices; 'may not' and 'should not' are also possible." },
    { text: "The suspect denied ever ____ set foot inside the warehouse.", answers: ["having"], explanation: "'Deny' is followed by an -ing form; the perfect gerund 'having set' refers to an earlier action." },
    { text: "She left the company suddenly, without ____ given any reason for her decision.", answers: ["being", "having"], explanation: "After 'without', the passive gerund 'being given' means she received no reason from anyone." },
    { text: "He narrowly avoided ____ knocked off his bike by a delivery van this morning.", answers: ["being", "getting"], explanation: "'Avoid' takes an -ing form; the passive gerund 'being/getting knocked' shows the action happened to him." },

    /* ---------- articles, determiners and quantifiers ---------- */
    { text: "It was ____ first time I had ever travelled anywhere by helicopter.", answers: ["the"], explanation: "Ordinal expressions like 'the first time' always take the definite article." },
    { text: "He was fined for driving without ____ valid licence.", answers: ["a"], explanation: "The singular countable noun 'licence' needs the indefinite article after 'without'." },
    { text: "What ____ astonishing view you get from the top of that lighthouse!", answers: ["an"], explanation: "Exclamations with 'What + singular noun' need a/an; 'astonishing' begins with a vowel sound, so 'an'." },
    { text: "The more you practise speaking English, ____ more confident you will become.", answers: ["the"], explanation: "The comparative correlative structure is 'the more..., the more...' with 'the' in both halves." },
    { text: "____ of the passengers had any idea how close the ferry had come to disaster.", answers: ["none", "few"], explanation: "'None of' (or 'few of') gives the negative quantity needed before 'had any idea'." },
    { text: "There isn't ____ time left before the deadline, so we must decide quickly.", answers: ["much"], explanation: "'Much' is used with uncountable nouns like 'time' in negative sentences." },
    { text: "____ of my two brothers has ever shown the slightest interest in cooking.", answers: ["neither"], explanation: "'Neither of' is used for a negative statement about exactly two people or things." },
    { text: "You're welcome to sit on ____ side of me; there's plenty of room on the bench.", answers: ["either"], explanation: "'Either side' means one side or the other of two; both options are acceptable." },
    { text: "____ single item in the shop has been reduced by at least thirty per cent.", answers: ["every"], explanation: "'Every single' is an emphatic determiner phrase used before a singular countable noun." },
    { text: "There are ____ many tourists in August that locals avoid the old town completely.", answers: ["so"], explanation: "'So many + plural noun + that' expresses cause and result." },
    { text: "I have ____ doubt whatsoever that she will make an excellent team captain.", answers: ["no"], explanation: "'No doubt whatsoever' is an emphatic way of saying you are completely certain." },
    { text: "Do help yourself to ____ more salad if you're still hungry.", answers: ["some"], explanation: "'Some' is used in offers and requests even though they are grammatically questions or imperatives." },
    { text: "Very ____ is known about the composer's early years in Vienna.", answers: ["little"], explanation: "'Little' functions as a pronoun here, meaning almost no information." },
    { text: "____ of the money raised at the summer fair will go to the children's hospice.", answers: ["most", "all", "some", "half"], explanation: "A quantifier + 'of the' + uncountable noun expresses a proportion of a specific amount." },
    { text: "I've read three of her novels, but ____ of them impressed me as much as her first.", answers: ["none"], explanation: "'None of them' is the pronoun form used for zero out of three or more items." },
    { text: "He has visited over fifty countries, ____ of which he has written about in his travel blog.", answers: ["many", "most", "all", "some"], explanation: "A quantifier + 'of which' introduces a non-defining relative clause about the countries." },
    { text: "There's hardly ____ sugar left, so could you buy a bag on your way home?", answers: ["any"], explanation: "'Hardly any' means almost none; 'any' is used because 'hardly' makes the sentence negative in meaning." },
    { text: "One of the lifts is out of order, so we'll have to use the ____ one.", answers: ["other"], explanation: "'The other' refers to the second of two specific things already known to the listener." },

    /* ---------- conjunctions and linking words ---------- */
    { text: "The harbour district has changed enormously ____ the last time I visited it.", answers: ["since"], explanation: "'Since' links a present-perfect idea to a past point in time — the previous visit." },
    { text: "You can't have any dessert ____ you finish your vegetables first.", answers: ["unless", "until"], explanation: "'Unless' means 'if... not'; 'until' also works, marking the time condition." },
    { text: "____ he is well over eighty, my uncle still swims in the sea every morning.", answers: ["although", "though", "while"], explanation: "A concessive conjunction introduces the surprising contrast between his age and his habit." },
    { text: "I'd love to join you on the hike; the trouble is ____ I've twisted my ankle.", answers: ["that"], explanation: "'The trouble/problem is that...' introduces a clause explaining the difficulty." },
    { text: "It never occurred to me ____ she might have been telling the truth all along.", answers: ["that"], explanation: "'It occurred to me that...' requires the conjunction 'that' to introduce the thought." },
    { text: "____ you happen to see Maria before Friday, could you remind her about the rehearsal?", answers: ["should", "if"], explanation: "'Should you see...' is an inverted conditional equal to 'if you should see', used for polite possibilities." },
    { text: "No sooner had the orchestra begun playing ____ the power failed across the whole district.", answers: ["than"], explanation: "'No sooner... than' is a fixed pair; 'than' (not 'when') follows 'no sooner'." },
    { text: "Scarcely had we left the harbour ____ the storm broke with tremendous force.", answers: ["when"], explanation: "'Scarcely/hardly... when' is the fixed pattern for two events happening almost together." },
    { text: "He talks about football ____ though he had played professionally himself.", answers: ["as"], explanation: "'As though' (like 'as if') introduces an unreal comparison, often with a past tense verb." },
    { text: "____ a rule, I try to avoid eating anything sweet after dinner.", answers: ["as"], explanation: "'As a rule' is a fixed expression meaning usually or generally." },
    { text: "He asked me ____ I had ever considered working overseas.", answers: ["whether", "if"], explanation: "Reported yes/no questions are introduced by 'whether' or 'if'." },
    { text: "It makes no difference ____ you pay now or when the goods are delivered.", answers: ["whether"], explanation: "Before 'or' in an alternative clause, 'whether' is required rather than 'if'." },
    { text: "Hard ____ she tried, she simply could not remember the man's surname.", answers: ["as", "though"], explanation: "'Adjective/adverb + as/though + subject + verb' is a concessive pattern meaning 'although she tried hard'." },
    { text: "Strange ____ it may seem, I have never once set foot in London.", answers: ["as", "though"], explanation: "'Strange as it may seem' is a concessive structure meaning 'although it seems strange'." },
    { text: "I'll lend you my lecture notes on condition ____ you photocopy them today.", answers: ["that"], explanation: "'On condition that' is a formal fixed phrase introducing a requirement." },
    { text: "____ the fact that tickets cost a fortune, the entire tour sold out within hours.", answers: ["despite"], explanation: "'Despite the fact that' introduces a contrast; 'despite' is followed by a noun phrase." },
    { text: "I'll wait here with the luggage ____ you fetch the car from the multi-storey.", answers: ["while", "whilst"], explanation: "'While' links two actions happening at the same time." },
    { text: "He must be at least seventy, ____ he certainly doesn't look it.", answers: ["though", "although", "but"], explanation: "'Though' at the start of the second clause adds a contrasting comment." },
    { text: "You'd better get a move on, ____ you'll miss the last train home.", answers: ["or", "otherwise"], explanation: "'Or (else)' and 'otherwise' introduce the negative consequence of not following advice." },
    { text: "It was only when the lights came back on ____ I noticed the broken window.", answers: ["that"], explanation: "The cleft structure 'It was only when... that...' emphasises the time; 'that' is required." },

    /* ---------- relatives and wh-words ---------- */
    { text: "The colleague ____ desk is next to mine is retiring at the end of June.", answers: ["whose"], explanation: "'Whose' is the possessive relative pronoun linking the colleague to her desk." },
    { text: "Everything ____ could possibly go wrong that morning did go wrong.", answers: ["that"], explanation: "After 'everything', the relative pronoun is 'that' rather than 'which'." },
    { text: "The little guesthouse ____ we stayed on our honeymoon has since been demolished.", answers: ["where"], explanation: "'Where' is the relative adverb for places; it replaces 'in which' here." },
    { text: "She showed me the old photographs, most of ____ were taken before the war.", answers: ["which"], explanation: "In non-defining clauses about things, 'quantifier + of which' is used, never 'of that'." },
    { text: "____ happens next is entirely up to the committee to decide.", answers: ["what", "whatever"], explanation: "'What' acts as a nominal relative here, meaning 'the thing that (happens next)'." },
    { text: "My neighbour, ____ car alarm kept the whole street awake, has finally apologised.", answers: ["whose"], explanation: "'Whose' shows possession in the non-defining relative clause about the neighbour's alarm." },
    { text: "The community award will go to ____ has contributed most to village life this year.", answers: ["whoever"], explanation: "'Whoever' means 'any person who' and acts as the subject of the clause." },
    { text: "Nobody could explain ____ the lights in the corridor kept flickering.", answers: ["why"], explanation: "'Why' introduces an indirect question about the reason for the flickering." },
    { text: "I can't for the life of me remember ____ I put my reading glasses.", answers: ["where"], explanation: "'Where' introduces an indirect question about place after 'remember'." },
    { text: "The 1960s were a decade ____ almost anything seemed possible.", answers: ["when"], explanation: "'When' is the relative adverb used after time expressions such as 'a decade'." },
    { text: "She's one of those rare people ____ you can always rely on in a crisis.", answers: ["who", "whom", "that"], explanation: "The relative pronoun is the object of 'rely on', so 'who', 'whom' or 'that' all fit." },
    { text: "Do you know anyone ____ flat I could borrow for a week in September?", answers: ["whose"], explanation: "'Whose' connects 'anyone' to the flat they possess." },

    /* ---------- fixed phrases ---------- */
    { text: "The two presidents spoke face to ____ for the first time since the border crisis began.", answers: ["face"], explanation: "'Face to face' is a fixed idiom meaning meeting someone in person." },
    { text: "The alarm seems to have gone off all by ____; nobody touched the control panel.", answers: ["itself"], explanation: "'By itself' means without anyone's involvement; the reflexive matches 'the alarm'." },
    { text: "Word of ____ is still the most powerful form of advertising for small restaurants.", answers: ["mouth"], explanation: "'Word of mouth' is a fixed expression for recommendations passed from person to person." },
    { text: "The project fell badly behind schedule, and, to make matters ____, the budget was then cut.", answers: ["worse"], explanation: "'To make matters worse' is a fixed phrase introducing an additional problem." },
    { text: "Entry to the gallery is completely free of ____ for visitors under eighteen.", answers: ["charge"], explanation: "'Free of charge' is a fixed expression meaning that no payment is required." },
    { text: "____ account of the icy conditions, all morning departures were suspended.", answers: ["on"], explanation: "'On account of' is a formal fixed phrase meaning 'because of'." },
    { text: "In ____ of the recent complaints, the café has decided to change its coffee supplier.", answers: ["view", "light"], explanation: "'In view/light of' means 'considering' or 'because of' a situation." },
    { text: "For the time ____, we'll continue working from the old office until the lease is signed.", answers: ["being"], explanation: "'For the time being' is a fixed phrase meaning temporarily, for now." },
    { text: "The two proposals are broadly similar, but they differ ____ one crucial respect.", answers: ["in"], explanation: "'In one/some/every respect' is the fixed pattern for talking about particular aspects." },
    { text: "I'm afraid we have very little in ____ with our new neighbours.", answers: ["common"], explanation: "'Have something/little/nothing in common with' describes shared interests or characteristics." },
    { text: "____ the whole, I'd say the conference was a great success despite the odd hiccup.", answers: ["on"], explanation: "'On the whole' is a fixed phrase meaning generally or all things considered." },
    { text: "The victory was, ____ least in part, the result of sheer good luck.", answers: ["at"], explanation: "'At least in part' means partly; 'at least' is the fixed element here." },

    /* ---------- pronouns and reflexives ---------- */
    { text: "Don't worry about the oven; it switches ____ off automatically after two hours.", answers: ["itself"], explanation: "The reflexive 'itself' shows the oven performs the action on its own." },
    { text: "We thoroughly enjoyed ____ at the street food festival last weekend.", answers: ["ourselves"], explanation: "'Enjoy' needs an object; when the subject is 'we', the reflexive is 'ourselves'." },
    { text: "Anyone locking ____ out of the building after hours should phone the caretaker.", answers: ["themselves", "himself", "herself"], explanation: "With the indefinite 'anyone', the reflexive 'themselves' is the usual modern choice." },
    { text: "The door swung open, and there stood the famous director ____.", answers: ["himself", "herself"], explanation: "An emphatic reflexive after a noun stresses that it really was that very person." },
    { text: "Those gloves aren't ____; mine are the blue ones on the radiator.", answers: ["mine"], explanation: "The possessive pronoun 'mine' stands alone without a following noun." },
    { text: "The film was nowhere near as funny as the trailer had led ____ to believe.", answers: ["us", "me", "everyone"], explanation: "'Lead somebody to believe' needs an object pronoun such as 'us' or 'me'." },
    { text: "If your headphones are broken, you can borrow ____ until yours are repaired.", answers: ["mine", "ours", "some"], explanation: "A possessive pronoun such as 'mine' replaces 'my headphones' to avoid repetition." },
    { text: "The two violinists have played together for years and understand each ____ perfectly on stage.", answers: ["other"], explanation: "'Each other' is the reciprocal pronoun showing the action goes both ways." },
    { text: "____ was so foggy on the motorway that we decided to stop at a service station.", answers: ["it"], explanation: "'It' is the empty subject used for weather expressions like 'it was foggy'." },
    { text: "____ used to be a bakery on this corner, but it closed down years ago.", answers: ["there"], explanation: "'There used to be' introduces the past existence of something." },
    { text: "I've lost my umbrella again, so I suppose I'll have to buy a new ____.", answers: ["one"], explanation: "The pronoun 'one' replaces the singular countable noun 'umbrella' to avoid repetition." },
    { text: "The critics praised the film, but audiences didn't think much of ____.", answers: ["it"], explanation: "The object pronoun 'it' refers back to the singular noun 'the film'." },

    /* ---------- comparison, time and miscellaneous grammar ---------- */
    { text: "The repairs turned out to be far more expensive ____ the garage had first estimated.", answers: ["than"], explanation: "Comparative structures with 'more' require 'than' to introduce the second element." },
    { text: "Her second album isn't nearly ____ good as her extraordinary debut.", answers: ["as", "so"], explanation: "The equality comparison 'as/so... as' is used here in the negative: not as good as." },
    { text: "The village shop opens every day ____ Sundays, when the owner goes fishing.", answers: ["except", "but", "excluding"], explanation: "'Except' introduces the one item excluded from 'every day'." },
    { text: "We haven't seen our old landlord ____ ages, not since we moved across town.", answers: ["for", "in"], explanation: "'For ages' means for a very long time; 'in ages' is also common in informal English." },
    { text: "The overnight train gets ____ Edinburgh at about half past seven in the morning.", answers: ["to", "into"], explanation: "'Get to' means to arrive at a destination; 'get into' also works for stations and cities." },
    { text: "____ being the cheapest option, the hostel was also the friendliest place we stayed.", answers: ["besides"], explanation: "'Besides + -ing' means 'in addition to being'; it introduces an extra positive point." },
    { text: "Cycling in the city is far safer now ____ it was ten years ago.", answers: ["than"], explanation: "The comparative 'safer' requires 'than' before the point of comparison." },
    { text: "The results should appear on screen a few seconds ____ you press the green button.", answers: ["after", "once", "when"], explanation: "A time conjunction such as 'after' links pressing the button to the result." },
    { text: "____ whole neighbourhood turned out to watch the hot-air balloons take off at dawn.", answers: ["the"], explanation: "'The whole + singular noun' means all of it; the definite article is required." },
    { text: "The chef travels to the fish market ____ other day to choose the catch personally.", answers: ["every"], explanation: "'Every other day' is a fixed expression meaning on alternate days." },
    { text: "Believe me, learning to juggle is nowhere near ____ difficult as it looks.", answers: ["as", "so"], explanation: "'Nowhere near as/so... as' is an emphatic negative equality comparison." },
    { text: "The lecture theatre was ____ full that latecomers had to stand at the back.", answers: ["so"], explanation: "'So + adjective + that' expresses cause and result." },
    { text: "We'd barely unpacked the tent ____ it started to pour with rain.", answers: ["when", "before"], explanation: "'Barely... when' links two events that happened almost simultaneously." },
    { text: "____ of the delegates raised their hands, so the motion was passed unopposed.", answers: ["none", "few"], explanation: "'None of' expresses zero quantity with the plural noun 'delegates'." },
    { text: "The chairman spoke ____ behalf of everyone present when he thanked the retiring treasurer.", answers: ["on", "in"], explanation: "'On behalf of' (or 'in behalf of' in American English) means representing others." },
    { text: "Take a business card, just in ____ you think of any questions after the meeting.", answers: ["case"], explanation: "'Just in case' introduces a precaution against a possible future situation." },
    { text: "The new regulations come ____ force at midnight on the first of January.", answers: ["into"], explanation: "'Come into force' is a fixed expression meaning that a law starts to apply." },
    { text: "The path was ____ narrow for the two of us to walk side by side.", answers: ["too"], explanation: "'Too + adjective + for somebody + to-infinitive' means excessively narrow." },
    { text: "____ my astonishment, the stray cat was still waiting on the doorstep the next morning.", answers: ["to"], explanation: "'To my astonishment/surprise' is a fixed phrase introducing an unexpected fact." },
    { text: "The archaeologists worked ____ dawn till dusk to record the site before the floodwaters returned.", answers: ["from"], explanation: "'From dawn till dusk' is a fixed expression meaning all day long." }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part2 = QUESTIONS.part2.concat(BANK);
})();
