/* FCE Prep extra bank: part3 wave 2 */
(function () {
  var BANK = [
    { text: "We waited at the station for the ____ of the night train from Vienna.", stem: "ARRIVE", answers: ["arrival"], explanation: "The verb 'arrive' becomes the noun 'arrival' after 'the' and before 'of'." },
    { text: "Have you replied to the wedding ____ yet?", stem: "INVITE", answers: ["invitation"], explanation: "A noun is needed after 'the wedding'; 'invite' forms the noun 'invitation'." },
    { text: "The article makes an interesting ____ between city life and village life.", stem: "COMPARE", answers: ["comparison"], explanation: "After 'an interesting' we need a noun; 'compare' becomes 'comparison'." },
    { text: "Moving abroad was the hardest ____ she had ever made.", stem: "DECIDE", answers: ["decision"], explanation: "We 'make a decision'; the verb 'decide' becomes the noun 'decision'." },
    { text: "The band gave an unforgettable ____ at the open-air festival.", stem: "PERFORM", answers: ["performance"], explanation: "After 'an unforgettable' a noun is required; 'perform' forms 'performance'." },
    { text: "I have come to a special ____ with my neighbour about sharing the garden.", stem: "ARRANGE", answers: ["arrangement"], explanation: "A noun follows 'a special'; the suffix -ment turns 'arrange' into 'arrangement'." },
    { text: "Engineers are still searching for a cheap ____ to the city's traffic problem.", stem: "SOLVE", answers: ["solution"], explanation: "'A cheap ____ to a problem' needs the noun 'solution', formed from 'solve'." },
    { text: "You need written ____ from a parent to join the school trip.", stem: "PERMIT", answers: ["permission"], explanation: "The noun 'permission' is formed from the verb 'permit'." },
    { text: "The manager dealt with my ____ about the noisy room very politely.", stem: "COMPLAIN", answers: ["complaint"], explanation: "After 'my' a noun is needed; 'complain' becomes 'complaint'." },
    { text: "The telephone is often described as the most important ____ of the nineteenth century.", stem: "INVENT", answers: ["invention"], explanation: "A noun is required after 'the most important'; 'invent' forms 'invention'." },
    { text: "The ____ of faster trains has cut the journey time by half.", stem: "INTRODUCE", answers: ["introduction"], explanation: "The subject of the sentence must be a noun; 'introduce' becomes 'introduction'." },
    { text: "The rapid ____ of the tourist industry has changed the coastline completely.", stem: "DEVELOP", answers: ["development"], explanation: "After 'the rapid' a noun is needed; -ment forms 'development'." },
    { text: "The gallery is holding an ____ of early photographs from the region.", stem: "EXHIBIT", answers: ["exhibition"], explanation: "'An ____ of photographs' requires the noun 'exhibition'." },
    { text: "The whole street joined in the ____ of the team's championship win.", stem: "CELEBRATE", answers: ["celebration"], explanation: "A noun follows 'the'; 'celebrate' becomes 'celebration'." },
    { text: "Some researchers doubt the ____ of life on other planets.", stem: "EXIST", answers: ["existence"], explanation: "After 'the' and before 'of' we need the noun 'existence', from 'exist'." },
    { text: "You should not judge people by their ____ alone.", stem: "APPEAR", answers: ["appearance"], explanation: "A noun is needed after 'their'; 'appear' forms 'appearance'." },
    { text: "Her ____ of difficult French words is remarkably clear.", stem: "PRONOUNCE", answers: ["pronunciation"], explanation: "The noun form of 'pronounce' is 'pronunciation'; note the spelling change." },
    { text: "The suitcase was over the airline's ____ limit, so I had to pay extra.", stem: "WEIGH", answers: ["weight"], explanation: "A noun is needed before 'limit'; the verb 'weigh' becomes the noun 'weight'." },
    { text: "Our ____ to Tokyo was delayed by heavy snow at the airport.", stem: "FLY", answers: ["flight"], explanation: "After 'our' a noun is required; 'fly' forms the irregular noun 'flight'." },
    { text: "The lawyer said there was no real ____ that her client had been at the scene.", stem: "PROVE", answers: ["proof"], explanation: "The verb 'prove' becomes the noun 'proof' after 'no real'." },
    { text: "The ____ of his passport ruined the first day of the holiday.", stem: "LOSE", answers: ["loss"], explanation: "The subject needs a noun; 'lose' becomes the irregular noun 'loss'." },
    { text: "The zookeeper studies the ____ of gorillas in their natural habitat.", stem: "BEHAVE", answers: ["behaviour", "behavior"], explanation: "After 'the' a noun is needed; 'behave' forms 'behaviour'." },
    { text: "Please check the board for your train's ____ time.", stem: "DEPART", answers: ["departure"], explanation: "A noun is needed before 'time'; 'depart' becomes 'departure'." },
    { text: "The sauce is a spicy ____ of tomatoes, garlic and chilli.", stem: "MIX", answers: ["mixture"], explanation: "'A spicy ____ of' requires the noun 'mixture', formed with -ture." },
    { text: "Divers must get used to the ____ of the water at great depths.", stem: "PRESS", answers: ["pressure"], explanation: "After 'the' and before 'of' a noun is needed; 'press' becomes 'pressure'." },
    { text: "The ____ of the harvest left many farming families without an income.", stem: "FAIL", answers: ["failure"], explanation: "The subject must be a noun; 'fail' forms 'failure'." },
    { text: "The restaurant offers free ____ on all orders over twenty euros.", stem: "DELIVER", answers: ["delivery"], explanation: "A noun is needed after 'free'; 'deliver' becomes 'delivery'." },
    { text: "The ____ to the cave is hidden behind a waterfall.", stem: "ENTER", answers: ["entrance"], explanation: "A noun is needed as the subject; 'enter' forms 'entrance'." },
    { text: "The market is famous for the sheer ____ of cheeses on sale.", stem: "VARY", answers: ["variety"], explanation: "After 'the sheer' a noun is required; 'vary' becomes 'variety'." },
    { text: "We enjoyed the ____ of the fire after our walk through the snow.", stem: "WARM", answers: ["warmth"], explanation: "The adjective 'warm' forms the noun 'warmth' with the suffix -th." },
    { text: "It took all his ____ to lift the fallen branch off the path.", stem: "STRONG", answers: ["strength"], explanation: "After 'all his' a noun is needed; 'strong' becomes 'strength'." },
    { text: "The pilot announced that we were flying at a ____ of ten thousand metres.", stem: "HIGH", answers: ["height"], explanation: "'At a ____ of' needs the noun 'height', formed from 'high'." },
    { text: "Measure the ____ of the doorway before you order the new fridge.", stem: "WIDE", answers: ["width"], explanation: "A noun is required after 'the'; 'wide' becomes 'width'." },
    { text: "Nobody believed him, although he was telling the ____ all along.", stem: "TRUE", answers: ["truth"], explanation: "After 'the' a noun is needed; 'true' forms 'truth'." },
    { text: "The ____ in the desert reaches forty-five degrees at midday.", stem: "HOT", answers: ["heat"], explanation: "The subject needs a noun; the adjective 'hot' corresponds to the noun 'heat'." },
    { text: "Working from home has given her the ____ to travel while she earns.", stem: "FREE", answers: ["freedom"], explanation: "A noun is needed after 'the'; 'free' becomes 'freedom' with the suffix -dom." },
    { text: "Villagers would visit the old shepherd for advice, valuing his quiet ____.", stem: "WISE", answers: ["wisdom"], explanation: "After 'his quiet' a noun is required; 'wise' forms 'wisdom'." },
    { text: "I will never forget the ____ the strangers showed us when our car broke down.", stem: "KIND", answers: ["kindness"], explanation: "A noun is needed after 'the'; 'kind' becomes 'kindness'." },
    { text: "Many elderly people say that ____ is harder to bear than poor health.", stem: "LONELY", answers: ["loneliness"], explanation: "The subject requires a noun; 'lonely' forms 'loneliness'." },
    { text: "The campaign aims to raise ____ of the dangers of texting while driving.", stem: "AWARE", answers: ["awareness"], explanation: "We 'raise awareness'; the adjective 'aware' becomes the noun 'awareness'." },
    { text: "Regular swimming has really improved my overall ____.", stem: "FIT", answers: ["fitness"], explanation: "After 'my overall' a noun is needed; 'fit' becomes 'fitness'." },
    { text: "As a child he was crippled by ____, but now he gives talks to huge audiences.", stem: "SHY", answers: ["shyness"], explanation: "A noun is required after 'by'; 'shy' forms 'shyness'." },
    { text: "For reasons of ____, visitors must leave their bags at the entrance.", stem: "SECURE", answers: ["security"], explanation: "'For reasons of' must be followed by a noun; 'secure' becomes 'security'." },
    { text: "Her endless ____ about how machines work led her to study engineering.", stem: "CURIOUS", answers: ["curiosity"], explanation: "After 'her endless' a noun is needed; 'curious' forms 'curiosity'." },
    { text: "Looking after the class hamster taught the children a sense of ____.", stem: "RESPONSIBLE", answers: ["responsibility"], explanation: "'A sense of' requires a noun; 'responsible' becomes 'responsibility'." },
    { text: "Dolphins have a surprising ____ to learn complicated tricks.", stem: "ABLE", answers: ["ability"], explanation: "After 'a surprising' a noun is needed; 'able' forms 'ability'." },
    { text: "The job offers great ____, as staff can choose their own working hours.", stem: "FLEXIBLE", answers: ["flexibility"], explanation: "A noun follows 'great'; 'flexible' becomes 'flexibility'." },
    { text: "The ____ of the universe is still one of science's biggest questions.", stem: "CREATE", answers: ["creation"], explanation: "After 'the' and before 'of' we need a noun; 'create' becomes 'creation'." },
    { text: "Thanks to the ____ of local businesses, the shelter raised enough money in a week.", stem: "GENEROUS", answers: ["generosity"], explanation: "A noun is required after 'the'; 'generous' forms 'generosity'." },
    { text: "The young ____ promised voters she would improve the region's schools.", stem: "POLITICS", answers: ["politician"], explanation: "A person noun is needed; 'politics' forms 'politician'." },
    { text: "We had to call an ____ when the lights in the kitchen stopped working.", stem: "ELECTRIC", answers: ["electrician"], explanation: "A person noun is required; 'electric' becomes 'electrician'." },
    { text: "The ____ spent six months interviewing families affected by the floods.", stem: "JOURNAL", answers: ["journalist"], explanation: "A person noun is needed as the subject; 'journal' forms 'journalist'." },
    { text: "Many ____ believe that raising interest rates will slow the economy down.", stem: "ECONOMY", answers: ["economists"], explanation: "A plural person noun is needed; 'economy' forms 'economist', here plural." },
    { text: "Every ____ at the factory receives a bonus in December.", stem: "EMPLOY", answers: ["employee"], explanation: "The suffix -ee gives the person who is employed: 'employee'." },
    { text: "The dentist's ____ phoned to remind me about my appointment.", stem: "ASSIST", answers: ["assistant"], explanation: "A person noun is needed; 'assist' becomes 'assistant'." },
    { text: "The novel's ____ managed to keep the humour of the original Spanish.", stem: "TRANSLATE", answers: ["translator"], explanation: "The suffix -or gives the person noun 'translator'." },
    { text: "The retired ____ told us stories about crossing the Atlantic in storms.", stem: "SAIL", answers: ["sailor"], explanation: "A person noun is needed; 'sail' forms 'sailor'." },
    { text: "The ____ helped me find several rare books for my project.", stem: "LIBRARY", answers: ["librarian"], explanation: "A person noun is required; 'library' becomes 'librarian'." },
    { text: "A local ____ has written a book about the castle's seven-hundred-year past.", stem: "HISTORY", answers: ["historian"], explanation: "A person noun is needed; 'history' forms 'historian'." },
    { text: "My uncle is a keen stamp ____ and owns over ten thousand different ones.", stem: "COLLECT", answers: ["collector"], explanation: "A person noun is required; 'collect' becomes 'collector'." },
    { text: "After three ____ attempts, she finally passed her driving test.", stem: "SUCCESS", answers: ["unsuccessful"], explanation: "The context (she passed only after these attempts) needs the negative adjective 'unsuccessful'." },
    { text: "Don't worry about the spider; it is completely ____.", stem: "HARM", answers: ["harmless"], explanation: "The reassuring context requires the adjective 'harmless', formed with -less." },
    { text: "It is ____ to argue with him once he has made up his mind.", stem: "USE", answers: ["useless"], explanation: "The meaning 'pointless' requires the negative adjective 'useless'." },
    { text: "Despite the bad weather, the climbers remained ____ about reaching the summit.", stem: "HOPE", answers: ["hopeful"], explanation: "An adjective is needed after 'remained'; 'hope' forms 'hopeful'." },
    { text: "The parade filled the grey streets with ____ costumes and music.", stem: "COLOUR", answers: ["colourful", "colorful"], explanation: "An adjective is needed before 'costumes'; 'colour' becomes 'colourful'." },
    { text: "The nurse promised that the injection would be almost ____.", stem: "PAIN", answers: ["painless"], explanation: "The reassuring meaning requires 'painless', i.e. without pain." },
    { text: "We moved to the countryside because our old flat was on a terribly ____ street.", stem: "NOISE", answers: ["noisy"], explanation: "An adjective is needed before 'street'; 'noise' forms 'noisy'." },
    { text: "Drivers were warned to slow down because the motorway was extremely ____.", stem: "FOG", answers: ["foggy"], explanation: "After 'extremely' an adjective is needed; 'fog' becomes 'foggy'." },
    { text: "Skipping breakfast every day is a very ____ habit, according to my doctor.", stem: "HEALTH", answers: ["unhealthy"], explanation: "The context of a bad habit requires the negative adjective 'unhealthy'." },
    { text: "The hotel was built by a ____ businessman who made his money in shipping.", stem: "WEALTH", answers: ["wealthy"], explanation: "An adjective is needed before 'businessman'; 'wealth' forms 'wealthy'." },
    { text: "For their anniversary they stayed in a ____ suite overlooking the bay.", stem: "LUXURY", answers: ["luxurious"], explanation: "An adjective is needed before 'suite'; 'luxury' becomes 'luxurious'." },
    { text: "The lights in the sky remained a ____ event that nobody could explain.", stem: "MYSTERY", answers: ["mysterious"], explanation: "An adjective is required before 'event'; 'mystery' forms 'mysterious'." },
    { text: "You have to be quite ____ to try street food in an unfamiliar country.", stem: "ADVENTURE", answers: ["adventurous"], explanation: "An adjective is needed after 'quite'; 'adventure' becomes 'adventurous'." },
    { text: "Building a railway across the mountains was an ____ plan for its time.", stem: "AMBITION", answers: ["ambitious"], explanation: "An adjective is required before 'plan'; 'ambition' forms 'ambitious'." },
    { text: "The shampoo contains only ____ ingredients such as herbs and oils.", stem: "NATURE", answers: ["natural"], explanation: "An adjective is needed before 'ingredients'; 'nature' becomes 'natural'." },
    { text: "The hotel's ____ location means every museum is within walking distance.", stem: "CENTRE", answers: ["central"], explanation: "An adjective is needed before 'location'; 'centre' forms 'central'." },
    { text: "Please do not read my diary; it contains my ____ thoughts.", stem: "PERSON", answers: ["personal"], explanation: "An adjective is required before 'thoughts'; 'person' becomes 'personal'." },
    { text: "The stadium will host the ____ championships for the first time in a decade.", stem: "NATION", answers: ["national"], explanation: "An adjective is needed before 'championships'; 'nation' forms 'national'." },
    { text: "The river was badly polluted by ____ waste from the nearby plants.", stem: "INDUSTRY", answers: ["industrial"], explanation: "An adjective is needed before 'waste'; 'industry' becomes 'industrial'." },
    { text: "The couple asked an adviser for help with their ____ planning.", stem: "FINANCE", answers: ["financial"], explanation: "An adjective is required before 'planning'; 'finance' forms 'financial'." },
    { text: "Strawberry picking is only ____ work, lasting from June until August.", stem: "SEASON", answers: ["seasonal"], explanation: "An adjective is needed before 'work'; 'season' becomes 'seasonal'." },
    { text: "After years of playing for fun, she finally became a ____ tennis player.", stem: "PROFESSION", answers: ["professional"], explanation: "An adjective is needed before 'tennis player'; 'profession' forms 'professional'." },
    { text: "The audio guide made the tour of the palace far more ____.", stem: "ENJOY", answers: ["enjoyable"], explanation: "An adjective is needed after 'more'; 'enjoy' becomes 'enjoyable'." },
    { text: "The weather in these mountains is so ____ that hikers must always carry warm clothes.", stem: "PREDICT", answers: ["unpredictable"], explanation: "The context (must always be prepared) requires the negative adjective 'unpredictable'." },
    { text: "Watching the sun rise over the volcano was a truly ____ experience.", stem: "FORGET", answers: ["unforgettable"], explanation: "The positive meaning 'impossible to forget' requires 'unforgettable'." },
    { text: "Some delays are simply ____ when you travel during the holiday season.", stem: "AVOID", answers: ["unavoidable"], explanation: "The meaning 'cannot be avoided' requires the adjective 'unavoidable'." },
    { text: "The wooden benches at the old stadium were hard and ____.", stem: "COMFORT", answers: ["uncomfortable"], explanation: "The context (hard benches) requires the negative adjective 'uncomfortable'." },
    { text: "Eating out in the capital is far more ____ than in the smaller towns.", stem: "EXPENSE", answers: ["expensive"], explanation: "An adjective is needed after 'more'; 'expense' becomes 'expensive'." },
    { text: "The palace ceilings are covered in ____ paintings of birds and flowers.", stem: "DECORATE", answers: ["decorative"], explanation: "An adjective is needed before 'paintings'; 'decorate' forms 'decorative'." },
    { text: "Critics describe the sixteen-year-old pianist as the most ____ musician of her generation.", stem: "TALENT", answers: ["talented"], explanation: "An adjective is needed before 'musician'; 'talent' becomes 'talented'." },
    { text: "The factory is struggling to find enough ____ workers to operate the new machines.", stem: "SKILL", answers: ["skilled"], explanation: "An adjective is required before 'workers'; 'skill' forms 'skilled'." },
    { text: "The company prefers not to send ____ staff to deal with important clients.", stem: "EXPERIENCE", answers: ["inexperienced"], explanation: "The context ('prefers not to send') requires the negative adjective 'inexperienced'." },
    { text: "____ in the region rose sharply after the mine closed down.", stem: "EMPLOY", answers: ["unemployment"], explanation: "The subject must be a noun, and the context of the mine closing requires the negative noun 'unemployment'." },
    { text: "Try not to lose your ____ when the toddler asks the same question again and again.", stem: "PATIENT", answers: ["patience"], explanation: "After 'your' a noun is needed; 'patient' forms 'patience'." },
    { text: "Drinking plenty of water is a simple but ____ way to reduce headaches.", stem: "EFFECT", answers: ["effective"], explanation: "An adjective is needed before 'way'; 'effect' becomes 'effective'." },
    { text: "The brochure makes the resort look far more ____ than it really is.", stem: "ATTRACT", answers: ["attractive"], explanation: "An adjective is needed after 'more'; 'attract' forms 'attractive'." },
    { text: "At eighteen she moved out, keen to be ____ of her parents at last.", stem: "DEPEND", answers: ["independent"], explanation: "The context of leaving home requires the adjective 'independent'." },
    { text: "The team's victory was completely ____, as they had lost every match that season.", stem: "EXPECT", answers: ["unexpected"], explanation: "The surprising context requires the negative adjective 'unexpected'." },
    { text: "It has been ____ warm for October, so the beaches are still busy.", stem: "USUAL", answers: ["unusually"], explanation: "An adverb is needed to modify the adjective 'warm'; 'usual' forms 'unusually'." },
    { text: "I had ____ forgotten about the meeting until my phone reminded me.", stem: "COMPLETE", answers: ["completely"], explanation: "An adverb is needed to modify 'forgotten'; 'complete' becomes 'completely'." },
    { text: "If you smell gas, leave the building ____ and call for help.", stem: "IMMEDIATE", answers: ["immediately"], explanation: "An adverb is required to modify 'leave'; 'immediate' forms 'immediately'." },
    { text: "After circling the airport for an hour, the plane ____ received permission to land.", stem: "FINAL", answers: ["finally"], explanation: "An adverb is needed to modify the verb; 'final' becomes 'finally'." },
    { text: "The ____ between the twins' voices makes them impossible to tell apart on the phone.", stem: "SIMILAR", answers: ["similarity"], explanation: "The subject needs a noun; 'similar' forms 'similarity'." },
    { text: "You should back up your files ____ so that nothing important is lost.", stem: "REGULAR", answers: ["regularly"], explanation: "An adverb is needed to modify 'back up'; 'regular' becomes 'regularly'." },
    { text: "The gymnast landed ____ and the judges awarded her top marks.", stem: "PERFECT", answers: ["perfectly"], explanation: "An adverb is required to modify 'landed'; 'perfect' forms 'perfectly'." },
    { text: "The cat crept ____ towards the sparrow on the lawn.", stem: "SILENT", answers: ["silently"], explanation: "An adverb is needed to modify 'crept'; 'silent' becomes 'silently'." },
    { text: "He slammed the door and walked off ____ without another word.", stem: "ANGRY", answers: ["angrily"], explanation: "An adverb is needed to modify 'walked off'; 'angry' forms 'angrily'." },
    { text: "Money alone cannot buy ____, as my grandmother often reminds me.", stem: "HAPPY", answers: ["happiness"], explanation: "The object of 'buy' must be a noun; 'happy' becomes 'happiness'." },
    { text: "The coach's job is to ____ young players rather than criticise their mistakes.", stem: "COURAGE", answers: ["encourage"], explanation: "A verb is needed after 'to'; the prefix en- turns 'courage' into 'encourage'." },
    { text: "Daily stretching exercises will gradually ____ the muscles around your knee.", stem: "STRENGTH", answers: ["strengthen"], explanation: "A verb is needed after 'will'; the suffix -en turns 'strength' into 'strengthen'." },
    { text: "The council plans to ____ the main road so that lorries can pass each other safely.", stem: "WIDE", answers: ["widen"], explanation: "A verb is required after 'to'; 'wide' becomes 'widen' with the suffix -en." },
    { text: "If you are ____ about which course to choose, talk to a careers adviser.", stem: "SURE", answers: ["unsure"], explanation: "The context of needing advice requires the negative adjective 'unsure'." },
    { text: "Walking through the empty house at night was a genuinely ____ experience.", stem: "FRIGHT", answers: ["frightening"], explanation: "An adjective describing the experience is needed; 'fright' forms 'frightening'." },
    { text: "To his great ____, he called the teacher 'Mum' in front of the whole class.", stem: "EMBARRASS", answers: ["embarrassment"], explanation: "After 'his great' a noun is needed; 'embarrass' forms 'embarrassment'." },
    { text: "She could not hide her ____ when the trip was cancelled at the last minute.", stem: "DISAPPOINT", answers: ["disappointment"], explanation: "A noun is needed after 'her'; 'disappoint' becomes 'disappointment'." },
    { text: "I find it really ____ when people chat during the film.", stem: "ANNOY", answers: ["annoying"], explanation: "An adjective describing the situation is needed; 'annoy' forms 'annoying'." },
    { text: "The market gets so ____ on Saturdays that it is hard to move.", stem: "CROWD", answers: ["crowded"], explanation: "An adjective is needed after 'so'; 'crowd' becomes 'crowded'." },
    { text: "The soup looked strange, but it turned out to be surprisingly ____.", stem: "TASTE", answers: ["tasty"], explanation: "An adjective is needed after 'surprisingly'; 'taste' forms 'tasty'." },
    { text: "The forecast promises a ____ weekend, so let's go to the coast.", stem: "SUN", answers: ["sunny"], explanation: "An adjective is needed before 'weekend'; 'sun' becomes 'sunny'." },
    { text: "The ferry was cancelled because the sea was too ____ to cross.", stem: "STORM", answers: ["stormy"], explanation: "An adjective is needed after 'too'; 'storm' forms 'stormy'." },
    { text: "It is highly ____ that the match will go ahead in this rain.", stem: "LIKELY", answers: ["unlikely"], explanation: "The context of heavy rain requires the negative adjective 'unlikely'." },
    { text: "Check your answers ____ before you hand the paper in.", stem: "CARE", answers: ["carefully"], explanation: "An adverb is needed to modify 'check'; 'care' forms 'carefully'." },
    { text: "The keeper made a ____ mistake that cost his team the cup.", stem: "COST", answers: ["costly"], explanation: "An adjective is needed before 'mistake'; 'cost' forms 'costly', meaning very damaging." },
    { text: "Her ____ to animals was clear from the moment she entered the stables.", stem: "DEVOTE", answers: ["devotion"], explanation: "The subject needs a noun; 'devote' becomes 'devotion'." },
    { text: "The instructions were so ____ that we gave up and phoned the helpline.", stem: "CONFUSE", answers: ["confusing"], explanation: "An adjective describing the instructions is needed; 'confuse' forms 'confusing'." }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part3 = QUESTIONS.part3.concat(BANK);
})();
