/* FCE Prep extra bank: speaking */
(function () {
  var BANK = [
    { question: "Why do some students find it hard to concentrate when studying at home?", bullets: ["phones and social media", "noisy family members", "no fixed routine"] },
    { question: "What are the advantages of learning to cook at a young age?", bullets: ["healthier eating habits", "independence from parents", "saving money later"] },
    { question: "Why do so many people enjoy watching sport rather than playing it?", bullets: ["excitement without effort", "supporting a team together", "admiring professional skill"] },
    { question: "How has the way people listen to music changed in recent years?", bullets: ["streaming instead of CDs", "listening anywhere with earphones", "discovering new artists online"] },
    { question: "Why is it important for children to have hobbies outside school?", bullets: ["developing new skills", "making friends with similar interests", "relaxing after lessons"] },
    { question: "What can people do to protect the environment in their daily lives?", bullets: ["recycling and reducing waste", "using public transport", "saving water and electricity"] },
    { question: "Why do some people prefer reading books to watching films?", bullets: ["using their imagination", "more detail about characters", "reading at their own pace"] },
    { question: "What makes a good teacher, in your opinion?", bullets: ["patience with slow learners", "making lessons interesting", "treating students fairly"] },
    { question: "Why do many young people want to become famous?", bullets: ["money and luxury lifestyle", "attention on social media", "being admired by others"] },
    { question: "What are the benefits of doing regular exercise?", bullets: ["staying fit and healthy", "reducing stress", "sleeping better at night"] },
    { question: "Why do people keep pets?", bullets: ["company and friendship", "teaching children responsibility", "encouragement to go outside"] },
    { question: "How do smartphones change the way families spend time together?", bullets: ["everyone looking at screens", "easier to stay in contact", "sharing photos and memories"] },
    { question: "Why is breakfast considered an important meal?", bullets: ["energy for the morning", "better concentration at school", "a moment together as a family"] },
    { question: "What are the advantages of working in a team rather than alone?", bullets: ["sharing different ideas", "finishing tasks faster", "learning from each other"] },
    { question: "Why do some people prefer shopping in markets rather than supermarkets?", bullets: ["fresher local products", "talking to the sellers", "lively atmosphere"] },
    { question: "What can young people learn from spending time with their grandparents?", bullets: ["stories about the past", "traditional skills and recipes", "patience and different values"] },
    { question: "Why is it useful to learn how to manage money as a teenager?", bullets: ["avoiding debt later", "understanding the value of things", "saving for bigger goals"] },
    { question: "What makes a city a good place for young people to live?", bullets: ["colleges and job opportunities", "cheap transport", "places to meet friends"] },
    { question: "Why do people enjoy taking photographs?", bullets: ["keeping memories of special moments", "sharing experiences with others", "expressing creativity"] },
    { question: "What are the advantages and disadvantages of studying with music on?", bullets: ["blocking out other noise", "songs with words distract", "depends on the task"] },
    { question: "Why do some people choose to become vegetarians?", bullets: ["health reasons", "concern for animals", "environmental impact of meat"] },
    { question: "How important is it for young people to play a musical instrument?", bullets: ["discipline from daily practice", "a skill for life", "playing together with others"] },
    { question: "Why do many people find public speaking difficult?", bullets: ["fear of making mistakes", "everyone watching you", "lack of practice"] },
    { question: "What are the benefits of having a best friend?", bullets: ["someone to trust with secrets", "support in difficult times", "sharing fun activities"] },
    { question: "Why do people enjoy cooking for others?", bullets: ["showing care and love", "sharing their culture", "pride when guests enjoy the food"] },
    { question: "How can schools encourage students to read more?", bullets: ["comfortable reading spaces", "letting students choose books", "book clubs and competitions"] },
    { question: "Why do some people prefer to travel by train rather than by plane?", bullets: ["enjoying the scenery", "less stressful than airports", "better for the environment"] },
    { question: "What are the advantages of living in a small flat?", bullets: ["easier to clean", "cheaper rent and bills", "encourages owning less stuff"] },
    { question: "Why is sleep so important for teenagers?", bullets: ["growing bodies need rest", "better memory for studying", "improved mood during the day"] },
    { question: "What can people do to make new friends when they move to a new place?", bullets: ["joining clubs or sports teams", "talking to neighbours", "accepting invitations even when shy"] },
    { question: "Why do people enjoy festivals and celebrations?", bullets: ["a break from routine", "spending time with family", "keeping traditions alive"] },
    { question: "How has online shopping changed people's habits?", bullets: ["buying at any time of day", "comparing prices easily", "buying things they don't need"] },
    { question: "Why do some students choose to study abroad?", bullets: ["improving a foreign language", "experiencing a new culture", "better career opportunities"] },
    { question: "What are the benefits of spending time in nature?", bullets: ["fresh air and exercise", "escaping from screens", "feeling calm and relaxed"] },
    { question: "Why do people volunteer to help others without being paid?", bullets: ["feeling useful to the community", "meeting new people", "gaining experience for work"] },
    { question: "How important is fashion to young people today?", bullets: ["expressing personality", "pressure from social media", "fitting in with friends"] },
    { question: "Why do some families eat together less often than in the past?", bullets: ["busy work schedules", "eating in front of screens", "different timetables at home"] },
    { question: "What are the advantages of having a part-time job as a student?", bullets: ["earning your own money", "learning to be responsible", "experience for the future"] },
    { question: "Why do people enjoy watching cooking programmes on TV?", bullets: ["getting new recipe ideas", "entertaining competitions", "watching skills they admire"] },
    { question: "How can technology help people learn languages?", bullets: ["apps for daily practice", "watching films with subtitles", "talking to native speakers online"] },
    { question: "Why is it important to drink enough water every day?", bullets: ["concentration and energy", "healthy skin and body", "cheaper and better than soft drinks"] },
    { question: "What makes a birthday celebration memorable?", bullets: ["surprises from friends", "being with the people you love", "doing something unusual"] },
    { question: "Why do some people prefer old buildings to modern ones?", bullets: ["history and character", "beautiful traditional details", "connection to the past"] },
    { question: "How can parents encourage children to spend less time on screens?", bullets: ["setting a good example", "offering fun alternatives", "agreeing clear rules together"] },
    { question: "Why do people enjoy board games and card games?", bullets: ["face-to-face fun with friends", "friendly competition", "no batteries or wifi needed"] },
    { question: "What are the benefits of walking or cycling to school or work?", bullets: ["daily exercise for free", "avoiding traffic jams", "reducing pollution"] },
    { question: "Why is teamwork important in most jobs?", bullets: ["combining different strengths", "solving problems faster", "supporting colleagues under pressure"] },
    { question: "How do advertisements influence what people buy?", bullets: ["creating desire for new products", "using famous faces", "making things seem cheaper than they are"] }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  SPEAKING = SPEAKING.concat(BANK);
})();
