/* FCE Prep extra bank: vocab wave 3 */
(function () {
  var BANK = [
    // ===== Education / school life =====
    { front: "enrol", pos: "v.", def: "to officially join a course, school or class", example: "She enrolled on an evening Spanish course at the local college.", zh: "註冊、報名（課程）" },
    { front: "attendance", pos: "n.", def: "the fact of being present at school or an event", example: "His attendance improved a lot after the teacher spoke to his parents.", zh: "出席、出席率" },
    { front: "absence", pos: "n.", def: "a time when you are not at school or work", example: "The school asks parents to explain every absence with a note.", zh: "缺席" },
    { front: "headteacher", pos: "n.", def: "the teacher in charge of a school", example: "The headteacher gave a short speech on the first day of term.", zh: "校長" },
    { front: "professor", pos: "n.", def: "a teacher of the highest rank at a university", example: "Our history professor makes even boring dates sound exciting.", zh: "教授" },
    { front: "seminar", pos: "n.", def: "a class in which a small group discusses a subject", example: "We have a two-hour seminar on modern literature every Friday.", zh: "研討課、專題討論課" },
    { front: "tutorial", pos: "n.", def: "a lesson for one student or a small group", example: "I asked a question about the essay during my weekly tutorial.", zh: "個別指導課" },
    { front: "textbook", pos: "n.", def: "a book used for studying a subject at school", example: "Please open your textbooks to page forty-two.", zh: "教科書" },
    { front: "stationery", pos: "n.", def: "pens, paper and other things used for writing", example: "I bought some new stationery before the school year started.", zh: "文具" },
    { front: "classmate", pos: "n.", def: "someone who is in the same class as you", example: "A classmate lent me her notes when I was ill.", zh: "同班同學" },
    { front: "essay", pos: "n.", def: "a short piece of writing on a subject, done for school", example: "We have to write a five-hundred-word essay on climate change.", zh: "文章、短論文" },
    { front: "discipline", pos: "n.", def: "training that makes people follow rules and behave well", example: "The new teacher found it hard to keep discipline in class.", zh: "紀律" },
    { front: "strict", pos: "adj.", def: "demanding that rules are obeyed exactly", example: "Our maths teacher is strict but always fair.", zh: "嚴格的" },
    { front: "grade", pos: "n.", def: "a mark or level that shows how good work is", example: "He got the top grade in his final English exam.", zh: "成績、等級" },
    { front: "assess", pos: "v.", def: "to judge the quality or level of something", example: "Students are assessed through coursework and a written exam.", zh: "評量、評估" },
    { front: "assessment", pos: "n.", def: "the act of judging how good something is", example: "There is a short assessment at the end of each unit.", zh: "評量、測驗" },
    { front: "concentrate", pos: "v.", def: "to give all your attention to something", example: "I cannot concentrate on my homework when the TV is on.", zh: "專心、集中注意力" },
    { front: "concentration", pos: "n.", def: "the ability to keep your attention on something", example: "Loud music in the library destroys my concentration.", zh: "專注力" },
    { front: "distract", pos: "v.", def: "to take someone's attention away from what they are doing", example: "Please do not distract your sister while she is studying.", zh: "使分心" },
    { front: "distraction", pos: "n.", def: "something that takes your attention away", example: "My phone is the biggest distraction when I revise.", zh: "令人分心的事物" },
    { front: "motivation", pos: "n.", def: "the desire or reason to do something", example: "Good teachers know how to build motivation in weaker students.", zh: "動機、積極性" },
    { front: "curiosity", pos: "n.", def: "a strong wish to know or learn about things", example: "Out of pure curiosity, she read every book on the shelf.", zh: "好奇心" },
    { front: "intelligence", pos: "n.", def: "the ability to learn, understand and think", example: "Exam results do not always show a person's real intelligence.", zh: "智力" },
    { front: "talented", pos: "adj.", def: "having a natural ability to do something well", example: "She is a talented musician who taught herself the piano.", zh: "有天賦的" },
    { front: "gifted", pos: "adj.", def: "having an unusually high natural ability", example: "The school runs extra classes for gifted children.", zh: "資賦優異的" },
    { front: "detention", pos: "n.", def: "a punishment where a student stays at school after lessons", example: "He got a detention for arriving late three times.", zh: "課後留校處分" },
    { front: "expel", pos: "v.", def: "to force a student to leave a school permanently", example: "Two boys were expelled for stealing from the science lab.", zh: "開除、退學" },
    { front: "suspend", pos: "v.", def: "to stop someone from attending school for a period as punishment", example: "She was suspended for a week after the fight.", zh: "勒令停學" },
    { front: "punish", pos: "v.", def: "to make someone suffer because they broke a rule", example: "The teacher punished the class by cancelling the trip.", zh: "處罰" },
    { front: "reward", pos: "n.", def: "something given for good work or behaviour", example: "The students got an afternoon off as a reward for their effort.", zh: "獎賞、報酬" },
    { front: "praise", pos: "v.", def: "to say that someone has done something well", example: "The teacher praised her for the imaginative ending of her story.", zh: "稱讚" },
    { front: "criticise", pos: "v.", def: "to say what is bad or wrong about someone or something", example: "It is easy to criticise, but much harder to suggest a better plan.", zh: "批評" },
    { front: "feedback", pos: "n.", def: "comments about how well or badly someone is doing", example: "The tutor gave me useful feedback on my first draft.", zh: "回饋意見" },
    { front: "bilingual", pos: "adj.", def: "able to speak two languages equally well", example: "Growing up in Canada, she became fully bilingual.", zh: "雙語的" },
    { front: "fluency", pos: "n.", def: "the ability to speak a language easily and well", example: "A year abroad really improved his fluency in French.", zh: "流利度" },
    { front: "pronounce", pos: "v.", def: "to make the sound of a word correctly", example: "I still cannot pronounce some of the longer German words.", zh: "發音" },
    { front: "pronunciation", pos: "n.", def: "the way a word is said", example: "Her pronunciation is so clear that everyone understands her.", zh: "發音（方式）" },
    { front: "graduation", pos: "n.", def: "the ceremony when you complete your studies", example: "The whole family flew over for her graduation.", zh: "畢業（典禮）" },
    { front: "diploma", pos: "n.", def: "a document showing you have finished a course of study", example: "He earned a diploma in graphic design last summer.", zh: "文憑" },
    { front: "admission", pos: "n.", def: "permission to enter a school or university", example: "Admission to the course depends on your exam results.", zh: "入學許可" },
    { front: "canteen", pos: "n.", def: "a place in a school or workplace where meals are served", example: "The canteen serves hot lunches from twelve o'clock.", zh: "餐廳、食堂" },
    { front: "playground", pos: "n.", def: "an outdoor area where children play at school", example: "The children raced out to the playground at break time.", zh: "操場、遊樂場" },
    { front: "nursery", pos: "n.", def: "a school for very young children", example: "My daughter started nursery when she was three.", zh: "幼兒園" },
    { front: "whiteboard", pos: "n.", def: "a white surface teachers write on in class", example: "The teacher wrote the homework on the whiteboard.", zh: "白板" },
    { front: "principal", pos: "n.", def: "the person in charge of a school or college", example: "The principal welcomed the new students at the assembly.", zh: "校長" },
    { front: "revision", pos: "n.", def: "the work of studying again for an exam", example: "I made a revision plan two months before the exams.", zh: "複習" },
    { front: "faculty", pos: "n.", def: "a department or group of departments in a university", example: "She teaches in the Faculty of Engineering.", zh: "（大學的）學院、系所" },
    { front: "misbehave", pos: "v.", def: "to behave badly", example: "If you misbehave in class, you will stay behind after school.", zh: "行為不端、調皮搗蛋" },
    { front: "bookworm", pos: "n.", def: "a person who loves reading books", example: "My brother is a real bookworm and finishes a novel every week.", zh: "書呆子、愛書人" },
    { front: "literate", pos: "adj.", def: "able to read and write", example: "By the end of the year, all the children were fully literate.", zh: "識字的、有讀寫能力的" },
    { front: "swot up", pos: "phr. v.", def: "to study something hard, especially before an exam", example: "I need to swot up on irregular verbs before Friday's test.", zh: "臨時抱佛腳、用功苦讀" },
    { front: "sail through", pos: "phr. v.", def: "to pass a test or deal with something very easily", example: "She sailed through her driving test on the first attempt.", zh: "輕鬆通過" },
    { front: "scrape through", pos: "phr. v.", def: "to only just pass an exam or test", example: "He did no revision and barely scraped through the exam.", zh: "勉強通過" },
    { front: "breeze through", pos: "phr. v.", def: "to do something quickly and easily", example: "She breezed through the interview and got the place.", zh: "輕鬆完成" },
    { front: "catch up on", pos: "phr. v.", def: "to do something you did not have time to do earlier", example: "I spent the weekend catching up on all my homework.", zh: "補上（落後的事）" },
    { front: "keep up", pos: "phr. v.", def: "to move or progress at the same speed as others", example: "The lessons are fast, but most students manage to keep up.", zh: "跟上進度" },
    { front: "take in", pos: "phr. v.", def: "to fully understand or absorb information", example: "The lecture was so fast that I could not take it all in.", zh: "理解、吸收" },
    { front: "sink in", pos: "phr. v.", def: "to gradually become fully understood", example: "It took a while for the news about the exam results to sink in.", zh: "（逐漸）被理解、領悟" },
    { front: "hand back", pos: "phr. v.", def: "to return something to the person who owns it", example: "The teacher handed back our tests with comments on them.", zh: "發還、歸還" },
    { front: "rub out", pos: "phr. v.", def: "to remove writing with an eraser", example: "Rub out that answer and write the correct one.", zh: "擦掉" },
    { front: "note down", pos: "phr. v.", def: "to write something quickly so you remember it", example: "Note down the key dates before the lesson ends.", zh: "記下" },
    { front: "jot down", pos: "phr. v.", def: "to write something quickly and informally", example: "I jotted down her phone number on the back of my notebook.", zh: "匆匆記下" },
    { front: "read up on", pos: "phr. v.", def: "to read a lot about a subject to learn about it", example: "Before the debate, I read up on renewable energy.", zh: "研讀、鑽研" },
    { front: "write down", pos: "phr. v.", def: "to record something on paper", example: "Write down the homework before you leave the classroom.", zh: "寫下" },
    { front: "write up", pos: "phr. v.", def: "to write something in a complete or final form", example: "After the experiment, we had to write up our results.", zh: "整理撰寫（報告）" },
    { front: "read out", pos: "phr. v.", def: "to say written words aloud for others to hear", example: "The teacher read out the winners of the poetry competition.", zh: "朗讀、宣讀" },
    { front: "call out", pos: "phr. v.", def: "to say something loudly, often to get attention", example: "Do not call out the answer; put your hand up instead.", zh: "大聲喊出" },
    { front: "team up", pos: "phr. v.", def: "to join another person to work together", example: "We teamed up with another class for the science project.", zh: "合作、組隊" },
    { front: "pair up", pos: "phr. v.", def: "to form groups of two", example: "The teacher asked us to pair up and practise the dialogue.", zh: "兩兩一組" },
    { front: "line up", pos: "phr. v.", def: "to stand in a row, one behind another", example: "The pupils lined up quietly outside the classroom.", zh: "排隊" },
    { front: "pick up on", pos: "phr. v.", def: "to notice something that is not obvious", example: "A good teacher picks up on the small mistakes students repeat.", zh: "察覺到" },
    { front: "read through", pos: "phr. v.", def: "to read something from beginning to end to check it", example: "Always read through your essay before you hand it in.", zh: "通讀、從頭讀到尾" },
    { front: "sit an exam", pos: "collocation", def: "to take an official test", example: "Students sit their final exams in June.", zh: "參加考試" },
    { front: "mock exam", pos: "collocation", def: "a practice exam taken before the real one", example: "The mock exams showed me which topics I needed to revise.", zh: "模擬考" },
    { front: "past paper", pos: "collocation", def: "an exam paper from a previous year used for practice", example: "Doing past papers is the best way to prepare for the test.", zh: "歷屆考題" },
    { front: "gap year", pos: "collocation", def: "a year between school and university spent travelling or working", example: "He took a gap year to travel around South America.", zh: "空檔年" },
    { front: "school uniform", pos: "collocation", def: "the special clothes students must wear at some schools", example: "Our school uniform is a grey jumper and black trousers.", zh: "學校制服" },
    { front: "give a presentation", pos: "collocation", def: "to talk formally to a group about a topic", example: "Each student has to give a presentation on a famous scientist.", zh: "做簡報" },
    { front: "get good grades", pos: "collocation", def: "to receive high marks at school", example: "She works hard because she wants to get good grades.", zh: "取得好成績" },
    { front: "attend a lecture", pos: "collocation", def: "to go to a formal talk at a university", example: "First-year students must attend a lecture on study skills.", zh: "聽講座、上大課" },
    { front: "do a degree", pos: "collocation", def: "to study for a university qualification", example: "She is doing a degree in biology at Manchester.", zh: "攻讀學位" },
    { front: "play truant", pos: "collocation", def: "to stay away from school without permission", example: "He played truant so often that the school contacted his parents.", zh: "逃學、曠課" },
    { front: "pass with flying colours", pos: "idiom", def: "to succeed in a test very easily and well", example: "She passed her final exams with flying colours.", zh: "高分通過、出色地通過" },
    { front: "teacher's pet", pos: "idiom", def: "a student who the teacher likes best", example: "He always answers first, so everyone calls him the teacher's pet.", zh: "老師的寵兒" },
    { front: "make the grade", pos: "idiom", def: "to reach the necessary standard to succeed", example: "Only a few players make the grade and turn professional.", zh: "達到標準、合格" },
    { front: "learn the hard way", pos: "idiom", def: "to learn from your own bad experience", example: "I learned the hard way that leaving revision to the last minute never works.", zh: "從慘痛經驗中學到" },
    { front: "put your thinking cap on", pos: "idiom", def: "to think hard to solve a problem", example: "We need a name for the project, so put your thinking cap on.", zh: "動腦筋、認真思考" },
    { front: "know something inside out", pos: "idiom", def: "to know something completely and in detail", example: "Ask Maria about grammar; she knows the rules inside out.", zh: "瞭若指掌" },
    { front: "a steep learning curve", pos: "idiom", def: "a situation where you must learn a lot very quickly", example: "My first month in the new job was a steep learning curve.", zh: "陡峭的學習曲線、需快速學習的過程" },
    // ===== Technology / internet =====
    { front: "laptop", pos: "n.", def: "a small computer you can carry with you", example: "I take my laptop to the library to work on my essays.", zh: "筆記型電腦" },
    { front: "tablet", pos: "n.", def: "a flat computer that you control by touching the screen", example: "She reads the news on her tablet over breakfast.", zh: "平板電腦" },
    { front: "keyboard", pos: "n.", def: "the set of keys used for typing on a computer", example: "My keyboard is so old that some letters have worn off.", zh: "鍵盤" },
    { front: "touchscreen", pos: "n.", def: "a screen you control by touching it with your fingers", example: "The ticket machine has a touchscreen, so it is easy to use.", zh: "觸控螢幕" },
    { front: "charger", pos: "n.", def: "a device that puts electricity back into a battery", example: "Can I borrow your charger? My phone is nearly dead.", zh: "充電器" },
    { front: "battery", pos: "n.", def: "the part of a device that stores electrical power", example: "The battery only lasts a few hours on this old phone.", zh: "電池" },
    { front: "headphones", pos: "n.", def: "equipment worn over the ears for listening to sound", example: "He wears headphones on the train so he can study.", zh: "耳機" },
    { front: "microphone", pos: "n.", def: "a device that makes your voice louder or records it", example: "Speak into the microphone so everyone can hear you.", zh: "麥克風" },
    { front: "webcam", pos: "n.", def: "a small camera connected to a computer", example: "Turn on your webcam so we can see you during the call.", zh: "網路攝影機" },
    { front: "printer", pos: "n.", def: "a machine that prints documents from a computer", example: "The printer has run out of ink again.", zh: "印表機" },
    { front: "software", pos: "n.", def: "the programs that a computer uses", example: "You need to install some software before the scanner will work.", zh: "軟體" },
    { front: "hardware", pos: "n.", def: "the physical parts of a computer system", example: "The problem is with the hardware, not the program.", zh: "硬體" },
    { front: "app", pos: "n.", def: "a small program used on a phone or tablet", example: "I use an app to track how much water I drink.", zh: "應用程式" },
    { front: "browser", pos: "n.", def: "a program used to look at websites", example: "Close some tabs; your browser is slowing everything down.", zh: "瀏覽器" },
    { front: "website", pos: "n.", def: "a set of pages on the internet about a subject", example: "The school website lists all the term dates.", zh: "網站" },
    { front: "link", pos: "n.", def: "a connection you click to move to another web page", example: "Click the link at the bottom of the email to confirm your address.", zh: "連結" },
    { front: "attachment", pos: "n.", def: "a file sent with an email", example: "I could not open the attachment you sent me yesterday.", zh: "附件" },
    { front: "inbox", pos: "n.", def: "the place where your received emails are kept", example: "My inbox is full of messages I have not answered.", zh: "收件匣" },
    { front: "spam", pos: "n.", def: "unwanted emails sent to many people", example: "Check your spam folder if my message does not arrive.", zh: "垃圾郵件" },
    { front: "hacker", pos: "n.", def: "someone who secretly gets into computer systems", example: "Hackers stole thousands of customers' details from the site.", zh: "駭客" },
    { front: "virus", pos: "n.", def: "a harmful program that damages computers", example: "My laptop caught a virus from a file I downloaded.", zh: "電腦病毒" },
    { front: "username", pos: "n.", def: "the name you use to enter a website or system", example: "I forgot my username, so I could not sign in.", zh: "使用者名稱" },
    { front: "profile", pos: "n.", def: "a page with information about you on a website", example: "She updated her profile with a new photo.", zh: "個人檔案" },
    { front: "notification", pos: "n.", def: "a message on your phone telling you something has happened", example: "I turn off notifications at night so I can sleep.", zh: "通知" },
    { front: "screenshot", pos: "n.", def: "a picture of what is on your screen", example: "Take a screenshot of the error and send it to me.", zh: "螢幕截圖" },
    { front: "emoji", pos: "n.", def: "a small picture used in messages to show feelings", example: "She ended the text with a smiling emoji.", zh: "表情符號" },
    { front: "influencer", pos: "n.", def: "a person who affects what others buy or do online", example: "The company paid an influencer to talk about its new trainers.", zh: "網紅、意見領袖" },
    { front: "follower", pos: "n.", def: "someone who chooses to see a person's posts online", example: "Her cooking videos gained her thousands of followers.", zh: "追蹤者、粉絲" },
    { front: "blog", pos: "n.", def: "a website where someone writes regularly about a topic", example: "He writes a blog about hiking in the mountains.", zh: "部落格" },
    { front: "forum", pos: "n.", def: "an online place where people discuss a subject", example: "I found the answer to my problem on a computer forum.", zh: "論壇" },
    { front: "server", pos: "n.", def: "a central computer that stores and shares information", example: "The website is down because the server has crashed.", zh: "伺服器" },
    { front: "database", pos: "n.", def: "a large organised collection of information on a computer", example: "The library keeps a database of every book it owns.", zh: "資料庫" },
    { front: "broadband", pos: "n.", def: "a fast permanent connection to the internet", example: "We changed provider to get cheaper broadband.", zh: "寬頻網路" },
    { front: "signal", pos: "n.", def: "the electronic waves that let a phone or radio work", example: "There is no signal in the tunnel, so the call cut out.", zh: "訊號" },
    { front: "connection", pos: "n.", def: "the link between a device and the internet", example: "The video kept stopping because of our slow connection.", zh: "連線" },
    { front: "disconnect", pos: "v.", def: "to break the link between a device and a network", example: "I was disconnected in the middle of the online game.", zh: "斷線、切斷連線" },
    { front: "install", pos: "v.", def: "to put a program onto a computer so it can be used", example: "You have to install the app before you can book tickets.", zh: "安裝" },
    { front: "uninstall", pos: "v.", def: "to remove a program from a computer", example: "I uninstalled the game because it took up too much space.", zh: "解除安裝" },
    { front: "delete", pos: "v.", def: "to remove something from a computer or phone", example: "I deleted the photo by mistake and lost it forever.", zh: "刪除" },
    { front: "crash", pos: "v.", def: "to suddenly stop working, used about computers", example: "The program crashed and I lost an hour of work.", zh: "（電腦）當機" },
    { front: "restart", pos: "v.", def: "to turn a machine off and on again", example: "Try restarting your phone if the screen freezes.", zh: "重新啟動" },
    { front: "compatible", pos: "adj.", def: "able to work together with another device or program", example: "This printer is not compatible with my new laptop.", zh: "相容的" },
    { front: "portable", pos: "adj.", def: "light and easy to carry", example: "We took a portable speaker to the beach.", zh: "可攜帶的" },
    { front: "innovative", pos: "adj.", def: "using new ideas and methods", example: "The company is famous for its innovative designs.", zh: "創新的" },
    { front: "outdated", pos: "adj.", def: "old and no longer useful or modern", example: "The office computers are so outdated that they take ages to start.", zh: "過時的" },
    { front: "digital", pos: "adj.", def: "using computer technology rather than older methods", example: "Most of our photos only exist in digital form now.", zh: "數位的" },
    { front: "automatic", pos: "adj.", def: "working by itself without human control", example: "The doors are automatic, so they open as you walk up.", zh: "自動的" },
    { front: "privacy", pos: "n.", def: "the state of keeping your personal life away from others", example: "Many people worry about their privacy on social media.", zh: "隱私" },
    { front: "cyberbullying", pos: "n.", def: "using the internet to frighten or upset someone", example: "The school invited a speaker to talk about cyberbullying.", zh: "網路霸凌" },
    { front: "user-friendly", pos: "adj.", def: "easy for people to use or understand", example: "The new banking app is much more user-friendly than the old one.", zh: "容易使用的" },
    { front: "high-tech", pos: "adj.", def: "using the most modern machines and methods", example: "The gym is full of high-tech running machines.", zh: "高科技的" },
    { front: "log out", pos: "phr. v.", def: "to close your account on a website or computer", example: "Always log out when you use a public computer.", zh: "登出" },
    { front: "sign in", pos: "phr. v.", def: "to enter your details to start using a website or system", example: "Sign in with your email address to see your order.", zh: "登入" },
    { front: "switch on", pos: "phr. v.", def: "to make a machine or light start working", example: "Switch on the projector while I find the slides.", zh: "打開（電源）" },
    { front: "switch off", pos: "phr. v.", def: "to make a machine or light stop working", example: "Please switch off your phones before the film starts.", zh: "關閉（電源）" },
    { front: "turn on", pos: "phr. v.", def: "to start a machine, light or supply working", example: "Turn on the TV; the match is about to begin.", zh: "打開" },
    { front: "turn off", pos: "phr. v.", def: "to stop a machine, light or supply working", example: "Turn off the lights when you leave the room.", zh: "關掉" },
    { front: "click on", pos: "phr. v.", def: "to press a mouse button on something on the screen", example: "Click on the icon to open the program.", zh: "點擊" },
    { front: "scroll down", pos: "phr. v.", def: "to move down a page on a screen", example: "Scroll down to the bottom of the page to find the prices.", zh: "向下捲動" },
    { front: "scroll through", pos: "phr. v.", def: "to move through content on a screen while looking at it", example: "She spent an hour scrolling through holiday photos.", zh: "滑覽、瀏覽" },
    { front: "zoom in", pos: "phr. v.", def: "to make an image on a screen look bigger and closer", example: "Zoom in on the map to see the street names.", zh: "放大" },
    { front: "zoom out", pos: "phr. v.", def: "to make an image on a screen show a wider area", example: "Zoom out a little so we can see the whole photo.", zh: "縮小" },
    { front: "pop up", pos: "phr. v.", def: "to appear suddenly on a screen", example: "An advert popped up in the middle of the video.", zh: "彈出" },
    { front: "boot up", pos: "phr. v.", def: "to start a computer", example: "My old laptop takes five minutes to boot up.", zh: "開機" },
    { front: "hook up", pos: "phr. v.", def: "to connect a machine to another machine or power supply", example: "Can you hook the console up to the hotel TV?", zh: "連接（設備）" },
    { front: "type in", pos: "phr. v.", def: "to enter information using a keyboard", example: "Type in the code from the text message to continue.", zh: "輸入" },
    { front: "hack into", pos: "phr. v.", def: "to secretly enter someone else's computer system", example: "Someone hacked into the company's email accounts.", zh: "入侵（電腦系統）" },
    { front: "charge up", pos: "phr. v.", def: "to fill a battery with electricity", example: "Charge up your phone before we set off on the trip.", zh: "充電" },
    { front: "top up", pos: "phr. v.", def: "to add more money or power to something", example: "I need to top up my travel card before we catch the bus.", zh: "加值、補足" },
    { front: "phase out", pos: "phr. v.", def: "to stop using something gradually", example: "The company is phasing out its oldest models.", zh: "逐步淘汰" },
    { front: "roll out", pos: "phr. v.", def: "to introduce a new product or service widely", example: "The update will be rolled out to all users next month.", zh: "推出、全面實施" },
    { front: "run on", pos: "phr. v.", def: "to use a particular type of power to work", example: "The camera runs on two small batteries.", zh: "以⋯⋯為動力運作" },
    { front: "shut off", pos: "phr. v.", def: "to stop a machine or supply from working", example: "The heating shuts off automatically at midnight.", zh: "關閉、切斷" },
    { front: "print off", pos: "phr. v.", def: "to produce a paper copy from a computer", example: "I printed off the tickets in case my phone died.", zh: "列印出來" },
    { front: "take apart", pos: "phr. v.", def: "to separate something into its different pieces", example: "He took the radio apart to see how it worked.", zh: "拆開" },
    { front: "go viral", pos: "collocation", def: "to spread very quickly on the internet", example: "Her video of the dancing cat went viral overnight.", zh: "爆紅、瘋傳" },
    { front: "surf the internet", pos: "collocation", def: "to look at different websites for fun or information", example: "He spends hours surfing the internet instead of studying.", zh: "上網瀏覽" },
    { front: "go online", pos: "collocation", def: "to connect to and use the internet", example: "I went online to compare prices before buying the camera.", zh: "上網" },
    { front: "send a text", pos: "collocation", def: "to send a written message from a phone", example: "Send me a text when you arrive at the station.", zh: "傳簡訊" },
    { front: "flat battery", pos: "collocation", def: "a battery that has no power left", example: "The car would not start because of a flat battery.", zh: "沒電的電池" },
    { front: "cutting-edge technology", pos: "collocation", def: "the most modern and advanced technology", example: "The hospital uses cutting-edge technology to scan patients.", zh: "尖端科技" },
    { front: "screen time", pos: "collocation", def: "the time spent looking at phones, computers or TV", example: "Doctors advise parents to limit children's screen time.", zh: "螢幕使用時間" },
    { front: "make a video call", pos: "collocation", def: "to talk to someone while seeing them on a screen", example: "We make a video call to my grandparents every Sunday.", zh: "打視訊電話" },
    { front: "identity theft", pos: "collocation", def: "the crime of using someone else's personal details", example: "Strong passwords help protect you from identity theft.", zh: "身分盜用" },
    { front: "technical support", pos: "collocation", def: "a service that helps people with computer problems", example: "I rang technical support when my internet stopped working.", zh: "技術支援" },
    { front: "not rocket science", pos: "idiom", def: "not difficult to understand or do", example: "Setting up the printer is not rocket science; just follow the steps.", zh: "並非難事、沒那麼複雜" },
    { front: "get your wires crossed", pos: "idiom", def: "to misunderstand each other", example: "We got our wires crossed and waited at different cafés.", zh: "雞同鴨講、誤會彼此" },
    { front: "on the same wavelength", pos: "idiom", def: "thinking in a similar way and understanding each other", example: "We work well together because we are on the same wavelength.", zh: "想法一致、頻率相同" },
    { front: "reinvent the wheel", pos: "idiom", def: "to waste time creating something that already exists", example: "Use the old template; there is no need to reinvent the wheel.", zh: "多此一舉、重複造輪子" },
    { front: "glued to the screen", pos: "idiom", def: "watching a screen without looking away", example: "The kids were glued to the screen all rainy afternoon.", zh: "目不轉睛盯著螢幕" },
    // ===== Nature / animals =====
    { front: "mammal", pos: "n.", def: "an animal that feeds its babies on milk", example: "Whales are mammals, not fish.", zh: "哺乳動物" },
    { front: "reptile", pos: "n.", def: "a cold-blooded animal such as a snake or lizard", example: "Reptiles lie in the sun to warm their bodies.", zh: "爬蟲類動物" },
    { front: "insect", pos: "n.", def: "a small creature with six legs, such as an ant or bee", example: "The light attracted hundreds of insects to the window.", zh: "昆蟲" },
    { front: "predator", pos: "n.", def: "an animal that hunts and eats other animals", example: "The island has no natural predators, so the birds are fearless.", zh: "掠食者" },
    { front: "prey", pos: "n.", def: "an animal that is hunted and eaten by another", example: "The eagle circled slowly, searching for prey.", zh: "獵物" },
    { front: "nest", pos: "n.", def: "a home that birds build for their eggs", example: "A pair of robins built a nest in our garden hedge.", zh: "鳥巢" },
    { front: "hive", pos: "n.", def: "a structure where bees live", example: "The farmer keeps six hives at the edge of the field.", zh: "蜂巢" },
    { front: "paw", pos: "n.", def: "the foot of an animal such as a cat or dog", example: "The dog lifted its paw as if to say hello.", zh: "（動物的）腳掌" },
    { front: "claw", pos: "n.", def: "the sharp curved nail on an animal's foot", example: "The kitten dug its claws into the sofa.", zh: "爪子" },
    { front: "fur", pos: "n.", def: "the soft hair covering an animal's body", example: "The rabbit's fur turns white in winter.", zh: "毛皮" },
    { front: "feather", pos: "n.", def: "one of the light soft things covering a bird's body", example: "We found a bright blue feather on the forest path.", zh: "羽毛" },
    { front: "beak", pos: "n.", def: "the hard pointed mouth of a bird", example: "The bird carried a twig in its beak.", zh: "鳥喙" },
    { front: "migrate", pos: "v.", def: "to travel to another place when the season changes", example: "These birds migrate south before the cold weather arrives.", zh: "遷徙" },
    { front: "hibernate", pos: "v.", def: "to sleep through the winter, used about animals", example: "Bears hibernate in caves during the coldest months.", zh: "冬眠" },
    { front: "hatch", pos: "v.", def: "to break out of an egg", example: "The chicks hatched after three weeks.", zh: "孵化" },
    { front: "breed", pos: "v.", def: "to produce young animals", example: "These frogs breed in shallow ponds in spring.", zh: "繁殖" },
    { front: "tame", pos: "adj.", def: "not wild and not afraid of people", example: "The deer in the park are so tame that they eat from your hand.", zh: "溫馴的" },
    { front: "stray", pos: "adj.", def: "having no home, used about pets", example: "They adopted a stray cat that kept visiting their garden.", zh: "流浪的" },
    { front: "graze", pos: "v.", def: "to eat grass in a field, used about animals", example: "Sheep were grazing peacefully on the hillside.", zh: "吃草" },
    { front: "roam", pos: "v.", def: "to move around freely over a wide area", example: "Wild horses still roam these hills.", zh: "漫遊、遊蕩" },
    { front: "sting", pos: "v.", def: "to hurt with a sharp point, used about insects", example: "A wasp stung me on the arm at the picnic.", zh: "螫、叮" },
    { front: "poisonous", pos: "adj.", def: "containing a substance that can kill or harm", example: "Some of these mushrooms are highly poisonous.", zh: "有毒的" },
    { front: "herd", pos: "n.", def: "a large group of animals such as cows or elephants", example: "A herd of elephants crossed the river at sunset.", zh: "獸群" },
    { front: "flock", pos: "n.", def: "a group of birds or sheep", example: "A flock of geese flew over the lake this morning.", zh: "（鳥、羊）群" },
    { front: "swarm", pos: "n.", def: "a large group of flying insects", example: "A swarm of bees settled on the apple tree.", zh: "（昆蟲）群" },
    { front: "creature", pos: "n.", def: "any living thing that is not a plant", example: "The rock pool was full of tiny sea creatures.", zh: "生物、動物" },
    { front: "vet", pos: "n.", def: "a doctor who treats animals", example: "We took the puppy to the vet for its first injection.", zh: "獸醫" },
    { front: "meadow", pos: "n.", def: "a field of grass and wild flowers", example: "We had a picnic in a meadow full of daisies.", zh: "草地、牧草地" },
    { front: "valley", pos: "n.", def: "the low land between hills or mountains", example: "A small river runs through the valley.", zh: "山谷" },
    { front: "cliff", pos: "n.", def: "a high steep face of rock, especially by the sea", example: "The path runs dangerously close to the edge of the cliff.", zh: "懸崖" },
    { front: "waterfall", pos: "n.", def: "water falling from a high place over rocks", example: "We hiked for two hours to reach the waterfall.", zh: "瀑布" },
    { front: "pond", pos: "n.", def: "a small area of still water", example: "Frogs lay their eggs in the garden pond every spring.", zh: "池塘" },
    { front: "swamp", pos: "n.", def: "an area of soft wet land", example: "Alligators live in the swamps of Florida.", zh: "沼澤" },
    { front: "blossom", pos: "n.", def: "the flowers on a tree in spring", example: "The cherry blossom only lasts a couple of weeks.", zh: "（樹上的）花" },
    { front: "soil", pos: "n.", def: "the top layer of earth in which plants grow", example: "Vegetables grow well in this rich, dark soil.", zh: "土壤" },
    { front: "boulder", pos: "n.", def: "a very large rock", example: "The road was blocked by a boulder that had fallen from the hillside.", zh: "巨石" },
    { front: "cave", pos: "n.", def: "a large natural hole in rock or under the ground", example: "Bats sleep in the cave during the day.", zh: "洞穴" },
    { front: "peak", pos: "n.", def: "the pointed top of a mountain", example: "Snow covers the highest peaks all year round.", zh: "山峰" },
    { front: "slope", pos: "n.", def: "the side of a hill or mountain", example: "We walked slowly up the grassy slope.", zh: "斜坡" },
    { front: "glacier", pos: "n.", def: "a huge mass of ice that moves very slowly", example: "The glacier has shrunk noticeably over the last twenty years.", zh: "冰河" },
    { front: "volcano", pos: "n.", def: "a mountain that can send out hot melted rock", example: "The village lies at the foot of an active volcano.", zh: "火山" },
    { front: "erupt", pos: "v.", def: "to explode and send out fire and rock, used about volcanoes", example: "The volcano last erupted over a century ago.", zh: "爆發" },
    { front: "tide", pos: "n.", def: "the regular rise and fall of the sea", example: "Check the tide times before you walk along the beach.", zh: "潮汐" },
    { front: "shore", pos: "n.", def: "the land along the edge of the sea or a lake", example: "We collected shells as we walked along the shore.", zh: "岸邊" },
    { front: "horizon", pos: "n.", def: "the line where the sky seems to meet the land or sea", example: "A ship appeared slowly on the horizon.", zh: "地平線" },
    { front: "dawn", pos: "n.", def: "the time when the sun first rises", example: "The birds start singing just before dawn.", zh: "黎明" },
    { front: "dusk", pos: "n.", def: "the time when it starts to get dark in the evening", example: "The street lights come on at dusk.", zh: "黃昏" },
    { front: "extinction", pos: "n.", def: "the situation when a type of animal stops existing", example: "Hunting has driven several species to extinction.", zh: "滅絕" },
    { front: "pollute", pos: "v.", def: "to make air, water or land dirty and dangerous", example: "Factories along the river have polluted the water for years.", zh: "污染" },
    { front: "tropical", pos: "adj.", def: "from or typical of the hottest parts of the world", example: "The greenhouse is full of tropical plants.", zh: "熱帶的" },
    { front: "breathtaking", pos: "adj.", def: "extremely beautiful or surprising", example: "The view from the summit was absolutely breathtaking.", zh: "令人屏息的" },
    { front: "picturesque", pos: "adj.", def: "pretty and pleasing to look at, used about places", example: "We stayed in a picturesque village by the lake.", zh: "如畫的" },
    { front: "vast", pos: "adj.", def: "extremely large in area or amount", example: "A vast desert stretches across the middle of the country.", zh: "廣闊的" },
    { front: "remote", pos: "adj.", def: "far away from towns and people", example: "They live on a remote farm with no neighbours for miles.", zh: "偏遠的" },
    { front: "steep", pos: "adj.", def: "rising or falling sharply, used about slopes", example: "The last part of the climb is too steep for beginners.", zh: "陡峭的" },
    { front: "chop down", pos: "phr. v.", def: "to make a tree fall by cutting it", example: "They chopped down the old oak to widen the road.", zh: "砍倒" },
    { front: "cut down", pos: "phr. v.", def: "to cut through a tree so that it falls", example: "Protesters tried to stop the company cutting down the forest.", zh: "砍伐" },
    { front: "dry up", pos: "phr. v.", def: "to lose all water, used about rivers and lakes", example: "The stream dries up completely in late summer.", zh: "乾涸" },
    { front: "cloud over", pos: "phr. v.", def: "to become covered with clouds", example: "It was sunny at breakfast, but the sky soon clouded over.", zh: "轉陰、烏雲密布" },
    { front: "pour down", pos: "phr. v.", def: "to rain very heavily", example: "It poured down all afternoon, so we stayed in the tent.", zh: "下傾盆大雨" },
    { front: "freeze over", pos: "phr. v.", def: "to become covered with ice", example: "The lake freezes over most winters, and people skate on it.", zh: "結冰" },
    { front: "wash away", pos: "phr. v.", def: "to carry something away with moving water", example: "The floods washed away the wooden bridge.", zh: "沖走" },
    { front: "blow down", pos: "phr. v.", def: "to make something fall by blowing, used about wind", example: "The storm blew down several trees in the park.", zh: "吹倒" },
    { front: "spring up", pos: "phr. v.", def: "to appear or grow suddenly", example: "After the rain, mushrooms sprang up all over the lawn.", zh: "突然出現、冒出" },
    { front: "grow back", pos: "phr. v.", def: "to grow again after being cut or damaged", example: "Do not worry about the hedge; it will grow back by summer.", zh: "重新長出" },
    { front: "set in", pos: "phr. v.", def: "to begin and seem likely to continue, used about weather", example: "We headed home before the bad weather set in.", zh: "（壞天氣）來臨並持續" },
    { front: "brighten up", pos: "phr. v.", def: "to become sunnier or more cheerful", example: "The forecast says it should brighten up this afternoon.", zh: "轉晴、變開朗" },
    { front: "wipe out", pos: "phr. v.", def: "to destroy something completely", example: "Disease nearly wiped out the island's bird population.", zh: "徹底消滅" },
    { front: "melt away", pos: "phr. v.", def: "to disappear gradually, like snow in the sun", example: "By April the snow on the lower slopes had melted away.", zh: "融化消失" },
    { front: "feed on", pos: "phr. v.", def: "to eat a particular kind of food, used about animals", example: "Owls feed on small animals such as mice.", zh: "以⋯⋯為食" },
    { front: "prey on", pos: "phr. v.", def: "to hunt and eat another animal", example: "Foxes prey on rabbits and small birds.", zh: "捕食" },
    { front: "live off", pos: "phr. v.", def: "to get the food or money you need from something", example: "The villagers live off the land, growing everything they eat.", zh: "靠⋯⋯生活" },
    { front: "scare off", pos: "phr. v.", def: "to make an animal or person go away by frightening them", example: "The farmer put up a scarecrow to scare off the birds.", zh: "嚇跑" },
    { front: "chase away", pos: "phr. v.", def: "to run after someone or something to make them leave", example: "Our dog chased away the fox that was near the chickens.", zh: "趕走" },
    { front: "food chain", pos: "collocation", def: "the natural system in which each creature eats another", example: "Removing one species can damage the whole food chain.", zh: "食物鏈" },
    { front: "natural disaster", pos: "collocation", def: "a terrible event caused by nature, like a flood or earthquake", example: "The charity sends help after natural disasters around the world.", zh: "天然災害" },
    { front: "mountain range", pos: "collocation", def: "a long line of mountains", example: "The Alps are the most famous mountain range in Europe.", zh: "山脈" },
    { front: "nature reserve", pos: "collocation", def: "an area of land protected for animals and plants", example: "The wetland was turned into a nature reserve for rare birds.", zh: "自然保護區" },
    { front: "national park", pos: "collocation", def: "a large natural area protected by the government", example: "We spent a week camping in the national park.", zh: "國家公園" },
    { front: "in the wild", pos: "collocation", def: "living in nature, not in a zoo or as a pet", example: "Very few of these tigers are left in the wild.", zh: "在野外" },
    { front: "raining cats and dogs", pos: "idiom", def: "raining extremely heavily", example: "Take an umbrella; it is raining cats and dogs out there.", zh: "下傾盆大雨" },
    { front: "the calm before the storm", pos: "idiom", def: "a quiet period just before trouble begins", example: "The office feels quiet, but it is just the calm before the storm.", zh: "暴風雨前的寧靜" },
    { front: "a fish out of water", pos: "idiom", def: "someone who feels uncomfortable in a new situation", example: "At the fashion show, he felt like a fish out of water.", zh: "格格不入的人" },
    { front: "let sleeping dogs lie", pos: "idiom", def: "to avoid mentioning a problem from the past", example: "Do not bring up that old argument; let sleeping dogs lie.", zh: "別自找麻煩、莫惹是非" },
    { front: "hold your horses", pos: "idiom", def: "used to tell someone to wait or slow down", example: "Hold your horses! We have not agreed on the plan yet.", zh: "且慢、別急" },
    { front: "a wild goose chase", pos: "idiom", def: "a search that wastes time because it cannot succeed", example: "The wrong address sent us on a wild goose chase across town.", zh: "白費力氣的追尋" },
    { front: "take the bull by the horns", pos: "idiom", def: "to deal with a difficult situation bravely and directly", example: "She took the bull by the horns and asked her boss for a raise.", zh: "當機立斷、迎難而上" },
    { front: "an early bird", pos: "idiom", def: "someone who gets up or arrives early", example: "My dad is an early bird and runs before six every day.", zh: "早起的人" },
    { front: "a night owl", pos: "idiom", def: "someone who stays awake and active late at night", example: "I am a night owl, so morning lectures are painful for me.", zh: "夜貓子" },
    { front: "make a mountain out of a molehill", pos: "idiom", def: "to treat a small problem as if it were very serious", example: "It is just a scratch; stop making a mountain out of a molehill.", zh: "小題大作" },
    { front: "at a snail's pace", pos: "idiom", def: "extremely slowly", example: "The traffic moved at a snail's pace all the way into town.", zh: "非常緩慢地" },
    { front: "the lion's share", pos: "idiom", def: "the largest part of something", example: "The lion's share of the budget went on new equipment.", zh: "最大的一份" },
    { front: "come out of your shell", pos: "idiom", def: "to become more confident and less shy", example: "She really came out of her shell after joining the drama club.", zh: "不再害羞、變得開朗" },
    { front: "a dark horse", pos: "idiom", def: "a person with hidden abilities that surprise people", example: "He is a dark horse; nobody knew he could sing so well.", zh: "深藏不露的人、黑馬" },
    { front: "the elephant in the room", pos: "idiom", def: "an obvious problem that nobody wants to talk about", example: "The cost of the project was the elephant in the room at the meeting.", zh: "眾人避而不談的明顯問題" },
    // ===== House / furniture =====
    { front: "attic", pos: "n.", def: "the room at the top of a house under the roof", example: "We store the Christmas decorations in the attic.", zh: "閣樓" },
    { front: "basement", pos: "n.", def: "a room or floor below the ground level of a building", example: "The washing machine is down in the basement.", zh: "地下室" },
    { front: "ceiling", pos: "n.", def: "the surface above you inside a room", example: "There is a damp patch on the bedroom ceiling.", zh: "天花板" },
    { front: "hallway", pos: "n.", def: "the area just inside the front door of a house", example: "Leave your shoes in the hallway, please.", zh: "門廳、玄關" },
    { front: "staircase", pos: "n.", def: "a set of stairs inside a building", example: "A wide wooden staircase leads up to the bedrooms.", zh: "樓梯" },
    { front: "drawer", pos: "n.", def: "a box-shaped part of furniture that slides out", example: "The scissors are in the top drawer of the desk.", zh: "抽屜" },
    { front: "wardrobe", pos: "n.", def: "a tall cupboard where you hang clothes", example: "Her wardrobe is so full that the doors will not shut.", zh: "衣櫃" },
    { front: "cupboard", pos: "n.", def: "a piece of furniture with doors, used for storing things", example: "The cups are in the cupboard above the sink.", zh: "櫥櫃" },
    { front: "shelf", pos: "n.", def: "a flat board fixed to a wall for putting things on", example: "He put the trophy on the highest shelf.", zh: "架子、層板" },
    { front: "bookcase", pos: "n.", def: "a piece of furniture with shelves for books", example: "The bookcase in the study is completely full.", zh: "書櫃" },
    { front: "armchair", pos: "n.", def: "a comfortable chair with supports for your arms", example: "Grandad fell asleep in his favourite armchair.", zh: "扶手椅" },
    { front: "cushion", pos: "n.", def: "a soft bag filled with material, put on a chair", example: "She bought some bright cushions to cheer up the sofa.", zh: "抱枕、椅墊" },
    { front: "mattress", pos: "n.", def: "the soft part of a bed that you lie on", example: "A firm mattress is better for your back.", zh: "床墊" },
    { front: "duvet", pos: "n.", def: "a thick warm cover filled with feathers or soft material", example: "I hid under the duvet when the alarm went off.", zh: "羽絨被" },
    { front: "blanket", pos: "n.", def: "a thick cover that keeps you warm", example: "She wrapped a blanket around her shoulders and read by the fire.", zh: "毯子" },
    { front: "curtain", pos: "n.", def: "a piece of cloth that covers a window", example: "Draw the curtains; the sun is in my eyes.", zh: "窗簾" },
    { front: "blinds", pos: "n.", def: "a window cover made of flat strips that can be raised", example: "The office has blinds instead of curtains.", zh: "百葉窗" },
    { front: "carpet", pos: "n.", def: "thick soft material that covers a floor", example: "Someone spilled coffee on the new living-room carpet.", zh: "地毯" },
    { front: "rug", pos: "n.", def: "a small piece of thick material put on part of a floor", example: "The cat loves sleeping on the rug by the fire.", zh: "小地毯" },
    { front: "wallpaper", pos: "n.", def: "paper used for decorating the walls of a room", example: "They chose a striped wallpaper for the bedroom.", zh: "壁紙" },
    { front: "chimney", pos: "n.", def: "the structure that carries smoke up from a fire", example: "Smoke rose gently from the cottage chimney.", zh: "煙囪" },
    { front: "fireplace", pos: "n.", def: "the open place in a wall where a fire burns", example: "We sat around the fireplace telling stories.", zh: "壁爐" },
    { front: "radiator", pos: "n.", def: "a metal object on a wall that heats a room", example: "I dried my gloves on the radiator.", zh: "暖氣機" },
    { front: "tap", pos: "n.", def: "the object that controls water coming from a pipe", example: "The kitchen tap has been dripping all week.", zh: "水龍頭" },
    { front: "sink", pos: "n.", def: "the bowl in a kitchen or bathroom where water runs", example: "The sink was full of dirty dishes after the party.", zh: "水槽" },
    { front: "drain", pos: "n.", def: "a pipe that carries dirty water away", example: "The drain outside the kitchen is blocked with leaves.", zh: "排水管" },
    { front: "balcony", pos: "n.", def: "a platform on the outside wall of a building", example: "You can see the sea from the balcony of our flat.", zh: "陽台" },
    { front: "porch", pos: "n.", def: "a covered area at the entrance of a house", example: "We left our muddy boots in the porch.", zh: "門廊" },
    { front: "fence", pos: "n.", def: "a wooden or metal structure around an area of land", example: "The dog dug a hole under the garden fence.", zh: "圍籬" },
    { front: "gate", pos: "n.", def: "a door in a fence or wall outside", example: "Please shut the gate so the sheep cannot get out.", zh: "大門、柵門" },
    { front: "lawn", pos: "n.", def: "an area of short grass in a garden", example: "The kids played football on the back lawn all afternoon.", zh: "草坪" },
    { front: "garage", pos: "n.", def: "a building where a car is kept", example: "The bikes take up half the garage.", zh: "車庫" },
    { front: "shed", pos: "n.", def: "a small building in a garden for storing tools", example: "The lawnmower is in the shed behind the house.", zh: "工具棚" },
    { front: "driveway", pos: "n.", def: "the private road from the street to a house", example: "A red van was parked in the driveway.", zh: "私人車道" },
    { front: "doorbell", pos: "n.", def: "the button by a door that makes a sound inside", example: "The doorbell rang just as we sat down to dinner.", zh: "門鈴" },
    { front: "letterbox", pos: "n.", def: "the hole in a door that letters are pushed through", example: "The keys were posted back through the letterbox.", zh: "信箱口、信件投遞口" },
    { front: "spacious", pos: "adj.", def: "having a lot of room inside", example: "The flat is surprisingly spacious for the price.", zh: "寬敞的" },
    { front: "cosy", pos: "adj.", def: "warm, comfortable and welcoming", example: "The cottage has a cosy little sitting room.", zh: "溫馨舒適的" },
    { front: "cramped", pos: "adj.", def: "too small and without enough space", example: "Four of us shared one cramped student room.", zh: "狹窄擁擠的" },
    { front: "cluttered", pos: "adj.", def: "untidily full of too many things", example: "His desk is so cluttered that he can never find a pen.", zh: "雜亂的" },
    { front: "tidy", pos: "adj.", def: "arranged neatly and in order", example: "Her room is always tidy, unlike her brother's.", zh: "整潔的" },
    { front: "messy", pos: "adj.", def: "dirty or untidy", example: "The kitchen was messy after we baked the cake.", zh: "凌亂的" },
    { front: "furnished", pos: "adj.", def: "containing furniture, used about rented rooms", example: "They rented a furnished flat near the university.", zh: "附家具的" },
    { front: "appliance", pos: "n.", def: "a machine used in the home, such as a fridge", example: "The kitchen came with all the modern appliances.", zh: "家電" },
    { front: "decorate", pos: "v.", def: "to paint a room or make it look attractive", example: "We spent the weekend decorating the baby's room.", zh: "裝潢、布置" },
    { front: "leak", pos: "v.", def: "to let liquid escape through a hole", example: "The roof leaks whenever it rains heavily.", zh: "漏水" },
    { front: "creak", pos: "v.", def: "to make a long high noise, used about doors and floors", example: "The old stairs creak with every step.", zh: "嘎吱作響" },
    { front: "draughty", pos: "adj.", def: "with cold air blowing in, used about rooms", example: "The hall is draughty because the door does not fit properly.", zh: "有冷風灌入的" },
    { front: "handy", pos: "adj.", def: "useful, or near and easy to reach", example: "Keep a torch handy in case there is a power failure.", zh: "方便的、順手可得的" },
    { front: "vacuum", pos: "v.", def: "to clean a floor with a machine that sucks up dirt", example: "I vacuum the stairs every Saturday morning.", zh: "用吸塵器清掃" },
    { front: "dust", pos: "v.", def: "to remove fine dry dirt from surfaces", example: "She dusted the shelves before the guests arrived.", zh: "擦去灰塵" },
    { front: "polish", pos: "v.", def: "to rub something to make it shine", example: "He polished the table until it shone like a mirror.", zh: "擦亮" },
    { front: "tidy up", pos: "phr. v.", def: "to make a place neat by putting things in order", example: "Tidy up your room before your friends come over.", zh: "收拾整齊" },
    { front: "clean up", pos: "phr. v.", def: "to remove dirt or mess from a place", example: "It took hours to clean up the kitchen after the party.", zh: "打掃乾淨" },
    { front: "throw out", pos: "phr. v.", def: "to get rid of something you do not want", example: "We threw out the broken chairs when we moved.", zh: "扔掉" },
    { front: "sweep up", pos: "phr. v.", def: "to clean a floor with a brush", example: "Can you sweep up the crumbs under the table?", zh: "掃乾淨" },
    { front: "wipe down", pos: "phr. v.", def: "to clean a surface with a cloth", example: "Wipe down the kitchen counters after cooking.", zh: "擦拭（表面）" },
    { front: "mop up", pos: "phr. v.", def: "to remove liquid from a floor with a mop or cloth", example: "Grab a towel and mop up the water by the door.", zh: "拖乾、擦乾" },
    { front: "fix up", pos: "phr. v.", def: "to repair or improve a building or room", example: "They bought a run-down cottage and fixed it up themselves.", zh: "修繕、整修" },
    { front: "take down", pos: "phr. v.", def: "to remove something from a wall or high place", example: "We took down the old posters and painted the wall.", zh: "取下、拆下" },
    { front: "put back", pos: "phr. v.", def: "to return something to its usual place", example: "Put the tools back in the shed when you finish.", zh: "放回原處" },
    { front: "board up", pos: "phr. v.", def: "to cover windows or doors with wooden boards", example: "The empty shop has been boarded up for months.", zh: "用木板封住" },
    { front: "block up", pos: "phr. v.", def: "to fill a hole or pipe so nothing can pass through", example: "Leaves had blocked up the gutter, so water ran down the wall.", zh: "堵塞" },
    { front: "burn down", pos: "phr. v.", def: "to be destroyed by fire, used about buildings", example: "The old barn burned down in less than an hour.", zh: "燒毀" },
    { front: "fall down", pos: "phr. v.", def: "to fall to the ground or collapse", example: "The garden wall is so old that it is starting to fall down.", zh: "倒塌" },
    { front: "pull down", pos: "phr. v.", def: "to destroy a building on purpose", example: "They pulled down the cinema to build flats.", zh: "拆除" },
    { front: "put in", pos: "phr. v.", def: "to fix new equipment into a house", example: "We are having a new bathroom put in next month.", zh: "安裝" },
    { front: "hand down", pos: "phr. v.", def: "to give something to a younger member of the family", example: "This clock was handed down from my great-grandmother.", zh: "傳給後代" },
    { front: "do the washing-up", pos: "collocation", def: "to wash the dirty dishes after a meal", example: "You cooked, so I will do the washing-up.", zh: "洗碗" },
    { front: "make the bed", pos: "collocation", def: "to arrange the covers of a bed neatly", example: "He never makes the bed before leaving for work.", zh: "鋪床" },
    { front: "set the table", pos: "collocation", def: "to put plates and cutlery on a table before a meal", example: "Could you set the table while I serve the soup?", zh: "擺餐具" },
    { front: "do the ironing", pos: "collocation", def: "to make clothes smooth with an iron", example: "I do the ironing while watching television.", zh: "燙衣服" },
    { front: "mow the lawn", pos: "collocation", def: "to cut the grass in a garden", example: "Dad mows the lawn every other weekend in summer.", zh: "修剪草坪" },
    { front: "take out the rubbish", pos: "collocation", def: "to carry the bin bags outside", example: "It is your turn to take out the rubbish tonight.", zh: "倒垃圾" },
    { front: "spring cleaning", pos: "collocation", def: "a thorough cleaning of the whole house", example: "We gave the flat a proper spring cleaning before Easter.", zh: "大掃除" },
    { front: "central heating", pos: "collocation", def: "a system that heats a whole building", example: "The central heating comes on at six in the morning.", zh: "中央暖氣" },
    { front: "spare room", pos: "collocation", def: "a bedroom kept for guests", example: "You can sleep in the spare room when you visit.", zh: "客房" },
    { front: "power cut", pos: "collocation", def: "a period when there is no electricity", example: "We lit candles during the power cut last night.", zh: "停電" },
    { front: "household chores", pos: "collocation", def: "the regular jobs done to keep a home clean", example: "We share the household chores equally in our flat.", zh: "家事" },
    { front: "estate agent", pos: "collocation", def: "a person whose job is selling houses", example: "The estate agent showed us three flats in one afternoon.", zh: "房屋仲介" },
    { front: "make yourself at home", pos: "idiom", def: "to relax as if you were in your own house", example: "Come in, sit down and make yourself at home.", zh: "把這裡當自己家、別拘束" },
    { front: "a roof over your head", pos: "idiom", def: "a place to live", example: "The job does not pay much, but at least we have a roof over our heads.", zh: "棲身之所" },
    { front: "sweep something under the carpet", pos: "idiom", def: "to hide a problem instead of dealing with it", example: "You cannot sweep the complaints under the carpet forever.", zh: "掩蓋問題" },
    { front: "everything but the kitchen sink", pos: "idiom", def: "far more things than are needed", example: "She packed everything but the kitchen sink for a weekend trip.", zh: "帶了一大堆東西" },
    { front: "hit the roof", pos: "idiom", def: "to become extremely angry", example: "Mum hit the roof when she saw the broken window.", zh: "勃然大怒" },
    { front: "get on like a house on fire", pos: "idiom", def: "to become friends quickly and like each other a lot", example: "My cousin and my best friend get on like a house on fire.", zh: "一見如故、非常投緣" },
    // ===== Clothes / appearance =====
    { front: "outfit", pos: "n.", def: "a set of clothes worn together", example: "She bought a new outfit for her cousin's wedding.", zh: "一套服裝" },
    { front: "garment", pos: "n.", def: "a piece of clothing", example: "Wash this garment by hand in cold water.", zh: "衣物" },
    { front: "sleeve", pos: "n.", def: "the part of clothing that covers your arm", example: "He rolled his sleeves above his elbows and started work.", zh: "袖子" },
    { front: "collar", pos: "n.", def: "the part of a shirt or coat around the neck", example: "He turned up his collar against the cold wind.", zh: "衣領" },
    { front: "fabric", pos: "n.", def: "cloth used for making clothes or curtains", example: "The dress is made from a light summer fabric.", zh: "布料" },
    { front: "cotton", pos: "n.", def: "a natural cloth made from a plant", example: "In hot weather I only wear cotton shirts.", zh: "棉、棉布" },
    { front: "wool", pos: "n.", def: "the soft hair of sheep, used to make warm clothes", example: "This jumper is pure wool, so it is really warm.", zh: "羊毛" },
    { front: "leather", pos: "n.", def: "material made from animal skin", example: "He saved up for months to buy a leather jacket.", zh: "皮革" },
    { front: "silk", pos: "n.", def: "a smooth expensive cloth made by silkworms", example: "She wore a beautiful silk scarf with the plain dress.", zh: "絲綢" },
    { front: "denim", pos: "n.", def: "the strong cotton cloth used for jeans", example: "Denim jackets seem to come back into fashion every few years.", zh: "丹寧布、牛仔布" },
    { front: "striped", pos: "adj.", def: "having lines of different colours", example: "He wore a blue and white striped shirt.", zh: "條紋的" },
    { front: "plain", pos: "adj.", def: "in one colour with no pattern", example: "A plain white T-shirt goes with everything.", zh: "素色的" },
    { front: "patterned", pos: "adj.", def: "decorated with shapes or designs", example: "She chose patterned curtains for the living room.", zh: "有圖案的" },
    { front: "checked", pos: "adj.", def: "having a pattern of squares", example: "The waiter wore a red checked shirt.", zh: "格紋的" },
    { front: "floral", pos: "adj.", def: "decorated with flowers", example: "Floral dresses are everywhere this summer.", zh: "花卉圖案的" },
    { front: "baggy", pos: "adj.", def: "loose and hanging in folds, used about clothes", example: "He wore baggy jeans and an old hoodie.", zh: "寬鬆下垂的" },
    { front: "loose", pos: "adj.", def: "not fitting closely to the body", example: "The trousers are a bit loose, so I need a belt.", zh: "寬鬆的" },
    { front: "tight", pos: "adj.", def: "fitting very closely to the body", example: "These shoes are too tight around the toes.", zh: "緊的" },
    { front: "fashionable", pos: "adj.", def: "popular at the moment, used about styles", example: "Bright colours are fashionable again this year.", zh: "時髦的" },
    { front: "trendy", pos: "adj.", def: "very fashionable and modern", example: "They opened a trendy café near the art school.", zh: "新潮的" },
    { front: "stylish", pos: "adj.", def: "attractive and fashionable in an elegant way", example: "She always looks stylish, even in casual clothes.", zh: "有型的、時尚的" },
    { front: "elegant", pos: "adj.", def: "graceful and attractive in a simple way", example: "The bride wore an elegant ivory gown.", zh: "優雅的" },
    { front: "glamorous", pos: "adj.", def: "attractive in an exciting and expensive-looking way", example: "The actress arrived in a glamorous silver dress.", zh: "光鮮迷人的" },
    { front: "scruffy", pos: "adj.", def: "untidy and slightly dirty in appearance", example: "You cannot go to the interview in those scruffy trainers.", zh: "邋遢的" },
    { front: "smart", pos: "adj.", def: "clean, tidy and well dressed", example: "Everyone looked very smart in their suits at the ceremony.", zh: "衣著體面的" },
    { front: "casual", pos: "adj.", def: "comfortable and informal, used about clothes", example: "The office lets us wear casual clothes on Fridays.", zh: "休閒的" },
    { front: "formal", pos: "adj.", def: "suitable for serious or official occasions", example: "The invitation says formal dress is required.", zh: "正式的" },
    { front: "vintage", pos: "adj.", def: "old but high quality and typical of its period", example: "She collects vintage handbags from the sixties.", zh: "復古的" },
    { front: "suit", pos: "v.", def: "to make someone look attractive", example: "That shade of green really suits you.", zh: "適合（某人）" },
    { front: "flatter", pos: "v.", def: "to make someone look more attractive than usual", example: "The cut of that coat really flatters her.", zh: "使顯得好看" },
    { front: "shrink", pos: "v.", def: "to become smaller, especially after washing", example: "My favourite jumper shrank in the hot wash.", zh: "縮水" },
    { front: "fade", pos: "v.", def: "to lose colour gradually", example: "The curtains have faded after years in the sun.", zh: "褪色" },
    { front: "stain", pos: "v.", def: "to leave a dirty mark that is hard to remove", example: "The tomato sauce stained his white shirt.", zh: "弄髒、留下污漬" },
    { front: "tear", pos: "v.", def: "to pull cloth or paper apart so it is damaged", example: "I tore my sleeve on a nail in the fence.", zh: "撕破" },
    { front: "mend", pos: "v.", def: "to repair something that is broken or torn", example: "Grandma mended the hole in my school trousers.", zh: "修補" },
    { front: "sew", pos: "v.", def: "to join cloth using a needle and thread", example: "Can you sew this button back onto my coat?", zh: "縫" },
    { front: "stitch", pos: "n.", def: "one small line of thread made when sewing", example: "A few stitches will fix that tear in no time.", zh: "一針、針腳" },
    { front: "knit", pos: "v.", def: "to make clothes from wool using long needles", example: "My aunt knitted me a scarf for my birthday.", zh: "編織" },
    { front: "crease", pos: "n.", def: "an untidy line made in cloth by folding", example: "Hang up the shirt so it does not get creases.", zh: "皺褶" },
    { front: "fasten", pos: "v.", def: "to close or join the two sides of something", example: "Fasten your coat; it is freezing outside.", zh: "扣緊、繫上" },
    { front: "accessory", pos: "n.", def: "something like a belt or bag worn to complete an outfit", example: "The right accessories can transform a simple dress.", zh: "配件" },
    { front: "jewellery", pos: "n.", def: "decorative objects like rings and necklaces", example: "She keeps her jewellery in a small wooden box.", zh: "珠寶飾品" },
    { front: "make-up", pos: "n.", def: "coloured substances put on the face to improve its look", example: "She never wears make-up to the gym.", zh: "化妝品、妝" },
    { front: "complexion", pos: "n.", def: "the natural colour and condition of the skin on your face", example: "Drinking lots of water is good for your complexion.", zh: "膚色、氣色" },
    { front: "fringe", pos: "n.", def: "hair cut short and hanging over the forehead", example: "Her new fringe almost covers her eyes.", zh: "瀏海" },
    { front: "freckles", pos: "n.", def: "small light brown spots on the skin", example: "He gets more freckles every summer.", zh: "雀斑" },
    { front: "wrinkles", pos: "n.", def: "small lines in the skin caused by age", example: "She smiled, and tiny wrinkles appeared around her eyes.", zh: "皺紋" },
    { front: "bald", pos: "adj.", def: "having little or no hair on the head", example: "My uncle went bald before he was thirty.", zh: "禿頭的" },
    { front: "curly", pos: "adj.", def: "having hair in curved shapes", example: "As a child she had thick, curly hair.", zh: "捲髮的" },
    { front: "wavy", pos: "adj.", def: "having gentle curves, used about hair", example: "Her long wavy hair reached her shoulders.", zh: "波浪捲的" },
    { front: "ponytail", pos: "n.", def: "hair tied together at the back of the head", example: "She pulled her hair into a ponytail before the race.", zh: "馬尾" },
    { front: "plait", pos: "n.", def: "hair twisted together in a pattern", example: "The little girl wore her hair in two neat plaits.", zh: "辮子" },
    { front: "dye", pos: "v.", def: "to change the colour of hair or cloth", example: "He dyed his hair blue for the festival.", zh: "染色" },
    { front: "slim", pos: "adj.", def: "attractively thin", example: "She stays slim by cycling to work every day.", zh: "苗條的" },
    { front: "plump", pos: "adj.", def: "slightly fat in a pleasant way", example: "The baby had plump little cheeks.", zh: "豐滿的、圓潤的" },
    { front: "skinny", pos: "adj.", def: "very thin, often too thin", example: "He was a skinny teenager who suddenly grew tall.", zh: "皮包骨的、極瘦的" },
    { front: "well-built", pos: "adj.", def: "having a strong, solid body", example: "The doorman was tall and well-built.", zh: "體格健壯的" },
    { front: "muscular", pos: "adj.", def: "having strong, well-developed muscles", example: "Years of swimming gave her muscular shoulders.", zh: "肌肉發達的" },
    { front: "resemble", pos: "v.", def: "to look like someone or something", example: "She strongly resembles her mother at the same age.", zh: "與⋯⋯相像" },
    { front: "identical", pos: "adj.", def: "exactly the same", example: "The twins are identical, and even their teacher mixes them up.", zh: "一模一樣的" },
    { front: "zip up", pos: "phr. v.", def: "to close clothing with a zip", example: "Zip up your jacket; the wind is getting stronger.", zh: "拉上拉鍊" },
    { front: "button up", pos: "phr. v.", def: "to close clothing with buttons", example: "He buttoned up his coat and stepped into the snow.", zh: "扣上鈕扣" },
    { front: "slip on", pos: "phr. v.", def: "to put clothing on quickly and easily", example: "She slipped on her sandals and ran to the door.", zh: "迅速穿上" },
    { front: "throw on", pos: "phr. v.", def: "to put clothes on quickly and carelessly", example: "I threw on some old jeans and went to answer the door.", zh: "隨手套上" },
    { front: "let out", pos: "phr. v.", def: "to make a piece of clothing wider or looser", example: "The tailor let out the waist of the trousers.", zh: "把（衣服）放寬" },
    { front: "dress down", pos: "phr. v.", def: "to wear clothes that are more informal than usual", example: "Staff are allowed to dress down on Fridays.", zh: "穿得隨性" },
    { front: "fold up", pos: "phr. v.", def: "to bend cloth or paper into a smaller neat shape", example: "Fold up your clothes instead of leaving them on the chair.", zh: "摺好" },
    { front: "smarten up", pos: "phr. v.", def: "to make yourself or a place look tidier", example: "You should smarten up a bit before the photo is taken.", zh: "打理整齊" },
    { front: "grow out of", pos: "phr. v.", def: "to become too big for your clothes", example: "Kids grow out of their shoes so quickly at that age.", zh: "長大而穿不下" },
    { front: "tie back", pos: "phr. v.", def: "to fasten hair away from the face", example: "Tie your hair back before you start cooking.", zh: "把頭髮綁起來" },
    { front: "slim down", pos: "phr. v.", def: "to become thinner", example: "He slimmed down a lot before the summer holidays.", zh: "瘦身" },
    { front: "lace up", pos: "phr. v.", def: "to fasten shoes by tying the laces", example: "She laced up her boots and set off along the trail.", zh: "繫緊鞋帶" },
    { front: "get dressed", pos: "collocation", def: "to put your clothes on", example: "Hurry up and get dressed, or we will miss the bus.", zh: "穿好衣服" },
    { front: "dress code", pos: "collocation", def: "the rules about what to wear somewhere", example: "The restaurant has a strict dress code, so no shorts.", zh: "服裝規定" },
    { front: "go out of fashion", pos: "collocation", def: "to stop being popular to wear", example: "Those huge sunglasses went out of fashion years ago.", zh: "退流行" },
    { front: "make a good impression", pos: "collocation", def: "to cause someone to have a positive opinion of you", example: "Dress smartly for the interview to make a good impression.", zh: "留下好印象" },
    { front: "get a haircut", pos: "collocation", def: "to have your hair cut shorter", example: "You should get a haircut before the graduation photos.", zh: "剪頭髮" },
    { front: "designer clothes", pos: "collocation", def: "expensive clothes made by famous companies", example: "She spends most of her salary on designer clothes.", zh: "名牌服飾" },
    { front: "smart casual", pos: "collocation", def: "a style of dress that is neat but not formal", example: "The invitation said smart casual, so I wore a shirt with jeans.", zh: "半正式休閒穿著" },
    { front: "first impression", pos: "collocation", def: "the opinion formed when you first meet someone", example: "A firm handshake helps create a good first impression.", zh: "第一印象" },
    { front: "fit like a glove", pos: "idiom", def: "to be exactly the right size", example: "I tried the jacket on, and it fitted like a glove.", zh: "非常合身" },
    { front: "wear and tear", pos: "idiom", def: "the damage caused by normal use over time", example: "The carpet shows a lot of wear and tear after ten years.", zh: "正常損耗" },
    { front: "a bad hair day", pos: "idiom", def: "a day when you look untidy and everything goes wrong", example: "Do not take that photo; I am having a bad hair day.", zh: "諸事不順（外表狼狽）的一天" },
    { front: "dressed to kill", pos: "idiom", def: "wearing very attractive clothes to be noticed", example: "She arrived at the party dressed to kill.", zh: "盛裝打扮、艷驚四座" },
    { front: "keep up appearances", pos: "idiom", def: "to hide problems and pretend everything is fine", example: "They kept up appearances even after the business failed.", zh: "維持體面" },
    { front: "the spitting image of", pos: "idiom", def: "looking exactly like another person", example: "He is the spitting image of his grandfather at twenty.", zh: "長得一模一樣" },
    { front: "roll up your sleeves", pos: "idiom", def: "to prepare to work hard", example: "We rolled up our sleeves and repainted the whole house.", zh: "捲起袖子（準備苦幹）" },
    { front: "tighten your belt", pos: "idiom", def: "to spend less money than before", example: "After the rent went up, we had to tighten our belts.", zh: "勒緊褲帶、節省開支" },
    { front: "have something up your sleeve", pos: "idiom", def: "to have a secret plan ready to use", example: "Do not worry; the coach always has something up his sleeve.", zh: "留有一手、暗藏妙計" },
    { front: "put yourself in someone's shoes", pos: "idiom", def: "to imagine how another person feels", example: "Put yourself in her shoes before you judge her decision.", zh: "設身處地" },
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
