/* FCE Prep extra bank: vocab wave 1 */
(function () {
  var BANK = [
    /* ---------- Work & career ---------- */
    { front: "ambitious", pos: "adj.", def: "having a strong wish to be successful", example: "She is very ambitious and hopes to run her own company one day.", zh: "有野心的、有抱負的" },
    { front: "candidate", pos: "n.", def: "a person who is trying to get a job or win an election", example: "There were over fifty candidates for the marketing position.", zh: "應徵者、候選人" },
    { front: "colleague", pos: "n.", def: "a person you work with", example: "I get on really well with my colleagues at the office.", zh: "同事" },
    { front: "commute", pos: "v.", def: "to travel regularly between home and work", example: "He commutes to the city centre by train every morning.", zh: "通勤" },
    { front: "deadline", pos: "n.", def: "the time by which something must be finished", example: "We worked all weekend to meet the project deadline.", zh: "截止期限" },
    { front: "demanding", pos: "adj.", def: "needing a lot of time, effort or attention", example: "Nursing is a demanding job, but it can be very rewarding.", zh: "要求高的、費力的" },
    { front: "dismiss", pos: "v.", def: "to officially make someone leave their job", example: "He was dismissed for repeatedly arriving late to work.", zh: "解僱" },
    { front: "earn", pos: "v.", def: "to receive money for the work you do", example: "She earns a good salary as a software engineer.", zh: "賺取" },
    { front: "employee", pos: "n.", def: "a person who is paid to work for a company", example: "The firm gives all its employees a bonus in December.", zh: "員工、僱員" },
    { front: "employer", pos: "n.", def: "a person or company that pays people to work", example: "My employer allows us to work from home twice a week.", zh: "僱主" },
    { front: "employment", pos: "n.", def: "the state of having paid work", example: "The new factory will provide employment for hundreds of people.", zh: "就業、僱用" },
    { front: "experienced", pos: "adj.", def: "having skill or knowledge from doing something for a long time", example: "We are looking for an experienced chef to join our kitchen team.", zh: "有經驗的" },
    { front: "income", pos: "n.", def: "the money you receive regularly for work or from investments", example: "Their income dropped sharply after the shop closed.", zh: "收入" },
    { front: "internship", pos: "n.", def: "a period of work experience, often for students", example: "She did a summer internship at a local newspaper.", zh: "實習" },
    { front: "interview", pos: "n.", def: "a formal meeting where someone is asked questions for a job", example: "He felt nervous before his interview at the bank.", zh: "面試" },
    { front: "occupation", pos: "n.", def: "a person's job or profession", example: "Please write your name, age and occupation on the form.", zh: "職業" },
    { front: "overtime", pos: "n.", def: "extra hours worked beyond your normal working hours", example: "They paid us extra for doing overtime at the weekend.", zh: "加班" },
    { front: "promotion", pos: "n.", def: "a move to a higher position at work", example: "After three years, she finally got a promotion to team leader.", zh: "升遷" },
    { front: "qualification", pos: "n.", def: "an exam you have passed or a skill you have that makes you suitable for a job", example: "You need a teaching qualification to work at this school.", zh: "資格、學歷" },
    { front: "recruit", pos: "v.", def: "to find new people to work for a company", example: "The hospital is recruiting more nurses this year.", zh: "招募" },
    { front: "resign", pos: "v.", def: "to officially leave your job by choice", example: "He resigned from his post to spend more time with his family.", zh: "辭職" },
    { front: "retire", pos: "v.", def: "to stop working because of your age", example: "My grandfather retired at sixty-five and took up gardening.", zh: "退休" },
    { front: "salary", pos: "n.", def: "a fixed amount of money paid to an employee, usually monthly", example: "The job offers a competitive salary and good holidays.", zh: "薪水" },
    { front: "staff", pos: "n.", def: "all the people who work for an organisation", example: "The hotel staff were friendly and helpful throughout our stay.", zh: "全體員工" },
    { front: "temporary", pos: "adj.", def: "lasting only for a limited time", example: "She took a temporary job in a cafe while she looked for something better.", zh: "臨時的、暫時的" },
    { front: "unemployed", pos: "adj.", def: "not having a job", example: "He was unemployed for six months before finding work again.", zh: "失業的" },
    { front: "wage", pos: "n.", def: "money paid for work, usually by the hour or week", example: "Many workers here are paid the minimum wage.", zh: "工資" },
    { front: "workload", pos: "n.", def: "the amount of work a person has to do", example: "Her workload doubled when two colleagues left the company.", zh: "工作量" },
    /* ---------- Education ---------- */
    { front: "absent", pos: "adj.", def: "not present in a place, especially school or work", example: "Three students were absent from class because of the flu.", zh: "缺席的" },
    { front: "academic", pos: "adj.", def: "connected with education, especially studying in schools and universities", example: "Her academic results were good enough for a top university.", zh: "學術的、學業的" },
    { front: "assignment", pos: "n.", def: "a piece of work given to someone as part of a course or job", example: "We have to hand in our history assignment by Friday.", zh: "作業、任務" },
    { front: "attend", pos: "v.", def: "to go to an event, class or place regularly", example: "You must attend at least eighty percent of the lectures.", zh: "出席、參加" },
    { front: "campus", pos: "n.", def: "the land and buildings of a university or college", example: "Most first-year students live on campus.", zh: "校園" },
    { front: "certificate", pos: "n.", def: "an official document proving you have completed a course or passed an exam", example: "She received a certificate after finishing the first-aid course.", zh: "證書" },
    { front: "cheat", pos: "v.", def: "to behave dishonestly to get an advantage, especially in an exam", example: "Anyone caught cheating in the exam will fail automatically.", zh: "作弊" },
    { front: "compulsory", pos: "adj.", def: "required by a rule or law; something you must do", example: "Maths is compulsory for all students until the age of sixteen.", zh: "必修的、強制的" },
    { front: "curriculum", pos: "n.", def: "the subjects taught at a school or on a course", example: "The school has added coding to its curriculum this year.", zh: "課程" },
    { front: "degree", pos: "n.", def: "a qualification given by a university", example: "He has a degree in biology from Manchester University.", zh: "學位" },
    { front: "educate", pos: "v.", def: "to teach someone, especially at a school or university", example: "The charity aims to educate children in remote villages.", zh: "教育" },
    { front: "graduate", pos: "v.", def: "to complete a degree or course of study successfully", example: "She graduated from university with top marks last summer.", zh: "畢業" },
    { front: "instructor", pos: "n.", def: "a person who teaches a skill or activity", example: "Our driving instructor is very patient with beginners.", zh: "教練、指導員" },
    { front: "knowledge", pos: "n.", def: "the information and understanding you have about something", example: "A tour guide needs a good knowledge of local history.", zh: "知識" },
    { front: "lecture", pos: "n.", def: "a formal talk given to teach a group of people", example: "The professor gave a fascinating lecture on climate science.", zh: "講座、講課" },
    { front: "literacy", pos: "n.", def: "the ability to read and write", example: "The programme has improved literacy rates among adults.", zh: "讀寫能力、識字" },
    { front: "memorise", pos: "v.", def: "to learn something so that you remember it exactly", example: "Actors have to memorise all their lines before filming starts.", zh: "背誦、記住" },
    { front: "postgraduate", pos: "n.", def: "a student studying for a degree after their first degree", example: "As a postgraduate, she spent most of her time doing research.", zh: "研究生" },
    { front: "pupil", pos: "n.", def: "a child who attends school", example: "The teacher praised her pupils for their hard work.", zh: "小學生、學生" },
    { front: "revise", pos: "v.", def: "to study something again before an exam", example: "I need to revise for my English test this weekend.", zh: "複習" },
    { front: "scholarship", pos: "n.", def: "money given to a student to pay for their studies", example: "He won a scholarship to study music in Vienna.", zh: "獎學金" },
    { front: "semester", pos: "n.", def: "one of the two periods that a school or university year is divided into", example: "The spring semester begins in February.", zh: "學期" },
    { front: "syllabus", pos: "n.", def: "a list of topics that a course of study covers", example: "The exam only tests what is on the syllabus.", zh: "教學大綱" },
    { front: "term", pos: "n.", def: "one of the periods the school year is divided into", example: "The autumn term ends just before Christmas.", zh: "學期" },
    { front: "tutor", pos: "n.", def: "a teacher who works with one student or a small group", example: "Her parents hired a private tutor to help her with maths.", zh: "家教、導師" },
    { front: "undergraduate", pos: "n.", def: "a university student studying for their first degree", example: "Most undergraduates share flats near the campus.", zh: "大學部學生" },
    /* ---------- Travel & transport ---------- */
    { front: "abroad", pos: "adv.", def: "in or to a foreign country", example: "She has always dreamed of studying abroad.", zh: "在國外、到國外" },
    { front: "accommodation", pos: "n.", def: "a place to live or stay", example: "The price of the trip includes flights and accommodation.", zh: "住宿" },
    { front: "arrival", pos: "n.", def: "the act of reaching a place", example: "On arrival at the hotel, we were given a welcome drink.", zh: "抵達" },
    { front: "backpack", pos: "n.", def: "a large bag carried on your back, used by travellers", example: "He packed everything he needed into one backpack.", zh: "背包" },
    { front: "board", pos: "v.", def: "to get on a plane, ship, train or bus", example: "Passengers for Rome may now board the aircraft.", zh: "登機、上車（船）" },
    { front: "border", pos: "n.", def: "the line that divides two countries", example: "We crossed the border into France early in the morning.", zh: "邊界、國界" },
    { front: "cabin", pos: "n.", def: "a small room on a ship, or the passenger area of a plane", example: "Our cabin on the ferry had two small beds and a window.", zh: "船艙、機艙" },
    { front: "crew", pos: "n.", def: "the people who work on a ship or plane", example: "The cabin crew served drinks shortly after take-off.", zh: "全體機組（船）員" },
    { front: "cruise", pos: "n.", def: "a holiday spent travelling on a ship", example: "They went on a two-week cruise around the Mediterranean.", zh: "郵輪旅行" },
    { front: "customs", pos: "n.", def: "the place at a border where officials check luggage", example: "It took ages to get through customs at the airport.", zh: "海關" },
    { front: "delay", pos: "n.", def: "a situation in which something happens later than expected", example: "Heavy snow caused long delays at the airport.", zh: "延誤" },
    { front: "departure", pos: "n.", def: "the act of leaving a place, especially at the start of a journey", example: "Please check the screens for your departure gate.", zh: "出發、離境" },
    { front: "destination", pos: "n.", def: "the place someone or something is going to", example: "After ten hours on the road, we finally reached our destination.", zh: "目的地" },
    { front: "expedition", pos: "n.", def: "an organised journey with a particular purpose, often to a distant place", example: "The team is planning an expedition to the Arctic next year.", zh: "遠征、探險" },
    { front: "ferry", pos: "n.", def: "a boat that carries people and vehicles across water regularly", example: "We took the ferry from Dover to Calais.", zh: "渡輪" },
    { front: "guidebook", pos: "n.", def: "a book that gives information for tourists", example: "According to the guidebook, this castle is over 800 years old.", zh: "旅遊指南" },
    { front: "itinerary", pos: "n.", def: "a plan of a journey, including places and times", example: "Our itinerary includes three days in Kyoto and two in Osaka.", zh: "行程表" },
    { front: "journey", pos: "n.", def: "the act of travelling from one place to another", example: "The train journey through the mountains was unforgettable.", zh: "旅程" },
    { front: "landing", pos: "n.", def: "the arrival of a plane on the ground", example: "The pilot made a smooth landing despite the strong wind.", zh: "降落" },
    { front: "luggage", pos: "n.", def: "the bags and suitcases you take when travelling", example: "You can leave your luggage at the hotel reception.", zh: "行李" },
    { front: "passenger", pos: "n.", def: "a person travelling in a vehicle but not driving it", example: "The bus can carry up to fifty passengers.", zh: "乘客" },
    { front: "platform", pos: "n.", def: "the area in a station where you get on and off trains", example: "The train to Edinburgh leaves from platform four.", zh: "月台" },
    { front: "resort", pos: "n.", def: "a place where many people go on holiday", example: "This ski resort is popular with families in winter.", zh: "度假勝地" },
    { front: "sightseeing", pos: "n.", def: "the activity of visiting interesting places as a tourist", example: "We spent the whole day sightseeing in the old town.", zh: "觀光" },
    { front: "souvenir", pos: "n.", def: "something you buy to remember a place you visited", example: "She bought a small wooden boat as a souvenir of Greece.", zh: "紀念品" },
    { front: "timetable", pos: "n.", def: "a list showing the times when buses, trains or classes happen", example: "Check the timetable before you go to the station.", zh: "時刻表" },
    { front: "visa", pos: "n.", def: "an official stamp or document allowing you to enter a country", example: "You need a visa to travel to some countries in Asia.", zh: "簽證" },
    { front: "voyage", pos: "n.", def: "a long journey, especially by sea or in space", example: "The voyage across the Atlantic took ten days.", zh: "航行、航海" },
    /* ---------- Feelings & personality ---------- */
    { front: "anxious", pos: "adj.", def: "worried and nervous about something", example: "She felt anxious about her first day at the new school.", zh: "焦慮的" },
    { front: "ashamed", pos: "adj.", def: "feeling bad because you have done something wrong", example: "He was ashamed of the way he had spoken to his mother.", zh: "羞愧的" },
    { front: "bad-tempered", pos: "adj.", def: "easily annoyed and often angry", example: "My uncle gets bad-tempered when he hasn't slept well.", zh: "脾氣壞的" },
    { front: "cautious", pos: "adj.", def: "careful to avoid danger or mistakes", example: "Drivers should be extra cautious on icy roads.", zh: "謹慎的" },
    { front: "cheerful", pos: "adj.", def: "happy and showing it in your behaviour", example: "The waiter greeted us with a cheerful smile.", zh: "開朗的、愉快的" },
    { front: "confident", pos: "adj.", def: "sure about your own abilities", example: "She sounded calm and confident during the presentation.", zh: "有自信的" },
    { front: "curious", pos: "adj.", def: "wanting to know or learn about something", example: "The children were curious about the strange machine.", zh: "好奇的" },
    { front: "delighted", pos: "adj.", def: "very pleased and happy", example: "We were delighted to hear that you passed your exam.", zh: "非常高興的" },
    { front: "depressed", pos: "adj.", def: "very unhappy for a long period", example: "He felt depressed after losing his job and rarely went out.", zh: "沮喪的、憂鬱的" },
    { front: "disappointed", pos: "adj.", def: "unhappy because something was not as good as expected", example: "Fans were disappointed when the concert was cancelled.", zh: "失望的" },
    { front: "embarrassed", pos: "adj.", def: "feeling shy or uncomfortable about what others think of you", example: "I was so embarrassed when I forgot her name.", zh: "尷尬的" },
    { front: "enthusiastic", pos: "adj.", def: "showing a lot of excitement and interest in something", example: "The new coach is enthusiastic about training young players.", zh: "熱情的、熱衷的" },
    { front: "envious", pos: "adj.", def: "wishing you had what someone else has", example: "I must admit I am envious of your long holidays.", zh: "羨慕的、嫉妒的" },
    { front: "exhausted", pos: "adj.", def: "extremely tired", example: "After the marathon, the runners were completely exhausted.", zh: "筋疲力盡的" },
    { front: "frightened", pos: "adj.", def: "feeling fear; afraid", example: "The little boy was frightened of the dark.", zh: "害怕的" },
    { front: "frustrated", pos: "adj.", def: "annoyed because you cannot achieve or change something", example: "She grew frustrated when the printer stopped working again.", zh: "沮喪的、氣餒的" },
    { front: "generous", pos: "adj.", def: "happy to give more money, time or help than expected", example: "It was generous of him to pay for everyone's dinner.", zh: "慷慨的" },
    { front: "grateful", pos: "adj.", def: "feeling thankful for something someone has done", example: "I am really grateful for all your support this year.", zh: "感激的" },
    { front: "jealous", pos: "adj.", def: "unhappy because someone has something you want", example: "He felt jealous when his brother got a new bike.", zh: "嫉妒的" },
    { front: "keen", pos: "adj.", def: "very interested in something and wanting to do it", example: "She is keen on photography and never travels without her camera.", zh: "熱衷的、渴望的" },
    { front: "miserable", pos: "adj.", def: "very unhappy or uncomfortable", example: "The weather was cold and wet, and we all felt miserable.", zh: "悲慘的、痛苦的" },
    { front: "nervous", pos: "adj.", def: "worried or slightly frightened about something", example: "He always gets nervous before speaking in public.", zh: "緊張的" },
    { front: "optimistic", pos: "adj.", def: "believing that good things will happen", example: "Despite the bad news, she remained optimistic about the future.", zh: "樂觀的" },
    { front: "pessimistic", pos: "adj.", def: "believing that bad things are likely to happen", example: "Don't be so pessimistic — the situation may improve soon.", zh: "悲觀的" },
    { front: "relieved", pos: "adj.", def: "happy because something bad did not happen or has ended", example: "We were relieved to hear that everyone was safe.", zh: "鬆一口氣的" },
    { front: "sensible", pos: "adj.", def: "showing good judgement; practical", example: "It was sensible of you to book the tickets early.", zh: "明智的" },
    { front: "sensitive", pos: "adj.", def: "easily affected by feelings, or understanding others' feelings", example: "Be careful what you say — she is very sensitive about her weight.", zh: "敏感的、體貼的" },
    { front: "stubborn", pos: "adj.", def: "refusing to change your opinion or plans", example: "He is too stubborn to admit that he was wrong.", zh: "固執的" },
    { front: "sympathetic", pos: "adj.", def: "showing that you understand and care about someone's problems", example: "The doctor was very sympathetic when I explained my worries.", zh: "有同情心的" },
    { front: "thrilled", pos: "adj.", def: "extremely pleased and excited", example: "She was thrilled to win first prize in the competition.", zh: "興奮的、極為高興的" },
    /* ---------- Environment & nature ---------- */
    { front: "breeze", pos: "n.", def: "a light, gentle wind", example: "A cool breeze came in from the sea in the evening.", zh: "微風" },
    { front: "climate", pos: "n.", def: "the usual weather conditions of a place", example: "The Mediterranean climate is warm and dry in summer.", zh: "氣候" },
    { front: "coast", pos: "n.", def: "the land next to the sea", example: "They rented a cottage on the south coast for a week.", zh: "海岸" },
    { front: "conservation", pos: "n.", def: "the protection of nature and wildlife", example: "The park was created for the conservation of rare birds.", zh: "保育、保護" },
    { front: "drought", pos: "n.", def: "a long period with little or no rain", example: "The drought destroyed most of the region's crops.", zh: "乾旱" },
    { front: "earthquake", pos: "n.", def: "a sudden shaking of the ground", example: "The earthquake damaged several buildings in the city centre.", zh: "地震" },
    { front: "endangered", pos: "adj.", def: "at risk of no longer existing", example: "Tigers are an endangered species in many parts of Asia.", zh: "瀕臨絕種的" },
    { front: "extinct", pos: "adj.", def: "no longer existing as a species", example: "Dinosaurs became extinct millions of years ago.", zh: "絕種的" },
    { front: "flood", pos: "n.", def: "a large amount of water covering land that is usually dry", example: "The heavy rain caused floods in several villages.", zh: "洪水" },
    { front: "forecast", pos: "n.", def: "a statement about what the weather will be like", example: "The forecast says it will be sunny all weekend.", zh: "預報" },
    { front: "habitat", pos: "n.", def: "the natural home of an animal or plant", example: "Cutting down forests destroys the habitat of many animals.", zh: "棲息地" },
    { front: "harvest", pos: "n.", def: "the time when crops are collected, or the crops themselves", example: "Farmers are expecting a good harvest this autumn.", zh: "收成、收穫" },
    { front: "hurricane", pos: "n.", def: "a violent storm with very strong winds", example: "The hurricane forced thousands of people to leave their homes.", zh: "颶風" },
    { front: "litter", pos: "n.", def: "rubbish left lying in public places", example: "Please take your litter home with you after the picnic.", zh: "垃圾（亂丟的）" },
    { front: "pollution", pos: "n.", def: "damage to air, water or land caused by harmful substances", example: "Air pollution in the city gets worse during rush hour.", zh: "污染" },
    { front: "recycle", pos: "v.", def: "to treat used materials so they can be used again", example: "We recycle glass, paper and plastic at home.", zh: "回收" },
    { front: "renewable", pos: "adj.", def: "describing energy that can be replaced naturally and never runs out", example: "Wind and solar power are renewable sources of energy.", zh: "可再生的" },
    { front: "rural", pos: "adj.", def: "connected with the countryside", example: "She grew up in a rural area with only one small shop.", zh: "鄉村的" },
    { front: "scenery", pos: "n.", def: "the natural beauty of an area", example: "The scenery in the Scottish Highlands is breathtaking.", zh: "風景" },
    { front: "shortage", pos: "n.", def: "a situation where there is not enough of something", example: "There is a serious water shortage in the region this summer.", zh: "短缺" },
    { front: "solar", pos: "adj.", def: "relating to or powered by the sun", example: "They installed solar panels on the roof to save money.", zh: "太陽能的、太陽的" },
    { front: "species", pos: "n.", def: "a group of animals or plants of the same type", example: "Scientists discovered a new species of frog in the rainforest.", zh: "物種" },
    { front: "sustainable", pos: "adj.", def: "able to continue without damaging the environment", example: "The hotel promotes sustainable tourism in the area.", zh: "永續的" },
    { front: "thunderstorm", pos: "n.", def: "a storm with thunder, lightning and heavy rain", example: "The match was stopped because of a sudden thunderstorm.", zh: "雷雨" },
    { front: "urban", pos: "adj.", def: "connected with towns and cities", example: "More and more people are moving to urban areas for work.", zh: "都市的" },
    { front: "waste", pos: "n.", def: "material that is no longer needed and is thrown away", example: "The factory was fined for dumping waste into the river.", zh: "廢棄物" },
    { front: "wildlife", pos: "n.", def: "animals and plants living in natural conditions", example: "The island is famous for its unusual wildlife.", zh: "野生動植物" },
    /* ---------- Money & shopping ---------- */
    { front: "affordable", pos: "adj.", def: "cheap enough for people to buy", example: "The city needs more affordable housing for young families.", zh: "負擔得起的" },
    { front: "auction", pos: "n.", def: "a public sale where things go to the person offering the most money", example: "The painting was sold at auction for two million pounds.", zh: "拍賣" },
    { front: "bargain", pos: "n.", def: "something bought for less than its usual price", example: "This coat was a real bargain — only twenty euros in the sale.", zh: "便宜貨、划算的交易" },
    { front: "bill", pos: "n.", def: "a piece of paper showing how much you must pay", example: "Could we have the bill, please? We are in a bit of a hurry.", zh: "帳單" },
    { front: "borrow", pos: "v.", def: "to take and use something that you will give back later", example: "Can I borrow your dictionary until tomorrow?", zh: "借入" },
    { front: "budget", pos: "n.", def: "the amount of money available for something", example: "We are travelling on a tight budget, so we will stay in hostels.", zh: "預算" },
    { front: "cash", pos: "n.", def: "money in the form of coins and notes", example: "The market stall only accepts cash, not cards.", zh: "現金" },
    { front: "charge", pos: "v.", def: "to ask an amount of money for goods or a service", example: "The garage charged me eighty pounds to repair the brakes.", zh: "收費" },
    { front: "currency", pos: "n.", def: "the money used in a particular country", example: "You should change some currency before you travel.", zh: "貨幣" },
    { front: "debt", pos: "n.", def: "money that you owe to someone", example: "It took them years to pay off their debts.", zh: "債務" },
    { front: "discount", pos: "n.", def: "a reduction in the usual price", example: "Students get a ten percent discount at this bookshop.", zh: "折扣" },
    { front: "expense", pos: "n.", def: "the money you spend on something", example: "Running a car is a big expense for most families.", zh: "花費、開銷" },
    { front: "fee", pos: "n.", def: "money paid for a professional service or activity", example: "The gym charges a small monthly membership fee.", zh: "費用" },
    { front: "fine", pos: "n.", def: "money paid as a punishment for breaking a rule", example: "He had to pay a fine for parking on the pavement.", zh: "罰款" },
    { front: "fortune", pos: "n.", def: "a very large amount of money", example: "She made a fortune selling her app to a tech company.", zh: "巨款、財富" },
    { front: "invest", pos: "v.", def: "to put money into something to make a profit", example: "They decided to invest their savings in property.", zh: "投資" },
    { front: "lend", pos: "v.", def: "to give something to someone for a time, expecting it back", example: "My brother lent me fifty pounds until payday.", zh: "借出" },
    { front: "loan", pos: "n.", def: "money borrowed, usually from a bank, that must be paid back", example: "They took out a loan to open their restaurant.", zh: "貸款" },
    { front: "luxury", pos: "n.", def: "something expensive and enjoyable but not necessary", example: "For us, eating out every week is a real luxury.", zh: "奢侈品、奢華" },
    { front: "mortgage", pos: "n.", def: "money borrowed from a bank to buy a house", example: "They will be paying off their mortgage for the next twenty years.", zh: "房屋貸款" },
    { front: "purchase", pos: "v.", def: "to buy something, especially something large or formal", example: "Tickets can be purchased online or at the door.", zh: "購買" },
    { front: "receipt", pos: "n.", def: "a piece of paper proving that you have paid for something", example: "Keep your receipt in case you want to return the shirt.", zh: "收據" },
    { front: "refund", pos: "n.", def: "money given back when you return something", example: "The shop gave me a full refund because the kettle was faulty.", zh: "退款" },
    { front: "savings", pos: "n.", def: "money you have kept, especially in a bank", example: "She used her savings to travel around South America.", zh: "存款、儲蓄" },
    { front: "second-hand", pos: "adj.", def: "already used by someone else; not new", example: "He bought a second-hand bike for half the price of a new one.", zh: "二手的" },
    { front: "valuable", pos: "adj.", def: "worth a lot of money, or very useful", example: "Never leave valuable items in your car overnight.", zh: "貴重的、寶貴的" },
    { front: "wallet", pos: "n.", def: "a small flat case for money and cards", example: "I realised at the till that I had left my wallet at home.", zh: "皮夾" },
    { front: "wealthy", pos: "adj.", def: "having a lot of money; rich", example: "The hotel attracts wealthy tourists from all over the world.", zh: "富有的" },
    { front: "withdraw", pos: "v.", def: "to take money out of a bank account", example: "You can withdraw up to 500 euros a day from this machine.", zh: "提款" },
    /* ---------- Health & body ---------- */
    { front: "ache", pos: "n.", def: "a continuous dull pain", example: "After moving the furniture, I had an ache in my back for days.", zh: "疼痛" },
    { front: "allergy", pos: "n.", def: "a medical condition in which your body reacts badly to something", example: "He has an allergy to nuts, so check the ingredients carefully.", zh: "過敏" },
    { front: "bandage", pos: "n.", def: "a strip of cloth tied around an injury", example: "The nurse wrapped a bandage around his sprained ankle.", zh: "繃帶" },
    { front: "bruise", pos: "n.", def: "a dark mark on the skin caused by a knock", example: "She had a large bruise on her leg after falling off her bike.", zh: "瘀傷" },
    { front: "check-up", pos: "n.", def: "a general medical examination", example: "You should have a dental check-up at least once a year.", zh: "健康檢查" },
    { front: "cure", pos: "n.", def: "something that makes an illness go away", example: "Scientists are still searching for a cure for the common cold.", zh: "療法、治癒" },
    { front: "diagnose", pos: "v.", def: "to identify what illness someone has", example: "The doctor diagnosed her with a mild ear infection.", zh: "診斷" },
    { front: "dizzy", pos: "adj.", def: "feeling as if everything is spinning around you", example: "He felt dizzy after standing up too quickly.", zh: "頭暈的" },
    { front: "fever", pos: "n.", def: "a body temperature that is higher than normal", example: "She stayed in bed with a fever and a sore throat.", zh: "發燒" },
    { front: "fit", pos: "adj.", def: "healthy and physically strong", example: "He keeps fit by cycling to work every day.", zh: "健康的、體格好的" },
    { front: "heal", pos: "v.", def: "to become healthy again after an injury", example: "The cut on my hand took about a week to heal.", zh: "癒合、痊癒" },
    { front: "infection", pos: "n.", def: "a disease caused by bacteria or a virus", example: "Wash the wound carefully to prevent infection.", zh: "感染" },
    { front: "injury", pos: "n.", def: "physical harm to a person's body", example: "Luckily, no one suffered serious injuries in the accident.", zh: "傷害、受傷" },
    { front: "insomnia", pos: "n.", def: "the condition of being unable to sleep", example: "Too much coffee in the evening gives me insomnia.", zh: "失眠" },
    { front: "nutritious", pos: "adj.", def: "containing substances that your body needs to stay healthy", example: "A nutritious breakfast helps you concentrate at school.", zh: "有營養的" },
    { front: "operation", pos: "n.", def: "a medical procedure in which a body is cut open to repair it", example: "He needs an operation on his knee after the football injury.", zh: "手術" },
    { front: "painkiller", pos: "n.", def: "a medicine that reduces pain", example: "Take a painkiller if your headache gets worse.", zh: "止痛藥" },
    { front: "patient", pos: "n.", def: "a person receiving medical treatment", example: "The hospital treats hundreds of patients every day.", zh: "病人" },
    { front: "prescription", pos: "n.", def: "a doctor's written order for medicine", example: "You cannot buy these tablets without a prescription.", zh: "處方" },
    { front: "recover", pos: "v.", def: "to become healthy again after illness or injury", example: "It took her a month to recover from the operation.", zh: "康復" },
    { front: "remedy", pos: "n.", def: "a treatment or cure for an illness or problem", example: "Hot lemon with honey is a traditional remedy for a sore throat.", zh: "療法、補救方法" },
    { front: "sneeze", pos: "v.", def: "to suddenly blow air out of your nose, often because of a cold", example: "The dust in the attic made everyone sneeze.", zh: "打噴嚏" },
    { front: "sore", pos: "adj.", def: "painful when touched or used", example: "My legs were sore for two days after the long hike.", zh: "疼痛的" },
    { front: "surgeon", pos: "n.", def: "a doctor who performs operations", example: "The surgeon explained the risks before the operation.", zh: "外科醫生" },
    { front: "swollen", pos: "adj.", def: "larger than usual because of injury or illness", example: "Her ankle was swollen after she twisted it on the stairs.", zh: "腫脹的" },
    { front: "symptom", pos: "n.", def: "a sign that shows you have an illness", example: "A high temperature is a common symptom of flu.", zh: "症狀" },
    { front: "treatment", pos: "n.", def: "medical care given to a sick or injured person", example: "The new treatment has helped many patients with the disease.", zh: "治療" },
    { front: "wound", pos: "n.", def: "an injury in which the skin is cut or broken", example: "The soldier's wound healed slowly over several weeks.", zh: "傷口" },
    /* ---------- Media & technology ---------- */
    { front: "advertisement", pos: "n.", def: "a notice or short film that tries to persuade people to buy something", example: "The advertisement for the new phone appears everywhere online.", zh: "廣告" },
    { front: "article", pos: "n.", def: "a piece of writing in a newspaper or magazine", example: "I read an interesting article about sleep and memory.", zh: "文章" },
    { front: "audience", pos: "n.", def: "the people watching or listening to a performance or programme", example: "The audience clapped loudly at the end of the play.", zh: "觀眾、聽眾" },
    { front: "broadcast", pos: "v.", def: "to send out a programme on television or radio", example: "The interview will be broadcast live on national radio.", zh: "廣播、播出" },
    { front: "browse", pos: "v.", def: "to look through websites or things in a shop without a clear plan", example: "I spent the evening browsing travel websites for holiday ideas.", zh: "瀏覽" },
    { front: "celebrity", pos: "n.", def: "a famous person, especially in entertainment", example: "The restaurant is popular with celebrities and film stars.", zh: "名人" },
    { front: "channel", pos: "n.", def: "a television station or a way of communicating", example: "There is a good documentary on channel four tonight.", zh: "頻道" },
    { front: "device", pos: "n.", def: "a piece of equipment made for a particular purpose", example: "Please switch off all electronic devices before take-off.", zh: "裝置、設備" },
    { front: "download", pos: "v.", def: "to copy data from the internet onto your computer or phone", example: "You can download the app for free from the store.", zh: "下載" },
    { front: "edit", pos: "v.", def: "to make changes to a text, film or recording", example: "She spent hours editing the video before posting it.", zh: "編輯" },
    { front: "gadget", pos: "n.", def: "a small, clever tool or device", example: "My dad loves buying kitchen gadgets he never actually uses.", zh: "小裝置、小玩意" },
    { front: "headline", pos: "n.", def: "the title of a newspaper story, printed in large letters", example: "The story about the flood was in all the headlines this morning.", zh: "新聞標題" },
    { front: "journalist", pos: "n.", def: "a person who writes news stories for media", example: "A journalist interviewed local residents about the new road.", zh: "記者" },
    { front: "network", pos: "n.", def: "a system of connected computers, or a group of connected people", example: "The office network was down all morning, so nobody could work.", zh: "網路、人脈網絡" },
    { front: "password", pos: "n.", def: "a secret word or set of characters used to access something", example: "Choose a strong password and never share it with anyone.", zh: "密碼" },
    { front: "podcast", pos: "n.", def: "a digital audio programme you can listen to online", example: "I listen to a history podcast on my way to work.", zh: "播客節目" },
    { front: "press", pos: "n.", def: "newspapers and magazines, or the journalists who work for them", example: "The minister refused to answer questions from the press.", zh: "新聞界、媒體" },
    { front: "publish", pos: "v.", def: "to produce a book, article or information for the public", example: "Her first novel was published when she was only twenty-two.", zh: "出版、發表" },
    { front: "review", pos: "n.", def: "a report giving an opinion about a book, film or product", example: "The film got excellent reviews from the critics.", zh: "評論" },
    { front: "stream", pos: "v.", def: "to watch or listen to something directly from the internet", example: "We usually stream films instead of going to the cinema.", zh: "串流播放" },
    { front: "subscribe", pos: "v.", def: "to pay regularly to receive a service or publication", example: "I subscribe to two music services, which is probably one too many.", zh: "訂閱" },
    { front: "update", pos: "v.", def: "to add the most recent information or version", example: "Remember to update your phone's software regularly.", zh: "更新" },
    { front: "upload", pos: "v.", def: "to copy data from your device onto the internet", example: "She uploaded the photos from the trip to share with her family.", zh: "上傳" },
    { front: "viewer", pos: "n.", def: "a person who watches television or online videos", example: "Millions of viewers watched the final episode of the series.", zh: "觀眾" },
    { front: "viral", pos: "adj.", def: "spreading very quickly among internet users", example: "The video of the dancing cat went viral within hours.", zh: "瘋傳的、病毒式的" },
    { front: "virtual", pos: "adj.", def: "existing on computers or the internet rather than in the real world", example: "The museum offers a virtual tour that you can take from home.", zh: "虛擬的" },
    { front: "wireless", pos: "adj.", def: "working without wires or cables", example: "These wireless headphones connect to your phone automatically.", zh: "無線的" },
    /* ---------- Society, crime & relationships ---------- */
    { front: "accuse", pos: "v.", def: "to say that someone has done something wrong or illegal", example: "The manager was accused of stealing money from the company.", zh: "指控" },
    { front: "acquaintance", pos: "n.", def: "a person you know slightly but who is not a close friend", example: "He is just an acquaintance from work, not a real friend.", zh: "認識的人、泛泛之交" },
    { front: "arrest", pos: "v.", def: "to take someone to a police station because they may have committed a crime", example: "Police arrested two men in connection with the robbery.", zh: "逮捕" },
    { front: "burglar", pos: "n.", def: "a person who enters a building illegally to steal", example: "The burglar got in through an open kitchen window.", zh: "竊賊、入室盜竊者" },
    { front: "charity", pos: "n.", def: "an organisation that helps people in need", example: "She runs marathons to raise money for a children's charity.", zh: "慈善機構" },
    { front: "community", pos: "n.", def: "the people living in one area, or a group with something in common", example: "The whole community helped to rebuild the damaged school.", zh: "社區、社群" },
    { front: "court", pos: "n.", def: "the place where legal cases are judged", example: "The case will be heard in court next month.", zh: "法院、法庭" },
    { front: "divorce", pos: "n.", def: "the legal ending of a marriage", example: "After the divorce, the children lived mainly with their mother.", zh: "離婚" },
    { front: "evidence", pos: "n.", def: "facts or objects that show whether something is true", example: "There was not enough evidence to prove he was guilty.", zh: "證據" },
    { front: "generation", pos: "n.", def: "all the people born around the same time", example: "The younger generation finds new technology much easier to use.", zh: "世代" },
    { front: "gossip", pos: "n.", def: "talk about other people's private lives, often unkind", example: "Try not to listen to office gossip — most of it is untrue.", zh: "八卦、流言" },
    { front: "guilty", pos: "adj.", def: "having broken a law, or feeling bad about something you did", example: "The jury found him guilty of theft.", zh: "有罪的、內疚的" },
    { front: "homeless", pos: "adj.", def: "without a place to live", example: "The shelter provides meals for homeless people every evening.", zh: "無家可歸的" },
    { front: "immigrant", pos: "n.", def: "a person who comes to live in a foreign country", example: "Many immigrants opened restaurants and shops in the neighbourhood.", zh: "移民" },
    { front: "innocent", pos: "adj.", def: "not guilty of a crime", example: "He insisted he was innocent and demanded a fair trial.", zh: "無辜的、清白的" },
    { front: "justice", pos: "n.", def: "fair treatment according to the law", example: "The victims' families are still waiting for justice.", zh: "正義、司法" },
    { front: "neighbourhood", pos: "n.", def: "an area of a town and the people who live there", example: "We moved to a quiet neighbourhood with lots of parks.", zh: "鄰里、街坊" },
    { front: "punishment", pos: "n.", def: "something unpleasant done to someone because they did something wrong", example: "As a punishment, he was not allowed to play video games for a week.", zh: "懲罰" },
    { front: "robbery", pos: "n.", def: "the crime of stealing using force or threats", example: "There was a robbery at the bank on the high street yesterday.", zh: "搶劫" },
    { front: "sentence", pos: "v.", def: "to state officially what punishment a criminal will receive", example: "The judge sentenced him to three years in prison.", zh: "判刑" },
    { front: "shoplifting", pos: "n.", def: "the crime of stealing goods from a shop", example: "The store installed cameras to reduce shoplifting.", zh: "順手牽羊、商店行竊" },
    { front: "suspect", pos: "n.", def: "a person the police think may have committed a crime", example: "The main suspect was seen near the bank before the robbery.", zh: "嫌疑犯" },
    { front: "theft", pos: "n.", def: "the crime of stealing something", example: "He reported the theft of his bicycle to the police.", zh: "竊盜" },
    { front: "trial", pos: "n.", def: "the legal process of deciding whether someone is guilty", example: "The trial lasted three weeks and attracted huge media attention.", zh: "審判" },
    { front: "victim", pos: "n.", def: "a person harmed by a crime, accident or event", example: "The victims of the flood received help from local charities.", zh: "受害者" },
    { front: "volunteer", pos: "n.", def: "a person who does work without being paid", example: "The festival needs volunteers to help visitors find their way.", zh: "志工" },
    { front: "witness", pos: "n.", def: "a person who sees a crime or accident happen", example: "A witness told the police exactly what she had seen.", zh: "目擊者、證人" },
    /* ---------- Phrasal verbs ---------- */
    { front: "back down", pos: "phr. v.", def: "to stop demanding something or admit you were wrong in an argument", example: "Neither side would back down, so the meeting ended without a deal.", zh: "讓步、退讓" },
    { front: "back up", pos: "phr. v.", def: "to make a copy of computer files, or to support someone", example: "Always back up your documents before updating your laptop.", zh: "備份；支持" },
    { front: "blow up", pos: "phr. v.", def: "to explode, or to fill something with air", example: "We blew up dozens of balloons for the birthday party.", zh: "爆炸；充氣" },
    { front: "break down", pos: "phr. v.", def: "to stop working, especially a car or machine", example: "Our car broke down on the motorway and we had to wait for help.", zh: "拋錨、故障" },
    { front: "break into", pos: "phr. v.", def: "to enter a building illegally, usually to steal", example: "Thieves broke into the office and stole three computers.", zh: "闖入、破門而入" },
    { front: "break up", pos: "phr. v.", def: "to end a romantic relationship", example: "They broke up after five years together but stayed friends.", zh: "分手" },
    { front: "bring up", pos: "phr. v.", def: "to care for a child until they are an adult, or to mention a topic", example: "She was brought up by her grandparents in a small village.", zh: "撫養；提起" },
    { front: "bump into", pos: "phr. v.", def: "to meet someone by chance", example: "I bumped into my old teacher at the supermarket yesterday.", zh: "偶遇" },
    { front: "call back", pos: "phr. v.", def: "to phone someone again", example: "He is in a meeting right now — could you call back after lunch?", zh: "回電" },
    { front: "call off", pos: "phr. v.", def: "to cancel something that was planned", example: "The match was called off because of the storm.", zh: "取消" },
    { front: "calm down", pos: "phr. v.", def: "to become less angry, upset or excited", example: "Take a deep breath and try to calm down before you reply.", zh: "冷靜下來" },
    { front: "carry on", pos: "phr. v.", def: "to continue doing something", example: "Despite the rain, the builders carried on working.", zh: "繼續" },
    { front: "carry out", pos: "phr. v.", def: "to do or complete a task, plan or promise", example: "Scientists carried out a series of tests on the new medicine.", zh: "執行、進行" },
    { front: "catch up", pos: "phr. v.", def: "to reach the same level or position as others", example: "She missed a week of school and had to work hard to catch up.", zh: "趕上" },
    { front: "check in", pos: "phr. v.", def: "to report your arrival at a hotel or airport", example: "We checked in online to avoid queuing at the airport.", zh: "報到、辦理入住" },
    { front: "check out", pos: "phr. v.", def: "to pay and leave a hotel, or to look at something interesting", example: "Guests must check out of their rooms by eleven o'clock.", zh: "退房；查看" },
    { front: "cheer up", pos: "phr. v.", def: "to become happier, or make someone happier", example: "I made her a cup of tea to cheer her up after the bad news.", zh: "振作起來、使開心" },
    { front: "come across", pos: "phr. v.", def: "to find something by chance", example: "I came across some old photos while tidying the attic.", zh: "偶然發現" },
    { front: "come along", pos: "phr. v.", def: "to go somewhere with someone, or to make progress", example: "We are going to the beach — why don't you come along?", zh: "一起來；進展" },
    { front: "come up with", pos: "phr. v.", def: "to think of an idea, plan or solution", example: "She came up with a brilliant name for the new cafe.", zh: "想出" },
    { front: "count on", pos: "phr. v.", def: "to depend on someone or something", example: "You can always count on Maria to help in an emergency.", zh: "依靠、指望" },
    { front: "cut down on", pos: "phr. v.", def: "to reduce the amount of something you use or do", example: "The doctor told him to cut down on sugar and fried food.", zh: "減少" },
    { front: "cut off", pos: "phr. v.", def: "to stop the supply of something, or to interrupt a phone call", example: "Our electricity was cut off during the storm last night.", zh: "切斷、中斷" },
    { front: "deal with", pos: "phr. v.", def: "to take action to solve a problem or handle a situation", example: "The manager dealt with the customer's complaint politely.", zh: "處理、應付" },
    { front: "do up", pos: "phr. v.", def: "to fasten something, or to repair and decorate a building", example: "They bought an old farmhouse and spent a year doing it up.", zh: "扣上；整修" },
    { front: "dress up", pos: "phr. v.", def: "to wear special or formal clothes", example: "You don't need to dress up — it's just a casual dinner.", zh: "盛裝打扮" },
    { front: "drop off", pos: "phr. v.", def: "to take someone or something to a place by car, or to fall asleep", example: "I can drop you off at the station on my way to work.", zh: "順道載送；打瞌睡" },
    { front: "drop out", pos: "phr. v.", def: "to leave school or a course before finishing it", example: "He dropped out of university to start his own business.", zh: "輟學、退出" },
    { front: "eat out", pos: "phr. v.", def: "to have a meal in a restaurant instead of at home", example: "We usually eat out on Friday evenings to celebrate the weekend.", zh: "外出用餐" },
    { front: "end up", pos: "phr. v.", def: "to finally be in a place or situation you did not plan", example: "We got lost and ended up in a tiny village miles from anywhere.", zh: "最終落得、結果變成" },
    { front: "fall apart", pos: "phr. v.", def: "to break into pieces, or to stop working properly", example: "These cheap shoes fell apart after only a month.", zh: "散架、崩潰" },
    { front: "fall out", pos: "phr. v.", def: "to have an argument and stop being friendly", example: "The two sisters fell out over money and did not speak for years.", zh: "鬧翻、吵架" },
    { front: "figure out", pos: "phr. v.", def: "to understand or solve something after thinking about it", example: "It took me a while to figure out how the new coffee machine works.", zh: "弄清楚、想出" },
    { front: "fill in", pos: "phr. v.", def: "to complete a form by writing information", example: "Please fill in this form and sign it at the bottom.", zh: "填寫" },
    { front: "find out", pos: "phr. v.", def: "to discover information", example: "I phoned the box office to find out what time the show starts.", zh: "查明、得知" },
    { front: "fit in", pos: "phr. v.", def: "to feel comfortable in a group because you are similar to the others", example: "It took him a few weeks to fit in at his new school.", zh: "融入" },
    { front: "get along", pos: "phr. v.", def: "to have a friendly relationship with someone", example: "Do you get along with your flatmates?", zh: "相處融洽" },
    { front: "get around", pos: "phr. v.", def: "to travel from place to place", example: "The best way to get around the city is by bike.", zh: "四處走動、出行" },
    { front: "get away with", pos: "phr. v.", def: "to do something wrong without being punished", example: "He cheated in the test and somehow got away with it.", zh: "逃過懲罰" },
    { front: "get by", pos: "phr. v.", def: "to manage to live with the money or things you have", example: "It is hard to get by on such a small salary in this city.", zh: "勉強過活" },
    { front: "get on with", pos: "phr. v.", def: "to continue doing a task, or to have a good relationship with someone", example: "Stop chatting and get on with your homework.", zh: "繼續做；與…處得好" },
    { front: "get over", pos: "phr. v.", def: "to recover from an illness, shock or disappointment", example: "It took her months to get over the flu completely.", zh: "克服、恢復" },
    { front: "get rid of", pos: "phr. v.", def: "to remove or throw away something you do not want", example: "We finally got rid of that broken old sofa.", zh: "擺脫、丟掉" },
    { front: "give away", pos: "phr. v.", def: "to give something free of charge, or to reveal a secret", example: "She gave away most of her books before moving abroad.", zh: "贈送；洩露" },
    { front: "give in", pos: "phr. v.", def: "to finally agree to something after refusing", example: "The children begged for a dog until their parents gave in.", zh: "屈服、讓步" },
    { front: "give up", pos: "phr. v.", def: "to stop doing something, especially a habit, or to stop trying", example: "He gave up smoking two years ago and feels much healthier.", zh: "戒除、放棄" },
    { front: "go off", pos: "phr. v.", def: "to explode or ring loudly, or to become bad to eat", example: "My alarm went off at six, but I stayed in bed until seven.", zh: "響起、爆炸；變質" },
    { front: "go on", pos: "phr. v.", def: "to continue, or to happen", example: "The party went on until three in the morning.", zh: "繼續；發生" },
    { front: "go through", pos: "phr. v.", def: "to experience something difficult, or to examine something carefully", example: "She went through a difficult time after losing her job.", zh: "經歷；仔細檢查" },
    { front: "grow up", pos: "phr. v.", def: "to change from a child into an adult", example: "He grew up in a small fishing town on the coast.", zh: "長大" },
    { front: "hand in", pos: "phr. v.", def: "to give work to a teacher or a document to an official", example: "You must hand in your essays by Monday morning.", zh: "繳交" },
    { front: "hand out", pos: "phr. v.", def: "to give something to each person in a group", example: "The teacher handed out the exam papers in silence.", zh: "分發" },
    { front: "hang out", pos: "phr. v.", def: "to spend time relaxing, often with friends", example: "At weekends we usually hang out at the shopping centre.", zh: "閒晃、廝混" },
    { front: "hang up", pos: "phr. v.", def: "to end a phone call", example: "She was so angry that she hung up before I could explain.", zh: "掛斷電話" },
    { front: "hold on", pos: "phr. v.", def: "to wait for a short time", example: "Hold on a second — I'll just get a pen to write that down.", zh: "稍等" },
    { front: "hurry up", pos: "phr. v.", def: "to do something more quickly", example: "Hurry up, or we will miss the beginning of the film!", zh: "趕快" },
    { front: "join in", pos: "phr. v.", def: "to take part in an activity with other people", example: "Everyone joined in the singing at the end of the show.", zh: "加入、參與" },
    { front: "keep up with", pos: "phr. v.", def: "to move or progress at the same speed as someone or something", example: "He walks so fast that I can hardly keep up with him.", zh: "跟上" },
    { front: "let down", pos: "phr. v.", def: "to disappoint someone by not doing what you promised", example: "She promised to help me move house, and she never lets me down.", zh: "使失望" },
    { front: "log in", pos: "phr. v.", def: "to enter a username and password to use a computer system", example: "I could not log in because I had forgotten my password.", zh: "登入" },
    { front: "look after", pos: "phr. v.", def: "to take care of someone or something", example: "Could you look after my plants while I am on holiday?", zh: "照顧" },
    { front: "look forward to", pos: "phr. v.", def: "to feel pleased about something that is going to happen", example: "We are really looking forward to seeing you next month.", zh: "期待" },
    { front: "look into", pos: "phr. v.", def: "to investigate or examine a problem", example: "The airline promised to look into my complaint about the lost bag.", zh: "調查" },
    { front: "look up", pos: "phr. v.", def: "to search for information in a book or online", example: "If you don't know the word, look it up in a dictionary.", zh: "查閱" },
    { front: "look up to", pos: "phr. v.", def: "to admire and respect someone", example: "Many young players look up to the team captain.", zh: "敬仰" },
    { front: "make up for", pos: "phr. v.", def: "to do something good to balance something bad", example: "He bought her flowers to make up for forgetting her birthday.", zh: "彌補" },
    { front: "mess up", pos: "phr. v.", def: "to do something badly or make something untidy", example: "I completely messed up the interview by arriving late.", zh: "搞砸" },
    { front: "move in", pos: "phr. v.", def: "to start living in a new home", example: "Our new neighbours moved in last weekend.", zh: "搬入" },
    { front: "move out", pos: "phr. v.", def: "to stop living in a home and leave it", example: "She moved out of her parents' house when she started university.", zh: "搬出" },
    { front: "own up", pos: "phr. v.", def: "to admit that you did something wrong", example: "Nobody owned up to breaking the classroom window.", zh: "坦承" },
    { front: "pass away", pos: "phr. v.", def: "to die (a polite expression)", example: "Her grandfather passed away peacefully at the age of ninety.", zh: "去世" },
    { front: "pass out", pos: "phr. v.", def: "to suddenly become unconscious; to faint", example: "It was so hot in the hall that one of the singers passed out.", zh: "昏倒" },
    { front: "pay back", pos: "phr. v.", def: "to return money that you borrowed", example: "I will pay you back as soon as I get my salary.", zh: "償還" },
    { front: "pick up", pos: "phr. v.", def: "to collect someone or something, or to learn a skill without lessons", example: "I will pick you up from the airport at eight.", zh: "接送；學會" },
    { front: "point out", pos: "phr. v.", def: "to tell someone about a fact or mistake", example: "The guide pointed out several famous buildings as we walked.", zh: "指出" },
    { front: "put off", pos: "phr. v.", def: "to delay something until later", example: "Stop putting off the decision — the deadline is tomorrow.", zh: "推遲" },
    { front: "put out", pos: "phr. v.", def: "to stop a fire or light from burning", example: "Firefighters took two hours to put out the blaze.", zh: "撲滅" },
    { front: "put up with", pos: "phr. v.", def: "to accept something unpleasant without complaining", example: "I don't know how you put up with all that noise from next door.", zh: "忍受" },
    { front: "run away", pos: "phr. v.", def: "to leave a place secretly because you are unhappy or afraid", example: "The dog ran away when it heard the fireworks.", zh: "逃跑" },
    { front: "run into", pos: "phr. v.", def: "to meet someone unexpectedly, or to experience problems", example: "We ran into some old friends at the concert last night.", zh: "偶遇；遭遇" },
    { front: "run over", pos: "phr. v.", def: "to hit someone or something with a vehicle", example: "Slow down — you nearly ran over that cat!", zh: "輾過、撞倒" },
    { front: "see off", pos: "phr. v.", def: "to go to a station or airport to say goodbye to someone", example: "The whole family came to the airport to see her off.", zh: "送行" },
    { front: "set off", pos: "phr. v.", def: "to start a journey", example: "We set off early to avoid the morning traffic.", zh: "出發" },
    { front: "set up", pos: "phr. v.", def: "to start a company or organisation, or to arrange equipment", example: "They set up a small design studio in an old warehouse.", zh: "創立、設立" },
    { front: "settle down", pos: "phr. v.", def: "to start living a quiet life in one place, or to become calm", example: "After years of travelling, he settled down in a village by the sea.", zh: "安頓下來" },
    { front: "show off", pos: "phr. v.", def: "to try to make people admire you in an annoying way", example: "He bought a sports car just to show off to his friends.", zh: "炫耀" },
    { front: "show up", pos: "phr. v.", def: "to arrive, especially when people are waiting for you", example: "We waited an hour, but the electrician never showed up.", zh: "出現、露面" },
    { front: "sign up", pos: "phr. v.", def: "to put your name on a list to join a course or activity", example: "Over a hundred people signed up for the charity run.", zh: "報名" },
    { front: "slow down", pos: "phr. v.", def: "to go or happen more slowly", example: "The doctor advised him to slow down and take more rest.", zh: "放慢速度" },
    { front: "sort out", pos: "phr. v.", def: "to solve a problem or organise something properly", example: "It took a week to sort out the mistake with my phone bill.", zh: "解決、整理" },
    { front: "speak up", pos: "phr. v.", def: "to talk more loudly, or to say what you think openly", example: "Could you speak up a bit? We can't hear you at the back.", zh: "大聲說；直言" },
    { front: "split up", pos: "phr. v.", def: "to end a relationship, or to divide into smaller groups", example: "The band split up after their third album.", zh: "分手、拆夥" },
    { front: "stand for", pos: "phr. v.", def: "to be an abbreviation of something, or to accept a situation", example: "What does BBC stand for?", zh: "代表；容忍" },
    { front: "stand out", pos: "phr. v.", def: "to be easy to notice because of being different or better", example: "Her red coat made her stand out in the crowd.", zh: "突出、顯眼" },
    { front: "stay up", pos: "phr. v.", def: "to not go to bed at the usual time", example: "The kids stayed up late to watch the fireworks.", zh: "熬夜" },
    { front: "take after", pos: "phr. v.", def: "to look or behave like an older family member", example: "Everyone says she takes after her mother.", zh: "與（長輩）相像" },
    { front: "take off", pos: "phr. v.", def: "to leave the ground and begin flying, or to remove clothing", example: "The plane took off twenty minutes late.", zh: "起飛；脫掉" },
    { front: "take on", pos: "phr. v.", def: "to accept extra work or responsibility, or to employ someone", example: "The shop takes on extra staff every Christmas.", zh: "承擔；僱用" },
    { front: "take over", pos: "phr. v.", def: "to get control of a company or job from someone else", example: "Her son will take over the family business when she retires.", zh: "接管" },
    { front: "take up", pos: "phr. v.", def: "to start a new hobby or activity", example: "He took up painting after he retired.", zh: "開始從事" },
    { front: "tell off", pos: "phr. v.", def: "to speak angrily to someone because they did something wrong", example: "The teacher told him off for using his phone in class.", zh: "責罵" },
    { front: "throw away", pos: "phr. v.", def: "to get rid of something you no longer want", example: "Don't throw away those boxes — we might need them for the move.", zh: "丟掉" },
    { front: "try on", pos: "phr. v.", def: "to put on clothes to see if they fit", example: "She tried on five dresses before choosing the blue one.", zh: "試穿" },
    { front: "try out", pos: "phr. v.", def: "to test something to see if it works or if you like it", example: "Can I try out your new tablet before I buy one myself?", zh: "試用" },
    { front: "turn down", pos: "phr. v.", def: "to refuse an offer, or to reduce the volume or heat", example: "She turned down the job because the office was too far away.", zh: "拒絕；調低" },
    { front: "turn into", pos: "phr. v.", def: "to change and become something different", example: "The friendly discussion quickly turned into an argument.", zh: "變成" },
    { front: "turn out", pos: "phr. v.", def: "to happen in a particular way or have a particular result", example: "The picnic turned out better than we had expected.", zh: "結果是" },
    { front: "turn up", pos: "phr. v.", def: "to arrive, often unexpectedly, or to increase the volume", example: "He turned up at the party without an invitation.", zh: "現身；調高" },
    { front: "warm up", pos: "phr. v.", def: "to prepare your body for exercise, or to become warmer", example: "The players warmed up for twenty minutes before the match.", zh: "熱身" },
    { front: "wear out", pos: "phr. v.", def: "to become too old or damaged to use, or to make someone tired", example: "I have worn out three pairs of running shoes this year.", zh: "磨損；使筋疲力盡" },
    { front: "work out", pos: "phr. v.", def: "to exercise, or to find the answer to something", example: "She works out at the gym three times a week.", zh: "健身；算出" },
    { front: "wrap up", pos: "phr. v.", def: "to cover something in paper, or to dress warmly, or to finish something", example: "Wrap up well — it is freezing outside today.", zh: "包起來；穿暖；結束" },
    /* ---------- Collocations ---------- */
    { front: "break a record", pos: "collocation", def: "to do something better or faster than anyone before", example: "She broke the national record in the 200 metres last night.", zh: "打破紀錄" },
    { front: "break the law", pos: "collocation", def: "to do something illegal", example: "You are breaking the law if you ride a motorbike without a helmet.", zh: "違法" },
    { front: "catch a cold", pos: "collocation", def: "to become ill with a cold", example: "Put on a jacket, or you will catch a cold.", zh: "感冒" },
    { front: "catch sight of", pos: "collocation", def: "to see someone or something suddenly and briefly", example: "I caught sight of an old friend in the crowd at the station.", zh: "瞥見" },
    { front: "commit a crime", pos: "collocation", def: "to do something illegal", example: "He was only sixteen when he committed his first crime.", zh: "犯罪" },
    { front: "do your best", pos: "collocation", def: "to try as hard as you can", example: "It doesn't matter if you win — just do your best.", zh: "盡力而為" },
    { front: "do the housework", pos: "collocation", def: "to clean and tidy the home", example: "We share the cooking, but I usually do the housework.", zh: "做家事" },
    { front: "do harm", pos: "collocation", def: "to damage or hurt someone or something", example: "Eating one piece of cake won't do you any harm.", zh: "造成傷害" },
    { front: "draw a conclusion", pos: "collocation", def: "to decide something after considering the facts", example: "It is too early to draw any conclusions from these results.", zh: "得出結論" },
    { front: "fully booked", pos: "collocation", def: "with no rooms, seats or places left", example: "The restaurant is fully booked this Saturday, I'm afraid.", zh: "訂滿的" },
    { front: "get in touch", pos: "collocation", def: "to contact someone by phone, email or letter", example: "Please get in touch with us if you have any questions.", zh: "取得聯繫" },
    { front: "have a go", pos: "collocation", def: "to try to do something, often for the first time", example: "I had never surfed before, but I decided to have a go.", zh: "試一試" },
    { front: "heavy traffic", pos: "collocation", def: "a large number of vehicles on the road", example: "We were an hour late because of heavy traffic on the ring road.", zh: "交通擁擠" },
    { front: "heavy rain", pos: "collocation", def: "rain that falls hard and in large amounts", example: "The festival was cancelled because of heavy rain.", zh: "大雨" },
    { front: "heavy smoker", pos: "collocation", def: "a person who smokes a lot of cigarettes", example: "He used to be a heavy smoker, but he quit five years ago.", zh: "老菸槍" },
    { front: "highly recommended", pos: "collocation", def: "praised by many people and worth trying", example: "This little seafood place comes highly recommended by locals.", zh: "強力推薦的" },
    { front: "keep a promise", pos: "collocation", def: "to do what you said you would do", example: "She kept her promise and visited her grandmother every Sunday.", zh: "遵守承諾" },
    { front: "keep a secret", pos: "collocation", def: "to not tell other people about something private", example: "Can you keep a secret? We are planning a surprise party for Dan.", zh: "保守祕密" },
    { front: "lose your temper", pos: "collocation", def: "to suddenly become very angry", example: "He lost his temper when the referee gave a penalty against his team.", zh: "發脾氣" },
    { front: "lose track of", pos: "collocation", def: "to no longer know what is happening or how much time has passed", example: "We were chatting so much that I lost track of time.", zh: "失去掌握、忘了" },
    { front: "make a decision", pos: "collocation", def: "to choose what to do after thinking about it", example: "We need to make a decision about the venue by Friday.", zh: "做決定" },
    { front: "make an appointment", pos: "collocation", def: "to arrange a time to see someone, such as a doctor", example: "I made an appointment to see the dentist next Tuesday.", zh: "預約" },
    { front: "make an effort", pos: "collocation", def: "to try hard to do something", example: "He made a real effort to be friendly to the new students.", zh: "努力" },
    { front: "make a fortune", pos: "collocation", def: "to earn a very large amount of money", example: "They made a fortune selling houses during the property boom.", zh: "發大財" },
    { front: "make progress", pos: "collocation", def: "to improve or move forward in what you are doing", example: "She has made great progress with her Spanish this term.", zh: "取得進展" },
    { front: "meet a deadline", pos: "collocation", def: "to finish something by the required time", example: "We worked overnight to meet the deadline for the report.", zh: "趕上期限" },
    { front: "miss the point", pos: "collocation", def: "to fail to understand the main idea of something", example: "You are missing the point — it is not about money, it is about trust.", zh: "沒抓到重點" },
    { front: "pay attention", pos: "collocation", def: "to watch or listen carefully", example: "Please pay attention to the safety instructions before we start.", zh: "專心、注意" },
    { front: "pay a compliment", pos: "collocation", def: "to say something nice about someone", example: "He paid her a compliment on her excellent presentation.", zh: "讚美" },
    { front: "place an order", pos: "collocation", def: "to formally ask for goods to be supplied", example: "We placed an order for two hundred chairs last week.", zh: "下訂單" },
    { front: "raise money", pos: "collocation", def: "to collect money for a particular purpose", example: "The school held a concert to raise money for new library books.", zh: "募款" },
    { front: "run a business", pos: "collocation", def: "to own and manage a company", example: "Her parents run a small business selling handmade furniture.", zh: "經營事業" },
    { front: "set an example", pos: "collocation", def: "to behave in a way that others should copy", example: "Senior players should set an example for the younger ones.", zh: "樹立榜樣" },
    { front: "strong accent", pos: "collocation", def: "a very noticeable way of pronouncing words from a region or country", example: "He speaks English fluently but with a strong French accent.", zh: "濃重的口音" },
    { front: "take a break", pos: "collocation", def: "to stop working or studying for a short rest", example: "Let's take a break and continue the meeting after coffee.", zh: "休息一下" },
    { front: "take a risk", pos: "collocation", def: "to do something even though something bad might happen", example: "Starting your own company means taking a big risk.", zh: "冒險" },
    { front: "take advantage of", pos: "collocation", def: "to use an opportunity, or to treat someone unfairly for your own benefit", example: "We took advantage of the good weather and went hiking.", zh: "利用、佔便宜" },
    { front: "take part in", pos: "collocation", def: "to be involved in an activity with other people", example: "Thousands of runners take part in the city marathon every year.", zh: "參加" },
    { front: "take place", pos: "collocation", def: "to happen, especially an organised event", example: "The wedding will take place in a small church by the lake.", zh: "舉行、發生" },
    { front: "tell the difference", pos: "collocation", def: "to notice how two things are not the same", example: "The twins look so alike that I can't tell the difference between them.", zh: "分辨差異" },
    { front: "waste of time", pos: "collocation", def: "an activity that brings no useful result", example: "Arguing with him is a complete waste of time — he never listens.", zh: "浪費時間" },
    { front: "win a prize", pos: "collocation", def: "to receive an award for coming first or doing well", example: "Her short story won a prize in a national competition.", zh: "獲獎" },
    { front: "bitterly cold", pos: "collocation", def: "extremely and unpleasantly cold", example: "It was bitterly cold, so we stayed indoors by the fire.", zh: "嚴寒刺骨" },
    { front: "deeply disappointed", pos: "collocation", def: "extremely disappointed", example: "Fans were deeply disappointed by the team's performance in the final.", zh: "深感失望" },
    /* ---------- Idioms ---------- */
    { front: "a piece of cake", pos: "idiom", def: "something very easy to do", example: "Don't worry about the driving test — it's a piece of cake.", zh: "輕而易舉的事" },
    { front: "a blessing in disguise", pos: "idiom", def: "something that seems bad at first but has a good result", example: "Losing that job was a blessing in disguise — it pushed me to study again.", zh: "因禍得福" },
    { front: "all of a sudden", pos: "idiom", def: "quickly and unexpectedly", example: "All of a sudden, the lights went out and the music stopped.", zh: "突然間" },
    { front: "as a rule", pos: "idiom", def: "usually; in most cases", example: "As a rule, I don't drink coffee after six in the evening.", zh: "通常、照慣例" },
    { front: "at short notice", pos: "idiom", def: "with very little warning or time to prepare", example: "Thanks for coming to help at such short notice.", zh: "臨時通知、倉促" },
    { front: "at the end of the day", pos: "idiom", def: "used to say what is most important after everything is considered", example: "At the end of the day, what matters is that everyone is safe.", zh: "說到底、歸根結柢" },
    { front: "behind the times", pos: "idiom", def: "old-fashioned; not modern", example: "Our office is a bit behind the times — we still use fax machines.", zh: "落伍的" },
    { front: "better late than never", pos: "idiom", def: "it is better to do something late than not at all", example: "He finally apologised — better late than never, I suppose.", zh: "遲做總比不做好" },
    { front: "break the ice", pos: "idiom", def: "to make people feel relaxed when they first meet", example: "The teacher played a quick game to break the ice on the first day.", zh: "打破僵局" },
    { front: "by heart", pos: "idiom", def: "from memory, exactly", example: "She knows all the words of the song by heart.", zh: "熟記、背下來" },
    { front: "change your mind", pos: "idiom", def: "to change your decision or opinion", example: "He was going to sell the house, but he changed his mind at the last minute.", zh: "改變主意" },
    { front: "cost an arm and a leg", pos: "idiom", def: "to be extremely expensive", example: "That designer handbag cost her an arm and a leg.", zh: "貴得要命" },
    { front: "down to earth", pos: "idiom", def: "practical, sensible and easy to talk to", example: "Despite her fame, the actress is surprisingly down to earth.", zh: "務實的、平易近人的" },
    { front: "easier said than done", pos: "idiom", def: "much harder to do than to talk about", example: "Saving half your salary sounds great, but it's easier said than done.", zh: "說時容易做時難" },
    { front: "feel at home", pos: "idiom", def: "to feel comfortable and relaxed in a place", example: "The hosts were so friendly that we felt at home straight away.", zh: "感到自在" },
    { front: "food for thought", pos: "idiom", def: "something that makes you think carefully", example: "Her talk on plastic waste gave us plenty of food for thought.", zh: "值得深思的事" },
    { front: "get cold feet", pos: "idiom", def: "to suddenly become too nervous to do something planned", example: "He got cold feet the night before the big move and almost cancelled.", zh: "臨陣退縮" },
    { front: "get the hang of", pos: "idiom", def: "to learn how to do something after practising", example: "Skateboarding is tricky at first, but you soon get the hang of it.", zh: "掌握訣竅" },
    { front: "give someone a hand", pos: "idiom", def: "to help someone", example: "Could you give me a hand with these heavy boxes?", zh: "幫忙" },
    { front: "have second thoughts", pos: "idiom", def: "to start doubting a decision you have made", example: "She accepted the offer but is now having second thoughts.", zh: "重新考慮、猶豫" },
    { front: "hit the nail on the head", pos: "idiom", def: "to describe a situation or problem exactly right", example: "You hit the nail on the head — the real issue is poor communication.", zh: "一針見血" },
    { front: "in hot water", pos: "idiom", def: "in trouble", example: "He found himself in hot water after missing three meetings in a row.", zh: "陷入麻煩" },
    { front: "in the long run", pos: "idiom", def: "over a long period of time in the future", example: "Buying good shoes costs more now but saves money in the long run.", zh: "長遠來看" },
    { front: "in a nutshell", pos: "idiom", def: "described in as few words as possible", example: "In a nutshell, the project failed because we ran out of money.", zh: "簡而言之" },
    { front: "keep an eye on", pos: "idiom", def: "to watch someone or something carefully", example: "Could you keep an eye on my bag while I buy the tickets?", zh: "留意、照看" },
    { front: "kill two birds with one stone", pos: "idiom", def: "to achieve two things with one action", example: "Cycling to work kills two birds with one stone — I save money and keep fit.", zh: "一石二鳥" },
    { front: "let the cat out of the bag", pos: "idiom", def: "to tell a secret by mistake", example: "Dad let the cat out of the bag about the surprise trip to Paris.", zh: "洩露祕密" },
    { front: "make ends meet", pos: "idiom", def: "to have just enough money to pay for what you need", example: "With rent so high, many students struggle to make ends meet.", zh: "收支平衡、勉強餬口" },
    { front: "no wonder", pos: "idiom", def: "it is not surprising", example: "You stayed up until three? No wonder you are so tired today.", zh: "難怪" },
    { front: "off the beaten track", pos: "idiom", def: "far from popular places that most tourists visit", example: "We found a lovely little beach well off the beaten track.", zh: "人跡罕至的" },
    { front: "on purpose", pos: "idiom", def: "deliberately; not by accident", example: "I'm sure he didn't break the vase on purpose.", zh: "故意地" },
    { front: "on the same page", pos: "idiom", def: "agreeing about something or understanding it the same way", example: "Let's have a quick meeting to make sure everyone is on the same page.", zh: "有共識" },
    { front: "once in a blue moon", pos: "idiom", def: "very rarely", example: "We live far apart now, so we only meet once in a blue moon.", zh: "千載難逢、極少" },
    { front: "out of the blue", pos: "idiom", def: "completely unexpectedly", example: "After ten years of silence, she phoned me out of the blue.", zh: "突如其來" },
    { front: "over the moon", pos: "idiom", def: "extremely happy", example: "They were over the moon when they heard they had won the trip.", zh: "欣喜若狂" },
    { front: "pull someone's leg", pos: "idiom", def: "to joke with someone by telling them something untrue", example: "Relax, I'm only pulling your leg — the exam isn't really tomorrow.", zh: "開玩笑、捉弄" },
    { front: "see eye to eye", pos: "idiom", def: "to agree with someone", example: "My boss and I don't always see eye to eye on how to run projects.", zh: "意見一致" },
    { front: "sooner or later", pos: "idiom", def: "at some time in the future, even if you do not know when", example: "Sooner or later, you will have to tell him the truth.", zh: "遲早" },
    { front: "spill the beans", pos: "idiom", def: "to reveal secret information", example: "Come on, spill the beans — what did he say about me?", zh: "洩密、和盤托出" },
    { front: "take it easy", pos: "idiom", def: "to relax and not do too much", example: "The doctor told him to take it easy for a few days after the operation.", zh: "放輕鬆" },
    { front: "the last straw", pos: "idiom", def: "the final problem that makes a situation impossible to accept", example: "When the train was cancelled again, it was the last straw — I bought a car.", zh: "最後一根稻草" },
    { front: "the tip of the iceberg", pos: "idiom", def: "a small, visible part of a much bigger problem", example: "These complaints are just the tip of the iceberg — many customers never write in.", zh: "冰山一角" },
    { front: "under the weather", pos: "idiom", def: "feeling slightly ill", example: "I'm feeling a bit under the weather, so I'll stay home tonight.", zh: "身體不舒服" },
    { front: "up to date", pos: "idiom", def: "modern, or including the latest information", example: "Make sure your contact details are up to date before the trip.", zh: "最新的" }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
