/* FCE Prep extra bank: vocab wave 4 */
(function () {
  var BANK = [
    { front: "affection", pos: "n.", def: "a gentle feeling of love or fondness for someone", example: "She shows great affection for her grandmother.", zh: "喜愛；感情" },
    { front: "affectionate", pos: "adj.", def: "showing love or fondness openly", example: "He gave his daughter an affectionate hug.", zh: "深情的；充滿愛的" },
    { front: "devoted", pos: "adj.", def: "loving and loyal to someone or something", example: "They are a devoted couple who do everything together.", zh: "忠誠的；摯愛的" },
    { front: "furious", pos: "adj.", def: "extremely angry", example: "Dad was furious when I broke the car window.", zh: "狂怒的" },
    { front: "terrified", pos: "adj.", def: "extremely frightened", example: "She was terrified of speaking in front of the class.", zh: "非常害怕的" },
    { front: "astonished", pos: "adj.", def: "very surprised", example: "I was astonished to hear that they had got married.", zh: "驚訝的" },
    { front: "overwhelmed", pos: "adj.", def: "having such strong emotions that you do not know how to react", example: "She felt overwhelmed by all the kind messages.", zh: "不知所措的；情緒滿溢的" },
    { front: "heartbroken", pos: "adj.", def: "extremely sad, usually because of love", example: "He was heartbroken when his girlfriend left him.", zh: "心碎的" },
    { front: "homesick", pos: "adj.", def: "sad because you are away from home", example: "During her first month abroad she felt terribly homesick.", zh: "想家的" },
    { front: "desperate", pos: "adj.", def: "feeling that you will do anything to change a bad situation", example: "He was desperate to find a job before the summer.", zh: "絕望的；不顧一切的" },
    { front: "devastated", pos: "adj.", def: "extremely shocked and upset", example: "The whole family was devastated by the news.", zh: "極度震驚悲痛的" },
    { front: "offended", pos: "adj.", def: "upset because of something rude someone said or did", example: "She felt offended by his comments about her cooking.", zh: "被冒犯的" },
    { front: "humiliated", pos: "adj.", def: "feeling ashamed because you have lost respect in front of others", example: "He felt humiliated when the teacher laughed at his answer.", zh: "感到羞辱的" },
    { front: "resentful", pos: "adj.", def: "feeling angry because you think you have been treated unfairly", example: "She grew resentful of doing all the housework alone.", zh: "怨恨的；不滿的" },
    { front: "insecure", pos: "adj.", def: "not confident about yourself", example: "Teenagers often feel insecure about their appearance.", zh: "缺乏自信的；沒安全感的" },
    { front: "vulnerable", pos: "adj.", def: "easily hurt physically or emotionally", example: "After the divorce she felt lonely and vulnerable.", zh: "脆弱的；易受傷害的" },
    { front: "supportive", pos: "adj.", def: "giving help and encouragement", example: "My parents were very supportive when I changed careers.", zh: "支持的" },
    { front: "trustworthy", pos: "adj.", def: "able to be trusted", example: "Choose a trustworthy friend to keep your secret.", zh: "值得信賴的" },
    { front: "self-centred", pos: "adj.", def: "only interested in yourself", example: "He is too self-centred to notice other people's problems.", zh: "自我中心的" },
    { front: "possessive", pos: "adj.", def: "wanting someone to give attention only to you", example: "Her boyfriend gets possessive when she goes out with friends.", zh: "佔有慾強的" },
    { front: "faithful", pos: "adj.", def: "loyal and not changing your feelings for someone", example: "He remained faithful to his wife all his life.", zh: "忠實的" },
    { front: "grief", pos: "n.", def: "great sadness, especially after someone dies", example: "It took years for her to get over her grief.", zh: "悲痛；哀傷" },
    { front: "sympathy", pos: "n.", def: "the feeling of understanding someone else's suffering", example: "We sent a card to express our sympathy.", zh: "同情" },
    { front: "empathy", pos: "n.", def: "the ability to understand another person's feelings", example: "A good nurse needs empathy as well as skill.", zh: "同理心" },
    { front: "compassion", pos: "n.", def: "a strong feeling of sympathy and a wish to help", example: "She treated the refugees with great compassion.", zh: "憐憫；同情心" },
    { front: "admiration", pos: "n.", def: "a feeling of respect and approval", example: "I have great admiration for people who learn languages as adults.", zh: "欽佩；讚賞" },
    { front: "envy", pos: "n.", def: "the feeling of wanting what someone else has", example: "Her new car filled the neighbours with envy.", zh: "羨慕；嫉妒" },
    { front: "temper", pos: "n.", def: "a tendency to become angry quickly", example: "You need to control your temper during meetings.", zh: "脾氣" },
    { front: "betray", pos: "v.", def: "to hurt someone who trusts you by not being loyal", example: "He betrayed his best friend by telling everyone the secret.", zh: "背叛" },
    { front: "forgive", pos: "v.", def: "to stop being angry with someone who has hurt you", example: "She finally forgave her brother for lying to her.", zh: "原諒" },
    { front: "reconcile", pos: "v.", def: "to become friendly again after an argument", example: "The sisters reconciled after years of not speaking.", zh: "和解" },
    { front: "flirt", pos: "v.", def: "to behave as if you are attracted to someone, but not seriously", example: "He spent the whole party flirting with the waitress.", zh: "調情" },
    { front: "propose", pos: "v.", def: "to ask someone to marry you", example: "He proposed to her on the beach at sunset.", zh: "求婚；提議" },
    { front: "engagement", pos: "n.", def: "an agreement to marry someone", example: "They announced their engagement at the family dinner.", zh: "訂婚" },
    { front: "companionship", pos: "n.", def: "the pleasant feeling of being with someone", example: "Many elderly people keep pets for companionship.", zh: "陪伴" },
    { front: "bond", pos: "n.", def: "a close connection between people", example: "There is a strong bond between the twins.", zh: "情感連結；羈絆" },
    { front: "comfort", pos: "v.", def: "to make someone feel less sad or worried", example: "She comforted the crying child with a hug.", zh: "安慰" },
    { front: "reassure", pos: "v.", def: "to make someone feel less worried", example: "The doctor reassured me that the test results were normal.", zh: "使安心" },
    { front: "confide", pos: "v.", def: "to tell someone a secret because you trust them", example: "She confided in her sister about her money problems.", zh: "吐露（祕密）" },
    { front: "adore", pos: "v.", def: "to love someone or something very much", example: "The children absolutely adore their new puppy.", zh: "熱愛；愛慕" },
    { front: "despise", pos: "v.", def: "to dislike someone strongly and have no respect for them", example: "She despises people who lie to get ahead.", zh: "鄙視" },
    { front: "resent", pos: "v.", def: "to feel angry about something you think is unfair", example: "He resents having to work every weekend.", zh: "怨恨；不滿" },
    { front: "irritable", pos: "adj.", def: "easily annoyed", example: "Lack of sleep makes me irritable in the morning.", zh: "易怒的" },
    { front: "gratitude", pos: "n.", def: "the feeling of being thankful", example: "She expressed her gratitude with a handwritten note.", zh: "感激" },
    { front: "loyalty", pos: "n.", def: "the quality of always supporting someone", example: "His loyalty to his old friends never changed.", zh: "忠誠" },
    { front: "tension", pos: "n.", def: "a feeling of nervousness or unfriendliness between people", example: "You could feel the tension between the two managers.", zh: "緊張關係" },
    { front: "quarrel", pos: "n.", def: "an angry argument", example: "They had a quarrel about money and did not speak for days.", zh: "爭吵" },
    { front: "sulk", pos: "v.", def: "to be silent and bad-tempered because you are annoyed", example: "He sulked for hours after losing the game.", zh: "生悶氣" },
    { front: "grumpy", pos: "adj.", def: "easily annoyed and complaining", example: "Grandad gets grumpy when he misses his afternoon nap.", zh: "脾氣壞的" },
    { front: "tearful", pos: "adj.", def: "crying or about to cry", example: "She gave a tearful goodbye at the airport.", zh: "含淚的" },
    { front: "drift apart", pos: "phr. v.", def: "to gradually become less close to someone", example: "After university we slowly drifted apart.", zh: "（感情）逐漸疏遠" },
    { front: "hit it off", pos: "phr. v.", def: "to like someone immediately when you meet them", example: "We hit it off at the party and have been friends ever since.", zh: "一見如故" },
    { front: "open up", pos: "phr. v.", def: "to start talking about your feelings", example: "It took months before he opened up about his childhood.", zh: "敞開心扉" },
    { front: "bottle up", pos: "phr. v.", def: "to hide your feelings instead of expressing them", example: "Don't bottle up your anger; talk to someone about it.", zh: "壓抑（情緒）" },
    { front: "stick up for", pos: "phr. v.", def: "to defend someone who is being criticised", example: "She always sticks up for her little brother at school.", zh: "為…挺身辯護" },
    { front: "stand by", pos: "phr. v.", def: "to continue to support someone in a difficult time", example: "His wife stood by him throughout the scandal.", zh: "支持；不離不棄" },
    { front: "cheer on", pos: "phr. v.", def: "to shout encouragement to someone", example: "Thousands of fans cheered on the runners.", zh: "為…加油" },
    { front: "look down on", pos: "phr. v.", def: "to think you are better than someone", example: "She looks down on people who didn't go to university.", zh: "看不起" },
    { front: "warm to", pos: "phr. v.", def: "to begin to like someone or something", example: "I didn't like him at first, but I soon warmed to him.", zh: "開始喜歡" },
    { front: "take to", pos: "phr. v.", def: "to start liking someone or something quickly", example: "The kids took to their new teacher immediately.", zh: "很快喜歡上" },
    { front: "get through to", pos: "phr. v.", def: "to make someone understand what you mean", example: "I just can't get through to my teenage son these days.", zh: "使理解；溝通成功" },
    { front: "talk down to", pos: "phr. v.", def: "to speak to someone as if they were less intelligent", example: "Students hate teachers who talk down to them.", zh: "以居高臨下的口吻說話" },
    { front: "suck up to", pos: "phr. v.", def: "to be too nice to someone to get an advantage", example: "He's always sucking up to the boss before promotions.", zh: "拍馬屁" },
    { front: "lash out", pos: "phr. v.", def: "to suddenly attack someone with words or actions", example: "When he's stressed, he lashes out at everyone around him.", zh: "猛烈抨擊；發火" },
    { front: "storm off", pos: "phr. v.", def: "to leave angrily", example: "She stormed off in the middle of the argument.", zh: "憤然離開" },
    { front: "go out with", pos: "phr. v.", def: "to have a romantic relationship with someone", example: "She's been going out with Mark for two years.", zh: "與…交往" },
    { front: "wind someone up", pos: "phr. v.", def: "to deliberately annoy or tease someone", example: "Stop winding your sister up about her new haircut.", zh: "故意惹惱；捉弄" },
    { front: "grow apart", pos: "phr. v.", def: "to slowly stop having a close relationship", example: "We were best friends at school, but we grew apart over the years.", zh: "漸行漸遠" },
    { front: "make it up to", pos: "phr. v.", def: "to do something good for someone you have treated badly", example: "I forgot her birthday, so I'll make it up to her this weekend.", zh: "補償" },
    { front: "fall back on", pos: "phr. v.", def: "to use someone or something for help when other things have failed", example: "If the business fails, I can fall back on my teaching degree.", zh: "依靠；求助於" },
    { front: "pick on", pos: "phr. v.", def: "to repeatedly treat someone unfairly or unkindly", example: "The older boys used to pick on him at school.", zh: "欺負；找碴" },
    { front: "come between", pos: "phr. v.", def: "to harm the relationship between two people", example: "Don't let money come between you and your brother.", zh: "破壞（兩人）關係" },
    { front: "tie the knot", pos: "idiom", def: "to get married", example: "After ten years together, they finally tied the knot.", zh: "結婚" },
    { front: "have a soft spot for", pos: "idiom", def: "to feel special affection for someone or something", example: "Grandma has always had a soft spot for her youngest grandson.", zh: "特別喜愛" },
    { front: "wear your heart on your sleeve", pos: "idiom", def: "to show your emotions openly", example: "You always know how Tom feels; he wears his heart on his sleeve.", zh: "情感外露" },
    { front: "get on someone's nerves", pos: "idiom", def: "to annoy someone", example: "His constant complaining really gets on my nerves.", zh: "使人心煩" },
    { front: "fall head over heels", pos: "idiom", def: "to fall deeply in love with someone", example: "He fell head over heels for a girl he met on holiday.", zh: "深深愛上" },
    { front: "blood is thicker than water", pos: "idiom", def: "family relationships are stronger than any others", example: "He'll help his cousin first — blood is thicker than water.", zh: "血濃於水" },
    { front: "a shoulder to cry on", pos: "idiom", def: "someone who listens to your problems and gives sympathy", example: "Whenever things go wrong, she needs a shoulder to cry on.", zh: "可傾訴的對象" },
    { front: "break someone's heart", pos: "idiom", def: "to make someone extremely sad, especially in love", example: "It broke her heart when he moved abroad without her.", zh: "使某人心碎" },
    { front: "stay in touch", pos: "collocation", def: "to continue communicating with someone", example: "We promised to stay in touch after graduation.", zh: "保持聯絡" },
    { front: "have mixed feelings", pos: "collocation", def: "to feel both positive and negative about something", example: "I have mixed feelings about moving to a new city.", zh: "心情複雜" },
    { front: "in a good mood", pos: "collocation", def: "feeling happy and cheerful", example: "The boss is in a good mood today, so ask him now.", zh: "心情好" },
    { front: "mood swings", pos: "collocation", def: "sudden changes in how someone feels", example: "Teenagers often suffer from mood swings.", zh: "情緒起伏" },
    { front: "love at first sight", pos: "idiom", def: "falling in love the first time you see someone", example: "For my parents it was love at first sight.", zh: "一見鍾情" },
    { front: "take someone for granted", pos: "idiom", def: "to not show that you value someone", example: "He never thanks his wife; he takes her for granted.", zh: "視為理所當然" },
    { front: "get off on the wrong foot", pos: "idiom", def: "to start a relationship badly", example: "We got off on the wrong foot, but now we're good friends.", zh: "一開始就不順利" },
    { front: "bury the hatchet", pos: "idiom", def: "to stop an argument and become friends again", example: "It's time you two buried the hatchet and moved on.", zh: "言歸於好" },
    { front: "give someone the cold shoulder", pos: "idiom", def: "to deliberately ignore someone", example: "She's been giving me the cold shoulder since our argument.", zh: "冷落某人" },
    { front: "drive someone up the wall", pos: "idiom", def: "to annoy someone very much", example: "His constant whistling drives me up the wall.", zh: "使人抓狂" },
    { front: "entrepreneur", pos: "n.", def: "someone who starts their own business", example: "The young entrepreneur opened three cafés in two years.", zh: "創業家" },
    { front: "freelance", pos: "adj.", def: "working for different companies rather than one employer", example: "She does freelance design work from home.", zh: "自由接案的" },
    { front: "redundant", pos: "adj.", def: "having lost your job because it is no longer needed", example: "Two hundred workers were made redundant when the factory closed.", zh: "被裁員的" },
    { front: "redundancy", pos: "n.", def: "the situation of losing your job because it is no longer needed", example: "The company announced five hundred redundancies.", zh: "裁員" },
    { front: "vacancy", pos: "n.", def: "a job that is available", example: "There's a vacancy for a sales assistant at the store.", zh: "職缺" },
    { front: "applicant", pos: "n.", def: "a person who formally asks for a job or place", example: "Over fifty applicants applied for the position.", zh: "應徵者" },
    { front: "bonus", pos: "n.", def: "extra money added to your pay, often as a reward", example: "Everyone received a Christmas bonus this year.", zh: "獎金" },
    { front: "commission", pos: "n.", def: "money paid to someone for each sale they make", example: "Sales staff earn ten percent commission on every car.", zh: "佣金" },
    { front: "invoice", pos: "n.", def: "a document listing goods or services and their cost", example: "Please pay the invoice within thirty days.", zh: "發票；請款單" },
    { front: "revenue", pos: "n.", def: "the money a company receives from its business", example: "Online sales now provide most of the company's revenue.", zh: "營收" },
    { front: "turnover", pos: "n.", def: "the total amount of money a business earns in a period", example: "The shop has an annual turnover of two million pounds.", zh: "營業額" },
    { front: "bankrupt", pos: "adj.", def: "unable to pay your debts", example: "The airline went bankrupt during the crisis.", zh: "破產的" },
    { front: "shareholder", pos: "n.", def: "a person who owns shares in a company", example: "Shareholders will vote on the merger next month.", zh: "股東" },
    { front: "investor", pos: "n.", def: "a person who puts money into something to make a profit", example: "The startup is looking for investors to fund its growth.", zh: "投資人" },
    { front: "corporation", pos: "n.", def: "a large company or group of companies", example: "He left a huge corporation to join a small startup.", zh: "大公司；企業" },
    { front: "headquarters", pos: "n.", def: "the main office of an organisation", example: "The company's headquarters are in Singapore.", zh: "總部" },
    { front: "supervisor", pos: "n.", def: "a person who watches over workers and their work", example: "Report any problems to your supervisor immediately.", zh: "主管；監督者" },
    { front: "apprentice", pos: "n.", def: "a person learning a skill by working for an expert", example: "He started as an apprentice to a local carpenter.", zh: "學徒" },
    { front: "trainee", pos: "n.", def: "a person being trained for a job", example: "The bank takes on twenty trainees every year.", zh: "實習生；受訓者" },
    { front: "pension", pos: "n.", def: "money paid regularly to someone who has retired", example: "She lives comfortably on her pension.", zh: "退休金" },
    { front: "workforce", pos: "n.", def: "all the people who work in a company or country", example: "Women make up half of the country's workforce.", zh: "勞動力" },
    { front: "workaholic", pos: "n.", def: "a person who works too much", example: "He's a workaholic who answers emails at midnight.", zh: "工作狂" },
    { front: "resignation", pos: "n.", def: "the act of officially leaving your job", example: "She handed in her resignation after ten years with the firm.", zh: "辭職" },
    { front: "dismissal", pos: "n.", def: "the act of removing someone from their job", example: "He claimed his dismissal was unfair and went to court.", zh: "解僱" },
    { front: "recruitment", pos: "n.", def: "the process of finding new people to work for a company", example: "The recruitment process took nearly three months.", zh: "招募" },
    { front: "profitable", pos: "adj.", def: "making money", example: "The café became profitable in its second year.", zh: "有利潤的" },
    { front: "instalment", pos: "n.", def: "one of several regular payments for something", example: "You can pay for the sofa in twelve monthly instalments.", zh: "分期付款的一期" },
    { front: "deposit", pos: "n.", def: "money you pay first as part of a larger payment", example: "We put down a deposit on the flat yesterday.", zh: "訂金；押金" },
    { front: "inflation", pos: "n.", def: "a general rise in prices", example: "Inflation has made everyday shopping much more expensive.", zh: "通貨膨脹" },
    { front: "recession", pos: "n.", def: "a period when a country's economy is doing badly", example: "Many shops closed down during the recession.", zh: "經濟衰退" },
    { front: "payslip", pos: "n.", def: "a document showing how much you have been paid", example: "Check your payslip to see how much tax you paid.", zh: "薪資單" },
    { front: "perk", pos: "n.", def: "an extra benefit you get from your job", example: "Free lunches are one of the perks of working here.", zh: "（工作）額外福利" },
    { front: "merger", pos: "n.", def: "the joining of two companies into one", example: "The merger created the largest bank in the region.", zh: "（公司）合併" },
    { front: "takeover", pos: "n.", def: "the act of one company getting control of another", example: "The takeover of the airline shocked the industry.", zh: "收購" },
    { front: "retail", pos: "n.", def: "the business of selling goods directly to customers", example: "She has worked in retail since leaving school.", zh: "零售業" },
    { front: "consumer", pos: "n.", def: "a person who buys goods or services", example: "Consumers are demanding more eco-friendly products.", zh: "消費者" },
    { front: "supplier", pos: "n.", def: "a company that provides goods to other businesses", example: "We changed suppliers to cut our costs.", zh: "供應商" },
    { front: "warehouse", pos: "n.", def: "a large building where goods are stored", example: "The orders are shipped from a warehouse outside the city.", zh: "倉庫" },
    { front: "overdraft", pos: "n.", def: "an arrangement to spend more money than you have in your bank account", example: "I went into my overdraft before payday again.", zh: "透支額度" },
    { front: "stingy", pos: "adj.", def: "not willing to spend money", example: "He's too stingy to buy anyone a birthday present.", zh: "小氣的" },
    { front: "well-off", pos: "adj.", def: "having plenty of money", example: "Her family is quite well-off and owns two houses.", zh: "富裕的" },
    { front: "broke", pos: "adj.", def: "having no money", example: "I can't come out tonight — I'm completely broke.", zh: "身無分文的" },
    { front: "priceless", pos: "adj.", def: "so valuable that no price can be given", example: "The museum holds a priceless collection of paintings.", zh: "無價的" },
    { front: "worthwhile", pos: "adj.", def: "worth the time, money or effort spent", example: "Volunteering was a really worthwhile experience.", zh: "值得的" },
    { front: "retirement", pos: "n.", def: "the period of life after you stop working", example: "They moved to the coast after retirement.", zh: "退休（生活）" },
    { front: "expertise", pos: "n.", def: "special skill or knowledge", example: "We need someone with expertise in marketing.", zh: "專業知識" },
    { front: "productivity", pos: "n.", def: "the rate at which work is done", example: "Working from home has improved my productivity.", zh: "生產力" },
    { front: "incentive", pos: "n.", def: "something that encourages you to do something", example: "The company offers cash incentives for good ideas.", zh: "激勵；誘因" },
    { front: "take out", pos: "phr. v.", def: "to arrange to get a loan, insurance or similar from a company", example: "They took out a loan to start the business.", zh: "申辦（貸款、保險）" },
    { front: "branch out", pos: "phr. v.", def: "to start doing something new in addition to what you do", example: "The bookshop has branched out into selling coffee.", zh: "拓展（業務）" },
    { front: "step down", pos: "phr. v.", def: "to leave an important job or position", example: "The CEO stepped down after the scandal.", zh: "辭職；下台" },
    { front: "buy out", pos: "phr. v.", def: "to buy someone's share of a business", example: "She bought out her partner and now owns the whole café.", zh: "買下（股份）" },
    { front: "sell off", pos: "phr. v.", def: "to sell things quickly and cheaply, often to get money", example: "The firm sold off its overseas offices to pay its debts.", zh: "拋售；變賣" },
    { front: "chip in", pos: "phr. v.", def: "to give some money when a group is paying for something", example: "We all chipped in to buy the boss a leaving present.", zh: "湊錢；出份子" },
    { front: "save up", pos: "phr. v.", def: "to keep money over time to buy something", example: "I'm saving up for a new laptop.", zh: "存錢" },
    { front: "fork out", pos: "phr. v.", def: "to pay money unwillingly", example: "We had to fork out two hundred pounds for repairs.", zh: "不情願地付錢" },
    { front: "shop around", pos: "phr. v.", def: "to compare prices in different shops before buying", example: "Shop around before choosing an insurance company.", zh: "貨比三家" },
    { front: "run up", pos: "phr. v.", def: "to allow a debt or bill to grow", example: "He ran up a huge phone bill while travelling.", zh: "積欠（帳單、債務）" },
    { front: "knock off", pos: "phr. v.", def: "to stop working at the end of the day", example: "We usually knock off at five on Fridays.", zh: "收工；下班" },
    { front: "bail out", pos: "phr. v.", def: "to help a person or company with money problems", example: "The government bailed out the failing banks.", zh: "紓困；救助" },
    { front: "cash in on", pos: "phr. v.", def: "to make money from an opportunity, often unfairly", example: "Shops cashed in on the heatwave by raising fan prices.", zh: "趁機牟利" },
    { front: "knuckle down", pos: "phr. v.", def: "to start working hard", example: "It's time to knuckle down and finish this report.", zh: "開始認真工作" },
    { front: "slack off", pos: "phr. v.", def: "to work less hard than you should", example: "He tends to slack off when the manager is away.", zh: "偷懶" },
    { front: "burn out", pos: "phr. v.", def: "to become exhausted from working too hard for too long", example: "If you keep working weekends, you'll burn out.", zh: "過勞；倦怠" },
    { front: "wind down", pos: "phr. v.", def: "to gradually reduce a business or activity before ending it", example: "They are winding down the factory before it closes next year.", zh: "逐步結束（業務）" },
    { front: "scrape by", pos: "phr. v.", def: "to manage to live with very little money", example: "As a student, I scraped by on part-time wages.", zh: "勉強度日" },
    { front: "live within your means", pos: "idiom", def: "to spend only the money you have", example: "If you live within your means, you will avoid debt.", zh: "量入為出" },
    { front: "go under", pos: "phr. v.", def: "to fail as a business", example: "Many small restaurants went under during the pandemic.", zh: "倒閉" },
    { front: "write off", pos: "phr. v.", def: "to accept that a debt will never be paid", example: "The bank wrote off millions in bad loans.", zh: "勾銷（債務）" },
    { front: "pay into", pos: "phr. v.", def: "to put money regularly into an account or fund", example: "I pay into a pension scheme every month.", zh: "定期存入" },
    { front: "clock in", pos: "phr. v.", def: "to record the time you arrive at work", example: "Staff must clock in by nine o'clock.", zh: "打卡上班" },
    { front: "set back", pos: "phr. v.", def: "to cost someone a lot of money", example: "The wedding set them back twenty thousand pounds.", zh: "花費（大筆錢）" },
    { front: "feel the pinch", pos: "idiom", def: "to have problems because you have less money than before", example: "Small businesses are feeling the pinch as costs rise.", zh: "感到手頭拮据" },
    { front: "in the red", pos: "idiom", def: "owing money to the bank", example: "My account is in the red until payday.", zh: "負債；透支" },
    { front: "cut your losses", pos: "idiom", def: "to stop doing something that is failing before you lose more", example: "The shop wasn't making money, so we cut our losses and closed it.", zh: "及時止損" },
    { front: "get down to business", pos: "idiom", def: "to start dealing with the important matter", example: "Let's skip the small talk and get down to business.", zh: "言歸正傳；開始辦正事" },
    { front: "time is money", pos: "idiom", def: "time is valuable, so do not waste it", example: "Stop chatting — time is money!", zh: "時間就是金錢" },
    { front: "money doesn't grow on trees", pos: "idiom", def: "money is limited and should not be wasted", example: "You can't have another new phone — money doesn't grow on trees.", zh: "錢不是從天上掉下來的" },
    { front: "strike a deal", pos: "collocation", def: "to reach an agreement, especially in business", example: "The two companies struck a deal after months of talks.", zh: "達成協議" },
    { front: "make a profit", pos: "collocation", def: "to earn more money than you spend", example: "The bakery made a small profit in its first year.", zh: "獲利" },
    { front: "pay rise", pos: "collocation", def: "an increase in your salary", example: "She asked her boss for a pay rise.", zh: "加薪" },
    { front: "job satisfaction", pos: "collocation", def: "the feeling of enjoying your work", example: "Nurses report high job satisfaction despite the long hours.", zh: "工作滿意度" },
    { front: "climb the career ladder", pos: "idiom", def: "to move to higher positions in your working life", example: "He's ambitious and keen to climb the career ladder quickly.", zh: "升遷；往上爬" },
    { front: "hand in your notice", pos: "collocation", def: "to officially tell your employer you are leaving", example: "She handed in her notice and booked a flight to Spain.", zh: "遞辭呈" },
    { front: "work around the clock", pos: "idiom", def: "to work all day and all night", example: "Engineers worked around the clock to fix the system.", zh: "日以繼夜地工作" },
    { front: "nine-to-five job", pos: "collocation", def: "a normal office job with regular hours", example: "He left his nine-to-five job to travel the world.", zh: "朝九晚五的工作" },
    { front: "break even", pos: "idiom", def: "to earn just enough money to cover your costs", example: "The restaurant should break even by the end of the year.", zh: "損益兩平" },
    { front: "bring home the bacon", pos: "idiom", def: "to earn the money that supports your family", example: "Both parents work to bring home the bacon.", zh: "養家糊口" },
    { front: "value for money", pos: "collocation", def: "worth the price paid", example: "The hotel was excellent value for money.", zh: "物有所值" },
    { front: "on a tight budget", pos: "collocation", def: "having only a small amount of money to spend", example: "We travelled around Europe on a tight budget.", zh: "預算有限" },
    { front: "stopover", pos: "n.", def: "a short stay somewhere between two parts of a journey", example: "We had a six-hour stopover in Dubai.", zh: "中途停留" },
    { front: "turbulence", pos: "n.", def: "sudden violent movement of air during a flight", example: "The plane hit turbulence over the mountains.", zh: "亂流" },
    { front: "aisle", pos: "n.", def: "the passage between rows of seats", example: "I'd prefer an aisle seat so I can stretch my legs.", zh: "走道" },
    { front: "terminal", pos: "n.", def: "a building at an airport where journeys begin and end", example: "International flights leave from Terminal Two.", zh: "航廈" },
    { front: "backpacker", pos: "n.", def: "a person who travels cheaply carrying a backpack", example: "The hostel was full of backpackers from all over the world.", zh: "背包客" },
    { front: "hitchhike", pos: "v.", def: "to travel by getting free rides in other people's cars", example: "They hitchhiked across the country with almost no money.", zh: "搭便車" },
    { front: "wander", pos: "v.", def: "to walk around slowly with no clear direction", example: "We spent the afternoon wandering around the old town.", zh: "漫步；閒逛" },
    { front: "trek", pos: "n.", def: "a long hard walk, especially in the mountains", example: "The trek to the base camp takes five days.", zh: "長途跋涉；健行" },
    { front: "monument", pos: "n.", def: "a structure built to remember a person or event", example: "The monument honours the soldiers who died in the war.", zh: "紀念碑" },
    { front: "heritage", pos: "n.", def: "the traditions and buildings passed down through history", example: "The old town is part of the country's cultural heritage.", zh: "文化遺產" },
    { front: "embassy", pos: "n.", def: "the office of a country's representatives abroad", example: "If you lose your passport, contact your embassy.", zh: "大使館" },
    { front: "hostel", pos: "n.", def: "a cheap place to stay, often with shared rooms", example: "We stayed in a youth hostel near the station.", zh: "青年旅館" },
    { front: "long-haul", pos: "adj.", def: "describing travel over very long distances", example: "Long-haul flights always leave me exhausted.", zh: "長途（飛行）的" },
    { front: "excursion", pos: "n.", def: "a short trip made for pleasure", example: "The hotel organises excursions to nearby islands.", zh: "短程旅遊" },
    { front: "overseas", pos: "adv.", def: "in or to a foreign country", example: "She spent a year working overseas.", zh: "在海外" },
    { front: "domestic", pos: "adj.", def: "within your own country, not international", example: "Domestic flights depart from the smaller terminal.", zh: "國內的" },
    { front: "cancellation", pos: "n.", def: "the act of deciding an arranged event will not happen", example: "Heavy snow caused the cancellation of dozens of flights.", zh: "取消" },
    { front: "reschedule", pos: "v.", def: "to change the time of a planned event", example: "Our flight was rescheduled for the next morning.", zh: "改期" },
    { front: "overbook", pos: "v.", def: "to sell more tickets or rooms than are available", example: "The airline overbooked the flight, so we were offered compensation.", zh: "超賣" },
    { front: "porter", pos: "n.", def: "a person whose job is carrying luggage", example: "A porter carried our bags up to the room.", zh: "行李員" },
    { front: "suite", pos: "n.", def: "a set of connected rooms in a hotel", example: "They booked the honeymoon suite for their anniversary.", zh: "套房" },
    { front: "self-catering", pos: "adj.", def: "describing accommodation where you cook your own meals", example: "We rented a self-catering apartment by the beach.", zh: "自炊式的" },
    { front: "seasick", pos: "adj.", def: "feeling ill because of the movement of a boat", example: "I got terribly seasick on the ferry crossing.", zh: "暈船的" },
    { front: "jet lag", pos: "n.", def: "tiredness caused by flying across time zones", example: "It took me three days to get over the jet lag.", zh: "時差" },
    { front: "compass", pos: "n.", def: "an instrument that shows direction", example: "Always carry a map and compass when hiking.", zh: "指南針" },
    { front: "navigate", pos: "v.", def: "to find the right direction to travel", example: "You drive and I'll navigate with the map.", zh: "導航；找路" },
    { front: "scenic", pos: "adj.", def: "having beautiful natural views", example: "We took the scenic route along the coast.", zh: "風景優美的" },
    { front: "idyllic", pos: "adj.", def: "extremely peaceful and beautiful", example: "They spent a week in an idyllic mountain village.", zh: "田園詩般的；恬靜優美的" },
    { front: "stunning", pos: "adj.", def: "extremely beautiful or impressive", example: "The view from the summit was absolutely stunning.", zh: "令人驚豔的" },
    { front: "secluded", pos: "adj.", def: "quiet and away from other people", example: "We found a secluded beach with no tourists at all.", zh: "僻靜的" },
    { front: "bustling", pos: "adj.", def: "full of busy activity", example: "The market was bustling with locals and visitors.", zh: "熙來攘往的" },
    { front: "hospitality", pos: "n.", def: "friendly and generous treatment of guests", example: "We were touched by the warm hospitality of our hosts.", zh: "熱情款待" },
    { front: "delicacy", pos: "n.", def: "a special food from a particular place", example: "Snails are considered a delicacy in France.", zh: "美味佳餚；特產" },
    { front: "custom", pos: "n.", def: "a traditional way of behaving in a place", example: "It's the custom here to remove your shoes indoors.", zh: "風俗習慣" },
    { front: "etiquette", pos: "n.", def: "the rules of polite behaviour", example: "Learn some local etiquette before you visit Japan.", zh: "禮儀" },
    { front: "phrasebook", pos: "n.", def: "a small book of useful expressions in a foreign language", example: "I ordered dinner with the help of a phrasebook.", zh: "常用語手冊" },
    { front: "campsite", pos: "n.", def: "a place where people stay in tents", example: "The campsite has showers and a small shop.", zh: "露營地" },
    { front: "caravan", pos: "n.", def: "a vehicle you can live in, pulled by a car", example: "They toured Scotland in a caravan last summer.", zh: "露營拖車" },
    { front: "sunburn", pos: "n.", def: "red painful skin caused by too much sun", example: "Wear sunscreen or you'll get sunburn on the boat.", zh: "曬傷" },
    { front: "harbour", pos: "n.", def: "an area of water where ships stop", example: "Fishing boats filled the little harbour.", zh: "港口" },
    { front: "spa", pos: "n.", def: "a place where people go for health and beauty treatment", example: "The hotel has a spa with a sauna and pool.", zh: "水療中心" },
    { front: "trail", pos: "n.", def: "a path through the countryside", example: "The hiking trail leads through the forest to a waterfall.", zh: "步道" },
    { front: "summit", pos: "n.", def: "the top of a mountain", example: "We reached the summit just before sunrise.", zh: "山頂；峰會" },
    { front: "altitude", pos: "n.", def: "height above sea level", example: "Some climbers feel sick at high altitude.", zh: "海拔" },
    { front: "nightlife", pos: "n.", def: "entertainment available at night in a place", example: "The city is famous for its lively nightlife.", zh: "夜生活" },
    { front: "vendor", pos: "n.", def: "a person who sells things, especially in the street", example: "We bought noodles from a street vendor.", zh: "小販" },
    { front: "underground", pos: "n.", def: "a railway system under a city", example: "The underground is the fastest way across London.", zh: "地鐵" },
    { front: "getaway", pos: "n.", def: "a short holiday", example: "We booked a weekend getaway in the mountains.", zh: "短假期" },
    { front: "unspoilt", pos: "adj.", def: "still beautiful and not changed by tourism", example: "The island remains unspoilt, with empty beaches.", zh: "未受破壞的" },
    { front: "off-peak", pos: "adj.", def: "at a less busy and usually cheaper time", example: "Off-peak train tickets cost half the price.", zh: "離峰的" },
    { front: "stop over", pos: "phr. v.", def: "to stay somewhere briefly during a long journey", example: "We stopped over in Bangkok on the way to Sydney.", zh: "中途停留" },
    { front: "touch down", pos: "phr. v.", def: "to land, used about planes", example: "The plane touched down ten minutes early.", zh: "降落" },
    { front: "get in", pos: "phr. v.", def: "to arrive, used about trains, planes or people", example: "What time does your flight get in?", zh: "抵達" },
    { front: "head off", pos: "phr. v.", def: "to start a journey or leave", example: "We headed off early to avoid the traffic.", zh: "出發" },
    { front: "pull in", pos: "phr. v.", def: "to arrive at a station, used about trains", example: "The train pulled in right on time.", zh: "（列車）進站" },
    { front: "pull out", pos: "phr. v.", def: "to leave a station, used about trains", example: "We reached the platform just as the train was pulling out.", zh: "（列車）駛離" },
    { front: "hop on", pos: "phr. v.", def: "to get on a bus, train or bike quickly", example: "Hop on the next bus and get off at the museum.", zh: "跳上（車）" },
    { front: "put someone up", pos: "phr. v.", def: "to let someone stay in your home", example: "My cousin put us up for the weekend in Rome.", zh: "留宿某人" },
    { front: "soak up", pos: "phr. v.", def: "to enjoy an atmosphere or experience fully", example: "We sat in the square soaking up the atmosphere.", zh: "沉浸於；盡情享受" },
    { front: "stay over", pos: "phr. v.", def: "to sleep at someone's house for a night", example: "It's late — why don't you stay over?", zh: "留宿過夜" },
    { front: "pack up", pos: "phr. v.", def: "to put your things into bags before leaving", example: "We packed up our tent and drove home.", zh: "收拾行李" },
    { front: "map out", pos: "phr. v.", def: "to plan something in detail", example: "She mapped out the whole route before the trip.", zh: "詳細規劃" },
    { front: "jet off", pos: "phr. v.", def: "to fly somewhere, especially on holiday", example: "They jetted off to the Maldives for their honeymoon.", zh: "搭機出遊" },
    { front: "venture out", pos: "phr. v.", def: "to go somewhere despite possible risks or bad weather", example: "We ventured out into the storm to find a restaurant.", zh: "冒險外出" },
    { front: "tick off", pos: "phr. v.", def: "to mark items on a list as done", example: "Another country ticked off my travel list!", zh: "打勾；完成清單項目" },
    { front: "press on", pos: "phr. v.", def: "to continue a journey or task despite difficulty", example: "Despite the rain, we pressed on to the next village.", zh: "繼續前進" },
    { front: "turn back", pos: "phr. v.", def: "to return the way you came", example: "The path was blocked, so we had to turn back.", zh: "折返" },
    { front: "get about", pos: "phr. v.", def: "to travel or move around a place", example: "It's easy to get about the city by tram.", zh: "四處走動；通行" },
    { front: "stock up on", pos: "phr. v.", def: "to buy a lot of something to use later", example: "We stocked up on snacks and water for the long bus ride.", zh: "囤購；備足" },
    { front: "start off", pos: "phr. v.", def: "to begin a journey or activity", example: "We started off at dawn to beat the heat.", zh: "啟程；開始" },
    { front: "pull up", pos: "phr. v.", def: "to stop a vehicle", example: "A taxi pulled up outside the hotel.", zh: "（車輛）停下" },
    { front: "head back", pos: "phr. v.", def: "to return towards the place you came from", example: "It's getting dark — we should head back to the hostel.", zh: "返回" },
    { front: "travel light", pos: "collocation", def: "to travel with very little luggage", example: "I always travel light, with just a small backpack.", zh: "輕裝旅行" },
    { front: "see the sights", pos: "collocation", def: "to visit the famous places in a city", example: "We spent two days seeing the sights of Paris.", zh: "觀光" },
    { front: "itchy feet", pos: "idiom", def: "a strong desire to travel", example: "After a year at home, I've got itchy feet again.", zh: "想去旅行的渴望" },
    { front: "on a shoestring", pos: "idiom", def: "with very little money", example: "We backpacked through Asia on a shoestring.", zh: "以極少的錢" },
    { front: "live out of a suitcase", pos: "idiom", def: "to travel so much that you never unpack properly", example: "As a tour manager, she lives out of a suitcase.", zh: "四處奔波（住旅館）" },
    { front: "home away from home", pos: "idiom", def: "a place where you feel as comfortable as at home", example: "The little guesthouse became our home away from home.", zh: "賓至如歸之處" },
    { front: "get away from it all", pos: "idiom", def: "to have a relaxing holiday far from daily life", example: "We rented a cabin in the woods to get away from it all.", zh: "遠離塵囂" },
    { front: "boarding pass", pos: "collocation", def: "the card that allows you to get on a plane", example: "Have your boarding pass and passport ready.", zh: "登機證" },
    { front: "window seat", pos: "collocation", def: "a seat next to the window on a plane or train", example: "I always ask for a window seat so I can watch the clouds.", zh: "靠窗座位" },
    { front: "connecting flight", pos: "collocation", def: "a second flight you take to continue your journey", example: "We missed our connecting flight in Frankfurt.", zh: "轉機航班" },
    { front: "package holiday", pos: "collocation", def: "a holiday where travel and hotel are arranged together", example: "They booked a package holiday to Greece.", zh: "套裝行程" },
    { front: "guided tour", pos: "collocation", def: "a visit to a place led by someone who explains it", example: "The guided tour of the palace lasts an hour.", zh: "導覽行程" },
    { front: "peak season", pos: "collocation", def: "the busiest time of year for travel", example: "Hotel prices double during peak season.", zh: "旺季" },
    { front: "exchange rate", pos: "collocation", def: "the value of one currency compared to another", example: "Check the exchange rate before you change your money.", zh: "匯率" },
    { front: "return ticket", pos: "collocation", def: "a ticket to a place and back again", example: "A return ticket is cheaper than two singles.", zh: "來回票" },
    { front: "full board", pos: "collocation", def: "hotel accommodation including all meals", example: "The price includes full board and airport transfers.", zh: "全食宿" },
    { front: "travel insurance", pos: "collocation", def: "insurance that protects you while travelling", example: "Never go abroad without travel insurance.", zh: "旅遊保險" },
    { front: "tourist trap", pos: "collocation", def: "a crowded place that charges tourists too much", example: "The restaurant by the tower is a real tourist trap.", zh: "坑觀光客的地方" },
    { front: "sprain", pos: "v.", def: "to injure a joint by twisting it", example: "She sprained her ankle playing basketball.", zh: "扭傷" },
    { front: "blister", pos: "n.", def: "a painful bubble of skin caused by rubbing or burning", example: "My new shoes gave me blisters on both heels.", zh: "水泡" },
    { front: "rash", pos: "n.", def: "red spots on the skin", example: "The medicine gave him a rash on his arms.", zh: "疹子" },
    { front: "nausea", pos: "n.", def: "the feeling that you are going to vomit", example: "The boat trip left me with terrible nausea.", zh: "噁心；反胃" },
    { front: "faint", pos: "v.", def: "to suddenly lose consciousness for a short time", example: "She fainted in the heat and fell to the ground.", zh: "昏倒" },
    { front: "numb", pos: "adj.", def: "unable to feel anything in part of your body", example: "My fingers went numb in the freezing wind.", zh: "麻木的" },
    { front: "itchy", pos: "adj.", def: "making you want to scratch your skin", example: "The mosquito bites are so itchy!", zh: "發癢的" },
    { front: "limp", pos: "v.", def: "to walk with difficulty because of an injured leg", example: "He limped off the pitch after the tackle.", zh: "跛行" },
    { front: "fracture", pos: "n.", def: "a break or crack in a bone", example: "The X-ray showed a small fracture in her wrist.", zh: "骨折" },
    { front: "stitches", pos: "n.", def: "threads used by doctors to close a cut", example: "The cut needed six stitches.", zh: "縫線；縫針" },
    { front: "ward", pos: "n.", def: "a room in a hospital where patients stay", example: "He spent a week in the children's ward.", zh: "病房" },
    { front: "specialist", pos: "n.", def: "a doctor with detailed knowledge of one area", example: "My GP referred me to a heart specialist.", zh: "專科醫師" },
    { front: "therapy", pos: "n.", def: "treatment to help the body or mind recover", example: "She's having therapy to deal with her anxiety.", zh: "治療" },
    { front: "therapist", pos: "n.", def: "a person trained to give treatment for problems", example: "The therapist taught him breathing exercises.", zh: "治療師" },
    { front: "counselling", pos: "n.", def: "professional help with personal problems", example: "The school offers free counselling to students.", zh: "心理諮商" },
    { front: "immune", pos: "adj.", def: "protected against a disease", example: "Once you've had the illness, you're usually immune to it.", zh: "免疫的" },
    { front: "contagious", pos: "adj.", def: "passing easily from one person to another", example: "Stay home — the flu is highly contagious.", zh: "接觸傳染的" },
    { front: "epidemic", pos: "n.", def: "a situation where a disease spreads quickly to many people", example: "The city struggled to control the flu epidemic.", zh: "流行病" },
    { front: "outbreak", pos: "n.", def: "the sudden start of a disease or something unpleasant", example: "There was an outbreak of food poisoning at the festival.", zh: "爆發" },
    { front: "prescribe", pos: "v.", def: "to say what medicine a patient should take", example: "The doctor prescribed antibiotics for the infection.", zh: "開（處方）" },
    { front: "allergic", pos: "adj.", def: "having a bad physical reaction to something", example: "I'm allergic to peanuts, so I always check the label.", zh: "過敏的" },
    { front: "infectious", pos: "adj.", def: "able to be passed from one person to another", example: "Measles is an extremely infectious disease.", zh: "傳染性的" },
    { front: "surgery", pos: "n.", def: "medical treatment that involves cutting the body", example: "He needs surgery on his injured knee.", zh: "手術" },
    { front: "plaster", pos: "n.", def: "a small sticky cover for a cut on the skin", example: "Put a plaster on that cut before it gets dirty.", zh: "OK繃" },
    { front: "injection", pos: "n.", def: "the act of putting medicine into the body with a needle", example: "The nurse gave me an injection in my arm.", zh: "注射" },
    { front: "dose", pos: "n.", def: "a measured amount of medicine", example: "Never take more than the recommended dose.", zh: "劑量" },
    { front: "crutches", pos: "n.", def: "sticks that help an injured person walk", example: "He was on crutches for six weeks after the operation.", zh: "拐杖" },
    { front: "paramedic", pos: "n.", def: "a person trained to give emergency medical help", example: "Paramedics treated the driver at the scene.", zh: "救護員" },
    { front: "obesity", pos: "n.", def: "the condition of being dangerously overweight", example: "Childhood obesity is a growing problem worldwide.", zh: "肥胖症" },
    { front: "nutrition", pos: "n.", def: "the food you eat and the way it affects your health", example: "Good nutrition is essential for growing children.", zh: "營養" },
    { front: "digest", pos: "v.", def: "to break down food in your stomach", example: "Heavy meals are hard to digest late at night.", zh: "消化" },
    { front: "circulation", pos: "n.", def: "the movement of blood around the body", example: "Regular exercise improves your circulation.", zh: "血液循環" },
    { front: "joint", pos: "n.", def: "a place where two bones meet", example: "Cold weather makes my joints ache.", zh: "關節" },
    { front: "spine", pos: "n.", def: "the line of bones down the middle of your back", example: "Sitting badly all day is terrible for your spine.", zh: "脊椎" },
    { front: "skull", pos: "n.", def: "the bones of the head", example: "The helmet protected his skull in the crash.", zh: "頭骨" },
    { front: "rib", pos: "n.", def: "one of the curved bones around the chest", example: "He broke two ribs falling off his bike.", zh: "肋骨" },
    { front: "liver", pos: "n.", def: "the organ that cleans the blood", example: "Drinking too much alcohol damages the liver.", zh: "肝臟" },
    { front: "kidney", pos: "n.", def: "one of the two organs that clean waste from the blood", example: "She donated a kidney to her brother.", zh: "腎臟" },
    { front: "pulse", pos: "n.", def: "the regular beat of blood in your body", example: "The nurse checked my pulse and blood pressure.", zh: "脈搏" },
    { front: "breathless", pos: "adj.", def: "having difficulty breathing", example: "Climbing the stairs leaves him breathless these days.", zh: "喘不過氣的" },
    { front: "fatigue", pos: "n.", def: "extreme tiredness", example: "Fatigue is a common symptom of the illness.", zh: "疲勞" },
    { front: "drowsy", pos: "adj.", def: "sleepy, often because of medicine", example: "These tablets may make you feel drowsy.", zh: "昏昏欲睡的" },
    { front: "hoarse", pos: "adj.", def: "having a rough voice, often from illness or shouting", example: "She was hoarse after cheering all night at the concert.", zh: "沙啞的" },
    { front: "chronic", pos: "adj.", def: "lasting a long time, used about illness", example: "He suffers from chronic back pain.", zh: "慢性的" },
    { front: "well-being", pos: "n.", def: "the state of feeling healthy and happy", example: "Exercise is good for both physical and mental well-being.", zh: "身心健康；福祉" },
    { front: "hygiene", pos: "n.", def: "the practice of keeping things clean to stay healthy", example: "Good hand hygiene helps prevent illness.", zh: "衛生" },
    { front: "transplant", pos: "n.", def: "an operation to put an organ from one person into another", example: "He's waiting for a heart transplant.", zh: "器官移植" },
    { front: "donor", pos: "n.", def: "a person who gives blood or an organ to help others", example: "Blood donors are urgently needed this winter.", zh: "捐贈者" },
    { front: "anaesthetic", pos: "n.", def: "a drug that stops you feeling pain", example: "The operation is done under general anaesthetic.", zh: "麻醉劑" },
    { front: "posture", pos: "n.", def: "the way you hold your body when sitting or standing", example: "Poor posture at your desk causes neck pain.", zh: "姿勢" },
    { front: "addiction", pos: "n.", def: "the condition of being unable to stop doing something harmful", example: "He's getting help for his addiction to gambling.", zh: "成癮" },
    { front: "hangover", pos: "n.", def: "a headache and sick feeling after drinking too much alcohol", example: "He woke up with a terrible hangover.", zh: "宿醉" },
    { front: "swallow", pos: "v.", def: "to make food or drink go down your throat", example: "My throat is so sore I can hardly swallow.", zh: "吞嚥" },
    { front: "choke", pos: "v.", def: "to be unable to breathe because something blocks your throat", example: "He nearly choked on a fish bone.", zh: "噎住" },
    { front: "scar", pos: "n.", def: "a mark left on the skin after a wound heals", example: "The operation left a small scar on her knee.", zh: "疤痕" },
    { front: "run-down", pos: "adj.", def: "tired and slightly ill from working too hard", example: "You look run-down — you should take a few days off.", zh: "疲憊虛弱的" },
    { front: "throw up", pos: "phr. v.", def: "to vomit", example: "The child threw up twice on the car journey.", zh: "嘔吐" },
    { front: "black out", pos: "phr. v.", def: "to suddenly lose consciousness", example: "He blacked out from the pain and woke up in hospital.", zh: "昏厥" },
    { front: "wear off", pos: "phr. v.", def: "to gradually stop having an effect", example: "The painkillers will wear off in a few hours.", zh: "（藥效）逐漸消退" },
    { front: "flare up", pos: "phr. v.", def: "to suddenly become worse, used about illness", example: "Her allergies flare up every spring.", zh: "（病情）突然發作" },
    { front: "swell up", pos: "phr. v.", def: "to become larger because of injury or illness", example: "His ankle swelled up after the fall.", zh: "腫起來" },
    { front: "shake off", pos: "phr. v.", def: "to get rid of an illness or problem", example: "I can't seem to shake off this cold.", zh: "擺脫（感冒等）" },
    { front: "fight off", pos: "phr. v.", def: "to stop an illness from developing", example: "Vitamin C may help you fight off infections.", zh: "抵抗（疾病）" },
    { front: "break out in", pos: "phr. v.", def: "to suddenly develop spots or sweat on your skin", example: "She broke out in a rash after eating the shellfish.", zh: "突然冒出（疹子）" },
    { front: "bounce back", pos: "phr. v.", def: "to recover quickly after illness or difficulty", example: "Children usually bounce back quickly from minor illnesses.", zh: "迅速康復" },
    { front: "work off", pos: "phr. v.", def: "to get rid of something, such as stress or calories, through activity", example: "I went for a run to work off some stress.", zh: "藉活動消耗、發洩" },
    { front: "sleep off", pos: "phr. v.", def: "to recover from something by sleeping", example: "He went to bed early to sleep off his headache.", zh: "以睡眠恢復" },
    { front: "go down with", pos: "phr. v.", def: "to become ill with something", example: "Half the class went down with the flu last week.", zh: "染上（疾病）" },
    { front: "come off", pos: "phr. v.", def: "to stop taking medicine or drugs", example: "The doctor says I can come off the tablets next month.", zh: "停（藥）" },
    { front: "perk up", pos: "phr. v.", def: "to become more lively or cheerful", example: "She perked up after a cup of coffee and a rest.", zh: "打起精神" },
    { front: "tone up", pos: "phr. v.", def: "to make your muscles firmer through exercise", example: "Swimming is a great way to tone up your whole body.", zh: "鍛鍊緊實（肌肉）" },
    { front: "burn off", pos: "phr. v.", def: "to use energy or calories through exercise", example: "A long walk helps burn off the big lunch.", zh: "燃燒（熱量）" },
    { front: "as fit as a fiddle", pos: "idiom", def: "in very good health", example: "At eighty, my grandfather is still as fit as a fiddle.", zh: "非常健康" },
    { front: "back on your feet", pos: "idiom", def: "healthy again after an illness", example: "It took a month, but she's finally back on her feet.", zh: "恢復健康" },
    { front: "on the mend", pos: "idiom", def: "getting better after an illness", example: "He was very ill, but he's on the mend now.", zh: "在康復中" },
    { front: "a clean bill of health", pos: "idiom", def: "a report saying that you are completely healthy", example: "After the tests, the doctor gave me a clean bill of health.", zh: "健康無虞的證明" },
    { front: "pull a muscle", pos: "collocation", def: "to injure a muscle by stretching it too much", example: "I pulled a muscle in my back lifting the boxes.", zh: "拉傷肌肉" },
    { front: "blood pressure", pos: "collocation", def: "the force of blood in your body, measured by doctors", example: "High blood pressure runs in our family.", zh: "血壓" },
    { front: "heart attack", pos: "collocation", def: "a sudden serious medical problem with the heart", example: "He survived a heart attack at fifty and changed his diet.", zh: "心臟病發作" },
    { front: "food poisoning", pos: "collocation", def: "illness caused by eating bad food", example: "We got food poisoning from the seafood restaurant.", zh: "食物中毒" },
    { front: "sick leave", pos: "collocation", def: "time away from work because of illness", example: "She's been on sick leave since the operation.", zh: "病假" },
    { front: "immune system", pos: "collocation", def: "the body's system that fights disease", example: "Lack of sleep weakens your immune system.", zh: "免疫系統" },
    { front: "runny nose", pos: "collocation", def: "a nose producing liquid because of a cold or allergy", example: "The baby has a runny nose and a slight cough.", zh: "流鼻水" },
    { front: "sore throat", pos: "collocation", def: "pain in the throat, often from a cold", example: "I woke up with a sore throat and a fever.", zh: "喉嚨痛" },
    { front: "put on weight", pos: "collocation", def: "to become heavier", example: "I put on weight over the holidays.", zh: "變胖" },
    { front: "catch your breath", pos: "idiom", def: "to rest until you can breathe normally again", example: "We stopped at the top of the hill to catch our breath.", zh: "喘口氣" },
    { front: "take a turn for the worse", pos: "idiom", def: "to suddenly become worse", example: "Her condition took a turn for the worse overnight.", zh: "（病情）惡化" },
    { front: "make a full recovery", pos: "collocation", def: "to become completely healthy again", example: "Doctors expect him to make a full recovery.", zh: "完全康復" },
    { front: "get a second opinion", pos: "collocation", def: "to ask another doctor for their view", example: "Before the operation, she decided to get a second opinion.", zh: "尋求第二意見" },
    { front: "recharge your batteries", pos: "idiom", def: "to rest in order to get your energy back", example: "A week by the sea will help you recharge your batteries.", zh: "充電；恢復精力" },
    { front: "burglary", pos: "n.", def: "the crime of entering a building to steal", example: "There have been several burglaries in our street recently.", zh: "入室竊盜" },
    { front: "mugging", pos: "n.", def: "an attack on someone in the street to rob them", example: "He reported the mugging to the police immediately.", zh: "街頭搶劫" },
    { front: "pickpocket", pos: "n.", def: "a thief who steals from people's pockets or bags", example: "Watch out for pickpockets on the crowded metro.", zh: "扒手" },
    { front: "vandalism", pos: "n.", def: "the crime of deliberately damaging property", example: "The bus stop was destroyed in an act of vandalism.", zh: "破壞公物" },
    { front: "fraud", pos: "n.", def: "the crime of deceiving people to get money", example: "He was arrested for credit card fraud.", zh: "詐欺" },
    { front: "forgery", pos: "n.", def: "the crime of making false copies of documents or money", example: "The passport turned out to be a forgery.", zh: "偽造" },
    { front: "smuggle", pos: "v.", def: "to take things into a country illegally", example: "They tried to smuggle cigarettes across the border.", zh: "走私" },
    { front: "kidnap", pos: "v.", def: "to take someone away illegally, usually for money", example: "The businessman's son was kidnapped on his way to school.", zh: "綁架" },
    { front: "hijack", pos: "v.", def: "to take control of a vehicle by force", example: "The plane was hijacked shortly after take-off.", zh: "劫持" },
    { front: "blackmail", pos: "n.", def: "the crime of demanding money by threatening to reveal secrets", example: "He was sent to prison for blackmail.", zh: "勒索" },
    { front: "bribery", pos: "n.", def: "the crime of giving money to influence someone's decisions", example: "The official was accused of bribery and corruption.", zh: "賄賂" },
    { front: "arson", pos: "n.", def: "the crime of deliberately setting fire to property", example: "Police believe the fire at the school was arson.", zh: "縱火" },
    { front: "assault", pos: "n.", def: "the crime of physically attacking someone", example: "He was charged with assault after the fight.", zh: "傷害罪；攻擊" },
    { front: "offence", pos: "n.", def: "an illegal act", example: "Driving without a licence is a serious offence.", zh: "罪行" },
    { front: "offender", pos: "n.", def: "a person who has committed a crime", example: "The programme helps young offenders find work.", zh: "罪犯" },
    { front: "verdict", pos: "n.", def: "the official decision in a court case", example: "The jury announced a verdict of not guilty.", zh: "判決" },
    { front: "jury", pos: "n.", def: "the group of people who decide if someone is guilty in court", example: "The jury took two days to reach a decision.", zh: "陪審團" },
    { front: "solicitor", pos: "n.", def: "a lawyer who gives legal advice and prepares documents", example: "You should speak to a solicitor before signing anything.", zh: "初級律師" },
    { front: "prosecute", pos: "v.", def: "to take legal action against someone in court", example: "Shoplifters will be prosecuted.", zh: "起訴" },
    { front: "defendant", pos: "n.", def: "the person accused of a crime in court", example: "The defendant denied all the charges.", zh: "被告" },
    { front: "imprisonment", pos: "n.", def: "the punishment of being kept in prison", example: "He faces ten years' imprisonment if found guilty.", zh: "監禁" },
    { front: "legislation", pos: "n.", def: "a law or set of laws", example: "New legislation will ban smoking in parks.", zh: "立法；法規" },
    { front: "prohibit", pos: "v.", def: "to officially forbid something", example: "The law prohibits the sale of alcohol to minors.", zh: "禁止" },
    { front: "enforce", pos: "v.", def: "to make people obey a law or rule", example: "Police will strictly enforce the new speed limits.", zh: "執行（法律）" },
    { front: "poverty", pos: "n.", def: "the state of being very poor", example: "Millions of children still grow up in poverty.", zh: "貧窮" },
    { front: "inequality", pos: "n.", def: "an unfair situation where some people have more than others", example: "The report highlights growing income inequality.", zh: "不平等" },
    { front: "discrimination", pos: "n.", def: "unfair treatment of people because of their group", example: "The company was fined for age discrimination.", zh: "歧視" },
    { front: "prejudice", pos: "n.", def: "an unfair opinion formed without knowledge", example: "We must challenge prejudice wherever we find it.", zh: "偏見" },
    { front: "minority", pos: "n.", def: "a smaller group within a larger population", example: "The law protects the rights of ethnic minorities.", zh: "少數群體" },
    { front: "welfare", pos: "n.", def: "help given by the state to people in need", example: "The family survived on welfare payments for a year.", zh: "社會福利" },
    { front: "unemployment", pos: "n.", def: "the situation of people not having jobs", example: "Youth unemployment has fallen to a record low.", zh: "失業" },
    { front: "protest", pos: "n.", def: "an action showing public disagreement", example: "Thousands joined the protest against the new law.", zh: "抗議" },
    { front: "petition", pos: "n.", def: "a document signed by many people asking for change", example: "Over ten thousand people signed the petition.", zh: "請願書" },
    { front: "citizen", pos: "n.", def: "a person who legally belongs to a country", example: "All citizens over eighteen have the right to vote.", zh: "公民" },
    { front: "demonstration", pos: "n.", def: "a public march or gathering to show an opinion", example: "A peaceful demonstration was held outside parliament.", zh: "示威遊行" },
    { front: "riot", pos: "n.", def: "violent behaviour by a crowd of people", example: "Riots broke out in the capital after the election.", zh: "暴動" },
    { front: "curfew", pos: "n.", def: "a rule that people must stay indoors at certain times", example: "The city imposed a night-time curfew during the unrest.", zh: "宵禁" },
    { front: "custody", pos: "n.", def: "the state of being kept by the police", example: "The suspect is being held in police custody.", zh: "拘留；監護" },
    { front: "bail", pos: "n.", def: "money paid so an accused person can stay free until trial", example: "He was released on bail of fifty thousand pounds.", zh: "保釋金" },
    { front: "convict", pos: "v.", def: "to officially decide in court that someone is guilty", example: "She was convicted of fraud and fined heavily.", zh: "定罪" },
    { front: "alibi", pos: "n.", def: "proof that you were somewhere else when a crime happened", example: "He has a solid alibi for the night of the robbery.", zh: "不在場證明" },
    { front: "investigation", pos: "n.", def: "an official attempt to discover the facts about something", example: "Police have launched an investigation into the fire.", zh: "調查" },
    { front: "corruption", pos: "n.", def: "dishonest behaviour by people in power", example: "The minister resigned over corruption charges.", zh: "貪腐" },
    { front: "scam", pos: "n.", def: "a dishonest plan to get people's money", example: "Thousands lost money in the online scam.", zh: "騙局" },
    { front: "hostage", pos: "n.", def: "a person held prisoner until demands are met", example: "The robbers took three hostages inside the bank.", zh: "人質" },
    { front: "ransom", pos: "n.", def: "money demanded for the release of a prisoner", example: "The kidnappers demanded a million-dollar ransom.", zh: "贖金" },
    { front: "gang", pos: "n.", def: "an organised group of criminals", example: "The gang was responsible for a series of robberies.", zh: "幫派" },
    { front: "law-abiding", pos: "adj.", def: "always obeying the law", example: "He's a law-abiding citizen who has never even had a parking fine.", zh: "守法的" },
    { front: "legalise", pos: "v.", def: "to make something legal", example: "The country voted to legalise same-sex marriage.", zh: "使合法化" },
    { front: "abolish", pos: "v.", def: "to officially end a law or system", example: "The death penalty was abolished decades ago.", zh: "廢除" },
    { front: "diversity", pos: "n.", def: "the fact of including many different types of people", example: "The city is proud of its cultural diversity.", zh: "多元性" },
    { front: "refugee", pos: "n.", def: "a person forced to leave their country for safety", example: "The charity provides shelter for refugees.", zh: "難民" },
    { front: "injustice", pos: "n.", def: "an unfair situation or treatment", example: "The film exposes the injustice faced by the workers.", zh: "不公不義" },
    { front: "sue", pos: "v.", def: "to take legal action against someone for money", example: "She sued the company for unfair dismissal.", zh: "控告" },
    { front: "compensation", pos: "n.", def: "money paid to someone for harm or loss", example: "Passengers received compensation for the delayed flight.", zh: "賠償金" },
    { front: "activist", pos: "n.", def: "a person who works to bring social or political change", example: "Environmental activists blocked the road to the factory.", zh: "社運人士" },
    { front: "controversial", pos: "adj.", def: "causing a lot of public disagreement", example: "The new law on protests is highly controversial.", zh: "有爭議的" },
    { front: "track down", pos: "phr. v.", def: "to find someone or something after a long search", example: "Police finally tracked down the escaped prisoner.", zh: "追查到" },
    { front: "crack down on", pos: "phr. v.", def: "to start dealing with bad behaviour more strictly", example: "The government is cracking down on tax fraud.", zh: "嚴厲打擊" },
    { front: "cover up", pos: "phr. v.", def: "to hide the truth about something bad", example: "Officials tried to cover up the scandal for years.", zh: "掩蓋" },
    { front: "tip off", pos: "phr. v.", def: "to secretly warn someone, especially the police", example: "Someone tipped off the police about the robbery.", zh: "密報" },
    { front: "make off with", pos: "phr. v.", def: "to steal something and escape with it", example: "The thieves made off with jewellery worth thousands.", zh: "偷走；攜贓逃逸" },
    { front: "turn yourself in", pos: "phr. v.", def: "to go to the police and admit your crime", example: "After a week in hiding, he turned himself in.", zh: "自首" },
    { front: "break out of", pos: "phr. v.", def: "to escape from a prison", example: "Two prisoners broke out of the jail last night.", zh: "逃出（監獄）" },
    { front: "bring in", pos: "phr. v.", def: "to introduce a new law or rule", example: "The government brought in stricter driving laws.", zh: "推行（新法）" },
    { front: "do away with", pos: "phr. v.", def: "to get rid of a law or system", example: "The government did away with the old licensing rules.", zh: "廢除" },
    { front: "beat up", pos: "phr. v.", def: "to hurt someone badly by hitting them", example: "He was beaten up outside the nightclub.", zh: "痛毆" },
    { front: "abide by", pos: "phr. v.", def: "to obey a rule or decision", example: "All members must abide by the club's rules.", zh: "遵守" },
    { front: "stamp out", pos: "phr. v.", def: "to end something bad completely", example: "The school is determined to stamp out bullying.", zh: "根除" },
    { front: "speak out", pos: "phr. v.", def: "to publicly give your opinion against something wrong", example: "More victims are speaking out against the company.", zh: "公開表態；仗義執言" },
    { front: "hunt down", pos: "phr. v.", def: "to search for someone until you catch them", example: "Detectives spent months hunting down the fraudster.", zh: "緝捕" },
    { front: "inform on", pos: "phr. v.", def: "to secretly tell the police about someone's crime", example: "He informed on his own gang to avoid prison.", zh: "告發" },
    { front: "behind bars", pos: "idiom", def: "in prison", example: "The burglar will spend the next five years behind bars.", zh: "入獄" },
    { front: "take the law into your own hands", pos: "idiom", def: "to punish someone yourself instead of using the police", example: "Angry residents took the law into their own hands and blocked the road.", zh: "私自執法" },
    { front: "caught red-handed", pos: "idiom", def: "caught at the moment of doing something wrong", example: "The shoplifter was caught red-handed by the guard.", zh: "當場被抓" },
    { front: "face the music", pos: "idiom", def: "to accept punishment for what you have done", example: "He skipped school and now he has to face the music.", zh: "承擔後果" },
    { front: "bend the rules", pos: "idiom", def: "to do something not normally allowed", example: "The manager bent the rules and let us in without tickets.", zh: "通融；變通規則" },
    { front: "do time", pos: "idiom", def: "to spend a period in prison", example: "He did time for robbery in his twenties.", zh: "坐牢" },
    { front: "community service", pos: "collocation", def: "unpaid work as punishment for a small crime", example: "She was sentenced to eighty hours of community service.", zh: "社區服務（刑罰）" },
    { front: "capital punishment", pos: "collocation", def: "punishment by death", example: "Many countries have abolished capital punishment.", zh: "死刑" },
    { front: "human rights", pos: "collocation", def: "the basic rights that every person should have", example: "The organisation campaigns for human rights worldwide.", zh: "人權" },
    { front: "freedom of speech", pos: "collocation", def: "the right to express your opinions publicly", example: "Freedom of speech is protected by the constitution.", zh: "言論自由" },
    { front: "go on strike", pos: "collocation", def: "to stop working as a protest", example: "The train drivers went on strike over pay.", zh: "罷工" },
    { front: "life sentence", pos: "collocation", def: "the punishment of staying in prison for life", example: "The murderer received a life sentence.", zh: "無期徒刑" },
    { front: "serve a sentence", pos: "collocation", def: "to spend time in prison as punishment", example: "He is serving a ten-year sentence for fraud.", zh: "服刑" },
    { front: "reach a verdict", pos: "collocation", def: "to make a final decision in court", example: "The jury failed to reach a verdict after three days.", zh: "作出判決" },
    { front: "law and order", pos: "collocation", def: "the situation where laws are obeyed", example: "The new mayor promised to restore law and order.", zh: "法律與秩序" },
    { front: "black market", pos: "collocation", def: "illegal buying and selling of goods", example: "Tickets were being sold on the black market at triple the price.", zh: "黑市" },
    { front: "a slap on the wrist", pos: "idiom", def: "a punishment that is too light", example: "He only got a slap on the wrist for cheating.", zh: "輕微的懲罰" },
    { front: "partners in crime", pos: "idiom", def: "people who do things together, often mischievous ones", example: "My sister and I were partners in crime as kids.", zh: "共犯；狼狽為奸的夥伴" },
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
