/* FCE Prep extra bank: vocab wave 5 */
(function () {
  var BANK = [
    // --- Entertainment / media / film ---
    { front: "sequel", pos: "n.", def: "a film or book that continues the story of an earlier one", example: "The sequel was even more exciting than the original film.", zh: "續集" },
    { front: "soundtrack", pos: "n.", def: "the music that accompanies a film", example: "I bought the soundtrack after watching the movie twice.", zh: "電影配樂；原聲帶" },
    { front: "subtitle", pos: "n.", def: "words shown at the bottom of a screen that translate what is said", example: "We watched the French film with English subtitles.", zh: "字幕" },
    { front: "blockbuster", pos: "n.", def: "a film or book that is very successful and popular", example: "The summer blockbuster earned millions in its first weekend.", zh: "賣座大片" },
    { front: "screenplay", pos: "n.", def: "the written text of a film, including dialogue and instructions", example: "She wrote the screenplay for an award-winning drama.", zh: "電影劇本" },
    { front: "episode", pos: "n.", def: "one part of a television or radio series", example: "The final episode of the series left everyone in tears.", zh: "（影集的）一集" },
    { front: "documentary", pos: "n.", def: "a film or programme giving facts about real events or people", example: "We watched a fascinating documentary about ocean life.", zh: "紀錄片" },
    { front: "sitcom", pos: "n.", def: "a funny television series about the same group of characters", example: "That sitcom has been making people laugh for ten years.", zh: "情境喜劇" },
    { front: "thriller", pos: "n.", def: "an exciting story about crime or danger", example: "I stayed up all night finishing the thriller.", zh: "驚悚片；驚悚小說" },
    { front: "animation", pos: "n.", def: "films made with drawings or computer images that appear to move", example: "The studio is famous for its beautiful hand-drawn animation.", zh: "動畫" },
    { front: "special effects", pos: "collocation", def: "images or sounds created artificially for a film", example: "The special effects in the space battle were incredible.", zh: "特效" },
    { front: "premiere", pos: "n.", def: "the first public showing of a film or play", example: "Hundreds of fans attended the film premiere in London.", zh: "首映" },
    { front: "red carpet", pos: "collocation", def: "special treatment given to famous or important visitors", example: "The stars posed for photos on the red carpet.", zh: "紅毯；隆重接待" },
    { front: "stage fright", pos: "collocation", def: "nervous fear felt before performing in front of people", example: "She suffered from terrible stage fright before her first concert.", zh: "怯場" },
    { front: "catchy", pos: "adj.", def: "pleasant and easy to remember, especially a tune", example: "The advert has such a catchy song that I keep humming it.", zh: "琅琅上口的" },
    { front: "gripping", pos: "adj.", def: "so exciting that it holds your attention completely", example: "The novel was so gripping that I read it in one sitting.", zh: "扣人心弦的" },
    { front: "hilarious", pos: "adj.", def: "extremely funny", example: "His impression of the teacher was absolutely hilarious.", zh: "極其好笑的" },
    { front: "predictable", pos: "adj.", def: "happening in a way that is easy to guess", example: "The ending of the film was disappointingly predictable.", zh: "可預測的；老套的" },
    { front: "entertaining", pos: "adj.", def: "amusing and enjoyable", example: "The show was light but very entertaining.", zh: "有趣的；令人愉快的" },
    { front: "chat show", pos: "n.", def: "a TV programme where famous people are interviewed informally", example: "The actor told a funny story on the chat show last night.", zh: "訪談節目" },
    { front: "reality show", pos: "n.", def: "a programme that films ordinary people in real situations", example: "She became famous after winning a cooking reality show.", zh: "實境節目" },
    { front: "tabloid", pos: "n.", def: "a small newspaper with many pictures and stories about famous people", example: "The tabloids published photos of the singer on holiday.", zh: "小報" },
    { front: "press conference", pos: "collocation", def: "a meeting where someone answers questions from journalists", example: "The manager announced his resignation at a press conference.", zh: "記者會" },
    { front: "ratings", pos: "n.", def: "figures showing how many people watch a programme", example: "The show was cancelled because of poor ratings.", zh: "收視率" },
    { front: "binge-watch", pos: "v.", def: "to watch many episodes of a series without stopping", example: "We binge-watched the whole season over the weekend.", zh: "追劇；連續狂看" },
    { front: "spoiler", pos: "n.", def: "information that reveals what happens in a story", example: "Don't give me any spoilers - I haven't seen the last episode yet!", zh: "劇透" },
    { front: "trailer", pos: "n.", def: "a short piece of film advertising a movie", example: "The trailer made the film look much better than it actually was.", zh: "預告片" },
    { front: "villain", pos: "n.", def: "the bad character in a story or film", example: "The villain in this movie is far more interesting than the hero.", zh: "反派" },
    { front: "scene", pos: "n.", def: "a part of a film or play happening in one place", example: "The opening scene takes place in a busy train station.", zh: "場景；一場戲" },
    { front: "remake", pos: "n.", def: "a new version of an old film", example: "The remake was nowhere near as good as the 1980s original.", zh: "重拍版" },
    { front: "tune in", pos: "phr. v.", def: "to watch or listen to a particular programme", example: "Millions of viewers tune in to the show every Saturday.", zh: "收看；收聽" },
    { front: "star in", pos: "phr. v.", def: "to have the main role in a film or show", example: "She starred in three successful films last year.", zh: "主演" },
    { front: "switch over", pos: "phr. v.", def: "to change from one TV channel to another", example: "This programme is boring - can we switch over to the news?", zh: "轉台" },
    { front: "be based on", pos: "collocation", def: "to use something as the starting point for a story", example: "The film is based on a true story from the 1960s.", zh: "根據……改編" },
    { front: "film crew", pos: "collocation", def: "the group of people who work together to make a film", example: "The film crew spent three months shooting in Iceland.", zh: "電影攝製團隊" },
    { front: "leading role", pos: "collocation", def: "the most important part in a film or play", example: "A young unknown actress was given the leading role.", zh: "主角" },
    { front: "supporting role", pos: "collocation", def: "a smaller acting part that is not the main character", example: "He won an award for his supporting role in the drama.", zh: "配角" },
    { front: "script", pos: "n.", def: "the written words of a film, play or speech", example: "The actors received the script a week before filming began.", zh: "劇本；講稿" },
    { front: "backstage", pos: "adv.", def: "in the area behind the stage in a theatre", example: "We were lucky enough to meet the band backstage.", zh: "在後台" },
    { front: "encore", pos: "n.", def: "an extra performance given because the audience asks for more", example: "The band played two encores before finally leaving the stage.", zh: "安可曲" },
    { front: "applaud", pos: "v.", def: "to clap your hands to show enjoyment or approval", example: "The audience applauded loudly at the end of the play.", zh: "鼓掌" },
    { front: "comedian", pos: "n.", def: "a person whose job is to make people laugh", example: "The comedian had the whole theatre laughing within minutes.", zh: "喜劇演員" },
    { front: "plot twist", pos: "collocation", def: "an unexpected change in the story", example: "The plot twist at the end took everyone by surprise.", zh: "劇情轉折" },
    { front: "cliffhanger", pos: "n.", def: "an exciting ending that leaves the story unfinished", example: "The episode ended on a cliffhanger, so we have to wait a week.", zh: "懸念結尾" },
    { front: "season finale", pos: "collocation", def: "the last episode of a series of programmes", example: "The season finale attracted a record number of viewers.", zh: "季終集" },
    { front: "news bulletin", pos: "collocation", def: "a short broadcast of the latest news", example: "The accident was reported in the evening news bulletin.", zh: "新聞快報" },
    { front: "front page", pos: "collocation", def: "the first page of a newspaper with the most important stories", example: "The scandal was on the front page of every newspaper.", zh: "頭版" },
    { front: "columnist", pos: "n.", def: "a journalist who writes regular articles giving opinions", example: "She works as a sports columnist for a national newspaper.", zh: "專欄作家" },
    { front: "subscription", pos: "n.", def: "money paid regularly to receive a service or magazine", example: "I cancelled my subscription because I never watched anything.", zh: "訂閱（費）" },
    { front: "presenter", pos: "n.", def: "a person who introduces a television or radio programme", example: "The presenter welcomed the guests onto the show.", zh: "節目主持人" },
    { front: "quiz show", pos: "n.", def: "a TV programme where people answer questions to win prizes", example: "He won ten thousand pounds on a TV quiz show.", zh: "益智問答節目" },
    { front: "game show", pos: "n.", def: "a TV programme where people play games to win prizes", example: "The game show has been running for over twenty years.", zh: "遊戲節目" },
    { front: "talent show", pos: "n.", def: "a competition where people perform to show their skills", example: "She was discovered on a talent show when she was sixteen.", zh: "選秀節目" },
    { front: "contestant", pos: "n.", def: "a person who takes part in a competition", example: "Each contestant has ninety seconds to answer the questions.", zh: "參賽者" },
    { front: "overnight success", pos: "collocation", def: "someone who becomes famous or successful very suddenly", example: "The song made her an overnight success at the age of nineteen.", zh: "一夜成名" },
    { front: "fame", pos: "n.", def: "the state of being known by many people", example: "He found fame difficult to cope with at first.", zh: "名聲；名氣" },
    // --- Sports / fitness ---
    { front: "stretch", pos: "v.", def: "to make your muscles longer by extending your body", example: "Always stretch properly before you go for a run.", zh: "伸展；拉筋" },
    { front: "jog", pos: "v.", def: "to run slowly for exercise", example: "She jogs around the park every morning before work.", zh: "慢跑" },
    { front: "umpire", pos: "n.", def: "the person who makes sure players follow the rules in some sports", example: "The umpire decided the ball had landed outside the line.", zh: "（網球、棒球等的）裁判" },
    { front: "beat", pos: "v.", def: "to defeat someone in a game or competition", example: "Our team beat the champions two goals to one.", zh: "打敗" },
    { front: "endurance", pos: "n.", def: "the ability to continue doing something difficult for a long time", example: "Marathon running requires incredible endurance.", zh: "耐力" },
    { front: "flexibility", pos: "n.", def: "the ability to bend and move your body easily", example: "Yoga has really improved my flexibility.", zh: "柔軟度；靈活性" },
    { front: "personal best", pos: "collocation", def: "the best result someone has ever achieved in a sport", example: "She set a new personal best in the 100 metres.", zh: "個人最佳成績" },
    { front: "gym membership", pos: "collocation", def: "the right to use a gym after paying a fee", example: "My gym membership costs forty pounds a month.", zh: "健身房會員資格" },
    { front: "whistle", pos: "n.", def: "a small object that makes a high sound when you blow it", example: "The referee blew his whistle to stop the game.", zh: "哨子" },
    { front: "track", pos: "n.", def: "a circular path used for running or racing", example: "The athletes warmed up on the track before the race.", zh: "跑道" },
    { front: "gear", pos: "n.", def: "the equipment or clothes needed for an activity", example: "Don't forget to bring your swimming gear tomorrow.", zh: "裝備" },
    { front: "athletic", pos: "adj.", def: "physically strong, fit and good at sport", example: "She comes from a very athletic family of runners.", zh: "運動型的；健壯的" },
    { front: "competitive", pos: "adj.", def: "wanting very much to win or be more successful than others", example: "He is so competitive that he even hates losing at cards.", zh: "好勝的；競爭激烈的" },
    { front: "level playing field", pos: "idiom", def: "a situation that is fair for everyone involved", example: "The new rules should create a level playing field for all clubs.", zh: "公平的競爭環境" },
    { front: "move the goalposts", pos: "idiom", def: "to unfairly change the rules or conditions of something", example: "Every time we meet the targets, the boss moves the goalposts.", zh: "任意改變規則" },
    { front: "get into shape", pos: "idiom", def: "to become physically fit through exercise", example: "I am trying to get into shape before the summer holidays.", zh: "鍛鍊身材；變健康" },
    { front: "out of breath", pos: "collocation", def: "breathing fast because of physical effort", example: "I was completely out of breath after climbing the stairs.", zh: "上氣不接下氣" },
    { front: "workout", pos: "n.", def: "a period of physical exercise", example: "She does a thirty-minute workout before breakfast.", zh: "健身；訓練" },
    { front: "training session", pos: "collocation", def: "a period of time spent practising a sport", example: "The team has two training sessions a day before big matches.", zh: "訓練課程" },
    { front: "captain", pos: "n.", def: "the leader of a sports team", example: "The captain encouraged her teammates before the final.", zh: "隊長" },
    { front: "defender", pos: "n.", def: "a player whose job is to stop the other team scoring", example: "The defender cleared the ball just before the striker reached it.", zh: "後衛" },
    { front: "striker", pos: "n.", def: "a player whose main job is to score goals", example: "Their star striker has scored twenty goals this season.", zh: "前鋒" },
    { front: "spectator sport", pos: "collocation", def: "a sport that people enjoy watching", example: "Football is the most popular spectator sport in the country.", zh: "觀賞性運動" },
    { front: "home team", pos: "collocation", def: "the team playing at its own ground", example: "The home team had the support of forty thousand fans.", zh: "主場隊伍" },
    { front: "final whistle", pos: "collocation", def: "the sound that marks the end of a match", example: "The fans ran onto the pitch at the final whistle.", zh: "終場哨音" },
    { front: "push yourself", pos: "collocation", def: "to make yourself work harder than usual", example: "You will never improve unless you push yourself in training.", zh: "督促自己；挑戰自我" },
    { front: "sweat", pos: "v.", def: "to lose liquid through your skin when hot or exercising", example: "He was sweating heavily by the end of the match.", zh: "流汗" },
    { front: "weightlifting", pos: "n.", def: "the sport or activity of lifting heavy weights", example: "She took up weightlifting to build her strength.", zh: "舉重" },
    { front: "treadmill", pos: "n.", def: "an exercise machine that you walk or run on", example: "I ran five kilometres on the treadmill at the gym.", zh: "跑步機" },
    { front: "underdog", pos: "n.", def: "the person or team expected to lose a competition", example: "Everyone loves it when the underdog wins the cup.", zh: "居劣勢的一方；黑馬" },
    { front: "fair play", pos: "collocation", def: "honest behaviour that follows the rules in sport", example: "The club received an award for fair play this season.", zh: "公平競賽" },
    { front: "sportsmanship", pos: "n.", def: "fair and generous behaviour when playing sport", example: "Shaking hands after the match shows good sportsmanship.", zh: "運動家精神" },
    { front: "trophy", pos: "n.", def: "a prize, such as a cup, given to the winner of a competition", example: "The captain lifted the trophy in front of the cheering crowd.", zh: "獎盃" },
    { front: "podium", pos: "n.", def: "the platform where winners stand to receive their prizes", example: "The three fastest runners stood on the podium.", zh: "頒獎台" },
    { front: "qualify", pos: "v.", def: "to reach the standard needed to enter a competition", example: "The team qualified for the World Cup for the first time.", zh: "取得資格；晉級" },
    { front: "eliminate", pos: "v.", def: "to remove someone from a competition by defeating them", example: "Our team was eliminated in the semi-finals.", zh: "淘汰" },
    // --- Environment / energy ---
    { front: "emissions", pos: "n.", def: "gases sent out into the air, especially harmful ones", example: "The government plans to cut carbon emissions by half.", zh: "排放物；廢氣" },
    { front: "greenhouse gas", pos: "collocation", def: "a gas that traps heat in the atmosphere and warms the planet", example: "Cars and factories produce large amounts of greenhouse gases.", zh: "溫室氣體" },
    { front: "carbon footprint", pos: "collocation", def: "the amount of carbon dioxide a person or activity produces", example: "Flying less is one way to reduce your carbon footprint.", zh: "碳足跡" },
    { front: "wind farm", pos: "collocation", def: "an area with many machines that use wind to make electricity", example: "A new wind farm is being built off the coast.", zh: "風力發電場" },
    { front: "fossil fuel", pos: "collocation", def: "fuel such as coal or oil formed underground over millions of years", example: "We need to stop depending on fossil fuels for energy.", zh: "化石燃料" },
    { front: "dispose of", pos: "phr. v.", def: "to get rid of something you no longer want", example: "Old batteries must be disposed of carefully.", zh: "處理掉；丟棄" },
    { front: "landfill", pos: "n.", def: "a place where rubbish is buried in the ground", example: "Most of our plastic waste ends up in landfill.", zh: "垃圾掩埋場" },
    { front: "deforestation", pos: "n.", def: "the cutting down of forests over a large area", example: "Deforestation is destroying the homes of many rare animals.", zh: "森林砍伐" },
    { front: "endangered species", pos: "collocation", def: "a type of animal or plant that may soon disappear", example: "The giant panda was an endangered species for decades.", zh: "瀕危物種" },
    { front: "wildfire", pos: "n.", def: "a fire that spreads quickly across natural land", example: "The wildfire destroyed thousands of hectares of forest.", zh: "野火" },
    { front: "ecosystem", pos: "n.", def: "all the living things in an area and how they affect each other", example: "The oil spill damaged the entire coastal ecosystem.", zh: "生態系統" },
    { front: "biodiversity", pos: "n.", def: "the variety of plants and animals in a place", example: "Tropical rainforests are famous for their rich biodiversity.", zh: "生物多樣性" },
    { front: "contaminate", pos: "v.", def: "to make something dirty or poisonous", example: "Chemicals from the factory contaminated the river.", zh: "污染" },
    { front: "exhaust fumes", pos: "collocation", def: "waste gases that come out of a vehicle", example: "Exhaust fumes from traffic make the city air unhealthy.", zh: "廢氣" },
    { front: "ozone layer", pos: "collocation", def: "the layer of gas high above the Earth that blocks harmful sunlight", example: "Certain chemicals were banned to protect the ozone layer.", zh: "臭氧層" },
    { front: "sea level", pos: "collocation", def: "the average height of the sea, used for measuring land height", example: "Rising sea levels threaten many island nations.", zh: "海平面" },
    { front: "power plant", pos: "collocation", def: "a factory that produces electricity", example: "The old coal power plant will close next year.", zh: "發電廠" },
    { front: "energy-efficient", pos: "adj.", def: "using little energy to work well", example: "We replaced all our bulbs with energy-efficient ones.", zh: "節能的" },
    { front: "insulation", pos: "n.", def: "material that stops heat escaping from a building", example: "Good insulation can cut your heating bills in half.", zh: "隔熱（材料）" },
    { front: "use up", pos: "phr. v.", def: "to finish a supply of something completely", example: "We have used up all the hot water again.", zh: "用完；耗盡" },
    { front: "environmentally friendly", pos: "collocation", def: "not harmful to the natural world", example: "The company switched to environmentally friendly packaging.", zh: "環保的" },
    { front: "go green", pos: "idiom", def: "to change your habits to protect the environment", example: "Our office went green by banning plastic cups.", zh: "走環保路線" },
    { front: "natural resources", pos: "collocation", def: "materials such as water, wood and oil that exist in nature", example: "The country is rich in natural resources like gas and timber.", zh: "天然資源" },
    { front: "scarce", pos: "adj.", def: "existing only in small amounts; not enough", example: "Clean water is becoming scarce in many regions.", zh: "稀少的；短缺的" },
    { front: "plentiful", pos: "adj.", def: "existing in large amounts; more than enough", example: "Fish were plentiful in the river before the pollution.", zh: "豐富的" },
    { front: "harmful", pos: "adj.", def: "causing damage or injury", example: "Too much sun can be harmful to your skin.", zh: "有害的" },
    { front: "eco-friendly", pos: "adj.", def: "designed to cause little damage to the environment", example: "They sell eco-friendly cleaning products made from plants.", zh: "環保的；生態友善的" },
    { front: "smog", pos: "n.", def: "dirty air that looks like a mixture of smoke and fog", example: "The city was covered in thick smog for days.", zh: "霧霾" },
    { front: "acid rain", pos: "collocation", def: "rain containing harmful chemicals from pollution", example: "Acid rain has damaged forests across the region.", zh: "酸雨" },
    { front: "oil spill", pos: "collocation", def: "an accident in which oil escapes into the sea", example: "Volunteers helped clean birds affected by the oil spill.", zh: "漏油事件" },
    { front: "toxic waste", pos: "collocation", def: "poisonous material left over from industry", example: "The company was fined for dumping toxic waste in the river.", zh: "有毒廢棄物" },
    { front: "sewage", pos: "n.", def: "waste water and material carried away from buildings in pipes", example: "Untreated sewage was flowing straight into the sea.", zh: "污水" },
    { front: "scarcity", pos: "n.", def: "a situation in which there is not enough of something", example: "Water scarcity is a growing problem in the south.", zh: "短缺；匱乏" },
    { front: "preservation", pos: "n.", def: "the act of keeping something safe from harm or change", example: "The charity works for the preservation of historic buildings.", zh: "保存；保護" },
    { front: "poaching", pos: "n.", def: "the illegal hunting of animals", example: "Poaching has reduced the elephant population dramatically.", zh: "盜獵" },
    { front: "overfishing", pos: "n.", def: "catching so many fish that few are left in the sea", example: "Overfishing has left some species close to extinction.", zh: "過度捕撈" },
    { front: "single-use", pos: "adj.", def: "designed to be used once and then thrown away", example: "Many shops no longer give out single-use plastic bags.", zh: "一次性使用的" },
    { front: "reusable", pos: "adj.", def: "able to be used again", example: "I always carry a reusable water bottle in my bag.", zh: "可重複使用的" },
    { front: "biodegradable", pos: "adj.", def: "able to decay naturally without harming the environment", example: "The cups are biodegradable and break down within weeks.", zh: "可生物分解的" },
    { front: "compost", pos: "n.", def: "decayed plant material used to improve soil", example: "We turn our kitchen waste into compost for the garden.", zh: "堆肥" },
    { front: "organic farming", pos: "collocation", def: "growing food without artificial chemicals", example: "Organic farming avoids the use of chemical sprays.", zh: "有機農業" },
    { front: "pesticide", pos: "n.", def: "a chemical used to kill insects that damage crops", example: "Wash the fruit carefully to remove any pesticides.", zh: "殺蟲劑；農藥" },
    { front: "fertiliser", pos: "n.", def: "a substance added to soil to help plants grow", example: "Too much fertiliser can pollute nearby rivers.", zh: "肥料" },
    { front: "irrigation", pos: "n.", def: "supplying water to land so crops can grow", example: "The new irrigation system doubled the farm's harvest.", zh: "灌溉" },
    { front: "ice cap", pos: "collocation", def: "a thick layer of ice permanently covering an area", example: "The polar ice caps are melting faster than expected.", zh: "冰帽；冰蓋" },
    { front: "carbon dioxide", pos: "collocation", def: "the gas produced when fuel is burned or when we breathe out", example: "Trees absorb carbon dioxide from the atmosphere.", zh: "二氧化碳" },
    { front: "carbon neutral", pos: "collocation", def: "not adding more carbon to the atmosphere than is removed", example: "The airline promises to become carbon neutral by 2050.", zh: "碳中和" },
    { front: "energy crisis", pos: "collocation", def: "a serious shortage of fuel or electricity", example: "The energy crisis forced families to cut back on heating.", zh: "能源危機" },
    { front: "hydroelectric", pos: "adj.", def: "producing electricity from the power of moving water", example: "The dam provides hydroelectric power for the whole valley.", zh: "水力發電的" },
    { front: "wind turbine", pos: "collocation", def: "a tall machine with blades that produces electricity from wind", example: "Dozens of wind turbines line the hills above the town.", zh: "風力渦輪機" },
    { front: "electric vehicle", pos: "collocation", def: "a car or other vehicle powered by electricity", example: "Sales of electric vehicles have doubled in the past year.", zh: "電動車" },
    { front: "save the planet", pos: "collocation", def: "to protect the Earth from environmental damage", example: "Small daily choices can help save the planet.", zh: "拯救地球" },
    { front: "environmental impact", pos: "collocation", def: "the effect that an activity has on the natural world", example: "The airport must study the environmental impact of the new runway.", zh: "環境影響" },
    // --- Shopping / consumer ---
    { front: "warranty", pos: "n.", def: "a written promise to repair or replace a faulty product", example: "The laptop comes with a two-year warranty.", zh: "保固" },
    { front: "faulty", pos: "adj.", def: "not working correctly; having a defect", example: "I returned the kettle because it was faulty.", zh: "有瑕疵的；故障的" },
    { front: "exchange", pos: "v.", def: "to return something and get another in its place", example: "Can I exchange this shirt for a larger size?", zh: "交換；換貨" },
    { front: "complaint", pos: "n.", def: "a statement saying you are unhappy about something", example: "She made a complaint about the rude shop assistant.", zh: "投訴；抱怨" },
    { front: "customer service", pos: "collocation", def: "the help a company gives people who buy its products", example: "I phoned customer service to ask about my order.", zh: "客服" },
    { front: "checkout", pos: "n.", def: "the place in a shop where you pay", example: "There was a long queue at the checkout.", zh: "結帳處" },
    { front: "till", pos: "n.", def: "the machine in a shop where money is kept", example: "The cashier opened the till and gave me my change.", zh: "收銀機" },
    { front: "queue", pos: "n.", def: "a line of people waiting for something", example: "We stood in the queue for almost an hour.", zh: "隊伍；排隊" },
    { front: "window shopping", pos: "collocation", def: "looking at goods in shops without buying anything", example: "We spent the afternoon window shopping in the city centre.", zh: "逛街看櫥窗（不買）" },
    { front: "wholesale", pos: "adj.", def: "relating to selling goods in large amounts to shops", example: "The restaurant buys its vegetables at wholesale prices.", zh: "批發的" },
    { front: "brand", pos: "n.", def: "a product made by a particular company under a name", example: "Which brand of coffee do you usually buy?", zh: "品牌" },
    { front: "label", pos: "n.", def: "a piece of paper on a product giving information about it", example: "Check the label to see where the shirt was made.", zh: "標籤" },
    { front: "logo", pos: "n.", def: "a symbol used by a company to identify its products", example: "The sports company's logo is recognised all over the world.", zh: "商標；標誌" },
    { front: "commercial", pos: "n.", def: "an advertisement on television or radio", example: "The commercial for the new phone was everywhere last month.", zh: "（電視）廣告" },
    { front: "afford", pos: "v.", def: "to have enough money to buy something", example: "We simply cannot afford a new car this year.", zh: "負擔得起" },
    { front: "overpriced", pos: "adj.", def: "costing more than it is really worth", example: "The food at that café is nice but seriously overpriced.", zh: "定價過高的" },
    { front: "reasonable price", pos: "collocation", def: "a price that is fair and not too high", example: "The hotel offers comfortable rooms at a reasonable price.", zh: "合理的價格" },
    { front: "rip-off", pos: "n.", def: "something that costs far too much money", example: "Ten pounds for a coffee? What a rip-off!", zh: "敲竹槓；坑人的東西" },
    { front: "special offer", pos: "collocation", def: "a temporary lower price to attract buyers", example: "The supermarket has a special offer on cheese this week.", zh: "特價優惠" },
    { front: "in stock", pos: "collocation", def: "available to buy in a shop now", example: "Luckily, the shoes I wanted were still in stock.", zh: "有現貨" },
    { front: "out of stock", pos: "collocation", def: "not available in a shop at the moment", example: "Sorry, that game is out of stock until next week.", zh: "缺貨" },
    { front: "delivery", pos: "n.", def: "the act of bringing goods to a person or place", example: "The shop offers free delivery on orders over fifty pounds.", zh: "送貨；遞送" },
    { front: "impulse buy", pos: "collocation", def: "something bought suddenly without planning", example: "The chocolate at the checkout was a classic impulse buy.", zh: "衝動購物" },
    { front: "loyalty card", pos: "collocation", def: "a card that gives regular customers rewards or discounts", example: "I collected enough points on my loyalty card for a free coffee.", zh: "會員集點卡" },
    { front: "shopping spree", pos: "collocation", def: "a short period of buying many things", example: "She went on a shopping spree after getting her bonus.", zh: "瘋狂購物" },
    { front: "cost a fortune", pos: "idiom", def: "to be extremely expensive", example: "Repairing the roof is going to cost a fortune.", zh: "花一大筆錢" },
    { front: "flea market", pos: "collocation", def: "an outdoor market selling old or used goods", example: "I found this antique lamp at a flea market for five euros.", zh: "跳蚤市場" },
    { front: "street market", pos: "collocation", def: "a market with stalls in a street or square", example: "The street market sells fresh fruit every Saturday morning.", zh: "街頭市集" },
    { front: "stall", pos: "n.", def: "a small open shop or table where goods are sold", example: "We bought handmade jewellery from a stall at the fair.", zh: "攤位" },
    { front: "cashier", pos: "n.", def: "the person who takes payments in a shop or bank", example: "The cashier asked if I wanted a receipt.", zh: "收銀員" },
    { front: "pay in instalments", pos: "collocation", def: "to pay for something in several smaller amounts over time", example: "We paid for the sofa in twelve monthly instalments.", zh: "分期付款" },
    { front: "voucher", pos: "n.", def: "a printed ticket that can be used instead of money", example: "I got a twenty-pound gift voucher for my birthday.", zh: "禮券；抵用券" },
    { front: "price tag", pos: "collocation", def: "a label showing how much something costs", example: "There was no price tag on the jacket, so I asked an assistant.", zh: "價格標籤" },
    { front: "trolley", pos: "n.", def: "a large basket on wheels used in supermarkets", example: "He filled the trolley with food for the whole week.", zh: "購物推車" },
    { front: "counterfeit", pos: "adj.", def: "made to look real in order to deceive people; fake", example: "Police seized thousands of counterfeit designer handbags.", zh: "偽造的；仿冒的" },
    { front: "durable", pos: "adj.", def: "strong and lasting a long time", example: "These boots are expensive but extremely durable.", zh: "耐用的" },
    { front: "long-lasting", pos: "adj.", def: "continuing or working for a long time", example: "The advert promises long-lasting battery life.", zh: "持久的" },
    { front: "mass-produced", pos: "adj.", def: "made in large numbers by machines in factories", example: "Mass-produced furniture is cheaper but less unique.", zh: "大量生產的" },
    { front: "handmade", pos: "adj.", def: "made by hand rather than by machine", example: "Each handmade chocolate is slightly different.", zh: "手工製的" },
    { front: "luxury goods", pos: "collocation", def: "expensive products that are pleasant but not necessary", example: "The airport shops are full of luxury goods like perfume and watches.", zh: "奢侈品" },
    { front: "snap up", pos: "phr. v.", def: "to buy something quickly because it is cheap or rare", example: "Shoppers snapped up the discounted televisions within an hour.", zh: "搶購" },
    { front: "queue up", pos: "phr. v.", def: "to stand in a line waiting for something", example: "Fans queued up overnight to buy tickets for the concert.", zh: "排隊" },
    { front: "take back", pos: "phr. v.", def: "to return something you bought to the shop", example: "If the shirt does not fit, you can take it back within thirty days.", zh: "退回（商品）" },
    { front: "money-back guarantee", pos: "collocation", def: "a promise to return your money if you are not satisfied", example: "The mattress comes with a hundred-day money-back guarantee.", zh: "退款保證" },
    { front: "free of charge", pos: "collocation", def: "without any payment; free", example: "Repairs are carried out free of charge during the first year.", zh: "免費" },
    { front: "on a budget", pos: "collocation", def: "with only a limited amount of money to spend", example: "The guidebook is perfect for travellers on a budget.", zh: "預算有限" },
    { front: "in the sales", pos: "collocation", def: "during the period when shops reduce their prices", example: "I bought this coat for half price in the sales.", zh: "在特賣期間" },
    { front: "half price", pos: "collocation", def: "at fifty percent of the usual cost", example: "Children's tickets are half price on weekdays.", zh: "半價" },
    // --- Celebrations / traditions ---
    { front: "anniversary", pos: "n.", def: "the date on which something important happened in a past year", example: "They celebrated their twentieth wedding anniversary in Paris.", zh: "週年紀念日" },
    { front: "ceremony", pos: "n.", def: "a formal event held on an important occasion", example: "The graduation ceremony lasted over two hours.", zh: "典禮；儀式" },
    { front: "festival", pos: "n.", def: "a special day or period of public celebration", example: "The town holds a music festival every August.", zh: "節慶；音樂節" },
    { front: "parade", pos: "n.", def: "a public procession of people celebrating something", example: "Thousands watched the carnival parade pass through the streets.", zh: "遊行" },
    { front: "fireworks", pos: "n.", def: "explosives that make coloured lights and noise in the sky", example: "The fireworks lit up the sky at midnight.", zh: "煙火" },
    { front: "decoration", pos: "n.", def: "something attractive put up for a special occasion", example: "We put up the Christmas decorations in early December.", zh: "裝飾（品）" },
    { front: "feast", pos: "n.", def: "a large special meal for many people", example: "The wedding ended with a huge feast for two hundred guests.", zh: "盛宴" },
    { front: "toast", pos: "n.", def: "the act of raising glasses to wish someone success or happiness", example: "The best man proposed a toast to the happy couple.", zh: "敬酒；祝酒" },
    { front: "reception", pos: "n.", def: "a formal party to welcome people or celebrate an event", example: "The wedding reception was held in a beautiful old hotel.", zh: "婚宴；歡迎會" },
    { front: "bride", pos: "n.", def: "a woman on her wedding day", example: "The bride wore a dress that had belonged to her grandmother.", zh: "新娘" },
    { front: "groom", pos: "n.", def: "a man on his wedding day", example: "The groom looked nervous as he waited at the altar.", zh: "新郎" },
    { front: "honeymoon", pos: "n.", def: "a holiday taken by a couple who have just got married", example: "They spent their honeymoon on a Greek island.", zh: "蜜月" },
    { front: "funeral", pos: "n.", def: "a ceremony for burying or cremating a dead person", example: "Hundreds of people attended the funeral of the popular teacher.", zh: "喪禮" },
    { front: "christening", pos: "n.", def: "a Christian ceremony in which a baby is given a name", example: "The whole family gathered for the baby's christening.", zh: "受洗命名儀式" },
    { front: "housewarming", pos: "n.", def: "a party held when someone moves into a new home", example: "They invited the neighbours to their housewarming party.", zh: "喬遷派對" },
    { front: "get-together", pos: "n.", def: "an informal meeting or small party", example: "We are having a little get-together on Friday evening.", zh: "小聚會" },
    { front: "reunion", pos: "n.", def: "a meeting of people who have not seen each other for a long time", example: "Our school reunion is held every five years.", zh: "重聚；同學會" },
    { front: "celebrate", pos: "v.", def: "to do something enjoyable for a special occasion", example: "How are you going to celebrate passing your exams?", zh: "慶祝" },
    { front: "commemorate", pos: "v.", def: "to remember and honour an important person or event", example: "A statue was built to commemorate the town's founder.", zh: "紀念" },
    { front: "tradition", pos: "n.", def: "a custom or belief passed from one generation to the next", example: "It is a family tradition to open one present on Christmas Eve.", zh: "傳統" },
    { front: "ritual", pos: "n.", def: "a set of actions always done in the same way, often for religion", example: "Lighting the candles is an important part of the ritual.", zh: "儀式" },
    { front: "folklore", pos: "n.", def: "the traditional stories and beliefs of a community", example: "According to local folklore, a dragon once lived in the lake.", zh: "民間傳說" },
    { front: "national holiday", pos: "collocation", def: "a day when most people in a country do not work", example: "The museum is closed on national holidays.", zh: "國定假日" },
    { front: "throw a party", pos: "collocation", def: "to organise a party", example: "We are throwing a party for Dad's sixtieth birthday.", zh: "舉辦派對" },
    { front: "blow out candles", pos: "collocation", def: "to put out candle flames with your breath, as on a birthday cake", example: "Make a wish before you blow out the candles!", zh: "吹熄蠟燭" },
    { front: "exchange gifts", pos: "collocation", def: "to give presents to each other", example: "In our family we exchange gifts on Christmas morning.", zh: "交換禮物" },
    { front: "mark the occasion", pos: "collocation", def: "to do something special to celebrate an event", example: "They planted a tree to mark the occasion of the school's centenary.", zh: "紀念這個時刻" },
    { front: "bridesmaid", pos: "n.", def: "a woman or girl who helps the bride at a wedding", example: "Her three best friends were bridesmaids at the wedding.", zh: "伴娘" },
    { front: "best man", pos: "collocation", def: "the male friend who helps the groom at a wedding", example: "The best man gave a very funny speech at the reception.", zh: "伴郎" },
    { front: "bonfire", pos: "n.", def: "a large outdoor fire for burning rubbish or for celebration", example: "We gathered around the bonfire and sang songs.", zh: "營火；篝火" },
    { front: "lantern", pos: "n.", def: "a light inside a container that you can carry or hang", example: "Paper lanterns floated into the night sky during the festival.", zh: "燈籠" },
    { front: "procession", pos: "n.", def: "a line of people or vehicles moving slowly as part of a ceremony", example: "The procession moved slowly through the old town.", zh: "隊伍；遊行行列" },
    { front: "carnival", pos: "n.", def: "a public celebration with music, dancing and costumes", example: "The streets fill with dancers during the carnival in February.", zh: "嘉年華" },
    { front: "fancy dress", pos: "collocation", def: "unusual clothes worn for fun to look like someone else", example: "Everyone came to the Halloween party in fancy dress.", zh: "變裝服裝" },
    { front: "confetti", pos: "n.", def: "small pieces of coloured paper thrown at celebrations", example: "Guests threw confetti as the couple left the church.", zh: "五彩碎紙" },
    { front: "banquet", pos: "n.", def: "a large formal meal for many people", example: "A banquet was held in honour of the visiting president.", zh: "宴會" },
    { front: "countdown", pos: "n.", def: "the act of counting backwards to zero before an event", example: "The crowd joined in the countdown to midnight.", zh: "倒數計時" },
    { front: "pass down", pos: "phr. v.", def: "to give something to a younger generation", example: "The recipe has been passed down from mother to daughter for a century.", zh: "傳承；代代相傳" },
    // --- Verbs of movement ---
    { front: "stroll", pos: "v.", def: "to walk slowly in a relaxed way", example: "We strolled along the beach at sunset.", zh: "漫步" },
    { front: "stride", pos: "v.", def: "to walk with long, confident steps", example: "She strode into the office and demanded an explanation.", zh: "大步走" },
    { front: "dash", pos: "v.", def: "to run somewhere very quickly", example: "He dashed across the road to catch the bus.", zh: "猛衝" },
    { front: "crawl", pos: "v.", def: "to move on your hands and knees", example: "The baby crawled across the carpet towards the toy.", zh: "爬行" },
    { front: "creep", pos: "v.", def: "to move slowly and quietly to avoid being noticed", example: "We crept upstairs so as not to wake the children.", zh: "躡手躡腳地走" },
    { front: "leap", pos: "v.", def: "to jump high or a long distance", example: "The cat leapt from the wall onto the roof.", zh: "跳躍" },
    { front: "hop", pos: "v.", def: "to jump on one foot, or to make small jumps", example: "The children hopped across the playground on one leg.", zh: "單腳跳；跳" },
    { front: "skip", pos: "v.", def: "to move with light jumping steps", example: "The little girl skipped happily down the path.", zh: "蹦蹦跳跳" },
    { front: "stagger", pos: "v.", def: "to walk unsteadily, almost falling", example: "He staggered to the sofa and collapsed, exhausted.", zh: "蹣跚；搖晃地走" },
    { front: "march", pos: "v.", def: "to walk with regular firm steps, like a soldier", example: "The protesters marched through the city centre.", zh: "行進；遊行" },
    { front: "rush", pos: "v.", def: "to move or do something very quickly", example: "There is no need to rush - we have plenty of time.", zh: "趕忙；衝" },
    { front: "drift", pos: "v.", def: "to move slowly, carried by water or air", example: "The empty boat drifted out to sea.", zh: "漂流；飄移" },
    { front: "slide", pos: "v.", def: "to move smoothly over a surface", example: "The children were sliding on the frozen pond.", zh: "滑行" },
    { front: "slip", pos: "v.", def: "to lose your balance on a smooth or wet surface", example: "She slipped on the icy pavement and hurt her wrist.", zh: "滑倒" },
    { front: "climb over", pos: "phr. v.", def: "to get across something by going up and over it", example: "The boys climbed over the fence into the orchard.", zh: "翻越" },
    { front: "sneak", pos: "v.", def: "to go somewhere quietly and secretly", example: "He sneaked out of the meeting before it finished.", zh: "偷偷地走" },
    { front: "tiptoe", pos: "v.", def: "to walk quietly on your toes", example: "She tiptoed past the sleeping dog.", zh: "踮腳走" },
    { front: "wade", pos: "v.", def: "to walk through water with effort", example: "We had to wade across the stream to reach the path.", zh: "涉水" },
    { front: "bounce", pos: "v.", def: "to move up and down after hitting a surface", example: "The ball bounced twice before going over the line.", zh: "彈跳" },
    { front: "swing", pos: "v.", def: "to move backwards and forwards while hanging", example: "The monkey swung from branch to branch.", zh: "擺盪" },
    { front: "sway", pos: "v.", def: "to move slowly from side to side", example: "The trees swayed gently in the evening breeze.", zh: "搖曳；搖擺" },
    { front: "spin", pos: "v.", def: "to turn around quickly in circles", example: "The dancer spun gracefully across the stage.", zh: "旋轉" },
    { front: "whirl", pos: "v.", def: "to turn or spin around very fast", example: "Leaves whirled around the garden in the strong wind.", zh: "急速旋轉" },
    { front: "plunge", pos: "v.", def: "to fall or jump suddenly downwards, often into water", example: "She plunged into the cold lake without hesitating.", zh: "縱身跳入；驟降" },
    { front: "trip over", pos: "phr. v.", def: "to hit your foot on something and almost fall", example: "I tripped over the cat in the dark hallway.", zh: "絆倒" },
    { front: "swerve", pos: "v.", def: "to change direction suddenly, especially in a vehicle", example: "The driver swerved to avoid a dog in the road.", zh: "急轉彎" },
    { front: "dodge", pos: "v.", def: "to move quickly to avoid being hit", example: "He dodged the snowball just in time.", zh: "閃避" },
    { front: "chase", pos: "v.", def: "to run after someone or something to catch them", example: "The dog chased the rabbit across the field.", zh: "追逐" },
    { front: "flee", pos: "v.", def: "to run away from danger", example: "Thousands of people fled the city before the storm arrived.", zh: "逃離" },
    { front: "wander off", pos: "phr. v.", def: "to walk away from where you should be", example: "One of the children wandered off during the museum tour.", zh: "走失；亂跑" },
    { front: "make for", pos: "phr. v.", def: "to move towards a place", example: "As soon as the rain started, we made for the nearest café.", zh: "朝……走去" },
    { front: "back away", pos: "phr. v.", def: "to move backwards away from something frightening", example: "She backed away slowly from the growling dog.", zh: "後退；退避" },
    // --- Verbs of speech ---
    { front: "mumble", pos: "v.", def: "to speak quietly and unclearly", example: "He mumbled an apology and left the room.", zh: "含糊地說" },
    { front: "yell", pos: "v.", def: "to shout loudly", example: "The coach yelled instructions from the side of the pitch.", zh: "大喊" },
    { front: "scream", pos: "v.", def: "to cry out loudly in fear, pain or excitement", example: "The fans screamed when the singer appeared on stage.", zh: "尖叫" },
    { front: "murmur", pos: "v.", def: "to say something very quietly and softly", example: "She murmured a few words of thanks and sat down.", zh: "低聲說" },
    { front: "stammer", pos: "v.", def: "to speak with pauses and repeated sounds, often from nerves", example: "He was so nervous that he stammered through his speech.", zh: "結巴地說" },
    { front: "exclaim", pos: "v.", def: "to say something suddenly with strong feeling", example: "What a wonderful surprise! she exclaimed.", zh: "驚呼" },
    { front: "admit", pos: "v.", def: "to agree, often unwillingly, that something is true", example: "He finally admitted that he had broken the window.", zh: "承認" },
    { front: "boast", pos: "v.", def: "to talk too proudly about what you have or can do", example: "She is always boasting about her expensive holidays.", zh: "吹噓" },
    { front: "complain", pos: "v.", def: "to say that you are unhappy or dissatisfied about something", example: "The guests complained about the noise from the building site.", zh: "抱怨" },
    { front: "chat away", pos: "phr. v.", def: "to talk continuously in a friendly way", example: "The two old friends chatted away for hours.", zh: "聊個不停" },
    { front: "talk over", pos: "phr. v.", def: "to discuss a problem or plan carefully", example: "Let's talk over the details before we sign anything.", zh: "商量；討論" },
    { front: "blurt out", pos: "phr. v.", def: "to say something suddenly without thinking", example: "He blurted out the secret before he could stop himself.", zh: "脫口而出" },
    { front: "cry out", pos: "phr. v.", def: "to shout suddenly because of pain or surprise", example: "She cried out in pain when she twisted her ankle.", zh: "大聲喊叫" },
    { front: "burst out", pos: "phr. v.", def: "to suddenly start laughing, crying or speaking", example: "Everyone burst out laughing at his joke.", zh: "突然（大笑／大哭）" },
    { front: "groan", pos: "v.", def: "to make a long low sound of pain or unhappiness", example: "The students groaned when the teacher announced a test.", zh: "呻吟；哀嘆" },
    { front: "moan", pos: "v.", def: "to complain in an annoying way, or make a low sound of pain", example: "Stop moaning about the weather and put a coat on.", zh: "抱怨；呻吟" },
    { front: "sigh", pos: "v.", def: "to breathe out slowly making a sound of tiredness or relief", example: "She sighed with relief when she found her passport.", zh: "嘆氣" },
    { front: "gasp", pos: "v.", def: "to take a quick deep breath from surprise or shock", example: "The audience gasped when the magician disappeared.", zh: "倒抽一口氣" },
    { front: "grumble", pos: "v.", def: "to complain quietly in a bad-tempered way", example: "He grumbled about the price but paid anyway.", zh: "發牢騷" },
    { front: "chatter", pos: "v.", def: "to talk quickly about unimportant things", example: "The children chattered excitedly on the way to the zoo.", zh: "喋喋不休" },
    { front: "plead", pos: "v.", def: "to ask for something in an emotional, urgent way", example: "She pleaded with her parents to let her go to the concert.", zh: "懇求" },
    { front: "urge", pos: "v.", def: "to strongly advise someone to do something", example: "Doctors urge people to take regular exercise.", zh: "力勸；敦促" },
    { front: "butt in", pos: "phr. v.", def: "to interrupt a conversation rudely", example: "Sorry to butt in, but I think you have got the wrong address.", zh: "插嘴" },
    { front: "go on about", pos: "phr. v.", def: "to talk about something for too long in a boring way", example: "He is always going on about his new car.", zh: "喋喋不休地講" },
    { front: "ramble", pos: "v.", def: "to talk for a long time without a clear point", example: "The professor tends to ramble, so take notes carefully.", zh: "漫無邊際地說" },
    { front: "raise your voice", pos: "collocation", def: "to speak more loudly, often because you are angry", example: "There is no need to raise your voice - I can hear you perfectly.", zh: "提高音量" },
    { front: "drop a hint", pos: "collocation", def: "to suggest something indirectly", example: "She dropped a hint that she would love flowers for her birthday.", zh: "暗示" },
    { front: "have a word with", pos: "collocation", def: "to speak to someone briefly, often about a problem", example: "Could I have a word with you about yesterday's meeting?", zh: "和……談一談" },
    { front: "get to the point", pos: "idiom", def: "to say the most important thing directly", example: "Stop wasting time and get to the point.", zh: "直說重點" },
    { front: "beat around the bush", pos: "idiom", def: "to avoid talking about something directly", example: "Stop beating around the bush and tell me what happened.", zh: "拐彎抹角" },
    { front: "spell out", pos: "phr. v.", def: "to explain something very clearly and in detail", example: "The teacher spelled out exactly what the exam would include.", zh: "詳細說明" },
    // --- Adjectives / adverbs of quantity and degree ---
    { front: "abundant", pos: "adj.", def: "existing in very large amounts", example: "The region has abundant supplies of fresh water.", zh: "豐富的；充足的" },
    { front: "numerous", pos: "adj.", def: "many; a large number of", example: "We have received numerous complaints about the noise.", zh: "許多的" },
    { front: "considerable", pos: "adj.", def: "large in amount or degree", example: "The project will require a considerable amount of money.", zh: "相當大的" },
    { front: "substantial", pos: "adj.", def: "large in size, value or importance", example: "She was given a substantial pay rise last month.", zh: "大量的；可觀的" },
    { front: "moderate", pos: "adj.", def: "average in amount; neither large nor small", example: "The medicine should be taken with a moderate amount of food.", zh: "適度的；中等的" },
    { front: "minimal", pos: "adj.", def: "very small in amount", example: "The storm caused only minimal damage to the village.", zh: "極小的；最低限度的" },
    { front: "excessive", pos: "adj.", def: "much more than is reasonable or necessary", example: "Excessive use of your phone can affect your sleep.", zh: "過度的" },
    { front: "sufficient", pos: "adj.", def: "as much as is needed; enough", example: "Make sure you have sufficient time to finish the paper.", zh: "足夠的" },
    { front: "insufficient", pos: "adj.", def: "not enough", example: "The project failed because of insufficient funding.", zh: "不足的" },
    { front: "immense", pos: "adj.", def: "extremely large", example: "Winning the award gave her immense satisfaction.", zh: "巨大的" },
    { front: "tremendous", pos: "adj.", def: "very great in amount or extremely good", example: "The new bridge was a tremendous achievement of engineering.", zh: "極大的；極好的" },
    { front: "slight", pos: "adj.", def: "small in degree; not serious", example: "There has been a slight improvement in his condition.", zh: "輕微的" },
    { front: "gradual", pos: "adj.", def: "happening slowly over a period of time", example: "We noticed a gradual change in the climate over the years.", zh: "逐漸的" },
    { front: "dramatic", pos: "adj.", def: "sudden and very noticeable", example: "There has been a dramatic fall in the number of visitors.", zh: "劇烈的；戲劇性的" },
    { front: "steady", pos: "adj.", def: "developing or happening at a regular, continuous rate", example: "The company has shown steady growth for five years.", zh: "穩定的" },
    { front: "approximate", pos: "adj.", def: "close to a particular number but not exact", example: "The approximate cost of the trip is five hundred euros.", zh: "大約的" },
    { front: "entire", pos: "adj.", def: "whole or complete", example: "The entire class passed the exam this year.", zh: "整個的；全部的" },
    { front: "countless", pos: "adj.", def: "too many to be counted", example: "She has helped countless students over her long career.", zh: "無數的" },
    { front: "plenty of", pos: "collocation", def: "a large amount; more than enough", example: "Don't worry, there is plenty of food for everyone.", zh: "大量的；充足的" },
    { front: "a great deal of", pos: "collocation", def: "a large amount of something", example: "The renovation took a great deal of time and effort.", zh: "大量的" },
    { front: "a handful of", pos: "collocation", def: "a very small number of people or things", example: "Only a handful of students turned up to the lecture.", zh: "少數的" },
    { front: "dozens of", pos: "collocation", def: "a lot of; many (literally, groups of twelve)", example: "Dozens of fans waited outside the stadium for autographs.", zh: "許多；幾十個" },
    { front: "barely", pos: "adv.", def: "only just; almost not", example: "I could barely hear her over the loud music.", zh: "幾乎不；勉強" },
    { front: "hardly", pos: "adv.", def: "almost not at all", example: "There was hardly anyone in the cinema on Monday night.", zh: "幾乎不" },
    { front: "roughly", pos: "adv.", def: "approximately; not exactly", example: "The journey takes roughly three hours by train.", zh: "大約" },
    { front: "virtually", pos: "adv.", def: "almost; very nearly", example: "The two products are virtually identical.", zh: "幾乎；實際上" },
    { front: "utterly", pos: "adv.", def: "completely; totally", example: "I was utterly exhausted after the long flight.", zh: "完全地；徹底地" },
    { front: "fairly", pos: "adv.", def: "to some degree, but not very", example: "The test was fairly easy compared to last year's.", zh: "相當；還算" },
    { front: "rather", pos: "adv.", def: "to a noticeable degree; quite", example: "It is rather cold today, so take a jacket.", zh: "相當；頗為" },
    { front: "extremely", pos: "adv.", def: "to a very high degree", example: "The final question was extremely difficult.", zh: "極其" },
    { front: "somewhat", pos: "adv.", def: "to a small degree; slightly", example: "The results were somewhat disappointing.", zh: "有點；稍微" },
    { front: "adequate", pos: "adj.", def: "good enough or big enough for a purpose", example: "The room was small but adequate for one person.", zh: "足夠的；尚可的" },
    { front: "ample", pos: "adj.", def: "more than enough", example: "There is ample parking space behind the hotel.", zh: "充裕的" },
    { front: "sheer", pos: "adj.", def: "complete; used to emphasise size or degree", example: "The sheer size of the mountain took my breath away.", zh: "全然的；純粹的" },
    { front: "mere", pos: "adj.", def: "used to emphasise how small or unimportant something is", example: "He won the race by a mere two seconds.", zh: "僅僅的" },
    { front: "drastic", pos: "adj.", def: "extreme and sudden, with strong effects", example: "The company took drastic measures to avoid bankruptcy.", zh: "激烈的；極端的" },
    { front: "intense", pos: "adj.", def: "very strong or extreme", example: "The intense heat made it impossible to work outside.", zh: "強烈的" },
    { front: "loads of", pos: "collocation", def: "a lot of (informal)", example: "There were loads of people at the festival this year.", zh: "很多（口語）" },
    { front: "the vast majority", pos: "collocation", def: "nearly all of a group", example: "The vast majority of students supported the new timetable.", zh: "絕大多數" },
    { front: "next to nothing", pos: "idiom", def: "almost nothing; a very small amount", example: "I bought this jacket for next to nothing at the market.", zh: "幾乎不用錢；微乎其微" },
    { front: "more or less", pos: "idiom", def: "approximately; almost", example: "The painting is finished, more or less.", zh: "差不多；大致上" },
    { front: "to some extent", pos: "collocation", def: "partly; in some degree", example: "I agree with you to some extent, but not completely.", zh: "在某種程度上" },
    { front: "by far", pos: "collocation", def: "by a great amount; clearly", example: "This is by far the best pizza in town.", zh: "顯然；……得多" },
    { front: "altogether", pos: "adv.", def: "completely; in total", example: "The trip cost us three hundred pounds altogether.", zh: "總共；完全" },
    { front: "entirely", pos: "adv.", def: "completely; in every way", example: "That is an entirely different question.", zh: "完全地" },
    { front: "thoroughly", pos: "adv.", def: "completely and carefully", example: "Wash your hands thoroughly before cooking.", zh: "徹底地" },
    { front: "considerably", pos: "adv.", def: "by a large amount", example: "House prices are considerably higher in the capital.", zh: "相當大地" },
    { front: "significantly", pos: "adv.", def: "in an important or noticeable way", example: "The new engine is significantly quieter than the old one.", zh: "顯著地" },
    { front: "slightly", pos: "adv.", def: "a little; by a small amount", example: "The train arrived slightly later than scheduled.", zh: "稍微" },
    { front: "increasingly", pos: "adv.", def: "more and more over time", example: "It is becoming increasingly difficult to find affordable housing.", zh: "日益；越來越" },
    // --- Time expressions ---
    { front: "meanwhile", pos: "adv.", def: "during the same period; at the same time", example: "The pasta was cooking; meanwhile, I prepared the sauce.", zh: "同時；在此期間" },
    { front: "occasionally", pos: "adv.", def: "sometimes, but not often", example: "We occasionally eat out at the weekend.", zh: "偶爾" },
    { front: "frequently", pos: "adv.", def: "often; many times", example: "Trains to the airport run frequently during the day.", zh: "頻繁地" },
    { front: "rarely", pos: "adv.", def: "not often; almost never", example: "She rarely watches television these days.", zh: "很少" },
    { front: "seldom", pos: "adv.", def: "almost never; not often", example: "He seldom talks about his childhood.", zh: "鮮少" },
    { front: "constantly", pos: "adv.", def: "all the time; repeatedly", example: "My little brother is constantly asking questions.", zh: "不斷地" },
    { front: "immediately", pos: "adv.", def: "at once; without delay", example: "Please call me immediately if anything changes.", zh: "立即" },
    { front: "instantly", pos: "adv.", def: "at that exact moment", example: "I instantly recognised her voice on the phone.", zh: "立刻；馬上" },
    { front: "currently", pos: "adv.", def: "at the present time", example: "The museum is currently closed for repairs.", zh: "目前" },
    { front: "previously", pos: "adv.", def: "before the present time or event", example: "She previously worked as a nurse in Manchester.", zh: "先前" },
    { front: "formerly", pos: "adv.", def: "in the past; at an earlier time", example: "The hotel was formerly a railway station.", zh: "從前；以前" },
    { front: "shortly", pos: "adv.", def: "soon; in a short time", example: "The doctor will see you shortly.", zh: "不久；很快" },
    { front: "temporarily", pos: "adv.", def: "for a limited time only", example: "The road is temporarily closed for repairs.", zh: "暫時地" },
    { front: "permanently", pos: "adv.", def: "for ever; without ending", example: "The factory closed permanently last spring.", zh: "永久地" },
    { front: "overdue", pos: "adj.", def: "not done or returned by the expected time", example: "The library sent me a reminder about my overdue books.", zh: "逾期的" },
    { front: "in advance", pos: "collocation", def: "before a particular time or event", example: "You should book your tickets well in advance.", zh: "預先；提前" },
    { front: "on time", pos: "collocation", def: "at the arranged or correct time; not late", example: "For once, the flight departed exactly on time.", zh: "準時" },
    { front: "in time", pos: "collocation", def: "early enough; before it is too late", example: "We arrived just in time to catch the last ferry.", zh: "及時" },
    { front: "at once", pos: "collocation", def: "immediately; or at the same time", example: "The manager asked to see me at once.", zh: "立刻；同時" },
    { front: "at last", pos: "collocation", def: "finally, after a long time or delay", example: "After hours of waiting, the results were announced at last.", zh: "終於" },
    { front: "from now on", pos: "collocation", def: "starting now and continuing into the future", example: "From now on, all meetings will start at nine sharp.", zh: "從今以後" },
    { front: "for the time being", pos: "idiom", def: "for now; until the situation changes", example: "You can stay in the spare room for the time being.", zh: "暫時" },
    { front: "every now and then", pos: "idiom", def: "occasionally; sometimes", example: "Every now and then we drive out to the coast for the day.", zh: "偶爾；不時" },
    { front: "around the clock", pos: "idiom", def: "all day and all night without stopping", example: "Rescue teams worked around the clock to find survivors.", zh: "全天候；日以繼夜" },
    { front: "ahead of schedule", pos: "collocation", def: "earlier than planned", example: "The new bridge was completed ahead of schedule.", zh: "提前；超前進度" },
    { front: "behind schedule", pos: "collocation", def: "later than planned", example: "The project is already two months behind schedule.", zh: "進度落後" },
    { front: "in the meantime", pos: "collocation", def: "in the period between two events", example: "Dinner is at eight; in the meantime, help yourself to snacks.", zh: "在此期間" },
    { front: "day in day out", pos: "idiom", def: "every day for a long period, often boringly", example: "He does the same job day in day out without complaining.", zh: "日復一日" },
    { front: "time flies", pos: "idiom", def: "time seems to pass very quickly", example: "Time flies when you are enjoying yourself.", zh: "時光飛逝" },
    { front: "kill time", pos: "idiom", def: "to do something to make time pass while waiting", example: "We played cards to kill time before the flight.", zh: "打發時間" },
    { front: "take your time", pos: "idiom", def: "to do something slowly and without hurrying", example: "Take your time - the test does not start for an hour.", zh: "慢慢來" },
    { front: "on the spot", pos: "idiom", def: "immediately, at that place and moment", example: "She was offered the job on the spot.", zh: "當場" },
    { front: "over time", pos: "collocation", def: "gradually, as time passes", example: "Your pronunciation will improve over time with practice.", zh: "隨著時間" },
    { front: "run out of time", pos: "collocation", def: "to have no time left to finish something", example: "I ran out of time before the last exam question.", zh: "時間不夠用" },
    { front: "beforehand", pos: "adv.", def: "earlier; before something happens", example: "If you are coming to dinner, let me know beforehand.", zh: "事先" },
    { front: "afterwards", pos: "adv.", def: "after an event or time already mentioned", example: "We saw the film and went for pizza afterwards.", zh: "之後" },
    { front: "prompt", pos: "adj.", def: "done quickly and without delay", example: "Thank you for your prompt reply to my email.", zh: "迅速的；及時的" },
    { front: "fortnight", pos: "n.", def: "a period of two weeks", example: "We are going to Spain for a fortnight in July.", zh: "兩週" },
    { front: "in due course", pos: "idiom", def: "at the appropriate time in the future", example: "You will receive your exam results in due course.", zh: "在適當時候" },
    { front: "in no time", pos: "idiom", def: "very quickly; very soon", example: "Don't worry, we will be home in no time.", zh: "很快；一下子" },
    { front: "on the dot", pos: "idiom", def: "at exactly the stated time", example: "The lesson starts at nine on the dot.", zh: "準時；一分不差" },
    { front: "at the crack of dawn", pos: "idiom", def: "very early in the morning", example: "We set off at the crack of dawn to avoid the traffic.", zh: "一大清早" },
    { front: "once in a while", pos: "idiom", def: "occasionally; not very often", example: "Once in a while we treat ourselves to a fancy dinner.", zh: "偶爾" },
    { front: "time-consuming", pos: "adj.", def: "taking a long time to do", example: "Preparing homemade pasta is delicious but time-consuming.", zh: "耗時的" },
    { front: "last-minute", pos: "adj.", def: "done at the latest possible time", example: "We got a last-minute deal on flights to Rome.", zh: "最後一刻的" },
    { front: "long-term", pos: "adj.", def: "continuing or having an effect over a long period", example: "Smoking has serious long-term effects on your health.", zh: "長期的" },
    { front: "short-term", pos: "adj.", def: "lasting or planned for only a short period", example: "It is only a short-term solution to the housing problem.", zh: "短期的" },
    { front: "out of date", pos: "collocation", def: "old and no longer useful or correct", example: "This guidebook is out of date - half the restaurants have closed.", zh: "過時的" },
    { front: "the other day", pos: "collocation", def: "a few days ago", example: "I bumped into your sister at the market the other day.", zh: "前幾天" },
    { front: "from time to time", pos: "idiom", def: "occasionally; sometimes", example: "From time to time I still think about my old school friends.", zh: "有時；不時" },
    { front: "in the nick of time", pos: "idiom", def: "at the last possible moment", example: "The firefighters arrived in the nick of time.", zh: "在最後關頭" },
    { front: "at the eleventh hour", pos: "idiom", def: "at the very last moment", example: "The two sides reached an agreement at the eleventh hour.", zh: "在最後一刻" },
    { front: "before long", pos: "collocation", def: "soon; in a short time", example: "Keep practising and before long you will play beautifully.", zh: "不久之後" },
    { front: "take ages", pos: "idiom", def: "to take a very long time", example: "The bus took ages to arrive this morning.", zh: "花很長時間" },
    { front: "fly by", pos: "phr. v.", def: "to pass very quickly, used about time", example: "The summer holidays always fly by too fast.", zh: "（時間）飛逝" },
    { front: "so far", pos: "collocation", def: "until now; up to this moment", example: "So far, nobody has complained about the new system.", zh: "到目前為止" }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
