/* FCE Prep extra bank: vocab wave 2 */
(function () {
  var BANK = [
    { front: "athlete", pos: "n.", def: "a person who is good at sports and competes in them", example: "The athlete trained six days a week before the games.", zh: "運動員" },
    { front: "opponent", pos: "n.", def: "the person or team you compete against", example: "She shook hands with her opponent after the match.", zh: "對手" },
    { front: "referee", pos: "n.", def: "the person who controls a sports match and makes sure the rules are followed", example: "The referee showed the defender a yellow card.", zh: "裁判" },
    { front: "spectator", pos: "n.", def: "a person who watches a sports event or show", example: "Thousands of spectators cheered as the runners crossed the line.", zh: "觀眾" },
    { front: "tournament", pos: "n.", def: "a competition with many players or teams and several rounds", example: "Our school tennis tournament takes place every June.", zh: "錦標賽" },
    { front: "championship", pos: "n.", def: "a competition to find the best player or team in a sport", example: "They won the national basketball championship last year.", zh: "冠軍賽；錦標賽" },
    { front: "defeat", pos: "n.", def: "a loss in a game, battle or competition", example: "It was their third defeat in a row this season.", zh: "失敗；戰敗" },
    { front: "victory", pos: "n.", def: "success in a game, competition or war", example: "The fans celebrated the team's victory all night.", zh: "勝利" },
    { front: "stamina", pos: "n.", def: "the physical strength to keep doing something tiring for a long time", example: "Marathon runners need incredible stamina.", zh: "耐力；體力" },
    { front: "coach", pos: "n.", def: "a person who trains sports players", example: "Our coach makes us practise passing for an hour every day.", zh: "教練" },
    { front: "league", pos: "n.", def: "a group of sports teams that play against each other", example: "The club was promoted to the top league this season.", zh: "聯盟；聯賽" },
    { front: "pitch", pos: "n.", def: "an area of ground where a sport such as football is played", example: "The players walked onto the pitch to loud applause.", zh: "球場" },
    { front: "goalkeeper", pos: "n.", def: "the player who guards the goal and tries to stop the ball", example: "The goalkeeper made a brilliant save in the last minute.", zh: "守門員" },
    { front: "penalty", pos: "n.", def: "a punishment, or a free kick given in football when a rule is broken", example: "The referee awarded a penalty after the foul.", zh: "處罰；點球" },
    { front: "sprint", pos: "v.", def: "to run as fast as you can for a short distance", example: "He sprinted to the bus stop but still missed the bus.", zh: "衝刺；快跑" },
    { front: "marathon", pos: "n.", def: "a running race of about 42 kilometres", example: "She finished her first marathon in just under four hours.", zh: "馬拉松" },
    { front: "teammate", pos: "n.", def: "a person who plays on the same team as you", example: "He passed the ball to a teammate near the goal.", zh: "隊友" },
    { front: "substitute", pos: "n.", def: "a player who replaces another during a match; a person or thing that replaces another", example: "The substitute came on and scored within five minutes.", zh: "替補；代替者" },
    { front: "medal", pos: "n.", def: "a metal prize given to the winner of a competition", example: "She won a gold medal in the swimming final.", zh: "獎牌" },
    { front: "amateur", pos: "adj.", def: "doing something for pleasure, not as a paid job", example: "He plays for an amateur football club at weekends.", zh: "業餘的" },
    { front: "experiment", pos: "n.", def: "a scientific test done to learn something or prove an idea", example: "The students carried out an experiment with magnets.", zh: "實驗" },
    { front: "laboratory", pos: "n.", def: "a room where scientists do experiments", example: "The samples were sent to the laboratory for testing.", zh: "實驗室" },
    { front: "researcher", pos: "n.", def: "a person who studies a subject carefully to discover new facts", example: "Researchers at the university are developing a new battery.", zh: "研究人員" },
    { front: "theory", pos: "n.", def: "an idea that explains how or why something happens", example: "Darwin's theory changed the way we think about nature.", zh: "理論" },
    { front: "gravity", pos: "n.", def: "the force that pulls things towards the Earth", example: "Objects fall to the ground because of gravity.", zh: "重力" },
    { front: "cell", pos: "n.", def: "the smallest living part of an animal or plant", example: "The human body is made up of billions of cells.", zh: "細胞" },
    { front: "atom", pos: "n.", def: "the smallest unit that a chemical element can be divided into", example: "Water is made of hydrogen and oxygen atoms.", zh: "原子" },
    { front: "chemical", pos: "n.", def: "a substance made by or used in chemistry", example: "Farmers are trying to use fewer chemicals on their crops.", zh: "化學物質" },
    { front: "substance", pos: "n.", def: "a type of solid, liquid or gas; a material", example: "The bottle contained a sticky green substance.", zh: "物質" },
    { front: "reaction", pos: "n.", def: "what you do or feel because of something; a chemical change", example: "Her first reaction to the news was complete surprise.", zh: "反應" },
    { front: "discovery", pos: "n.", def: "the act of finding something new or learning something for the first time", example: "The discovery of penicillin saved millions of lives.", zh: "發現" },
    { front: "invention", pos: "n.", def: "a new machine, tool or idea that someone has created", example: "The smartphone is one of the most useful inventions ever.", zh: "發明" },
    { front: "breakthrough", pos: "n.", def: "an important discovery or success after a long effort", example: "Scientists have made a major breakthrough in cancer research.", zh: "重大突破" },
    { front: "data", pos: "n.", def: "facts or information, especially numbers collected for study", example: "The app collects data about how far you walk each day.", zh: "資料；數據" },
    { front: "microscope", pos: "n.", def: "an instrument that makes very small things look bigger", example: "We looked at the leaf cells under a microscope.", zh: "顯微鏡" },
    { front: "telescope", pos: "n.", def: "an instrument that makes distant objects, like stars, look closer", example: "Through the telescope we could see the rings of Saturn.", zh: "望遠鏡" },
    { front: "vaccine", pos: "n.", def: "a substance put into the body to protect it from a disease", example: "The new vaccine protects children against the virus.", zh: "疫苗" },
    { front: "bacteria", pos: "n.", def: "very small living things, some of which cause disease", example: "Washing your hands removes harmful bacteria.", zh: "細菌" },
    { front: "gene", pos: "n.", def: "a part of a cell that controls what you inherit from your parents", example: "Scientists found a gene linked to the disease.", zh: "基因" },
    { front: "evolve", pos: "v.", def: "to develop and change slowly over time", example: "Birds evolved from dinosaurs millions of years ago.", zh: "進化；逐漸發展" },
    { front: "observe", pos: "v.", def: "to watch something carefully to learn about it", example: "The class observed how the plants grew in different light.", zh: "觀察" },
    { front: "measure", pos: "v.", def: "to find the size, amount or degree of something", example: "We measured the temperature of the water every hour.", zh: "測量" },
    { front: "predict", pos: "v.", def: "to say what you think will happen in the future", example: "It is hard to predict who will win the election.", zh: "預測" },
    { front: "prove", pos: "v.", def: "to show that something is definitely true", example: "The test results proved that the theory was correct.", zh: "證明" },
    { front: "sample", pos: "n.", def: "a small amount of something that shows what the rest is like", example: "The nurse took a blood sample for testing.", zh: "樣本" },
    { front: "formula", pos: "n.", def: "a set of letters, numbers or rules that expresses a scientific fact", example: "Do you remember the formula for calculating speed?", zh: "公式" },
    { front: "conduct", pos: "v.", def: "to organise and carry out an activity such as research", example: "The team conducted a survey of five hundred students.", zh: "進行；執行" },
    { front: "analyse", pos: "v.", def: "to examine something carefully to understand it", example: "The scientists analysed the results of the experiment.", zh: "分析" },
    { front: "humid", pos: "adj.", def: "warm and slightly wet, describing air or weather", example: "Summers here are hot and humid, so everyone uses fans.", zh: "潮濕悶熱的" },
    { front: "chilly", pos: "adj.", def: "unpleasantly cold", example: "Take a jacket — it gets chilly in the evenings.", zh: "寒冷的" },
    { front: "mild", pos: "adj.", def: "not very cold or severe; gentle", example: "We had a mild winter with hardly any snow.", zh: "溫和的" },
    { front: "overcast", pos: "adj.", def: "covered with clouds; grey and dull", example: "The sky was overcast all morning, but it never rained.", zh: "陰天的" },
    { front: "hail", pos: "n.", def: "small balls of ice that fall like rain", example: "The hail was so heavy it damaged the car roof.", zh: "冰雹" },
    { front: "frost", pos: "n.", def: "a thin white layer of ice that forms in cold weather", example: "The grass was white with frost this morning.", zh: "霜" },
    { front: "fog", pos: "n.", def: "thick cloud near the ground that makes it hard to see", example: "The airport was closed because of thick fog.", zh: "霧" },
    { front: "gale", pos: "n.", def: "a very strong wind", example: "The gale blew several trees down in the park.", zh: "強風" },
    { front: "lightning", pos: "n.", def: "a bright flash of electricity in the sky during a storm", example: "Lightning lit up the whole sky for a second.", zh: "閃電" },
    { front: "thunder", pos: "n.", def: "the loud noise you hear during a storm after lightning", example: "The dog hid under the bed when it heard thunder.", zh: "雷聲" },
    { front: "heatwave", pos: "n.", def: "a period of unusually hot weather", example: "During the heatwave, temperatures stayed above 38 degrees.", zh: "熱浪" },
    { front: "blizzard", pos: "n.", def: "a severe snowstorm with strong winds", example: "The blizzard closed roads across the whole region.", zh: "暴風雪" },
    { front: "downpour", pos: "n.", def: "a sudden, very heavy fall of rain", example: "We got caught in a downpour on the way home.", zh: "傾盆大雨" },
    { front: "damp", pos: "adj.", def: "slightly wet, often in an unpleasant way", example: "The clothes were still damp, so I hung them up again.", zh: "潮濕的" },
    { front: "vehicle", pos: "n.", def: "a machine such as a car or bus that carries people or things", example: "Electric vehicles are becoming more common in the city.", zh: "車輛；交通工具" },
    { front: "pedestrian", pos: "n.", def: "a person walking in the street, not driving", example: "Drivers must stop to let pedestrians cross here.", zh: "行人" },
    { front: "motorway", pos: "n.", def: "a wide road for fast traffic between cities", example: "We took the motorway to avoid the small country roads.", zh: "高速公路" },
    { front: "roundabout", pos: "n.", def: "a circular area where several roads meet and traffic goes around", example: "Take the second exit at the roundabout.", zh: "圓環" },
    { front: "lane", pos: "n.", def: "one of the parts of a road marked for a single line of traffic", example: "The lorry moved into the slow lane to let us pass.", zh: "車道" },
    { front: "fare", pos: "n.", def: "the money you pay to travel by bus, train or taxi", example: "Bus fares went up again this year.", zh: "車資；票價" },
    { front: "congestion", pos: "n.", def: "a situation where roads are too full of traffic", example: "Congestion in the city centre is worst around six o'clock.", zh: "交通壅塞" },
    { front: "detour", pos: "n.", def: "a longer route you take to avoid a problem on the road", example: "We had to make a detour because the bridge was closed.", zh: "繞道" },
    { front: "helmet", pos: "n.", def: "a hard hat that protects your head", example: "Always wear a helmet when you ride a motorbike.", zh: "安全帽" },
    { front: "pavement", pos: "n.", def: "the path beside a road where people walk", example: "Cyclists are not allowed to ride on the pavement.", zh: "人行道" },
    { front: "cyclist", pos: "n.", def: "a person who rides a bicycle", example: "The new lane keeps cyclists separate from cars.", zh: "自行車騎士" },
    { front: "aircraft", pos: "n.", def: "any vehicle that can fly, such as a plane", example: "The aircraft landed safely despite the storm.", zh: "飛機；航空器" },
    { front: "carriage", pos: "n.", def: "one of the separate sections of a train for passengers", example: "The quiet carriage is at the front of the train.", zh: "車廂" },
    { front: "tram", pos: "n.", def: "an electric vehicle for passengers that runs on rails in the street", example: "The tram is the quickest way to get across the old town.", zh: "路面電車" },
    { front: "toll", pos: "n.", def: "money you pay to use a road, bridge or tunnel", example: "There is a small toll to cross the new bridge.", zh: "通行費" },
    { front: "overtake", pos: "v.", def: "to pass another vehicle that is moving in the same direction", example: "It is dangerous to overtake on a bend.", zh: "超車" },
    { front: "seatbelt", pos: "n.", def: "a belt in a car that holds you safely in your seat", example: "Please fasten your seatbelt before we set off.", zh: "安全帶" },
    { front: "runway", pos: "n.", def: "the long road at an airport where planes take off and land", example: "Our plane waited on the runway for twenty minutes.", zh: "跑道" },
    { front: "suburb", pos: "n.", def: "an area of houses outside the centre of a city", example: "They moved to a quiet suburb when the baby was born.", zh: "郊區" },
    { front: "skyscraper", pos: "n.", def: "a very tall modern building in a city", example: "From the hotel you can see the skyscrapers of the financial district.", zh: "摩天大樓" },
    { front: "landmark", pos: "n.", def: "a famous building or place that is easy to recognise", example: "The tower is the most famous landmark in the city.", zh: "地標" },
    { front: "inhabitant", pos: "n.", def: "a person or animal that lives in a place", example: "The island has fewer than a thousand inhabitants.", zh: "居民" },
    { front: "resident", pos: "n.", def: "a person who lives in a particular place", example: "Local residents complained about the noise from the club.", zh: "居民；住戶" },
    { front: "facility", pos: "n.", def: "a building, service or piece of equipment provided for a purpose", example: "The sports centre has excellent facilities, including two pools.", zh: "設施" },
    { front: "district", pos: "n.", def: "an area of a town or country", example: "The old district is full of narrow streets and cafés.", zh: "區；地區" },
    { front: "mayor", pos: "n.", def: "the person elected to lead a town or city", example: "The mayor promised to improve public transport.", zh: "市長" },
    { front: "council", pos: "n.", def: "the group of people who govern a town or area", example: "The city council plans to build a new library.", zh: "議會；委員會" },
    { front: "outskirts", pos: "n.", def: "the outer areas of a town or city", example: "The factory is on the outskirts, far from the centre.", zh: "市郊；邊緣地帶" },
    { front: "tenant", pos: "n.", def: "a person who pays rent to live in a house or flat", example: "The tenants asked the owner to repair the heating.", zh: "房客" },
    { front: "landlord", pos: "n.", def: "a person who owns a house or flat and rents it to others", example: "Our landlord raised the rent by five percent.", zh: "房東" },
    { front: "construction", pos: "n.", def: "the work of building houses, roads or bridges", example: "Construction of the new stadium will take two years.", zh: "建造；建設" },
    { front: "demolish", pos: "v.", def: "to knock down a building completely", example: "They demolished the old cinema to build flats.", zh: "拆除" },
    { front: "renovate", pos: "v.", def: "to repair an old building and make it modern again", example: "The couple spent a year renovating the farmhouse.", zh: "翻新；整修" },
    { front: "lively", pos: "adj.", def: "full of energy and activity", example: "The market is at its most lively on Saturday mornings.", zh: "熱鬧的；充滿活力的" },
    { front: "vibrant", pos: "adj.", def: "full of life, energy and excitement", example: "The city has a vibrant music scene.", zh: "充滿活力的" },
    { front: "crowded", pos: "adj.", def: "full of people, with little space", example: "The train was so crowded that we had to stand.", zh: "擁擠的" },
    { front: "arrogant", pos: "adj.", def: "believing you are better or more important than other people", example: "He became arrogant after winning a few matches.", zh: "傲慢的" },
    { front: "modest", pos: "adj.", def: "not talking proudly about your own abilities or success", example: "Despite her fame, she remained modest about her achievements.", zh: "謙虛的" },
    { front: "sociable", pos: "adj.", def: "enjoying spending time with other people", example: "My flatmate is very sociable and invites friends over all the time.", zh: "善於交際的" },
    { front: "outgoing", pos: "adj.", def: "friendly and confident with other people", example: "You need an outgoing personality to work in sales.", zh: "外向的" },
    { front: "reserved", pos: "adj.", def: "quiet and not showing your feelings easily", example: "He seems reserved at first, but he is very funny once you know him.", zh: "內向拘謹的" },
    { front: "talkative", pos: "adj.", def: "talking a lot", example: "The taxi driver was so talkative that the journey flew by.", zh: "健談的" },
    { front: "bossy", pos: "adj.", def: "always telling other people what to do", example: "My older sister was quite bossy when we were kids.", zh: "愛指使人的" },
    { front: "moody", pos: "adj.", def: "having feelings that change quickly, often becoming angry or sad", example: "Teenagers can be moody, especially in the morning.", zh: "喜怒無常的" },
    { front: "impatient", pos: "adj.", def: "not wanting to wait; easily annoyed by delays", example: "He gets impatient when the internet is slow.", zh: "沒耐心的" },
    { front: "considerate", pos: "adj.", def: "thinking about other people's feelings and needs", example: "It was considerate of you to call and check on your grandmother.", zh: "體貼的" },
    { front: "loyal", pos: "adj.", def: "always supporting your friends, family or team", example: "She has been a loyal friend to me for twenty years.", zh: "忠誠的" },
    { front: "sincere", pos: "adj.", def: "honest and meaning what you say", example: "Please accept my sincere apologies for the mistake.", zh: "真誠的" },
    { front: "witty", pos: "adj.", def: "funny in a clever way", example: "His speech was full of witty remarks about school life.", zh: "機智風趣的" },
    { front: "charming", pos: "adj.", def: "pleasant and attractive in a way that people like", example: "The waiter was charming and made everyone feel welcome.", zh: "迷人的" },
    { front: "easy-going", pos: "adj.", def: "relaxed and not easily worried or annoyed", example: "Our teacher is easy-going and never shouts at us.", zh: "隨和的" },
    { front: "mature", pos: "adj.", def: "behaving in a sensible, adult way", example: "She is very mature for a fifteen-year-old.", zh: "成熟的" },
    { front: "adventurous", pos: "adj.", def: "willing to try new and exciting things, even if they are risky", example: "Be adventurous and try the local street food.", zh: "愛冒險的" },
    { front: "imaginative", pos: "adj.", def: "good at thinking of new and original ideas", example: "The film has an imaginative plot unlike anything I have seen.", zh: "富有想像力的" },
    { front: "open-minded", pos: "adj.", def: "willing to consider new ideas and different opinions", example: "Try to stay open-minded when you visit other cultures.", zh: "心胸開放的" },
    { front: "thoughtful", pos: "adj.", def: "kind and thinking about what other people need", example: "It was thoughtful of him to bring soup when I was ill.", zh: "體貼周到的" },
    { front: "tolerant", pos: "adj.", def: "accepting behaviour and beliefs different from your own", example: "The city is famous for being tolerant of different lifestyles.", zh: "寬容的" },
    { front: "decisive", pos: "adj.", def: "able to make decisions quickly and confidently", example: "A good captain has to be decisive under pressure.", zh: "果斷的" },
    { front: "courageous", pos: "adj.", def: "brave; not afraid of danger or difficulty", example: "The firefighters were courageous to enter the burning building.", zh: "勇敢的" },
    { front: "self-conscious", pos: "adj.", def: "nervous or embarrassed about how you look or seem to others", example: "He felt self-conscious about speaking English in front of the class.", zh: "不自在的；害羞的" },
    { front: "hard-working", pos: "adj.", def: "putting a lot of effort into your work or studies", example: "She is the most hard-working student in the year.", zh: "勤奮的" },
    { front: "punctual", pos: "adj.", def: "arriving or doing things at the correct time", example: "Please be punctual — the bus leaves at eight sharp.", zh: "準時的" },
    { front: "fierce", pos: "adj.", def: "very strong, angry or aggressive", example: "There is fierce competition for places at the university.", zh: "激烈的；兇猛的" },
    { front: "aggressive", pos: "adj.", def: "behaving in an angry or violent way towards others", example: "The dog becomes aggressive when strangers approach the gate.", zh: "有攻擊性的" },
    { front: "recipe", pos: "n.", def: "instructions for cooking a particular dish", example: "This soup recipe has been in our family for generations.", zh: "食譜" },
    { front: "ingredient", pos: "n.", def: "one of the foods you use to make a dish", example: "The only ingredients are flour, eggs and milk.", zh: "食材；成分" },
    { front: "flavour", pos: "n.", def: "the particular taste of a food or drink", example: "The lemon gives the cake a fresh flavour.", zh: "味道；風味" },
    { front: "spicy", pos: "adj.", def: "having a strong hot taste from spices", example: "Thai food is often too spicy for my father.", zh: "辣的" },
    { front: "bitter", pos: "adj.", def: "having a strong, sharp taste like black coffee", example: "The medicine left a bitter taste in my mouth.", zh: "苦的" },
    { front: "sour", pos: "adj.", def: "having a sharp taste like lemon or vinegar", example: "The milk smells sour — I think it has gone off.", zh: "酸的" },
    { front: "savoury", pos: "adj.", def: "tasting of salt or spices rather than sugar", example: "I prefer savoury snacks like crisps to sweet ones.", zh: "鹹味的" },
    { front: "crispy", pos: "adj.", def: "pleasantly hard and dry on the outside", example: "The chicken skin was golden and crispy.", zh: "酥脆的" },
    { front: "tender", pos: "adj.", def: "soft and easy to cut or chew, describing meat", example: "Cook the beef slowly until it is tender.", zh: "軟嫩的" },
    { front: "raw", pos: "adj.", def: "not cooked", example: "In Japan people often eat raw fish.", zh: "生的" },
    { front: "ripe", pos: "adj.", def: "fully grown and ready to eat, describing fruit", example: "Wait until the bananas are ripe before you eat them.", zh: "成熟的" },
    { front: "rotten", pos: "adj.", def: "old and decayed; no longer good to eat", example: "There was a rotten apple at the bottom of the bag.", zh: "腐爛的" },
    { front: "stale", pos: "adj.", def: "no longer fresh, describing bread or air", example: "The bread was stale, so we made toast with it.", zh: "不新鮮的" },
    { front: "slice", pos: "v.", def: "to cut food into thin flat pieces", example: "Slice the tomatoes and lay them on the plate.", zh: "切片" },
    { front: "grate", pos: "v.", def: "to rub food against a rough tool to cut it into small pieces", example: "Grate some cheese over the pasta before serving.", zh: "磨碎；刨絲" },
    { front: "stir", pos: "v.", def: "to mix a liquid or food by moving a spoon in circles", example: "Stir the sauce so it does not stick to the pan.", zh: "攪拌" },
    { front: "simmer", pos: "v.", def: "to cook something gently in liquid just below boiling", example: "Let the soup simmer for twenty minutes.", zh: "小火慢燉" },
    { front: "roast", pos: "v.", def: "to cook food such as meat in an oven or over a fire", example: "We roasted a chicken with potatoes for Sunday lunch.", zh: "烘烤" },
    { front: "grill", pos: "v.", def: "to cook food under or over direct heat", example: "Grill the fish for four minutes on each side.", zh: "燒烤" },
    { front: "whisk", pos: "v.", def: "to mix eggs or cream very quickly with a tool", example: "Whisk the eggs until they are light and fluffy.", zh: "打發；攪打" },
    { front: "peel", pos: "v.", def: "to remove the skin from fruit or vegetables", example: "Peel the potatoes and cut them into chunks.", zh: "削皮" },
    { front: "seasoning", pos: "n.", def: "salt, pepper or spices added to food to improve its taste", example: "Taste the sauce and add more seasoning if needed.", zh: "調味料" },
    { front: "appetite", pos: "n.", def: "the feeling of wanting to eat", example: "The long walk gave us a huge appetite.", zh: "食慾" },
    { front: "cuisine", pos: "n.", def: "a style of cooking, especially of a country or region", example: "Italian cuisine is popular all over the world.", zh: "菜餚；烹飪風格" },
    { front: "vegetarian", pos: "n.", def: "a person who does not eat meat or fish", example: "My sister has been a vegetarian since she was twelve.", zh: "素食者" },
    { front: "leftovers", pos: "n.", def: "food that remains after a meal and can be eaten later", example: "We had the leftovers from dinner for lunch the next day.", zh: "剩菜" },
    { front: "exhibition", pos: "n.", def: "a public show of art or other interesting objects", example: "There is a photography exhibition at the gallery this month.", zh: "展覽" },
    { front: "gallery", pos: "n.", def: "a building or room where art is shown", example: "The gallery is free to visit on Sundays.", zh: "美術館；畫廊" },
    { front: "sculpture", pos: "n.", def: "a work of art made by shaping stone, metal or wood", example: "The park is full of modern sculptures.", zh: "雕塑" },
    { front: "portrait", pos: "n.", def: "a painting, drawing or photo of a person", example: "The artist painted a portrait of the queen.", zh: "肖像" },
    { front: "masterpiece", pos: "n.", def: "an extremely good work of art or piece of work", example: "Many critics consider the novel his masterpiece.", zh: "傑作" },
    { front: "performance", pos: "n.", def: "the act of entertaining an audience by acting, singing or playing music", example: "The band gave an unforgettable performance last night.", zh: "表演" },
    { front: "rehearsal", pos: "n.", def: "a practice of a play or concert before the real performance", example: "The final rehearsal lasted until midnight.", zh: "排練" },
    { front: "playwright", pos: "n.", def: "a person who writes plays", example: "Shakespeare is the most famous playwright in English.", zh: "劇作家" },
    { front: "novelist", pos: "n.", def: "a person who writes novels", example: "The novelist based the story on her own childhood.", zh: "小說家" },
    { front: "plot", pos: "n.", def: "the events that make up the story of a book, film or play", example: "The film has a clever plot with a surprise ending.", zh: "情節" },
    { front: "genre", pos: "n.", def: "a type or style of art, music or writing", example: "Science fiction is my favourite genre.", zh: "類型；體裁" },
    { front: "fiction", pos: "n.", def: "books and stories about imaginary people and events", example: "She reads mostly fiction, especially crime novels.", zh: "小說；虛構作品" },
    { front: "biography", pos: "n.", def: "the story of a person's life written by someone else", example: "I am reading a biography of Nelson Mandela.", zh: "傳記" },
    { front: "poetry", pos: "n.", def: "poems in general as a form of literature", example: "We studied modern poetry in English class this term.", zh: "詩" },
    { front: "orchestra", pos: "n.", def: "a large group of musicians playing classical music together", example: "The orchestra performed a symphony by Beethoven.", zh: "管弦樂團" },
    { front: "conductor", pos: "n.", def: "a person who directs an orchestra; a person who checks tickets on a train", example: "The conductor raised his arms and the music began.", zh: "指揮；列車長" },
    { front: "composer", pos: "n.", def: "a person who writes music", example: "Mozart was a composer who started writing music as a child.", zh: "作曲家" },
    { front: "melody", pos: "n.", def: "a tune; a series of musical notes that sound pleasant together", example: "The song has a simple melody that is easy to remember.", zh: "旋律" },
    { front: "rhythm", pos: "n.", def: "a regular repeated pattern of sound or movement", example: "The dancers moved perfectly to the rhythm of the drums.", zh: "節奏" },
    { front: "lyrics", pos: "n.", def: "the words of a song", example: "I love the melody, but I cannot understand the lyrics.", zh: "歌詞" },
    { front: "applause", pos: "n.", def: "the sound of people clapping to show they enjoyed something", example: "The actors returned to the stage to loud applause.", zh: "掌聲" },
    { front: "audition", pos: "n.", def: "a short performance to test whether someone is good enough for a role", example: "She has an audition for the school musical tomorrow.", zh: "試鏡；試演" },
    { front: "costume", pos: "n.", def: "special clothes worn by an actor or worn for a party", example: "The costumes in the play were beautifully designed.", zh: "戲服；服裝" },
    { front: "cast", pos: "n.", def: "all the actors in a film or play", example: "The whole cast came out to bow at the end.", zh: "演員陣容" },
    { front: "persuade", pos: "v.", def: "to make someone agree to do something by giving good reasons", example: "She persuaded her parents to let her go to the concert.", zh: "說服" },
    { front: "convince", pos: "v.", def: "to make someone believe that something is true", example: "He convinced the teacher that the excuse was genuine.", zh: "使相信" },
    { front: "negotiate", pos: "v.", def: "to discuss something in order to reach an agreement", example: "The union is negotiating a pay rise with the company.", zh: "談判；協商" },
    { front: "debate", pos: "n.", def: "a formal discussion in which people give different opinions", example: "There was a lively debate about school uniforms.", zh: "辯論" },
    { front: "interrupt", pos: "v.", def: "to stop someone while they are speaking or doing something", example: "Please do not interrupt me while I am explaining.", zh: "打斷" },
    { front: "apologise", pos: "v.", def: "to say you are sorry for something you have done", example: "He apologised for arriving late to the meeting.", zh: "道歉" },
    { front: "exaggerate", pos: "v.", def: "to make something seem bigger or better than it really is", example: "Do not exaggerate — the fish was not that big.", zh: "誇大" },
    { front: "hesitate", pos: "v.", def: "to pause before doing something because you are not sure", example: "She hesitated before answering the difficult question.", zh: "猶豫" },
    { front: "whisper", pos: "v.", def: "to speak very quietly so others cannot hear", example: "He whispered the answer to the boy next to him.", zh: "低聲說" },
    { front: "mutter", pos: "v.", def: "to speak quietly and unclearly, often when annoyed", example: "He muttered something about the unfair rules and walked off.", zh: "咕噥；嘀咕" },
    { front: "announce", pos: "v.", def: "to tell people something officially or publicly", example: "The airline announced a delay of two hours.", zh: "宣布" },
    { front: "declare", pos: "v.", def: "to say something officially or firmly", example: "The judges declared her the winner of the competition.", zh: "宣告；聲明" },
    { front: "confess", pos: "v.", def: "to admit that you have done something wrong", example: "He finally confessed that he had broken the window.", zh: "承認；坦白" },
    { front: "deny", pos: "v.", def: "to say that something is not true", example: "She denied taking the money from the drawer.", zh: "否認" },
    { front: "insist", pos: "v.", def: "to say firmly that something must happen or is true", example: "My aunt insisted on paying for everyone's dinner.", zh: "堅持" },
    { front: "remark", pos: "n.", def: "something you say; a comment", example: "His remark about her cooking was rather rude.", zh: "評論；言論" },
    { front: "fluent", pos: "adj.", def: "able to speak a language easily and well", example: "After two years in Madrid, she is fluent in Spanish.", zh: "流利的" },
    { front: "misunderstanding", pos: "n.", def: "a situation where someone understands something wrongly", example: "There was a misunderstanding about the meeting time.", zh: "誤會" },
    { front: "rumour", pos: "n.", def: "a story that people repeat but that may not be true", example: "There is a rumour that the shop is closing down.", zh: "謠言" },
    { front: "sarcastic", pos: "adj.", def: "saying the opposite of what you mean to mock someone", example: "Nice of you to join us, he said in a sarcastic voice.", zh: "諷刺的" },
    { front: "oversleep", pos: "v.", def: "to sleep longer than you intended", example: "I overslept and missed the first lesson.", zh: "睡過頭" },
    { front: "yawn", pos: "v.", def: "to open your mouth wide and breathe in because you are tired or bored", example: "He kept yawning during the long lecture.", zh: "打呵欠" },
    { front: "laundry", pos: "n.", def: "clothes that need washing or have just been washed", example: "I do the laundry every Saturday morning.", zh: "待洗衣物；洗衣" },
    { front: "groceries", pos: "n.", def: "food and other goods you buy for the home", example: "He carried the groceries up three flights of stairs.", zh: "食品雜貨" },
    { front: "shift", pos: "n.", def: "a period of work time, especially in a job with different hours", example: "She works the night shift at the hospital.", zh: "輪班" },
    { front: "leisure", pos: "n.", def: "free time when you are not working or studying", example: "He spends most of his leisure time fishing by the river.", zh: "閒暇" },
    { front: "chore", pos: "n.", def: "a boring job you have to do regularly, especially at home", example: "Washing the dishes is my least favourite chore.", zh: "家務雜事" },
    { front: "refreshed", pos: "adj.", def: "feeling less tired and full of energy again", example: "After a short nap I felt completely refreshed.", zh: "恢復精神的" },
    { front: "accomplish", pos: "v.", def: "to succeed in doing or finishing something", example: "We accomplished everything on the list before lunch.", zh: "完成；達成" },
    { front: "acquire", pos: "v.", def: "to get or gain something, such as a skill or possession", example: "Children acquire language surprisingly quickly.", zh: "獲得；習得" },
    { front: "adapt", pos: "v.", def: "to change in order to suit a new situation", example: "It took him a while to adapt to life in a big city.", zh: "適應" },
    { front: "admire", pos: "v.", def: "to respect or like someone or something very much", example: "I really admire her courage in speaking up.", zh: "欽佩" },
    { front: "annoy", pos: "v.", def: "to make someone slightly angry", example: "It annoys me when people talk during films.", zh: "使惱怒" },
    { front: "anticipate", pos: "v.", def: "to expect something and prepare for it", example: "We anticipate a large crowd, so come early.", zh: "預期" },
    { front: "appreciate", pos: "v.", def: "to be grateful for something; to understand its value", example: "I really appreciate all the help you gave me.", zh: "感激；欣賞" },
    { front: "assume", pos: "v.", def: "to think something is true without proof", example: "I assumed the shop was open, but it was shut.", zh: "假設；以為" },
    { front: "attempt", pos: "n.", def: "an act of trying to do something", example: "Her first attempt at skiing ended in a fall.", zh: "嘗試" },
    { front: "attitude", pos: "n.", def: "the way you think and feel about something", example: "He has a very positive attitude towards his studies.", zh: "態度" },
    { front: "aware", pos: "adj.", def: "knowing about something", example: "Are you aware that the deadline is tomorrow?", zh: "意識到的" },
    { front: "benefit", pos: "n.", def: "an advantage or helpful effect", example: "One benefit of cycling is that it keeps you fit.", zh: "好處；利益" },
    { front: "capable", pos: "adj.", def: "having the ability or skill to do something", example: "She is perfectly capable of organising the trip herself.", zh: "有能力的" },
    { front: "challenging", pos: "adj.", def: "difficult in an interesting way that tests your ability", example: "Learning Chinese is challenging but rewarding.", zh: "有挑戰性的" },
    { front: "coincidence", pos: "n.", def: "a surprising situation where two things happen at the same time by chance", example: "By coincidence, we were both staying at the same hotel.", zh: "巧合" },
    { front: "collapse", pos: "v.", def: "to fall down suddenly", example: "The old bridge collapsed after the heavy floods.", zh: "倒塌；崩潰" },
    { front: "consequence", pos: "n.", def: "a result of an action, often a bad one", example: "One consequence of the strike was cancelled trains.", zh: "後果" },
    { front: "cope", pos: "v.", def: "to deal successfully with a difficult situation", example: "She coped well with the pressure of the exams.", zh: "應付；處理" },
    { front: "deliberately", pos: "adv.", def: "on purpose; intentionally", example: "He deliberately left his phone at home to avoid calls.", zh: "故意地" },
    { front: "deserve", pos: "v.", def: "to have earned something because of what you have done", example: "After all that work, you deserve a holiday.", zh: "應得" },
    { front: "disaster", pos: "n.", def: "a sudden event that causes great damage or harm", example: "The earthquake was the worst disaster in the region's history.", zh: "災難" },
    { front: "dull", pos: "adj.", def: "boring; not interesting or bright", example: "The lecture was so dull that several students fell asleep.", zh: "枯燥的；暗淡的" },
    { front: "eager", pos: "adj.", def: "wanting to do something very much", example: "The children were eager to open their presents.", zh: "渴望的" },
    { front: "efficient", pos: "adj.", def: "working well without wasting time or energy", example: "The new heating system is much more efficient.", zh: "有效率的" },
    { front: "encourage", pos: "v.", def: "to give someone confidence or support to do something", example: "My teacher encouraged me to enter the writing competition.", zh: "鼓勵" },
    { front: "enormous", pos: "adj.", def: "extremely large", example: "An enormous crowd gathered outside the stadium.", zh: "巨大的" },
    { front: "eventually", pos: "adv.", def: "in the end, after a long time or many problems", example: "We got lost twice but eventually found the hotel.", zh: "最終" },
    { front: "fascinating", pos: "adj.", def: "extremely interesting", example: "The documentary about deep-sea creatures was fascinating.", zh: "極有趣的" },
    { front: "flexible", pos: "adj.", def: "able to change easily to suit new conditions", example: "My job has flexible hours, so I can start late.", zh: "彈性的；靈活的" },
    { front: "genuine", pos: "adj.", def: "real and true; not fake", example: "The signature turned out to be genuine.", zh: "真正的" },
    { front: "gradually", pos: "adv.", def: "slowly, over a period of time", example: "The weather gradually improved during the week.", zh: "逐漸地" },
    { front: "guarantee", pos: "v.", def: "to promise that something will definitely happen or work", example: "The shop guarantees delivery within three days.", zh: "保證" },
    { front: "hire", pos: "v.", def: "to pay to use something for a short time; to give someone a job", example: "We hired bikes and rode along the coast.", zh: "租用；雇用" },
    { front: "ignore", pos: "v.", def: "to pay no attention to someone or something", example: "He ignored the warning signs and swam out too far.", zh: "忽視" },
    { front: "impress", pos: "v.", def: "to make someone admire you", example: "She impressed the interviewers with her confident answers.", zh: "使印象深刻" },
    { front: "incident", pos: "n.", def: "an event, especially an unusual or unpleasant one", example: "The police are investigating an incident at the station.", zh: "事件" },
    { front: "incredible", pos: "adj.", def: "difficult to believe; extremely good or surprising", example: "The view from the top of the mountain was incredible.", zh: "難以置信的" },
    { front: "isolated", pos: "adj.", def: "far away from other places or people", example: "The village is so isolated that it has no bus service.", zh: "孤立的；偏僻的" },
    { front: "lack", pos: "n.", def: "the state of not having something or not having enough of it", example: "The project failed because of a lack of money.", zh: "缺乏" },
    { front: "launch", pos: "v.", def: "to start something new, such as a product or campaign", example: "The company will launch its new phone in September.", zh: "推出；發起" },
    { front: "motivate", pos: "v.", def: "to make someone want to do something", example: "A good coach knows how to motivate the players.", zh: "激勵" },
    { front: "obtain", pos: "v.", def: "to get something, especially by effort", example: "You need to obtain a permit before you can fish here.", zh: "取得" },
    { front: "overcome", pos: "v.", def: "to succeed in dealing with a problem or difficulty", example: "She overcame her fear of flying and visited Australia.", zh: "克服" },
    { front: "owe", pos: "v.", def: "to need to pay money back to someone", example: "I still owe my brother twenty pounds.", zh: "欠" },
    { front: "add up", pos: "phr. v.", def: "to calculate the total; to make sense", example: "His story just does not add up — something is wrong.", zh: "合計；合乎情理" },
    { front: "ask around", pos: "phr. v.", def: "to ask several people for information", example: "I will ask around and see if anyone has a spare ticket.", zh: "四處打聽" },
    { front: "ask out", pos: "phr. v.", def: "to invite someone to go on a date", example: "He finally asked her out after weeks of chatting.", zh: "邀約會" },
    { front: "bring about", pos: "phr. v.", def: "to cause something to happen", example: "The internet has brought about huge changes in how we work.", zh: "導致；引起" },
    { front: "bring back", pos: "phr. v.", def: "to return something; to make you remember something", example: "That song brings back memories of our school trip.", zh: "帶回；勾起回憶" },
    { front: "bring down", pos: "phr. v.", def: "to reduce something; to cause something to fall", example: "The new law should bring down the price of medicine.", zh: "降低；使倒下" },
    { front: "brush up on", pos: "phr. v.", def: "to practise and improve a skill you have not used for a while", example: "I need to brush up on my French before the trip to Paris.", zh: "溫習；重新練習" },
    { front: "build up", pos: "phr. v.", def: "to increase gradually", example: "Traffic builds up on this road every morning.", zh: "逐漸增加；累積" },
    { front: "call in", pos: "phr. v.", def: "to visit a place briefly; to ask someone to come and help", example: "They had to call in an expert to fix the server.", zh: "順道拜訪；請來" },
    { front: "call on", pos: "phr. v.", def: "to visit someone; to formally ask someone to do something", example: "The mayor called on residents to save water during the drought.", zh: "拜訪；呼籲" },
    { front: "catch on", pos: "phr. v.", def: "to become popular; to understand something", example: "The dance move caught on quickly among teenagers.", zh: "流行起來；領悟" },
    { front: "chill out", pos: "phr. v.", def: "to relax completely", example: "We spent the afternoon chilling out by the pool.", zh: "放鬆" },
    { front: "chop up", pos: "phr. v.", def: "to cut something into small pieces", example: "Chop up the onions while I heat the oil.", zh: "切碎" },
    { front: "clear out", pos: "phr. v.", def: "to remove things you do not want from a place", example: "I spent Sunday clearing out the garage.", zh: "清理；清空" },
    { front: "clear up", pos: "phr. v.", def: "to tidy a place; to explain or solve a problem; to become sunny", example: "The weather cleared up in time for the barbecue.", zh: "整理；澄清；放晴" },
    { front: "close down", pos: "phr. v.", def: "to stop operating as a business", example: "The old bookshop closed down after forty years.", zh: "歇業；關閉" },
    { front: "come down with", pos: "phr. v.", def: "to start to suffer from an illness", example: "She came down with the flu the day before the exam.", zh: "染上（病）" },
    { front: "come out", pos: "phr. v.", def: "to be published or released; to become known", example: "Her new album comes out next Friday.", zh: "出版；發行；顯露" },
    { front: "come round", pos: "phr. v.", def: "to visit someone at their home; to become conscious again", example: "Why don't you come round for dinner on Saturday?", zh: "來訪；甦醒" },
    { front: "cool down", pos: "phr. v.", def: "to become less hot; to become calmer", example: "Let the cake cool down before you cut it.", zh: "冷卻；冷靜下來" },
    { front: "cross out", pos: "phr. v.", def: "to draw a line through writing to show it is wrong", example: "Cross out any answers you want the examiner to ignore.", zh: "劃掉" },
    { front: "cut back on", pos: "phr. v.", def: "to reduce the amount of something, especially money or food", example: "The doctor told him to cut back on salt.", zh: "削減" },
    { front: "cut out", pos: "phr. v.", def: "to remove something by cutting; to stop eating or doing something", example: "She cut out sugar completely for a month.", zh: "剪下；戒除" },
    { front: "die down", pos: "phr. v.", def: "to become gradually less strong or loud", example: "We waited for the wind to die down before sailing.", zh: "逐漸平息" },
    { front: "die out", pos: "phr. v.", def: "to disappear completely; to become extinct", example: "Many traditional crafts are slowly dying out.", zh: "滅絕；消失" },
    { front: "dig up", pos: "phr. v.", def: "to remove something from the ground; to discover hidden information", example: "Workers dug up an ancient coin while repairing the road.", zh: "挖出；挖掘出" },
    { front: "do without", pos: "phr. v.", def: "to manage even though you do not have something", example: "There is no milk, so we will have to do without.", zh: "沒有…也行" },
    { front: "doze off", pos: "phr. v.", def: "to fall asleep without meaning to", example: "Grandad dozed off in front of the television again.", zh: "打瞌睡" },
    { front: "drag on", pos: "phr. v.", def: "to continue for longer than necessary in a boring way", example: "The meeting dragged on for three hours.", zh: "拖延；沒完沒了" },
    { front: "draw up", pos: "phr. v.", def: "to prepare a plan, list or document", example: "We drew up a list of everything we needed for the trip.", zh: "擬定" },
    { front: "drop by", pos: "phr. v.", def: "to make a short visit, often without arranging it", example: "Drop by any time — I am home all weekend.", zh: "順道拜訪" },
    { front: "drop in", pos: "phr. v.", def: "to visit someone briefly without an appointment", example: "An old friend dropped in while we were having lunch.", zh: "順路探訪" },
    { front: "fall behind", pos: "phr. v.", def: "to fail to keep up with work, payments or other people", example: "He fell behind with his homework after being ill.", zh: "落後" },
    { front: "fall for", pos: "phr. v.", def: "to be tricked by something; to fall in love with someone", example: "Thousands of people fell for the online scam.", zh: "受騙；愛上" },
    { front: "fall through", pos: "phr. v.", def: "to fail to happen, describing a plan or arrangement", example: "Our holiday plans fell through at the last minute.", zh: "告吹；落空" },
    { front: "fill out", pos: "phr. v.", def: "to complete a form by writing information on it", example: "Please fill out this form and hand it to reception.", zh: "填寫（表格）" },
    { front: "fill up", pos: "phr. v.", def: "to make something completely full", example: "We filled up the car before driving to the mountains.", zh: "加滿；填滿" },
    { front: "get across", pos: "phr. v.", def: "to make people understand an idea", example: "Charts helped her get her point across to the audience.", zh: "使被理解；傳達" },
    { front: "get ahead", pos: "phr. v.", def: "to be more successful than others, especially at work", example: "Learning new skills will help you get ahead in your career.", zh: "領先；出人頭地" },
    { front: "get away", pos: "phr. v.", def: "to escape; to go somewhere for a holiday", example: "We hope to get away for a few days in August.", zh: "逃離；度假" },
    { front: "get back", pos: "phr. v.", def: "to return, especially to your home", example: "What time did you get back from the party?", zh: "回來" },
    { front: "get down to", pos: "phr. v.", def: "to finally start doing something seriously", example: "Stop chatting and get down to work.", zh: "開始認真做" },
    { front: "get into", pos: "phr. v.", def: "to become interested in something; to be accepted by a school", example: "I got into photography during the summer holidays.", zh: "開始喜歡；進入" },
    { front: "get off", pos: "phr. v.", def: "to leave a bus, train or plane", example: "Get off at the third stop and turn left.", zh: "下車" },
    { front: "get on", pos: "phr. v.", def: "to enter a bus, train or plane; to make progress", example: "How are you getting on with your new project?", zh: "上車；進展" },
    { front: "get out of", pos: "phr. v.", def: "to avoid doing something you should do", example: "He tried to get out of doing the washing-up.", zh: "逃避" },
    { front: "get through", pos: "phr. v.", def: "to finish or deal with something; to reach someone by phone", example: "I tried calling all morning but could not get through.", zh: "完成；接通電話" },
    { front: "get together", pos: "phr. v.", def: "to meet socially with other people", example: "The whole family gets together every Chinese New Year.", zh: "聚會" },
    { front: "give back", pos: "phr. v.", def: "to return something to its owner", example: "Can you give back the book I lent you last month?", zh: "歸還" },
    { front: "give out", pos: "phr. v.", def: "to hand things to many people; to stop working", example: "The teacher gave out the exam papers at nine o'clock.", zh: "分發；失靈" },
    { front: "go ahead", pos: "phr. v.", def: "to start or continue with a plan; used to give permission", example: "The concert will go ahead despite the rain.", zh: "進行；照辦" },
    { front: "go along with", pos: "phr. v.", def: "to agree with a person or plan", example: "I did not love the idea, but I went along with it.", zh: "贊同；配合" },
    { front: "go down", pos: "phr. v.", def: "to decrease; to become lower", example: "House prices have gone down slightly this year.", zh: "下降" },
    { front: "go over", pos: "phr. v.", def: "to check or review something carefully", example: "Let's go over the plan once more before we start.", zh: "檢查；複習" },
    { front: "go up", pos: "phr. v.", def: "to increase; to rise", example: "The price of coffee has gone up again.", zh: "上漲" },
    { front: "go without", pos: "phr. v.", def: "to live without something you usually have", example: "The campers went without hot water for a week.", zh: "將就沒有" },
    { front: "hand over", pos: "phr. v.", def: "to give something to someone, often because you must", example: "The robber told him to hand over his wallet.", zh: "交出" },
    { front: "hang around", pos: "phr. v.", def: "to spend time in a place doing nothing in particular", example: "A group of teenagers were hanging around outside the shop.", zh: "閒晃" },
    { front: "head for", pos: "phr. v.", def: "to move in the direction of a place", example: "After the match, everyone headed for the exits.", zh: "前往" },
    { front: "heat up", pos: "phr. v.", def: "to make food hot again; to become hotter", example: "I heated up last night's curry for lunch.", zh: "加熱" },
    { front: "hold back", pos: "phr. v.", def: "to stop yourself from showing feelings; to prevent progress", example: "She could not hold back her tears at the wedding.", zh: "抑制；阻礙" },
    { front: "hold up", pos: "phr. v.", def: "to delay someone or something", example: "Sorry I am late — I was held up by an accident on the motorway.", zh: "耽擱" },
    { front: "keep on", pos: "phr. v.", def: "to continue doing something", example: "She kept on practising until she could play the piece perfectly.", zh: "繼續" },
    { front: "keep out", pos: "phr. v.", def: "to stop someone or something from entering", example: "The fence is there to keep out wild animals.", zh: "使不得入內" },
    { front: "kick off", pos: "phr. v.", def: "to begin, especially a football match or event", example: "The festival kicks off with a fireworks display on Friday.", zh: "開始；開賽" },
    { front: "knock down", pos: "phr. v.", def: "to hit someone so they fall; to destroy a building", example: "The cyclist was knocked down by a van at the crossing.", zh: "撞倒；拆除" },
    { front: "knock out", pos: "phr. v.", def: "to make someone unconscious; to defeat a team so it leaves a competition", example: "Our team was knocked out in the semi-final.", zh: "擊昏；淘汰" },
    { front: "lay off", pos: "phr. v.", def: "to stop employing someone because there is not enough work", example: "The factory laid off two hundred workers last month.", zh: "裁員" },
    { front: "leave out", pos: "phr. v.", def: "to not include someone or something", example: "You left out an important detail in your report.", zh: "遺漏；不包括" },
    { front: "let in", pos: "phr. v.", def: "to allow someone or something to enter", example: "Open the curtains and let in some light.", zh: "讓…進入" },
    { front: "let off", pos: "phr. v.", def: "to not punish someone, or punish them only lightly", example: "The police let him off with just a warning.", zh: "從輕發落" },
    { front: "live on", pos: "phr. v.", def: "to have a particular amount of money for basic needs; to eat mainly one food", example: "As a student he lived on noodles and toast.", zh: "靠…生活" },
    { front: "live up to", pos: "phr. v.", def: "to be as good as people expected", example: "The film did not live up to all the excitement around it.", zh: "不辜負；符合期望" },
    { front: "lock up", pos: "phr. v.", def: "to lock all the doors of a building; to put someone in prison", example: "Remember to lock up before you leave the office.", zh: "鎖好門窗；監禁" },
    { front: "look around", pos: "phr. v.", def: "to walk around a place and see what is there", example: "We spent the morning looking around the old town.", zh: "四處參觀" },
    { front: "look out", pos: "phr. v.", def: "used to warn someone of danger", example: "Look out! There is a car coming.", zh: "當心" },
    { front: "look over", pos: "phr. v.", def: "to examine something quickly", example: "Could you look over my essay before I hand it in?", zh: "快速檢查" },
    { front: "look through", pos: "phr. v.", def: "to read or examine something, usually quickly", example: "I looked through the brochure but nothing caught my eye.", zh: "瀏覽" },
    { front: "make out", pos: "phr. v.", def: "to manage to see, hear or understand something with difficulty", example: "I could just make out a ship on the horizon.", zh: "勉強辨認出" },
    { front: "make up", pos: "phr. v.", def: "to invent a story or excuse; to become friends again after an argument", example: "He made up an excuse about missing the bus.", zh: "編造；和好" },
    { front: "mix up", pos: "phr. v.", def: "to confuse two people or things", example: "I always mix up the twins — they look identical.", zh: "搞混" },
    { front: "move on", pos: "phr. v.", def: "to start doing or discussing something new", example: "Let's move on to the next question.", zh: "繼續前進；換話題" },
    { front: "narrow down", pos: "phr. v.", def: "to reduce the number of choices", example: "We narrowed down the list of hotels to just three.", zh: "縮小範圍" },
    { front: "nod off", pos: "phr. v.", def: "to fall asleep for a short time without intending to", example: "I nodded off during the second half of the film.", zh: "打盹" },
    { front: "pass on", pos: "phr. v.", def: "to give information or a message to someone else", example: "Could you pass on the message to your manager?", zh: "轉達；傳遞" },
    { front: "pay off", pos: "phr. v.", def: "to bring success after effort; to finish paying a debt", example: "All those hours of training finally paid off.", zh: "取得成效；還清" },
    { front: "pick out", pos: "phr. v.", def: "to choose something from a group", example: "She picked out a blue dress for the wedding.", zh: "挑選" },
    { front: "plug in", pos: "phr. v.", def: "to connect a machine to the electricity supply", example: "Plug in your laptop before the battery dies.", zh: "插上電源" },
    { front: "print out", pos: "phr. v.", def: "to produce a paper copy from a computer", example: "Print out your boarding pass the night before.", zh: "列印" },
    { front: "pull over", pos: "phr. v.", def: "to drive to the side of the road and stop", example: "The police officer signalled to the driver to pull over.", zh: "靠邊停車" },
    { front: "pull through", pos: "phr. v.", def: "to recover from a serious illness or difficult situation", example: "It was a bad accident, but the doctors say he will pull through.", zh: "度過難關；康復" },
    { front: "put aside", pos: "phr. v.", def: "to save money for later; to ignore a disagreement for now", example: "They put aside a little money each month for a holiday.", zh: "存下；擱置" },
    { front: "put away", pos: "phr. v.", def: "to put something back in its usual place", example: "Put away your phones before the test begins.", zh: "收好" },
    { front: "put down", pos: "phr. v.", def: "to place something on a surface; to criticise someone unkindly", example: "He put down his bag and collapsed onto the sofa.", zh: "放下；貶低" },
    { front: "put forward", pos: "phr. v.", def: "to suggest an idea or plan for discussion", example: "She put forward a plan to reduce waste at school.", zh: "提出" },
    { front: "put on", pos: "phr. v.", def: "to dress yourself in something; to organise a show or event", example: "Put on a coat — it is freezing outside.", zh: "穿上；舉辦" },
    { front: "put together", pos: "phr. v.", def: "to assemble something from parts; to prepare something", example: "It took us two hours to put together the bookshelf.", zh: "組裝；彙整" },
    { front: "put up", pos: "phr. v.", def: "to build or attach something; to let someone stay in your home", example: "They put up a tent in the garden for the kids.", zh: "搭建；留宿" },
    { front: "rip off", pos: "phr. v.", def: "to charge someone far too much money", example: "The taxi driver ripped us off on the way from the airport.", zh: "敲竹槓" },
    { front: "rule out", pos: "phr. v.", def: "to decide that something is not possible or suitable", example: "Doctors ruled out anything serious after the tests.", zh: "排除" },
    { front: "run through", pos: "phr. v.", def: "to practise or explain something quickly from start to finish", example: "Let's run through the presentation one last time.", zh: "排練；快速講解" },
    { front: "sell out", pos: "phr. v.", def: "to be sold completely so none is left", example: "Tickets for the final sold out within an hour.", zh: "售罄" },
    { front: "send back", pos: "phr. v.", def: "to return something because it is wrong or damaged", example: "The soup was cold, so she sent it back.", zh: "退回" },
    { front: "send off", pos: "phr. v.", def: "to post something; to order a player to leave the field", example: "The striker was sent off for a dangerous tackle.", zh: "寄出；罰下場" },
    { front: "set aside", pos: "phr. v.", def: "to keep something, especially time or money, for a purpose", example: "Set aside an hour a day for revision.", zh: "留出；撥出" },
    { front: "set out", pos: "phr. v.", def: "to begin a journey; to start with a particular aim", example: "We set out at dawn to avoid the traffic.", zh: "出發；著手" },
    { front: "settle in", pos: "phr. v.", def: "to become comfortable in a new home, job or school", example: "It took a few weeks to settle in at my new school.", zh: "適應新環境" },
    { front: "show around", pos: "phr. v.", def: "to guide someone around a place for the first time", example: "A student volunteer showed us around the campus.", zh: "帶…參觀" },
    { front: "shut down", pos: "phr. v.", def: "to stop a machine, business or system from operating", example: "The website shut down for maintenance last night.", zh: "關閉；停業" },
    { front: "slip up", pos: "phr. v.", def: "to make a careless mistake", example: "The waiter slipped up and brought us the wrong order.", zh: "出差錯" },
    { front: "speed up", pos: "phr. v.", def: "to move or happen faster", example: "The train speeded up as it left the city.", zh: "加速" },
    { front: "splash out", pos: "phr. v.", def: "to spend a lot of money on something you do not really need", example: "They splashed out on a five-star hotel for their anniversary.", zh: "揮霍；大手筆花錢" },
    { front: "make a living", pos: "collocation", def: "to earn enough money to live", example: "He makes a living selling handmade furniture.", zh: "謀生" },
    { front: "make a complaint", pos: "collocation", def: "to formally say you are unhappy about something", example: "She made a complaint about the noisy hotel room.", zh: "投訴" },
    { front: "make a reservation", pos: "collocation", def: "to book a table, room or ticket in advance", example: "I made a reservation for two at eight o'clock.", zh: "預訂" },
    { front: "make a mistake", pos: "collocation", def: "to do something wrong by accident", example: "Everyone makes mistakes when learning a language.", zh: "犯錯" },
    { front: "do research", pos: "collocation", def: "to study something carefully to discover new information", example: "She is doing research on how children learn to read.", zh: "做研究" },
    { front: "take notes", pos: "collocation", def: "to write down important points during a lesson or meeting", example: "I always take notes during lectures so I can revise later.", zh: "做筆記" },
    { front: "take responsibility", pos: "collocation", def: "to accept that you are the one who must deal with something", example: "The manager took responsibility for the delay.", zh: "承擔責任" },
    { front: "take a nap", pos: "collocation", def: "to sleep for a short time during the day", example: "Grandma takes a nap after lunch every day.", zh: "小睡" },
    { front: "take a deep breath", pos: "collocation", def: "to breathe in slowly, often to stay calm", example: "Take a deep breath before you walk on stage.", zh: "深呼吸" },
    { front: "keep fit", pos: "collocation", def: "to stay healthy through exercise", example: "Swimming twice a week helps me keep fit.", zh: "保持健康" },
    { front: "lose weight", pos: "collocation", def: "to become lighter and thinner", example: "He lost weight by cutting out fizzy drinks.", zh: "減重" },
    { front: "gain weight", pos: "collocation", def: "to become heavier", example: "Many students gain weight in their first year away from home.", zh: "增重" },
    { front: "catch the bus", pos: "collocation", def: "to get on a bus in time to travel on it", example: "I have to leave now or I will not catch the bus.", zh: "趕上公車" },
    { front: "rush hour", pos: "collocation", def: "the time of day when traffic is heaviest", example: "Avoid the underground during rush hour if you can.", zh: "尖峰時間" },
    { front: "traffic jam", pos: "collocation", def: "a long line of vehicles that cannot move or move slowly", example: "We sat in a traffic jam for over an hour.", zh: "塞車" },
    { front: "public transport", pos: "collocation", def: "buses, trains and other transport for everyone to use", example: "Public transport in the city is cheap and reliable.", zh: "大眾運輸" },
    { front: "driving licence", pos: "collocation", def: "an official document that allows you to drive", example: "She passed her test and got her driving licence at eighteen.", zh: "駕照" },
    { front: "side effect", pos: "collocation", def: "an extra, usually unwanted, effect of a medicine or action", example: "The most common side effect of the drug is a headache.", zh: "副作用" },
    { front: "common sense", pos: "collocation", def: "the ability to make sensible decisions in everyday life", example: "Use your common sense and do not swim alone at night.", zh: "常識" },
    { front: "first aid", pos: "collocation", def: "simple medical help given quickly to an injured person", example: "Every teacher at the camp is trained in first aid.", zh: "急救" },
    { front: "climate change", pos: "collocation", def: "long-term changes in the world's weather patterns", example: "Climate change is causing more extreme storms.", zh: "氣候變遷" },
    { front: "global warming", pos: "collocation", def: "the rise in the Earth's temperature caused by pollution", example: "Global warming is melting ice at the poles.", zh: "全球暖化" },
    { front: "fossil fuels", pos: "collocation", def: "fuels such as coal, oil and gas formed underground long ago", example: "We need to burn fewer fossil fuels to protect the planet.", zh: "化石燃料" },
    { front: "solar panel", pos: "collocation", def: "a piece of equipment that turns sunlight into electricity", example: "They installed solar panels on the roof last summer.", zh: "太陽能板" },
    { front: "balanced diet", pos: "collocation", def: "a mix of foods that gives your body everything it needs", example: "A balanced diet includes plenty of fruit and vegetables.", zh: "均衡飲食" },
    { front: "junk food", pos: "collocation", def: "food that tastes good but is bad for your health", example: "He promised to eat less junk food during exam season.", zh: "垃圾食物" },
    { front: "home-cooked meal", pos: "collocation", def: "food prepared at home rather than bought ready-made", example: "After a month of travelling, I missed a good home-cooked meal.", zh: "家常菜" },
    { front: "packed lunch", pos: "collocation", def: "food you prepare at home and take to school or work", example: "Mum made me a packed lunch for the school trip.", zh: "自備午餐" },
    { front: "strong wind", pos: "collocation", def: "wind that blows with great force", example: "Strong winds blew the umbrellas across the beach.", zh: "強風" },
    { front: "torrential rain", pos: "collocation", def: "extremely heavy rain", example: "The match was cancelled because of torrential rain.", zh: "豪雨" },
    { front: "full-time job", pos: "collocation", def: "a job you do for the whole working week", example: "She found a full-time job soon after graduating.", zh: "全職工作" },
    { front: "tight schedule", pos: "collocation", def: "a plan with very little free time in it", example: "We are on a tight schedule, so please be on time.", zh: "緊湊的行程" },
    { front: "spare time", pos: "collocation", def: "time when you are free to do what you like", example: "In his spare time he builds model aeroplanes.", zh: "空閒時間" },
    { front: "quality time", pos: "collocation", def: "time you spend giving someone your full attention", example: "Weekends are for quality time with the kids.", zh: "寶貴的相處時光" },
    { front: "fresh air", pos: "collocation", def: "clean air outside, especially away from the city", example: "Let's go for a walk and get some fresh air.", zh: "新鮮空氣" },
    { front: "sense of humour", pos: "collocation", def: "the ability to find things funny and make others laugh", example: "I like people with a good sense of humour.", zh: "幽默感" },
    { front: "peer pressure", pos: "collocation", def: "the influence of friends of your own age on your behaviour", example: "Peer pressure made him try smoking, which he regrets.", zh: "同儕壓力" },
    { front: "mother tongue", pos: "collocation", def: "the first language you learn as a child", example: "Her mother tongue is Portuguese, but she also speaks English.", zh: "母語" },
    { front: "body language", pos: "collocation", def: "the way your body movements show your feelings", example: "His body language showed that he was nervous.", zh: "肢體語言" },
    { front: "eye contact", pos: "collocation", def: "looking directly into someone's eyes while communicating", example: "Try to keep eye contact during a job interview.", zh: "眼神接觸" },
    { front: "small talk", pos: "collocation", def: "polite conversation about unimportant things", example: "We made small talk about the weather while we waited.", zh: "閒聊" },
    { front: "word of mouth", pos: "collocation", def: "information passed from person to person by speaking", example: "The little restaurant became popular by word of mouth.", zh: "口耳相傳" },
    { front: "breaking news", pos: "collocation", def: "news about something that has just happened", example: "The programme was interrupted by breaking news of the storm.", zh: "即時新聞" },
    { front: "social media", pos: "collocation", def: "websites and apps where people share content and connect", example: "The band announced the tour on social media first.", zh: "社群媒體" },
    { front: "standing ovation", pos: "collocation", def: "when an audience stands up and claps to show great approval", example: "The singer received a standing ovation at the end.", zh: "起立鼓掌" },
    { front: "box office", pos: "collocation", def: "the place where tickets are sold; a film's ticket sales", example: "The film broke box office records in its first week.", zh: "售票處；票房" },
    { front: "work of art", pos: "collocation", def: "a painting, sculpture or anything made with great skill", example: "The wedding cake was a real work of art.", zh: "藝術品" },
    { front: "team spirit", pos: "collocation", def: "the feeling of loyalty and cooperation among team members", example: "Winning together really improved our team spirit.", zh: "團隊精神" },
    { front: "score a goal", pos: "collocation", def: "to get a point by putting the ball into the goal", example: "She scored a goal in the last minute of the match.", zh: "進球得分" },
    { front: "extra time", pos: "collocation", def: "additional playing time when a match ends in a draw", example: "The final went to extra time and then penalties.", zh: "延長賽" },
    { front: "hit the road", pos: "idiom", def: "to leave or begin a journey", example: "It is getting late — we should hit the road.", zh: "上路；出發" },
    { front: "hit the books", pos: "idiom", def: "to start studying seriously", example: "Exams start Monday, so I need to hit the books this weekend.", zh: "用功讀書" },
    { front: "in the same boat", pos: "idiom", def: "in the same difficult situation as other people", example: "Do not worry about failing — we are all in the same boat.", zh: "處境相同" },
    { front: "over the top", pos: "idiom", def: "too extreme or exaggerated", example: "The decorations were a bit over the top for a small party.", zh: "太誇張" },
    { front: "off the top of my head", pos: "idiom", def: "from memory, without checking or thinking carefully", example: "Off the top of my head, I would say about fifty people came.", zh: "不假思索地" },
    { front: "through thick and thin", pos: "idiom", def: "through good times and bad times", example: "They have stayed friends through thick and thin.", zh: "同甘共苦" },
    { front: "on cloud nine", pos: "idiom", def: "extremely happy", example: "She was on cloud nine after passing her driving test.", zh: "欣喜若狂" },
    { front: "down in the dumps", pos: "idiom", def: "feeling sad and without hope", example: "He has been down in the dumps since his team lost.", zh: "情緒低落" },
    { front: "full of beans", pos: "idiom", def: "having a lot of energy and enthusiasm", example: "The kids were full of beans after the birthday cake.", zh: "精力充沛" },
    { front: "a breath of fresh air", pos: "idiom", def: "someone or something new, different and refreshing", example: "The new teacher is a breath of fresh air after years of boring lessons.", zh: "令人耳目一新的人事物" },
    { front: "cut corners", pos: "idiom", def: "to do something quickly and cheaply, lowering the quality", example: "The builder cut corners, and now the roof leaks.", zh: "偷工減料" },
    { front: "call it a day", pos: "idiom", def: "to stop working on something for the day", example: "We have painted three rooms — let's call it a day.", zh: "今天到此為止" },
    { front: "go the extra mile", pos: "idiom", def: "to make more effort than is expected", example: "The staff always go the extra mile to help guests.", zh: "加倍努力" },
    { front: "learn the ropes", pos: "idiom", def: "to learn how to do a new job or activity", example: "It took me a month to learn the ropes at the café.", zh: "學會訣竅" },
    { front: "on the ball", pos: "idiom", def: "quick to understand and react to things", example: "Our new assistant is really on the ball — nothing gets missed.", zh: "反應敏捷" },
    { front: "out of the question", pos: "idiom", def: "impossible; not allowed", example: "A holiday abroad this year is out of the question.", zh: "不可能；免談" },
    { front: "sit on the fence", pos: "idiom", def: "to avoid choosing between two sides", example: "Stop sitting on the fence and tell us which plan you prefer.", zh: "保持中立；騎牆" },
    { front: "the ball is in your court", pos: "idiom", def: "it is your turn to take action or make a decision", example: "I have sent them our offer, so now the ball is in their court.", zh: "輪到你決定" },
    { front: "throw in the towel", pos: "idiom", def: "to give up trying to do something", example: "After three failed attempts, he threw in the towel.", zh: "認輸放棄" },
    { front: "up in the air", pos: "idiom", def: "not yet decided or certain", example: "Our travel plans are still up in the air because of the strike.", zh: "懸而未決" },
    { front: "a drop in the ocean", pos: "idiom", def: "a very small amount compared with what is needed", example: "My donation is just a drop in the ocean, but every bit helps.", zh: "滄海一粟" },
    { front: "against the clock", pos: "idiom", def: "in a hurry to finish before a particular time", example: "The builders worked against the clock to finish before winter.", zh: "分秒必爭" },
    { front: "back to square one", pos: "idiom", def: "back to the beginning after a failure", example: "The experiment failed, so we are back to square one.", zh: "回到原點" },
    { front: "bite off more than you can chew", pos: "idiom", def: "to try to do more than you are able to do", example: "Taking three part-time jobs was biting off more than he could chew.", zh: "不自量力" },
    { front: "blow off steam", pos: "idiom", def: "to release strong feelings or energy, often through activity", example: "He goes running after work to blow off steam.", zh: "發洩情緒" },
    { front: "burn the midnight oil", pos: "idiom", def: "to work or study late into the night", example: "She burned the midnight oil to finish her essay on time.", zh: "熬夜苦讀" },
    { front: "come rain or shine", pos: "idiom", def: "whatever happens; in any weather", example: "He walks the dog every morning, come rain or shine.", zh: "風雨無阻" },
    { front: "get out of hand", pos: "idiom", def: "to become impossible to control", example: "The party got out of hand and the neighbours called the police.", zh: "失去控制" },
    { front: "give it a shot", pos: "idiom", def: "to try something, often for the first time", example: "I have never tried surfing, but I will give it a shot.", zh: "試試看" },
    { front: "go with the flow", pos: "idiom", def: "to accept a situation and do what others are doing", example: "I had no plans for the trip — I just went with the flow.", zh: "順其自然" },
    { front: "have a sweet tooth", pos: "idiom", def: "to love eating sweet things", example: "She has a sweet tooth and never says no to chocolate.", zh: "愛吃甜食" },
    { front: "in the blink of an eye", pos: "idiom", def: "extremely quickly", example: "The holidays were over in the blink of an eye.", zh: "一眨眼之間" },
    { front: "keep your fingers crossed", pos: "idiom", def: "to hope that something will happen", example: "Keep your fingers crossed that the weather stays dry.", zh: "祈求好運" },
    { front: "not my cup of tea", pos: "idiom", def: "not the kind of thing I like", example: "Horror films are not my cup of tea at all.", zh: "非我所好" },
    { front: "on the tip of my tongue", pos: "idiom", def: "almost remembered but not quite able to say", example: "Her name is on the tip of my tongue — give me a second.", zh: "話到嘴邊想不起來" },
    { front: "out of shape", pos: "idiom", def: "not physically fit", example: "I got so out of shape during winter that I could not run a mile.", zh: "身材走樣；體能差" },
    { front: "pull yourself together", pos: "idiom", def: "to control your emotions and behave calmly", example: "Pull yourself together — the interview starts in five minutes.", zh: "振作起來" },
    { front: "ring a bell", pos: "idiom", def: "to sound familiar", example: "The name rings a bell, but I cannot remember where I heard it.", zh: "有點印象" },
    { front: "run in the family", pos: "idiom", def: "to be a quality shared by many members of a family", example: "Musical talent runs in the family — they all play instruments.", zh: "家族遺傳" },
    { front: "safe and sound", pos: "idiom", def: "unharmed after a journey or dangerous situation", example: "After the storm, everyone arrived home safe and sound.", zh: "平安無事" },
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
