/* CPE Prep extra bank: part2 wave 2 */
(function () {
  var BANK = [
    { text: "She worded the letter with extreme care ____ any offence be taken.", answers: ["lest"], explanation: "'Lest' introduces a feared outcome and takes the bare subjunctive ('be taken'), which rules out 'in case'." },
    { text: "The college operates a mentoring scheme ____ each first-year student is paired with a finalist.", answers: ["whereby", "wherein"], explanation: "'Whereby' (or formal 'wherein') introduces a relative clause describing how the scheme works." },
    { text: "He demanded a written apology, failing ____ he would take legal action.", answers: ["which"], explanation: "'Failing which' is a formal fixed connector meaning 'and if that does not happen'." },
    { text: "____ matter how compelling the evidence, some people will simply refuse to believe it.", answers: ["no"], explanation: "'No matter how + adjective' means 'however compelling the evidence may be'." },
    { text: "Hardly had the applause died away ____ the fire alarm went off.", answers: ["when", "before"], explanation: "'Hardly had X happened when/before Y' pairs the inverted 'hardly' clause with 'when' or 'before'." },
    { text: "She can hardly afford the rent on this flat, ____ alone a mortgage.", answers: ["let"], explanation: "'Let alone' follows a negative idea to introduce something even less likely." },
    { text: "He never even acknowledged the letter, ____ less replied to it.", answers: ["much", "still", "far"], explanation: "'Much/still/far less' after a negative means 'and even less likely, X'." },
    { text: "____ that as it may, the deadline stands and must be met.", answers: ["be"], explanation: "'Be that as it may' is a fossilized subjunctive concession meaning 'even so'." },
    { text: "The service on this line has deteriorated markedly ____ late.", answers: ["of"], explanation: "'Of late' is a formal fixed phrase meaning 'recently'." },
    { text: "The comparison is instructive only ____ as the two economies are structurally similar.", answers: ["insofar", "inasmuch"], explanation: "'Insofar/inasmuch as' means 'to the extent that', limiting the scope of the claim." },
    { text: "____ was the force of the explosion that windows shattered three streets away.", answers: ["such"], explanation: "Fronted 'Such was X that...' is an emphatic inversion meaning 'X was so great that'." },
    { text: "The vaccine has ____ far proved safe in every trial conducted.", answers: ["so", "thus"], explanation: "'So far' and 'thus far' both mean 'up to now'." },
    { text: "Only by pooling their resources ____ the villagers able to rebuild the school.", answers: ["were", "are"], explanation: "Fronted 'Only by...' forces inversion; 'able' requires a form of 'be' ('were/are the villagers able')." },
    { text: "____ this house bring you both as much happiness as it brought us.", answers: ["may"], explanation: "Optative 'may' + bare infinitive expresses a formal wish: 'May this house bring you...'." },
    { text: "How ____ you suggest that I falsified the results!", answers: ["dare"], explanation: "'How dare you + bare infinitive' is the fixed formula for indignant protest." },
    { text: "The stain simply ____ not come out, however hard she scrubbed.", answers: ["would", "did"], explanation: "Past 'would not' expresses stubborn refusal (even of things); plain past 'did not' also fits before the bare verb 'come'." },
    { text: "The company never confirmed the report, ____ did it issue a denial.", answers: ["nor", "neither"], explanation: "'Nor/neither did it...' continues a negative statement with inversion." },
    { text: "____ remains, however, the thorny question of who is to foot the bill.", answers: ["there"], explanation: "Formal existential inversion: 'There remains the question of...'." },
    { text: "The judge made ____ plain that any further outburst would result in a contempt charge.", answers: ["it"], explanation: "Anticipatory 'it' stands for the that-clause: 'made it plain that...'." },
    { text: "The dispute is not really about money at all; it is ____ of principle.", answers: ["one"], explanation: "'One' substitutes for 'a dispute': 'it is one of principle' = 'a dispute of principle'." },
    { text: "____ the report fails to address is how the scheme is to be funded.", answers: ["what"], explanation: "Pseudo-cleft: 'What X fails to address is Y' focuses attention on Y." },
    { text: "____ leaked the memo clearly had access to the minister's private office.", answers: ["whoever", "whosoever"], explanation: "The nominal relative 'whoever' means 'the person, whoever it was, who leaked it'." },
    { text: "____ you do, don't sign anything until your lawyer has seen it.", answers: ["whatever"], explanation: "'Whatever you do' is a fixed emphatic warning formula meaning 'above all'." },
    { text: "My colleagues weren't consulted about the changes, and I wasn't ____.", answers: ["either"], explanation: "'Either' echoes a preceding negative: 'and I wasn't (consulted) either'." },
    { text: "You ____ to have seen the state of the kitchen after the party.", answers: ["ought"], explanation: "'You ought to have seen X' is an exclamatory way of saying it was remarkable." },
    { text: "There ____ to be an orchard where the car park now stands.", answers: ["used"], explanation: "'There used to be' describes a past state that no longer holds." },
    { text: "____ bitten, twice shy.", answers: ["once"], explanation: "The proverb 'Once bitten, twice shy' means a bad experience makes one cautious." },
    { text: "Heaven ____ that we should ever have to use the emergency procedures in earnest.", answers: ["forbid"], explanation: "'Heaven forbid (that)...' is a fixed subjunctive formula meaning 'may it never happen'." },
    { text: "Her second novel is every ____ as accomplished as her first.", answers: ["bit"], explanation: "'Every bit as X as Y' emphatically asserts equality." },
    { text: "____ that the funds have run out, the excavation will have to be suspended.", answers: ["now", "seeing", "given", "considering"], explanation: "'Now/seeing/given/considering that...' all introduce the reason for the consequence." },
    { text: "She was on the ____ of deleting the file when she noticed the discrepancy.", answers: ["point", "verge", "brink"], explanation: "'On the point/verge/brink of doing something' means 'just about to do it'." },
    { text: "Stranded on the mountainside overnight, the climbers were at the ____ of the elements.", answers: ["mercy"], explanation: "'At the mercy of' means completely in the power of, unable to protect oneself from." },
    { text: "In the ____ of recent revelations, the minister's position looks increasingly untenable.", answers: ["light", "wake", "face", "aftermath"], explanation: "'In the light/wake/aftermath of' means 'because of, following'; 'in the face of' means 'confronted with'." },
    { text: "He kept his doubts about the merger to himself for ____ of undermining morale.", answers: ["fear"], explanation: "'For fear of doing X' means 'so as not to risk doing X'." },
    { text: "The regulations are being reviewed with a ____ to simplifying the application process.", answers: ["view"], explanation: "'With a view to + gerund' expresses purpose; the article 'a' rules out 'an eye'." },
    { text: "The sparse staging is entirely in ____ with the director's minimalist aesthetic.", answers: ["keeping", "line", "tune", "harmony", "step", "accordance", "accord"], explanation: "'In keeping/line/tune/harmony/step/accordance with' all mean 'consistent with'." },
    { text: "The survey measures perceived, as ____ to actual, levels of crime.", answers: ["opposed"], explanation: "'As opposed to' contrasts one thing explicitly with another." },
    { text: "As far as the budget is ____, we have very little room for manoeuvre.", answers: ["concerned"], explanation: "'As far as X is concerned' is the fixed frame for 'regarding X'." },
    { text: "The two editors have been at daggers ____ for months over the paper's political line.", answers: ["drawn"], explanation: "'At daggers drawn' is a fixed idiom meaning 'in open hostility'." },
    { text: "The residents petitioned the council repeatedly, but to no ____.", answers: ["avail", "effect", "purpose"], explanation: "'To no avail/effect/purpose' means 'without achieving anything'." },
    { text: "I called at his office on the ____ chance that he might be free for lunch.", answers: ["off"], explanation: "'On the off chance that' means 'in the faint hope that'." },
    { text: "In ____, accepting the first offer would have been the wiser course.", answers: ["retrospect", "hindsight"], explanation: "'In retrospect/hindsight' means 'looking back now at what happened'." },
    { text: "The vaccine's very long-term effects are ____ yet unknown.", answers: ["as"], explanation: "'As yet' means 'up to now (but this may change)'." },
    { text: "The experts confessed themselves at a ____ to explain the anomalous readings.", answers: ["loss"], explanation: "'At a loss to do something' means unable to do it." },
    { text: "Six months on, the renovations are still ____ near finished.", answers: ["nowhere"], explanation: "'Nowhere near + adjective' means 'not remotely, far from'." },
    { text: "Despite its title, the lecture was ____ but introductory; half the audience was lost within minutes.", answers: ["anything"], explanation: "'Anything but X' means 'not at all X'; the context excludes 'all but' (= almost)." },
    { text: "With the rise of digital printing, the craft of hand-setting type has ____ but disappeared.", answers: ["all"], explanation: "'All but + verb' means 'almost completely'." },
    { text: "By walking out of the meeting, she as ____ as conceded defeat.", answers: ["good", "much"], explanation: "'As good as' and 'as much as' before a verb mean 'virtually, in effect'." },
    { text: "There's no point waiting for the last bus now; we might as ____ walk.", answers: ["well"], explanation: "'Might as well' suggests an action because there is no better alternative." },
    { text: "It is high ____ the airport's ageing radar system was replaced.", answers: ["time"], explanation: "'It is high time + past tense' means the action is already overdue." },
    { text: "The two cases differ ____ that only one of them involved premeditation.", answers: ["in"], explanation: "'Differ in that...' means 'differ in the respect that'." },
    { text: "The appeal was dismissed on the ____ that no new evidence had been presented.", answers: ["grounds", "ground", "basis"], explanation: "'On the grounds/ground/basis that' introduces the official reason for a decision." },
    { text: "The airline cut turnaround times, but at the ____ of routine maintenance.", answers: ["expense", "cost", "price"], explanation: "'At the expense/cost/price of X' means X was sacrificed to achieve it." },
    { text: "Rehearsals for the winter season are already well ____ way.", answers: ["under"], explanation: "'Under way' means 'in progress'; 'well under way' = at an advanced stage." },
    { text: "With three hundred jobs at ____, the talks could hardly be more delicate.", answers: ["stake", "risk"], explanation: "'At stake' and 'at risk' both mean liable to be lost." },
    { text: "Several reviewers took ____ with the book's central premise.", answers: ["issue", "exception", "umbrage"], explanation: "'Take issue/exception/umbrage with' means to object to or be offended by." },
    { text: "The unexplained payments gave ____ to suspicions of bribery.", answers: ["rise"], explanation: "'Give rise to' means 'cause, provoke'." },
    { text: "The captain paid scant ____ to the coastguard's repeated warnings.", answers: ["heed", "attention", "regard"], explanation: "'Pay scant heed/attention/regard to' means to largely ignore." },
    { text: "The garrison held out for six weeks in the ____ of overwhelming odds.", answers: ["face", "teeth"], explanation: "'In the face/teeth of' means 'despite direct opposition from'." },
    { text: "The project faces numerous obstacles, not ____ the chronic shortage of skilled labour.", answers: ["least"], explanation: "'Not least' singles out one especially important example." },
    { text: "____ to the astonishment of the pundits, the incumbent conceded before midnight.", answers: ["much"], explanation: "'Much to someone's astonishment/surprise' intensifies the reaction." },
    { text: "Genuine bargains at these auctions are few and far ____.", answers: ["between"], explanation: "'Few and far between' is a fixed idiom meaning 'rare'." },
    { text: "As it ____, I was in the building on the very day of the robbery.", answers: ["happens", "happened", "chanced"], explanation: "'As it happens/happened' introduces a coincidental fact." },
    { text: "____ to say, none of the stolen money was ever recovered.", answers: ["needless"], explanation: "'Needless to say' is a fixed phrase meaning 'obviously'." },
    { text: "Economists are fond of pointing out that there is no ____ thing as a free lunch.", answers: ["such"], explanation: "'No such thing as X' denies that X exists at all." },
    { text: "The passengers were badly shaken but otherwise none the ____ for their ordeal.", answers: ["worse"], explanation: "'None the worse for X' means 'not harmed by X'." },
    { text: "Seldom, if ____, has a flagship policy been reversed so swiftly.", answers: ["ever"], explanation: "'Seldom, if ever' means 'rarely, and perhaps never'." },
    { text: "The payment was a gift and, ____ such, is not liable to income tax.", answers: ["as"], explanation: "'As such' means 'in that capacity, being what it is'." },
    { text: "It is not the technology ____ se that worries regulators, but the uses to which it may be put.", answers: ["per"], explanation: "'Per se' is a Latin fixed phrase meaning 'in itself'." },
    { text: "Staff who are required to work on public holidays may take time off in ____.", answers: ["lieu"], explanation: "'In lieu' means 'instead, as a substitute (for the time worked)'." },
    { text: "She rose to the top of a crowded profession by ____ of sheer persistence.", answers: ["dint", "virtue"], explanation: "'By dint/virtue of' means 'through, as a result of'." },
    { text: "Let us assume, for the ____ of argument, that the witness is telling the truth.", answers: ["sake"], explanation: "'For the sake of argument' means 'purely as a hypothesis to discuss'." },
    { text: "He was offered the post on the ____ of a single dazzling interview.", answers: ["strength", "basis", "back"], explanation: "'On the strength/basis/back of X' means X was the justification for the decision." },
    { text: "This is the most comprehensive survey of the reef undertaken ____ date.", answers: ["to"], explanation: "'To date' means 'up to the present time'." },
    { text: "The treaty cannot come ____ force until every signatory has ratified it.", answers: ["into"], explanation: "'Come into force' means to become legally effective." },
    { text: "Keep a fire extinguisher close ____ hand whenever you are welding.", answers: ["at", "to"], explanation: "'Close at hand' (also British 'close to hand') means within easy reach." },
    { text: "Few of the colonists suspected what lay in ____ for them.", answers: ["store", "wait"], explanation: "'Lie in store for' means 'await in the future'; 'lie in wait for' suggests lurking danger." },
    { text: "Two of the escapees were recaptured within hours; the third remains ____ large.", answers: ["at"], explanation: "'At large' describes an escaped prisoner still free." },
    { text: "As a boy he learnt whole cantos of Dante ____ heart.", answers: ["by"], explanation: "'Learn something by heart' means to memorize it perfectly." },
    { text: "During the siege, the shelling continued for days ____ end.", answers: ["on"], explanation: "'For days on end' means 'for many days continuously'." },
    { text: "The virus can apparently switch its surface proteins ____ will.", answers: ["at"], explanation: "'At will' means 'whenever and however it chooses'." },
    { text: "Rescuers searched the ravine for a whole week, but in ____.", answers: ["vain"], explanation: "'In vain' means 'without success'." },
    { text: "He was generous to a fault and, alas, drank ____ excess.", answers: ["to"], explanation: "'To excess' means 'more than is sensible or healthy'." },
    { text: "Quite why the committee approved such a flawed design is ____ me.", answers: ["beyond"], explanation: "'Beyond me' means 'impossible for me to understand'." },
    { text: "____ the question of compensation, the company maintains a studied silence.", answers: ["regarding", "concerning", "on"], explanation: "'Regarding/concerning/on the question of X' introduces the topic being addressed." },
    { text: "The children of the estate wanted ____ nothing materially, yet saw little of their parents.", answers: ["for"], explanation: "'Want for nothing' means to have everything one needs." },
    { text: "He never answers my emails — ____ that I particularly mind.", answers: ["not"], explanation: "'Not that I mind' retracts a possible implication: 'though I don't actually mind'." },
    { text: "The safe was locked and only she knew the code; how ____ could the documents have vanished?", answers: ["else"], explanation: "'How else' asks what other way is possible, implying there is none." },
    { text: "That the climate is changing is now beyond ____; the causes remain contested.", answers: ["dispute", "doubt", "question", "argument", "debate"], explanation: "'Beyond dispute/doubt/question' means impossible to deny." },
    { text: "In the absence of conclusive proof, the tribunal gave the accused the benefit of the ____.", answers: ["doubt"], explanation: "'Give someone the benefit of the doubt' means to assume they are innocent or right." },
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part2 = QUESTIONS.part2.concat(BANK);
})();
