/* CPE Prep extra bank: part2 wave 5 */
(function () {
  var BANK = [
    { text: "____ so much as a backward glance, she boarded the train and was gone.", answers: ["without"], explanation: "'Without so much as X' emphasises the absence of even a minimal gesture; only 'without' fits before the gerund-like noun phrase." },
    { text: "Just ____ the jury arrived at that verdict remains a mystery to legal scholars.", answers: ["how"], explanation: "An embedded question acts as subject of 'remains'; 'just how' asks about the manner, the only reading the sentence allows." },
    { text: "Oddly ____, the quietest candidate proved the most persuasive.", answers: ["enough"], explanation: "'Oddly enough' is a fixed sentence adverbial meaning 'strange as it may seem'; 'enough' follows the adverb it intensifies." },
    { text: "____ before had the observatory recorded so violent a solar flare.", answers: ["never"], explanation: "Fronted negative 'Never before' triggers the inversion 'had the observatory recorded'; only 'never' yields this emphatic structure." },
    { text: "You had ____ declare those earnings before the auditors unearth them themselves.", answers: ["better"], explanation: "'Had better + bare infinitive' expresses strong advice with a hint of warning; no other word follows 'had' this way." },
    { text: "The evidence was, at ____, circumstantial, and at worst pure fabrication.", answers: ["best"], explanation: "'At best... at worst...' frames the two extremes of an assessment; the contrast with 'at worst' forces 'best'." },
    { text: "At ____, the delay will cost us a fortnight; it may well cost the whole season.", answers: ["worst", "most"], explanation: "'At worst/at most' caps the estimate at its upper extreme, which the follow-up 'may well cost more' then undercuts." },
    { text: "For the ____ part, the reviews were kinder than the film deserved.", answers: ["most"], explanation: "'For the most part' is a fixed adverbial meaning 'mostly, in general'." },
    { text: "He told them in so ____ words that their services were no longer required.", answers: ["many"], explanation: "'In so many words' means explicitly and directly; the idiom admits no substitute for 'many'." },
    { text: "Loyalty, in this trade, is a blade that cuts ____ ways.", answers: ["both"], explanation: "'To cut both ways' means to have advantages and disadvantages for each side; 'both' is fixed in the idiom." },
    { text: "One way or ____, the debt will have to be honoured.", answers: ["another"], explanation: "'One way or another' means by some means or other; 'one... another' is the required correlative pair." },
    { text: "The rumour, once planted, took on a life of ____ own.", answers: ["its"], explanation: "'Take on a life of its own' needs the possessive agreeing with 'the rumour', hence neuter singular 'its'." },
    { text: "I caught ____ nodding along to an argument I had spent years refuting.", answers: ["myself"], explanation: "'Catch oneself doing something' means to suddenly notice one's own behaviour; the first-person subject demands 'myself'." },
    { text: "By blushing whenever her name was mentioned, he gave the game ____ completely.", answers: ["away"], explanation: "'Give the game away' means to betray a secret unintentionally; the phrasal particle is 'away'." },
    { text: "Delegates shuttled back and ____ between the two negotiating rooms.", answers: ["forth"], explanation: "'Back and forth' is the fixed binomial for repeated movement in two directions." },
    { text: "Invoices are reconciled against purchase orders as a ____ of course.", answers: ["matter"], explanation: "'As a matter of course' means as part of normal routine procedure." },
    { text: "If ____ be, we can always convert the garage into a studio.", answers: ["need"], explanation: "'If need be' is a fossilised subjunctive meaning 'if it should prove necessary'." },
    { text: "As luck would ____ it, the only witness had been abroad that night.", answers: ["have"], explanation: "'As luck would have it' is the fixed formula introducing a fortunate or unfortunate coincidence." },
    { text: "Stranded by the storm, we resolved to make the ____ of an unplanned holiday.", answers: ["best", "most"], explanation: "'Make the best/most of something' means to exploit an imperfect situation as fully as possible; both superlatives are idiomatic here." },
    { text: "You are welcome to share our little library, such ____ it is.", answers: ["as"], explanation: "'Such as it is' is a self-deprecating tag conceding that the thing offered is of modest quality." },
    { text: "____ that I had heeded her warning while there was still time!", answers: ["would"], explanation: "Optative 'Would that + past subjunctive' expresses a regretful wish, equivalent to 'if only I had heeded'." },
    { text: "She ought to have known better ____ to lend him the manuscript.", answers: ["than"], explanation: "'Know better than to do something' means to be wise enough not to do it; the comparative 'better' requires 'than'." },
    { text: "The keynote was delivered by none other ____ the reclusive laureate herself.", answers: ["than"], explanation: "'None other than' is the emphatic identifying formula signalling a surprising or illustrious person." },
    { text: "All ____ a handful of the crew survived the crossing.", answers: ["but"], explanation: "Quantifier 'all but X' means 'all except X'; 'but' functions here as a preposition of exception." },
    { text: "Not ____ single pane of glass survived the blast.", answers: ["a", "one"], explanation: "Emphatic negation 'not a/one single + noun' stresses that there were zero exceptions." },
    { text: "Her composure made his outburst all ____ more embarrassing.", answers: ["the"], explanation: "'All the more + adjective' intensifies a comparative in the light of a given circumstance; 'the' is obligatory before the comparative." },
    { text: "The apology, in ____ of itself, repairs nothing.", answers: ["and"], explanation: "'In and of itself' is the fixed formula meaning 'considered intrinsically, on its own'." },
    { text: "He looked every ____ the seasoned diplomat as he defused the row.", answers: ["inch", "bit"], explanation: "'Every inch/bit the + noun' means completely and visibly the very type of person named." },
    { text: "The itinerary had been choreographed to the ____ degree.", answers: ["nth"], explanation: "'To the nth degree' means to the utmost possible extent, borrowing the mathematical 'n'." },
    { text: "In the ____ instance, grievances should be raised with your line manager.", answers: ["first"], explanation: "'In the first instance' is formal register for 'as the first step in a procedure'." },
    { text: "As a restorer of early keyboard instruments, she is second ____ none.", answers: ["to"], explanation: "'Second to none' means unsurpassed, inferior to nobody; the idiom requires 'to'." },
    { text: "The chateau, half in ruins, fetched next ____ nothing at auction.", answers: ["to"], explanation: "'Next to nothing' means almost nothing; 'next to' functions as 'almost' before negatives." },
    { text: "Medieval workshops stand cheek ____ jowl along the alley.", answers: ["by"], explanation: "'Cheek by jowl' is the fixed binomial meaning crowded closely side by side." },
    { text: "The neighbours' philosophy was simple: live and ____ live.", answers: ["let"], explanation: "'Live and let live' expresses mutual tolerance; the causative 'let' with bare infinitive is fixed." },
    { text: "The alibi, however elaborate, simply does not ____ water.", answers: ["hold"], explanation: "'Hold water' (of an argument or story) means to withstand scrutiny; usually negative." },
    { text: "Pausing to ____ stock of our losses, we decided against a counterattack.", answers: ["take"], explanation: "'Take stock of' means to assess a situation carefully before proceeding." },
    { text: "The scandal must be allowed to run its ____ before any rebuilding can begin.", answers: ["course"], explanation: "'Run its course' means to develop and end naturally without interference." },
    { text: "The commission will publish its findings in due ____.", answers: ["course"], explanation: "'In due course' means at the appropriate time in the natural sequence of events." },
    { text: "Their objections were given short ____ by the chairman.", answers: ["shrift"], explanation: "'Give something short shrift' means to dismiss it quickly and unsympathetically." },
    { text: "We had been talking at cross ____ for an hour before we noticed we agreed.", answers: ["purposes"], explanation: "'At cross purposes' describes two people unknowingly discussing different things or aims." },
    { text: "Qualified actuaries are in desperately short ____ this year.", answers: ["supply"], explanation: "'In short supply' means scarce; the modifier 'desperately short' locks in the noun 'supply'." },
    { text: "After a month in hospital, grandfather is finally on the ____.", answers: ["mend"], explanation: "'On the mend' means recovering from illness or injury." },
    { text: "She had been burning the midnight ____ all week before the viva.", answers: ["oil"], explanation: "'Burn the midnight oil' means to work late into the night, from the era of oil lamps." },
    { text: "Guests began arriving on the ____ of eight, as the invitation demanded.", answers: ["stroke", "dot"], explanation: "'On the stroke/dot of eight' means at exactly eight o'clock." },
    { text: "A reprieve came at the eleventh ____, with the bulldozers already idling.", answers: ["hour"], explanation: "'At the eleventh hour' means at the last possible moment." },
    { text: "Engineers worked round the ____ to restore the grid.", answers: ["clock"], explanation: "'Round the clock' means continuously, day and night." },
    { text: "The convoy slipped across the border in the ____ of night.", answers: ["dead"], explanation: "'In the dead of night' means in the quietest, darkest hours." },
    { text: "Of ____, the tone of parliamentary debate has coarsened noticeably.", answers: ["late"], explanation: "'Of late' is a formal adverbial meaning 'recently', typically with the present perfect." },
    { text: "As ____ ago as 1911, engineers had warned that the dam was undersized.", answers: ["long"], explanation: "'As long ago as + date' stresses how early something happened; 'ago' rules out 'far' (which needs 'back')." },
    { text: "As it ____ out, the 'stolen' painting had been in the vault all along.", answers: ["turned", "turns"], explanation: "'As it turned/turns out' introduces what was eventually discovered to be the case." },
    { text: "The design is ingenious and, what is ____, cheap to manufacture.", answers: ["more"], explanation: "'What is more' is a discourse marker adding a further, stronger point." },
    { text: "If ____ else, the expedition taught them the limits of preparation.", answers: ["nothing"], explanation: "'If nothing else' concedes that this one benefit holds even if no others do." },
    { text: "By no ____ of the imagination could the flat be described as spacious.", answers: ["stretch"], explanation: "'By no stretch of the imagination' emphatically denies a description; the fronted negative also triggers inversion." },
    { text: "At first ____, the accounts appear immaculate; the rot lies deeper.", answers: ["glance", "sight", "blush"], explanation: "'At first glance/sight/blush' means on initial, superficial inspection." },
    { text: "On second ____, perhaps that letter is best left unsent.", answers: ["thoughts", "thought"], explanation: "'On second thoughts' (BrE) or 'on second thought' (AmE) signals a revised opinion." },
    { text: "The talks were convened ____ the auspices of the African Union.", answers: ["under"], explanation: "'Under the auspices of' means with the sponsorship or protection of an organisation." },
    { text: "He gained entry ____ the pretext of inspecting the wiring.", answers: ["on", "under"], explanation: "'On/under the pretext of' means using a false stated reason as cover." },
    { text: "He is vain and quarrelsome, and yet I cannot help liking him for all ____.", answers: ["that"], explanation: "'For all that' is a concessive tag meaning 'in spite of everything just mentioned'." },
    { text: "The costs spiralled — so ____ so that the sponsors withdrew.", answers: ["much"], explanation: "'So much so that' intensifies the preceding statement and introduces its consequence." },
    { text: "I cannot for the ____ of me recall where I filed the deed.", answers: ["life"], explanation: "'Cannot for the life of me' emphasises total inability despite effort, only in negative contexts." },
    { text: "Not a ____ of credible evidence has ever been produced.", answers: ["shred", "scrap", "jot", "iota", "whit", "particle"], explanation: "Emphatic negation 'not a shred/scrap/jot of' means not even the smallest amount." },
    { text: "Frankly, the electorate could not care ____ about procedural niceties.", answers: ["less"], explanation: "'Could not care less' means to be completely indifferent; the comparative 'less' marks the lowest possible degree of caring." },
    { text: "The forger and the celebrated connoisseur turned out to be one and the ____.", answers: ["same"], explanation: "'One and the same' emphatically asserts that two apparently distinct people or things are identical." },
    { text: "I will not tolerate plagiarism in ____ shape or form.", answers: ["any"], explanation: "'In any shape or form' universalises the prohibition; negative polarity 'any' is required after 'not'." },
    { text: "I would just as ____ walk the five miles as wait an hour for the bus.", answers: ["soon"], explanation: "'Would just as soon X as Y' expresses an equal or mild preference for X over Y." },
    { text: "The antidote arrived, and not a moment too ____.", answers: ["soon"], explanation: "'Not a moment too soon' means only just in time, at the last acceptable moment." },
    { text: "It is no ____ pretending the deficit will close itself.", answers: ["use", "good"], explanation: "'It is no use/good + -ing' declares an action pointless; the gerund clause is the pattern's hallmark." },
    { text: "The dress, scandalised columnists agreed, left ____ to the imagination.", answers: ["little", "nothing"], explanation: "'Leave little/nothing to the imagination' means to be very revealing; both quantifiers are idiomatic." },
    { text: "____ wonder the villagers distrust outsiders, given the mine's legacy.", answers: ["no", "little", "small"], explanation: "'No/little/small wonder (that)...' means the fact is entirely unsurprising." },
    { text: "The verdict was, in all ____, settled before the trial even began.", answers: ["likelihood", "probability"], explanation: "'In all likelihood/probability' is a formal adverbial meaning 'very probably'." },
    { text: "She knew full ____ that the signature was forged.", answers: ["well"], explanation: "'Know full well' emphasises conscious, undeniable awareness, often with an accusatory tone." },
    { text: "____ sheer force of habit, he checked the locks a second time.", answers: ["by", "from", "through"], explanation: "'By/from/through force of habit' means because of ingrained routine rather than deliberate choice." },
    { text: "The refugees pressed north in ____ of kinder borders.", answers: ["search", "quest"], explanation: "'In search/quest of' means seeking; the pattern takes no article before the noun." },
    { text: "At any ____, the manuscript is safe, whatever became of its author.", answers: ["rate"], explanation: "'At any rate' is a discourse marker meaning 'whatever else may be true, at least this holds'." },
    { text: "In any ____, the concert will go ahead, rain or shine.", answers: ["event", "case"], explanation: "'In any event/case' means whatever happens; both nouns are idiomatic in this frame." },
    { text: "The soloist improvised to such an ____ that the printed score became irrelevant.", answers: ["extent"], explanation: "'To such an extent that' expresses degree with a result clause; the article 'an' requires a vowel-initial noun, ruling out 'degree'." },
    { text: "In the long ____, appeasement merely bought the aggressor time.", answers: ["run", "term", "haul"], explanation: "'In the long run/term/haul' means over an extended period, once eventual effects are counted." },
    { text: "On ____, the reforms have done more good than harm.", answers: ["balance"], explanation: "'On balance' means after weighing all considerations against each other." },
    { text: "The tribunal found in ____ of the dismissed workers.", answers: ["favour", "favor"], explanation: "'Find in favour of' is the legal formula for deciding a case for one party." },
    { text: "In ____ for immunity, the accountant surrendered the ledgers.", answers: ["return", "exchange"], explanation: "'In return/exchange for' marks the reciprocal condition of a transaction." },
    { text: "It was purely by ____ that the two halves of the manuscript ended up in the same archive.", answers: ["chance", "accident", "coincidence", "luck"], explanation: "'Purely by chance/accident' means without any design; the cleft 'It was... that' highlights the fortuitousness." },
    { text: "The finished film is a far ____ from the script we approved.", answers: ["cry"], explanation: "'A far cry from' means very different from, usually disappointingly so." },
    { text: "The negotiations came within a hair's ____ of collapse.", answers: ["breadth"], explanation: "'Within a hair's breadth of' means extremely close to, by the width of a single hair." },
    { text: "The hermitage lies a stone's ____ from the motorway, yet feels centuries away.", answers: ["throw"], explanation: "'A stone's throw from' means a very short distance away." },
    { text: "All of a ____, the tremors ceased.", answers: ["sudden"], explanation: "'All of a sudden' is the fixed adverbial meaning 'suddenly'; 'sudden' functions as a noun only here." },
    { text: "The lead changed hands in the ____ of an eye.", answers: ["blink", "twinkling"], explanation: "'In the blink/twinkling of an eye' means almost instantaneously." },
    { text: "On ____ of the drought, the region now faces locusts.", answers: ["top"], explanation: "'On top of' means in addition to an already burdensome situation." },
    { text: "I can't quote the exact clause off the ____ of my head.", answers: ["top"], explanation: "'Off the top of my head' means from memory, without checking sources." },
    { text: "With the caterers gone, we shall simply have to make ____ with sandwiches.", answers: ["do"], explanation: "'Make do with' means to manage with an inferior substitute." },
    { text: "Only a treaty can put an ____ to the border raids.", answers: ["end", "stop"], explanation: "'Put an end/stop to' means to terminate something decisively." },
    { text: "By midnight, the night editor was at her wits' ____.", answers: ["end"], explanation: "'At one's wits' end' means so worried or frustrated that one no longer knows what to do." },
    { text: "Never lose ____ of the fact that models merely simplify reality.", answers: ["sight", "track"], explanation: "'Lose sight/track of' means to stop bearing something in mind." },
    { text: "Day ____, day out, the lighthouse keeper logged the weather.", answers: ["in"], explanation: "'Day in, day out' means every day without variation, stressing monotony." },
    { text: "Renovations dragged on well ____ the small hours.", answers: ["into"], explanation: "'Well into the small hours' expresses movement in time deep into the period after midnight." },
    { text: "Once in a ____ moon, the auction house misprices a masterpiece.", answers: ["blue"], explanation: "'Once in a blue moon' means extremely rarely." },
    { text: "The twin spires rise side by ____ above the fog.", answers: ["side"], explanation: "'Side by side' is the fixed reduplicative binomial for two things positioned next to each other." },
    { text: "Little by ____, the estuary is reclaiming the abandoned docks.", answers: ["little"], explanation: "'Little by little' means gradually, in small increments." },
    { text: "His objections, though loudly voiced, are neither here ____ there.", answers: ["nor"], explanation: "'Neither here nor there' means irrelevant; 'neither' obligatorily pairs with 'nor'." },
    { text: "He was, if you ____, the unofficial mayor of the quarter.", answers: ["will", "like", "please"], explanation: "'If you will/like' is a hedging tag inviting the listener to accept a loose or fanciful description." },
    { text: "Once Maria warms to a theme, nobody else can get a word in ____.", answers: ["edgeways", "edgewise"], explanation: "'Get a word in edgeways/edgewise' means to manage to say something when someone else is talking non-stop." },
    { text: "____ a pinch, the dinghy will hold four.", answers: ["at", "in"], explanation: "'At a pinch' (BrE) or 'in a pinch' (AmE) means if absolutely necessary, though not comfortably." },
    { text: "In a ____, the committee wants the impossible done cheaply.", answers: ["nutshell", "word"], explanation: "'In a nutshell/word' introduces the briefest possible summary of a situation." },
    { text: "I offered to reimburse her, but she would not ____ of it.", answers: ["hear", "dream"], explanation: "'Not hear/dream of it' means to refuse even to consider a proposal." },
    { text: "The club can ill ____ another relegation season.", answers: ["afford"], explanation: "'Can ill afford' is the fixed collocation meaning can scarcely bear the cost or consequences of." },
    { text: "The statute as it ____ offers whistle-blowers no protection.", answers: ["stands"], explanation: "'As it stands' means in its present unamended form." },
    { text: "Let's get the formalities over and ____ with.", answers: ["done"], explanation: "'Get something over and done with' means to finish an unpleasant task completely so it need not be faced again." },
    { text: "Sherpas think ____ of carrying such loads at altitude.", answers: ["nothing"], explanation: "'Think nothing of doing something' means to regard a remarkable feat as entirely ordinary." },
    { text: "The province has been independent in ____ but name for a decade.", answers: ["all"], explanation: "'In all but name' means effectively so, though not officially recognised as such." },
    { text: "The venture cost him his savings, to ____ nothing of his marriage.", answers: ["say"], explanation: "'To say nothing of' adds an even weightier item the speaker need hardly mention." },
    { text: "Promise me you won't ____ a word of this to the press.", answers: ["breathe"], explanation: "'Not breathe a word' means to reveal absolutely nothing, keeping a total secret." },
    { text: "True to ____, the tenor cancelled at the last minute.", answers: ["form", "type"], explanation: "'True to form/type' means behaving exactly as one's past record would predict." },
    { text: "The brochure promised sea views; the room offered nothing of the ____.", answers: ["sort", "kind"], explanation: "'Nothing of the sort/kind' emphatically denies that something matches an earlier description." },
    { text: "For one ____, the funds are already committed; for another, the permits have lapsed.", answers: ["thing"], explanation: "'For one thing..., for another...' enumerates reasons; 'thing' is fixed in the first limb." },
    { text: "To all ____, theirs was a contented marriage.", answers: ["appearances"], explanation: "'To all appearances' means judging only by what could outwardly be seen." },
    { text: "The apprentices stood in ____ of the old engraver.", answers: ["awe"], explanation: "'Stand in awe of' means to regard with reverent wonder mixed with fear." },
    { text: "The ambulance reached the clearing in the very ____ of time.", answers: ["nick"], explanation: "'In the (very) nick of time' means at the last possible moment before it would have been too late." },
    { text: "The village is barely three miles away as the crow ____.", answers: ["flies"], explanation: "'As the crow flies' measures distance in a straight line, ignoring roads and terrain." },
    { text: "The pay rise, once inflation is counted, is nothing to write ____ about.", answers: ["home"], explanation: "'Nothing to write home about' means unremarkable, not worth reporting." },
    { text: "After months of glitches, the booking system is finally up and ____.", answers: ["running"], explanation: "'Up and running' means fully operational, especially of systems and ventures." },
    { text: "I'll stay in tonight — I've been feeling a little ____ the weather.", answers: ["under"], explanation: "'Under the weather' means slightly unwell." },
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part2 = QUESTIONS.part2.concat(BANK);
})();
