/* CPE Prep extra bank: part2 wave 3 */
(function () {
  var BANK = [
    { text: "____ unforeseen complications, the patient should be discharged within a week.", answers: ["barring", "absent", "excepting"], explanation: "'Barring/absent/excepting X' means 'unless X occurs', introducing the only condition that could prevent the outcome." },
    { text: "____ the outcome of the appeal, the club's licence has been suspended.", answers: ["pending"], explanation: "'Pending' as a preposition means 'while awaiting', linking the suspension to the future decision." },
    { text: "The chairman accused her of leaking the minutes, ____ she gathered her papers and walked out.", answers: ["whereupon"], explanation: "'Whereupon' means 'immediately after which', linking an event to the reaction it provoked." },
    { text: "The fortress was built on a black basalt outcrop — ____ its name, Blackrock.", answers: ["hence"], explanation: "'Hence its name' means 'and that is the origin of its name'; no verb follows, so only 'hence' fits." },
    { text: "The senator resigned before the vote, ____ depriving the bill of its chief sponsor.", answers: ["thereby", "thus", "so"], explanation: "'Thereby/thus/so + -ing' introduces the direct result of the action just described." },
    { text: "One glaring factual error mars an ____ impeccable piece of scholarship.", answers: ["otherwise"], explanation: "'An otherwise impeccable X' means 'impeccable in every other respect'." },
    { text: "The refit will cost millions; ____ more troubling is the projected loss of jobs.", answers: ["yet", "even", "still", "far", "much"], explanation: "An intensifier before a fronted comparative: 'yet/even/still/far/much more troubling is...' with subject-verb inversion." },
    { text: "It was not ____ the 1960s that the manuscript's true author was finally identified.", answers: ["until", "till"], explanation: "Cleft structure 'It was not until X that Y' emphasises how late something happened." },
    { text: "____ when has the marketing department had a say in editorial decisions?", answers: ["since"], explanation: "'Since when...?' is an indignant question implying the situation is new and unwelcome." },
    { text: "The tasting is free of charge, and remains so ____ stocks last.", answers: ["while", "whilst"], explanation: "'While/whilst stocks last' is the fixed commercial formula meaning 'until supplies run out'." },
    { text: "You may quote the report freely, ____ that the source is properly acknowledged.", answers: ["provided", "providing"], explanation: "'Provided/providing that' means 'on the strict condition that'." },
    { text: "____ the ferry were cancelled — how would we get back to the mainland?", answers: ["supposing", "suppose", "say", "imagine"], explanation: "'Supposing/suppose/say/imagine + hypothetical clause' invites the listener to consider a possibility." },
    { text: "____ side was prepared to blink first, and so the shutdown dragged on for weeks.", answers: ["neither"], explanation: "'Neither side' refers negatively to both of exactly two parties; the positive verb rules out 'no'." },
    { text: "Willow trees line ____ bank of the canal for most of its length.", answers: ["either", "each"], explanation: "'Either/each bank' means 'both banks', treating the two banks individually with a singular noun." },
    { text: "The signed first editions fetched over two thousand pounds ____.", answers: ["each", "apiece"], explanation: "Post-posed 'each/apiece' distributes the price over the individual items." },
    { text: "The grant is payable on completion or in June, ____ comes first.", answers: ["whichever"], explanation: "'Whichever comes first' selects between the two alternatives just mentioned." },
    { text: "She interviewed dozens of veterans, many of ____ had never spoken publicly before.", answers: ["whom"], explanation: "Quantifier + 'of whom' in a non-defining relative clause referring to people: 'many of whom'." },
    { text: "The last guests left at two in the morning, by ____ time the hosts were dead on their feet.", answers: ["which"], explanation: "'By which time' is a relative connector referring back to the time just mentioned." },
    { text: "Will ____ wishing to join the excursion please sign the list by Friday.", answers: ["those", "anyone", "all"], explanation: "'Those/anyone/all wishing to...' uses a reduced relative clause to mean 'the people who wish to'." },
    { text: "The island's climate is considerably milder than ____ of the mainland.", answers: ["that"], explanation: "'That of' substitutes for 'the climate of' to avoid repeating the noun." },
    { text: "____ is more, the new device costs barely half as much as its rivals.", answers: ["what"], explanation: "'What is more' is a fixed connector adding a further, stronger point." },
    { text: "Should any symptoms persist, ____ not hesitate to consult your doctor.", answers: ["do"], explanation: "Negative imperative with the auxiliary: 'do not hesitate to...'." },
    { text: "We owe ____ to the victims' families to establish the full truth of what happened.", answers: ["it"], explanation: "Anticipatory 'it' stands for the following to-infinitive: 'owe it to someone to do something'." },
    { text: "Let there ____ no mistake: this is a full-blown crisis, not a blip.", answers: ["be"], explanation: "'Let there be no mistake' is a fixed emphatic formula with the bare infinitive 'be'." },
    { text: "He refused to apologise, and quite rightly ____, in my view.", answers: ["so", "too"], explanation: "'And rightly so/too' endorses the action just mentioned; 'so' substitutes for the whole clause." },
    { text: "The keynote address was delivered by none ____ than the reclusive laureate herself.", answers: ["other"], explanation: "'None other than' expresses surprise at a person's identity." },
    { text: "The pace of redundancies has not slowed; if ____, it has accelerated.", answers: ["anything"], explanation: "'If anything' introduces a correction suggesting the opposite tendency is true." },
    { text: "He has spent thirty-____ years in the diplomatic service — he has long since lost exact count.", answers: ["odd"], explanation: "'Thirty-odd' means 'approximately thirty, slightly more'; the lost count confirms the approximation." },
    { text: "The lighthouse was automated a century ____ so ago.", answers: ["or"], explanation: "'A century or so' means 'approximately a century'." },
    { text: "Loose slates, rising damp, dry rot — the surveyor found ____ end of problems.", answers: ["no"], explanation: "'No end of X' is an idiom meaning 'a great many X'." },
    { text: "The sequel is not ____ as inventive as the original film.", answers: ["half", "nearly", "remotely"], explanation: "'Not half/nearly/remotely as X as Y' emphatically denies equality." },
    { text: "The logistics ____ would be enough to sink the proposal, never mind the cost.", answers: ["alone", "themselves"], explanation: "Post-posed 'alone' (or emphatic 'themselves') means 'even considering just this one factor'." },
    { text: "The ____ suggestion that she might retire sent the share price tumbling.", answers: ["very", "mere", "merest", "slightest", "faintest"], explanation: "'The very/mere suggestion' emphasises that even the idea itself, without substance, had this effect." },
    { text: "The rumours died down of their ____ accord once the accounts were published.", answers: ["own"], explanation: "'Of its/their own accord' means 'spontaneously, without outside intervention'." },
    { text: "In ____ of himself, he found the farewell ceremony strangely moving.", answers: ["spite"], explanation: "'In spite of oneself' means despite one's intention or expectation not to react that way." },
    { text: "____ than entrust the diaries to a museum, she chose to burn them.", answers: ["rather", "sooner"], explanation: "Fronted 'Rather/sooner than + bare infinitive' expresses a rejected alternative." },
    { text: "The reception was polite but not ____ the triumph the organisers had hoped for.", answers: ["quite", "exactly", "precisely"], explanation: "'Not quite/exactly/precisely X' softens the denial: it fell somewhat short of X." },
    { text: "____ now, forty years on, survivors find the events almost impossible to discuss.", answers: ["even"], explanation: "'Even now' stresses that the situation persists despite the long time elapsed." },
    { text: "____ a week passes without some fresh revelation about the ministry's finances.", answers: ["hardly", "scarcely", "barely", "seldom"], explanation: "'Hardly/scarcely/barely (or seldom) a week passes without...' means revelations come almost weekly." },
    { text: "Original fittings have been preserved ____ possible throughout the restoration.", answers: ["wherever", "where", "whenever", "when", "if"], explanation: "'Wherever/where(ver) possible' is a reduced clause meaning 'in every case in which it was possible'." },
    { text: "Well ____ the shareholders demand an inquiry — the losses are staggering.", answers: ["might", "may"], explanation: "Fronted 'Well might/may X do Y' means 'X has every reason to do Y'." },
    { text: "There is ____ to choose between the two finalists; both were flawless.", answers: ["little", "nothing"], explanation: "'There is little/nothing to choose between X and Y' means they are virtually equal." },
    { text: "The old theatre is to be demolished next spring, more's the ____.", answers: ["pity"], explanation: "'More's the pity' is a fixed tag expressing regret about the fact just stated." },
    { text: "____ of next Monday, all visitors must sign in at the east gate.", answers: ["as"], explanation: "'As of + time' marks the point from which a new arrangement takes effect." },
    { text: "Whether the case proceeds to trial is ____ to the prosecutor alone.", answers: ["up", "down"], explanation: "'Be up to someone' (BrE also 'down to someone') means the decision rests with them." },
    { text: "Volunteers receive travel expenses ____ and above their daily allowance.", answers: ["over"], explanation: "'Over and above' means 'in addition to'." },
    { text: "____ all, do nothing that might alarm the hostages.", answers: ["above"], explanation: "'Above all' singles out the most important instruction." },
    { text: "He considered manual work ____ him, an attitude his grandfather despised.", answers: ["beneath", "below"], explanation: "'Beneath (or below) someone' means unworthy of their status or dignity." },
    { text: "I wouldn't put it ____ them to have leaked the story themselves.", answers: ["past"], explanation: "'Not put it past someone to do X' means to believe them quite capable of X." },
    { text: "She was just ____ to lock up for the night when the phone rang.", answers: ["about"], explanation: "'Be about to do something' means to be on the point of doing it." },
    { text: "The regulations are strict, but determined importers always find a way ____ them.", answers: ["around", "round"], explanation: "'Find a way around/round something' means to circumvent it." },
    { text: "Strictly ____ ourselves, the director is on the verge of resigning.", answers: ["between"], explanation: "'Between ourselves' marks what follows as confidential." },
    { text: "The delegation included, ____ others, two Nobel laureates and a former president.", answers: ["among", "amongst"], explanation: "'Among(st) others' indicates the list is not exhaustive." },
    { text: "____ all its scholarly apparatus, the biography sheds little new light on its subject.", answers: ["for", "despite", "notwithstanding", "with"], explanation: "Concessive 'For all / despite / notwithstanding / with all X' means 'although it has X'." },
    { text: "Frankly, the rival manifestos are much of a ____.", answers: ["muchness"], explanation: "'Much of a muchness' is a fixed idiom meaning 'barely distinguishable from each other'." },
    { text: "The garrison resolved, to a ____, to fight on rather than surrender.", answers: ["man"], explanation: "'To a man' means 'every single one of them, without exception'." },
    { text: "Poverty and poor health tend to go hand ____ hand.", answers: ["in"], explanation: "'Go hand in hand' means to occur together, closely connected." },
    { text: "Row ____ row of white crosses stretched away to the horizon.", answers: ["upon", "after", "on"], explanation: "'Row upon/after/on row' conveys a vast repeated series." },
    { text: "And ____ that, she snapped her briefcase shut and swept out of the courtroom.", answers: ["with", "at"], explanation: "'And with/at that' means 'and immediately after saying/doing that'." },
    { text: "____ closer inspection, the signature proved to be a clumsy forgery.", answers: ["on", "upon"], explanation: "'On/upon closer inspection' means 'when examined more carefully'." },
    { text: "____ being well, the satellite will enter its final orbit early on Tuesday.", answers: ["all"], explanation: "'All being well' is an absolute participle clause meaning 'if nothing goes wrong'." },
    { text: "As ____ stand, neither party has the votes to force the issue.", answers: ["things", "matters"], explanation: "'As things/matters stand' means 'in the present situation'." },
    { text: "The rent must reach the landlord's account by the first of the month without ____.", answers: ["fail"], explanation: "'Without fail' means 'absolutely reliably, every time'." },
    { text: "The east wing of the gallery will remain closed until ____ notice.", answers: ["further"], explanation: "'Until further notice' means 'until a new announcement is made'." },
    { text: "The recall applies to all affected models with ____ effect.", answers: ["immediate"], explanation: "'With immediate effect' is the formal phrase meaning 'starting now'." },
    { text: "The court quashed the conviction, and in ____ doing rewrote the rules of evidence.", answers: ["so"], explanation: "'In so doing' means 'by doing that', referring back to the action just described." },
    { text: "It is telling that not one minister ____ have thought to offer an apology.", answers: ["should"], explanation: "Putative 'should' after evaluative expressions: 'It is telling that X should have...'." },
    { text: "He ____ interrupt, however many times I ask him not to.", answers: ["will", "does"], explanation: "Stressed 'will' expresses an annoying habit; emphatic 'does' also asserts the habitual fact." },
    { text: "You ____ at least have warned us that the inspectors were coming today!", answers: ["might", "could"], explanation: "'You might/could at least have + past participle' reproaches someone for not doing something." },
    { text: "If you ____ know, the tip-off came from inside the department itself.", answers: ["must"], explanation: "'If you must know' grudgingly concedes information to a persistent questioner." },
    { text: "Guests are under no obligation to tip, but are naturally welcome ____ if they wish.", answers: ["to"], explanation: "Ellipsis with stranded 'to': 'welcome to (tip) if they wish'." },
    { text: "The design is undeniably elegant. It is hardly practical, ____.", answers: ["though", "however"], explanation: "Sentence-final 'though/however' adds a contrasting afterthought." },
    { text: "____ by design or through sheer neglect, the archive was allowed to rot.", answers: ["whether"], explanation: "'Whether X or Y' presents two alternative explanations without deciding between them." },
    { text: "The evidence is largely circumstantial; the jury ____ found it persuasive.", answers: ["nevertheless", "nonetheless", "still"], explanation: "'Nevertheless/nonetheless/still' concedes the previous point while asserting a contrast." },
    { text: "The premises are cramped; ____, the lease expressly forbids any alterations.", answers: ["moreover", "furthermore", "besides", "additionally", "further", "worse"], explanation: "An additive connector ('moreover', 'furthermore', etc.) introduces a second, reinforcing objection." },
    { text: "The dig uncovered a ____ unsuspected Roman settlement beneath the orchard.", answers: ["hitherto", "previously"], explanation: "'Hitherto/previously unsuspected' means 'not suspected until now'." },
    { text: "Tenants are responsible for the upkeep of the garden or any part ____.", answers: ["thereof"], explanation: "Legal 'thereof' means 'of it/that', referring back to the garden." },
    { text: "The new curriculum lets engineers take arts electives, and vice ____.", answers: ["versa"], explanation: "'Vice versa' means 'the other way round' — arts students may take engineering electives." },
    { text: "Genuine misprints of this stamp are rare; few, ____ any, ever reach public auction.", answers: ["if"], explanation: "'Few, if any' means 'very few, and possibly none at all'." },
    { text: "He carried on with the lecture as ____ nothing whatsoever had happened.", answers: ["if", "though"], explanation: "'As if/though + past perfect' describes behaviour at odds with what had really occurred." },
    { text: "Any editor ____ her salt would have spotted the libel risk at once.", answers: ["worth"], explanation: "'Anyone worth their salt' means 'anyone competent at their job'." },
    { text: "The cottage has no central heating, not to ____ the leaking roof.", answers: ["mention"], explanation: "'Not to mention X' adds a further, even more obvious problem." },
    { text: "Restoring public trust will take a generation; such things are easier said than ____.", answers: ["done"], explanation: "'Easier said than done' is the fixed idiom for something simple to propose but hard to achieve." },
    { text: "Tiny errors can have vast consequences: the lost 1999 Mars orbiter is a ____ in point.", answers: ["case"], explanation: "'A case in point' is a specific example illustrating the general claim." },
    { text: "Criticising a colleague in public went right against the ____ for her.", answers: ["grain"], explanation: "'Go against the grain' means to conflict with one's natural inclinations." },
    { text: "The book's inconclusive final chapter nonetheless offers plenty of food for ____.", answers: ["thought"], explanation: "'Food for thought' means material worth reflecting on." },
    { text: "Surrounded by strangers in evening dress, he felt distinctly ill at ____.", answers: ["ease"], explanation: "'Ill at ease' means uncomfortable and anxious." },
    { text: "By and ____, the reforms have achieved what they set out to do.", answers: ["large"], explanation: "'By and large' means 'on the whole, generally'." },
    { text: "Her agent stood by her through thick and ____ for over three decades.", answers: ["thin"], explanation: "'Through thick and thin' means through good times and bad alike." },
    { text: "Delays, it would seem, are part and ____ of modern air travel.", answers: ["parcel"], explanation: "'Part and parcel of X' means an inseparable feature of X." },
    { text: "The tribunal declared the disputed election null and ____.", answers: ["void"], explanation: "'Null and void' is the fixed legal doublet meaning 'without legal force'." },
    { text: "The deposit covers damage over and beyond normal wear and ____.", answers: ["tear"], explanation: "'Wear and tear' is the fixed phrase for gradual damage from ordinary use." },
    { text: "The auditors examined each and ____ invoice issued since 2019.", answers: ["every"], explanation: "'Each and every' is an emphatic doublet meaning 'absolutely all', taking a singular noun." },
    { text: "She regards herself first and ____ as a teacher, and only then as a politician.", answers: ["foremost"], explanation: "'First and foremost' means 'primarily, above everything else'." },
    { text: "The pharmacist followed the storage instructions to the ____.", answers: ["letter"], explanation: "'To the letter' means with exact, literal precision." },
    { text: "The negotiators went through the leaked transcript word for ____.", answers: ["word"], explanation: "'Word for word' means examining or reproducing every single word exactly." },
    { text: "On a caretaker's wages, the couple struggled to make ends ____.", answers: ["meet"], explanation: "'Make ends meet' means to earn just enough to cover one's expenses." },
    { text: "After thirty years behind the wheel, double-declutching is second ____ to him.", answers: ["nature"], explanation: "'Second nature to someone' describes a skill so practised it feels instinctive." },
    { text: "Regulators turned a blind ____ to the bank's creative accounting for years.", answers: ["eye"], explanation: "'Turn a blind eye to' means to deliberately ignore wrongdoing." },
    { text: "Her repeated warnings about the dam fell on deaf ____.", answers: ["ears"], explanation: "'Fall on deaf ears' means to be ignored by those addressed." },
    { text: "He has finally come to ____ with the fact that his playing days are over.", answers: ["terms", "grips"], explanation: "'Come to terms/grips with' means to accept or begin to deal with a difficult reality." },
    { text: "No photograph can do ____ to the sheer scale of the canyon.", answers: ["justice"], explanation: "'Do justice to something' means to represent it as well as it deserves." },
    { text: "To his ____, he owned up to the blunder before anyone else noticed it.", answers: ["credit"], explanation: "'To someone's credit' acknowledges a praiseworthy action." },
    { text: "Long overshadowed by her father, she is now celebrated as a sculptor in her own ____.", answers: ["right"], explanation: "'In one's own right' means through one's own merits, not by association." },
    { text: "Litigation should be a last ____, not an opening move.", answers: ["resort"], explanation: "'A last resort' is the option turned to only when everything else has failed." },
    { text: "The regular drummer fell ill, so a session player was drafted in at short ____.", answers: ["notice"], explanation: "'At short notice' means with very little warning or preparation time." },
    { text: "A burst water main brought the entire west of the city to a ____.", answers: ["standstill", "halt"], explanation: "'Bring something to a standstill/halt' means to stop it completely." },
    { text: "Decades of relentless touring have taken their ____ on the singer's voice.", answers: ["toll"], explanation: "'Take its/their toll on' means to cause cumulative damage to." },
    { text: "The low-lying coastal villages bore the ____ of the storm.", answers: ["brunt"], explanation: "'Bear the brunt of' means to suffer the worst part of something." },
    { text: "All timetables printed herein are ____ to alteration without notice.", answers: ["subject", "liable", "open"], explanation: "'Subject/liable/open to alteration' means the timetables may be changed." },
    { text: "With tempers fraying on both sides, a confrontation was ____ to happen sooner or later.", answers: ["bound", "certain", "sure", "destined", "fated"], explanation: "'Bound/certain/sure to happen' means inevitable given the circumstances." },
    { text: "The hotel's service, alas, is not on a ____ with its five-star prices.", answers: ["par", "level"], explanation: "'On a par/level with' means of equal standard to." },
    { text: "The open-air ceremony will go ahead ____ of the weather.", answers: ["regardless", "irrespective"], explanation: "'Regardless/irrespective of X' means X will make no difference." },
    { text: "____ to popular belief, lightning frequently strikes the same place twice.", answers: ["contrary"], explanation: "'Contrary to popular belief' introduces a fact that most people get wrong." },
    { text: "All hold luggage is screened ____ to being loaded onto the aircraft.", answers: ["prior"], explanation: "'Prior to' is a formal preposition meaning 'before'." },
    { text: "The summary is accurate as far as it ____, but it omits the crucial final year.", answers: ["goes"], explanation: "'As far as it goes' concedes limited adequacy while implying incompleteness." },
    { text: "When it ____ to squeezing money out of donors, she has no equal.", answers: ["comes"], explanation: "'When it comes to + gerund' introduces the specific field being discussed." },
    { text: "Strictly ____, the tomato is a fruit rather than a vegetable.", answers: ["speaking"], explanation: "'Strictly speaking' signals that a technically precise definition follows." },
    { text: "____ bluntly, the club is broke and the players know it.", answers: ["put", "stated"], explanation: "'Put bluntly' is a fronted participle formula meaning 'to express it directly'." },
    { text: "We took it for ____ that the mountain roads would be passable in June.", answers: ["granted"], explanation: "'Take it for granted that...' means to assume something without checking." },
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part2 = QUESTIONS.part2.concat(BANK);
})();
