/* CPE Reading — Gapped text, wave 2 */
(function () {
  var BANK = [
    {
      id: "p-rgap2-01",
      title: "Ice as Archive: Artefacts from the Melting Mountains",
      segments: [
        "For millennia, the high glaciers of Europe, Asia, and the Americas have acted as unlikely custodians of human history. Extreme cold arrests decomposition so thoroughly that organic materials preserved in ice can emerge, centuries later, in near-perfect condition. Scientists and archaeologists have long known that glaciers advance and retreat, but the pace at which they are currently receding has transformed them, in the words of one glaciologist, into \"libraries that are burning faster than we can read them.\"",
        "The implications of this accelerating melt extend well beyond the purely scientific. Mountain communities that have depended on glacial meltwater for irrigation and drinking water are confronting an existential threat to their livelihoods. But for archaeologists, each retreating ice margin also represents a racing clock: once an artefact is exposed to summer temperatures, biological decay resumes with startling speed.",
        "The range of materials that survive glacial entombment is astonishing. Leather, wool, hair, wood, and even foodstuffs have been recovered in states of preservation that conventional burial in soil almost never achieves. The chemistry of ice entombment is straightforward: in sub-zero anaerobic conditions, the bacteria and fungi that ordinarily drive decomposition cannot function.",
        "Not all glacial finds are prehistoric. The Alps have yielded artefacts from every major conflict fought in or near the mountains, including the First and Second World Wars. Soldiers who went missing in high-altitude engagements have been recovered with their equipment, uniforms, and personal effects intact, presenting military historians with primary evidence of a kind rarely available from conventional battlefields.",
        "The logistical challenges of glacial archaeology are considerable. High-altitude sites are difficult to access, weather windows are narrow, and the melt itself may rebury or destroy an object within a single season. Teams working in the Schnalstal glacier in the Italian Alps, for example, routinely employ satellite-guided survey drones to detect anomalies in the ice surface before committing field personnel to dangerous terrain.",
        "Conservation once the objects are removed presents an equally demanding set of problems. The transition from sub-zero, oxygen-free conditions to a temperate laboratory environment must be managed with extraordinary care. Rapid temperature change causes ice crystals within the artefact's cellular structure to expand and rupture, while sudden exposure to atmospheric oxygen triggers oxidative reactions that can disfigure or destroy surfaces within hours.",
        "Funding for this branch of archaeology is chronically precarious. Unlike dramatic excavations in desert sands or tropical jungles, glacial fieldwork rarely yields the photogenic golden treasures that attract public attention and private sponsorship. The work is painstaking, the finds are often fragmentary, and the scientific rewards, though genuine, are seldom immediate.",
        "What emerges from all this effort is a portrait of human life in mountain environments that no written record could supply. Clothing styles, dietary choices, trade routes, and metallurgical techniques that might otherwise be inferred only from ambiguous textual sources become tangible, dateable, and measurable. The glaciers, even as they vanish, are insisting on being heard."
      ],
      options: [
        "Otzi the Iceman, recovered from the Otztal Alps in 1991, remains the most celebrated example. His body, equipment, and even the contents of his last meal survived roughly 5,300 years of glacial custody and continue to generate peer-reviewed research across disciplines ranging from forensic medicine to Bronze Age economic history.",
        "Dendrochronology and radiocarbon dating have allowed researchers to assign precise dates to many glacial finds, but these techniques are not infallible. Contamination from modern carbon in the immediate environment, or from organic material introduced during earlier, undocumented disturbances of the ice, can skew results significantly, demanding cross-validation against multiple independent chronometers.",
        "Specialist conservators therefore work in refrigerated chambers, stabilising objects at temperatures close to those of their glacial resting place before any cleaning or analysis is attempted. Freeze-drying, a process that removes moisture through sublimation rather than evaporation, has become the standard method for stabilising organic materials without the dimensional distortion that air-drying invariably causes.",
        "One partial solution has been the establishment of purpose-built cold-storage repositories where rescued artefacts can be held in stable conditions while funding for full conservation is sought. Several Swiss and Austrian museums now operate such facilities, working in partnership with regional governments that recognise the cultural as well as the scientific value of the objects.",
        "Drone survey programmes have also identified zones of subglacial bedrock where objects may have been trapped and concentrated over thousands of years, a phenomenon archaeologists call an \"ice trap.\" These locations, when the overlying ice finally melts, may yield clusters of artefacts from multiple time periods, making systematic excavation both more productive and more complex.",
        "Some finds have rewritten established chronologies in unexpected ways. A wooden bow stave recovered from a Norwegian glacier proved to be approximately 5,400 years old, predating by several centuries the previously accepted timeline for bow technology in northern Europe and prompting a thorough reappraisal of prehistoric hunting practices across the sub-arctic zone.",
        "The ethical dimensions of these discoveries are not straightforward either. Some recovered individuals are claimed by indigenous communities as ancestral remains deserving repatriation and respectful interment, rather than scientific study. Negotiations between archaeologists, museum curators, and community representatives have in several cases lasted decades without reaching a mutually satisfactory resolution.",
        "International coordination has, in some measure, addressed this problem. The European Union has funded transnational consortia that pool expertise and equipment across borders, and several universities in the Americas have established formal partnerships with Andean governments to ensure that finds from high-altitude sites in Peru, Bolivia, and Chile are studied and conserved within their countries of origin."
      ],
      answers: [0, 5, 2, 7, 4, 3, 1],
      explanations: [
        "段落以「Otzi」開頭，是「有機物質可近乎完美保存」的最著名具體範例，承接第一段關於冰川保存能力的概述。",
        "「Some finds have rewritten established chronologies」呼應前段「各種材料的保存令人驚嘆」，並以挪威弓具體說明改寫年代表的案例，邏輯承接。",
        "「Specialist conservators therefore work in refrigerated chambers」中的「therefore」直接呼應前段說明的熱脹與氧化雙重威脅，提出具體的保存處理方法。",
        "「International coordination has, in some measure, addressed this problem」的「this problem」回指前段倫理糾紛和談判困境，提供跨國合作作為部分解方。",
        "「Drone survey programmes have also identified zones」中的「also」連接前段已提及的無人機技術，進一步拓展其功能（識別「冰阱」），邏輯遞進。",
        "「One partial solution」接續保存費用昂貴、資金匱乏的困境，提出冷藏庫存設施作為折衷辦法，語意緊密相連。",
        "「Dendrochronology and radiocarbon dating」呼應前段提到各種測定技術，進一步討論其局限性與交叉驗證的必要，學術議題深化。"
      ]
    }
    ,
    {
      id: "p-rgap2-02",
      title: "The Secondhand Bookshop as Economic Paradox",
      segments: [
        "Walk into almost any secondhand bookshop and you will notice the same apparent contradiction: the shelves are impossibly full, the prices are low, and yet the proprietor seems, if not exactly prosperous, at least stubbornly solvent. The economics of the trade have puzzled retail analysts for decades. In a sector where margins on new books are notoriously thin and large chains have repeatedly collapsed, the small, chaotic, independently owned used bookshop continues to survive.",
        "Part of the explanation lies in the structure of the supply chain. A new-book retailer must buy stock at a wholesale price set by the publisher, bear the cost of unsold returns, and compete on price with online platforms that have perfected the logistics of deep discounting. The secondhand dealer, by contrast, acquires stock at close to zero marginal cost, prices according to perceived demand, and carries no obligation to return unsold items.",
        "The idiosyncratic organisation of most secondhand shops is not, as it might appear, a symptom of neglect. Many proprietors have spent years developing elaborate personal filing systems that allow them to locate any volume within minutes. The apparent disorder is, in many cases, a deliberate deterrent to browsing customers who might disturb a carefully maintained arrangement.",
        "The internet age posed what seemed an existential threat. When platforms such as AbeBooks and Alibris made it possible to search millions of secondhand titles globally and have them delivered within days, commentators predicted the death of the physical shop. The browsable, serendipitous experience of the bricks-and-mortar store was supposed to be no match for the algorithmic efficiency of online aggregators.",
        "What the internet actually did, however, was bifurcate the market. It absorbed the functional demand for specific out-of-print titles and drove down prices for common volumes to near-zero. But it simultaneously created a new category of bibliophile customer: one who uses online platforms to research and compare, then visits physical shops specifically for the pleasure of discovery that no algorithm can replicate.",
        "The community role of the secondhand bookshop is equally underappreciated by those who analyse the sector purely through a commercial lens. In many small towns and urban neighbourhoods, the local used bookshop functions as an informal cultural centre, hosting readings, providing a quiet working space, and maintaining a relationship with its customers that most retail formats explicitly design out.",
        "Some proprietors have formalised this community function, converting part of their floor space into licensed cafes, event venues, or subscription reading rooms. The most successful of these hybrid formats generate income streams that are entirely independent of book sales, effectively cross-subsidising the retail operation and insulating it from the volatility of secondhand pricing.",
        "The secondhand bookshop is, in the end, less a retail business than a form of cultural infrastructure maintained by the stubbornness of its proprietors and the loyalty of its customers. Its persistence in the face of apparently superior competition suggests that the market for books is not, and perhaps never has been, fully captured by the logic of efficiency."
      ],
      options: [
        "Rent is often the decisive variable. Many long-established secondhand shops occupy premises that were taken on at favourable rates decades ago, and landlords in secondary locations have found that a bookshop generates more goodwill and foot traffic than a vacant unit. The combination of below-market rents and near-zero stock costs produces a cost structure that a new-book retailer could not approach.",
        "The prediction proved spectacularly wrong. Between 2010 and 2020, the number of independent secondhand bookshops in Britain actually increased, a trend mirrored in the United States, France, and the Netherlands. Physical bookshops, it turned out, were not competing with the internet so much as occupying a different emotional register of the reading experience.",
        "Charity shops and house-clearance sales are the primary sources of stock for most dealers, supplemented by customers who bring in boxes of unwanted volumes. The result is an inventory that is perpetually renewed at minimal cost, and the dealer's skill lies not in buying well but in pricing well: recognising which volumes will sell quickly at a premium and which will linger until marked down.",
        "This bifurcation has had tangible consequences for the internal economics of the trade. Volumes that once formed the reliable turnover of a secondhand shop, standard editions of canonical texts, popular fiction from the preceding decade, have been commoditised to the point of worthlessness. Shops that once stocked broadly now curate aggressively, focusing on areas of genuine rarity or local relevance.",
        "Staff knowledge is the other irreplaceable asset. A bookseller who can recommend an obscure 1960s novel to a customer who mentioned enjoying a particular contemporary author is performing a service no recommendation engine has yet mastered. This curatorial intelligence, accumulated over careers spent reading and selling, is the trade's most durable competitive advantage.",
        "The towns of Hay-on-Wye in Wales and Bouquinistes along the Seine in Paris have both demonstrated that a concentration of secondhand bookshops can become a tourist destination in its own right, drawing visitors whose primary purpose is browsing rather than any specific purchase. The phenomenon has been replicated in Wigtown in Scotland, Clunes in Australia, and several towns in Belgium and the Netherlands.",
        "Not all secondhand bookshop owners welcome this evolution. Some regard the cafe-and-events model as a betrayal of the trade's essential nature, an admission that books alone can no longer sustain a viable business. Their resistance points to a genuine tension between the cultural and commercial functions that the secondhand bookshop has always, to varying degrees, been expected to fulfil.",
        "Online-only secondhand dealers, by contrast, have found the economics considerably harsher. Without the physical browsing experience that generates impulse purchases and repeat visits, they compete almost entirely on price and speed of delivery, a race to the bottom that has eliminated margins and driven consolidation among all but the largest operators."
      ],
      answers: [2, 0, 4, 1, 3, 5, 6],
      explanations: [
        "「Charity shops and house-clearance sales」具體說明了供應鏈如何讓二手書商以接近零成本取得庫存，承接前段對供應鏈結構差異的分析。",
        "「Rent is often the decisive variable」補充說明成本結構的第三項關鍵要素（租金），與前段庫存成本並列，完整勾勒出成本優勢的全貌。",
        "「Staff knowledge is the other irreplaceable asset」中的「the other」呼應前段提到的個人化檔案系統，形成一組無形資產的並列陳述。",
        "「The prediction proved spectacularly wrong」直接反駁前段「沒有實體店能抗衡演算法效率」的預測，段落開頭的「The prediction」回指清晰。",
        "「This bifurcation has had tangible consequences」的「this bifurcation」回指前段剛描述的市場分化（functional vs. serendipitous），承接邏輯嚴密。",
        "「The towns of Hay-on-Wye」以具體地名例子佐證前段所說書店社群角色被低估，從非正式文化中心延伸到旅遊目的地。",
        "「Not all secondhand bookshop owners welcome this evolution」中的「this evolution」回指前段混合業態（咖啡廳＋活動空間）的演變，引出業界內部張力。"
      ]
    }
    ,
    {
      id: "p-rgap2-03",
      title: "Flashing in Concert: The Science of Synchronised Fireflies",
      segments: [
        "On warm summer evenings in the forests of the Great Smoky Mountains, a phenomenon occurs that draws thousands of visitors each year: thousands of fireflies begin to flash simultaneously, their cold bioluminescent light pulsing in waves across the dark understorey. The spectacle is neither random nor orchestrated by any single individual. It is, instead, an emergent property of local interactions repeated across an entire population.",
        "The species responsible, Photinus carolinus, is one of only a handful of firefly species in the world known to synchronise. The male emits a distinctive pattern of six rapid flashes followed by a pause of roughly eight seconds. Females perched in the vegetation respond with a delayed double flash. Mating success depends on the male's signal being both distinctive and detectable against background noise.",
        "The mechanism by which synchrony emerges has been studied using mathematical models borrowed from the physics of coupled oscillators. Each firefly behaves as an autonomous clock that can be nudged forward or backward by the flashes it perceives from neighbours. When the density of individuals is high enough, these local adjustments propagate through the group until the entire population locks into a common rhythm.",
        "Confirmation of this model required more than casual observation of forest displays. Researchers had to track individual insects across time, a formidable challenge given that the insects move continuously through three-dimensional space in near-total darkness. The development of stereo infrared camera arrays, capable of reconstructing individual flight trajectories without disturbing the insects, proved transformative.",
        "The synchrony of Photinus carolinus has attracted interest well beyond entomology. Mathematicians and engineers have drawn on the coupled-oscillator model to design distributed communication protocols for wireless sensor networks, where individual nodes must coordinate timing without a central clock. The firefly's solution to the synchronisation problem is, it turns out, computationally elegant.",
        "Ecological context shapes the synchrony in ways that the pure mathematical model cannot predict. Population density, canopy structure, and even ambient temperature alter the speed at which phase-locking occurs. In denser populations the convergence is faster but also more fragile: a single large disturbance, such as a vehicle's headlights sweeping through the forest, can reset the entire population to an asynchronous state.",
        "Conservation of synchronised firefly habitats has become an increasingly urgent priority. Light pollution from nearby settlements disrupts the mating signal at its most fundamental level: artificial light reduces the contrast against which the flash pattern is perceived, effectively masking the signal and suppressing mate-finding success. Several national parks in the United States and Taiwan have introduced seasonal lighting ordinances in buffer zones around known synchronisation sites.",
        "The firefly's achievement is, in the end, a reminder that coordination among large numbers of autonomous agents does not require hierarchy or central control. The same mathematical principles that govern forest clearings in Tennessee have been detected in cardiac pacemaker cells, neural oscillation in the sleeping brain, and the clapping rhythms of concert audiences. Synchrony, it appears, is one of nature's most versatile solutions."
      ],
      options: [
        "The problem is complicated by the fact that different firefly species have evolved mutually incompatible flash codes as a reproductive isolation mechanism. A female of one species will not respond to the signal of another, even when their flash rates are superficially similar. This specificity makes cross-species interference rare, but it also means that a slight alteration in flash timing can eliminate a male's reproductive success entirely.",
        "Early theoretical work on the problem was carried out by the mathematician Art Winfree in the 1960s and refined by Steven Strogatz and Rennie Mirollo in a landmark 1990 paper. Their model demonstrated that a population of oscillators with slightly different natural frequencies would, above a critical coupling threshold, spontaneously lock into synchrony, a result that translated directly to the biological case.",
        "The stereo camera data revealed that synchrony does not sweep through the population from a single starting point, as one might expect of a wave emanating from a dominant individual. Instead, multiple local clusters achieve phase-lock independently and then gradually merge, a process the researchers termed \"cluster coalescence,\" which takes approximately twenty minutes on a typical observation night.",
        "A parallel line of research has examined the neurological basis of flash production. Each flash is generated by the controlled release of a chemical substrate, luciferin, in the presence of the enzyme luciferase and molecular oxygen, a reaction that produces light with near-perfect quantum efficiency. The neural trigger for this reaction originates in a dedicated ganglion in the firefly's abdomen.",
        "Tourism management has added another layer of complexity to conservation efforts. The annual synchronised firefly event in the Smoky Mountains now requires a lottery system to limit visitor numbers, and the park service employs red-filtered torchlight and strict quiet protocols during peak displays. Even well-intentioned observers, if numerous enough, can suppress the very phenomenon they have come to witness.",
        "These applications include the design of more robust GPS-free timing systems for autonomous vehicle swarms, where vehicles must coordinate manoeuvres without continuous radio contact. The elegance of the biological solution lies in its robustness to individual failure: if a single firefly goes dark, the remaining population continues to synchronise, a property that engineers find difficult to achieve with top-down clock distribution.",
        "Researchers working in the Smokies have noted that synchrony in Photinus carolinus takes noticeably longer to emerge on nights when ambient temperatures drop below fifteen degrees Celsius. Lower temperatures slow the rate of neurochemical signalling, effectively stretching each firefly's internal period and increasing the time required for the population to reach consensus on a shared beat.",
        "The biochemistry of bioluminescence has attracted commercial interest for reasons entirely unrelated to synchrony. The luciferase gene, isolated and cloned in the 1980s, has become one of the most widely used reporter genes in molecular biology, allowing researchers to track gene expression in living tissue by measuring light output. This application has generated far more research funding than the ecological study of firefly behaviour."
      ],
      answers: [1, 0, 2, 3, 5, 6, 4],
      explanations: [
        "「Early theoretical work... Art Winfree... Strogatz and Mirollo」提供耦合振盪模型的學術淵源，直接承接前段引入「coupled oscillators」數學模型的說明。",
        "「The problem is complicated by the fact that different firefly species have evolved mutually incompatible flash codes」延伸前段對 P. carolinus 特定閃光模式的描述，說明物種特異性與訊號錯誤的代價。",
        "「The stereo camera data revealed that synchrony does not sweep through the population from a single starting point」中的「The stereo camera data」回指前段「stereo infrared camera arrays」的研究工具，報告具體發現。",
        "「A parallel line of research has examined the neurological basis」的「parallel」表示與前面追蹤飛行軌跡的研究並行，探討閃光的神經生物學機制，邏輯層次遞進。",
        "「These applications include the design of more robust GPS-free timing systems」中的「these applications」回指前段提到的無線感測網路等工程應用，具體舉例。",
        "「Researchers working in the Smokies have noted that synchrony... takes noticeably longer... when ambient temperatures drop」回應前段說「環境溫度會影響 phase-locking 速度」，提供具體機制說明。",
        "「Tourism management has added another layer of complexity to conservation efforts」的「another layer」建立在前段已討論的光污染問題之上，引入旅遊管理作為第二重保育挑戰。"
      ]
    }
    ,
    {
      id: "p-rgap2-04",
      title: "Rescuing the Image: The Restoration of Early Silent Cinema",
      segments: [
        "The history of cinema is, in part, a history of catastrophic loss. It is estimated that roughly seventy-five percent of all silent films produced before 1930 no longer exist in any form. Nitrate film stock, the medium on which virtually all early cinema was recorded, is chemically unstable, highly flammable, and subject to a form of decomposition that accelerates as humidity and temperature fluctuate. Entire studio archives burned, and many more collections were deliberately destroyed once the transition to sound rendered the films commercially worthless.",
        "What survives is often a matter of accident. A reel found under a collapsed building in Dawson City, Yukon, in 1978 contained 372 films that had lain undisturbed in permafrost since the 1930s, preserved by the very conditions that had made the site unsuitable for habitation. Other discoveries have been made in hospital projection rooms, government film libraries, and the personal collections of enthusiasts who salvaged prints from studio dumpsters.",
        "The physical restoration of a damaged nitrate print is a labour-intensive and genuinely hazardous undertaking. Nitrate is classified as a class-one flammable solid; a single reel can spontaneously ignite if stored at elevated temperatures, and the fire it generates produces gases toxic enough to kill anyone in an enclosed space. Work with original nitrate therefore takes place in specialised facilities built to contain and suppress fires, staffed by technicians trained in both archival science and emergency response.",
        "Once a print is stabilised and safe to handle, the next challenge is photochemical or digital restoration of the image itself. Decades of poor storage produce a recognisable set of defects: silvering, in which the silver halide in the emulsion forms a metallic sheen that obscures detail; vinegar syndrome, the acetic acid off-gassing that accompanies decomposition; shrinkage, which causes the sprocket holes to misalign and the frame to judder during projection.",
        "Digital restoration has transformed the possibilities of the field since the late 1990s. Frame-by-frame scanning at resolutions of up to eight thousand pixels per line captures image information invisible to the naked eye, and machine-learning algorithms trained on thousands of hours of damaged footage can now identify and remove scratches, dust, and flicker with a precision that manual retouching could never approach.",
        "The question of how to present restored silent films to contemporary audiences raises issues that are as much philosophical as technical. Silent films were not simply films without sound: they were conceived for live musical accompaniment, for the noise of a crowded theatre, and for a viewing culture in which audiences talked, ate, and moved freely. Presenting them in the reverential silence of a modern art-house cinema can produce a misleading impression of their original character.",
        "Tinting and toning, two techniques by which early filmmakers added colour to black-and-white prints, present a particular restoration challenge. Original tinting formulas varied by studio and era, and many have been lost. The wrong tint can fundamentally alter the emotional register of a scene: the warm amber used to signify firelight reads very differently from the blue-green conventionally applied to nocturnal exteriors.",
        "The goal of silent film restoration is ultimately an interpretive act as much as a technical one. Every decision made during the restoration process, from the choice of musical score to the speed at which frames are projected, encodes assumptions about what the film originally was and what it should mean to a new audience. The restored film is not the original; it is an argument about the original, made with the best evidence available."
      ],
      options: [
        "Projection speed alone illustrates the interpretive complexity. Silent cameras were cranked by hand at rates ranging from twelve to twenty-six frames per second, and projectionists varied speed according to the emotional mood of each scene. Standardised twenty-four-frames-per-second digital playback, applied without adjustment, can make action sequences look frenetic and intimate scenes appear unnaturally slow, distorting the rhythm that the director originally intended.",
        "The Dawson City find is the most celebrated of these accidents, but it is far from the only one. A cache of films discovered in a New Zealand film board vault in 1987 included the only surviving print of the complete version of the 1914 feature \"From the Manger to the Cross,\" a film long considered entirely lost. Such finds continue to occur at irregular intervals, suggesting that the full extent of silent cinema's survival remains unknown.",
        "Music is perhaps the most contentious element of any restoration. Surviving scores composed for the original release are rare; for most films, the music performed at a given screening was selected or improvised by a local accompanist according to personal taste and the available instrumentation. Modern restorations commission new scores from contemporary composers, creating hybrid artefacts that are simultaneously faithful to the film and entirely foreign to it.",
        "These algorithms are not infallible, and their application requires constant human oversight. A scratch running across a face can be removed accurately only if the algorithm correctly identifies where the underlying facial features should be; errors produce uncanny, mask-like distortions that are more distracting than the original damage. Skilled digital operators spend hours reviewing algorithmic output frame by frame, correcting errors that the software generates with confident incorrectness.",
        "The chemical instability of nitrate was recognised almost from the beginning of cinema, and several studios began transferring archives to safety film as early as the 1940s. However, the transfers were often made at reduced resolution, with image cropping and speed alterations that compounded the losses already caused by physical deterioration. In some cases, the safety copy is demonstrably inferior to a surviving nitrate fragment.",
        "Colour reconstruction has benefited from an unlikely source: the trade catalogues of film stock manufacturers, which sometimes include colour reference charts and descriptions of tinting formulae used in specific periods. Cross-referencing these with surviving tinted prints from the same studios has allowed conservators to reconstruct palettes with a degree of confidence previously impossible.",
        "Some institutions have taken a deliberately interventionist approach to this challenge, presenting restored silents with live orchestral accompaniment, intertitle translation, and even restored spoken introductions delivered by actors in period costume. The purist objection that such presentations distort the original experience is countered by the pragmatic argument that an engaged audience is more valuable than an academically correct but alienating one.",
        "International cooperation has become essential to the field, since many surviving prints are scattered across archives in different countries, and no single institution possesses a complete version of any given film. The Italian national film archive, the Library of Congress, and the Cinematheque Francaise have jointly restored several major titles by combining reels held separately in Rome, Washington, and Paris, assembling a composite version from the best surviving footage across all three holdings."
      ],
      answers: [1, 4, 3, 0, 5, 2, 6],
      explanations: [
        "「The Dawson City find is the most celebrated of these accidents, but it is far from the only one」以「these accidents」回指前段「matter of accident」，並補充紐西蘭案例，擴展「偶然保存」的範疇。",
        "「The chemical instability of nitrate was recognised almost from the beginning」承接前段硝酸鹽轉移到安全膠片的暗示，說明早期轉制的問題與損失。",
        "「These algorithms are not infallible」中的「these algorithms」回指前段剛介紹的機器學習演算法，緊接說明其局限性與人工監督的必要。",
        "「Projection speed alone illustrates the interpretive complexity」中「the interpretive complexity」回指前段提及的哲學性問題（呈現方式的詮釋困難），並以具體技術細節加以例證。",
        "「Colour reconstruction has benefited from an unlikely source」承接前段對色調（tinting/toning）復原挑戰的描述，提供製造商目錄作為意外的解決資源。",
        "「Music is perhaps the most contentious element of any restoration」呼應前段對現代藝術院線靜默呈現方式的批判，進一步聚焦音樂選擇這一最具爭議的詮釋決定。",
        "「Some institutions have taken a deliberately interventionist approach to this challenge」的「this challenge」回指前段音樂詮釋爭議，描述機構如何以介入主義方式回應，並引出爭辯。"
      ]
    }
    ,
    {
      id: "p-rgap2-05",
      title: "The Weight of Empty Time: Boredom and Its Philosophers",
      segments: [
        "Boredom is so thoroughly familiar that it barely seems worth thinking about, yet philosophers from Pascal to Heidegger have returned to it with something approaching alarm. The experience of finding time empty and heavy, of being unable to engage with what surrounds you, is so common as to seem trivial. It is anything but. Boredom, examined carefully, reveals something fundamental about the human relationship to time, meaning, and the conditions under which action becomes possible.",
        "Pascal was perhaps the first to articulate boredom as a philosophical problem rather than a moral failing. In his Pensees, he argued that the restlessness which drives human beings from one diversion to the next is not mere weakness of character but a symptom of something deeper: the inability to sit quietly in a room. For Pascal, the capacity to tolerate stillness was inseparable from the capacity to confront one's own contingency, and most people found that confrontation intolerable.",
        "Schopenhauer carried the analysis further, locating boredom at one pole of a miserable oscillation that defines human experience. At one extreme, unfulfilled desire produces suffering; at the other, its satisfaction produces boredom. Life swings between the two without ever reaching a stable resting place. The only escape he could identify was aesthetic contemplation, a form of attention so absorbed that the self temporarily dissolves into the object of its focus.",
        "Kierkegaard, writing in the same century, was more attentive to boredom's social dimensions. He observed that the aesthete, the figure who pursues novelty and sensation as a way of fending off boredom, inevitably reaches a point at which no new experience can any longer generate the required intensity. The aesthete's strategy is self-defeating: the very pursuit of stimulation habituates one to stimulation, raising the threshold of what can engage.",
        "Heidegger's treatment of boredom in his 1929-30 lecture course represents the most sustained philosophical engagement with the phenomenon. He distinguished between three forms: the superficial boredom of waiting for a train, the deeper boredom of being at a social gathering that simply fails to engage, and what he called profound boredom (tiefe Langeweile), in which one is not bored by any particular thing but by existence itself.",
        "The last of these forms was, for Heidegger, philosophically significant in a way that the others were not. In profound boredom, the ordinary scaffolding of purposes and projects that organises everyday experience falls away, leaving the individual confronted with existence as such, stripped of the meanings that habit and routine supply. This confrontation, though uncomfortable, was also a kind of disclosure: boredom could become the opening through which authentic existence becomes possible.",
        "Contemporary neuroscience has approached boredom from a very different angle, treating it as a signal state that motivates the search for stimulation. Brain-imaging studies suggest that boredom activates the default mode network, the set of regions associated with mind-wandering, self-referential thought, and the imagining of alternative scenarios. Far from being a blank or empty state, boredom appears to be one of heightened internal activity.",
        "The philosophical and the neuroscientific perspectives are not as incompatible as they might appear. Both agree that boredom is productive in some sense: that it is a condition which, if not immediately escaped, can orient the individual toward something more fundamental than the next distraction. Whether that something is, as Heidegger would have it, the question of being, or simply, as the neuroscientists suggest, a richer repertoire of self-generated thought, it is something that our culture of perpetual connectivity may be systematically preventing us from reaching."
      ],
      options: [
        "This neurological perspective aligns interestingly with research on creativity. Studies in which participants were asked to perform a boring task before attempting a creative exercise consistently outperformed control groups who moved directly to the creative task. The hypothesis is that enforced idleness activates the kind of diffuse, associative thinking that novel problem-solving requires, and that constant stimulation suppresses this mode by keeping the brain in a focused, task-oriented state.",
        "The distinction matters because it implies that the cure for boredom is not, in Heidegger's view, simply more stimulation. The shallow forms of boredom can indeed be relieved by an engaging conversation or an interesting task. Profound boredom, however, is not a deficit of stimulation but a disclosure of the groundlessness of existence, and it demands a different kind of response: not distraction but a resolute turning toward the situation one finds oneself in.",
        "Kierkegaard's solution to this impasse was the ethical life, a mode of existence organised around commitment and responsibility rather than sensation. The individual who takes on genuine obligations, who says \"I am this, I am a husband, a judge, a citizen,\" becomes resistant to boredom not by seeking novelty but by inhabiting their commitments so fully that time acquires weight and direction. The problem of empty time dissolves when time is filled with purpose.",
        "This account has been disputed by philosophers who argue that Schopenhauer's pessimism rests on a contestable premise: that desire is essentially unsatisfiable. Aristotle's concept of eudaimonia, or flourishing, suggests instead that certain forms of activity, specifically those that exercise human capacities at their highest level, are self-sustaining rather than self-extinguishing. The satisfied desire does not necessarily produce boredom if the activity that fulfilled it was constitutively valuable.",
        "The etymology of boredom is itself instructive. The English word did not appear until the nineteenth century, suggesting that the experience it names, or at least the cultural prominence of that experience, is a product of modernity. Earlier European languages relied on the Latin acedia, a theological concept denoting a spiritual torpor associated with the failure to find meaning in devotional practice, and the French ennui, which carries connotations of world-weariness and existential dissatisfaction that English \"boredom\" does not fully capture.",
        "Pascal's diagnosis was given a secular reformulation by Bertrand Russell, who argued in \"The Conquest of Happiness\" that boredom was the chief occupational hazard of modern civilisation. Russell observed that the capacity to endure boredom is itself a precondition of achievement: the greatest creative work requires sustained engagement with problems that are, for long stretches, dull. The person who cannot tolerate monotony will never write a serious book, compose a symphony, or conduct a rigorous scientific experiment.",
        "The social history of boredom tracks closely with the history of leisure. Before industrialisation, most human beings had little unstructured time; the daily rhythms of agricultural labour left small space for the experience of emptiness that boredom requires. The expansion of the working and middle classes into leisure time in the nineteenth and twentieth centuries created, for the first time, large populations with hours to fill and no traditional framework for filling them.",
        "Critics of Heidegger's account have questioned whether profound boredom, as he describes it, is genuinely common or whether it is the prerogative of a particular kind of introspective, philosophically trained individual. The experience of most people during episodes of boredom, they argue, is not an encounter with the groundlessness of being but simply an unpleasant awareness that the current environment offers insufficient stimulation, a condition reliably remedied by a change of scene or company."
      ],
      answers: [4, 5, 3, 2, 1, 0, 7],
      explanations: [
        "「The etymology of boredom is itself instructive」以詞源學切入，說明「boredom」是現代詞彙，呼應前段 Pascal 作為「首位把無聊當哲學問題」的描述，提供歷史語言脈絡。",
        "「Pascal's diagnosis was given a secular reformulation by Bertrand Russell」以「Pascal's diagnosis」直接回指前段帕斯卡論述，羅素的世俗重述延續同一主題並擴展論點。",
        "「This account has been disputed by philosophers who argue that Schopenhauer's pessimism rests on a contestable premise」中「This account」回指前段叔本華的擺盪論，提出亞里斯多德式反駁，形成哲學辯論結構。",
        "「Kierkegaard's solution to this impasse was the ethical life」中的「this impasse」回指前段描述的美學家策略的自我挫敗困境，提出倫理生活作為解方。",
        "「The distinction matters because it implies that the cure for boredom is not... simply more stimulation」的「The distinction」回指前段海德格對三種無聊形式的區分，尤其是「深層無聊」與淺層無聊的不同應對方式。",
        "「This neurological perspective aligns interestingly with research on creativity」的「This neurological perspective」回指前段神經科學研究（預設模式網路），並以創造力實驗進一步支持該觀點。",
        "「Critics of Heidegger's account have questioned whether profound boredom... is genuinely common」直接回應前段海德格對深層無聊作為哲學揭示的主張，提出批評性質疑，邏輯上是辯證的反方。"
      ]
    }
    ,
    {
      id: "p-rgap2-06",
      title: "Fitted Without Fasteners: The Art of Japanese Timber Joinery",
      segments: [
        "In the carpenter's workshop of a traditional Japanese temple, no nail is ever driven, no screw turned, no metal bracket bolted into place. The timbers that will carry the weight of a roof for the next five centuries are shaped so precisely that they interlock under their own geometry, held together by the same compressive forces that the structure they form will bear. This tradition of nail-free joinery, known in Japanese as miyadaiku or temple carpentry, represents one of the most sophisticated applications of geometric reasoning in the history of applied craft.",
        "The intellectual core of the tradition lies in the joint itself. Japanese timber joinery has developed several hundred distinct joint forms, each adapted to a specific structural situation: the meeting of two horizontal beams, the juncture of a post and a lintel, the point where a rafter meets a ridge beam at a compound angle. The vocabulary of joints is, in effect, a vocabulary of structural problems and their solutions.",
        "The most celebrated of these joints is the nuki, a long tenon that passes entirely through a post and locks in place through a slight taper rather than a mechanical fastener. The nuki can be disassembled and reassembled without damage, a property that has proved invaluable in the periodic rebuilding cycles of Japan's wooden temples. The Ise Grand Shrine, for example, is ritually dismantled and rebuilt on an adjacent site every twenty years, a practice that has continued for at least thirteen centuries.",
        "The complexity of these joints places extraordinary demands on the carpenter's spatial reasoning. A compound joint at the corner of a building, where two beams meeting at ninety degrees must both connect to a post that rises vertically, may require cuts that angle simultaneously in three planes. The carpenter who executes such a joint must carry the geometry in his or her head, translating a three-dimensional solution into a sequence of saw cuts and chisel strokes with no margin for error.",
        "Training in the miyadaiku tradition takes, by common estimate, at least fifteen years before a carpenter is trusted to cut independently on a major project. The first years are spent doing nothing but sharpening and maintaining tools, a discipline that inculcates the understanding that precision in cutting depends entirely on the condition of the blade. A chisel ground to the correct bevel angle and stropped to a mirror finish will cut with a predictability that no amount of skill can compensate for if the tool is blunt.",
        "The tradition's relationship to modernity is neither simple resistance nor uncritical accommodation. Contemporary miyadaiku carpenters use laser measuring equipment, computer-aided design software for calculating compound angles in complex roofs, and motorised planers for preliminary dimensioning of timber. The point at which technology is set aside and hand tools taken up is not a matter of tradition for its own sake but of precision: no machine yet built can match the hand plane in the final stages of fitting a joint where tolerances are measured in fractions of a millimetre.",
        "Earthquake resistance is one area where the nail-free approach demonstrates measurable engineering advantages. A rigid, nailed frame transmits seismic energy through its joints, concentrating stress at fixed points until a member fails. A jointed timber frame, by contrast, can absorb and dissipate seismic energy by allowing controlled micro-movement at each joint, a property that Japanese structural engineers have begun to quantify using data gathered from instrumented temple buildings during actual earthquake events.",
        "The survival of miyadaiku into the twenty-first century is not accidental. Several generations of master carpenters made deliberate decisions to document their knowledge in ways that traditional oral transmission could not guarantee. The result is a body of technical literature, supplemented by filmed teaching sessions and computer-modelled joint libraries, that makes the tradition accessible to learners who may never serve a formal apprenticeship, though most practitioners agree that the literature and the film can transmit knowledge, but only practice transmits understanding."
      ],
      options: [
        "Several of these joint forms achieve structural effects that Western carpentry never developed. The kigumi, a box joint used in timber framing, gains strength as the wood it joins expands with seasonal moisture, since expansion drives the interlocking fingers more tightly together rather than splitting them apart. It is a solution that exploits the material properties of wood rather than working against them, converting what Western builders have long regarded as a liability into a structural asset.",
        "This training philosophy reflects a deeper epistemology. In the miyadaiku tradition, knowledge is not primarily propositional but procedural: it resides in the hands and the eye rather than in written instructions or verbal descriptions. A master carpenter teaching a joinery technique will not explain why a certain angle is correct but will guide the apprentice's hands repeatedly through the motion until the geometry becomes, in the practitioner's own phrase, \"something the body knows.\"",
        "The computational demands of this geometry were, for most of the tradition's history, met by a single instrument: the sashigane, a graduated L-shaped steel square whose two arms are calibrated in different scales. A skilled carpenter using the sashigane can calculate the angles required for any roof pitch, any compound joint, and any tapered element without recourse to trigonometric tables. The instrument encodes geometric relationships that took European architects centuries to formalise algebraically.",
        "This measured flexibility is not a structural weakness but a designed response to an environment in which major earthquakes are predictable over the centuries-long lifespan of a temple building. The Horyuji temple complex near Nara, parts of which date to the seventh century, has survived numerous significant seismic events, a record that modern structural engineers have cited as evidence for the earthquake resistance of traditional construction methods.",
        "Documentation began in earnest after the Second World War, when several major temple restoration projects revealed that the number of carpenters capable of executing the most complex joints had fallen dangerously low. The postwar economic transformation of Japan had drawn young men away from artisanal apprenticeships and into manufacturing, and the pool of experienced practitioners contracted sharply within a single generation.",
        "The economic viability of the tradition depends partly on the maintenance requirements of existing temple buildings. Japan has approximately one hundred and fifty thousand listed cultural properties, a significant proportion of which are timber structures requiring periodic repair and reconstruction by qualified miyadaiku carpenters. This ongoing demand sustains a small but stable professional community, though demand spikes around major restoration projects and slumps in the intervals between them.",
        "Contemporary architects working outside the traditional temple context have been drawn to timber joinery as both an aesthetic and a structural resource. Several high-profile buildings completed in the past decade, including the Japan Pavilion at the 2000 Hanover Expo designed by Shigeru Ban, have employed large-scale timber joints as primary structural systems, demonstrating that the principles developed for sacred buildings translate without loss of integrity to secular and large-scale applications.",
        "The wood itself is a critical variable. Hinoki cypress, the preferred species for temple construction, has a straight grain, a low coefficient of moisture expansion, and a natural resistance to fungal attack that makes it exceptional among temperate timber species. It also takes a clean cut from a sharp plane, closing its grain surface as the blade passes rather than tearing it, a property that is indispensable for the tight tolerances that joinery demands."
      ],
      answers: [2, 0, 7, 1, 3, 6, 4],
      explanations: [
        "「The computational demands of this geometry were, for most of the tradition's history, met by a single instrument: the sashigane」呼應前段「將幾何轉化為鋸切和鑿擊序列」的認知要求，介紹傳統計算工具。",
        "「Several of these joint forms achieve structural effects that Western carpentry never developed」中「several of these joint forms」回指前段的「幾百種榫卯形式」，以 kigumi 為例說明獨特結構效果。",
        "「The wood itself is a critical variable」承接前段學徒花費多年保養工具的精密要求，轉向材料本身（檜木）作為影響精密度的另一關鍵變數。",
        "「This training philosophy reflects a deeper epistemology」的「This training philosophy」回指前段描述的嚴苛學徒訓練（研磨工具），揭示其背後的知識論——程序性而非命題性知識。",
        "「This measured flexibility is not a structural weakness but a designed response」的「This measured flexibility」回指前段說明榫卯接頭允許微量位移的抗震性質，並以法隆寺佐證其工程優越性。",
        "「Contemporary architects working outside the traditional temple context have been drawn to timber joinery」呼應前段現代與傳統並用的討論，說明榫卯原則在當代世俗建築中的延伸應用。",
        "「Documentation began in earnest after the Second World War」呼應前段說明傳統如何延續到21世紀並非偶然，揭示主動文獻化的歷史起點和迫切性。"
      ]
    }
  ];
  if (typeof module !== "undefined" && module.exports) { module.exports = BANK; return; }
  window.READING = window.READING || { mc: [], gap: [], match: [] };
  window.READING.gap = window.READING.gap.concat(BANK);
})();
