(function () {
var BANK = [
  {
    id: "p-rgap4-01",
    title: "The Voice in the Wax: A Short Life of the Cylinder",
    segments: [
      "Until the winter of 1877, sound was the most perishable thing in the world. Every voice that had ever spoken had died with its last echo; music existed only for as long as someone was making it. Then Thomas Edison, shouting a nursery rhyme at a sheet of tinfoil wrapped around a hand-cranked cylinder, heard the machine speak his own words back, and the oldest boundary in human experience quietly moved. What is less remembered is what Edison thought the miracle was actually for.",
      "That list, with entertainment loitering near its bottom, ranks among history's better jokes, and the correction came quickly and from below. Within a decade, businessmen who cared nothing for dying words had discovered where the money in recorded sound really lay.",
      "Pennies of that kind accumulated faster than dictation contracts ever had, and the phonograph's future as an amusement was settled. But the early industry laboured under a constraint that seems almost unbelievable now: the recordings themselves could not be multiplied.",
      "Exhaustion on that scale could not survive contact with a better idea, and the better idea arrived from a rival format. The cylinder's undoing was not a failure of sound but a failure of arithmetic.",
      "Against industrial multiplication of that kind, the cylinder had no answer, and by the 1910s the disc had taken the parlour. Yet the older format did not vanish; it retreated into the one niche where Edison had placed it in the first place, and there it proved surprisingly tenacious.",
      "There is a certain circular justice in that survival — the machine ending its commercial life doing exactly what its inventor first advertised. But the cylinder's deepest legacy was being written elsewhere, far from any office, by people who saw in the fragile wax something no disc factory cared about.",
      "Those wax fieldnotes now constitute an archive of unbearable preciousness and unbearable fragility: languages with no living speakers, songs whose last singers died a century ago. And the cruellest property of the medium is that consultation is destruction — each pass of the stylus shaves away a little of the very voice it summons.",
      "So the wheel comes fully around. A device built to trap sound in matter is rescued by a method that refuses to touch the matter at all, and voices recorded before anyone now alive was born climb out of the wax as clean as the day they entered it. Edison promised his customers that the phonograph would let the dead speak. It took a hundred and forty years, and instruments he never imagined, for the promise to be kept in full."
    ],
    options: [
      "Each cylinder was, in the strictest sense, an original: there was no way to copy one, so a 'recording session' meant performing the piece over and over, into banks of horns feeding a few machines at a time. A popular singer might deliver the same song forty times in a day, and a big seller condemned its artist to weeks of identical repetition. Recorded music, at its birth, was the most labour-intensive product in show business.",
      "The rescue has come from optics. Laboratories now photograph the groove at microscopic resolution, or trace it with light, and reconstruct the sound mathematically from the image — playback without contact, the stylus replaced by a beam that weighs nothing and wears nothing. Cylinders too cracked or mouldy ever to be played again have yielded clear voices to the scanner.",
      "In the prospectus he published within months of the invention, Edison listed the phonograph's likely uses in order of importance: letter-writing and dictation without a stenographer, books that would read themselves to the blind, the teaching of elocution, and the preservation of the last words of the dying. Reproducing music appears fourth, one place above the talking doll.",
      "Radio, when it arrived in the 1920s, briefly threatened to make all recorded formats obsolete at once. Why buy a performance when the air was full of free ones? Record sales collapsed across the decade, and the industry was saved less by any technical advance than by the jukebox boom and the dance crazes of the following one.",
      "The niche was the office. As a dictation machine — the use its inventor had ranked first all along — the wax cylinder outlived its musical self by half a century. Executives spoke their correspondence into Ediphones and Dictaphones whose cylinders could be shaved smooth and re-recorded dozens of times, and the last of these machines were still taking letters in the 1950s.",
      "Emile Berliner's gramophone recorded not on a cylinder but on a flat disc, and the disc could be stamped. From a single master, a press could squeeze out thousands of identical copies at a fraction of the cost, the way a mint strikes coins. One performance now sufficed for a nation of listeners, and the price of owning music fell accordingly.",
      "The people were ethnographers and folklorists, and they carried the phonograph out of the parlour and into the field. From the 1890s onwards, collectors lugged the machines to reservations, villages and remote islands, recording epics, laments and whole languages that written notation had always flattened or missed. For the first time, a vanishing voice could be argued with, checked, and heard again.",
      "They installed coin-in-the-slot phonographs in drugstores, saloons and railway waiting rooms: a nickel bought two minutes of a song or a comic monologue through listening tubes. A single well-placed machine could earn more in a week than a clerk did in a month, and the 'phonograph parlour' — ancestor of the jukebox and, arguably, of every media vending system since — spread across America."
    ],
    answers: [2, 7, 0, 5, 4, 6, 1],
    explanations: [
      "The first segment ends by asking 'what Edison thought the miracle was actually for'; the option supplies his prospectus list with music near the bottom, and the next segment's 'That list, with entertainment loitering near its bottom' refers straight back to it.",
      "The previous text says businessmen 'discovered where the money in recorded sound really lay'; the option describes the nickel-in-the-slot phonograph parlours, whose takings the next segment picks up as 'Pennies of that kind'.",
      "The preceding segment says recordings 'could not be multiplied'; the option explains that every cylinder was an original, forcing singers into endless repetition, which the next segment summarises as 'Exhaustion on that scale'.",
      "The previous text promises an undoing that 'was not a failure of sound but a failure of arithmetic'; the option gives Berliner's stampable disc — thousands of copies from one master — which the next segment calls 'industrial multiplication of that kind'.",
      "The preceding segment says the cylinder retreated into 'the one niche where Edison had placed it in the first place'; the option identifies office dictation, his top-ranked use, matching the next segment's 'circular justice' of the machine doing what its inventor first advertised.",
      "The previous text says the legacy was written 'far from any office, by people who saw in the fragile wax something no disc factory cared about'; the option names the ethnographers recording vanishing languages, and the next segment's 'Those wax fieldnotes' refers to their work.",
      "The preceding segment laments that 'consultation is destruction' since the stylus shaves the wax; the option supplies the optical rescue — playback without contact — which the final segment celebrates as a method 'that refuses to touch the matter at all'."
    ]
  },
  {
    id: "p-rgap4-02",
    title: "Paper Promises: A Short History of the Banknote",
    segments: [
      "The note in your wallet is one of the most audacious confidence tricks ever institutionalised: a scrap of printed cotton, intrinsically worth nothing, which strangers will nonetheless exchange for dinner, shelter or a day of their labour. Like most tricks of genius, it was invented far from Europe and long before Europeans were ready to believe in it.",
      "Polo's readers largely refused to believe him, filing paper money alongside his other travellers' tales, and Europe took another four centuries to stumble upon the idea independently. When it did, the inventors were not emperors but tradesmen solving a storage problem.",
      "Once the receipt itself would circulate, a discovery of alarming beauty followed: since depositors never came for all their gold at once, a goldsmith could issue more receipts than he had metal, and the surplus paper was, in effect, money conjured from confidence alone. It was only a matter of time before somebody tested how far the conjuring could go.",
      "Ruin on that scale taught Europe a fear of printed money that lasted a century, and the eventual remedy was not to abandon the trick but to nationalise it. If paper was to circulate, the reasoning ran, only one institution in each realm should be allowed to perform the magic.",
      "A promise so public, printed in millions, naturally attracted those who preferred to print their own, and the banknote's whole subsequent history can be read as an arms race between the engraver and the forger.",
      "The race never ended; it merely changed materials. What the eighteenth century fought with the gallows, the twenty-first fights with physics and chemistry.",
      "The irony of the present moment is hard to miss: just as the banknote has become almost impossible to counterfeit, it has begun to disappear from daily life altogether — not defeated by forgers, but deserted by its users.",
      "Yet the obituaries may be premature. Cash still works when the power fails and the network falls over; it settles a debt without asking either party's name, a discretion no card can offer; and in every crisis, from pandemics to bank runs, the queues at the machines show where trust retreats to when the abstractions wobble. The trick, it turns out, was never really about paper. It was about promise made visible — and people like to be able to hold a promise in their hands."
    ],
    options: [
      "The Bank of England, chartered in 1694 to fund a war and granted a gradual monopoly of issue, turned the note into a standardised public promise. The wording it settled on — 'I promise to pay the bearer on demand the sum of...' — survives on British notes to this day, a fossil of the era when the paper was still, in theory, a claim on gold in a vault.",
      "Rome had run the same experiment with metal. Successive emperors, short of silver, quietly reduced the precious content of the denarius until the coin was little more than washed bronze, and prices duly soared. Debasement, however, at least left something physical in the hand; the coin was diminished, not imaginary.",
      "China got there first, and by a wide margin. Tang dynasty merchants, weary of hauling strings of bronze coins, developed deposit certificates known as 'flying cash', and by the eleventh century the Song state was printing true circulating notes. Marco Polo devoted an astonished chapter to the system, marvelling that the Great Khan made money out of the bark of trees and that refusing it was punished as a capital offence.",
      "The Swedes, who were among the first Europeans to issue banknotes, are now among the first to abandon them: cash transactions there have fallen to a few per cent of the total, many banks hold no notes at all, and buses will not accept them. Cards, phones and instant transfers have made the pocketful of paper feel, to a generation, as quaint as a pocket watch.",
      "The goldsmiths of seventeenth-century London kept strongrooms, and customers left bullion and coin with them for safekeeping, taking a written receipt. It did not take long to notice that a purchase could be settled by handing over the receipt itself rather than fetching the metal — and once the receipts circulated from hand to hand, the paper was functioning as money in everything but name.",
      "Modern notes answer the threat with physics: polymer substrates that tear like cloth or not at all, holograms that shift image with the angle, windows of clear film, inks that change colour as the note tilts, and microprinting legible only under a lens. Each feature is chosen less to be impossible to copy than to be uneconomic to copy well.",
      "The test came in France, and it nearly destroyed the kingdom's finances. John Law, a Scottish gambler turned economic visionary, persuaded the Regent in 1716 to let his bank issue paper backed by the imagined riches of Louisiana. Shares and notes multiplied gloriously for four years; then confidence turned, the paper collapsed to nothing, and a generation of French statesmen treated the very word 'banque' as an obscenity.",
      "Governments answered with theatrical severity. In eighteenth-century England, forging a note was a capital crime, and hundreds went to the gallows for it — including, notoriously, poor recipients who had merely passed on a fake. The Bank of England meanwhile hired ever finer engravers, on the sound principle that the best defence was a note too intricate to imitate profitably."
    ],
    answers: [2, 4, 6, 0, 7, 5, 3],
    explanations: [
      "The opening segment says the trick 'was invented far from Europe and long before Europeans were ready to believe in it'; the option supplies China's flying cash and Marco Polo's astonished chapter, to which the next segment's 'Polo's readers largely refused to believe him' refers directly.",
      "The previous text says Europe's inventors were 'tradesmen solving a storage problem'; the option describes the London goldsmiths whose receipts began to circulate, and the next segment opens 'Once the receipt itself would circulate', continuing the thought.",
      "The preceding segment says it was 'only a matter of time before somebody tested how far the conjuring could go'; the option is John Law's paper scheme and its collapse, which the next segment calls 'Ruin on that scale'.",
      "The previous text says 'only one institution in each realm should be allowed to perform the magic'; the option gives the Bank of England's monopoly and its printed promise to the bearer, which the next segment picks up as 'A promise so public'.",
      "The preceding segment announces 'an arms race between the engraver and the forger'; the option supplies both sides — the gallows for forgers and ever finer engraving — and the next segment's 'What the eighteenth century fought with the gallows' refers back to it.",
      "The previous text says the modern race is fought 'with physics and chemistry'; the option lists polymer, holograms and colour-shifting inks, exactly the material weapons the transition promised.",
      "The preceding segment says the note is 'deserted by its users'; the option describes Sweden's near-cashless economy, the concrete case of desertion, and the final segment's 'the obituaries may be premature' answers it."
    ]
  },
  {
    id: "p-rgap4-03",
    title: "Worth Its Salt: The Rise and Fall of a Strategic Mineral",
    segments: [
      "Of all the substances on a kitchen shelf, the cheapest is the one that has started wars, financed empires and helped bring one of them down. A kilogram of salt now costs less than a newspaper, and the collapse in its dignity has been so total that we need an effort of imagination to see what our ancestors saw: a substance on which life itself, quite literally, depended.",
      "A substance answering to needs of that order was never going to remain a mere seasoning; it became wealth, and the languages we speak still carry the receipts.",
      "Etymology of that kind is charming; the fiscal history is grimmer. A commodity that everyone must buy, in roughly equal amounts, is a tax collector's dream — and few states resisted the dream for long.",
      "France was not the last regime to learn what salt could do to an empire's legitimacy. A century and a half later, the same lesson was administered on the other side of the world, this time by design.",
      "A commodity that could carry a revolution on its back was, by then, already living on borrowed time as a strategic asset, because geology and engineering were quietly abolishing its scarcity.",
      "Abundance dethroned the old king, but did not retire him; it redeployed him. The salt of the twenty-first century leads a double life, and the pinch on your table is the smaller half of it.",
      "Invisibility of that industrial sort is the usual fate of conquered kings. Yet salt has forced its way back into public argument by one last route — not through the treasury or the chemical works, but through the body that craved it in the first place.",
      "So the story closes on a neat reversal. For most of history, the human problem with salt was getting enough of it; for the affluent present, the problem is stopping. The appetite that made it precious — precious enough to tax, to march for, to die over — has outlived the scarcity that made the appetite dangerous to ignore, and the old king, dethroned and invisible, still rules us from inside."
    ],
    options: [
      "Mohandas Gandhi chose it as the perfect grievance. In 1930 he walked two hundred and forty miles to the sea at Dandi and, before the world's cameras, picked up a handful of salt in defiance of the British monopoly, which taxed a substance the poorest labourer sweated away daily and forbade him to gather freely from his own coastline. The genius of the gesture was its legibility: no peasant needed the economics explained, and the empire was left prosecuting people for possessing seawater's residue.",
      "The discovery was that the earth is, in places, made of the stuff. Geologists traced beds of rock salt hundreds of metres thick — the corpses of vanished seas — under Cheshire, Poland and half of North America, while engineers learned to dissolve it out with pumped water at trifling cost. A substance once worth guarding with garrisons became, within two generations, one of the cheapest industrial materials on earth.",
      "Pepper tells a parallel story of preciousness. The vines grew only on the Malabar coast, and the trade that carried the dried berries westward enriched Venice, provoked the Portuguese voyages, and made 'peppercorn' a byword first for wealth and only much later for a trifling rent. But pepper was always a luxury of the tongue; no one ever died for lack of it.",
      "The dependence is written into our physiology. Sodium is what nerves fire with and what blood pressure is regulated by, and a body deprived of it dies more quickly than one deprived of food. Before refrigeration, salt was also the only technology that could hold decay at bay: the salted cod, the brined pork and the pickled cabbage in the barrel were not delicacies but the entire winter food supply of northern Europe.",
      "Hence the modern indictment. Physicians point out that affluent populations now consume several times the sodium their bodies need, with measurable costs in hypertension and stroke, and public-health campaigns treat the salt cellar much as they treat the ashtray. The appetite itself is blameless but obsolete: a craving calibrated for a world of scarcity, marooned in a world of abundance.",
      "The most notorious example was the French gabelle, a royal salt tax of grotesque design: households were compelled to buy a fixed quantity at official prices, which varied so wildly between provinces that a pound of salt cost thirty times more on one bank of a river than on the other. Smuggling became a mass profession, thousands of 'faux-sauniers' were sent to the galleys, and when the Revolution came, the gabelle was among the first grievances burned — its collectors among the first casualties.",
      "Roman soldiers received part of their pay as an allowance for salt — the salarium from which every modern 'salary' descends — and one of the empire's oldest roads, the Via Salaria, exists because the mineral had to move from the coastal pans to the city. To question whether a man is 'worth his salt' is to speak, without knowing it, the language of a quartermaster two thousand years dead.",
      "The larger half works unseen. Roughly two-thirds of production goes to the chemical industry, where salt is cracked into chlorine and caustic soda — the ancestors of plastics, disinfectants, paper and glass — and a further great tranche is scattered on winter roads, where a single icy week can consume more salt than a nation's kitchens use in a year."
    ],
    answers: [3, 6, 5, 0, 1, 7, 4],
    explanations: [
      "The opening segment ends with salt as 'a substance on which life itself, quite literally, depended'; the option grounds that claim in physiology and pre-refrigeration preservation, and the next segment's 'needs of that order' refers back to both.",
      "The previous text says 'the languages we speak still carry the receipts'; the option supplies the linguistic evidence — salarium, 'worth his salt', the Via Salaria — which the next segment dismisses fondly as 'Etymology of that kind'.",
      "The preceding segment calls universal salt consumption 'a tax collector's dream'; the option describes the French gabelle and its role in the Revolution, and the next segment's 'France was not the last regime' refers straight back to it.",
      "The previous text promises 'the same lesson... administered on the other side of the world, this time by design'; the option is Gandhi's Salt March, the deliberately staged colonial lesson, which the next segment calls 'a commodity that could carry a revolution on its back'.",
      "The preceding segment says 'geology and engineering were quietly abolishing its scarcity'; the option describes the discovery of vast rock-salt beds and cheap extraction, which the next segment summarises as 'Abundance dethroned the old king'.",
      "The previous text says modern salt 'leads a double life, and the pinch on your table is the smaller half'; the option details the larger half — chlorine chemistry and road de-icing — the unseen industrial career the next segment calls 'Invisibility of that industrial sort'.",
      "The preceding segment says salt returned to public argument 'through the body that craved it'; the option presents the health indictment of excess sodium and the obsolete appetite, which the final segment's 'the problem is stopping' carries to its conclusion."
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.gap = window.READING.gap.concat(BANK);
})();
