/* CPE Prep extra vocab wave 5 */
(function () {
  var BANK = [
    { front: "posit", pos: "v.", def: "put forward as a basis for argument", example: "The theory posits a direct link between inequality and social unrest.", zh: "假定；提出（論點）" },
    { front: "postulate", pos: "v.", def: "assume as true for the sake of reasoning", example: "Economists postulate that consumers behave rationally, which is rarely borne out.", zh: "假設；假定" },
    { front: "explicate", pos: "v.", def: "analyse and explain in detail", example: "Her lecture explicated the poem's dense allusions with admirable clarity.", zh: "詳細闡明；解說" },
    { front: "adduce", pos: "v.", def: "cite as evidence in support of an argument", example: "The prosecution adduced telephone records to establish the defendant's whereabouts.", zh: "舉出（證據）；引證" },
    { front: "aver", pos: "v.", def: "state or assert confidently", example: "The minister averred that no public funds had been misappropriated.", zh: "斷言；堅稱" },
    { front: "ascribe", pos: "v.", def: "attribute something to a cause or source", example: "Critics ascribe the film's failure to its meandering script.", zh: "把…歸因於" },
    { front: "presuppose", pos: "v.", def: "require as a prior condition; assume beforehand", example: "The argument presupposes a level of literacy that many voters lack.", zh: "以…為前提；預先假定" },
    { front: "underscore", pos: "v.", def: "emphasise or highlight the importance of", example: "The report underscores the urgency of reforming the pension system.", zh: "強調；凸顯" },
    { front: "transcend", pos: "v.", def: "go beyond the limits of", example: "Her music transcends genre, appealing to purists and casual listeners alike.", zh: "超越；凌駕" },
    { front: "typify", pos: "v.", def: "be a characteristic example of", example: "The dispute typifies the friction between regulators and the tech industry.", zh: "為…的典型；代表" },
    { front: "vitiate", pos: "v.", def: "spoil or impair the quality or validity of", example: "The survey's findings were vitiated by a woefully unrepresentative sample.", zh: "損害；使無效" },
    { front: "ossify", pos: "v.", def: "become rigid and cease to develop", example: "Once-radical institutions tend to ossify into bureaucratic complacency.", zh: "僵化；停滯不前" },
    { front: "codify", pos: "v.", def: "arrange rules or laws into a systematic code", example: "The new charter codifies practices that had long been merely customary.", zh: "編纂；使法典化" },
    { front: "ratify", pos: "v.", def: "give formal consent to; make officially valid", example: "Parliament must still ratify the treaty before it takes effect.", zh: "批准；正式認可" },
    { front: "annul", pos: "v.", def: "declare legally invalid", example: "The constitutional court annulled the election results amid fraud allegations.", zh: "宣告無效；廢除" },
    { front: "adjudicate", pos: "v.", def: "make a formal judgement on a dispute", example: "An independent panel was appointed to adjudicate the boundary dispute.", zh: "裁決；判定" },
    { front: "arbitrate", pos: "v.", def: "settle a dispute as a neutral third party", example: "A retired judge was brought in to arbitrate between the union and management.", zh: "仲裁；調停" },
    { front: "indict", pos: "v.", def: "formally charge with a serious crime", example: "The grand jury voted to indict the executive on fraud charges.", zh: "起訴；控告" },
    { front: "incriminate", pos: "v.", def: "make someone appear guilty of wrongdoing", example: "He refused to answer questions that might incriminate his colleagues.", zh: "使入罪；連累" },
    { front: "implicate", pos: "v.", def: "show someone to be involved in wrongdoing", example: "Leaked documents implicate several officials in the bribery scheme.", zh: "牽連；顯示涉入" },
    { front: "absolve", pos: "v.", def: "declare free from blame or responsibility", example: "The inquiry absolved the pilot of any responsibility for the crash.", zh: "免除（責任）；赦免" },
    { front: "acquit", pos: "v.", def: "declare not guilty of a criminal charge", example: "After a six-week trial, the jury acquitted her on all counts.", zh: "宣判無罪" },
    { front: "vilify", pos: "v.", def: "speak or write about in an abusively disparaging way", example: "The whistle-blower was vilified in the tabloid press for months.", zh: "詆毀；醜化" },
    { front: "lionise", pos: "v.", def: "treat someone as a celebrity or hero", example: "The young novelist was lionised by critics after her stunning debut.", zh: "把…捧為名人；追捧" },
    { front: "demonise", pos: "v.", def: "portray as wicked or threatening", example: "Populist rhetoric routinely demonises immigrants as a drain on resources.", zh: "妖魔化" },
    { front: "sensationalise", pos: "v.", def: "present information in an exaggerated, lurid way", example: "The coverage sensationalised a routine dispute into a national scandal.", zh: "以聳動手法渲染" },
    { front: "trivialise", pos: "v.", def: "make something seem less important than it is", example: "Reducing the crisis to a soundbite trivialises the suffering involved.", zh: "使顯得瑣碎；輕描淡寫" },
    { front: "marginalise", pos: "v.", def: "push to the edge of society or a group", example: "Austerity policies further marginalised communities already struggling to cope.", zh: "使邊緣化" },
    { front: "monopolise", pos: "v.", def: "have or take exclusive control of", example: "One conglomerate has effectively monopolised the domestic media market.", zh: "壟斷；獨占" },
    { front: "polarise", pos: "v.", def: "divide into sharply opposing groups", example: "The referendum polarised the country along generational lines.", zh: "使兩極化" },
    { front: "politicise", pos: "v.", def: "make a matter political in character", example: "Scientists warned against politicising what should be an empirical question.", zh: "使政治化" },
    { front: "legitimise", pos: "v.", def: "make lawful or acceptable", example: "Granting the group airtime risks legitimising its extremist views.", zh: "使合法化；使正當化" },
    { front: "embroil", pos: "v.", def: "involve deeply in conflict or difficulty", example: "The firm became embroiled in a protracted legal battle over patents.", zh: "使捲入（紛爭）" },
    { front: "enshrine", pos: "v.", def: "preserve a right or principle in law", example: "Freedom of assembly is enshrined in the constitution.", zh: "（將權利）載入；奉為神聖" },
    { front: "burnish", pos: "v.", def: "polish; enhance a reputation or image", example: "The charity gala was a transparent attempt to burnish his public image.", zh: "擦亮；提升（形象）" },
    { front: "fortify", pos: "v.", def: "strengthen against attack or difficulty", example: "The central bank fortified its reserves against further currency speculation.", zh: "加強；鞏固" },
    { front: "crystallise", pos: "v.", def: "make or become clear and definite", example: "The debate crystallised public anxiety about artificial intelligence.", zh: "使具體化；使明朗" },
    { front: "distil", pos: "v.", def: "extract the essential meaning of something", example: "The editor distilled two hundred pages of testimony into a crisp summary.", zh: "提煉；萃取（要旨）" },
    { front: "synthesise", pos: "v.", def: "combine elements into a coherent whole", example: "The review synthesises findings from over forty independent studies.", zh: "綜合；統整" },
    { front: "contextualise", pos: "v.", def: "place in a context for better understanding", example: "The exhibition contextualises the paintings within the artist's turbulent life.", zh: "置於脈絡中理解" },
    { front: "exhume", pos: "v.", def: "dig up a body; revive something forgotten", example: "Historians exhumed long-forgotten archives to challenge the official narrative.", zh: "掘出；重新發掘" },
    { front: "exhilarate", pos: "v.", def: "make someone feel very happy and energised", example: "The audience left the premiere visibly exhilarated by the performance.", zh: "使興奮；使振奮" },
    { front: "rejuvenate", pos: "v.", def: "make someone or something feel or seem younger", example: "The new director has rejuvenated a festival that had grown stale.", zh: "使恢復活力" },
    { front: "revitalise", pos: "v.", def: "give new life or vigour to", example: "The grant scheme aims to revitalise the city's derelict docklands.", zh: "使復甦；振興" },
    { front: "resuscitate", pos: "v.", def: "revive from unconsciousness; bring back to life", example: "The government is attempting to resuscitate stalled peace negotiations.", zh: "使甦醒；使復活" },
    { front: "reinstate", pos: "v.", def: "restore to a former position or state", example: "The tribunal ordered the company to reinstate the dismissed engineers.", zh: "使復職；恢復" },
    { front: "founder", pos: "v.", def: "fail or collapse; fill with water and sink", example: "The coalition talks foundered on the question of tax policy.", zh: "（計畫）失敗；（船）沉沒" },
    { front: "smoulder", pos: "v.", def: "burn slowly without flame; harbour suppressed feeling", example: "Resentment over the verdict smouldered in the community for years.", zh: "悶燒；（情緒）鬱積" },
    { front: "escalate", pos: "v.", def: "increase rapidly in intensity or seriousness", example: "A minor border incident quickly escalated into open hostilities.", zh: "升級；愈演愈烈" },
    { front: "aggravate", pos: "v.", def: "make a problem or condition worse", example: "The fuel shortage was aggravated by panic buying across the region.", zh: "使惡化；加劇" },
    { front: "compound", pos: "v.", def: "make a bad situation worse", example: "The airline compounded its error by refusing to apologise.", zh: "使（問題）雪上加霜" },
    { front: "entail", pos: "v.", def: "involve as a necessary consequence", example: "Hosting the summit entails security costs the city can ill afford.", zh: "必然涉及；需要" },
    { front: "necessitate", pos: "v.", def: "make something necessary as a result", example: "The discovery of asbestos necessitated the evacuation of the entire wing.", zh: "使成為必要" },
    { front: "warrant", pos: "v.", def: "justify or deserve a course of action", example: "The allegations are serious enough to warrant an independent inquiry.", zh: "使有正當理由；值得" },
    { front: "embolden", pos: "v.", def: "give courage or confidence to", example: "Early victories emboldened the protesters to press for wider reforms.", zh: "使大膽；壯膽" },
    { front: "hobble", pos: "v.", def: "walk awkwardly; restrict progress or effectiveness", example: "Chronic underinvestment has hobbled the railway network for decades.", zh: "跛行；牽制" },
    { front: "scupper", pos: "v.", def: "ruin a plan deliberately; sink a ship", example: "A last-minute veto scuppered months of painstaking diplomacy.", zh: "使（計畫）泡湯；破壞" },
    { front: "torpedo", pos: "v.", def: "deliberately wreck a plan or negotiation", example: "The leaked memo torpedoed any hope of a merger.", zh: "破壞；使徹底失敗" },
    { front: "derail", pos: "v.", def: "obstruct a process by diverting it from its course", example: "Hardliners on both sides sought to derail the peace process.", zh: "使出軌；使偏離正軌" },
    { front: "shelve", pos: "v.", def: "postpone or cancel a plan indefinitely", example: "The expansion project was shelved when interest rates soared.", zh: "擱置（計畫）" },
    { front: "mothball", pos: "v.", def: "put out of use indefinitely while preserving it", example: "Two power stations were mothballed pending a review of energy policy.", zh: "封存；長期停用" },
    { front: "rubber-stamp", pos: "v.", def: "approve automatically without proper consideration", example: "Critics accuse the board of merely rubber-stamping executive decisions.", zh: "橡皮圖章式批准" },
    { front: "underwrite", pos: "v.", def: "accept financial responsibility for; guarantee", example: "The treasury agreed to underwrite the losses of the ailing insurer.", zh: "承擔（費用）；擔保" },
    { front: "bankroll", pos: "v.", def: "provide the money to fund something", example: "The campaign was quietly bankrolled by a handful of hedge-fund donors.", zh: "出資；資助" },
    { front: "recoup", pos: "v.", def: "regain money that has been spent or lost", example: "The studio needs a global hit to recoup its enormous outlay.", zh: "收回（成本）；彌補損失" },
    { front: "offset", pos: "v.", def: "counterbalance or compensate for", example: "Gains in exports were offset by a sharp rise in import costs.", zh: "抵銷；補償" },
    { front: "outpace", pos: "v.", def: "go faster than; surpass in growth or progress", example: "Wage growth has consistently failed to outpace inflation.", zh: "超越；比…快" },
    { front: "eclipse", pos: "v.", def: "surpass and make less important", example: "The scandal has eclipsed every other story on the front pages.", zh: "使黯然失色；蓋過" },
    { front: "dwarf", pos: "v.", def: "make something seem small by comparison", example: "The rescue package dwarfs any previous government intervention.", zh: "使相形見絀" },
    { front: "overshadow", pos: "v.", def: "cast gloom over; appear more prominent than", example: "The ceremony was overshadowed by news of the ambassador's resignation.", zh: "使蒙上陰影；掩蓋" },
    { front: "overstate", pos: "v.", def: "express too strongly; exaggerate", example: "It is hard to overstate the significance of this ruling.", zh: "誇大；言過其實" },
    { front: "belittle", pos: "v.", def: "dismiss as unimportant; disparage", example: "He habitually belittled his rivals' achievements in interviews.", zh: "貶低；輕視" },
    { front: "extort", pos: "v.", def: "obtain by force, threats, or coercion", example: "The gang extorted protection money from local shopkeepers.", zh: "勒索；敲詐" },
    { front: "defraud", pos: "v.", def: "illegally obtain money by deception", example: "The accountant defrauded investors of millions over a decade.", zh: "詐騙；詐取" },
    { front: "launder", pos: "v.", def: "conceal the origins of illegally obtained money", example: "The shell companies were used to launder the proceeds of corruption.", zh: "洗錢" },
    { front: "collude", pos: "v.", def: "cooperate secretly for a dishonest purpose", example: "The airlines were fined for colluding to fix ticket prices.", zh: "勾結；共謀" },
    { front: "abet", pos: "v.", def: "assist or encourage wrongdoing", example: "He was charged with abetting the escape of a convicted felon.", zh: "教唆；協助（犯罪）" },
    { front: "perpetrate", pos: "v.", def: "carry out a harmful or illegal act", example: "The fraud was perpetrated over years without arousing suspicion.", zh: "犯下；施行（惡行）" },
    { front: "perpetuate", pos: "v.", def: "cause to continue indefinitely", example: "Such stereotypes perpetuate inequality across generations.", zh: "使長存；使持續" },
    { front: "propagate", pos: "v.", def: "spread an idea widely; breed plants", example: "State media were used to propagate the official version of events.", zh: "散播；繁殖" },
    { front: "proliferate", pos: "v.", def: "increase rapidly in number; multiply", example: "Conspiracy theories proliferated online within hours of the announcement.", zh: "激增；擴散" },
    { front: "supersede", pos: "v.", def: "take the place of something older or less effective", example: "The 1998 guidelines have long since been superseded by stricter rules.", zh: "取代；替代" },
    { front: "abdicate", pos: "v.", def: "renounce a throne; fail to fulfil a duty", example: "By ignoring the warnings, the regulator abdicated its responsibility.", zh: "退位；放棄（職責）" },
    { front: "waive", pos: "v.", def: "voluntarily give up a right or claim", example: "The university agreed to waive tuition fees for displaced students.", zh: "放棄（權利）；免除" },
    { front: "forfeit", pos: "v.", def: "lose a right or possession as a penalty", example: "Players who breach the code forfeit their prize money.", zh: "喪失；被沒收" },
    { front: "concede", pos: "v.", def: "admit reluctantly; surrender a point or contest", example: "The incumbent conceded defeat shortly after midnight.", zh: "承認；讓步" },
    { front: "prevail", pos: "v.", def: "prove more powerful; be widespread", example: "Common sense eventually prevailed over partisan bickering.", zh: "獲勝；盛行" },
    { front: "subdue", pos: "v.", def: "bring under control by force or persuasion", example: "Riot police struggled to subdue the crowds outside parliament.", zh: "制伏；壓制" },
    { front: "muzzle", pos: "v.", def: "prevent from expressing opinions freely", example: "The decree effectively muzzles independent journalists.", zh: "壓制言論；使噤聲" },
    { front: "redact", pos: "v.", def: "censor or obscure parts of a text", example: "The released files were so heavily redacted as to be useless.", zh: "遮蔽（機密內容）；刪修" },
    { front: "disclose", pos: "v.", def: "make secret or new information known", example: "Directors must disclose any conflict of interest before the vote.", zh: "揭露；公開" },
    { front: "withhold", pos: "v.", def: "refuse to give something due or desired", example: "The agency withheld crucial evidence from the defence team.", zh: "扣留；拒絕給予" },
    { front: "repeal", pos: "v.", def: "officially revoke a law", example: "Campaigners are pressing parliament to repeal the outdated statute.", zh: "廢除（法律）" },
    { front: "enact", pos: "v.", def: "make a bill into law; put into practice", example: "The reforms were enacted despite fierce lobbying from industry.", zh: "制定（法律）；實施" },
    { front: "infringe", pos: "v.", def: "violate a law, right, or agreement", example: "The surveillance programme infringes citizens' right to privacy.", zh: "侵犯；違反" },
    { front: "waver", pos: "v.", def: "become unsteady; hesitate between options", example: "Her resolve never wavered, even under relentless cross-examination.", zh: "動搖；猶豫" },
    { front: "recoil", pos: "v.", def: "spring back in fear or disgust", example: "Voters recoiled from the party's increasingly strident rhetoric.", zh: "退縮；畏縮" },
    { front: "flinch", pos: "v.", def: "make a quick nervous movement; shrink from", example: "She did not flinch from naming those responsible.", zh: "退縮；畏怯" },
    { front: "grimace", pos: "v.", def: "twist the face in pain or disgust", example: "He grimaced at the mention of his earlier, disowned work.", zh: "做鬼臉；面部扭曲" },
    { front: "sneer", pos: "v.", def: "smile or speak with contemptuous mockery", example: "Critics sneered at the novel, which nonetheless became a classic.", zh: "嘲笑；譏諷" },
    { front: "satirise", pos: "v.", def: "mock through humour, irony, or exaggeration", example: "The play satirises the vanity of the political establishment.", zh: "諷刺" },
    { front: "whistle-blower", pos: "n.", def: "person who exposes wrongdoing within an organisation", example: "The whistle-blower was granted anonymity before testifying to the committee.", zh: "吹哨者；揭弊者" },
    { front: "soundbite", pos: "n.", def: "short, memorable extract from a speech", example: "Complex policy was reduced to a string of glib soundbites.", zh: "（媒體）金句；簡短引語" },
    { front: "embargo", pos: "n.", def: "official ban on trade or publication", example: "The arms embargo has been in force for over a decade.", zh: "禁運；禁令" },
    { front: "libel", pos: "n.", def: "published false statement damaging a reputation", example: "The actor sued the newspaper for libel and won substantial damages.", zh: "誹謗（文字）" },
    { front: "disinformation", pos: "n.", def: "deliberately false information spread to deceive", example: "The campaign was targeted by a coordinated disinformation operation.", zh: "假訊息；不實資訊" },
    { front: "curmudgeon", pos: "n.", def: "bad-tempered, grumpy person", example: "The columnist cultivated his reputation as a lovable curmudgeon.", zh: "壞脾氣的人；老頑固" },
    { front: "doyen", pos: "n.", def: "most respected senior member of a field", example: "She is widely regarded as the doyen of investigative journalism.", zh: "資深泰斗；元老" },
    { front: "exponent", pos: "n.", def: "person who promotes or skilfully practises something", example: "He was an early exponent of evidence-based policymaking.", zh: "倡導者；能手" },
    { front: "proponent", pos: "n.", def: "person who advocates a theory or course of action", example: "Proponents of the scheme insist the costs are exaggerated.", zh: "支持者；提倡者" },
    { front: "detractor", pos: "n.", def: "person who criticises or disparages someone", example: "Even her fiercest detractors concede the reform was overdue.", zh: "批評者；貶低者" },
    { front: "adherent", pos: "n.", def: "supporter of a party, idea, or leader", example: "The movement's adherents span every social class.", zh: "擁護者；信徒" },
    { front: "bellwether", pos: "n.", def: "indicator of a trend; leader others follow", example: "The constituency is seen as a bellwether for national sentiment.", zh: "風向標；領頭羊" },
    { front: "behemoth", pos: "n.", def: "something enormous, especially a large organisation", example: "Small retailers cannot compete with the online behemoths.", zh: "龐然大物；巨獸" },
    { front: "uptick", pos: "n.", def: "small increase or upward trend", example: "Analysts noted a modest uptick in consumer confidence.", zh: "小幅上升" },
    { front: "austerity", pos: "n.", def: "severe economic restraint; plainness", example: "A decade of austerity hollowed out local public services.", zh: "撙節；緊縮政策" },
    { front: "brinkmanship", pos: "n.", def: "pushing a dispute to the edge of disaster", example: "The budget standoff descended into reckless political brinkmanship.", zh: "邊緣策略；玩火手段" },
    { front: "detente", pos: "n.", def: "easing of hostility between countries", example: "The summit marked a cautious detente between the two rivals.", zh: "（緊張關係）緩和" },
    { front: "gerrymandering", pos: "n.", def: "manipulating electoral boundaries for advantage", example: "The court ruled that the map amounted to blatant gerrymandering.", zh: "不公正劃分選區" },
    { front: "filibuster", pos: "n.", def: "prolonged speech obstructing legislative progress", example: "Opposition senators mounted a filibuster to delay the vote.", zh: "冗長演說阻撓議事" },
    { front: "oligarchy", pos: "n.", def: "government by a small privileged group", example: "Critics say the country has drifted from democracy towards oligarchy.", zh: "寡頭政治" },
    { front: "caricature", pos: "n.", def: "grotesquely exaggerated portrayal of someone", example: "The debate reduced both candidates to crude caricatures.", zh: "諷刺畫；誇張醜化的描繪" },
    { front: "rhetoric", pos: "n.", def: "persuasive language, often insincere or exaggerated", example: "Behind the lofty rhetoric lay a distinctly modest proposal.", zh: "花言巧語；修辭" },
    { front: "polemic", pos: "n.", def: "strongly worded attack on an opinion", example: "Her latest book is a polemic against consumer culture.", zh: "抨擊性言論；論戰" },
    { front: "vitriol", pos: "n.", def: "bitter, caustic criticism or malice", example: "The online vitriol directed at the referee was appalling.", zh: "尖酸刻薄的言語" },
    { front: "reprisal", pos: "n.", def: "act of retaliation for harm suffered", example: "Villagers feared reprisals if they spoke to reporters.", zh: "報復（行動）" },
    { front: "retribution", pos: "n.", def: "punishment inflicted as vengeance", example: "The mob demanded swift retribution for the betrayal.", zh: "報應；懲罰" },
    { front: "amnesty", pos: "n.", def: "official pardon for offences", example: "The government declared an amnesty for undocumented migrants.", zh: "特赦；大赦" },
    { front: "litigation", pos: "n.", def: "process of taking legal action", example: "The dispute has generated years of costly litigation.", zh: "訴訟" },
    { front: "loophole", pos: "n.", def: "ambiguity allowing rules to be evaded", example: "Multinationals exploit tax loopholes that legislators never intended.", zh: "（法律）漏洞" },
    { front: "manifesto", pos: "n.", def: "public declaration of policies and aims", example: "The pledge appeared prominently in the party's election manifesto.", zh: "（政黨）宣言；政見" },
    { front: "constituency", pos: "n.", def: "voters in an electoral area; body of supporters", example: "She has represented the same rural constituency for thirty years.", zh: "選區；支持群體" },
    { front: "insurgency", pos: "n.", def: "armed rebellion against authority", example: "The insurgency spread rapidly through the northern provinces.", zh: "叛亂；暴動" },
    { front: "coup", pos: "n.", def: "sudden illegal seizure of power; notable achievement", example: "Securing the exclusive interview was a considerable coup for the paper.", zh: "政變；重大成就" },
    { front: "stalemate", pos: "n.", def: "situation in which neither side can progress", example: "Negotiations have reached a stalemate over fishing rights.", zh: "僵局" },
    { front: "deadlock", pos: "n.", def: "complete standstill in a dispute", example: "A marathon session failed to break the budget deadlock.", zh: "僵持；停頓" },
    { front: "standoff", pos: "n.", def: "deadlocked confrontation between opposing parties", example: "The armed standoff at the border lasted three tense days.", zh: "對峙；僵持局面" },
    { front: "ultimatum", pos: "n.", def: "final demand backed by a threat", example: "The union issued an ultimatum: restore pay or face a strike.", zh: "最後通牒" },
    { front: "concession", pos: "n.", def: "something granted to end a dispute", example: "Both sides will have to make painful concessions for peace.", zh: "讓步" },
    { front: "watchdog", pos: "n.", def: "organisation monitoring conduct or standards", example: "The media watchdog censured the broadcaster for misleading viewers.", zh: "監督機構" },
    { front: "ombudsman", pos: "n.", def: "official investigating complaints against institutions", example: "She referred her grievance to the financial ombudsman.", zh: "監察使；申訴專員" },
    { front: "oversight", pos: "n.", def: "supervision; an unintentional failure to notice", example: "The committee provides parliamentary oversight of the intelligence services.", zh: "監督；疏忽" },
    { front: "malfeasance", pos: "n.", def: "wrongdoing by a public official", example: "The mayor resigned amid allegations of malfeasance in office.", zh: "瀆職；不法行為" },
    { front: "malpractice", pos: "n.", def: "improper or negligent professional conduct", example: "The surgeon faces a string of malpractice suits.", zh: "失職；醫療疏失" },
    { front: "graft", pos: "n.", def: "corruption involving bribery; hard work (BrE)", example: "The tribunal exposed decades of graft in the licensing office.", zh: "貪污；（英）苦幹" },
    { front: "kickback", pos: "n.", def: "illicit payment for facilitating a transaction", example: "Contractors allegedly paid kickbacks to secure the tenders.", zh: "回扣；賄款" },
    { front: "patronage", pos: "n.", def: "support given by a patron; appointive favouritism", example: "Jobs in the ministry were dispensed through political patronage.", zh: "贊助；恩庇任命" },
    { front: "stipend", pos: "n.", def: "fixed regular payment, especially for training", example: "Doctoral students receive a modest stipend for teaching duties.", zh: "津貼；獎助金" },
    { front: "arrears", pos: "n.", def: "money owed that should already have been paid", example: "Thousands of tenants fell into rent arrears during the recession.", zh: "欠款；拖欠" },
    { front: "slump", pos: "n.", def: "sudden severe decline in prices or activity", example: "The housing slump wiped billions off household wealth.", zh: "暴跌；蕭條" },
    { front: "volatility", pos: "n.", def: "tendency to change rapidly and unpredictably", example: "Currency volatility has made exporters reluctant to invest.", zh: "波動性；不穩定" },
    { front: "attrition", pos: "n.", def: "gradual weakening through sustained pressure or loss", example: "The department shrank through natural attrition rather than redundancies.", zh: "消耗；自然減員" },
    { front: "redundancy", pos: "n.", def: "loss of a job because it is no longer needed", example: "The plant closure will mean eight hundred compulsory redundancies.", zh: "（英）裁員；資遣" },
    { front: "furlough", pos: "n.", def: "temporary leave from work, often unpaid", example: "Half the workforce was placed on furlough during the shutdown.", zh: "無薪假；暫時停職" },
    { front: "subsidy", pos: "n.", def: "government money supporting an industry or price", example: "Farm subsidies remain the most contentious item in the budget.", zh: "補貼；補助金" },
    { front: "tariff", pos: "n.", def: "tax on imports or exports", example: "Retaliatory tariffs threaten to ignite a full trade war.", zh: "關稅" },
    { front: "levy", pos: "n.", def: "sum of money raised by official demand", example: "A new levy on sugary drinks funds school sports programmes.", zh: "徵收的稅款" },
    { front: "remit", pos: "n.", def: "area of responsibility or authority", example: "Investigating private firms falls outside the committee's remit.", zh: "職權範圍" },
    { front: "purview", pos: "n.", def: "scope of influence, concern, or responsibility", example: "Online platforms now fall within the regulator's purview.", zh: "管轄範圍；權限" },
    { front: "jurisdiction", pos: "n.", def: "official power to make legal decisions", example: "The court ruled it had no jurisdiction over offshore assets.", zh: "司法管轄權" },
    { front: "proviso", pos: "n.", def: "condition attached to an agreement", example: "She accepted the post with the proviso that she could work remotely.", zh: "但書；附帶條件" },
    { front: "zeitgeist", pos: "n.", def: "defining spirit or mood of a period", example: "The novel captured the anxious zeitgeist of the post-war years.", zh: "時代精神" },
    { front: "ethos", pos: "n.", def: "characteristic spirit or values of a community", example: "Transparency is central to the organisation's ethos.", zh: "精神特質；風氣" },
    { front: "mores", pos: "n.", def: "customs and conventions of a community", example: "The play scandalised audiences by flouting Victorian social mores.", zh: "風俗習慣；道德觀" },
    { front: "orthodoxy", pos: "n.", def: "generally accepted belief or established practice", example: "Her findings challenge the prevailing economic orthodoxy.", zh: "正統觀念" },
    { front: "premise", pos: "n.", def: "statement on which reasoning is based", example: "The entire argument rests on a deeply questionable premise.", zh: "前提" },
    { front: "corollary", pos: "n.", def: "natural consequence or accompanying result", example: "Greater freedom brings, as its corollary, greater responsibility.", zh: "必然結果；推論" },
    { front: "dichotomy", pos: "n.", def: "sharp division between two opposed things", example: "The supposed dichotomy between growth and sustainability is a false one.", zh: "二分法；對立" },
    { front: "connotation", pos: "n.", def: "idea or feeling a word evokes beyond its meaning", example: "The word 'regime' carries unmistakably negative connotations.", zh: "言外之意；隱含意義" },
    { front: "vernacular", pos: "n.", def: "everyday language of ordinary people", example: "The sermon was delivered in the local vernacular rather than Latin.", zh: "方言；白話" },
    { front: "colloquialism", pos: "n.", def: "informal word or phrase used in conversation", example: "Avoid colloquialisms when drafting formal correspondence.", zh: "口語用法" },
    { front: "lingua franca", pos: "n.", def: "common language used between speakers of different tongues", example: "English serves as the lingua franca of international aviation.", zh: "通用語" },
    { front: "oxymoron", pos: "n.", def: "figure of speech combining contradictory terms", example: "He quipped that 'business ethics' was the perfect oxymoron.", zh: "矛盾修辭" },
    { front: "non sequitur", pos: "n.", def: "conclusion that does not follow from the premises", example: "His reply was such a non sequitur that the panel fell silent.", zh: "不合邏輯的推論" },
    { front: "anomaly", pos: "n.", def: "something deviating from what is normal", example: "Auditors flagged several anomalies in the quarterly accounts.", zh: "異常；反常現象" },
    { front: "outlier", pos: "n.", def: "person or thing differing markedly from the group", example: "The study discarded two outliers that skewed the results.", zh: "離群值；異數" },
    { front: "precursor", pos: "n.", def: "thing that comes before and signals another", example: "The riots were a precursor to the revolution that followed.", zh: "先驅；前兆" },
    { front: "portent", pos: "n.", def: "sign or warning of a momentous event", example: "Falling bond yields were read as a portent of recession.", zh: "凶兆；預兆" },
    { front: "premonition", pos: "n.", def: "strong feeling that something is about to happen", example: "She had a premonition that the deal would collapse.", zh: "預感" },
    { front: "hindsight", pos: "n.", def: "understanding of an event only after it has happened", example: "With hindsight, the warning signs were painfully obvious.", zh: "事後之明；後見之明" },
    { front: "posterity", pos: "n.", def: "all future generations of people", example: "The manuscripts were digitised to preserve them for posterity.", zh: "後世；子孫" },
    { front: "peremptory", pos: "adj.", def: "insisting on immediate obedience; brusquely imperious", example: "Her peremptory tone brooked no argument from the junior staff.", zh: "專橫的；不容反駁的" },
    { front: "slapdash", pos: "adj.", def: "done hastily and carelessly", example: "The report was so slapdash that it had to be entirely rewritten.", zh: "草率的；馬虎的" },
    { front: "anaemic", pos: "adj.", def: "lacking vigour or vitality; feeble", example: "The recovery remains anaemic despite record-low interest rates.", zh: "貧血的；疲弱無力的" },
    { front: "laudatory", pos: "adj.", def: "expressing praise", example: "The biography is laudatory to the point of hagiography.", zh: "讚揚的" },
    { front: "derisive", pos: "adj.", def: "expressing contempt or ridicule", example: "His proposal was greeted with derisive laughter from the backbenches.", zh: "嘲弄的；譏諷的" },
    { front: "dismissive", pos: "adj.", def: "showing that something is unworthy of consideration", example: "The panel was witheringly dismissive of the study's methodology.", zh: "不屑一顧的" },
    { front: "equivocal", pos: "adj.", def: "ambiguous; open to more than one interpretation", example: "The minister gave an equivocal answer that satisfied nobody.", zh: "模稜兩可的" },
    { front: "unrelenting", pos: "adj.", def: "not yielding in severity or determination", example: "The team faced unrelenting pressure to deliver results.", zh: "不間斷的；毫不留情的" },
    { front: "irreproachable", pos: "adj.", def: "beyond criticism; faultless", example: "Her conduct throughout the ordeal was irreproachable.", zh: "無可指責的" },
    { front: "indefensible", pos: "adj.", def: "impossible to justify or excuse", example: "Paying bonuses amid mass layoffs is morally indefensible.", zh: "無法辯解的" },
    { front: "untrammelled", pos: "adj.", def: "not restricted or hampered", example: "The agency enjoys untrammelled access to citizens' financial records.", zh: "不受限制的" },
    { front: "unabated", pos: "adj.", def: "continuing at full strength without weakening", example: "The storm raged unabated through the night.", zh: "未減弱的；不衰的" },
    { front: "abortive", pos: "adj.", def: "failing to achieve the intended result", example: "After several abortive attempts, the launch was postponed indefinitely.", zh: "失敗的；夭折的" },
    { front: "avowed", pos: "adj.", def: "openly declared or admitted", example: "He is an avowed sceptic of central planning.", zh: "公開承認的" },
    { front: "acrid", pos: "adj.", def: "unpleasantly bitter or pungent; caustic", example: "Acrid smoke drifted across the picket lines.", zh: "辛辣的；刺鼻的" },
    { front: "voracious", pos: "adj.", def: "having an insatiable appetite for something", example: "A voracious reader, she devoured the entire archive in weeks.", zh: "貪婪的；如飢似渴的" },
    { front: "beleaguered", pos: "adj.", def: "under severe pressure or criticism; besieged", example: "The beleaguered chief executive faced calls to resign.", zh: "四面楚歌的；飽受困擾的" },
    { front: "axiomatic", pos: "adj.", def: "self-evident; unquestionably true", example: "It is axiomatic that markets abhor uncertainty.", zh: "不言自明的" },
    { front: "puritanical", pos: "adj.", def: "strictly moral in a censorious way", example: "The board took a puritanical stance on expense claims.", zh: "極端拘謹的；清教徒式的" },
    { front: "pragmatic", pos: "adj.", def: "dealing with things practically rather than ideologically", example: "She favours a pragmatic approach over doctrinaire purity.", zh: "務實的" },
    { front: "viable", pos: "adj.", def: "capable of working successfully; feasible", example: "Without subsidies, the scheme is simply not commercially viable.", zh: "可行的" },
    { front: "far-fetched", pos: "adj.", def: "unlikely and difficult to believe", example: "The plot twist struck reviewers as hopelessly far-fetched.", zh: "牽強的；難以置信的" },
    { front: "outmoded", pos: "adj.", def: "old-fashioned and no longer useful", example: "The curriculum clings to outmoded notions of rote learning.", zh: "過時的" },
    { front: "antiquated", pos: "adj.", def: "old-fashioned or outdated", example: "The court system still relies on antiquated paper records.", zh: "陳舊的；老式的" },
    { front: "cosmopolitan", pos: "adj.", def: "familiar with many cultures; internationally diverse", example: "The port city has always had a cosmopolitan character.", zh: "國際化的；四海一家的" },
    { front: "provincial", pos: "adj.", def: "narrow-minded; unsophisticated; of the provinces", example: "Critics dismissed the festival as hopelessly provincial.", zh: "狹隘的；地方的" },
    { front: "jingoistic", pos: "adj.", def: "aggressively and belligerently patriotic", example: "The tabloids struck an increasingly jingoistic tone before the summit.", zh: "沙文主義的；好戰愛國的" },
    { front: "partisan", pos: "adj.", def: "strongly biased towards a party or cause", example: "The hearing degenerated into partisan point-scoring.", zh: "黨派的；偏袒的" },
    { front: "impartial", pos: "adj.", def: "treating all sides equally; unbiased", example: "Jurors must remain impartial despite saturation media coverage.", zh: "公正的；不偏不倚的" },
    { front: "skewed", pos: "adj.", def: "distorted or biased in a misleading way", example: "Self-selected samples produce hopelessly skewed data.", zh: "偏斜的；失真的" },
    { front: "lopsided", pos: "adj.", def: "uneven or unbalanced", example: "The treaty struck many as a lopsided bargain favouring the stronger party.", zh: "不平衡的；一面倒的" },
    { front: "disproportionate", pos: "adj.", def: "too large or small in comparison with something", example: "The sanctions had a disproportionate impact on ordinary citizens.", zh: "不成比例的" },
    { front: "trifling", pos: "adj.", def: "unimportant or trivial in amount", example: "The fine was trifling compared with the profits involved.", zh: "微不足道的" },
    { front: "profuse", pos: "adj.", def: "given or occurring in large amounts; abundant", example: "He offered profuse apologies for the scheduling debacle.", zh: "大量的；再三的" },
    { front: "impoverished", pos: "adj.", def: "made poor; deprived of quality or strength", example: "Remittances sustain thousands of impoverished rural households.", zh: "赤貧的；貧困的" },
    { front: "affluent", pos: "adj.", def: "having a great deal of money; wealthy", example: "The clinic serves affluent suburbs while inner-city provision withers.", zh: "富裕的" },
    { front: "well-heeled", pos: "adj.", def: "wealthy; having plenty of money", example: "The auction attracted well-heeled collectors from three continents.", zh: "富有的；闊綽的" },
    { front: "extortionate", pos: "adj.", def: "outrageously expensive", example: "Commuters complain of extortionate fares for unreliable services.", zh: "（價格）敲竹槓的；過高的" },
    { front: "nominal", pos: "adj.", def: "existing in name only; very small in amount", example: "Members pay a nominal fee that barely covers postage.", zh: "名義上的；象徵性的" },
    { front: "cosmetic", pos: "adj.", def: "superficial; improving appearance without substance", example: "The reshuffle amounted to cosmetic change rather than genuine reform.", zh: "表面的；裝點門面的" },
    { front: "shoddy", pos: "adj.", def: "badly made or done; of poor quality", example: "The inquiry blamed shoddy workmanship for the collapse.", zh: "劣質的；粗製濫造的" },
    { front: "substandard", pos: "adj.", def: "below the usual or required standard", example: "Inspectors condemned the substandard housing provided to seasonal workers.", zh: "不合標準的" },
    { front: "middling", pos: "adj.", def: "moderate in quality; mediocre", example: "The film opened to middling reviews and modest box-office returns.", zh: "中等的；平庸的" },
    { front: "unparalleled", pos: "adj.", def: "having no equal; exceptional", example: "The pandemic caused disruption on an unparalleled scale.", zh: "無與倫比的；空前的" },
    { front: "maladroit", pos: "adj.", def: "clumsy or inept, especially in handling situations", example: "The minister's maladroit handling of the crisis deepened public anger.", zh: "笨拙的；不圓滑的" },
    { front: "bungling", pos: "adj.", def: "characterised by clumsy incompetence", example: "The bungling response turned a mishap into a full-blown scandal.", zh: "笨手笨腳的；搞砸的" },
    { front: "ill-conceived", pos: "adj.", def: "badly planned from the outset", example: "The ill-conceived merger unravelled within eighteen months.", zh: "構想欠佳的" },
    { front: "misguided", pos: "adj.", def: "based on faulty judgement or reasoning", example: "The boycott, however well-intentioned, was fundamentally misguided.", zh: "誤入歧途的；失策的" },
    { front: "utopian", pos: "adj.", def: "idealistic but impractically perfect", example: "Critics dismissed universal basic income as a utopian fantasy.", zh: "烏托邦式的；不切實際的" },
    { front: "dystopian", pos: "adj.", def: "relating to an imagined oppressive, degraded society", example: "The surveillance proposals have a distinctly dystopian flavour.", zh: "反烏托邦的" },
    { front: "prophetic", pos: "adj.", def: "accurately predicting the future", example: "Her warnings about the housing bubble proved eerily prophetic.", zh: "預言性的；先知般的" },
    { front: "opportune", pos: "adj.", def: "occurring at an especially convenient time", example: "The endorsement came at a most opportune moment for the campaign.", zh: "適時的；恰好的" },
    { front: "imminent", pos: "adj.", def: "about to happen very soon", example: "Officials warned that the dam's collapse was imminent.", zh: "迫在眉睫的" },
    { front: "erstwhile", pos: "adj.", def: "former; previous", example: "His erstwhile allies now lead the campaign against him.", zh: "昔日的；以前的" },
    { front: "self-styled", pos: "adj.", def: "claiming a title without justification", example: "The self-styled prophet amassed a fortune from his followers.", zh: "自封的；自稱的" },
    { front: "unsubstantiated", pos: "adj.", def: "not supported by evidence", example: "The article repeated unsubstantiated rumours as established fact.", zh: "未經證實的" },
    { front: "bogus", pos: "adj.", def: "not genuine; counterfeit or fake", example: "Thousands were duped by bogus investment schemes.", zh: "假冒的；偽造的" },
    { front: "underhand", pos: "adj.", def: "acting in a secret or dishonest way", example: "The takeover was accomplished through distinctly underhand tactics.", zh: "偷偷摸摸的；卑鄙的" },
    { front: "unscrupulous", pos: "adj.", def: "having no moral principles; unprincipled", example: "Unscrupulous landlords prey on tenants unaware of their rights.", zh: "無恥的；不擇手段的" },
    { front: "groundbreaking", pos: "adj.", def: "innovative; pioneering new methods or ideas", example: "Her groundbreaking research transformed the study of epidemics.", zh: "開創性的" },
    { front: "consequential", pos: "adj.", def: "important; having significant results", example: "It may prove the most consequential ruling of the decade.", zh: "影響重大的" },
    { front: "notwithstanding", pos: "adv.", def: "in spite of this; nevertheless", example: "The objections, notwithstanding, the committee approved the plan.", zh: "儘管如此" },
    { front: "hitherto", pos: "adv.", def: "until now or until the point in question", example: "The archive contains hitherto unpublished letters from the poet.", zh: "迄今；到目前為止" },
    { front: "henceforth", pos: "adv.", def: "from this time onwards", example: "Henceforth, all submissions must be filed electronically.", zh: "從今以後" },
    { front: "purportedly", pos: "adv.", def: "as claimed, though not necessarily truly", example: "The footage purportedly shows the minister accepting the envelope.", zh: "據稱；據宣稱" },
    { front: "paradoxically", pos: "adv.", def: "in a seemingly contradictory way", example: "Paradoxically, the ban only increased the book's popularity.", zh: "矛盾的是" },
    { front: "intermittently", pos: "adv.", def: "at irregular intervals; not continuously", example: "Power was restored, though supplies functioned only intermittently.", zh: "斷斷續續地" },
    { front: "incrementally", pos: "adv.", def: "gradually, in small successive stages", example: "Reforms were introduced incrementally to avoid alarming the markets.", zh: "逐步地" },
    { front: "exponentially", pos: "adv.", def: "at an increasingly rapid rate", example: "Demand for translation services has grown exponentially.", zh: "呈指數地；急遽地" },
    { front: "wilfully", pos: "adv.", def: "deliberately; with stubborn intention", example: "The firm wilfully ignored repeated safety warnings.", zh: "故意地；任性地" },
    { front: "manifestly", pos: "adv.", def: "clearly and obviously", example: "The tribunal found the process manifestly unfair.", zh: "顯然地" },
    { front: "summarily", pos: "adv.", def: "immediately and without due process", example: "Striking workers were summarily dismissed without a hearing.", zh: "立即地；未經正當程序地" },
    { front: "unilaterally", pos: "adv.", def: "done by one side without agreement from others", example: "The company unilaterally rewrote the terms of employment.", zh: "單方面地" },
    { front: "demonstrably", pos: "adv.", def: "in a way that can be clearly shown", example: "The claims in the advertisement were demonstrably false.", zh: "可證明地；明顯地" },
    { front: "conversely", pos: "adv.", def: "introducing a statement that reverses the previous one", example: "Exports rose sharply; conversely, domestic consumption stagnated.", zh: "相反地" },
    { front: "bristle at", pos: "phrasal v.", def: "react with visible anger or indignation", example: "She bristled at the suggestion that her data were fabricated.", zh: "對…勃然變色；動怒" },
    { front: "put down to", pos: "phrasal v.", def: "attribute something to a particular cause", example: "Analysts put the slump down to weakening consumer confidence.", zh: "把…歸因於" },
    { front: "set forth", pos: "phrasal v.", def: "state or present formally in writing or speech", example: "The white paper sets forth the government's long-term strategy.", zh: "闡述；提出" },
    { front: "give way to", pos: "phrasal v.", def: "be replaced by; yield to", example: "Initial euphoria soon gave way to sober reassessment.", zh: "讓位給；被…取代" },
    { front: "bow to", pos: "phrasal v.", def: "yield reluctantly to pressure or demands", example: "The board finally bowed to shareholder pressure and resigned.", zh: "屈服於" },
    { front: "answer to", pos: "phrasal v.", def: "be accountable to a person or authority", example: "The new agency answers directly to the prime minister.", zh: "向…負責" },
    { front: "attend to", pos: "phrasal v.", def: "deal with; give practical attention to", example: "Urgent structural faults must be attended to before reopening.", zh: "處理；照料" },
    { front: "amount to", pos: "phrasal v.", def: "be equivalent to; add up to", example: "The minister's statement amounts to a tacit admission of failure.", zh: "等同於；總計達" },
    { front: "border on", pos: "phrasal v.", def: "come close to an extreme condition", example: "His devotion to the project borders on obsession.", zh: "近乎；瀕於" },
    { front: "allow for", pos: "phrasal v.", def: "take into consideration when planning", example: "The timetable allows for inevitable delays at customs.", zh: "將…納入考量；預留" },
    { front: "bargain away", pos: "phrasal v.", def: "give up something valuable in exchange for less", example: "Unions accused the negotiators of bargaining away hard-won rights.", zh: "（廉價）出讓；犧牲換取" },
    { front: "call out", pos: "phrasal v.", def: "publicly criticise or challenge someone", example: "The presenter was called out for repeating the debunked statistic.", zh: "公開點名批評" },
    { front: "carry off", pos: "phrasal v.", def: "succeed in doing something difficult", example: "Few actors could carry off such a demanding dual role.", zh: "成功做到；勝任" },
    { front: "cordon off", pos: "phrasal v.", def: "close an area with a police or military barrier", example: "Officers cordoned off the square within minutes of the blast.", zh: "封鎖（區域）" },
    { front: "crowd out", pos: "phrasal v.", def: "displace by taking available space or resources", example: "Cheap imports have crowded out local manufacturers.", zh: "排擠掉" },
    { front: "price out", pos: "phrasal v.", def: "force out of a market by high costs", example: "Young families are being priced out of the capital.", zh: "因價格過高而被迫退出" },
    { front: "drum into", pos: "phrasal v.", def: "teach through constant repetition", example: "Fire drills were drummed into every new recruit.", zh: "反覆灌輸" },
    { front: "fall away", pos: "phrasal v.", def: "gradually decrease or disappear", example: "Support for the coalition fell away sharply after the scandal.", zh: "逐漸減少；消退" },
    { front: "filter through", pos: "phrasal v.", def: "become known gradually", example: "News of the ceasefire slowly filtered through to the besieged town.", zh: "（消息）逐漸傳開" },
    { front: "gun for", pos: "phrasal v.", def: "pursue aggressively; try to attack or defeat", example: "Rival executives have been gunning for the chairman all year.", zh: "伺機攻擊；緊盯目標" },
    { front: "hive off", pos: "phrasal v.", def: "separate part of a business into a new entity", example: "The conglomerate hived off its loss-making media division.", zh: "分拆（業務）" },
    { front: "hold down", pos: "phrasal v.", def: "manage to keep a job; keep at a low level", example: "She held down two jobs while completing her doctorate.", zh: "保住（工作）；壓低" },
    { front: "lock in", pos: "phrasal v.", def: "commit irreversibly to an arrangement or rate", example: "Borrowers rushed to lock in the historically low rates.", zh: "鎖定；綁定" },
    { front: "mount up", pos: "phrasal v.", def: "gradually increase in amount", example: "Legal fees mounted up alarmingly as the case dragged on.", zh: "逐漸累積" },
    { front: "nod through", pos: "phrasal v.", def: "approve without proper discussion", example: "The amendment was nodded through a near-empty chamber.", zh: "草率通過；點頭放行" },
    { front: "parcel out", pos: "phrasal v.", def: "divide and distribute in portions", example: "Reconstruction contracts were parcelled out among party donors.", zh: "分配；瓜分" },
    { front: "pass up", pos: "phrasal v.", def: "fail to take advantage of an opportunity", example: "It was an offer too lucrative to pass up.", zh: "放棄（機會）" },
    { front: "phase in", pos: "phrasal v.", def: "introduce gradually in stages", example: "The emissions standards will be phased in over five years.", zh: "逐步引進" },
    { front: "play off against", pos: "phrasal v.", def: "set parties in opposition for one's own advantage", example: "He shrewdly played the two bidders off against each other.", zh: "挑撥雙方以漁利" },
    { front: "plough back", pos: "phrasal v.", def: "reinvest profits into a business", example: "Every penny of profit is ploughed back into research.", zh: "（利潤）再投資" },
    { front: "preside over", pos: "phrasal v.", def: "be in charge during a period or event", example: "She presided over the bank's most profitable decade.", zh: "主持；掌管（期間）" },
    { front: "puzzle out", pos: "phrasal v.", def: "solve through careful thought", example: "Cryptographers spent months puzzling out the cipher.", zh: "苦思解出" },
    { front: "round off", pos: "phrasal v.", def: "complete something in a satisfying way", example: "A late goal rounded off an emphatic victory.", zh: "圓滿結束" },
    { front: "rule out", pos: "phrasal v.", def: "exclude as a possibility", example: "Detectives have not ruled out foul play.", zh: "排除（可能性）" },
    { front: "run up", pos: "phrasal v.", def: "accumulate debts or costs quickly", example: "The club ran up debts of forty million pounds.", zh: "累積（債務）" },
    { front: "salt away", pos: "phrasal v.", def: "save money secretly for the future", example: "He had salted away a fortune in offshore accounts.", zh: "私下積存（錢）" },
    { front: "scrape through", pos: "phrasal v.", def: "succeed by a very narrow margin", example: "The bill scraped through by a single vote.", zh: "勉強通過" },
    { front: "screen out", pos: "phrasal v.", def: "exclude through a selection process", example: "The algorithm screens out applications lacking key qualifications.", zh: "篩除" },
    { front: "sell off", pos: "phrasal v.", def: "dispose of assets, often cheaply", example: "The council sold off playing fields to plug budget gaps.", zh: "出售；變賣" },
    { front: "set back", pos: "phrasal v.", def: "delay progress; cost someone money", example: "The fire set the restoration project back by two years.", zh: "使延誤；花費" },
    { front: "shake off", pos: "phrasal v.", def: "free oneself from something unwanted", example: "The industry has struggled to shake off its polluter image.", zh: "擺脫" },
    { front: "shout down", pos: "phrasal v.", def: "silence a speaker by shouting", example: "The visiting lecturer was shouted down by protesters.", zh: "以叫喊聲壓過（使無法發言）" },
    { front: "sign off on", pos: "phrasal v.", def: "give official approval to", example: "The auditors refused to sign off on the accounts.", zh: "簽核；批准" },
    { front: "siphon off", pos: "phrasal v.", def: "divert money or resources dishonestly", example: "Millions in aid were siphoned off by intermediaries.", zh: "抽走；挪用" },
    { front: "smoke out", pos: "phrasal v.", def: "force into the open from hiding", example: "The sting operation was designed to smoke out the informant.", zh: "逼出；使現形" },
    { front: "spin off", pos: "phrasal v.", def: "create a by-product or separate company from something", example: "The research programme spun off several profitable start-ups.", zh: "衍生出；分拆成立" },
    { front: "spirit away", pos: "phrasal v.", def: "remove quickly, secretly, and mysteriously", example: "The deposed president was spirited away to a foreign embassy.", zh: "神不知鬼不覺地帶走" },
    { front: "splash out", pos: "phrasal v.", def: "spend money freely on something", example: "The club splashed out eighty million on a single striker.", zh: "揮霍；大手筆花錢" },
    { front: "stack up", pos: "phrasal v.", def: "compare with; appear plausible under scrutiny", example: "The minister's figures simply do not stack up.", zh: "比得上；站得住腳" },
    { front: "stand down", pos: "phrasal v.", def: "resign from a position; withdraw", example: "The chairman announced he would stand down at the annual meeting.", zh: "辭職；退出" },
    { front: "string along", pos: "phrasal v.", def: "deceive someone over time with false promises", example: "Investors realised they had been strung along for years.", zh: "愚弄；用空話拖住" },
    { front: "strip away", pos: "phrasal v.", def: "remove layers to reveal the essence", example: "Strip away the jargon and the proposal is remarkably thin.", zh: "剝除；去除" },
    { front: "swear off", pos: "phrasal v.", def: "promise to give up something", example: "After the debacle, he swore off political punditry entirely.", zh: "發誓戒除" },
    { front: "talk round", pos: "phrasal v.", def: "persuade someone to change their mind", example: "It took hours to talk the sceptical trustees round.", zh: "說服（改變立場）" },
    { front: "thrash out", pos: "phrasal v.", def: "resolve through vigorous discussion", example: "Delegates thrashed out a compromise in an all-night session.", zh: "反覆討論以解決" },
    { front: "tip off", pos: "phrasal v.", def: "warn or inform secretly, especially of wrongdoing", example: "A journalist was tipped off about the impending raid.", zh: "向…通風報信" },
    { front: "touch off", pos: "phrasal v.", def: "cause something to begin suddenly; trigger", example: "The verdict touched off protests in a dozen cities.", zh: "引發；觸發" },
    { front: "trade on", pos: "phrasal v.", def: "exploit something for personal advantage", example: "He shamelessly trades on his family's famous name.", zh: "利用（名聲等）" },
    { front: "want for", pos: "phrasal v.", def: "lack something necessary", example: "Whatever its faults, the school wants for nothing in facilities.", zh: "缺乏" },
    { front: "ward off", pos: "phrasal v.", def: "prevent something harmful from affecting one", example: "The bank raised rates to ward off a run on the currency.", zh: "抵擋；避開" },
    { front: "water down", pos: "phrasal v.", def: "make weaker or less forceful", example: "Lobbyists succeeded in watering down the safety provisions.", zh: "沖淡；弱化" },
    { front: "wear down", pos: "phrasal v.", def: "weaken gradually through persistent pressure", example: "Months of attritional negotiation wore down their resistance.", zh: "逐漸消磨；使疲憊屈服" },
    { front: "win out", pos: "phrasal v.", def: "prevail in the end after difficulty", example: "Pragmatism eventually won out over ideology.", zh: "最終獲勝" },
    { front: "write off", pos: "phrasal v.", def: "dismiss as worthless; cancel a debt", example: "Creditors agreed to write off half the country's debt.", zh: "勾銷；認定無價值" },
    { front: "buy off", pos: "phrasal v.", def: "pay someone to stop causing trouble", example: "The company tried to buy off the protesting villagers.", zh: "收買" },
    { front: "hold all the cards", pos: "idiom", def: "be in the strongest negotiating position", example: "With three rival bidders, the sellers hold all the cards.", zh: "掌握全局；佔盡優勢" },
    { front: "get one's ducks in a row", pos: "idiom", def: "organise everything thoroughly before acting", example: "Get your ducks in a row before approaching the investors.", zh: "把事情安排妥當" },
    { front: "throw someone under the bus", pos: "idiom", def: "sacrifice someone else to protect oneself", example: "The CEO threw his deputy under the bus at the hearing.", zh: "犧牲他人以自保" },
    { front: "the ball is in your court", pos: "idiom", def: "it is your turn to act or respond", example: "We have made our final offer; the ball is in their court.", zh: "輪到你採取行動" },
    { front: "cut one's teeth on", pos: "idiom", def: "gain early experience from a particular activity", example: "She cut her teeth on local radio before joining the network.", zh: "初試身手；累積最初經驗" },
    { front: "run rings around", pos: "idiom", def: "outclass or outmanoeuvre someone completely", example: "The young barrister ran rings around the prosecution's witnesses.", zh: "遠勝過；把…耍得團團轉" },
    { front: "sell like hot cakes", pos: "idiom", def: "be bought quickly and in large numbers", example: "The commemorative editions sold like hot cakes.", zh: "熱賣；搶購一空" },
    { front: "keep one's powder dry", pos: "idiom", def: "stay ready and hold back resources until needed", example: "The board is keeping its powder dry until the market settles.", zh: "按兵不動；保留實力" },
    { front: "show one's true colours", pos: "idiom", def: "reveal one's real character or intentions", example: "Once in office, the reformer showed his true colours.", zh: "露出真面目" },
    { front: "throw one's hat into the ring", pos: "idiom", def: "announce one's candidacy or intention to compete", example: "Three senators have already thrown their hats into the ring.", zh: "宣布參選；投入競爭" },
    { front: "paint oneself into a corner", pos: "idiom", def: "put oneself in a position with no escape", example: "By ruling out tax rises, the chancellor painted himself into a corner.", zh: "把自己逼入絕境" },
    { front: "put all one's eggs in one basket", pos: "idiom", def: "risk everything on a single venture", example: "Diversify; never put all your eggs in one basket.", zh: "孤注一擲" },
    { front: "the jury is still out", pos: "idiom", def: "no decision or consensus has been reached yet", example: "The jury is still out on whether the reforms improved outcomes.", zh: "尚無定論" },
    { front: "bite the hand that feeds you", pos: "idiom", def: "harm someone who supports you", example: "Criticising his own sponsors was biting the hand that feeds him.", zh: "恩將仇報" },
    { front: "the pot calling the kettle black", pos: "idiom", def: "criticising a fault one has oneself", example: "His lecture on punctuality was the pot calling the kettle black.", zh: "五十步笑百步" },
    { front: "a wolf in sheep's clothing", pos: "idiom", def: "person hiding hostile intent behind harmless appearance", example: "The friendly consultant proved a wolf in sheep's clothing.", zh: "披著羊皮的狼" },
    { front: "throw the baby out with the bathwater", pos: "idiom", def: "discard the valuable along with the worthless", example: "Scrapping the whole system would throw the baby out with the bathwater.", zh: "因噎廢食" },
    { front: "reinvent the wheel", pos: "idiom", def: "waste effort recreating something that already exists", example: "Use the existing framework; there is no need to reinvent the wheel.", zh: "白費工夫重做現成之事" },
    { front: "square the circle", pos: "idiom", def: "attempt something impossible, especially reconciling opposites", example: "Balancing growth with deep emissions cuts means squaring the circle.", zh: "做不可能之事" },
    { front: "gild the lily", pos: "idiom", def: "spoil something by unnecessary embellishment", example: "Adding another chorus would simply gild the lily.", zh: "畫蛇添足" },
    { front: "grasp the nettle", pos: "idiom", def: "tackle a difficult problem boldly", example: "Ministers must grasp the nettle of pension reform.", zh: "當機立斷處理難題" },
    { front: "take the flak", pos: "idiom", def: "receive strong criticism on behalf of others", example: "The press officer took the flak for the botched announcement.", zh: "承受砲火；代人受過" },
    { front: "cut no ice with", pos: "idiom", def: "fail to impress or persuade someone", example: "Celebrity endorsements cut no ice with seasoned voters.", zh: "對…毫無作用" },
    { front: "strike a chord", pos: "idiom", def: "evoke sympathy or resonate emotionally", example: "Her account of rural poverty struck a chord with readers.", zh: "引起共鳴" },
    { front: "strike while the iron is hot", pos: "idiom", def: "act decisively while conditions are favourable", example: "With public opinion onside, the reformers struck while the iron was hot.", zh: "打鐵趁熱" },
    { front: "set the cat among the pigeons", pos: "idiom", def: "provoke controversy or alarm deliberately", example: "His resignation letter set the cat among the pigeons.", zh: "引起軒然大波" },
    { front: "upset the applecart", pos: "idiom", def: "spoil a plan or disturb the status quo", example: "The surprise ruling upset the applecart for both parties.", zh: "打亂計畫" },
    { front: "take a leaf out of someone's book", pos: "idiom", def: "imitate someone's successful behaviour", example: "Other councils should take a leaf out of Bristol's book.", zh: "效法某人" },
    { front: "give someone the cold shoulder", pos: "idiom", def: "deliberately ignore or treat unfriendlily", example: "Former colleagues gave the whistle-blower the cold shoulder.", zh: "冷落某人" },
    { front: "keep someone at arm's length", pos: "idiom", def: "avoid closeness or intimacy with someone", example: "The party leadership kept its radical fringe at arm's length.", zh: "保持距離" },
    { front: "wash one's hands of", pos: "idiom", def: "refuse further responsibility for", example: "The distributor washed its hands of the defective batch.", zh: "撒手不管" },
    { front: "pull the plug on", pos: "idiom", def: "end an activity by withdrawing support", example: "The network pulled the plug on the series after one season.", zh: "終止；撤資" },
    { front: "pull the rug from under", pos: "idiom", def: "suddenly withdraw essential support from someone", example: "The funding cut pulled the rug from under the research team.", zh: "抽走支持；拆台" },
    { front: "sweep under the carpet", pos: "idiom", def: "conceal a problem hoping it will be forgotten", example: "Complaints of harassment were swept under the carpet for years.", zh: "掩蓋（問題）" },
    { front: "talk at cross purposes", pos: "idiom", def: "misunderstand due to pursuing different aims", example: "Negotiators spent the morning talking at cross purposes.", zh: "雞同鴨講；各說各話" },
    { front: "go round in circles", pos: "idiom", def: "make no progress despite effort", example: "The debate went round in circles for three fruitless hours.", zh: "原地打轉；毫無進展" },
    { front: "on the cards", pos: "idiom", def: "likely to happen", example: "A snap election is very much on the cards.", zh: "很有可能發生" },
    { front: "off the record", pos: "idiom", def: "not for publication or attribution", example: "Speaking off the record, the official confirmed the rift.", zh: "私下透露；不得引述" },
    { front: "in black and white", pos: "idiom", def: "in writing; in absolute terms", example: "The guarantee is there in black and white, in the contract.", zh: "白紙黑字" },
    { front: "read the riot act", pos: "idiom", def: "reprimand severely and warn of consequences", example: "The manager read the squad the riot act after the defeat.", zh: "嚴厲訓斥" },
    { front: "lay down the law", pos: "idiom", def: "give orders dogmatically and forcefully", example: "The new headmistress laid down the law on uniform standards.", zh: "發號施令；立下規矩" },
    { front: "rule with an iron fist", pos: "idiom", def: "govern in a harshly authoritarian manner", example: "The general ruled the province with an iron fist.", zh: "鐵腕統治" },
    { front: "turn the corner", pos: "idiom", def: "pass the worst point and begin improving", example: "After two grim quarters, the economy appears to have turned the corner.", zh: "度過難關；好轉" },
    { front: "come rain or shine", pos: "idiom", def: "whatever happens; in any circumstances", example: "Come rain or shine, the market opens at dawn.", zh: "風雨無阻" },
    { front: "against the clock", pos: "idiom", def: "under time pressure to finish something", example: "Engineers worked against the clock to restore the grid.", zh: "分秒必爭" },
    { front: "behind the times", pos: "idiom", def: "old-fashioned; not aware of current developments", example: "Their paper-based system is hopelessly behind the times.", zh: "落伍；跟不上時代" },
    { front: "ahead of the curve", pos: "idiom", def: "more advanced than others; anticipating trends", example: "Early investment in renewables put the firm ahead of the curve.", zh: "領先趨勢" },
    { front: "on the back foot", pos: "idiom", def: "in a defensive, disadvantaged position", example: "The leaked audit put the ministry firmly on the back foot.", zh: "處於守勢" },
    { front: "gain the upper hand", pos: "idiom", def: "obtain a position of advantage or control", example: "Government forces slowly gained the upper hand in the region.", zh: "佔上風" },
    { front: "hold the fort", pos: "idiom", def: "take temporary charge in someone's absence", example: "Her deputy held the fort while she attended the summit.", zh: "暫代職務；留守" },
    { front: "pass with flying colours", pos: "idiom", def: "succeed easily and impressively", example: "The prototype passed every stress test with flying colours.", zh: "高分通過；表現出色" },
    { front: "by a whisker", pos: "idiom", def: "by an extremely narrow margin", example: "The incumbent retained her seat by a whisker.", zh: "以些微之差" },
    { front: "to all intents and purposes", pos: "idiom", def: "in every practical sense; virtually", example: "The talks are, to all intents and purposes, dead.", zh: "實際上；幾乎等於" },
    { front: "in no uncertain terms", pos: "idiom", def: "clearly, forcefully, and unambiguously", example: "She rejected the insinuation in no uncertain terms.", zh: "毫不含糊地；斬釘截鐵地" },
    { front: "at the mercy of", pos: "idiom", def: "completely in the power of; unprotected against", example: "Smallholders remain at the mercy of volatile commodity prices.", zh: "任由…擺布" },
    { front: "in the wake of", pos: "idiom", def: "following as a consequence of", example: "Regulations were tightened in the wake of the banking collapse.", zh: "隨…而來；在…之後" },
    { front: "be at pains to", pos: "idiom", def: "take great care and effort to do something", example: "Officials were at pains to stress that no data had been lost.", zh: "煞費苦心地" },
    { front: "to the letter", pos: "idiom", def: "exactly, following every detail", example: "The protocol was followed to the letter, yet the trial failed.", zh: "不折不扣地；嚴格按照" },
    { front: "hang in the balance", pos: "idiom", def: "be in an uncertain, critical state", example: "With funding withdrawn, the museum's future hangs in the balance.", zh: "懸而未決；命運未卜" },
    { front: "the powers that be", pos: "idiom", def: "the unnamed people in authority", example: "The powers that be quietly shelved the recommendations.", zh: "當權者" },
    { front: "cook the books", pos: "idiom", def: "falsify financial accounts", example: "The auditors discovered the treasurer had been cooking the books.", zh: "做假帳" },
    { front: "foot the bill", pos: "idiom", def: "pay for something, especially unwillingly", example: "Taxpayers will ultimately foot the bill for the bailout.", zh: "買單；承擔費用" },
    { front: "bear fruit", pos: "idiom", def: "produce successful results", example: "Years of quiet diplomacy finally bore fruit at the summit.", zh: "開花結果；奏效" },
    { front: "break the mould", pos: "idiom", def: "do something in a completely new way", example: "Her candidacy broke the mould of establishment politics.", zh: "打破窠臼" },
    { front: "red tape", pos: "idiom", def: "excessive bureaucracy and official formality", example: "Start-ups complain that red tape strangles innovation.", zh: "官僚繁文縟節" },
    { front: "arresting image", pos: "collocation", def: "picture that strikingly captures attention", example: "The photographer's arresting images dominated the front pages.", zh: "引人注目的影像" },
    { front: "saturation coverage", pos: "collocation", def: "media reporting so extensive it excludes other news", example: "The royal wedding received saturation coverage for a week.", zh: "鋪天蓋地的報導" },
    { front: "crippling sanctions", pos: "collocation", def: "penalties that severely damage an economy", example: "Crippling sanctions have halved the country's oil revenues.", zh: "癱瘓性制裁" },
    { front: "deft touch", pos: "collocation", def: "skilful, delicate handling of something", example: "The director handles weighty themes with a remarkably deft touch.", zh: "巧妙的手法" },
    { front: "boundless energy", pos: "collocation", def: "seemingly unlimited vitality and enthusiasm", example: "Her boundless energy carried the campaign through its darkest weeks.", zh: "無窮的活力" },
    { front: "unblemished record", pos: "collocation", def: "history entirely free of faults or offences", example: "The judge cited the defendant's hitherto unblemished record.", zh: "毫無污點的紀錄" },
    { front: "airtight case", pos: "collocation", def: "legal argument with no weaknesses", example: "Prosecutors believed they had an airtight case until the witness recanted.", zh: "無懈可擊的案子" },
    { front: "ringing endorsement", pos: "collocation", def: "emphatic public expression of support", example: "The lukewarm statement was hardly a ringing endorsement.", zh: "強力背書" },
    { front: "tenuous link", pos: "collocation", def: "very weak or slight connection", example: "The article drew a tenuous link between the two incidents.", zh: "牽強薄弱的關聯" },
    { front: "veiled criticism", pos: "collocation", def: "disapproval expressed indirectly", example: "Her speech contained thinly veiled criticism of the chairman.", zh: "含沙射影的批評" },
    { front: "festering resentment", pos: "collocation", def: "bitterness that worsens over time", example: "Festering resentment over pay finally erupted into strikes.", zh: "日益加深的積怨" },
    { front: "gnawing anxiety", pos: "collocation", def: "persistent, tormenting worry", example: "A gnawing anxiety about redundancy pervaded the newsroom.", zh: "揮之不去的焦慮" },
    { front: "embattled leader", pos: "collocation", def: "leader beset by problems and criticism", example: "The embattled leader survived a third confidence vote.", zh: "四面楚歌的領導人" },
    { front: "popular mandate", pos: "collocation", def: "authority granted through electoral support", example: "The landslide gave the government a clear popular mandate for reform.", zh: "民意授權" },
    { front: "hung parliament", pos: "collocation", def: "parliament in which no party has a majority", example: "Polls point to a hung parliament and weeks of coalition talks.", zh: "無多數黨的國會；懸峙國會" },
    { front: "snap election", pos: "collocation", def: "election called suddenly and unexpectedly", example: "The premier gambled on a snap election and lost her majority.", zh: "閃電大選" },
    { front: "bruising battle", pos: "collocation", def: "conflict that is damaging to those involved", example: "The takeover was approved after a bruising battle with regulators.", zh: "兩敗俱傷的激戰" },
    { front: "crunch talks", pos: "collocation", def: "decisive negotiations at a critical moment", example: "Union leaders enter crunch talks with ministers tonight.", zh: "關鍵談判" },
    { front: "surging demand", pos: "collocation", def: "rapidly increasing desire for goods or services", example: "Surging demand for chips has outstripped global capacity.", zh: "急遽攀升的需求" },
    { front: "flagging support", pos: "collocation", def: "enthusiasm or backing that is weakening", example: "The rally was intended to revive the party's flagging support.", zh: "日漸衰退的支持" },
    { front: "waning influence", pos: "collocation", def: "gradually diminishing power to affect events", example: "The report charts the waning influence of print media.", zh: "式微的影響力" },
    { front: "fledgling democracy", pos: "collocation", def: "newly established democratic state", example: "Observers fear the coup could strangle the fledgling democracy.", zh: "新興民主國家" },
    { front: "entrenched interests", pos: "collocation", def: "established groups resistant to change", example: "Reform foundered on the opposition of entrenched interests.", zh: "根深蒂固的既得利益" },
    { front: "lavish praise", pos: "collocation", def: "extremely generous compliments", example: "Critics heaped lavish praise on the debut novel.", zh: "極高的讚譽" },
    { front: "unstinting support", pos: "collocation", def: "help given generously without limit", example: "She thanked her family for their unstinting support.", zh: "毫無保留的支持" },
    { front: "unswerving loyalty", pos: "collocation", def: "devotion that never wavers", example: "His unswerving loyalty to the party survived every purge.", zh: "堅定不移的忠誠" },
    { front: "relentless pursuit", pos: "collocation", def: "unceasing chase or striving for something", example: "Her relentless pursuit of the story took her to three continents.", zh: "不懈的追求" },
    { front: "forensic examination", pos: "collocation", def: "painstakingly detailed scrutiny", example: "The accounts were subjected to forensic examination by investigators.", zh: "鉅細靡遺的查核；鑑識檢驗" },
    { front: "damage limitation", pos: "collocation", def: "action to minimise harmful effects of an event", example: "The press conference was a transparent exercise in damage limitation.", zh: "損害控管" },
    { front: "charm offensive", pos: "collocation", def: "campaign of deliberate friendliness to win support", example: "The new envoy launched a charm offensive in regional capitals.", zh: "魅力攻勢" },
    { front: "media frenzy", pos: "collocation", def: "period of intense, excited press coverage", example: "The actor's arrest triggered an unseemly media frenzy.", zh: "媒體瘋狂追逐" },
    { front: "character assassination", pos: "collocation", def: "deliberate destruction of someone's reputation", example: "The senator dismissed the exposé as character assassination.", zh: "人格抹殺；抹黑" },
    { front: "trial by media", pos: "collocation", def: "public judgement through press coverage before legal process", example: "His lawyers complained he had endured trial by media.", zh: "媒體公審" },
    { front: "gagging order", pos: "collocation", def: "court order preventing publication of information", example: "A gagging order prevented the paper from naming the executive.", zh: "禁言令" },
    { front: "public outcry", pos: "collocation", def: "strong collective expression of anger", example: "The cull was abandoned after a public outcry.", zh: "輿論譁然" },
    { front: "fevered speculation", pos: "collocation", def: "intense, excited guessing about events", example: "His absence prompted fevered speculation about a reshuffle.", zh: "沸沸揚揚的臆測" },
    { front: "swift backlash", pos: "collocation", def: "rapid hostile reaction to something", example: "The ad campaign provoked a swift backlash online.", zh: "迅速的反彈" },
    { front: "sustained campaign", pos: "collocation", def: "prolonged, continuous organised effort", example: "The charity waged a sustained campaign against the loophole.", zh: "持續不斷的行動" },
    { front: "veneer of respectability", pos: "collocation", def: "superficial appearance of decency", example: "The foundation lent a veneer of respectability to his dealings.", zh: "體面的假象" },
    { front: "shred of evidence", pos: "collocation", def: "smallest amount of proof", example: "Not a shred of evidence supports the conspiracy theory.", zh: "一絲一毫的證據" },
    { front: "glimmer of hope", pos: "collocation", def: "faint sign that something may improve", example: "The ceasefire offers a glimmer of hope for the region.", zh: "一線希望" },
    { front: "wave of protests", pos: "collocation", def: "series of demonstrations occurring in succession", example: "The fuel hike sparked a wave of protests nationwide.", zh: "一波抗議浪潮" },
    { front: "groundswell of support", pos: "collocation", def: "rapidly growing public backing", example: "A groundswell of support forced the council to reverse the closure.", zh: "民意支持浪潮" },
    { front: "chorus of disapproval", pos: "collocation", def: "many voices expressing criticism together", example: "The proposal met a chorus of disapproval from economists.", zh: "一片撻伐之聲" },
    { front: "swingeing cuts", pos: "collocation", def: "severe reductions, especially in spending", example: "The ministry announced swingeing cuts to arts funding.", zh: "大刀闊斧的刪減" },
    { front: "biting satire", pos: "collocation", def: "sharply critical humorous mockery", example: "The columnist's biting satire spared no party.", zh: "尖銳的諷刺" },
    { front: "penetrating insight", pos: "collocation", def: "deep, perceptive understanding", example: "The memoir offers penetrating insight into court politics.", zh: "深刻的洞見" },
    { front: "first-hand account", pos: "collocation", def: "description from direct personal experience", example: "The documentary features first-hand accounts from survivors.", zh: "第一手記述" },
    { front: "candid admission", pos: "collocation", def: "frank acknowledgement of something awkward", example: "In a candid admission, the coach conceded his tactics had failed.", zh: "坦率的承認" },
    { front: "unreserved apology", pos: "collocation", def: "complete apology without qualification", example: "The broadcaster issued an unreserved apology for the error.", zh: "毫無保留的道歉" },
    { front: "stunned silence", pos: "collocation", def: "quiet caused by shock or astonishment", example: "The verdict was greeted with stunned silence in the courtroom.", zh: "錯愕的沉默" },
    { front: "uneasy truce", pos: "collocation", def: "fragile, tense suspension of conflict", example: "An uneasy truce holds between the rival factions.", zh: "脆弱的休戰" },
    { front: "fragile ceasefire", pos: "collocation", def: "cessation of fighting likely to break down", example: "Aid convoys moved in under the fragile ceasefire.", zh: "岌岌可危的停火" },
    { front: "broker a deal", pos: "collocation", def: "arrange an agreement between parties", example: "Mediators worked through the night to broker a deal.", zh: "斡旋促成協議" },
    { front: "strike a balance", pos: "collocation", def: "find a reasonable compromise between demands", example: "Regulators must strike a balance between innovation and safety.", zh: "取得平衡" },
    { front: "bridge the gap", pos: "collocation", def: "reduce the difference between two groups or things", example: "The scheme aims to bridge the gap between school and employment.", zh: "彌合差距" },
    { front: "set a precedent", pos: "collocation", def: "establish an example for future cases", example: "Lawyers warned the ruling would set a dangerous precedent.", zh: "開創先例" },
    { front: "shoulder the blame", pos: "collocation", def: "accept responsibility for a failure", example: "The captain shouldered the blame for the humiliating defeat.", zh: "扛起責任" },
    { front: "court controversy", pos: "collocation", def: "deliberately behave in ways likely to provoke argument", example: "The gallery has never been afraid to court controversy.", zh: "刻意招惹爭議" },
    { front: "spark outrage", pos: "collocation", def: "provoke intense public anger", example: "The judge's remarks sparked outrage among campaigners.", zh: "引發眾怒" },
    { front: "defuse tensions", pos: "collocation", def: "reduce hostility in a dangerous situation", example: "Back-channel talks helped defuse tensions along the border.", zh: "化解緊張" },
    { front: "stoke fears", pos: "collocation", def: "deliberately increase anxiety or alarm", example: "The pamphlet was designed to stoke fears about immigration.", zh: "煽動恐懼" },
    { front: "allay fears", pos: "collocation", def: "calm or dispel worries", example: "The briefing did little to allay fears of contamination.", zh: "消除疑慮" },
    { front: "landmark ruling", pos: "collocation", def: "court decision with far-reaching significance", example: "The landmark ruling redefined privacy rights in the digital age.", zh: "里程碑式判決" },
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
