/* CPE Prep extra vocab wave 1 */
(function () {
  var BANK = [
  /* ===== Batch 1 ===== */
  { front: "obfuscate", pos: "v.", def: "to deliberately make something unclear or hard to understand", example: "The contract's jargon seemed designed to obfuscate rather than inform.", zh: "使模糊、故意混淆" },
  { front: "recalcitrant", pos: "adj.", def: "stubbornly refusing to obey authority or discipline", example: "Even the most recalcitrant pupils warmed to her teaching.", zh: "頑抗的、不服管教的" },
  { front: "propitious", pos: "adj.", def: "giving a good chance of success; favourable", example: "With rates falling, the moment seemed propitious for expansion.", zh: "吉利的、有利的" },
  { front: "perfunctory", pos: "adj.", def: "done quickly, without real interest or care", example: "He gave the report a perfunctory glance and signed it.", zh: "敷衍的、草率的" },
  { front: "obsequious", pos: "adj.", def: "excessively eager to please or obey", example: "The waiter's obsequious manner made the meal faintly uncomfortable.", zh: "諂媚的、卑躬屈膝的" },
  { front: "capricious", pos: "adj.", def: "changing mood or behaviour suddenly and unpredictably", example: "Investors dislike nothing more than a capricious regulator.", zh: "反覆無常的" },
  { front: "laconic", pos: "adj.", def: "using very few words", example: "His laconic reply — 'Perhaps' — ended the interview.", zh: "言簡意賅的、寡言的" },
  { front: "taciturn", pos: "adj.", def: "habitually silent and reserved in speech", example: "Her taciturn father rarely offered more than a nod.", zh: "沉默寡言的" },
  { front: "garrulous", pos: "adj.", def: "excessively talkative, especially about trivial matters", example: "A garrulous seatmate turned the short flight into an ordeal.", zh: "喋喋不休的" },
  { front: "truculent", pos: "adj.", def: "aggressively defiant and quick to argue", example: "The truculent witness contradicted the barrister at every turn.", zh: "好鬥的、蠻橫的" },
  { front: "belligerent", pos: "adj.", def: "hostile and eager to fight or argue", example: "His belligerent tone alienated even his allies on the committee.", zh: "好戰的、挑釁的" },
  { front: "acquiesce", pos: "v.", def: "to accept something reluctantly without protest", example: "She acquiesced in the decision, though her silence spoke volumes.", zh: "默許、勉強同意" },
  { front: "abrogate", pos: "v.", def: "to formally cancel a law, agreement or duty", example: "Parliament voted to abrogate the outdated treaty.", zh: "廢除、撤銷" },
  { front: "abscond", pos: "v.", def: "to leave secretly, typically to escape arrest or with money", example: "The treasurer absconded with the club's entire savings.", zh: "潛逃、捲款而逃" },
  { front: "admonish", pos: "v.", def: "to warn or scold someone firmly but not harshly", example: "The judge admonished the jurors not to discuss the case.", zh: "告誡、責備" },
  { front: "aggrandise", pos: "v.", def: "to increase the power, wealth or status of someone", example: "Critics accused the mayor of using the project to aggrandise himself.", zh: "擴大權勢、抬高（自己）" },
  { front: "ameliorate", pos: "v.", def: "to make a bad situation better", example: "Small subsidies did little to ameliorate the housing shortage.", zh: "改善、緩和" },
  { front: "anathema", pos: "n.", def: "something one detests as completely unacceptable", example: "Censorship of any kind is anathema to her.", zh: "深惡痛絕之事" },
  { front: "antithesis", pos: "n.", def: "the exact opposite of something", example: "His flamboyance is the antithesis of her quiet rigour.", zh: "對立面、正相反" },
  { front: "apocryphal", pos: "adj.", def: "widely told but probably not true", example: "The apocryphal tale of the rejected manuscript still circulates.", zh: "杜撰的、真實性可疑的" },
  { front: "arcane", pos: "adj.", def: "understood by very few; mysterious and specialised", example: "Tax law is full of arcane provisions nobody remembers writing.", zh: "晦澀難懂的、少有人知的" },
  { front: "ascetic", pos: "adj.", def: "practising severe self-discipline and avoiding pleasures", example: "He kept an almost ascetic routine of work, walks and sleep.", zh: "苦行的、禁慾的" },
  { front: "assiduous", pos: "adj.", def: "showing great care, persistence and hard work", example: "Her assiduous note-taking saved the project months later.", zh: "勤勉的、孜孜不倦的" },
  { front: "audacious", pos: "adj.", def: "willing to take bold risks; daringly original", example: "The heist was audacious even by the gang's standards.", zh: "大膽的、無畏的" },
  { front: "auspicious", pos: "adj.", def: "suggesting future success; promising", example: "Record ticket sales made for an auspicious opening night.", zh: "吉兆的、前景看好的" },
  { front: "avarice", pos: "n.", def: "extreme greed for wealth", example: "The novel charts one family's descent into avarice.", zh: "貪婪" },
  { front: "banal", pos: "adj.", def: "boringly ordinary and lacking originality", example: "The film's dialogue is banal to the point of parody.", zh: "陳腐的、平庸的" },
  { front: "bellicose", pos: "adj.", def: "demonstrating aggression and willingness to fight", example: "The general's bellicose rhetoric alarmed neighbouring states.", zh: "好戰的" },
  { front: "berate", pos: "v.", def: "to scold someone angrily and at length", example: "The coach berated the defence for a full ten minutes.", zh: "痛斥、嚴厲責罵" },
  { front: "bombastic", pos: "adj.", def: "using inflated language with little meaning", example: "His bombastic speeches promised everything and delivered nothing.", zh: "誇誇其談的" },
  { front: "boon", pos: "n.", def: "something very helpful or beneficial", example: "The new bridge has been a boon to local traders.", zh: "恩惠、福音" },
  { front: "brazen", pos: "adj.", def: "bold and shameless", example: "It was a brazen lie, delivered without a flicker of embarrassment.", zh: "厚顏無恥的" },
  { front: "bucolic", pos: "adj.", def: "relating to pleasant aspects of countryside life", example: "The brochure promised a bucolic retreat far from motorways.", zh: "田園的、鄉村風味的" },
  { front: "burgeoning", pos: "adj.", def: "growing or developing rapidly", example: "The city's burgeoning tech sector is straining its housing stock.", zh: "迅速發展的" },
  { front: "cacophony", pos: "n.", def: "a harsh, unpleasant mixture of sounds", example: "A cacophony of horns greeted the stalled traffic.", zh: "刺耳的嘈雜聲" },
  { front: "cajole", pos: "v.", def: "to persuade someone by flattery or gentle coaxing", example: "She cajoled her brother into lending her the car.", zh: "哄騙、勸誘" },
  { front: "callous", pos: "adj.", def: "cruelly insensitive to others' suffering", example: "The insurer's callous refusal made headlines.", zh: "冷酷無情的" },
  { front: "candour", pos: "n.", def: "the quality of being open and honest", example: "She discussed her failures with disarming candour.", zh: "坦率、直言" },
  { front: "castigate", pos: "v.", def: "to criticise or punish someone severely", example: "The report castigates managers for ignoring repeated warnings.", zh: "嚴厲斥責" },
  { front: "caustic", pos: "adj.", def: "bitterly sarcastic in a hurtful way", example: "Her caustic wit spared no one in the newsroom.", zh: "尖酸刻薄的" },
  { front: "circuitous", pos: "adj.", def: "longer and less direct than necessary", example: "He gave a circuitous answer that avoided the question entirely.", zh: "迂迴的、繞圈子的" },
  { front: "come in for", pos: "phrasal v.", def: "to receive criticism, blame or praise", example: "The scheme has come in for fierce criticism from economists.", zh: "受到（批評、指責等）" },
  { front: "live up to", pos: "phrasal v.", def: "to be as good as what was expected or promised", example: "The sequel never quite lives up to the original.", zh: "不辜負、達到（期望）" },
  { front: "fall back on", pos: "phrasal v.", def: "to use something for support when other options fail", example: "With savings to fall back on, she could afford to resign.", zh: "退而依靠、以…為後盾" },
  { front: "do away with", pos: "phrasal v.", def: "to abolish or get rid of something", example: "The reform would do away with paper filings altogether.", zh: "廢除、去除" },
  { front: "zero in on", pos: "phrasal v.", def: "to direct all attention to one target or point", example: "The auditors zeroed in on three suspicious transfers.", zh: "集中注意於、瞄準" },
  { front: "iron out", pos: "phrasal v.", def: "to resolve small problems or disagreements", example: "The lawyers spent a week ironing out the final details.", zh: "解決（分歧、小問題）" },
  { front: "bear out", pos: "phrasal v.", def: "to confirm or support a claim with evidence", example: "The latest figures bear out her earlier predictions.", zh: "證實、支持（說法）" },
  { front: "drum up", pos: "phrasal v.", def: "to work hard to obtain support, business or interest", example: "He toured the region drumming up support for the bid.", zh: "招徠、爭取（支持、生意）" },
  { front: "fend off", pos: "phrasal v.", def: "to defend oneself against attack, questions or competition", example: "The CEO spent the briefing fending off questions about the merger.", zh: "擋開、抵擋" },
  { front: "whittle down", pos: "phrasal v.", def: "to gradually reduce something in size or number", example: "The panel whittled down two hundred entries to a shortlist of five.", zh: "逐步削減" },
  { front: "wade through", pos: "phrasal v.", def: "to deal with tedious material with effort", example: "I spent the weekend wading through six hundred pages of testimony.", zh: "費力讀完、艱難處理" },
  { front: "a storm in a teacup", pos: "idiom", def: "great fuss about a trivial matter", example: "The 'scandal' proved a storm in a teacup and was forgotten by Friday.", zh: "小題大作、茶壺裡的風暴" },
  { front: "par for the course", pos: "idiom", def: "what is normal or expected in a situation", example: "Delays of an hour are par for the course on this line.", zh: "司空見慣、意料之中" },
  { front: "go against the grain", pos: "idiom", def: "to be contrary to one's nature or usual practice", example: "Praising a rival went firmly against the grain for him.", zh: "違背本性、格格不入" },
  { front: "a red herring", pos: "idiom", def: "a misleading clue that diverts attention", example: "The missing key turned out to be a red herring.", zh: "轉移焦點的線索、障眼法" },
  { front: "the elephant in the room", pos: "idiom", def: "an obvious problem everyone avoids mentioning", example: "Nobody raised the elephant in the room: the founder's health.", zh: "眾人避而不談的明顯問題" },
  { front: "throw down the gauntlet", pos: "idiom", def: "to issue a challenge", example: "The start-up threw down the gauntlet to the industry giants.", zh: "下戰帖、公開挑戰" },
  { front: "leave no stone unturned", pos: "idiom", def: "to try every possible means to achieve something", example: "Detectives left no stone unturned in the search for the child.", zh: "千方百計、不遺餘力" },
  { front: "add insult to injury", pos: "idiom", def: "to make a bad situation even worse", example: "To add insult to injury, the refund was taxed.", zh: "雪上加霜" },
  { front: "a blessing in disguise", pos: "idiom", def: "an apparent misfortune that turns out well", example: "Losing that job was a blessing in disguise.", zh: "因禍得福" },
  { front: "keep something at bay", pos: "idiom", def: "to prevent something harmful from coming near", example: "Regular exercise helps keep anxiety at bay.", zh: "使…不能靠近、遏制" },
  { front: "sit on the fence", pos: "idiom", def: "to avoid committing to either side of an issue", example: "You can't sit on the fence on this vote.", zh: "騎牆觀望、不表態" },
  { front: "vested interest", pos: "collocation", def: "a personal stake that biases one's position", example: "Landlords have a vested interest in blocking the rent cap.", zh: "既得利益" },
  { front: "sweeping generalisation", pos: "collocation", def: "a broad statement made without regard for exceptions", example: "The article is built on sweeping generalisations about the young.", zh: "以偏概全的論斷" },
  { front: "mounting pressure", pos: "collocation", def: "steadily increasing demands or stress", example: "The minister resigned under mounting pressure from her own party.", zh: "與日俱增的壓力" },
  { front: "glaring omission", pos: "collocation", def: "an obvious and striking failure to include something", example: "The absence of any costings is the report's most glaring omission.", zh: "明顯的疏漏" },
  { front: "resounding success", pos: "collocation", def: "a very great and unmistakable success", example: "The festival's first edition was a resounding success.", zh: "巨大的成功" },
  { front: "abject failure", pos: "collocation", def: "a complete and humiliating failure", example: "The pilot scheme was an abject failure and was quietly shelved.", zh: "徹底的失敗" },
  { front: "dire consequences", pos: "collocation", def: "extremely serious negative results", example: "Ignoring the warnings could have dire consequences for the coast.", zh: "嚴重的後果" },
  { front: "meteoric rise", pos: "collocation", def: "a very rapid climb to success or fame", example: "Her meteoric rise from intern to editor took four years.", zh: "一飛沖天的崛起" },
  { front: "unmitigated disaster", pos: "collocation", def: "a total disaster without any redeeming feature", example: "The product launch was an unmitigated disaster.", zh: "徹頭徹尾的災難" },
  { front: "burning question", pos: "collocation", def: "an urgent issue everyone wants answered", example: "The burning question is who will fund the rebuild.", zh: "亟待解答的問題" },
  { front: "uphill struggle", pos: "collocation", def: "a task that is difficult from the outset", example: "Convincing rural voters proved an uphill struggle.", zh: "艱苦的奮鬥" },
  { front: "wishful thinking", pos: "collocation", def: "believing something because one wants it to be true", example: "Hopes of a quick recovery were pure wishful thinking.", zh: "一廂情願的想法" },
  /* ===== Batch 2 ===== */
  { front: "chagrin", pos: "n.", def: "annoyance or embarrassment at having failed", example: "Much to his chagrin, the typo appeared on the front page.", zh: "懊惱、羞愧" },
  { front: "chicanery", pos: "n.", def: "the use of trickery to achieve a purpose", example: "The audit exposed years of accounting chicanery.", zh: "欺詐手段、詭計" },
  { front: "circumspect", pos: "adj.", def: "cautious and unwilling to take risks", example: "Officials were circumspect about naming a suspect.", zh: "謹慎的、慎重的" },
  { front: "clandestine", pos: "adj.", def: "kept secret, often because illicit", example: "They held clandestine meetings in a disused warehouse.", zh: "祕密的、暗中進行的" },
  { front: "coalesce", pos: "v.", def: "to come together to form one whole", example: "Scattered protests coalesced into a national movement.", zh: "聯合、合併" },
  { front: "cogent", pos: "adj.", def: "clear, logical and convincing", example: "She made a cogent case for delaying the launch.", zh: "有說服力的" },
  { front: "commensurate", pos: "adj.", def: "corresponding in size or degree; proportionate", example: "Salaries here are commensurate with experience.", zh: "相稱的、成比例的" },
  { front: "complacent", pos: "adj.", def: "smugly satisfied and unaware of danger", example: "Success made the team complacent, and rivals soon overtook them.", zh: "自滿的、掉以輕心的" },
  { front: "conflate", pos: "v.", def: "to mistakenly combine two distinct things into one", example: "The article conflates immigration with asylum, which are separate issues.", zh: "混為一談" },
  { front: "congenial", pos: "adj.", def: "pleasant and suited to one's tastes", example: "She found the college a congenial place to write.", zh: "意氣相投的、宜人的" },
  { front: "conjecture", pos: "n.", def: "an opinion formed without sufficient evidence", example: "The cause of the blaze remains a matter of conjecture.", zh: "推測、臆測" },
  { front: "connive", pos: "v.", def: "to secretly cooperate in wrongdoing", example: "Officials connived with smugglers to wave the trucks through.", zh: "共謀、縱容" },
  { front: "construe", pos: "v.", def: "to interpret words or actions in a particular way", example: "Her silence was construed as consent.", zh: "解讀、詮釋為" },
  { front: "contentious", pos: "adj.", def: "likely to cause disagreement or argument", example: "Water rights remain the most contentious clause in the treaty.", zh: "有爭議的" },
  { front: "contrite", pos: "adj.", def: "feeling genuine remorse for wrongdoing", example: "He appeared suitably contrite before the disciplinary panel.", zh: "悔悟的、痛悔的" },
  { front: "conundrum", pos: "n.", def: "a confusing and difficult problem", example: "How to grow without polluting is the classic development conundrum.", zh: "難題、謎題" },
  { front: "copious", pos: "adj.", def: "abundant in quantity", example: "She took copious notes throughout the trial.", zh: "大量的、豐富的" },
  { front: "corroborate", pos: "v.", def: "to confirm a statement with supporting evidence", example: "Two witnesses corroborated his account of the crash.", zh: "證實、佐證" },
  { front: "covet", pos: "v.", def: "to strongly desire something belonging to another", example: "The award is the most coveted prize in architecture.", zh: "覬覦、渴望得到" },
  { front: "credulous", pos: "adj.", def: "too ready to believe things; gullible", example: "The scam preyed on credulous first-time investors.", zh: "輕信的" },
  { front: "cursory", pos: "adj.", def: "hasty and not thorough", example: "Even a cursory reading reveals the plan's flaws.", zh: "粗略的、草率的" },
  { front: "dearth", pos: "n.", def: "a scarcity or lack of something", example: "The region suffers a dearth of qualified engineers.", zh: "缺乏、不足" },
  { front: "debacle", pos: "n.", def: "a sudden humiliating failure or collapse", example: "The ticketing debacle forced the organisers to apologise.", zh: "潰敗、慘敗" },
  { front: "decorum", pos: "n.", def: "behaviour that is polite and socially appropriate", example: "The heckler was removed for breaching parliamentary decorum.", zh: "禮儀、得體" },
  { front: "deference", pos: "n.", def: "polite respect and submission to another's judgement", example: "Out of deference to the family, the photos were withheld.", zh: "尊重、順從" },
  { front: "deleterious", pos: "adj.", def: "causing harm or damage, often subtly", example: "Chronic noise has deleterious effects on concentration.", zh: "有害的" },
  { front: "demur", pos: "v.", def: "to raise objections or show reluctance", example: "Asked to comment on the leak, the spokesman demurred.", zh: "表示異議、婉拒" },
  { front: "denigrate", pos: "v.", def: "to unfairly criticise and belittle someone", example: "The campaign sought to denigrate her record rather than debate it.", zh: "詆毀、貶低" },
  { front: "deride", pos: "v.", def: "to mock something as ridiculous or worthless", example: "Critics derided the scheme as accounting sleight of hand.", zh: "嘲笑、譏諷" },
  { front: "derivative", pos: "adj.", def: "imitative of others' work and lacking originality", example: "Reviewers dismissed the album as pleasant but derivative.", zh: "缺乏原創性的、模仿的" },
  { front: "despondent", pos: "adj.", def: "in low spirits from loss of hope", example: "After the third rejection she grew visibly despondent.", zh: "沮喪的、灰心的" },
  { front: "desultory", pos: "adj.", def: "lacking plan, purpose or enthusiasm", example: "They made desultory conversation while waiting for the results.", zh: "散漫的、無條理的" },
  { front: "diatribe", pos: "n.", def: "a bitter verbal attack against someone or something", example: "His resignation letter was a ten-page diatribe against management.", zh: "抨擊、謾罵" },
  { front: "didactic", pos: "adj.", def: "intended to teach, often in a preachy way", example: "The novel's didactic tone smothers an otherwise fine story.", zh: "說教的" },
  { front: "diffident", pos: "adj.", def: "modest and lacking self-confidence", example: "The diffident intern turned out to be the sharpest mind in the room.", zh: "羞怯的、缺乏自信的" },
  { front: "dilapidated", pos: "adj.", def: "in a state of ruin from neglect", example: "They bought a dilapidated farmhouse and spent a decade restoring it.", zh: "破敗失修的" },
  { front: "discern", pos: "v.", def: "to perceive or recognise something not obvious", example: "It is hard to discern any strategy behind these cuts.", zh: "辨別、看出" },
  { front: "disdain", pos: "n.", def: "the feeling that something is beneath one's respect", example: "She regarded the tabloids with undisguised disdain.", zh: "輕蔑、鄙視" },
  { front: "disingenuous", pos: "adj.", def: "not sincere, pretending to know less than one does", example: "It is disingenuous to claim the risks were unknown.", zh: "虛偽的、假裝坦率的" },
  { front: "dogmatic", pos: "adj.", def: "asserting opinions as facts without allowing debate", example: "His dogmatic style left no room for dissenting views.", zh: "武斷的、教條的" },
  { front: "duplicity", pos: "n.", def: "deceitfulness; saying different things to different people", example: "The memoir lays bare the duplicity behind the negotiations.", zh: "口是心非、欺騙" },
  { front: "hark back to", pos: "phrasal v.", def: "to recall or resemble something from the past", example: "The design harks back to the ocean liners of the 1930s.", zh: "追溯、令人想起（過去）" },
  { front: "latch on to", pos: "phrasal v.", def: "to seize on an idea enthusiastically; to attach oneself to", example: "The press quickly latched on to the phrase and made it a slogan.", zh: "抓住不放、緊跟" },
  { front: "own up to", pos: "phrasal v.", def: "to admit responsibility for something wrong", example: "Nobody owned up to leaking the memo.", zh: "承認（過錯）" },
  { front: "crack down on", pos: "phrasal v.", def: "to enforce rules against something much more strictly", example: "The city is cracking down on unlicensed short-term rentals.", zh: "嚴厲取締、打擊" },
  { front: "phase out", pos: "phrasal v.", def: "to withdraw something gradually in stages", example: "The subsidy will be phased out over five years.", zh: "逐步淘汰" },
  { front: "single out", pos: "phrasal v.", def: "to choose one person or thing from a group for attention", example: "The report singles out the finance team for particular praise.", zh: "單獨挑出、特別點名" },
  { front: "stave off", pos: "phrasal v.", def: "to delay or prevent something bad temporarily", example: "An emergency loan staved off bankruptcy for another quarter.", zh: "暫時擋住、延緩" },
  { front: "tone down", pos: "phrasal v.", def: "to make something less extreme or offensive", example: "Editors asked her to tone down the article's accusations.", zh: "緩和、降低（語氣）" },
  { front: "spell out", pos: "phrasal v.", def: "to explain something clearly and in detail", example: "The contract spells out exactly who bears the risk.", zh: "詳細說明、講清楚" },
  { front: "breeze through", pos: "phrasal v.", def: "to complete something easily and confidently", example: "She breezed through the oral exam in twenty minutes.", zh: "輕鬆完成" },
  { front: "mull over", pos: "phrasal v.", def: "to think about something carefully over time", example: "He mulled over the offer for a week before declining.", zh: "反覆思考、斟酌" },
  { front: "pull out all the stops", pos: "idiom", def: "to make every possible effort", example: "The hotel pulled out all the stops for the delegation.", zh: "竭盡全力、傾力而為" },
  { front: "move the goalposts", pos: "idiom", def: "to unfairly change the rules or criteria mid-process", example: "Each time we met the target, head office moved the goalposts.", zh: "臨時改變標準、出爾反爾" },
  { front: "cut to the chase", pos: "idiom", def: "to get to the point without wasting time", example: "Let's cut to the chase: can you deliver by March?", zh: "直奔主題、開門見山" },
  { front: "take the plunge", pos: "idiom", def: "to finally do something risky after hesitation", example: "After years of dithering, they took the plunge and emigrated.", zh: "下定決心、毅然行動" },
  { front: "up in arms", pos: "idiom", def: "very angry and protesting strongly", example: "Residents are up in arms over the incinerator plan.", zh: "群情激憤、強烈抗議" },
  { front: "by the skin of one's teeth", pos: "idiom", def: "only just; by the narrowest margin", example: "He passed the resit by the skin of his teeth.", zh: "險些不成、僥倖" },
  { front: "on tenterhooks", pos: "idiom", def: "in a state of anxious suspense", example: "We were on tenterhooks until the biopsy results came back.", zh: "提心吊膽、焦急等待" },
  { front: "at a crossroads", pos: "idiom", def: "at a point where a crucial decision must be made", example: "The party stands at a crossroads between reform and retreat.", zh: "處於十字路口、面臨抉擇" },
  { front: "come to a head", pos: "idiom", def: "to reach a crisis point requiring action", example: "Tensions came to a head when the pay freeze was announced.", zh: "（矛盾）到達臨界點" },
  { front: "fall on deaf ears", pos: "idiom", def: "to be ignored despite being said", example: "Warnings about the dam fell on deaf ears for a decade.", zh: "無人理會、充耳不聞" },
  { front: "grasp at straws", pos: "idiom", def: "to try desperate, unlikely options out of hopelessness", example: "Suggesting a technicality at this stage is grasping at straws.", zh: "病急亂投醫、抓救命稻草" },
  { front: "golden opportunity", pos: "collocation", def: "an exceptionally favourable chance", example: "The vacancy is a golden opportunity to reshape the department.", zh: "絕佳機會" },
  { front: "heated debate", pos: "collocation", def: "an intense, emotional argument or discussion", example: "The zoning proposal sparked a heated debate at the council.", zh: "激烈的辯論" },
  { front: "cutting-edge technology", pos: "collocation", def: "the most advanced technology available", example: "The lab uses cutting-edge technology to map coral reefs.", zh: "尖端科技" },
  { front: "scathing criticism", pos: "collocation", def: "extremely harsh and contemptuous criticism", example: "The watchdog delivered scathing criticism of the bank's controls.", zh: "嚴厲的批評" },
  { front: "painstaking research", pos: "collocation", def: "research done with extreme care and thoroughness", example: "The biography rests on painstaking research in five archives.", zh: "縝密的研究" },
  { front: "staunch supporter", pos: "collocation", def: "a very loyal and committed supporter", example: "She remains a staunch supporter of proportional representation.", zh: "堅定的支持者" },
  { front: "blatant disregard", pos: "collocation", def: "open and shameless lack of concern", example: "The demolition showed blatant disregard for heritage rules.", zh: "公然漠視" },
  { front: "fierce competition", pos: "collocation", def: "intense rivalry between competitors", example: "Fierce competition has driven fares to record lows.", zh: "激烈的競爭" },
  { front: "lasting legacy", pos: "collocation", def: "an effect that endures long after its cause", example: "The games left a lasting legacy of public sports facilities.", zh: "深遠的影響、長久的遺產" },
  { front: "plausible explanation", pos: "collocation", def: "an explanation that seems reasonable and believable", example: "Fatigue is the only plausible explanation for the error.", zh: "合理的解釋" },
  { front: "dwindling resources", pos: "collocation", def: "resources that are steadily decreasing", example: "The clinic struggles on with dwindling resources.", zh: "日漸減少的資源" },
  { front: "rampant inflation", pos: "collocation", def: "inflation that is spreading uncontrollably", example: "Rampant inflation wiped out a decade of savings.", zh: "失控的通貨膨脹" },
  /* ===== Batch 3 ===== */
  { front: "ebullient", pos: "adj.", def: "cheerful and full of energy", example: "The coach was ebullient after the come-from-behind win.", zh: "熱情洋溢的、興高采烈的" },
  { front: "eclectic", pos: "adj.", def: "drawing from a wide, varied range of sources", example: "Her eclectic playlist ran from plainsong to punk.", zh: "兼容並蓄的、多元的" },
  { front: "efficacious", pos: "adj.", def: "effective in producing the intended result", example: "The older, cheaper drug proved just as efficacious.", zh: "有效的、奏效的" },
  { front: "effrontery", pos: "n.", def: "shameless boldness; insolence", example: "He had the effrontery to bill us for his own mistake.", zh: "厚顏、放肆" },
  { front: "elucidate", pos: "v.", def: "to make something clear by explaining it", example: "The footnotes elucidate the poem's more obscure references.", zh: "闡明、解釋" },
  { front: "emaciated", pos: "adj.", def: "abnormally thin from illness or starvation", example: "Rescuers found the stranded climbers emaciated but alive.", zh: "瘦弱憔悴的" },
  { front: "embellish", pos: "v.", def: "to make more attractive; to add invented details", example: "He tends to embellish his war stories with each retelling.", zh: "美化、加油添醋" },
  { front: "eminent", pos: "adj.", def: "famous and respected in a profession", example: "A panel of eminent jurists reviewed the conviction.", zh: "傑出的、聲譽卓著的" },
  { front: "empirical", pos: "adj.", def: "based on observation and experiment, not theory", example: "There is little empirical support for the four-day-week claims.", zh: "實證的、經驗上的" },
  { front: "emulate", pos: "v.", def: "to try to equal or surpass by imitation", example: "Many cities have tried to emulate Copenhagen's cycling culture.", zh: "效法、見賢思齊" },
  { front: "enervate", pos: "v.", def: "to drain someone of energy or vitality", example: "The humid heat enervated even the fittest runners.", zh: "使衰弱無力" },
  { front: "enigmatic", pos: "adj.", def: "mysterious and difficult to interpret", example: "She gave an enigmatic smile and changed the subject.", zh: "神祕難解的" },
  { front: "enmity", pos: "n.", def: "a state of deep-seated hostility", example: "Decades of enmity between the clans ended with a single marriage.", zh: "敵意、仇恨" },
  { front: "ennui", pos: "n.", def: "listless boredom from lack of interest", example: "A creeping ennui settled over the office by August.", zh: "倦怠、無聊" },
  { front: "epitome", pos: "n.", def: "a perfect example embodying a quality", example: "The chateau is the epitome of understated luxury.", zh: "典範、縮影" },
  { front: "equanimity", pos: "n.", def: "calmness and composure under stress", example: "She received the verdict with remarkable equanimity.", zh: "沉著、平靜" },
  { front: "equivocate", pos: "v.", def: "to use ambiguous language to avoid committing oneself", example: "Pressed on the timetable, the minister equivocated.", zh: "含糊其辭、模稜兩可" },
  { front: "erudite", pos: "adj.", def: "having or showing great learning", example: "His erudite lectures ranged effortlessly across three centuries.", zh: "博學的" },
  { front: "esoteric", pos: "adj.", def: "intended for or understood by a small expert group", example: "The debate turned on an esoteric point of maritime law.", zh: "深奧的、只有內行懂的" },
  { front: "ethereal", pos: "adj.", def: "delicate and light in an unworldly way", example: "Her ethereal soprano floated above the orchestra.", zh: "飄渺的、超凡的" },
  { front: "euphemism", pos: "n.", def: "a mild expression substituted for a harsh one", example: "'Downsizing' is a euphemism for mass redundancies.", zh: "委婉語" },
  { front: "exasperate", pos: "v.", def: "to irritate someone intensely", example: "The endless form-filling exasperated even patient applicants.", zh: "激怒、使惱火" },
  { front: "exculpate", pos: "v.", def: "to show that someone is not guilty of wrongdoing", example: "The recovered emails exculpated the accountant entirely.", zh: "開脫、證明無罪" },
  { front: "exemplary", pos: "adj.", def: "serving as an outstanding model; or serving as a warning", example: "Her conduct throughout the crisis was exemplary.", zh: "堪為模範的" },
  { front: "exhaustive", pos: "adj.", def: "covering every possible detail; complete", example: "The commission produced an exhaustive account of the failure.", zh: "詳盡無遺的" },
  { front: "exonerate", pos: "v.", def: "to officially clear someone of blame", example: "DNA evidence exonerated him after nineteen years in prison.", zh: "還以清白、免除罪責" },
  { front: "expedient", pos: "adj.", def: "convenient and practical, though possibly improper", example: "It was politically expedient to postpone the announcement.", zh: "權宜的、便利可行的" },
  { front: "expedite", pos: "v.", def: "to make a process happen more quickly", example: "A dedicated clerk was hired to expedite visa applications.", zh: "加速、加快辦理" },
  { front: "expunge", pos: "v.", def: "to remove or erase something completely", example: "The conviction was expunged from his record.", zh: "刪除、抹去" },
  { front: "extraneous", pos: "adj.", def: "irrelevant or unrelated to the subject", example: "Strip out the extraneous detail and the essay improves at once.", zh: "無關的、多餘的" },
  { front: "exuberant", pos: "adj.", def: "full of unrestrained energy and excitement", example: "An exuberant crowd carried the players off the pitch.", zh: "興高采烈的、奔放的" },
  { front: "facetious", pos: "adj.", def: "treating serious issues with inappropriate humour", example: "His facetious remarks fell flat at the memorial.", zh: "不合時宜地開玩笑的" },
  { front: "fastidious", pos: "adj.", def: "very attentive to detail; hard to please", example: "A fastidious editor caught the error no one else had.", zh: "一絲不苟的、挑剔的" },
  { front: "fatuous", pos: "adj.", def: "silly and pointless in a smug way", example: "The interview was padded with fatuous questions about his diet.", zh: "愚蠢的、昏庸的" },
  { front: "fervent", pos: "adj.", def: "showing intense and passionate feeling", example: "She is a fervent advocate of open-source software.", zh: "熱切的、狂熱的" },
  { front: "fickle", pos: "adj.", def: "changing loyalties or preferences frequently", example: "Fashion is a fickle business; today's icon is tomorrow's cliché.", zh: "善變的、無常的" },
  { front: "flabbergasted", pos: "adj.", def: "extremely surprised and confused", example: "We were flabbergasted to learn the bid had succeeded.", zh: "目瞪口呆的" },
  { front: "flagrant", pos: "adj.", def: "shockingly obvious and offensive (of wrongdoing)", example: "The handball was a flagrant breach of the rules.", zh: "明目張膽的" },
  { front: "flippant", pos: "adj.", def: "not showing proper seriousness or respect", example: "His flippant answer infuriated the grieving relatives.", zh: "輕率無禮的" },
  { front: "exalt", pos: "v.", def: "to praise highly or raise in status", example: "The film exalts rural life while ignoring its hardships.", zh: "褒揚、推崇" },
  { front: "fledgling", pos: "adj.", def: "new and inexperienced (of a person or organisation)", example: "The fledgling democracy faced its first real test.", zh: "初出茅廬的、新興的" },
  { front: "fritter away", pos: "phrasal v.", def: "to waste time or money bit by bit", example: "He frittered away the inheritance on failed ventures.", zh: "一點一滴地浪費" },
  { front: "palm off", pos: "phrasal v.", def: "to get rid of something by deceptively passing it to someone", example: "The dealer palmed off a fake as an original print.", zh: "矇混脫手、以假充真" },
  { front: "plough through", pos: "phrasal v.", def: "to continue doing something long and tedious to the end", example: "She ploughed through the entire archive in a fortnight.", zh: "埋頭苦讀／苦幹到底" },
  { front: "rope in", pos: "phrasal v.", def: "to persuade someone to join an activity", example: "I got roped in to organising the school fair again.", zh: "拉…入夥、說動幫忙" },
  { front: "shrug off", pos: "phrasal v.", def: "to treat something as unimportant", example: "The champion shrugged off the injury and played on.", zh: "對…不予理會、不當回事" },
  { front: "smooth over", pos: "phrasal v.", def: "to make a disagreement or problem seem less serious", example: "A joint statement smoothed over the diplomatic rift.", zh: "緩和、化解（矛盾）" },
  { front: "square up to", pos: "phrasal v.", def: "to face a difficult situation or opponent with determination", example: "It is time the board squared up to the pension deficit.", zh: "正視、勇敢面對" },
  { front: "talk down to", pos: "phrasal v.", def: "to speak to someone as if they were inferior", example: "Good science writing informs without talking down to readers.", zh: "以居高臨下的口吻說話" },
  { front: "tide over", pos: "phrasal v.", def: "to help someone through a difficult period, especially financially", example: "The loan tided the farm over until harvest.", zh: "幫助渡過難關" },
  { front: "while away", pos: "phrasal v.", def: "to spend time in a relaxed, unhurried way", example: "We whiled away the delay playing cards in the lounge.", zh: "消磨（時間）" },
  { front: "weigh up", pos: "phrasal v.", def: "to consider the advantages and disadvantages carefully", example: "She weighed up the offers before choosing the smaller firm.", zh: "權衡、斟酌" },
  { front: "hit the nail on the head", pos: "idiom", def: "to describe a situation or problem exactly", example: "Her diagnosis of the team's malaise hit the nail on the head.", zh: "一針見血、切中要害" },
  { front: "in the doldrums", pos: "idiom", def: "in a period of stagnation or low spirits", example: "The housing market has been in the doldrums all year.", zh: "低迷不振、意志消沉" },
  { front: "jump through hoops", pos: "idiom", def: "to complete many difficult, often pointless requirements", example: "Applicants must jump through endless bureaucratic hoops.", zh: "疲於應付繁瑣程序" },
  { front: "keep a low profile", pos: "idiom", def: "to deliberately avoid attracting attention", example: "The family kept a low profile during the trial.", zh: "保持低調" },
  { front: "not mince one's words", pos: "idiom", def: "to speak bluntly without softening the message", example: "The report does not mince its words about safety lapses.", zh: "直言不諱" },
  { front: "off the beaten track", pos: "idiom", def: "in a remote place few people visit", example: "The vineyard lies well off the beaten track.", zh: "人跡罕至、偏僻的" },
  { front: "play devil's advocate", pos: "idiom", def: "to argue an opposing view to test an idea", example: "Let me play devil's advocate: what if demand halves?", zh: "故意唱反調（以檢驗論點）" },
  { front: "pull the wool over someone's eyes", pos: "idiom", def: "to deceive someone by hiding the truth", example: "The forged accounts pulled the wool over the auditors' eyes for years.", zh: "蒙蔽、欺瞞" },
  { front: "rest on one's laurels", pos: "idiom", def: "to rely on past success instead of improving", example: "The brand rested on its laurels while rivals innovated.", zh: "吃老本、安於既有成就" },
  { front: "spread oneself too thin", pos: "idiom", def: "to attempt too many things at once", example: "By chairing five committees she has spread herself too thin.", zh: "分身乏術、攤子鋪太大" },
  { front: "take the bull by the horns", pos: "idiom", def: "to confront a difficulty directly and boldly", example: "He took the bull by the horns and demanded a full audit.", zh: "當機立斷、迎難而上" },
  { front: "sweeping reforms", pos: "collocation", def: "extensive changes affecting many areas", example: "The new government promised sweeping reforms of the courts.", zh: "全面性的改革" },
  { front: "vicious circle", pos: "collocation", def: "a cycle in which problems reinforce each other", example: "Low pay and high turnover form a vicious circle in care work.", zh: "惡性循環" },
  { front: "ulterior motive", pos: "collocation", def: "a hidden reason behind an action", example: "Her generosity concealed no ulterior motive whatsoever.", zh: "別有用心的動機" },
  { front: "tacit agreement", pos: "collocation", def: "an understanding accepted without being stated", example: "By tacit agreement, politics was never discussed at dinner.", zh: "默契、心照不宣的協議" },
  { front: "categorical denial", pos: "collocation", def: "an absolute, unconditional denial", example: "The studio issued a categorical denial of the casting rumours.", zh: "斷然否認" },
  { front: "chequered history", pos: "collocation", def: "a past marked by both successes and failures", example: "The stadium project has a chequered history of overruns.", zh: "毀譽參半的歷史" },
  { front: "crushing defeat", pos: "collocation", def: "an overwhelming, humiliating loss", example: "The by-election ended in a crushing defeat for the incumbents.", zh: "慘敗" },
  { front: "daunting task", pos: "collocation", def: "a task that seems intimidatingly difficult", example: "Digitising a million records is a daunting task.", zh: "艱鉅的任務" },
  { front: "deep-seated prejudice", pos: "collocation", def: "prejudice that is firmly established and hard to change", example: "The survey revealed deep-seated prejudice against older applicants.", zh: "根深蒂固的偏見" },
  { front: "gaping hole", pos: "collocation", def: "a large, obvious gap or deficiency", example: "The ruling exposed a gaping hole in data-protection law.", zh: "明顯的漏洞、巨大缺口" },
  { front: "grave concern", pos: "collocation", def: "serious worry about something important", example: "The leak is a matter of grave concern to regulators.", zh: "嚴重關切" },
  { front: "groundless accusation", pos: "collocation", def: "an accusation with no basis in fact", example: "He dismissed the claims as groundless accusations.", zh: "毫無根據的指控" },
  /* ===== Batch 4 ===== */
  { front: "flummox", pos: "v.", def: "to confuse someone completely", example: "The final riddle flummoxed every contestant.", zh: "使困惑、難倒" },
  { front: "foment", pos: "v.", def: "to stir up trouble, unrest or rebellion", example: "The pamphlets were designed to foment discontent among the troops.", zh: "煽動、挑起" },
  { front: "forestall", pos: "v.", def: "to prevent something by acting first", example: "The bank cut rates to forestall a run on deposits.", zh: "預先阻止、先發制人" },
  { front: "fortuitous", pos: "adj.", def: "happening by lucky chance", example: "A fortuitous meeting at a conference launched the collaboration.", zh: "偶然而幸運的" },
  { front: "fractious", pos: "adj.", def: "irritable and quarrelsome; hard to control", example: "The chair struggled to manage an increasingly fractious meeting.", zh: "易怒難管的、鬧彆扭的" },
  { front: "frugal", pos: "adj.", def: "careful and sparing with money or resources", example: "Decades of frugal living funded her early retirement.", zh: "節儉的" },
  { front: "furtive", pos: "adj.", def: "done secretly to avoid being noticed", example: "He cast a furtive glance at the examiner's notes.", zh: "偷偷摸摸的" },
  { front: "gainsay", pos: "v.", def: "to deny or contradict a statement", example: "There is no gainsaying the scale of her achievement.", zh: "否認、反駁" },
  { front: "gargantuan", pos: "adj.", def: "enormous in size or scale", example: "Cleaning up the spill was a gargantuan undertaking.", zh: "巨大無比的" },
  { front: "gauche", pos: "adj.", def: "socially awkward and tactless", example: "His gauche toast embarrassed both families.", zh: "笨拙失禮的" },
  { front: "germane", pos: "adj.", def: "relevant and appropriate to the matter at hand", example: "Keep your comments germane to the motion under debate.", zh: "切題的、密切相關的" },
  { front: "glib", pos: "adj.", def: "fluent but insincere or shallow", example: "Voters saw through his glib assurances.", zh: "油腔滑調的、膚淺流利的" },
  { front: "grandiose", pos: "adj.", def: "impressive in an exaggerated, unrealistic way", example: "The grandiose masterplan never got beyond the drawings.", zh: "浮誇的、好大喜功的" },
  { front: "gratuitous", pos: "adj.", def: "unnecessary and unjustified (of something harmful)", example: "Critics objected to the film's gratuitous violence.", zh: "無端的、毫無必要的" },
  { front: "gregarious", pos: "adj.", def: "fond of company; sociable", example: "A gregarious host, she filled the house with strangers who left as friends.", zh: "愛交際的、合群的" },
  { front: "guile", pos: "n.", def: "clever but deceitful cunning", example: "He won the contract through guile rather than merit.", zh: "狡詐、詭計" },
  { front: "hackneyed", pos: "adj.", def: "overused and therefore lacking impact", example: "The speech leaned on hackneyed metaphors about journeys.", zh: "陳腔濫調的" },
  { front: "hapless", pos: "adj.", def: "unlucky and deserving pity", example: "The hapless courier was blamed for the entire fiasco.", zh: "倒楣的、不幸的" },
  { front: "harangue", pos: "v.", def: "to lecture someone at length in an aggressive manner", example: "He harangued the staff about punctuality for half an hour.", zh: "喋喋不休地訓斥" },
  { front: "haughty", pos: "adj.", def: "arrogantly superior and disdainful", example: "Her haughty dismissal of the question drew gasps.", zh: "傲慢的、目中無人的" },
  { front: "hedonistic", pos: "adj.", def: "devoted to the pursuit of pleasure", example: "The resort caters to a hedonistic, moneyed crowd.", zh: "享樂主義的" },
  { front: "heinous", pos: "adj.", def: "utterly wicked or shockingly evil", example: "The tribunal was created to prosecute the most heinous crimes.", zh: "十惡不赦的" },
  { front: "histrionic", pos: "adj.", def: "excessively dramatic and theatrical", example: "Her histrionic outburst was calculated for the cameras.", zh: "誇張做作的" },
  { front: "hubris", pos: "n.", def: "excessive pride that leads to downfall", example: "The merger collapsed under the weight of executive hubris.", zh: "傲慢、狂妄自大" },
  { front: "iconoclast", pos: "n.", def: "a person who attacks cherished beliefs or institutions", example: "An iconoclast by temperament, she questioned every convention of the form.", zh: "反傳統者、打破舊習者" },
  { front: "idiosyncratic", pos: "adj.", def: "peculiar to one individual; distinctively odd", example: "His idiosyncratic filing system defeated every successor.", zh: "獨特古怪的" },
  { front: "ignominious", pos: "adj.", def: "deserving or causing public shame", example: "The campaign ended in ignominious retreat.", zh: "恥辱的、不光彩的" },
  { front: "immutable", pos: "adj.", def: "unchanging and unchangeable over time", example: "He treats market cycles as immutable laws of nature.", zh: "不可改變的" },
  { front: "impasse", pos: "n.", def: "a deadlock with no possible progress", example: "Talks reached an impasse over the border clause.", zh: "僵局" },
  { front: "impeccable", pos: "adj.", def: "flawless; in accordance with the highest standards", example: "Her timing, as ever, was impeccable.", zh: "無可挑剔的" },
  { front: "imperious", pos: "adj.", def: "arrogantly domineering and commanding", example: "With an imperious wave, he dismissed the objections.", zh: "專橫傲慢的" },
  { front: "impervious", pos: "adj.", def: "unable to be affected or penetrated", example: "He seemed impervious to criticism of any kind.", zh: "不受影響的、不能滲透的" },
  { front: "impetuous", pos: "adj.", def: "acting quickly without thought or care", example: "An impetuous tweet cost him the sponsorship.", zh: "衝動魯莽的" },
  { front: "implacable", pos: "adj.", def: "impossible to appease or pacify", example: "She faced implacable opposition from the old guard.", zh: "難以平息的、毫不妥協的" },
  { front: "impunity", pos: "n.", def: "exemption from punishment or consequences", example: "The militias operated with near-total impunity.", zh: "免受懲罰" },
  { front: "inadvertent", pos: "adj.", def: "not intentional; resulting from oversight", example: "The breach was inadvertent but costly nonetheless.", zh: "無意的、疏忽造成的" },
  { front: "incendiary", pos: "adj.", def: "designed to provoke anger or conflict", example: "His incendiary remarks set social media ablaze.", zh: "煽動性的" },
  { front: "incisive", pos: "adj.", def: "intelligently sharp and direct in analysis", example: "Her incisive questioning exposed the flaw in minutes.", zh: "犀利透澈的" },
  { front: "incongruous", pos: "adj.", def: "strangely out of place or inconsistent", example: "The glass tower looks incongruous beside the mediaeval walls.", zh: "不協調的、格格不入的" },
  { front: "incorrigible", pos: "adj.", def: "unable to be corrected or reformed", example: "He is an incorrigible optimist, whatever the forecast.", zh: "屢教不改的、積習難改的" },
  { front: "indefatigable", pos: "adj.", def: "tireless; persisting without ever flagging", example: "An indefatigable campaigner, she never missed a hearing in thirty years.", zh: "不知疲倦的" },
  { front: "balk at", pos: "phrasal v.", def: "to hesitate or refuse to accept something", example: "Shareholders balked at the chairman's pay package.", zh: "對…卻步、不肯接受" },
  { front: "bank on", pos: "phrasal v.", def: "to rely confidently on something happening", example: "Don't bank on the weather holding for the ceremony.", zh: "指望、依賴" },
  { front: "bottle up", pos: "phrasal v.", def: "to suppress emotions instead of expressing them", example: "Years of bottled-up resentment surfaced in one argument.", zh: "壓抑（情緒）" },
  { front: "brush aside", pos: "phrasal v.", def: "to dismiss something as unimportant", example: "The CEO brushed aside concerns about the debt load.", zh: "漠視、置之不理" },
  { front: "chip away at", pos: "phrasal v.", def: "to gradually reduce or weaken something", example: "Successive rulings have chipped away at the agency's authority.", zh: "逐漸削弱、蠶食" },
  { front: "come down on", pos: "phrasal v.", def: "to punish or criticise someone severely", example: "The regulator came down hard on undisclosed fees.", zh: "嚴懲、狠批" },
  { front: "cotton on to", pos: "phrasal v.", def: "to begin to understand or realise something", example: "It took the markets a week to cotton on to the implications.", zh: "領悟、開始明白" },
  { front: "dredge up", pos: "phrasal v.", def: "to bring up something unpleasant from the past", example: "The interviewer dredged up a scandal from his student days.", zh: "重提（舊事）、翻舊帳" },
  { front: "egg on", pos: "phrasal v.", def: "to urge someone to do something unwise", example: "Egged on by the crowd, he attempted the jump.", zh: "慫恿、煽動" },
  { front: "eke out", pos: "phrasal v.", def: "to make something last by careful use; to barely obtain", example: "They eked out a living from two acres of stony soil.", zh: "勉強維持、省吃儉用" },
  { front: "face up to", pos: "phrasal v.", def: "to accept and deal with something difficult", example: "The industry must face up to its environmental record.", zh: "正視、勇於面對" },
  { front: "throw caution to the wind", pos: "idiom", def: "to abandon prudence and take a risk", example: "She threw caution to the wind and invested her savings in the venture.", zh: "不顧一切、豁出去" },
  { front: "turn a blind eye", pos: "idiom", def: "to deliberately ignore wrongdoing", example: "Managers turned a blind eye to the falsified logs.", zh: "視而不見、睜一隻眼閉一隻眼" },
  { front: "weather the storm", pos: "idiom", def: "to survive a period of difficulty", example: "Smaller suppliers may not weather the storm of cancelled orders.", zh: "度過難關" },
  { front: "a bone of contention", pos: "idiom", def: "a subject over which there is continuing disagreement", example: "The parking spaces remain a bone of contention between the tenants.", zh: "爭執的焦點" },
  { front: "bite off more than one can chew", pos: "idiom", def: "to take on more than one can manage", example: "Renovating both houses at once was biting off more than we could chew.", zh: "不自量力、貪多嚼不爛" },
  { front: "burn one's bridges", pos: "idiom", def: "to destroy any possibility of returning or retreating", example: "His scathing farewell email burned every bridge in the industry.", zh: "自斷後路" },
  { front: "call the shots", pos: "idiom", def: "to be the person who makes the decisions", example: "It is the funders, not the curators, who call the shots now.", zh: "發號施令、作主" },
  { front: "champ at the bit", pos: "idiom", def: "to be impatient to start doing something", example: "The recruits were champing at the bit to see real cases.", zh: "躍躍欲試、迫不及待" },
  { front: "down to the wire", pos: "idiom", def: "undecided until the very last moment", example: "The title race went down to the wire on the final afternoon.", zh: "拖到最後一刻才見分曉" },
  { front: "fall from grace", pos: "idiom", def: "to lose status, respect or favour", example: "The banker's fall from grace was swift and public.", zh: "失勢、聲名掃地" },
  { front: "fly in the face of", pos: "idiom", def: "to be in open contradiction to something", example: "The decision flies in the face of all the expert advice.", zh: "公然違背" },
  { front: "hidden agenda", pos: "collocation", def: "a secret motive behind stated aims", example: "Critics suspect a hidden agenda behind the 'efficiency review'.", zh: "不可告人的目的" },
  { front: "knee-jerk reaction", pos: "collocation", def: "an automatic, unthinking response", example: "Banning the app was a knee-jerk reaction to one incident.", zh: "下意識的反應、直覺反應" },
  { front: "level playing field", pos: "collocation", def: "a situation of fair and equal competition", example: "The tax rebate denies smaller firms a level playing field.", zh: "公平的競爭環境" },
  { front: "pivotal role", pos: "collocation", def: "a role of crucial importance", example: "Community nurses played a pivotal role in the vaccination drive.", zh: "關鍵作用" },
  { front: "profound impact", pos: "collocation", def: "a very deep and far-reaching effect", example: "The ruling will have a profound impact on gig-economy workers.", zh: "深遠的影響" },
  { front: "quantum leap", pos: "collocation", def: "a sudden, dramatic advance", example: "The new battery represents a quantum leap in storage density.", zh: "重大突破、飛躍" },
  { front: "seething resentment", pos: "collocation", def: "intense suppressed anger and bitterness", example: "Behind the polite emails lay seething resentment.", zh: "沸騰的積怨" },
  { front: "sheer audacity", pos: "collocation", def: "pure, astonishing boldness", example: "The sheer audacity of the forgery impressed even the detectives.", zh: "十足的大膽" },
  { front: "spiralling costs", pos: "collocation", def: "costs rising rapidly out of control", example: "Spiralling costs forced the museum to halt construction.", zh: "不斷飆升的成本" },
  { front: "stumbling block", pos: "collocation", def: "an obstacle that prevents progress", example: "Funding remains the chief stumbling block to the merger.", zh: "絆腳石、障礙" },
  { front: "tangible benefits", pos: "collocation", def: "clear, real and measurable advantages", example: "Residents have yet to see tangible benefits from the regeneration.", zh: "實質的好處" },
  { front: "mounting evidence", pos: "collocation", def: "a growing body of proof", example: "Mounting evidence links the additive to allergic reactions.", zh: "越來越多的證據" },
  /* ===== Batch 5 ===== */
  { front: "indelible", pos: "adj.", def: "impossible to remove or forget", example: "The eruption left an indelible mark on the island's psyche.", zh: "無法磨滅的" },
  { front: "indignant", pos: "adj.", def: "angry at perceived unfair treatment", example: "Indignant passengers demanded to see the manager.", zh: "憤憤不平的" },
  { front: "indolent", pos: "adj.", def: "habitually lazy and avoiding effort", example: "The indolent heir let the estate crumble around him.", zh: "怠惰的" },
  { front: "ineffable", pos: "adj.", def: "too great or extreme to be expressed in words", example: "Standing beneath the aurora, we felt an ineffable awe.", zh: "難以言喻的" },
  { front: "inept", pos: "adj.", def: "lacking skill; clumsily incompetent", example: "The inept handling of the recall deepened the crisis.", zh: "無能的、笨拙的" },
  { front: "inexorable", pos: "adj.", def: "impossible to stop or prevent", example: "Nothing could halt the inexorable spread of the desert.", zh: "不可阻擋的" },
  { front: "infallible", pos: "adj.", def: "incapable of making mistakes or failing", example: "No forecasting model is infallible, however elegant.", zh: "絕無差錯的" },
  { front: "ingenuous", pos: "adj.", def: "innocently frank and trusting", example: "Her ingenuous questions disarmed the seasoned negotiators.", zh: "天真坦率的" },
  { front: "inimical", pos: "adj.", def: "harmful or hostile to something", example: "Constant interruption is inimical to deep thought.", zh: "有害的、敵對的" },
  { front: "iniquitous", pos: "adj.", def: "grossly unfair and morally wrong", example: "The pamphlet denounced the iniquitous window tax.", zh: "極不公正的" },
  { front: "innocuous", pos: "adj.", def: "completely harmless or inoffensive", example: "What began as an innocuous question sparked a furious row.", zh: "無害的、不得罪人的" },
  { front: "inscrutable", pos: "adj.", def: "impossible to understand or interpret", example: "Throughout the hearing his expression remained inscrutable.", zh: "高深莫測的" },
  { front: "insipid", pos: "adj.", def: "lacking flavour, interest or vigour", example: "The panel dismissed the wine as insipid and overpriced.", zh: "乏味的、平淡的" },
  { front: "insolent", pos: "adj.", def: "rude and disrespectful, especially to authority", example: "The insolent reply earned him a week's suspension.", zh: "無禮傲慢的" },
  { front: "insular", pos: "adj.", def: "narrow-minded through isolation from outside influences", example: "The industry's insular culture resisted every outside idea.", zh: "狹隘的、封閉的" },
  { front: "interminable", pos: "adj.", def: "seeming to last forever; tediously long", example: "We sat through an interminable succession of speeches.", zh: "冗長不休的" },
  { front: "intractable", pos: "adj.", def: "very difficult to solve or manage", example: "Homelessness has proved an intractable problem for successive mayors.", zh: "棘手難解的" },
  { front: "intrepid", pos: "adj.", def: "fearless and adventurous", example: "A few intrepid reporters stayed on in the besieged city.", zh: "無畏的" },
  { front: "inured", pos: "adj.", def: "accustomed to something unpleasant through long exposure", example: "Years on the trading floor left her inured to abuse.", zh: "習以為常的（對不快之事）" },
  { front: "invective", pos: "n.", def: "abusive or insulting language", example: "The debate degenerated into pure invective.", zh: "謾罵、抨擊之詞" },
  { front: "inveterate", pos: "adj.", def: "having a long-established, unlikely-to-change habit", example: "An inveterate gambler, he could not pass a casino.", zh: "積習難改的" },
  { front: "irascible", pos: "adj.", def: "easily angered; hot-tempered", example: "The irascible chef was feared by three generations of apprentices.", zh: "易怒的" },
  { front: "itinerant", pos: "adj.", def: "travelling from place to place for work", example: "Itinerant pickers follow the harvest up the valley.", zh: "巡迴的、流動的" },
  { front: "jaded", pos: "adj.", def: "tired and unenthusiastic after too much of something", example: "Even jaded festival-goers were astonished by the finale.", zh: "厭倦的、麻木的" },
  { front: "jubilant", pos: "adj.", def: "expressing great joy at a success", example: "Jubilant supporters poured into the square at midnight.", zh: "歡欣鼓舞的" },
  { front: "judicious", pos: "adj.", def: "showing good judgement and sense", example: "A judicious mix of caution and ambition served her well.", zh: "明智審慎的" },
  { front: "juxtapose", pos: "v.", def: "to place contrasting things side by side", example: "The exhibition juxtaposes wartime posters with private letters.", zh: "並列、對照" },
  { front: "lackadaisical", pos: "adj.", def: "lacking enthusiasm and determination; careless", example: "Their lackadaisical defending cost them the match.", zh: "無精打采的、散漫的" },
  { front: "lament", pos: "v.", def: "to express deep sorrow or regret about something", example: "Historians lament the loss of the archive in the fire.", zh: "哀嘆、痛惜" },
  { front: "languish", pos: "v.", def: "to remain neglected in an unwanted state; to weaken", example: "The bill has languished in committee for two years.", zh: "被擱置、日漸衰弱" },
  { front: "largesse", pos: "n.", def: "generosity in giving money or gifts", example: "The gallery owes its wing to one collector's largesse.", zh: "慷慨捐贈" },
  { front: "latent", pos: "adj.", def: "existing but not yet developed or visible", example: "The coach spotted her latent talent at a school meet.", zh: "潛在的" },
  { front: "laudable", pos: "adj.", def: "deserving praise, even if not wholly successful", example: "The aims are laudable; the execution is another matter.", zh: "值得稱許的" },
  { front: "lethargic", pos: "adj.", def: "sluggish and lacking energy", example: "The heat left the whole office lethargic by mid-afternoon.", zh: "昏昏欲睡的、無力的" },
  { front: "loquacious", pos: "adj.", def: "very talkative", example: "Our loquacious guide barely paused for breath in two hours.", zh: "健談的、多話的" },
  { front: "lucid", pos: "adj.", def: "clearly expressed; mentally clear", example: "Her lucid summary made the tangled case comprehensible.", zh: "清晰明瞭的、神志清醒的" },
  { front: "magnanimous", pos: "adj.", def: "generous and forgiving towards a rival or enemy", example: "In victory he was magnanimous, praising his opponent's campaign.", zh: "寬宏大量的" },
  { front: "malleable", pos: "adj.", def: "easily shaped or influenced", example: "Young audiences are assumed, wrongly, to be endlessly malleable.", zh: "可塑的、易受影響的" },
  { front: "maudlin", pos: "adj.", def: "tearfully sentimental, often excessively", example: "The film's maudlin ending undercuts its earlier restraint.", zh: "多愁善感的、濫情的" },
  { front: "maverick", pos: "n.", def: "an independent-minded person who defies convention", example: "The appointment of a known maverick unsettled the board.", zh: "特立獨行的人" },
  { front: "mellifluous", pos: "adj.", def: "sweet and smooth-sounding (of a voice or music)", example: "His mellifluous baritone made even the shipping forecast soothing.", zh: "悅耳流暢的" },
  { front: "fizzle out", pos: "phrasal v.", def: "to end weakly after a promising start", example: "The protest movement fizzled out once winter set in.", zh: "虎頭蛇尾、逐漸消失" },
  { front: "flesh out", pos: "phrasal v.", def: "to add detail to a plan or idea", example: "The white paper fleshes out proposals sketched in the manifesto.", zh: "充實、使具體化" },
  { front: "hold out for", pos: "phrasal v.", def: "to refuse to accept less than what one wants", example: "The union is holding out for a genuine pay rise.", zh: "堅持等待（更好條件）" },
  { front: "home in on", pos: "phrasal v.", def: "to focus attention precisely on a target", example: "The inquiry homed in on the missing minutes.", zh: "鎖定、聚焦於" },
  { front: "leaf through", pos: "phrasal v.", def: "to turn pages quickly, reading casually", example: "She leafed through the catalogue while she waited.", zh: "隨手翻閱" },
  { front: "level with", pos: "phrasal v.", def: "to speak honestly to someone", example: "I'll level with you: the project is three months behind.", zh: "對…坦誠相告" },
  { front: "nail down", pos: "phrasal v.", def: "to establish something clearly and finally", example: "We still need to nail down the delivery dates.", zh: "確定、敲定" },
  { front: "pan out", pos: "phrasal v.", def: "to develop or turn out, especially successfully", example: "The partnership didn't pan out as either side had hoped.", zh: "（事情）發展、結果" },
  { front: "paper over", pos: "phrasal v.", def: "to hide a problem rather than solve it", example: "The joint communiqué papered over deep divisions.", zh: "掩蓋（問題、分歧）" },
  { front: "pare down", pos: "phrasal v.", def: "to reduce something to its essentials", example: "The director pared the script down to ninety taut minutes.", zh: "精簡、削減" },
  { front: "pin down", pos: "phrasal v.", def: "to force someone to be specific; to define exactly", example: "Ministers proved impossible to pin down on a date.", zh: "使明確表態、確切界定" },
  { front: "get wind of", pos: "idiom", def: "to hear about something secret or private", example: "Journalists got wind of the takeover before the staff did.", zh: "聽到風聲、獲悉" },
  { front: "give someone the benefit of the doubt", pos: "idiom", def: "to choose to believe someone despite uncertainty", example: "It was his first offence, so the referee gave him the benefit of the doubt.", zh: "姑且相信、從寬認定" },
  { front: "go down like a lead balloon", pos: "idiom", def: "to be received very badly by an audience", example: "The pay-freeze announcement went down like a lead balloon.", zh: "反應極差、不受歡迎" },
  { front: "have one's work cut out", pos: "idiom", def: "to face a very difficult task", example: "The new manager has her work cut out rebuilding morale.", zh: "任務艱鉅" },
  { front: "in dire straits", pos: "idiom", def: "in an extremely difficult situation", example: "By March the airline was in dire straits financially.", zh: "陷入困境、岌岌可危" },
  { front: "jump the gun", pos: "idiom", def: "to act before the proper or agreed time", example: "The paper jumped the gun and published before the embargo lifted.", zh: "操之過急、搶先行動" },
  { front: "keep one's cards close to one's chest", pos: "idiom", def: "to keep one's plans or intentions secret", example: "On the succession question, the chairman keeps his cards close to his chest.", zh: "守口如瓶、不露底牌" },
  { front: "leave someone in the lurch", pos: "idiom", def: "to abandon someone when they need help", example: "The contractor's collapse left hundreds of buyers in the lurch.", zh: "棄人於危難之中" },
  { front: "make a mountain out of a molehill", pos: "idiom", def: "to exaggerate a minor problem", example: "It's a typo, not a scandal — don't make a mountain out of a molehill.", zh: "小題大作" },
  { front: "nip something in the bud", pos: "idiom", def: "to stop a problem at an early stage", example: "Mediation nipped the dispute in the bud.", zh: "防患未然、及早遏止" },
  { front: "not hold water", pos: "idiom", def: "to fail to stand up to scrutiny (of an argument)", example: "His alibi simply doesn't hold water.", zh: "站不住腳" },
  { front: "thorny issue", pos: "collocation", def: "a problem that is complicated and hard to resolve", example: "Pension reform remains the thorniest issue on the agenda.", zh: "棘手的問題" },
  { front: "thriving economy", pos: "collocation", def: "an economy that is growing and prosperous", example: "Tourism underlies the island's thriving economy.", zh: "蓬勃發展的經濟" },
  { front: "unbridled enthusiasm", pos: "collocation", def: "enthusiasm that is uncontrolled and unrestrained", example: "She greeted the plan with unbridled enthusiasm.", zh: "毫無保留的熱情" },
  { front: "unwavering commitment", pos: "collocation", def: "steady, resolute dedication that never falters", example: "The charity thanked donors for their unwavering commitment.", zh: "堅定不移的投入" },
  { front: "utter contempt", pos: "collocation", def: "complete and total scorn", example: "He regarded the tabloid's apology with utter contempt.", zh: "十足的蔑視" },
  { front: "vehement opposition", pos: "collocation", def: "intense, forceful resistance", example: "The route change met vehement opposition from farmers.", zh: "強烈的反對" },
  { front: "watertight alibi", pos: "collocation", def: "an alibi that cannot be disproved", example: "The suspect produced a watertight alibi for the whole evening.", zh: "無懈可擊的不在場證明" },
  { front: "widespread condemnation", pos: "collocation", def: "criticism expressed by many people or groups", example: "The raid drew widespread condemnation abroad.", zh: "普遍的譴責" },
  { front: "wreak havoc", pos: "collocation", def: "to cause great damage or disorder", example: "The late frost wreaked havoc on the vineyards.", zh: "造成嚴重破壞" },
  { front: "yawning gap", pos: "collocation", def: "a very large and obvious difference", example: "A yawning gap separates the rhetoric from the budget.", zh: "巨大的差距" },
  { front: "abject poverty", pos: "collocation", def: "extreme, degrading poverty", example: "Millions still live in abject poverty on the city's fringes.", zh: "赤貧" },
  { front: "blissful ignorance", pos: "collocation", def: "a happy state of not knowing unpleasant facts", example: "We spent the weekend in blissful ignorance of the crisis unfolding at work.", zh: "渾然不知的幸福" },
  /* ===== Batch 6 ===== */
  { front: "mendacious", pos: "adj.", def: "habitually lying or false", example: "The court found the testimony deliberately mendacious.", zh: "撒謊成性的、虛假的" },
  { front: "mercurial", pos: "adj.", def: "subject to sudden unpredictable changes of mood", example: "Working for such a mercurial director required nerves of steel.", zh: "情緒多變的" },
  { front: "meticulous", pos: "adj.", def: "extremely careful and precise about details", example: "Her meticulous records made the audit painless.", zh: "一絲不苟的" },
  { front: "misnomer", pos: "n.", def: "a wrong or inaccurate name for something", example: "'Fast rail' is a misnomer for a line averaging forty miles an hour.", zh: "名不副實的稱呼、誤稱" },
  { front: "mollify", pos: "v.", def: "to calm someone's anger; to appease", example: "A partial refund did little to mollify the stranded passengers.", zh: "安撫、平息（怒氣）" },
  { front: "morose", pos: "adj.", def: "sullen, gloomy and unwilling to talk", example: "He grew morose and withdrawn after the shop closed.", zh: "鬱鬱寡歡的" },
  { front: "munificent", pos: "adj.", def: "extremely generous in giving", example: "A munificent bequest endowed the new scholarship.", zh: "慷慨大方的" },
  { front: "nadir", pos: "n.", def: "the lowest point of a situation", example: "Relations between the two capitals reached their nadir that winter.", zh: "最低點、谷底" },
  { front: "nefarious", pos: "adj.", def: "wicked or criminal in nature", example: "The shell companies served altogether more nefarious purposes.", zh: "邪惡的、不法的" },
  { front: "nonchalant", pos: "adj.", def: "calmly casual and appearing unconcerned", example: "He gave a nonchalant shrug, as if millions were not at stake.", zh: "滿不在乎的、若無其事的" },
  { front: "nonplussed", pos: "adj.", def: "so surprised that one is unsure how to react", example: "The panel seemed nonplussed by her unorthodox answer.", zh: "不知所措的" },
  { front: "obdurate", pos: "adj.", def: "stubbornly refusing to change one's opinion", example: "The landlord remained obdurate despite every appeal.", zh: "執拗的、頑固的" },
  { front: "obstreperous", pos: "adj.", def: "noisy, unruly and difficult to control", example: "Stewards struggled to contain the obstreperous crowd.", zh: "吵鬧任性的、難以控制的" },
  { front: "obtuse", pos: "adj.", def: "annoyingly slow to understand, perhaps deliberately", example: "Don't be obtuse — you know exactly what the memo implied.", zh: "遲鈍的（或裝傻的）" },
  { front: "obviate", pos: "v.", def: "to remove a need or difficulty in advance", example: "Digital signatures obviate the need for couriered documents.", zh: "消除（必要性）、避免" },
  { front: "officious", pos: "adj.", def: "asserting authority in an annoyingly domineering way", example: "An officious steward demanded to see our passes twice.", zh: "好管閒事的、愛擺官腔的" },
  { front: "onerous", pos: "adj.", def: "involving heavy obligations; burdensome", example: "Small charities find the reporting rules especially onerous.", zh: "繁重的、負擔沉重的" },
  { front: "opulent", pos: "adj.", def: "luxuriously wealthy and lavish", example: "The opulent lobby was all marble and gold leaf.", zh: "豪華的、奢侈的" },
  { front: "ostracise", pos: "v.", def: "to exclude someone from a group or society", example: "Whistle-blowers are too often ostracised by former colleagues.", zh: "排擠、放逐" },
  { front: "palliative", pos: "n.", def: "a remedy that eases symptoms without curing the cause", example: "The tax cut is a palliative, not a solution to stagnant wages.", zh: "治標不治本的措施；緩和劑" },
  { front: "palpable", pos: "adj.", def: "so intense as to seem almost physically felt", example: "The tension in the courtroom was palpable.", zh: "明顯可感的" },
  { front: "paltry", pos: "adj.", def: "insultingly small in amount", example: "The settlement offered a paltry sum for a ruined career.", zh: "微不足道的" },
  { front: "paragon", pos: "n.", def: "a perfect model of a particular quality", example: "She was held up as a paragon of journalistic integrity.", zh: "典範、完人" },
  { front: "pariah", pos: "n.", def: "a person or entity despised and rejected by others", example: "After the scandal, the firm became a pariah in the industry.", zh: "被唾棄者、賤民" },
  { front: "parsimonious", pos: "adj.", def: "extremely unwilling to spend money", example: "The famously parsimonious owner reused envelopes twice.", zh: "吝嗇的" },
  { front: "paucity", pos: "n.", def: "an insufficient amount; scarcity", example: "The study is hampered by a paucity of reliable data.", zh: "缺乏、匱乏" },
  { front: "pejorative", pos: "adj.", def: "expressing disapproval or contempt (of a word)", example: "'Bureaucrat' is almost always used in a pejorative sense.", zh: "貶義的" },
  { front: "penchant", pos: "n.", def: "a strong habitual liking for something", example: "She has a penchant for impossible deadlines.", zh: "嗜好、偏好" },
  { front: "perennial", pos: "adj.", def: "continually recurring or long-lasting", example: "Underfunding is the perennial complaint of rural schools.", zh: "長期反覆出現的" },
  { front: "peripatetic", pos: "adj.", def: "travelling from place to place, especially for work", example: "His peripatetic childhood left him fluent in four languages.", zh: "四處遊走的、流動的" },
  { front: "perspicacious", pos: "adj.", def: "having sharp insight and understanding", example: "A perspicacious reviewer spotted the flaw in the methodology.", zh: "睿智敏銳的" },
  { front: "pertinent", pos: "adj.", def: "directly relevant to the matter in question", example: "Confine your answers to the pertinent facts.", zh: "切題的、相關的" },
  { front: "phlegmatic", pos: "adj.", def: "calm and unemotional, even in a crisis", example: "The phlegmatic pilot narrated the emergency as if reading a menu.", zh: "冷靜沉著的" },
  { front: "pithy", pos: "adj.", def: "brief, forceful and full of meaning", example: "Her pithy summary said more than the fifty-page report.", zh: "簡潔有力的" },
  { front: "platitude", pos: "n.", def: "an overused remark presented as if meaningful", example: "The speech offered platitudes where policies were needed.", zh: "陳腔濫調" },
  { front: "plethora", pos: "n.", def: "an excessive or overabundant amount", example: "Shoppers face a plethora of near-identical tariffs.", zh: "過多、過剩" },
  { front: "precipitate", pos: "v.", def: "to cause something bad to happen suddenly", example: "The bank's collapse precipitated a regional crisis.", zh: "促使（壞事）突然發生" },
  { front: "profligate", pos: "adj.", def: "recklessly wasteful with money or resources", example: "Auditors condemned the agency's profligate spending on consultants.", zh: "揮霍無度的" },
  { front: "prosaic", pos: "adj.", def: "dull, ordinary and lacking imagination", example: "The explanation proved prosaic: a blown fuse, not sabotage.", zh: "平淡無奇的" },
  { front: "quixotic", pos: "adj.", def: "idealistic and impractical to a fault", example: "His quixotic bid to row the Atlantic alone ended in Lisbon.", zh: "不切實際的、唐吉訶德式的" },
  { front: "recondite", pos: "adj.", def: "little known and difficult to understand", example: "The thesis explores a recondite corner of Byzantine law.", zh: "深奧冷僻的" },
  { front: "piece together", pos: "phrasal v.", def: "to reconstruct facts or events from fragments", example: "Investigators pieced together the flight's final minutes.", zh: "拼湊出（真相）" },
  { front: "play down", pos: "phrasal v.", def: "to make something seem less important than it is", example: "Officials played down the risk of contamination.", zh: "淡化、輕描淡寫" },
  { front: "prattle on", pos: "phrasal v.", def: "to talk at length about trivial things", example: "He prattled on about his golf handicap through dinner.", zh: "喋喋不休" },
  { front: "rail against", pos: "phrasal v.", def: "to protest strongly and bitterly about something", example: "The column rails against the cult of productivity.", zh: "怒斥、猛烈抨擊" },
  { front: "ratchet up", pos: "phrasal v.", def: "to increase something steadily in stages", example: "Both sides ratcheted up the rhetoric before the summit.", zh: "逐步升高、加碼" },
  { front: "reel off", pos: "phrasal v.", def: "to say a list quickly and effortlessly from memory", example: "She reeled off the statistics without a single note.", zh: "一口氣說出" },
  { front: "rein in", pos: "phrasal v.", def: "to bring something under stricter control", example: "The treaty aims to rein in subsidies for overfishing.", zh: "控制、約束" },
  { front: "ride out", pos: "phrasal v.", def: "to survive a difficult period without serious harm", example: "The firm rode out the recession by cutting everything but research.", zh: "安然度過" },
  { front: "root out", pos: "phrasal v.", def: "to find and completely remove something bad", example: "The new chief vowed to root out corruption in the force.", zh: "根除、剷除" },
  { front: "scale back", pos: "phrasal v.", def: "to reduce something in size or extent", example: "The developer scaled back the tower from forty storeys to twelve.", zh: "縮減（規模）" },
  { front: "skate over", pos: "phrasal v.", def: "to avoid dealing with a difficult subject properly", example: "The memoir skates over his years at the ministry.", zh: "避重就輕、一筆帶過" },
  { front: "off the cuff", pos: "idiom", def: "without preparation; improvised", example: "Speaking off the cuff, she was even more persuasive than her scripts.", zh: "即興地、未經準備地" },
  { front: "on a knife-edge", pos: "idiom", def: "in a very tense, uncertain situation", example: "The referendum result stood on a knife-edge all night.", zh: "千鈞一髮、勝負難料" },
  { front: "out of one's depth", pos: "idiom", def: "in a situation too difficult for one's ability", example: "Promoted too soon, he was visibly out of his depth.", zh: "力不從心、能力不及" },
  { front: "pay lip service to", pos: "idiom", def: "to support something in words but not in action", example: "The firm pays lip service to sustainability while lobbying against it.", zh: "口惠而實不至" },
  { front: "pull no punches", pos: "idiom", def: "to criticise with complete frankness", example: "The documentary pulls no punches about the industry's failings.", zh: "毫不留情、直言批評" },
  { front: "run out of steam", pos: "idiom", def: "to lose energy or momentum before finishing", example: "The reform drive ran out of steam after the minister moved on.", zh: "後繼無力、失去動力" },
  { front: "set in stone", pos: "idiom", def: "fixed and impossible to change", example: "The schedule is provisional — nothing is set in stone.", zh: "板上釘釘、不可更改" },
  { front: "split hairs", pos: "idiom", def: "to argue about tiny, unimportant differences", example: "Whether it's a 'fee' or a 'charge' is splitting hairs.", zh: "吹毛求疵、鑽牛角尖" },
  { front: "swim against the tide", pos: "idiom", def: "to act contrary to prevailing opinion or trends", example: "Her cash-only shop swims against the tide of digital payment.", zh: "逆流而行、與潮流相悖" },
  { front: "throw in the towel", pos: "idiom", def: "to admit defeat and give up", example: "After three failed funding rounds, the founders threw in the towel.", zh: "認輸、放棄" },
  { front: "a drop in the ocean", pos: "idiom", def: "an amount too small to make any real difference", example: "The donation, though generous, is a drop in the ocean of what's needed.", zh: "滄海一粟、杯水車薪" },
  { front: "astronomical prices", pos: "collocation", def: "extremely high prices", example: "Central flats now fetch astronomical prices.", zh: "天價" },
  { front: "bleak outlook", pos: "collocation", def: "a future prospect offering little hope", example: "Economists paint a bleak outlook for exporters this year.", zh: "黯淡的前景" },
  { front: "compelling argument", pos: "collocation", def: "an argument that is powerfully convincing", example: "She makes a compelling argument for scrapping the levy.", zh: "極具說服力的論點" },
  { front: "crippling debt", pos: "collocation", def: "debt so heavy it prevents normal functioning", example: "Graduates enter the workforce carrying crippling debt.", zh: "沉重難負的債務" },
  { front: "damning evidence", pos: "collocation", def: "evidence that strongly proves guilt or failure", example: "The recordings provided damning evidence of price-fixing.", zh: "罪證確鑿的證據" },
  { front: "draconian measures", pos: "collocation", def: "excessively harsh rules or punishments", example: "Critics called the curfew draconian measures unfit for a democracy.", zh: "嚴苛的措施" },
  { front: "flimsy excuse", pos: "collocation", def: "a weak, unconvincing excuse", example: "He skipped the hearing on the flimsiest of excuses.", zh: "站不住腳的藉口" },
  { front: "glowing review", pos: "collocation", def: "a review full of enthusiastic praise", example: "The debut novel earned glowing reviews on both sides of the Atlantic.", zh: "讚譽有加的評論" },
  { front: "implicit assumption", pos: "collocation", def: "an assumption taken for granted without being stated", example: "The model rests on the implicit assumption that demand never falls.", zh: "隱含的假設" },
  { front: "sobering thought", pos: "collocation", def: "a fact that makes one serious and reflective", example: "That half the town is uninsured is a sobering thought.", zh: "發人深省的想法" },
  { front: "uncharted territory", pos: "collocation", def: "a situation never experienced before", example: "Negative interest rates took central banks into uncharted territory.", zh: "未知的領域" },
  { front: "wholesale changes", pos: "collocation", def: "extensive changes affecting everything at once", example: "The relegated club made wholesale changes to its squad.", zh: "大規模的變動" }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
