(function () {
var BANK = [
  { id: "c-lis3-01", title: "Interview: Recording the Wild — A Nature Sound Specialist Speaks", kind: "dialogue",
    script: "Host: My guest today is Elena Marsh, whose job title, wildlife sound recordist, hides twenty years of lying in bogs before dawn. Elena, people assume the pictures are the hard part of a nature documentary. Set us straight.\nElena: Gladly, because it's a myth I fight constantly. The truth is that most of what you hear on a wildlife film wasn't recorded when the camera was rolling. Cameras with long lenses can film from two hundred metres away; a microphone at that distance mostly captures wind and, these days, traffic. So the sound team goes out separately, sometimes weeks later, to gather the honest voices of that habitat.\nHost: Honest voices — but recorded at a different time. Some would call that fakery.\nElena: I'd push back on that, carefully. If I record a real dawn chorus in the actual valley you're watching, and lay it under footage filmed there, I'd argue that's truthful in every way that matters. Where I do draw a line, and the industry has tightened up here, is using a library recording from a different continent because it sounds more dramatic. That used to be routine, frankly, and it made scientists wince.\nHost: What's the hardest thing you've ever captured?\nElena: Silence, oddly enough. I spent three weeks in a desert trying to record genuine natural quiet for a sequence about aridity, and I was defeated night after night — not by animals, but by aircraft. There is almost nowhere left on Earth without a flight path overhead. In the end we got ninety usable seconds, and I'm prouder of those than of anything with a lion in it.\nHost: And has the job changed you?\nElena: Completely. I hear cities the way most people hear orchestras — layers, patterns. But the bigger change is grief, if I'm honest. Recordings I made twenty years ago in ordinary English woodland simply cannot be repeated now; the density of birdsong has thinned that much. My archive has accidentally become evidence, and I've started donating it to researchers, because it documents a decline I never set out to record.",
    questions: [
      { q: "What misconception does Elena say she constantly has to correct?", options: ["That sound is captured at the same moment as the pictures.", "That wildlife sound recordists rarely leave the studio.", "That cameras cannot film animals from a distance.", "That documentaries no longer employ sound teams."], answer: 0, explanation: "She says \"most of what you hear on a wildlife film wasn't recorded when the camera was rolling\" — the sound team goes out separately, sometimes weeks later." },
      { q: "Where does Elena draw the line on acceptable practice?", options: ["Recording a dawn chorus weeks after filming.", "Laying real local sound under footage of the same place.", "Using recordings from an entirely different region for dramatic effect.", "Editing out traffic noise from a recording."], answer: 2, explanation: "She defends same-valley recordings as \"truthful in every way that matters\" but draws a line at \"a library recording from a different continent because it sounds more dramatic\"." },
      { q: "Why was the desert assignment so difficult?", options: ["The animals refused to approach her microphones.", "Aircraft noise made true silence almost impossible to find.", "The wind destroyed her recording equipment.", "She was only given ninety seconds of recording time."], answer: 1, explanation: "She was defeated \"not by animals, but by aircraft. There is almost nowhere left on Earth without a flight path overhead\" — the ninety seconds were what survived, not a time limit." },
      { q: "How does Elena feel about the desert recording?", options: ["Embarrassed that so little material was usable.", "More satisfied with it than with more spectacular recordings.", "Angry that the sequence was cut from the film.", "Doubtful that audiences noticed it at all."], answer: 1, explanation: "She says \"we got ninety usable seconds, and I'm prouder of those than of anything with a lion in it\" — pride, not embarrassment." },
      { q: "What unexpected significance has Elena's archive acquired?", options: ["It has become valuable to collectors of rare media.", "It proves that woodland birds have adapted to cities.", "It serves as evidence of declining birdsong over time.", "It is now used to train new sound recordists."], answer: 2, explanation: "Recordings from twenty years ago \"simply cannot be repeated now; the density of birdsong has thinned\" — her archive \"has accidentally become evidence\" of a decline, so she donates it to researchers." }
    ] },
  { id: "c-lis3-02", title: "Beneath the Varnish: Confessions of a Painting Conservator", kind: "monologue",
    script: "People imagine my profession as a kind of glamorous detective work, and occasionally it is — but let me start with the sentence I say most often to visitors at the studio: my job is not to make paintings look new. It is to make them honestly old. The distinction took me years to feel in my hands, so let me unpack it.\nA four-hundred-year-old portrait arrives with a varnish gone brown as gravy, candle soot in the sky, and someone's Victorian repainting over the sitter's left hand. The temptation, and the expectation of many owners, is total transformation. But every mark on that surface is information. Strip too enthusiastically and you don't reveal the original; you erase the evidence of its life, and occasionally, in the worst cases of past centuries, the artist's own final glazes went into the cotton swab along with the dirt. Half my training was learning what not to touch.\nThe governing principle of modern conservation, and it would surprise most people, is reversibility. Everything I add — every retouching, every filling — must be removable by a future colleague with better tools and better knowledge than mine. We work in materials deliberately weaker than the original, in paints that dissolve in solvents the old layers can resist. That's not modesty as decoration; it's the structural humility of the field. We assume we are wrong about something, we just don't yet know what.\nAnd sometimes the detective work does arrive. Two years ago, cleaning a dull landscape attributed to a minor follower, I found under the overpaint a signature and a date that moved the picture up a century and into a different workshop entirely. The owner was delighted for about a day, until I explained that the honest thing was now a full technical study, which would take a year, rather than a quick sale. Not everyone wants the truth their picture has to offer.\nIf you take one thing from this talk, let it be this: when you next stand in a gallery, you are never looking at 'the past', pure and untouched. You are looking at a negotiation between centuries — the artist's hand, time's damage, and generations of people like me deciding, each with our era's confidence, what mattered enough to keep.",
    questions: [
      { q: "What does the speaker say is the core aim of her work?", options: ["To restore paintings to their original brand-new appearance.", "To let paintings show their age truthfully.", "To identify forgeries in public collections.", "To satisfy the expectations of a painting's owner."], answer: 1, explanation: "Her most-repeated sentence is that her job \"is not to make paintings look new. It is to make them honestly old\" — the opposite of total transformation." },
      { q: "What danger of over-cleaning does the speaker highlight?", options: ["The artist's own finishing layers can be removed along with the dirt.", "The canvas may tear under repeated rubbing.", "Owners may refuse to pay for the extra work.", "Victorian repainting may become permanently fixed."], answer: 0, explanation: "She says that in the worst cases \"the artist's own final glazes went into the cotton swab along with the dirt\" — over-cleaning erases original material, not just grime." },
      { q: "Why do conservators deliberately use weaker materials than the original?", options: ["Because stronger materials are prohibitively expensive.", "Because weak materials are easier to apply quickly.", "So that future specialists can undo today's work.", "So that owners can distinguish new paint from old."], answer: 2, explanation: "The governing principle is reversibility: everything added \"must be removable by a future colleague with better tools and better knowledge\", hence paints that dissolve where old layers resist." },
      { q: "How did the owner of the landscape react to the discovery beneath the overpaint?", options: ["With lasting gratitude for the increase in value.", "With initial pleasure that soon gave way to frustration.", "With disbelief that the signature was genuine.", "With immediate plans to donate it to a museum."], answer: 1, explanation: "The owner \"was delighted for about a day\" until told the honest course was a year-long technical study rather than a quick sale — pleasure turning to frustration." },
      { q: "What final idea does the speaker want the audience to remember?", options: ["Galleries should label restored paintings more clearly.", "Conservators of the past were careless compared with today's.", "Most paintings in galleries are too damaged to display honestly.", "A painting on display is the outcome of choices made across centuries."], answer: 3, explanation: "She closes by saying a gallery visitor sees \"a negotiation between centuries — the artist's hand, time's damage, and generations of people like me deciding... what mattered enough to keep\"." }
    ] },
  { id: "c-lis3-03", title: "Counter Proposals: Two Booksellers Debate Going Online", kind: "dialogue",
    script: "Ruth: Right, you've seen the figures. Foot traffic down nine per cent on last year, and the rent review's in March. I think we finally have to do it — proper online sales, the whole catalogue listed, postage deals, everything.\nAdam: I knew this was coming. Look, I'm not dismissing it out of hand, but do the arithmetic with me. Listing eleven thousand titles means photographing and describing eleven thousand titles. That's months of work, and meanwhile who's on the till?\nRuth: We start with the collectable stock, obviously — the two hundred books upstairs that sit there for years precisely because the one person in the country who wants each of them has never walked past our door. Online, that person finds us in ten seconds. That's not replacing the shop, it's rescuing the stock the shop can't sell.\nAdam: On the rare books, fine, you've half convinced me. My real worry is different, though. The minute we're online, we're competing on price with everyone, everywhere. In the shop, someone pays eight pounds because they're holding the book and they want it today. On a screen, they see it a click away for six fifty and we've lost them — or worse, we've taught our own regulars to check.\nRuth: Except our regulars already check, Adam. I watch them do it at the shelves, phones out. Pretending the comparison doesn't exist doesn't protect us from it.\nAdam: Hmm. That's fair, and it stung a bit. All right — but then let's be honest about what we're selling online, because it can't be atmosphere. It has to be trust. Accurate condition reports, honest grading, the kind of description collectors actually rely on. If we do that properly, we're not competing with the click-away copy at six fifty, because ours is the one they can believe.\nRuth: Now you're designing the thing you were against ten minutes ago.\nAdam: I'm designing the version of it I can live with. Trial run — the collectable stock only, six months, and we review the numbers before touching the general shelves. And you're doing the photography.\nRuth: Deal. You write the condition reports — nobody grades a spine as brutally as you.",
    questions: [
      { q: "What prompts Ruth to raise the idea of selling online?", options: ["Declining visitor numbers and an upcoming rent review.", "A competitor's successful website.", "Pressure from their regular customers.", "An offer of free photography services."], answer: 0, explanation: "Ruth opens with \"Foot traffic down nine per cent on last year, and the rent review's in March\" — the figures drive her proposal." },
      { q: "What is Adam's first objection?", options: ["Online buyers cannot be trusted to pay.", "The workload of listing the entire stock is enormous.", "The shop's regulars would feel betrayed.", "Postage costs would wipe out any profit."], answer: 1, explanation: "He asks Ruth to \"do the arithmetic\": listing eleven thousand titles \"means photographing and describing eleven thousand titles. That's months of work\"." },
      { q: "Why does Ruth think the collectable stock is suited to online selling?", options: ["It photographs more attractively than newer books.", "It is light enough to post cheaply.", "Its rare buyers are unlikely ever to visit the shop in person.", "It is stored upstairs where customers cannot browse."], answer: 2, explanation: "She says those books sit unsold \"precisely because the one person in the country who wants each of them has never walked past our door\", whereas online \"that person finds us in ten seconds\"." },
      { q: "How does Ruth counter Adam's fear about price comparison?", options: ["She proposes matching the lowest online price.", "She points out that customers already compare prices in the shop.", "She argues their prices are lower than competitors'.", "She suggests hiding prices until checkout."], answer: 1, explanation: "Ruth says \"our regulars already check... I watch them do it at the shelves, phones out. Pretending the comparison doesn't exist doesn't protect us from it\" — and Adam admits it stung." },
      { q: "What do the two booksellers finally agree on?", options: ["Listing the whole catalogue immediately.", "Abandoning the online plan until after the rent review.", "Selling atmosphere rather than books online.", "A limited six-month trial with the rare stock only."], answer: 3, explanation: "Adam proposes \"Trial run — the collectable stock only, six months, and we review the numbers before touching the general shelves\", and Ruth replies \"Deal\"." }
    ] },
  { id: "c-lis3-04", title: "Podcast: The Curious Rise of the Houseplant Economy", kind: "monologue",
    script: "Hello and welcome back to Root Causes, the show that digs into the businesses hiding in plain sight. Today: houseplants, an industry that has quietly grown into billions while the rest of retail was writing farewell notes to the high street.\nLet's begin with the puzzle. A houseplant is, commercially speaking, a terrible product. It's perishable, awkward to ship, and — here's the killer — it reproduces. Your customer can turn one purchase into ten gifts with a pair of scissors and a jar of water. By every rule of retail, this market should be tiny. Instead, it boomed, and the boom tells us more about the buyers than the plants.\nThe standard explanation is the one you've heard: younger generations, priced out of houses and delaying families, are directing their nurturing instincts at something achievable. There's real evidence for the ownership part — surveys do show plant spending concentrated among urban renters. But I'd treat the pop-psychology garnish with suspicion, because the same surveys show the fastest-growing group of buyers is actually the over-fifty-fives, who own homes and raised families and apparently just like ferns. Beware of any explanation that flatters a headline.\nWhat the industry did brilliantly, and this is the part I find genuinely instructive, was to reposition the product. Thirty years ago a houseplant was sold as decor — a green thing to fill a corner. Today it's sold as a practice. You don't buy a monstera; you take up plant care, with its rituals, its vocabulary, its online communities trading cuttings like currency. And a practice, unlike an ornament, generates repeat purchases forever: the pots, the feeds, the grow lights, the inevitable replacements for the victims. The plant is almost the loss leader for the lifestyle.\nOne warning note before I let you go. Booms attract extraction, and the rare-plant corner of this market has already had its speculative bubble — variegated cuttings changing hands for thousands, then crashing to a tenth of the price within two years as growers flooded the supply. If that pattern sounds familiar, it should. From tulips in the 1630s to tech stocks, it's the oldest graph in economics, this time with foliage. Next week: the strange afterlife of shopping centres.",
    questions: [
      { q: "Why does the presenter call the houseplant a 'terrible product'?", options: ["It is perishable, hard to ship, and customers can propagate it themselves.", "It appeals only to a narrow group of wealthy buyers.", "It is too cheap to generate any profit at all.", "It requires expensive advertising to sell."], answer: 0, explanation: "He lists the commercial flaws: \"perishable, awkward to ship, and — here's the killer — it reproduces\", letting one purchase become ten gifts." },
      { q: "What makes the presenter doubt the standard explanation for the boom?", options: ["Urban renters have stopped buying plants entirely.", "Plant spending is falling among younger buyers.", "The fastest-growing group of buyers does not fit the theory.", "No surveys have ever measured plant spending."], answer: 2, explanation: "He accepts the ownership data but notes \"the fastest-growing group of buyers is actually the over-fifty-fives, who own homes and raised families\" — contradicting the frustrated-nurturing story." },
      { q: "According to the presenter, how did the industry transform the market?", options: ["By breeding plants that cannot be propagated.", "By selling plant care as an ongoing activity rather than plants as decoration.", "By lowering prices below those of florists.", "By moving all sales into online communities."], answer: 1, explanation: "Thirty years ago a plant was \"sold as decor\"; today \"it's sold as a practice\" with rituals and communities — and \"a practice, unlike an ornament, generates repeat purchases forever\"." },
      { q: "What does the presenter mean by calling the plant 'almost the loss leader for the lifestyle'?", options: ["Plants are given away free with other purchases.", "Most plants die before generating any revenue.", "The real profits come from the accessories and habits around the plant.", "Retailers deliberately sell plants at a loss to beat rivals."], answer: 2, explanation: "The practice generates the ongoing spending — \"the pots, the feeds, the grow lights, the inevitable replacements\" — so the plant mainly opens the door to that stream of purchases." },
      { q: "Why does the presenter mention tulips in the 1630s?", options: ["To show that houseplant fashions repeat every few centuries.", "To place the rare-plant price bubble in a long tradition of speculation.", "To argue that flowers hold value better than foliage plants.", "To recommend tulips as a safer investment."], answer: 1, explanation: "After describing variegated cuttings crashing to a tenth of their price, he says \"From tulips in the 1630s to tech stocks, it's the oldest graph in economics, this time with foliage\" — the bubble follows a familiar speculative pattern." }
    ] },
  { id: "c-lis3-05", title: "Kitchen Table Summit: Should Mum's Recipes Become a Book?", kind: "dialogue",
    script: "Nadia: So I've counted them properly at last. Between the exercise books, the loose cards and the margins of that ruined atlas, Mum left about two hundred recipes. I think we should turn them into a proper book. Printed, bound, the lot.\nJoel: I love the idea in theory. It's the practice that worries me. Have you actually tried cooking from her notes? I attempted the lamb thing on Sunday. The instructions say, and I quote, 'enough flour, cook until it behaves'. Until it behaves, Nadia.\nNadia: That's exactly why it has to be done now, though. You and I can still translate 'until it behaves' because we stood in that kitchen and watched. The cousins' children won't have a clue. Every year we wait, more of the context dies with the people who remember it.\nJoel: Fair. But then what we're really writing isn't her book, it's our interpretation of her book. The moment I write 'two hundred grams of flour, simmer for forty minutes', I've replaced her voice with mine. There's a small dishonesty in that, and it bothers me.\nNadia: Unless we keep both. Her words on the left page, photographed from the actual cards — stains and all — and our tested, measured version on the right. Nobody's voice gets overwritten; the translation sits beside the original.\nJoel: That... actually dissolves my objection, and it's annoying how quickly you did it. All right, different problem: cost. Print runs, photography, editing. I looked into this for the choir's cookbook, remember, and it swallowed their whole fundraising pot.\nNadia: Which is why we don't do a print run. Print on demand — we upload it, the cousins order copies as they want them, and it costs us nothing but our time. This isn't a commercial venture, Joel. If we sell thirty copies inside the family, it's a triumph.\nJoel: And the testing? Two hundred recipes, each cooked until we're sure?\nNadia: We split them. And we start with the twenty everyone actually asks about — the festival dishes. If the project dies after those twenty, we've still saved what matters most.\nJoel: You've thought about this for longer than you're letting on, haven't you? Fine. I'll take the baking half. But I'm writing a footnote defending 'until it behaves'. It deserves to survive somewhere.",
    questions: [
      { q: "What problem does Joel identify with cooking from their mother's notes?", options: ["Most of the recipes have pages missing.", "The instructions rely on judgement rather than precise measures.", "The recipes were written in another language.", "The dishes require unobtainable ingredients."], answer: 1, explanation: "He quotes the lamb recipe's \"enough flour, cook until it behaves\" — instructions that assume the cook's judgement instead of quantities and times." },
      { q: "Why does Nadia insist the project must happen now?", options: ["The recipe cards are physically deteriorating.", "The cousins' children have asked for copies.", "The knowledge needed to interpret the recipes is fading with the people who hold it.", "A publisher has shown interest in the collection."], answer: 2, explanation: "Nadia says they \"can still translate 'until it behaves' because we stood in that kitchen and watched\", and \"Every year we wait, more of the context dies with the people who remember it\"." },
      { q: "What is Joel's concern about writing precise modern versions?", options: ["It would substitute their voice for their mother's.", "It would make the book too long to print.", "It would reveal family secrets to outsiders.", "It would make the dishes taste different."], answer: 0, explanation: "Joel says \"The moment I write 'two hundred grams of flour...', I've replaced her voice with mine. There's a small dishonesty in that\"." },
      { q: "How does Nadia resolve Joel's objection about authenticity?", options: ["By agreeing to leave the vaguest recipes out.", "By promising to record the cousins' memories instead.", "By letting Joel write the entire text himself.", "By presenting the original notes and the tested versions side by side."], answer: 3, explanation: "Her design puts \"Her words on the left page, photographed from the actual cards... and our tested, measured version on the right\" — Joel admits this \"dissolves my objection\"." },
      { q: "How do they plan to manage the scale of the task?", options: ["By hiring a professional food writer.", "By dividing the recipes and starting with the most requested dishes.", "By testing every recipe together over one summer.", "By asking each cousin to test ten recipes."], answer: 1, explanation: "Nadia says \"We split them. And we start with the twenty everyone actually asks about — the festival dishes\", and Joel takes the baking half." }
    ] },
  { id: "c-lis3-06", title: "Chasing the Dictionary: How New Words Earn Their Place", kind: "monologue",
    script: "The question I'm asked most often at dinner parties, once people discover I'm a lexicographer, is some version of: who let that word in? Said with real indignation, usually about a word the speaker's teenager uses. And my answer always disappoints them, so let me disappoint you all collectively tonight: nobody lets words in. There is no gate, and we are not guards.\nA dictionary, at least the kind I work on, is a record, not a rulebook. We include a word when the evidence says people use it — widely, durably, and in print or speech beyond its original niche. Those three tests matter, so let me linger on the middle one. Every year produces hundreds of glittering coinages that die by Christmas. We watch them the way a doctor watches a temperature chart. A word needs to survive, typically, several years of sustained use across different kinds of sources before we draft an entry. When people accuse us of chasing fashion, I point out that by the time a word enters our pages, it is usually about as fashionable as a word can cease to be.\nNow, the part of my job nobody asks about: the definitions of ordinary words. Anyone can define a new slang term, roughly. Try defining 'the'. Or 'set', which in our current edition runs to over four hundred senses and took one of my predecessors most of a decade. The glamour cases get the headlines, but the deep labour of lexicography is maintenance — noticing that 'literally' has been used to mean 'figuratively' for two centuries, including by Dickens, and recording that sense despite knowing the letters of complaint are already being written.\nAnd that brings me to the accusation behind the dinner-party question: that by recording a use, we approve it. We don't, any more than a thermometer approves of fever. But I understand the anger, truly. A dictionary is one of the few books people still treat as an authority, and when it describes the language as it is rather than as they were taught it should be, it feels like betrayal. My defence is simple. The language belongs to its speakers — all of them, including the teenagers. We just take the minutes.",
    questions: [
      { q: "How does the speaker respond to the question of who 'lets words in'?", options: ["By denying that any gatekeeping process exists.", "By naming the committee responsible for approvals.", "By blaming teenagers for lowering standards.", "By explaining that only printed words are admitted."], answer: 0, explanation: "His answer is \"nobody lets words in. There is no gate, and we are not guards\" — a dictionary is \"a record, not a rulebook\"." },
      { q: "What point does the speaker make about durability?", options: ["Words used mainly in speech can never qualify.", "A word must show sustained use over years before it earns an entry.", "Most new words survive longer than critics expect.", "Dictionary entries are deleted if a word falls out of use."], answer: 1, explanation: "He lingers on the middle test: hundreds of coinages \"die by Christmas\", and a word \"needs to survive, typically, several years of sustained use across different kinds of sources\" first." },
      { q: "Why does the speaker mention the word 'set'?", options: ["To show that short words are the most fashionable.", "To give an example of a word recently added to the dictionary.", "To illustrate that defining common words is the real hard labour.", "To criticise a predecessor for working too slowly."], answer: 2, explanation: "'Set' runs \"to over four hundred senses and took one of my predecessors most of a decade\" — an example that \"the deep labour of lexicography is maintenance\", not glamorous new slang." },
      { q: "Why does the speaker refer to Dickens?", options: ["To prove that great writers avoided the word 'literally'.", "To show that the disputed use of 'literally' has a long literary history.", "To argue that older novels need modern glossaries.", "To explain why complaint letters are usually ignored."], answer: 1, explanation: "He notes 'literally' \"has been used to mean 'figuratively' for two centuries, including by Dickens\" — the contested sense is old and well-attested, which is why it is recorded." },
      { q: "What comparison does the speaker use to reject the charge that recording a word means approving it?", options: ["A doctor watching a temperature chart.", "A guard deciding who may pass a gate.", "A thermometer registering a fever.", "A secretary taking minutes at a meeting."], answer: 2, explanation: "Answering the accusation directly, he says \"We don't, any more than a thermometer approves of fever\" — recording describes a state without endorsing it; the minutes image closes the talk but answers a different point about ownership." }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
