(function () {
var BANK = [
  { id: "c-lis4-01", title: "Green Between the Cracks: An Urban Planner on Pocket Parks", kind: "dialogue",
    script: "Host: My guest designs what she calls pocket parks — green spaces the size of a tennis court, squeezed into leftover corners of the city. Priya, why so small? Isn't a proper park better?\nPriya: The honest answer is that the proper park question is a luxury most neighbourhoods don't have. Large parks need large sites, and in a built-up district those simply don't exist — but a disused loading bay, a corner where a demolished building left a gap, the dead space beside a railway arch? Every district has a dozen of those. Small isn't the compromise; small is the opportunity.\nHost: Critics say these projects are cosmetic. A few benches and a flower bed don't change anyone's life.\nPriya: I used to half-believe that myself, until we measured it. The surprise in our data wasn't environmental — it was social. A pocket park within three minutes' walk changes behaviour in a way a grand park a bus ride away never does. Older residents in particular use it daily instead of monthly, and the park becomes where neighbours actually learn each other's names.\nHost: What's the biggest mistake cities make with them?\nPriya: Building them and walking away. A pocket park has no staff, no rangers, so if the council doesn't hand real responsibility — and a small budget — to a local group, the space is derelict again within two years. The design is maybe a fifth of the job. The arrangement for looking after it is the rest.\nHost: And your favourite site so far?\nPriya: A strip behind a bus depot that the residents fought us over — they wanted parking. We built the park anyway, which I'm not proud of as a process, and it taught me the lesson I now lead with: win the argument before the diggers arrive, or you've built a monument to your own stubbornness. It took three years and a lot of tea before that street forgave us, and the park only came alive when they took it over.",
    questions: [
      { q: "How does Priya respond to the suggestion that a large park would be better?", options: ["She argues that suitable large sites rarely exist in dense districts.", "She agrees but says large parks are too expensive to maintain.", "She claims small parks attract more wildlife than large ones.", "She says residents consistently prefer smaller spaces."], answer: 0, explanation: "She says large parks need large sites which \"simply don't exist\" in built-up districts, whereas every district has leftover corners — \"Small isn't the compromise; small is the opportunity\"." },
      { q: "What surprised Priya in her team's data?", options: ["Pocket parks improved air quality more than expected.", "The main measurable benefit was social rather than environmental.", "Younger residents used the parks more than older ones.", "Grand parks were used more often than pocket parks."], answer: 1, explanation: "\"The surprise in our data wasn't environmental — it was social\": a park within three minutes' walk changes daily behaviour and becomes \"where neighbours actually learn each other's names\"." },
      { q: "What does Priya identify as the biggest mistake cities make?", options: ["Choosing sites that are too close to railways.", "Spending too much of the budget on design.", "Failing to arrange ongoing local care for the space.", "Employing rangers the parks do not need."], answer: 2, explanation: "The mistake is \"building them and walking away\": without responsibility and a small budget handed to a local group, \"the space is derelict again within two years\"." },
      { q: "What proportion of the job does Priya say design represents?", options: ["Around a fifth.", "About half.", "Nearly all of it.", "A negligible amount."], answer: 0, explanation: "She says \"The design is maybe a fifth of the job. The arrangement for looking after it is the rest.\"" },
      { q: "What lesson did Priya draw from the bus depot site?", options: ["Parking demand should always take priority over green space.", "Community consent should be secured before construction begins.", "Parks near depots are unsuitable for older residents.", "Residents' objections usually disappear once a park is built."], answer: 1, explanation: "Having built over residents' objections, she \"now lead[s] with\" the lesson: \"win the argument before the diggers arrive, or you've built a monument to your own stubbornness\"." }
    ] },
  { id: "c-lis4-02", title: "The Words That Give You Away: A Forensic Linguist's Casebook", kind: "monologue",
    script: "When I tell people I'm a forensic linguist, they picture handwriting analysis, which is the one thing I don't do. My material is language itself — the choices of word, spelling and rhythm that identify a writer as surely as a gait identifies a walker. Let me start with the case that convinced the sceptics in my own field. A series of threatening letters, anonymous, printed, posted from different towns. The police had a suspect but nothing to hold him on. What convicted him, in the end, was a habit so small he could not have known he had it: he never once wrote 'anything' as a single word. It was 'any thing', two words, every time — in the letters, in his old workplace emails, in a complaint he'd filed years earlier. Individually, a coincidence. Combined with a dozen quieter habits, a signature.\nNow, a warning, because I give this talk partly to correct the television version of my work. Language evidence is probabilistic, not magical. I can say that two documents are consistent with the same author; I can very rarely say they must be. The responsible use of my discipline is exclusion — demonstrating that a confession supposedly dictated by a suspect contains constructions he demonstrably never uses, which has freed more people than my evidence has convicted, and I'm prouder of that side of the ledger.\nThe part of the job that keeps me awake is the newest: anonymised online abuse. The volume is enormous, the texts are short, and short texts are where my methods are weakest — a tweet simply doesn't contain enough choices to be distinctive. So my advice to young researchers entering the field is unfashionable: resist the pressure to promise certainty. Our credibility was built by admitting what we cannot do, and it will be spent, quickly, by anyone who forgets that.",
    questions: [
      { q: "What misconception about his work does the speaker correct at the start?", options: ["That forensic linguistics involves analysing handwriting.", "That linguists work mainly for the defence.", "That his evidence is never used in court.", "That he studies the way suspects walk."], answer: 0, explanation: "People \"picture handwriting analysis, which is the one thing I don't do\" — his material is language choices, not script; the gait reference is only an analogy." },
      { q: "What finally identified the writer of the threatening letters?", options: ["The towns the letters were posted from.", "A consistent two-word spelling of a common word.", "Fingerprints found on the envelopes.", "A confession made during police interview."], answer: 1, explanation: "The suspect \"never once wrote 'anything' as a single word. It was 'any thing', two words, every time\" — a tiny unconscious habit that, combined with others, formed a signature." },
      { q: "What does the speaker say about the strength of language evidence?", options: ["It can usually prove authorship beyond doubt.", "It is stronger than most physical evidence.", "It indicates probability rather than certainty.", "It is only accepted in a handful of countries."], answer: 2, explanation: "\"Language evidence is probabilistic, not magical\": he can say documents are consistent with the same author but \"very rarely\" that they must be." },
      { q: "Why is the speaker prouder of exclusion work?", options: ["It has cleared more people than his evidence has convicted.", "It requires more sophisticated statistical methods.", "It attracts greater respect from television producers.", "It pays better than prosecution work."], answer: 0, explanation: "Showing that a disputed confession contains constructions a suspect never uses \"has freed more people than my evidence has convicted, and I'm prouder of that side of the ledger\"." },
      { q: "Why does online abuse pose a particular problem for his methods?", options: ["The authors use software to disguise their style.", "The messages are too short to contain distinctive choices.", "The volume of texts makes them expensive to store.", "Courts refuse to accept evidence from the internet."], answer: 1, explanation: "Short texts \"are where my methods are weakest — a tweet simply doesn't contain enough choices to be distinctive\", and the volume of such cases is enormous." }
    ] },
  { id: "c-lis4-03", title: "Hot Desks, Cold Feet: Two Managers Argue over the Office Redesign", kind: "dialogue",
    script: "Sofia: You've seen the architect's plans, then. No assigned desks at all — everyone books a space each morning through the app. I think it's the push we need, and before you say it, yes, I know you hate it.\nMarcus: I don't hate it, I distrust it, which is different. Every hot-desking rollout I've watched promised collaboration and delivered a daily scramble for the seats by the window. And there's a cost nobody puts on the slide: people spend the first twenty minutes of every day re-establishing themselves — finding a desk, adjusting the chair, working out who's where. Multiply that across two hundred staff and we've bought ourselves a permanent morning of lost time.\nSofia: Against which, look at the utilisation report. On any given day, forty per cent of our desks are empty — people are with clients, on leave, working from home on the days we agreed. We are heating, lighting and insuring a floor and a half of furniture that nobody is sitting at. I can't defend that to the board, Marcus, and honestly, neither can you.\nMarcus: The forty per cent is real, I'll grant you that without a fight. My question is what we do with it. The architect's answer is fewer desks. Mine would be different space — meeting rooms you can actually book, quiet rooms for the calls everyone currently takes in the stairwell. Shrink the desks, yes, but spend the saving on the rooms we're actually short of, instead of on beanbags.\nSofia: Then we're closer than you think, because I'd trade the beanbags for phone booths tomorrow. What I won't move on is the teams sitting in fixed zones. The moment you draw team territories on the plan, you've rebuilt the old office with extra steps.\nMarcus: And that's where I dig in. Fine — no personal desks. But a team that can't sit together isn't a team, it's a mailing list. Give each team a home zone, unassigned seats within it, and I'll back the whole scheme at the board.\nSofia: Home zones, no assigned seats, savings spent on rooms. Put that counter-proposal in writing by Friday and we present it together.",
    questions: [
      { q: "What hidden cost of hot-desking does Marcus describe?", options: ["Higher spending on booking software.", "Time lost each morning as staff settle into new places.", "Increased sickness absence among senior staff.", "The expense of replacing chairs more often."], answer: 1, explanation: "He says people \"spend the first twenty minutes of every day re-establishing themselves\", which across two hundred staff is \"a permanent morning of lost time\" — a cost \"nobody puts on the slide\"." },
      { q: "What is the basis of Sofia's case for the redesign?", options: ["Staff have complained about the current layout.", "The architect has offered a discount this year.", "A large share of desks sits unused on any given day.", "Competitors have already moved to hot-desking."], answer: 2, explanation: "She cites the utilisation report: \"forty per cent of our desks are empty\", meaning the firm is \"heating, lighting and insuring a floor and a half of furniture that nobody is sitting at\"." },
      { q: "How would Marcus prefer to use the space freed by fewer desks?", options: ["Creating bookable meeting rooms and quiet rooms for calls.", "Installing more informal seating such as beanbags.", "Subletting the spare floor to another company.", "Expanding the staff canteen and social areas."], answer: 0, explanation: "His answer to the empty forty per cent is \"different space — meeting rooms you can actually book, quiet rooms for the calls everyone currently takes in the stairwell\", not beanbags." },
      { q: "What does Sofia refuse to accept?", options: ["Any reduction in the total number of desks.", "Spending the savings on phone booths.", "Presenting the plan to the board herself.", "Allocating fixed territorial zones to teams."], answer: 3, explanation: "\"What I won't move on is the teams sitting in fixed zones\" — drawing team territories would rebuild \"the old office with extra steps\". (Marcus later softens this to home zones with unassigned seats.)" },
      { q: "On what terms does Marcus agree to support the scheme?", options: ["Teams keep a shared zone containing unassigned seats.", "Every employee keeps one personal desk.", "The booking app is abandoned entirely.", "The redesign is postponed until next year."], answer: 0, explanation: "He digs in on togetherness, not ownership: \"Give each team a home zone, unassigned seats within it, and I'll back the whole scheme at the board\" — and Sofia accepts the compromise." }
    ] },
  { id: "c-lis4-04", title: "Podcast: The Ten-Day Journey of a Supermarket Rose", kind: "monologue",
    script: "Welcome back to Shelf Life, the programme that follows everyday products to their unlikely origins. Today: the supermarket rose, and a question I promise you've never asked at the checkout — how is it possible that a flower grown four thousand miles away costs less than one from a greenhouse an hour up the road?\nStart at the equator, because that's where your rose almost certainly began. The industry migrated decades ago to the high plateaus of East Africa and South America, and the reason isn't only wages, though wages matter. It's daylight. On the equator you get twelve reliable hours of intense light, every day of the year, free. A grower near London must build that sun out of glass and gas, and from November to February the heating bill alone can exceed every cost the equatorial farm faces put together.\nNow the clock starts, because a cut rose is dying from the second the knife touches it. Within hours it's chilled, graded and boxed; within a day it's on a night flight; and here's the detail that surprised me most in the research: it likely spends longer at the auction and distribution stage in the Netherlands — still the industry's crossroads — than in the air. Ten days after harvest, it's in your kitchen, and the whole system exists to steal back a few of those days for your vase.\nThe uncomfortable question is carbon, and the answer refuses to be simple. Air freight sounds indefensible until you run the numbers on heated glass: several studies have found the flown equatorial rose responsible for less carbon than the locally grown winter one, because months of heating outweigh a flight. Buying local is a good rule of thumb; in this industry, in January, the rule of thumb points the wrong way.\nWhat should trouble you more is water, because roses are thirsty, and some growing regions cluster around lakes that whole communities also depend on. The certification labels on the wrapper actually mean something here — they audit water use and wages both — so for once, the small print is where your power is. Next week: the improbable voyage of the vanilla pod.",
    questions: [
      { q: "According to the presenter, what is the decisive natural advantage of equatorial growers?", options: ["Consistent intense daylight all year round.", "Soil that requires no fertiliser.", "Proximity to major flower auctions.", "A complete absence of plant diseases."], answer: 0, explanation: "The reason \"isn't only wages... It's daylight\" — twelve reliable hours of intense light every day, free, which a northern grower \"must build... out of glass and gas\"." },
      { q: "What surprised the presenter most in his research?", options: ["That roses are flown overnight rather than shipped.", "That flowers spend longer in distribution than in flight.", "That roses reach the shops within a single day.", "That the Netherlands no longer dominates the trade."], answer: 1, explanation: "\"Here's the detail that surprised me most\": the rose \"likely spends longer at the auction and distribution stage in the Netherlands... than in the air\"." },
      { q: "What does the presenter say about the carbon comparison?", options: ["Air freight always makes imported roses worse for the climate.", "No credible studies of the question exist.", "Flown equatorial roses can have a smaller footprint than local winter ones.", "The two options produce identical emissions."], answer: 2, explanation: "Studies \"have found the flown equatorial rose responsible for less carbon than the locally grown winter one, because months of heating outweigh a flight\" — the local rule of thumb \"points the wrong way\" in January." },
      { q: "What issue does the presenter suggest should concern listeners more than carbon?", options: ["The wages paid to airline staff.", "The pesticides used during transport.", "The declining quality of supermarket flowers.", "The pressure rose farms place on shared water sources."], answer: 3, explanation: "\"What should trouble you more is water\": roses are thirsty, and some growing regions \"cluster around lakes that whole communities also depend on\"." },
      { q: "Why does the presenter recommend checking certification labels?", options: ["They audit both water use and workers' pay.", "They guarantee the roses were grown locally.", "They indicate how long the flowers will last.", "They show which auction handled the flowers."], answer: 0, explanation: "The labels \"actually mean something here — they audit water use and wages both — so for once, the small print is where your power is\"." }
    ] },
  { id: "c-lis4-05", title: "Half a Plot Each: The Allotment Committee Faces Its Waiting List", kind: "dialogue",
    script: "Gwen: Right, item four, and it's the big one. The waiting list hit one hundred and ninety names this week. At current turnover that's a fourteen-year wait, Ray. People are joining it for their retirement while they're still at school, practically.\nRay: I know the number. And I know what you're going to propose, because it's what the federation newsletter has been pushing all year: split the plots. Halve every vacant plot as it comes up, two families where there was one.\nGwen: And you're against it because the old guard will revolt?\nRay: No — I'll surprise you. I'm for splitting, with one condition. My worry was never the revolt; it's the sheds and the water. Half plots mean twice the members, and our four taps and one track already can't cope on a bank holiday weekend. If we split without spending on infrastructure first, we're inviting eighty new members into a queue for a tap, and they'll leave angry within two seasons.\nGwen: The infrastructure money exists, as it happens. The council's community growing fund reopens in September, and half-plots actually strengthen the bid — they score it on households served, not square metres.\nRay: Then you've solved my objection and I'll move the motion myself. But I want us honest about the other thing, the thing nobody says at the AGM. A third of our current plots are barely cultivated. Old members holding land they can't work any more, out of pride, while a nurse with two kids waits fourteen years. The kind thing and the fair thing have stopped being the same thing, Gwen.\nGwen: Which is why I want cultivation checks twice a year — but paired with an offer, not a threat. Anyone struggling can downsize to a half plot with help moving, keep their fruit trees where possible, stay in the community. Nobody gets a warning letter before they've had a cup of tea and a conversation.\nRay: Tea before letters. Put that exact phrase in the policy, and you have my vote on the whole package.",
    questions: [
      { q: "What problem opens the discussion?", options: ["A waiting list so long that new applicants face a fourteen-year delay.", "A sudden fall in the number of allotment applications.", "The council's decision to close part of the site.", "A dispute between two long-standing members."], answer: 0, explanation: "Gwen reports the list has hit 190 names: \"At current turnover that's a fourteen-year wait\" — the meeting's central problem." },
      { q: "What is Ray's actual concern about splitting plots?", options: ["Long-standing members would resign in protest.", "The site's water supply and access could not support more members.", "Half plots are too small to grow anything worthwhile.", "The federation newsletter opposes the idea."], answer: 1, explanation: "He surprises Gwen: his worry \"was never the revolt; it's the sheds and the water\" — four taps and one track already can't cope, so splitting without infrastructure would create angry members." },
      { q: "Why does Gwen believe the funding bid would be helped by half plots?", options: ["The council prefers projects proposed by federations.", "Half plots are cheaper to connect to water.", "The fund assesses applications by the number of households served.", "The fund only supports sites with waiting lists."], answer: 2, explanation: "The community growing fund \"score[s] it on households served, not square metres\", so doubling the number of member households strengthens the application." },
      { q: "What uncomfortable issue does Ray insist they acknowledge?", options: ["The committee has been misusing its funds.", "Younger members neglect their plots more than older ones.", "The AGM minutes have not been published for years.", "Some members retain land they are no longer able to cultivate."], answer: 3, explanation: "He names \"the thing nobody says at the AGM\": a third of plots are barely cultivated because \"old members holding land they can't work any more, out of pride\", while others wait years." },
      { q: "How does Gwen propose handling under-cultivated plots?", options: ["Immediate warning letters followed by eviction.", "Inspections paired with a supportive offer to downsize.", "Raising the rent on any neglected plot.", "Transferring them directly to the nurse at the top of the list."], answer: 1, explanation: "She wants twice-yearly cultivation checks \"paired with an offer, not a threat\": help moving to a half plot, keeping fruit trees where possible — \"a cup of tea and a conversation\" before any letter." }
    ] },
  { id: "c-lis4-06", title: "Ninety Per Cent Sure: A Forecaster on the Language of Uncertainty", kind: "monologue",
    script: "I've spent thirty years forecasting the weather, and I want to talk tonight not about meteorology but about a communication failure — one my profession helped create and is still learning to fix.\nHere is the uncomfortable truth: our forecasts have never been better, and public trust in them has barely moved. The five-day forecast today is as accurate as the two-day forecast was when I started, an achievement I'd rank with anything in applied science. Yet the phrase 'they never get it right' survives every improvement. Why? Because of how people score us. When we say seventy per cent chance of rain and it stays dry, the public records a miss. But a seventy per cent forecast should be 'wrong' three times in ten — if it never failed, the number would be a lie. We taught people to hear certainty, then blamed them for hearing it.\nThe deeper problem is what listeners do with a percentage. Research found a good share of the public believes 'seventy per cent chance of rain' means it will rain over seventy per cent of the area, or for seventy per cent of the day. And honestly, why wouldn't they? We broadcast the number for decades without once explaining it.\nWhat actually works, we've found, is framing by consequence rather than by probability. Not 'thirty per cent chance of ice' but 'three mornings like this in ten, this road is lethal — leave ten minutes early'. Same information, but pointed at a decision, and people act on it. The forecast, it turns out, was never the product. The decision was.\nI'll leave you with the sentence I now give every trainee. The public does not need you to sound certain; it needs you to be useful, and the two are rivals more often than colleagues. Certainty is what we sound like when we've stopped respecting our audience. Usefulness is harder, quieter, and the only thing that has ever moved that stubborn trust number at all.",
    questions: [
      { q: "What paradox does the speaker highlight at the start?", options: ["Forecast accuracy has improved greatly while public trust has not.", "Forecasters trust their models less as they improve.", "Five-day forecasts are now less accurate than two-day ones.", "The public trusts forecasts more than forecasters do."], answer: 0, explanation: "\"Our forecasts have never been better, and public trust in them has barely moved\" — the five-day forecast now matches the old two-day one, yet \"they never get it right\" survives." },
      { q: "Why does the speaker say a seventy per cent forecast must sometimes 'fail'?", options: ["Because rain gauges cannot measure light rain reliably.", "Because if it never failed, the stated probability would be dishonest.", "Because forecasters deliberately overstate the risk of rain.", "Because the public prefers forecasts that are occasionally wrong."], answer: 1, explanation: "A seventy per cent forecast \"should be 'wrong' three times in ten — if it never failed, the number would be a lie\"; dry days are part of a correct probability, not a miss." },
      { q: "What misunderstanding of percentages does the research reveal?", options: ["People assume percentages refer to the forecaster's confidence.", "People think higher percentages mean heavier rain.", "People believe the figure describes how much of the area or day will be wet.", "People ignore any figure below fifty per cent."], answer: 2, explanation: "A good share of the public believes seventy per cent \"means it will rain over seventy per cent of the area, or for seventy per cent of the day\" — a reading the profession never corrected." },
      { q: "What change in wording does the speaker say actually works?", options: ["Replacing percentages with descriptive words like 'likely'.", "Giving separate figures for each hour of the day.", "Avoiding any mention of uncertainty on air.", "Linking the probability to a concrete decision listeners can take."], answer: 3, explanation: "Framing by consequence works: \"three mornings like this in ten, this road is lethal — leave ten minutes early\" — the same information \"pointed at a decision\", because \"the decision was\" the real product." },
      { q: "What is the message the speaker gives every trainee?", options: ["Sounding certain and being useful are usually in conflict.", "Audiences respect forecasters who never admit doubt.", "Trust figures should be ignored as unmeasurable.", "Usefulness matters less than scientific precision."], answer: 0, explanation: "\"The public does not need you to sound certain; it needs you to be useful, and the two are rivals more often than colleagues\" — usefulness, not performed certainty, moves trust." }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
