(function () {
var BANK = [
  { id: "c-lis2-01", title: "Blue Lights and Grey Areas: A Paramedic on Night-Shift Decisions", kind: "monologue",
    script: "People assume the hardest part of being a paramedic is the blood, and honestly, you get used to blood surprisingly fast. What you never quite get used to is the deciding. On a night shift, you're making judgement calls at three in the morning, on someone's kitchen floor, with maybe a tenth of the information a hospital doctor would have. And you have to make them quickly, because indecision is itself a decision — usually a bad one.\nLet me give you a flavour. We get called to an elderly man, chest pain, but by the time we arrive he's chatting away, insisting it was indigestion, begging us not to take him in because his wife has dementia and can't be left alone. Now, the protocol says chest pain of that sort goes to hospital, full stop. But protocols don't sit in the kitchen with you. So you're weighing a possible heart attack against the very real harm of leaving a confused woman alone at 4 a.m. What we actually did was ring the daughter, wait forty minutes for her to drive over, and then transport him. He'd had a minor cardiac event, as it turned out. Was the delay risky? A little. Was it right? I still think so.\nThe thing I'd want the public to understand is that we're not ambulance drivers — I do slightly bristle at that phrase — we're clinicians who happen to drive. The vehicle is the least of it. And the biggest change over my fifteen years isn't the equipment, though that's better; it's that maybe half our night calls now aren't emergencies in the classic sense at all. They're loneliness, anxiety, people who couldn't get a GP appointment. You can't defibrillate loneliness. So the skill I use most isn't anything from my training manual — it's working out, in about ninety seconds, what kind of problem I'm actually looking at. That, more than anything, is the job.",
    questions: [
      { q: "According to the speaker, what is the most difficult aspect of the job?", options: ["Coping with the sight of blood.", "Making judgement calls with limited information.", "Staying awake until three in the morning.", "Working without any hospital doctors nearby."], answer: 1, explanation: "他說血很快就習慣了，「What you never quite get used to is the deciding」，難的是在資訊只有醫院醫師十分之一的情況下快速做判斷。" },
      { q: "Why did the crew delay taking the elderly man to hospital?", options: ["He convinced them it was only indigestion.", "The protocol allowed a forty-minute wait.", "They needed someone to come and stay with his wife.", "They were waiting for a doctor's authorisation."], answer: 2, explanation: "他們打電話給女兒並等她開車過來照顧失智的太太，之後才送醫；並非相信是消化不良，事後證實是輕微心臟事件。" },
      { q: "How does the speaker feel about the phrase \"ambulance drivers\"?", options: ["He finds it mildly irritating.", "He accepts it as technically accurate.", "He thinks it flatters the profession.", "He uses it himself with patients."], answer: 0, explanation: "他說「I do slightly bristle at that phrase」，強調自己是會開車的臨床人員，車輛是最不重要的部分，可見該稱呼令他不快。" },
      { q: "What does the speaker identify as the biggest change over his fifteen years?", options: ["Equipment has improved beyond recognition.", "Night shifts have become far longer.", "Protocols have become stricter about chest pain.", "Many calls are no longer classic emergencies."], answer: 3, explanation: "他說最大的改變不是設備，「it's that maybe half our night calls now aren't emergencies in the classic sense」，而是孤獨、焦慮、掛不到門診的人。" },
      { q: "What does the speaker say is the skill he uses most?", options: ["Rapidly identifying what kind of problem he is facing.", "Applying techniques from his training manual.", "Operating a defibrillator under pressure.", "Persuading patients to accept transport."], answer: 0, explanation: "結尾說他最常用的技能不在訓練手冊裡，而是「working out, in about ninety seconds, what kind of problem I'm actually looking at」。" }
    ] },
  { id: "c-lis2-02", title: "Twelve Courses and Counting: Two Critics Cross Forks over Tasting Menus", kind: "dialogue",
    script: "Marta: Right, I'll say it plainly: the tasting menu has become a hostage situation. Three and a half hours, no choices, and a bill that could reservice a small car. We reviewed the same place last week, Theo — tell me you weren't checking your watch by course nine.\nTheo: I was checking my watch, I'll grant you that. But I'd frame it differently. A tasting menu is the one format where a chef can actually make an argument — a beginning, a middle, an end. Order à la carte and you've hired a cook; sit through a tasting menu and you've met an author.\nMarta: An author who won't let you leave the library! Look, I adore ambition, but somewhere along the way the format stopped serving diners and started serving egos. Half those courses last week existed so the kitchen could show off a technique, not because anyone wanted to eat them. The smoked celeriac thing — be honest.\nTheo: The celeriac was a misstep, fine. But you're judging the format by its worst indulgences. By that logic we'd dismiss the novel because some novels are bloated. And there's a practical case you're skating past: small kitchens can't do à la carte brilliantly. A fixed menu means no waste, precise ordering, and a team of four can genuinely compete with a brigade of twenty. For young chefs, it's not vanity — it's survival.\nMarta: That's the first argument tonight that's actually landed, I admit. The economics are real. But then be honest about it on the menu — say, this is how we keep the doors open — instead of dressing necessity up as a fourteen-course journey of the chef's childhood.\nTheo: Ha! All right, here's my compromise. Keep the format, but cap it — ninety minutes, eight courses, and every menu must offer an exit ramp, a shorter version, without any sneering from the waiters.\nMarta: The no-sneering clause might be the hardest to enforce. But yes — put that in the column, and for once we can share a byline.",
    questions: [
      { q: "What is Marta's central complaint about tasting menus?", options: ["The food is rarely cooked with technique.", "They remove the diner's freedom and take too long.", "Restaurants refuse to publish their prices.", "Chefs no longer write their own menus."], answer: 1, explanation: "她開頭說品嚐菜單成了「a hostage situation. Three and a half hours, no choices」還很貴，重點是剝奪選擇、時間過長。" },
      { q: "How does Theo defend the tasting menu format?", options: ["It lets a chef present a complete, authored argument.", "It guarantees diners a shorter overall meal.", "It allows customers to hire the cook directly.", "It gives diners more choices than à la carte."], answer: 0, explanation: "Theo 說品嚐菜單「is the one format where a chef can actually make an argument — a beginning, a middle, an end」，主廚像作者而非受僱廚師。" },
      { q: "What does Marta imply about the smoked celeriac course?", options: ["It was the best course of the evening.", "It was too small to judge fairly.", "It existed to display technique rather than to please diners.", "It should have appeared earlier in the meal."], answer: 2, explanation: "她說有一半菜色「existed so the kitchen could show off a technique, not because anyone wanted to eat them」，並點名 celeriac 要 Theo 誠實承認。" },
      { q: "Which of Theo's arguments does Marta accept?", options: ["That bloated novels are still worth reading.", "That waiters are usually polite about shorter menus.", "That fourteen-course menus reflect chefs' childhoods.", "That fixed menus make financial sense for small kitchens."], answer: 3, explanation: "Theo 說固定菜單零浪費、四人團隊也能競爭，Marta 回應「That's the first argument tonight that's actually landed... The economics are real」。" },
      { q: "What do the two critics finally agree on?", options: ["Tasting menus should be abolished entirely.", "A limited format with a shorter option should be offered.", "Restaurants should return to à la carte only.", "Their reviews should always be written separately."], answer: 1, explanation: "Theo 提議保留形式但限九十分鐘、八道菜並提供較短版本，Marta 同意「put that in the column, and for once we can share a byline」。" }
    ] },
  { id: "c-lis2-03", title: "Interview: The Quiet Art of Keeping Bridges Standing", kind: "dialogue",
    script: "Host: My guest today is Ingrid Halvorsen, who has spent thirty years inspecting and maintaining bridges. Ingrid, you once said your ambition is to be completely forgettable. Explain that.\nIngrid: Well, think about when a bridge makes the news. It's never good, is it? If people are talking about my work, something has gone terribly wrong. Maintenance is the art of the non-event. My proudest achievements are the disasters that never happened, and by definition nobody thanks you for those.\nHost: Walk us through an inspection. I imagine lots of high-tech scanning these days?\nIngrid: There's some, and it's genuinely useful — drones for the places we'd once have needed ropes, sensors that listen for changes in vibration. But I'll tell you a slightly heretical thing: the most reliable instrument I carry is still a small hammer. You tap the steel and you listen. Healthy metal rings; corroded metal gives this dull, disappointing thud. A sensor gives you a number, but a number needs interpreting, and interpretation needs experience. The technology extends my senses. It doesn't replace the judgement.\nHost: What's the biggest threat to our bridges, then? Age?\nIngrid: Age is manageable — we know how materials degrade, more or less. The threat that genuinely worries me is political, not structural. Maintenance budgets are the easiest thing in the world to cut, because the consequences arrive years later, on someone else's watch. A politician gets a ribbon-cutting for a new bridge; nobody has ever held a ceremony for a repainted one. So we systematically underfund the unglamorous work, and then act surprised when it catches up with us.\nHost: That sounds bleak. Any grounds for optimism?\nIngrid: Actually, yes, and it's the young engineers. When I started, maintenance was where careers went to stall — everyone wanted to design new landmarks. The graduates I meet now genuinely want to extend the life of what exists. They see it, rightly, as a climate question: the greenest bridge is almost always the one that's already built. That shift in attitude, more than any gadget, is what gives me hope.",
    questions: [
      { q: "Why does Ingrid want her work to be \"forgettable\"?", options: ["She dislikes speaking to journalists about it.", "Bridges only attract attention when something has failed.", "She believes engineers should stay anonymous by law.", "Her achievements have never been recognised by anyone."], answer: 1, explanation: "她說橋上新聞「It's never good」，維護是「the art of the non-event」，最自豪的是從未發生的災難，所以被記住反而代表出事。" },
      { q: "What point does Ingrid make with the small hammer?", options: ["Old tools are cheaper than drones and sensors.", "Modern sensors frequently give false numbers.", "Technology supports but cannot replace expert judgement.", "Steel bridges no longer need electronic monitoring."], answer: 2, explanation: "她說感測器給的數字仍需詮釋，「The technology extends my senses. It doesn't replace the judgement」，鎚子代表經驗判斷的不可取代。" },
      { q: "According to Ingrid, why are maintenance budgets so often cut?", options: ["The negative effects only appear much later.", "New materials have made maintenance unnecessary.", "Engineers ask for more money than they need.", "Repainting bridges has become far too expensive."], answer: 0, explanation: "她說預算最容易砍是因為「the consequences arrive years later, on someone else's watch」，後果多年後才浮現，且落在別人任內。" },
      { q: "What does Ingrid suggest by contrasting ribbon-cuttings with repainted bridges?", options: ["New bridges are usually painted at their opening.", "Ceremonies should be banned for public works.", "Politicians secretly prefer maintenance projects.", "Unglamorous work receives no political reward."], answer: 3, explanation: "「A politician gets a ribbon-cutting for a new bridge; nobody has ever held a ceremony for a repainted one」，對比說明不起眼的維護工作得不到政治回報而被長期低估。" },
      { q: "What gives Ingrid the most hope for the future?", options: ["New graduates now value extending existing structures.", "Governments have started funding climate gadgets.", "Landmark design has finally gone out of fashion.", "Maintenance careers now pay better than design."], answer: 0, explanation: "她說現在的畢業生「genuinely want to extend the life of what exists」，並視之為氣候議題，「That shift in attitude... is what gives me hope」。" }
    ] },
  { id: "c-lis2-04", title: "Podcast: Press Start to Parler — Can Video Games Teach You a Language?", kind: "monologue",
    script: "Hello and welcome back to Tongue Tied, the show about how people actually learn languages, as opposed to how textbooks think they should. Today's episode: gaming, and whether all those hours online are secretly a classroom.\nLet me start with a confession. I was sceptical about this one. The stereotype writes itself, doesn't it — teenagers absorbing nothing but insults and slang. But when I started interviewing learners for this episode, a pattern emerged that I couldn't dismiss. Person after person — a Finnish nurse, a Brazilian programmer, a retired French teacher, of all people — told me the same story: school gave them grammar, but games gave them the nerve to actually speak.\nAnd I think the mechanism is worth unpacking, because it isn't really about vocabulary. What games provide, almost uniquely, is stakes without consequences. In a classroom, making a mistake costs you face; everyone's watching, and the only point of the exercise is your accuracy. In a raid with five strangers, nobody cares about your past tense — they care whether you said heal me in time. The language stops being the object of attention and becomes a tool, and that shift, according to most acquisition research, is precisely where fluency lives.\nNow, before anyone cancels their evening class, the honest caveats. Game language is narrow. You'll become magnificent at coordinating an ambush and hopeless at, say, renting a flat. Several interviewees admitted their vocabulary was, let's say, tactically skewed. And the written word barely features — one gamer told me he could argue strategy in fluent spoken German but couldn't write a postcard in it.\nSo my verdict, for what it's worth: games are a superb gym for one specific muscle — real-time, high-pressure speaking — and a poor substitute for everything else. The learners who flourished treated gaming as a supplement, not the syllabus. Next week: why singing in the shower might do more for your accent than any app. Don't miss it.",
    questions: [
      { q: "How did the presenter initially feel about gaming as a language tool?", options: ["Doubtful, until interviews changed the picture.", "Enthusiastic because of personal experience.", "Neutral, since no research existed.", "Convinced it only taught insults and slang."], answer: 0, explanation: "他自白「I was sceptical about this one」，也提到刻板印象，但訪談中反覆出現的模式讓他無法忽視，態度因此轉變。" },
      { q: "What common story did the interviewees tell?", options: ["Games taught them grammar better than school did.", "School provided grammar, but games gave them confidence to speak.", "They abandoned formal classes after starting to play.", "Retired teachers make the fastest online learners."], answer: 1, explanation: "訪談者一個接一個說「school gave them grammar, but games gave them the nerve to actually speak」，學校給文法、遊戲給開口的勇氣。" },
      { q: "According to the presenter, what do games uniquely offer learners?", options: ["A larger vocabulary than any textbook.", "Teachers who correct mistakes instantly.", "Pressure to communicate without social penalty for errors.", "An audience that scores their accuracy."], answer: 2, explanation: "他說遊戲提供「stakes without consequences」：課堂上出錯丟臉，但隊友只在乎你有沒有及時喊 heal me，語言變成工具而非被檢視的對象。" },
      { q: "What limitation does the presenter acknowledge?", options: ["Gamers refuse to speak outside their teams.", "Games are too expensive to replace classes.", "Online language is impossible to research.", "The language learned is narrow and rarely written."], answer: 3, explanation: "他坦承「Game language is narrow」，會指揮突襲卻不會租房子，且「the written word barely features」，有人能用德語辯論戰術卻寫不了明信片。" },
      { q: "What is the presenter's final verdict on gaming for language learning?", options: ["It should replace evening classes for most people.", "It is valuable as a supplement, not a full course.", "It only works for spoken German.", "It benefits pronunciation more than speaking."], answer: 1, explanation: "結論是遊戲是訓練即時口說的「superb gym for one specific muscle」，成功的學習者「treated gaming as a supplement, not the syllabus」。" }
    ] },
  { id: "c-lis2-05", title: "The Spreadsheet Summit: Two Housemates Talk Money", kind: "dialogue",
    script: "Nadia: Okay, Josh, I've made tea, I've opened the spreadsheet, and I promise I'm not ambushing you. But we do need to sort the house money out properly, because the current system — which, let's be honest, is vibes — isn't working.\nJosh: That's fair. Though in my defence, the vibes worked fine for the first six months.\nNadia: They did, until the boiler broke and we spent a genuinely awkward week deciding whose turn it was to be three hundred pounds poorer. So, proposal one: a joint house account. We each pay in a fixed amount monthly, all bills and shared food come out of it, done.\nJosh: Mm. I want to like it, but here's my hesitation — and it's not about trusting you, it's the fixed amount. My freelance income swings around. Some months a set payment is nothing; other months it lands right when three invoices are late. A rigid system that ignores that isn't fairness, it's just tidiness.\nNadia: Okay, that's a real point, not an excuse — noted. Counter-proposal, then. We keep the joint account for the predictable stuff, rent and bills, because those don't care about your invoices either. But we split them proportionally to income, not fifty-fifty. I earn more; I pay more. And we review the split every six months.\nJosh: Honestly, that's generous, and my pride wants to refuse it.\nNadia: Your pride didn't refuse my lasagne all winter.\nJosh: Fair. Wounding, but fair. Okay — proportional split, yes. But then let me push back on one thing: the shared food budget. I'd rather keep groceries separate, because we shop so differently. You meal-plan like a military operation; I buy sad reduced sandwiches at ten pm. A shared food pot means I'm effectively subsidised, and that will make me weird about it.\nNadia: Fine — groceries stay separate, joint account covers rent, bills, and a small repairs fund so no boiler ever humiliates us again. Twenty a month each into repairs?\nJosh: Twenty-five. If we're doing this, let's actually be covered.\nNadia: Look at you, out-budgeting me. Deal. And Josh — thanks for not treating this as an ambush.",
    questions: [
      { q: "Why does Nadia want to change the current arrangement?", options: ["Josh has stopped paying his share of rent.", "The informal system failed when a big expense arrived.", "The landlord now demands one single payment.", "She wants to stop cooking shared meals."], answer: 1, explanation: "她說現在的制度是「vibes」，鍋爐壞掉時兩人尷尬了一週不知誰該付三百鎊，可見無明確規則的做法在大額支出時失靈。" },
      { q: "What is Josh's objection to a fixed monthly payment?", options: ["His irregular freelance income makes it hard some months.", "He does not trust joint accounts in principle.", "He believes Nadia should pay all the bills.", "He thinks fixed payments are too tidy to track."], answer: 0, explanation: "他說「My freelance income swings around」，固定金額有些月份剛好撞上發票遲付，「A rigid system that ignores that isn't fairness」。" },
      { q: "What does Nadia propose in response to Josh's concern?", options: ["Cancelling the joint account idea entirely.", "Letting Josh skip payments when invoices are late.", "Splitting fixed costs in proportion to their incomes.", "Paying all the bills herself for six months."], answer: 2, explanation: "她提出「we split them proportionally to income, not fifty-fifty. I earn more; I pay more」，並每半年檢討一次比例。" },
      { q: "Why does Josh want groceries kept out of the joint account?", options: ["He dislikes Nadia's military-style meal plans.", "He wants to hide how much he spends on food.", "Nadia refuses to eat reduced-price food.", "Their different shopping habits would leave him feeling subsidised."], answer: 3, explanation: "他說兩人買菜方式差太多，共用伙食金「means I'm effectively subsidised, and that will make me weird about it」，是心理上過意不去而非嫌棄對方。" },
      { q: "What do the housemates finally agree on?", options: ["A joint account for rent, bills and a repairs fund, with separate groceries.", "A fifty-fifty split of every household cost.", "Separate accounts for everything including rent.", "A repairs fund of twenty pounds each per month."], answer: 0, explanation: "最終方案是共同帳戶付房租、帳單與維修基金，伙食各自負擔；維修金額 Josh 主動加碼到二十五鎊，故二十鎊選項是干擾項。" }
    ] },
  { id: "c-lis2-06", title: "The Line Less Travelled: Bringing Regional Railways Back to Life", kind: "monologue",
    script: "Good evening, everyone. I want to talk about branch lines — those small regional railways that were closed in their hundreds across Europe in the sixties and seventies, and which communities like this one are now trying to bring back. I've been involved in three reopening campaigns, one successful, and I'll be honest about the other two as well.\nFirst, the case against, because you'll hear it and it deserves a straight answer. Critics say these lines closed because nobody used them, so reopening is nostalgia on rails. And here's the uncomfortable truth: they're half right. If you reopen a line and simply run the 1960s timetable — two trains a day at inconvenient hours — you will get 1960s passenger numbers, and the critics will be proved right at enormous public expense. That's essentially what sank our first campaign, in the Vale of Merton. We fought for the track and forgot to fight for the service.\nWhat changed everything in the successful case, the Aldenford line, was flipping the question. We stopped asking, how do we get our railway back, and started asking, what journeys do people around here actually need to make? It turned out the answer wasn't the market town the old line served — it was the hospital and the college two miles beyond it. So we campaigned for an extended route, hourly trains from early morning, and crucially, a bus that met every single arrival. Ridership beat the forecast within eighteen months, and it's still climbing.\nAnd the benefits, I should stress, weren't mainly about transport. House-hunters started shortlisting villages they'd previously never heard of. Two employers cited the line, unprompted, in their relocation decisions. A railway, it turns out, is less like a bus route and more like a signal — it tells the outside world a place has a future.\nSo my message tonight is simple. By all means, love your old railway. But don't campaign for the past. Count the journeys people need today, design the service around them, and let the nostalgia be a bonus rather than the business case.",
    questions: [
      { q: "How does the speaker respond to critics of reopening branch lines?", options: ["He dismisses their argument as pure nostalgia.", "He concedes they are partly correct.", "He accuses them of exaggerating the costs.", "He says passenger numbers prove them wrong everywhere."], answer: 1, explanation: "他說「here's the uncomfortable truth: they're half right」，若只照 1960 年代班表重開，就會得到當年的慘澹客量，批評者說中一半。" },
      { q: "Why did the Vale of Merton campaign fail, according to the speaker?", options: ["The community focused on the track but neglected the service.", "The government refused to fund any track repairs.", "Local residents opposed the reopening plan.", "The old station buildings had been demolished."], answer: 0, explanation: "他說「We fought for the track and forgot to fight for the service」，只爭取到鐵軌卻沒爭取像樣的班次，重蹈兩班車的覆轍。" },
      { q: "What was the key change of approach in the Aldenford campaign?", options: ["Hiring professional lobbyists to press the case.", "Restoring the original 1960s route exactly.", "Starting from the journeys people actually needed.", "Replacing the planned trains with buses."], answer: 2, explanation: "他們把問題從「how do we get our railway back」翻轉為「what journeys do people around here actually need to make」，據此延伸路線到醫院與學院。" },
      { q: "What does the speaker mean by calling a railway \"a signal\"?", options: ["Its signalling equipment attracts engineering firms.", "It warns house-hunters away from remote villages.", "It operates more punctually than any bus route.", "It communicates that a place has prospects."], answer: 3, explanation: "他說鐵路「tells the outside world a place has a future」，購屋者與雇主因此青睞當地，重點是象徵意義而非號誌設備。" },
      { q: "What is the speaker's concluding advice to the audience?", options: ["Design services around present-day needs rather than the past.", "Abandon nostalgia for old railways completely.", "Campaign first for the original market-town route.", "Treat the business case as a bonus to nostalgia."], answer: 0, explanation: "結語是「don't campaign for the past. Count the journeys people need today, design the service around them」，懷舊只能是附帶收穫而非商業理由。" }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
