(function () {
var BANK = [
  { id: "c-lis1-01", title: "Interview: Behind the Scenes with a Festival Logistics Director", kind: "dialogue",
    script: "Host: With me today is Carla Mendes, logistics director for the Ashfield Music Festival, which somehow manages to move eighty thousand people onto a farm every summer without descending into chaos. Carla, how on earth does that work?\nCarla: Well, the honest answer is that it doesn't, not entirely. Something always goes wrong — the trick is making sure the audience never notices. People imagine my job is about trucks and tents, and yes, there's plenty of that, but really it's about anticipating failure. I spend most of the year asking, what if this breaks, what if that supplier lets us down.\nHost: Give us an example of a near-disaster, then.\nCarla: Oh, gladly. Two years ago our main water contractor pulled out ten days before the gates opened. Ten days! Now, on paper we had a backup supplier, but they could only cover half the demand. So we ended up ringing every farm within twenty miles asking to borrow bowsers — those big water tanks. The local farmers absolutely saved us, and honestly, that taught me more than any contract ever has. Relationships beat paperwork every time.\nHost: There's a perception that festivals are terribly wasteful. Fair?\nCarla: I'd say it was fair a decade ago. These days the pressure from ticket-holders is enormous, and rightly so. We've banned single-use tents from our campsites — people used to abandon thousands of them — and we now reuse about seventy per cent of our site infrastructure year on year. I'm not claiming we're perfect, far from it, but the direction of travel is genuine, not just marketing gloss.\nHost: And what keeps you up at night these days?\nCarla: Weather, always weather. You can negotiate with a supplier; you can't negotiate with a storm. We model rainfall scenarios obsessively now, because one flooded car park generates more complaints than every other problem combined. If I could control one thing, it wouldn't be budgets — it'd be the sky.",
    questions: [
      { q: "According to Carla, what is the essence of her job?", options: ["Managing trucks and tents on site.", "Preparing for things that might go wrong.", "Keeping the audience entertained during delays.", "Negotiating annual contracts with suppliers."], answer: 1, explanation: "Carla says her job \"really it's about anticipating failure\" — she spends the year asking what could break; trucks and tents are the surface impression she explicitly rejects." },
      { q: "What did Carla learn from the water contractor incident?", options: ["Backup suppliers should always cover full demand.", "Contracts must be signed earlier in the year.", "Personal relationships matter more than formal agreements.", "Farms are unsuitable venues for large festivals."], answer: 2, explanation: "The local farmers saved them, and she concludes \"Relationships beat paperwork every time\" — personal relationships matter more than formal contracts." },
      { q: "How does Carla respond to the claim that festivals are wasteful?", options: ["She admits it was once true but says things have changed.", "She dismisses it as media exaggeration.", "She argues audiences are the ones causing the waste.", "She claims her festival has completely solved the problem."], answer: 0, explanation: "She says \"I'd say it was fair a decade ago\", then cites improvements like banning single-use tents, adding \"I'm not claiming we're perfect\" — admitting it was once true but has changed." },
      { q: "What does Carla imply about the festival's environmental efforts?", options: ["They are mainly designed as marketing gloss.", "They were forced on the festival by regulators.", "They are sincere even though incomplete.", "They have doubled the cost of infrastructure."], answer: 2, explanation: "She says \"the direction of travel is genuine, not just marketing gloss\" — the efforts are sincere though incomplete; 'marketing gloss' is exactly the claim she denies." },
      { q: "Why does weather worry Carla more than anything else?", options: ["It cannot be influenced by negotiation.", "It has ruined the budget in previous years.", "Storms have forced the festival to cancel twice.", "Rainfall models are too expensive to run."], answer: 0, explanation: "She says \"You can negotiate with a supplier; you can't negotiate with a storm\" — the point is that weather cannot be controlled by negotiation, not budgets or past cancellations." }
    ] },
  { id: "c-lis1-02", title: "Office Debate: Should We Trial a Four-Day Week?", kind: "dialogue",
    script: "Dan: So you've seen the memo, then. Management want volunteers for the four-day week trial. I've already put my name down, obviously.\nPriya: Obviously. Look, I'm not against it in principle — who wouldn't want Fridays back — but I've read the small print, and it's the same salary for the same output in four days. That's not a gift, Dan, that's compression.\nDan: Isn't that the whole point, though? The research from those trials in Iceland and the UK suggests output doesn't actually drop. People cut the padding — the meetings that could've been emails, the aimless scrolling. You work with more intention when the clock's tighter.\nPriya: For some roles, sure. If your work is project-based, you can squeeze it. But I run client support. My clients don't compress their problems into four days to suit my schedule. Someone still has to answer the phone on Friday, and I can tell you now it'll be my team drawing the short straw.\nDan: Fair enough, but the memo does mention staggered days — half the team off Monday, half off Friday. Coverage doesn't disappear.\nPriya: In theory. In practice, staggering means the one colleague who knows the answer is always the one who's off. And here's my other worry — the trial itself. Everyone will sprint for six months to make the numbers look good, management will declare victory, and then we're stuck delivering sprint-level output forever. Trials aren't neutral; people perform for them.\nDan: That's... actually a decent point. Though you could flip it — if we don't trial it, we'll never get it at all. I'd rather risk an imperfect version than wait for a perfect one that never arrives.\nPriya: Hmm. Look, I'm not saying refuse. I'm saying negotiate the terms first — proper coverage rules, and a review that measures burnout, not just output. Get that in writing and I'll sign up next to you.\nDan: Deal. You draft the demands, I'll charm the steering group.",
    questions: [
      { q: "What is Priya's initial objection to the trial?", options: ["She believes salaries should rise under the new scheme.", "She thinks it simply squeezes the same work into fewer days.", "She objects to losing her Fridays off.", "She doubts the research from Iceland was real."], answer: 1, explanation: "Priya says \"same salary for the same output in four days. That's not a gift, that's compression\" — the work is merely squeezed, not a benefit." },
      { q: "How does Dan justify his support for the four-day week?", options: ["Evidence suggests productivity is maintained as waste is cut.", "Meetings will be replaced entirely by emails.", "Management has promised extra pay for volunteers.", "Other companies force employees to join such schemes."], answer: 0, explanation: "Dan cites the Iceland and UK trials: \"output doesn't actually drop. People cut the padding\" — productivity holds while wasted time is trimmed." },
      { q: "Why does Priya think her team is a special case?", options: ["Her team already works staggered days.", "Her team's projects are easy to compress.", "Client demands do not fit a four-day schedule.", "Her clients only contact her on Fridays."], answer: 2, explanation: "She says \"My clients don't compress their problems into four days to suit my schedule\" — client-support demands don't fit a four-day week; someone must answer the phone on Friday." },
      { q: "What does Priya fear about the trial period itself?", options: ["Management will cancel it after six months.", "Colleagues will refuse to take part in it.", "The steering group will ignore the numbers.", "An unsustainable pace will become the permanent standard."], answer: 3, explanation: "She fears everyone will sprint for six months and then \"we're stuck delivering sprint-level output forever\" — the trial pace becomes the permanent standard." },
      { q: "By the end of the conversation, what have the two colleagues agreed to do?", options: ["Refuse to volunteer until salaries are raised.", "Push for better conditions before joining the trial.", "Report the memo's flaws to their clients.", "Let Dan join while Priya stays out entirely."], answer: 1, explanation: "Priya says \"negotiate the terms first... Get that in writing and I'll sign up\" and Dan replies \"Deal\" — they agree to secure conditions before joining, not to refuse or join separately." }
    ] },
  { id: "c-lis1-03", title: "When the Ice Fights Back: A Glaciologist's Field Notes", kind: "monologue",
    script: "People hear the word glaciologist and they picture something rather heroic — you know, squinting nobly into a blizzard, planting flags. The reality, I'm afraid, is mostly carrying batteries uphill and apologising to equipment. Let me tell you about my first season on the Vatnsdalur glacier, because nothing in my doctorate prepared me for it.\nOur main task that year was drilling shallow cores to read the last few decades of snowfall. Simple enough, on paper. Except the drill — a beautiful, expensive Swedish thing — turned out to despise the cold, which, when you think about it, is a fairly fundamental design flaw for glacier equipment. Below minus fifteen, the motor would sulk and stop. Our fix, and I'm not proud of this, was to take turns hugging it inside our jackets to keep it warm. Three PhDs, cuddling a drill. Science in action.\nThen there was the crevasse incident. Now, before anyone panics, nobody fell in — not a person, anyway. What fell was our lunch, an entire week's supply of chocolate and dried stew, when a sledge strap snapped at exactly the wrong moment. We stood at the edge watching our calories disappear into this gorgeous blue abyss, and my field partner said, very quietly, well, future glaciologists will core through that and wonder about the chocolate layer. That's field humour — it's how you cope.\nWhat I want you to take from these stories isn't that fieldwork is a comedy of errors, though it often is. It's that the mishaps are the methodology. Every failure forced us to improvise, and half of our lab's standard procedures today started life as an embarrassing workaround on the ice. The sensor housings we now publish about? They exist because a fox chewed our first cables. So when students ask me how to prepare for fieldwork, I tell them: pack spares, obviously, but more importantly, pack the humility to be outsmarted by weather, machinery, and the occasional fox.",
    questions: [
      { q: "What does the speaker suggest about the public image of glaciology?", options: ["It is far more glamorous than the everyday reality.", "It accurately reflects the dangers of blizzards.", "It underestimates how heroic the work truly is.", "It focuses too much on laboratory research."], answer: 0, explanation: "The speaker says people picture something \"heroic... planting flags\", but the reality \"is mostly carrying batteries uphill and apologising to equipment\" — far less glamorous than the image." },
      { q: "What was the problem with the Swedish drill?", options: ["It was too heavy to carry uphill.", "It stopped working in very low temperatures.", "It produced cores that were too shallow.", "It had been damaged during shipping."], answer: 1, explanation: "He says \"Below minus fifteen, the motor would sulk and stop\" — the drill failed in extreme cold, a fundamental design flaw for glacier equipment." },
      { q: "How did the team deal with the drill's fault?", options: ["They sent it back to the manufacturer.", "They replaced its motor with a spare.", "They warmed it with their own body heat.", "They only drilled on warmer afternoons."], answer: 2, explanation: "The fix was to \"take turns hugging it inside our jackets to keep it warm\" — three PhDs warming the drill with their own body heat." },
      { q: "Why does the speaker mention his partner's remark about the chocolate layer?", options: ["To prove the crevasse was too deep to explore.", "To criticise his partner's careless packing.", "To show that the food could still be recovered.", "To illustrate how humour helps researchers cope."], answer: 3, explanation: "After quoting his partner's joke that future glaciologists would wonder about the chocolate layer, he says \"That's field humour — it's how you cope\" — the point is humour as a coping mechanism." },
      { q: "What is the speaker's main message about fieldwork mishaps?", options: ["They can be avoided with careful preparation.", "They often lead directly to better methods.", "They show that expensive equipment is a waste.", "They discourage most students from continuing."], answer: 1, explanation: "He says \"the mishaps are the methodology\" — half the lab's standard procedures began as workarounds on the ice, so failures led directly to better methods." }
    ] },
  { id: "c-lis1-04", title: "Podcast: The Secret Economics of Second-Hand Books", kind: "monologue",
    script: "Welcome back to Margin Notes, the podcast about the book world's quieter corners. Today: the second-hand trade, which everyone assumes is dying and which, rather inconveniently for that narrative, keeps refusing to die.\nLet's start with the assumption itself. When e-readers arrived, the obituaries practically wrote themselves — who'd want a musty paperback when the entire library fits in your pocket? And yet used-book sales have actually grown over the past decade. Part of that is price, of course, especially for students. But the more interesting driver, I'd argue, is that a second-hand book is the one product that improves with a previous owner. A pencilled note in the margin, a train ticket used as a bookmark — buyers tell dealers these traces are half the appeal. Try saying that about a used phone.\nNow, the economics are genuinely strange. The trade runs on what dealers call the long tail: a shop might hold twenty thousand titles, and most will sit unsold for years, subsidised by a handful of steady earners. What's shifted everything is the internet — but not in the way you'd think. Online platforms didn't kill the shops; they killed the mystery. Once anyone could check a book's price globally in ten seconds, the era of the lucky attic discovery mostly ended. Prices flattened. Dealers I've interviewed are quite wistful about it — one told me the internet made him more money and less joy, which might be the most honest sentence ever spoken about e-commerce.\nAnd the shops that survive? They've stopped competing on stock and started competing on atmosphere. The successful ones are effectively slow retail: armchairs, coffee, a proprietor who remembers what you bought last spring. You're not paying three pounds for a novel; you're paying for the hour you spent finding it. Whether that's a sustainable business or an elaborate form of hospitality, well, I'll let the accountants argue. Next week: the strange world of library sales.",
    questions: [
      { q: "What point does the presenter make at the start about the second-hand trade?", options: ["It has declined exactly as commentators predicted.", "It keeps surviving despite predictions of its death.", "It only survives thanks to e-reader users.", "It was never seriously threatened by technology."], answer: 1, explanation: "He opens by saying the trade is one \"everyone assumes is dying and which... keeps refusing to die\", with sales actually growing over the past decade — contrary to the obituaries." },
      { q: "According to the presenter, what is the most interesting reason buyers choose used books?", options: ["Traces left by previous owners add to the appeal.", "They are cheaper than any digital alternative.", "They are easier to resell than new books.", "They fit more conveniently in a pocket."], answer: 0, explanation: "He argues \"a second-hand book is the one product that improves with a previous owner\" — pencilled notes and old bookmarks are half the appeal; price is only part of the reason." },
      { q: "What does the phrase \"the long tail\" describe in this context?", options: ["The years a dealer waits before opening a shop.", "The queue of collectors outside popular shops.", "A few steady sellers supporting many slow-moving titles.", "The delay between buying and reselling a rare book."], answer: 2, explanation: "He explains the long tail as a shop holding twenty thousand titles, most unsold for years, \"subsidised by a handful of steady earners\" — a few sellers supporting many slow movers." },
      { q: "How did the internet actually change the trade, according to the presenter?", options: ["It forced most physical shops to close down.", "It made attic discoveries far more common.", "It raised prices for nearly every title.", "It removed the uncertainty that made bargains possible."], answer: 3, explanation: "He says online platforms \"didn't kill the shops; they killed the mystery\" — anyone can check global prices in ten seconds, so lucky attic finds ended and prices flattened." },
      { q: "What does the presenter suggest about the surviving bookshops?", options: ["They now sell the experience rather than just the stock.", "They rely mainly on selling coffee for profit.", "They have abandoned rare books for bestsellers.", "They are officially classified as hospitality businesses."], answer: 0, explanation: "He says surviving shops \"stopped competing on stock and started competing on atmosphere\" — you pay for the hour spent finding the book, i.e. the experience rather than the book itself." }
    ] },
  { id: "c-lis1-05", title: "Trading Places: City Mouse, Country Mouse", kind: "dialogue",
    script: "Leo: So, a year on from the great swap. You left Manchester for a village of four hundred people, I did the reverse. Any regrets?\nSam: Honestly? Fewer than I expected, but not zero. The silence took months to stop feeling eerie. I used to fall asleep to traffic, and suddenly the loudest thing at night was an owl with opinions. Now I can't imagine going back — but I'd be lying if I said it was the postcard fantasy either.\nLeo: Go on, puncture the fantasy for me.\nSam: The big one is logistics. Everything is a drive. The dentist is forty minutes away, the supermarket's twenty, and when my car broke down in February I was basically under house arrest for a week. Nobody puts that on the lifestyle blogs. But the flip side is real too — I know my neighbours' names, all of them, and when I was ill in spring, three separate people left food on my doorstep. In fifteen years in Manchester, I never once knew who lived above me.\nLeo: See, that's funny, because the anonymity is precisely what I'm enjoying. In the village where I grew up, everyone had a settled idea of who I was by the time I was twelve. In the city, nobody's watching, and that turns out to be freeing rather than lonely — at least for me. Plus, I'd forgotten what spontaneity feels like. Gig on a Tuesday? Just go. No planning committee required.\nSam: And the costs don't horrify you?\nLeo: Oh, they do. My flat is half the size of your cottage for twice the rent — I've done the maths and it stings. I tell myself I'm paying for options. Though I'll admit, most weeks I use about ten per cent of those options.\nSam: That's the trade in a nutshell, isn't it? I've got space and belonging but no choices; you've got infinite choices you barely touch.\nLeo: When you put it like that, we should probably swap back in a decade and compare notes again.",
    questions: [
      { q: "How does Sam feel about the move overall after a year?", options: ["Certain it was a mistake he cannot undo.", "Satisfied, while acknowledging it is not idyllic.", "Convinced the postcard fantasy came true.", "Eager to return to Manchester soon."], answer: 1, explanation: "Sam says \"Now I can't imagine going back — but I'd be lying if I said it was the postcard fantasy either\" — satisfied without idealising it, neither regretful nor eager to return." },
      { q: "What does Sam identify as the biggest drawback of village life?", options: ["The unsettling silence at night.", "Unfriendly neighbours who watch him.", "The dependence on driving for everything.", "The cost of maintaining a cottage."], answer: 2, explanation: "He says \"The big one is logistics. Everything is a drive\" — a forty-minute dentist trip, house arrest when the car broke down; the eerie silence was only an early adjustment." },
      { q: "Why does Leo value the anonymity of the city?", options: ["It frees him from others' fixed expectations.", "It helps him avoid paying for social events.", "It protects him from nosy landlords.", "It makes him feel pleasantly lonely."], answer: 0, explanation: "Leo says the village had a settled idea of him by age twelve, whereas in the city \"nobody's watching, and that turns out to be freeing rather than lonely\" — anonymity brings freedom." },
      { q: "What does Leo admit about the options city life offers?", options: ["They justify a rent lower than Sam's.", "They forced him to form a planning committee.", "They mostly involve Tuesday concerts.", "He rarely takes advantage of most of them."], answer: 3, explanation: "He admits \"most weeks I use about ten per cent of those options\" — he pays double the rent for options he rarely uses, and the maths stings." },
      { q: "How does Sam summarise the difference between their situations?", options: ["Both of them ended up with belonging but no space.", "Each gained something the other one gave up.", "Leo's choice was wiser than his own.", "Neither move changed their lives significantly."], answer: 1, explanation: "Sam sums up: \"I've got space and belonging but no choices; you've got infinite choices you barely touch\" — each gained what the other gave up, with no verdict on who chose better." }
    ] },
  { id: "c-lis1-06", title: "Small Visitors, Big Ideas: Designing Museum Exhibitions for Children", kind: "monologue",
    script: "Thank you all for coming. I've spent twenty years designing museum exhibitions for children, and I want to start by dismantling the phrase people always use about my work: dumbing down. The assumption is that a children's exhibition is an adult one with longer words removed. It's the opposite, actually. Designing for an eight-year-old is harder, because children are the most ruthless audience in existence. An adult will politely read a dull panel out of guilt. A child owes you nothing. If the exhibit doesn't earn their attention in about four seconds, they're gone, and no amount of curatorial prestige will bring them back.\nSo what does earn that attention? Not screens, interestingly — or not primarily. When we track children through galleries, the exhibits they return to are overwhelmingly physical: cranks, pulleys, things with satisfying weight and resistance. There's a lesson in that. A touchscreen is what they have at home. A hand-operated Victorian printing press is not.\nThe second principle, and this one surprises clients, is that you should design at two heights and two levels of meaning. The obvious part is physical — sightlines at a metre and at a metre seventy. The subtler part is intellectual. The best children's exhibits carry a layer for the accompanying adult, because children learn most when an adult alongside them is genuinely curious rather than supervising out of duty. If the parent is bored, the visit dies. We're not really designing for children; we're designing conversations between children and adults.\nAnd finally, a word about failure — the visitor's failure, I mean. We used to design interactives so that every child would succeed instantly, and we've rowed back on that, deliberately. An exhibit you master in one go is an exhibit you abandon in one go. A puzzle that resists a little, that requires a second and third attempt, holds a child four times longer, according to our observation data. Frustration, in careful doses, is a design material. Get the dose right and you haven't just filled an afternoon — you've taught persistence, in a building that never once said the word.",
    questions: [
      { q: "Why does the speaker object to the phrase \"dumbing down\"?", options: ["Because designing for children is in fact more demanding.", "Because children prefer longer and more complex words.", "Because adults never read exhibition panels anyway.", "Because the phrase was invented by rival curators."], answer: 0, explanation: "He says \"It's the opposite, actually. Designing for an eight-year-old is harder\" — children are the most ruthless audience, gone in four seconds, so it is anything but simplification." },
      { q: "What does the speaker say tracking data reveals about children in galleries?", options: ["They spend most time at large touchscreens.", "They are drawn back to hands-on mechanical exhibits.", "They ignore anything from the Victorian era.", "They follow their parents' route through the space."], answer: 1, explanation: "He says tracking data shows the exhibits children return to \"are overwhelmingly physical: cranks, pulleys\" — touchscreens are what they have at home; hands-on machinery is the draw." },
      { q: "Why should exhibits include a layer of meaning for adults?", options: ["Adults pay for the tickets and expect value.", "Museums must legally cater to all age groups.", "Children stay engaged when the adult with them is truly interested.", "Adults complain more loudly than children do."], answer: 2, explanation: "He says children learn most when \"an adult alongside them is genuinely curious rather than supervising out of duty\" — a bored parent kills the visit, so exhibits need an adult layer of meaning." },
      { q: "What change has the speaker's team made to interactive exhibits?", options: ["They removed all puzzles that children found frustrating.", "They ensured every child succeeds on the first try.", "They replaced physical puzzles with observation screens.", "They now build in a degree of difficulty on purpose."], answer: 3, explanation: "He says they used to let every child succeed instantly but \"we've rowed back on that, deliberately\" — puzzles that resist a little hold children four times longer, so difficulty is built in on purpose." },
      { q: "What is the speaker's concluding point about controlled frustration?", options: ["It can quietly teach children persistence.", "It should be avoided in public buildings.", "It works only for children over eight.", "It fills an afternoon but teaches nothing."], answer: 0, explanation: "He concludes that frustration in careful doses is a design material: \"you've taught persistence, in a building that never once said the word\" — it quietly teaches children to persevere." }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
