/* CAE Prep extra bank: part2 wave 4 */
(function () {
  var BANK = [
    { text: "The observatory was funded largely ____ public subscription.", answers: ["by", "through"], explanation: "'By public subscription' means paid for through donations collected from the public." },
    { text: "The inquiry laid the blame squarely ____ the shoulders of the contractors.", answers: ["on", "upon"], explanation: "The idiom is 'lay the blame on/upon someone's shoulders', meaning to hold them responsible." },
    { text: "The apprentices pick the craft up largely ____ watching the master at work.", answers: ["through", "by", "from"], explanation: "'Through/by watching' expresses the means by which something is learned." },
    { text: "____ the exception of the cloisters, the abbey is fully wheelchair accessible.", answers: ["with"], explanation: "The fixed phrase 'with the exception of' means 'apart from'." },
    { text: "The peace talks are in danger of collapse ____ the two sides even meeting.", answers: ["without"], explanation: "'Without + -ing' shows the action (meeting) has not happened; the talks may fail before any meeting takes place." },
    { text: "The soprano withdrew ____ the eleventh hour, citing a throat infection.", answers: ["at"], explanation: "'At the eleventh hour' is an idiom meaning at the last possible moment." },
    { text: "The pipeline runs the entire length of the island, much of it ____ ground.", answers: ["under", "below"], explanation: "'Underground/below ground' describes something buried beneath the surface; here written as two words after 'much of it'." },
    { text: "The summit yielded little ____ the way of concrete commitments.", answers: ["in"], explanation: "The fixed phrase 'little in the way of X' means hardly any X." },
    { text: "The castle keep dates ____ to the reign of the first Norman kings.", answers: ["back"], explanation: "The phrasal verb 'date back to' means to have existed since a particular time." },
    { text: "The documentary was turned ____ by every broadcaster before a streaming service picked it up.", answers: ["down"], explanation: "'Turn down' is a phrasal verb meaning to reject an offer or proposal." },
    { text: "Only later ____ it emerge that the painting had been swapped for a copy.", answers: ["did"], explanation: "After 'only later' at the start of a sentence, subject and auxiliary invert: 'only later did it emerge'." },
    { text: "Scarcely a month goes by ____ a new café opening on the high street.", answers: ["without"], explanation: "'Scarcely a week/month goes by without X happening' means X happens almost every week/month." },
    { text: "Seldom ____ the committee overturned a planning decision on appeal.", answers: ["has"], explanation: "Negative adverb 'seldom' at the front forces inversion with the auxiliary: 'seldom has the committee overturned'." },
    { text: "Not since the 1970s ____ inflation eaten into savings at such a pace.", answers: ["has"], explanation: "'Not since + time' triggers inversion; the present perfect auxiliary 'has' precedes the subject." },
    { text: "Never before ____ the regatta been cancelled two years running.", answers: ["had", "has"], explanation: "'Never before' fronted requires inversion; 'had/has been cancelled' fits depending on the time frame." },
    { text: "Nowhere ____ the safety briefing were life jackets mentioned.", answers: ["in"], explanation: "'Nowhere in the briefing' means at no point within it; the negative adverbial also triggers the inversion 'were life jackets mentioned'." },
    { text: "At no point ____ the defendant express any remorse.", answers: ["did"], explanation: "The fronted negative phrase 'at no point' requires inversion with the auxiliary 'did'." },
    { text: "It was not the money so much as the principle ____ drove her to sue.", answers: ["that"], explanation: "This is a cleft sentence: 'It was X that...' emphasises the true cause." },
    { text: "It is the volunteers ____ deserve the credit, not the trustees.", answers: ["who", "that"], explanation: "In a cleft sentence emphasising people, 'who' or 'that' introduces the relative clause." },
    { text: "What the village needs ____ not another gift shop but a working bakery.", answers: ["is"], explanation: "A 'what'-clause acting as subject takes a singular verb: 'What the village needs is...'." },
    { text: "____ began as a hobby has grown into a business employing forty people.", answers: ["what"], explanation: "'What' introduces a nominal relative clause meaning 'the thing that began as a hobby'." },
    { text: "All ____ remains of the settlement is a ring of post holes.", answers: ["that"], explanation: "After 'all', the relative pronoun must be 'that': 'all that remains'." },
    { text: "The hotel employs a sommelier, without ____ the cellar would be wasted on most guests.", answers: ["whom"], explanation: "After a preposition referring to a person, the relative pronoun is 'whom': 'without whom'." },
    { text: "The glacier feeds three rivers, ____ of which is navigable year round.", answers: ["none"], explanation: "With three rivers, 'none of which' means not a single one; 'neither' would only work for two." },
    { text: "She has two passports, ____ of which is currently valid.", answers: ["neither"], explanation: "'Neither of which' is used for two items to mean not one nor the other." },
    { text: "The witnesses gave three accounts, each of ____ contradicted the others.", answers: ["which"], explanation: "'Each of which' refers back to the accounts in a non-defining relative clause." },
    { text: "The lodge sits at the head of a fjord ____ waters freeze solid by November.", answers: ["whose"], explanation: "'Whose' expresses possession and can refer to things as well as people: the fjord's waters." },
    { text: "The programme pairs each newcomer with a mentor, ____ role is purely advisory.", answers: ["whose"], explanation: "'Whose' is the possessive relative pronoun: the mentor's role." },
    { text: "The bridge will stay open ____ engineers detect further movement in the piers.", answers: ["unless", "until"], explanation: "'Unless' means 'except if'; 'until' would mean 'up to the time when'. Both create a coherent condition here." },
    { text: "____ the rain eased, the groundstaff had the pitch playable within the hour.", answers: ["once", "when", "after"], explanation: "'Once/when/after' introduces a time clause: as soon as the rain stopped, work began." },
    { text: "The reef looks pristine, ____ appearances can be deceptive at depth.", answers: ["but", "though", "yet"], explanation: "A contrastive conjunction is needed: it looks pristine, but that impression may be misleading." },
    { text: "The mill still grinds flour, ____ only for demonstration purposes these days.", answers: ["if", "though", "albeit"], explanation: "'If/though/albeit only' concedes a limitation: it grinds flour, but merely for show." },
    { text: "The path is safe enough, ____ that you keep to the marked route.", answers: ["provided", "providing"], explanation: "'Provided/providing that' means 'on condition that'." },
    { text: "The offer stands ____ long as the survey raises no structural concerns.", answers: ["as", "so"], explanation: "'As/so long as' introduces a condition: the offer remains valid only if the survey is clean." },
    { text: "____ route you take, allow a full day for the crossing.", answers: ["whichever", "whatever"], explanation: "'Whichever/whatever route' means 'it does not matter which route'." },
    { text: "The clinic will see you today, ____ urgent your case may seem to the receptionist.", answers: ["however"], explanation: "'However + adjective' means 'no matter how urgent'." },
    { text: "____ of the two proposals convinced the planning officer, so both were sent back.", answers: ["neither"], explanation: "'Neither of the two' means not one of the pair; the negative sense is confirmed by both being rejected." },
    { text: "Hardly ____ of the original orchard survived the motorway works.", answers: ["any"], explanation: "'Hardly any' means almost none of the orchard remained." },
    { text: "The rescue team had precious ____ daylight left when the signal was picked up.", answers: ["little"], explanation: "'Precious little' is an emphatic way of saying 'very little' with an uncountable noun." },
    { text: "Precious ____ of the paintings survived the damp.", answers: ["few"], explanation: "'Precious few' means 'very few' and is used with plural countable nouns." },
    { text: "The tickets cost twice as ____ as they did before the refurbishment.", answers: ["much"], explanation: "With an uncountable idea of price, the comparison is 'twice as much as'." },
    { text: "There were more volunteers ____ tasks, so shifts were shortened.", answers: ["than"], explanation: "'More X than Y' compares the two quantities: volunteers outnumbered tasks." },
    { text: "The two firms have been at ____ other's throats for a decade over the patent.", answers: ["each"], explanation: "The idiom 'at each other's throats' means fighting or arguing fiercely." },
    { text: "The negotiations were conducted ____ closed doors.", answers: ["behind"], explanation: "'Behind closed doors' means in private, away from public view." },
    { text: "The estate was divided equally ____ the four surviving cousins.", answers: ["among", "between", "amongst"], explanation: "'Among(st)' distributes something within a group; 'between' is also accepted with more than two in modern usage." },
    { text: "The summit was scheduled ____ short notice after the currency slid overnight.", answers: ["at"], explanation: "'At short notice' means with very little warning time." },
    { text: "The whistleblower acted entirely ____ her own initiative.", answers: ["on"], explanation: "'On one's own initiative' means without being asked or instructed." },
    { text: "The results were published in full, ____ keeping with the institute's open-data policy.", answers: ["in"], explanation: "'In keeping with' means consistent with or conforming to." },
    { text: "The lifeboat crew are on call twenty-four hours a day, all year ____.", answers: ["round", "long"], explanation: "'All year round' means throughout the entire year; 'all year long' is an accepted alternative." },
    { text: "The exam results are due out ____ the end of the month.", answers: ["by", "at", "before"], explanation: "'By/at/before the end of the month' all locate the release within or at that deadline." },
    { text: "The parcel ought to ____ arrived by now; it was posted a fortnight ago.", answers: ["have"], explanation: "'Ought to have + past participle' expresses an expectation about the past that seems unfulfilled." },
    { text: "You ____ well ask why the alarm was switched off in the first place.", answers: ["may", "might"], explanation: "'You may/might well ask' acknowledges that the question is a very reasonable one." },
    { text: "The panic proved needless, as such panics so often ____.", answers: ["do"], explanation: "'Do' substitutes for the verb phrase 'prove needless' to avoid repetition." },
    { text: "Rarely ____ so much depended on the testimony of a single witness.", answers: ["has"], explanation: "Fronted 'rarely' triggers inversion; 'has depended' is the present perfect." },
    { text: "I'd rather you ____ mention the surprise party to anyone just yet.", answers: ["didn't"], explanation: "'Would rather + subject' takes a past tense form for present or future reference: 'I'd rather you didn't'." },
    { text: "It's about time the pavilion ____ given a fresh coat of paint.", answers: ["was", "were", "got"], explanation: "'It's about time' is followed by a past form referring to the present: 'was/were given'." },
    { text: "If only the architects ____ consulted the residents before finalising the plans.", answers: ["had"], explanation: "'If only + past perfect' expresses regret about the past: they did not consult anyone." },
    { text: "____ I in your position, I would ask for the offer in writing.", answers: ["were"], explanation: "Inverted conditional 'Were I...' replaces 'If I were...' in formal style." },
    { text: "The regulations require that every rider ____ fitted with a transponder.", answers: ["be"], explanation: "After 'require that', the subjunctive 'be' is used: 'that every rider be fitted'." },
    { text: "The auditors recommended that the accounts ____ resubmitted quarterly rather than annually.", answers: ["be"], explanation: "Verbs like 'recommend that' take the subjunctive: 'that the accounts be resubmitted'." },
    { text: "In ____ event of fire, do not use the lifts.", answers: ["the"], explanation: "The fixed formal phrase is 'in the event of', meaning 'if X happens'." },
    { text: "The retreat offers, above ____ else, silence.", answers: ["all"], explanation: "'Above all else' means more than anything; silence is the key attraction." },
    { text: "The negotiations achieved next to ____.", answers: ["nothing"], explanation: "'Next to nothing' means almost nothing at all." },
    { text: "The senator's answer, such ____ it was, satisfied nobody.", answers: ["as"], explanation: "'Such as it was' concedes that the answer was barely worthy of the name." },
    { text: "The correspondence, some of ____ predates the revolution, fills forty boxes.", answers: ["which"], explanation: "'Some of which' refers back to the correspondence in a non-defining relative clause." },
    { text: "The volunteers cooked for the whole camp, keeping only the leftovers for ____.", answers: ["themselves"], explanation: "The reflexive pronoun 'themselves' refers back to the volunteers." },
    { text: "Anyone wishing to speak should make ____ known to the clerk before noon.", answers: ["themselves", "himself", "herself"], explanation: "'Make oneself known to' means introduce oneself; singular 'anyone' commonly takes 'themselves'." },
    { text: "The device recalibrates ____ every time it is powered on.", answers: ["itself"], explanation: "The reflexive 'itself' shows the device performs the action on its own systems." },
    { text: "The programme caters ____ absolute beginners and seasoned coders alike.", answers: ["for", "to"], explanation: "'Cater for/to' means to provide what a particular group needs." },
    { text: "The mayor shrugged the criticism ____ and pressed ahead with the scheme.", answers: ["off"], explanation: "'Shrug off' is a phrasal verb meaning to dismiss something as unimportant." },
    { text: "Talks broke ____ overnight without so much as a joint statement.", answers: ["down", "off"], explanation: "'Break down' means to fail completely; 'break off' means to be abruptly ended." },
    { text: "The old wharf has been done ____ and reopened as a food market.", answers: ["up"], explanation: "'Do up' is a phrasal verb meaning to renovate or redecorate a building." },
    { text: "The story doesn't quite add ____; the timings are all wrong.", answers: ["up"], explanation: "'Add up' means to make sense; a story that doesn't add up seems inconsistent." },
    { text: "The union refused to rule ____ further strikes in the autumn.", answers: ["out"], explanation: "'Rule out' means to exclude something as a possibility." },
    { text: "The debate was less about cost ____ about who controls the data.", answers: ["than"], explanation: "The structure 'less about X than about Y' contrasts the true issue with the apparent one." },
    { text: "The report concedes, ____ grudgingly, that the pilot scheme worked.", answers: ["albeit", "if", "though", "however"], explanation: "'Albeit/if/though grudgingly' concedes the manner of the admission within the clause." },
    { text: "The festival went ahead as planned, the forecast ____.", answers: ["notwithstanding"], explanation: "'Notwithstanding' can follow its noun: 'the forecast notwithstanding' means despite the forecast." },
    { text: "____ the outcome of the appeal, her reputation has already suffered.", answers: ["whatever"], explanation: "'Whatever the outcome' means regardless of how the appeal ends." },
    { text: "The twin villages, ____ barely a mile apart, support two fiercely rival brass bands.", answers: ["though", "while", "albeit", "although"], explanation: "A concessive word contrasts their closeness with their rivalry." },
    { text: "The committee met in private, ____ is customary for disciplinary matters.", answers: ["as"], explanation: "'As is customary' comments on the whole clause: meeting in private is the usual practice." },
    { text: "The manuscript is too fragile ____ be handled without gloves.", answers: ["to"], explanation: "The structure 'too + adjective + to + infinitive' shows the handling is not possible." },
    { text: "The pass stays snowbound from November ____ to late May.", answers: ["through", "right", "up"], explanation: "'From November through/right/up to late May' emphasises the full extent of the period." },
    { text: "The louder he protested his innocence, the ____ convinced the jury became.", answers: ["less"], explanation: "The correlative comparative 'the louder..., the less...' links the two changes inversely." },
    { text: "The higher the observatory, the sharper the images, ____ else being equal.", answers: ["all"], explanation: "'All else being equal' means assuming other factors stay the same." },
    { text: "The delegates argued long ____ the night without narrowing their differences.", answers: ["into"], explanation: "'Long into the night' means continuing until a very late hour." },
    { text: "The recipe has been handed ____ through five generations of the same family.", answers: ["down"], explanation: "'Hand down' means to pass something from older to younger generations." },
    { text: "The candidate refused to be drawn ____ the question of tax rises.", answers: ["on"], explanation: "'Be drawn on a subject' means be persuaded to comment on it; refusing to be drawn means declining to answer." },
    { text: "____ say the least, the launch did not go according to plan.", answers: ["to"], explanation: "'To say the least' indicates the statement is an understatement." },
    { text: "The cargo shifted in heavy seas, ____ which the vessel developed a list.", answers: ["upon", "after", "following"], explanation: "'Upon which' means 'immediately after which', linking the shift to its consequence." },
    { text: "The staff learned of the closure not from management but ____ the local paper.", answers: ["from", "through", "via"], explanation: "The parallel structure 'not from X but from/through Y' identifies the actual source of the news." },
    { text: "The fort commands the valley, ____ its strategic value for two millennia.", answers: ["hence", "whence"], explanation: "'Hence' means 'which explains': its position is the reason for its strategic value." },
    { text: "The choir will sing regardless, come rain ____ shine.", answers: ["or"], explanation: "'Come rain or shine' is an idiom meaning whatever the weather or circumstances." },
    { text: "The ambassador would neither confirm ____ deny the reports of a secret annex.", answers: ["nor"], explanation: "'Neither... nor...' is the correlative pair for two negated alternatives." },
    { text: "The lock gates are original and, ____ such, are listed structures.", answers: ["as"], explanation: "'As such' means in that capacity: being original, they qualify for protection." },
    { text: "The moorland is common land, meaning anyone may walk there at ____.", answers: ["will"], explanation: "'At will' means whenever and however one pleases." },
    { text: "The satellite images left no room ____ doubt about the scale of deforestation.", answers: ["for"], explanation: "'Leave no room for doubt' means to make something absolutely certain." },
    { text: "The programme aims to help those ____ whom conventional schooling has failed.", answers: ["for"], explanation: "'Those for whom X has failed' uses preposition + 'whom' in a formal relative clause." },
    { text: "The bidder remained anonymous, communicating solely ____ an intermediary.", answers: ["through", "via"], explanation: "'Through/via an intermediary' expresses the channel of communication." },
    { text: "The road is closed to all traffic ____ from residents' vehicles.", answers: ["apart", "aside"], explanation: "'Apart/aside from' means with the exception of." },
    { text: "The lecture was pitched at specialists, which explains ____ so many students drifted away.", answers: ["why"], explanation: "'Explains why' introduces the reason clause for the students' departure." },
    { text: "Hardly ____ we set up camp when the first thunderclap rolled across the valley.", answers: ["had"], explanation: "'Hardly had X happened when Y' uses past perfect inversion for two closely following events." },
    { text: "No sooner had she declared the exhibition open ____ the lights failed.", answers: ["than"], explanation: "'No sooner... than...' is the fixed pair; 'when' is not used with 'no sooner'." },
    { text: "The startup burned through its funding within a year, as so ____ do.", answers: ["many"], explanation: "'As so many do' means as a large number of similar companies also do." },
    { text: "The two candidates agree on very little, if ____ at all.", answers: ["anything"], explanation: "'Very little, if anything' concedes there may be nothing at all they agree on." },
    { text: "____ dense was the fog that the pilots taxied by instruments alone.", answers: ["so"], explanation: "Fronted 'so + adjective' with inversion: 'So dense was the fog that...' emphasises the extreme degree." },
    { text: "It was thanks to a mislabelled crate ____ the fossils survived the fire.", answers: ["that"], explanation: "A cleft sentence with 'It was... that...' highlights the lucky cause." },
    { text: "What worries the residents most ____ the absence of any evacuation plan.", answers: ["is"], explanation: "The 'what'-clause subject takes a singular verb: 'What worries them most is...'." },
    { text: "The tribunal ordered that the licence ____ revoked with immediate effect.", answers: ["be"], explanation: "'Order that' is followed by the subjunctive: 'that the licence be revoked'." },
    { text: "Were the subsidy to be scrapped, thousands of farms would go ____.", answers: ["under", "bust", "bankrupt"], explanation: "'Go under' is an idiom meaning to fail financially or go out of business." },
    { text: "The apprenticeship scheme is open to anyone ____ the age of twenty-five.", answers: ["under", "below"], explanation: "'Under/below the age of' sets an upper age limit for eligibility." },
    { text: "The orchestra played on, ____ though the hall was emptying around them.", answers: ["even"], explanation: "'Even though' is an emphatic concessive conjunction: despite the emptying hall, they continued." },
    { text: "The playwright drew ____ her own childhood for the play's central family.", answers: ["on", "upon", "from"], explanation: "'Draw on/upon' means to use something as a source or inspiration." },
    { text: "By the time the brigade arrived, the barn was ____ saving.", answers: ["beyond", "past"], explanation: "'Beyond/past saving' means too far gone to be rescued." },
    { text: "The committee could not decide ____ to publish the findings or suppress them.", answers: ["whether"], explanation: "'Whether... or...' introduces the two alternatives being weighed." },
    { text: "The ship's log makes no mention of the storm, ____ is odd given its severity.", answers: ["which"], explanation: "'Which' refers back to the whole preceding clause in a sentential relative." },
    { text: "The archaeologists stumbled ____ the mosaic while laying drainage pipes.", answers: ["upon", "across", "on"], explanation: "'Stumble upon/across/on' means to discover something by chance." },
    { text: "Half the jurors turned up ____ having read the brief.", answers: ["without"], explanation: "'Without + -ing' shows the expected action (reading the brief) had not been done." },
    { text: "Under ____ circumstances are visitors to feed the seals.", answers: ["no"], explanation: "'Under no circumstances' is an emphatic prohibition and triggers the inversion 'are visitors to feed'." },
    { text: "Only rarely ____ auroras visible this far south.", answers: ["are"], explanation: "Fronted 'only rarely' requires inversion: 'only rarely are auroras visible'." },
    { text: "So fierce ____ the competition for allotments that the waiting list runs to a decade.", answers: ["is", "was"], explanation: "Fronted 'so + adjective' inverts subject and verb: 'So fierce is the competition that...'." },
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part2 = QUESTIONS.part2.concat(BANK);
})();
