/* CAE Prep extra bank: part2 wave 1 */
(function () {
  var BANK = [
    { text: "The company is said to be ____ the verge of announcing its most ambitious merger yet.", answers: ["on"], explanation: "'On the verge of' is a fixed phrase meaning about to do something imminently." },
    { text: "____ the wake of the scandal, three board members tendered their resignations.", answers: ["in"], explanation: "'In the wake of' means as a consequence of, or immediately following, an event." },
    { text: "She accepted the lifetime achievement award ____ behalf of her late grandfather.", answers: ["on"], explanation: "'On behalf of someone' means as that person's representative." },
    { text: "His meteoric rise came ____ the expense of his health and most of his friendships.", answers: ["at"], explanation: "'At the expense of' indicates that something is sacrificed to achieve something else." },
    { text: "____ no circumstances should passengers unfasten their seatbelts while the light is on.", answers: ["under","in"], explanation: "'Under/In no circumstances' is a fronted negative phrase triggering inversion ('should passengers unfasten')." },
    { text: "The negotiations collapsed on Tuesday, ____ which point both delegations flew home.", answers: ["at"], explanation: "'At which point' is a relative expression meaning 'and at that moment'." },
    { text: "By ____ the most compelling argument was the one nobody had anticipated.", answers: ["far"], explanation: "'By far' intensifies a superlative, meaning by a great margin." },
    { text: "No ____ how meticulously you plan, something unforeseen invariably crops up.", answers: ["matter"], explanation: "'No matter how' introduces a concessive clause meaning 'regardless of how'." },
    { text: "She can barely afford the rent on a bedsit, ____ alone a mortgage on a house.", answers: ["let"], explanation: "'Let alone' follows a negative idea to emphasise that something greater is even less likely." },
    { text: "Seldom ____ critics reach such a unanimous verdict on a debut novel.", answers: ["do"], explanation: "Fronted 'Seldom' is a negative adverb requiring subject-auxiliary inversion: 'Seldom do critics...'." },
    { text: "Scarcely ____ the ceremony begun when the fire alarm brought it to a halt.", answers: ["had"], explanation: "'Scarcely had X happened when Y' uses inversion with the past perfect auxiliary." },
    { text: "Not until the final chapter ____ the narrator's true motive become clear.", answers: ["does"], explanation: "Fronting 'Not until...' forces inversion in the main clause: 'does the motive become clear'." },
    { text: "____ it not been for the volunteers, the festival would never have gone ahead.", answers: ["had"], explanation: "Inverted third conditional: 'Had it not been for' replaces 'If it had not been for'." },
    { text: "____ the central bank to raise rates again, mortgage holders would feel it immediately.", answers: ["were"], explanation: "Inverted hypothetical conditional: 'Were X to do Y' replaces 'If X were to do Y'." },
    { text: "____ you require any further assistance, please do not hesitate to contact the helpdesk.", answers: ["should"], explanation: "Inverted conditional 'Should you require' is a formal alternative to 'If you should require'." },
    { text: "The quarterly results were disappointing, ____ to say disastrous.", answers: ["not"], explanation: "'Not to say' introduces a stronger alternative description: 'disappointing, not to say disastrous'." },
    { text: "The manuscript, ____ authenticity has long been disputed, goes to auction next month.", answers: ["whose"], explanation: "'Whose' is the possessive relative pronoun, used here for a thing as well as for people." },
    { text: "The firm introduced a scheme ____ employees can exchange salary for additional leave.", answers: ["whereby"], explanation: "'Whereby' is a formal relative meaning 'by means of which'." },
    { text: "There were a dozen applicants, none of ____ met the essential criteria.", answers: ["whom"], explanation: "After a preposition in a relative clause referring to people, 'whom' is required." },
    { text: "____ struck me most about the documentary was its refusal to moralise.", answers: ["what"], explanation: "'What' introduces a nominal relative clause acting as the subject of the sentence (a wh-cleft)." },
    { text: "It was only after the votes had been counted ____ the scale of the upset became apparent.", answers: ["that"], explanation: "Cleft structure: 'It was only after X that Y' requires 'that' before the second clause." },
    { text: "The two studies reached strikingly similar conclusions, ____ by entirely different methods.", answers: ["albeit","though"], explanation: "'Albeit' (or 'though') introduces a concessive phrase meaning 'even if/although'." },
    { text: "____ often than not, first impressions turn out to be thoroughly misleading.", answers: ["more"], explanation: "'More often than not' is a fixed phrase meaning 'usually'." },
    { text: "The scheme sounds attractive in theory; ____ practice, however, it is fraught with difficulty.", answers: ["in"], explanation: "'In practice' contrasts with 'in theory' as a fixed prepositional phrase." },
    { text: "The exhibition is well worth the detour, ____ only for the room of early sketches.", answers: ["if"], explanation: "'If only for' means 'even if for no other reason than'." },
    { text: "Strange ____ it may seem, parts of the desert can flood within minutes.", answers: ["as","though"], explanation: "'Adjective + as/though + subject + verb' is a concessive inversion: 'Strange as it may seem'." },
    { text: "Try ____ she might, she could not recall where she had left the keys.", answers: ["as"], explanation: "'Try as she might' is a fixed concessive structure meaning 'however hard she tried'." },
    { text: "The bridge withstood the earthquake, ____ to the astonishment of its own engineers.", answers: ["much"], explanation: "'Much to the astonishment of' is a fixed pattern expressing a strong reaction." },
    { text: "He is, ____ all accounts, a remarkably generous employer.", answers: ["by"], explanation: "'By all accounts' means according to what everyone says." },
    { text: "The findings should be treated with caution, ____ the unusually small sample size.", answers: ["given","considering"], explanation: "'Given' functions as a preposition meaning 'taking into account'." },
    { text: "The witness declined to answer, ____ was her legal right.", answers: ["as","which"], explanation: "'As/which was her right' is a sentential relative commenting on the whole preceding clause." },
    { text: "The volcano could erupt at any moment, in ____ case the entire valley would be evacuated.", answers: ["which"], explanation: "'In which case' is a relative expression meaning 'and if that happens'." },
    { text: "____ the negotiations succeed or fail, the alliance has already been weakened.", answers: ["whether"], explanation: "'Whether... or...' introduces alternative concessive conditions." },
    { text: "You may borrow the car, ____ that you return it with a full tank.", answers: ["provided","providing"], explanation: "'Provided/providing that' means 'on condition that'." },
    { text: "____ appears to be a minor clause could in fact expose the firm to enormous liability.", answers: ["what"], explanation: "'What' heads a nominal relative clause serving as the subject: 'What appears to be X'." },
    { text: "The lecture was so densely argued ____ few of us could follow it to the end.", answers: ["that"], explanation: "'So + adjective + that' introduces a result clause." },
    { text: "So intense ____ the heat that the tarmac on the runway began to melt.", answers: ["was"], explanation: "Fronting 'So intense' triggers inversion: 'So intense was the heat that...'." },
    { text: "Such ____ the demand for tickets that the website crashed within seconds.", answers: ["was"], explanation: "Fronted 'Such' requires inversion: 'Such was the demand that...'." },
    { text: "No sooner had the ceasefire been declared ____ sporadic fighting resumed.", answers: ["than"], explanation: "'No sooner... than...' is the fixed correlative pair; 'when' is not possible here." },
    { text: "Hardly had the plane touched down ____ passengers began switching on their phones.", answers: ["when","before"], explanation: "'Hardly had X happened when/before Y' is the standard correlative with inversion." },
    { text: "Far ____ resolving the dispute, the ruling merely entrenched both sides.", answers: ["from"], explanation: "'Far from doing X' means 'instead of doing X at all'." },
    { text: "____ regards accommodation, delegates are strongly advised to book early.", answers: ["as"], explanation: "'As regards' is a formal fixed phrase meaning 'concerning'." },
    { text: "The proposal was rejected ____ the grounds that it breached planning regulations.", answers: ["on"], explanation: "'On the grounds that' means 'for the stated reason that'." },
    { text: "The landlord may inspect the premises ____ any time without prior notice.", answers: ["at"], explanation: "'At any time' is the fixed prepositional phrase for unrestricted timing." },
    { text: "The rumours about the takeover turned ____ to be entirely unfounded.", answers: ["out"], explanation: "'Turn out to be' means to prove to be, in the end." },
    { text: "After a week of walkouts, the talks are said to be ____ the brink of collapse.", answers: ["on"], explanation: "'On the brink of' means extremely close to (usually something bad)." },
    { text: "The painting fetched three times ____ the gallery had originally paid for it.", answers: ["what"], explanation: "'Three times what X paid' uses 'what' as a nominal relative meaning 'the amount that'." },
    { text: "____ with the recession, the pandemic all but destroyed the hospitality sector.", answers: ["along","together","coupled"], explanation: "'Along/together/coupled with' adds a second contributing factor." },
    { text: "The congestion charge is intended to benefit commuters and cyclists ____.", answers: ["alike"], explanation: "'X and Y alike' means both X and Y equally." },
    { text: "The two versions of the report differ from ____ another in several key respects.", answers: ["one"], explanation: "'Differ from one another' is the reciprocal pronoun phrase." },
    { text: "In ____ of the latest findings, the dietary guidelines have been quietly revised.", answers: ["light","view"], explanation: "'In light/view of' means 'because of' or 'taking into consideration'." },
    { text: "The open-air concert went ahead in ____ of the torrential rain.", answers: ["spite"], explanation: "'In spite of' is the fixed concessive phrase; only 'spite' completes it." },
    { text: "Bonuses are calculated ____ the basis of the previous year's performance.", answers: ["on"], explanation: "'On the basis of' means 'using X as the criterion'." },
    { text: "The refugees fled with little ____ than the clothes they were wearing.", answers: ["more","other"], explanation: "'Little more/other than' means 'hardly anything except'." },
    { text: "____ of the candidates impressed the panel, so the post was re-advertised.", answers: ["none","neither"], explanation: "'None of' (or 'neither of' for two) is a negative quantifier taking 'of + noun phrase'." },
    { text: "The official figures, ____ anything, understate the true scale of the problem.", answers: ["if"], explanation: "'If anything' suggests the opposite of what might be expected, or a stronger version of the claim." },
    { text: "The director, together with her two deputies, ____ due to arrive shortly.", answers: ["is"], explanation: "'Together with' does not make the subject plural; the verb agrees with 'the director'." },
    { text: "____ being a gifted linguist, she is an accomplished violinist.", answers: ["besides"], explanation: "'Besides + -ing' means 'in addition to being'." },
    { text: "There is ____ point in rehearsing arguments that will convince nobody.", answers: ["no","little"], explanation: "'There is no/little point in + -ing' is the fixed pattern for futility." },
    { text: "The cathedral took the best part ____ a century to complete.", answers: ["of"], explanation: "'The best part of' means almost the whole of a period or amount." },
    { text: "____ it comes to delicate negotiation, few can match her composure.", answers: ["when"], explanation: "'When it comes to' is a fixed phrase meaning 'as far as X is concerned'." },
    { text: "To save power, the projector switches itself off when not ____ use.", answers: ["in"], explanation: "'In use' means currently being used; 'when not in use' is the fixed form." },
    { text: "He is nothing ____ not persistent; he has applied for the same grant nine times.", answers: ["if"], explanation: "'Nothing if not' is an emphatic idiom meaning 'extremely'." },
    { text: "The forensic evidence is suggestive but still far ____ conclusive.", answers: ["from"], explanation: "'Far from + adjective' means 'not at all'." },
    { text: "The new assembly is composed ____ representatives from all twelve districts.", answers: ["of"], explanation: "'Be composed of' means to consist of; the preposition is fixed." },
    { text: "____ do we appreciate clean water until the supply is suddenly cut off.", answers: ["little","seldom","rarely"], explanation: "A fronted negative adverb ('Little/Seldom/Rarely') triggers the inversion 'do we appreciate'." },
    { text: "The chief executive declined to comment, ____ did any member of the board.", answers: ["nor","neither"], explanation: "'Nor/neither did X' continues a negative statement with inversion." },
    { text: "It's not so much the cost ____ the principle of the thing that bothers me.", answers: ["as"], explanation: "'Not so much X as Y' is a fixed comparative structure meaning Y rather than X." },
    { text: "The witness's timeline was completely ____ odds with the forensic evidence.", answers: ["at"], explanation: "'At odds with' means in conflict or disagreement with." },
    { text: "The final decision rests ____ the shareholders alone.", answers: ["with"], explanation: "'The decision rests with someone' means that person has the authority to decide." },
    { text: "____ from a brief spell in Rome, she has lived in Lisbon all her life.", answers: ["apart","aside"], explanation: "'Apart/aside from' means 'with the exception of'." },
    { text: "The renovation ran ____ budget by nearly forty per cent.", answers: ["over"], explanation: "'Run over budget' means to exceed the planned spending." },
    { text: "He spoke at length about his achievements, ____ of which impressed us in the slightest.", answers: ["none"], explanation: "'None of which' is a negative quantifier heading a relative clause." },
    { text: "____ matters in the end is not winning but the manner of taking part.", answers: ["what"], explanation: "Wh-cleft: 'What matters is...' places emphasis on the following idea." },
    { text: "The government has come ____ sustained fire for its handling of the crisis.", answers: ["under"], explanation: "'Come under fire' is an idiom meaning to be strongly criticised." },
    { text: "The deal fell ____ at the eleventh hour over licensing rights.", answers: ["through"], explanation: "'Fall through' means to fail to be completed after seeming certain." },
    { text: "The new legislation does away ____ the requirement for annual inspections.", answers: ["with"], explanation: "'Do away with' is a phrasal verb meaning to abolish." },
    { text: "____ but the most dedicated fans will sit through a five-hour director's cut.", answers: ["none","few"], explanation: "'None/Few but the most dedicated' means only, or hardly anyone except, the most dedicated." },
    { text: "The mayor's speech amounted to little more ____ a string of platitudes.", answers: ["than"], explanation: "'Little more than' means hardly anything beyond; 'than' completes the comparison." },
    { text: "She would sooner resign ____ put her name to a report she believes is false.", answers: ["than"], explanation: "'Would sooner X than Y' expresses preference; 'than' is the required correlative." },
    { text: "The variant spread far more rapidly ____ even the pessimists had predicted.", answers: ["than"], explanation: "The comparative 'more rapidly' requires 'than' to introduce the standard of comparison." },
    { text: "____ the time being, the museum will remain closed on Mondays.", answers: ["for"], explanation: "'For the time being' means temporarily, for now." },
    { text: "The last flight of the evening was delayed ____ to freezing fog.", answers: ["owing","due"], explanation: "'Owing/due to' introduces the cause of the delay." },
    { text: "Attitudes to the reform vary considerably ____ one region to another.", answers: ["from"], explanation: "'Vary from one X to another' is the fixed pattern for expressing difference across items." },
    { text: "The airline denies ____ wrongdoing whatsoever in its handling of the refunds.", answers: ["any"], explanation: "'Any... whatsoever' is an emphatic negative polarity structure after 'denies'." },
    { text: "There is ____ denying that streaming has transformed the music industry.", answers: ["no"], explanation: "'There is no denying that' is a fixed idiom meaning it cannot be disputed." },
    { text: "It goes without ____ that punctuality is essential in this line of work.", answers: ["saying"], explanation: "'It goes without saying' is a fixed idiom meaning it is obvious." },
    { text: "The prisoner escaped by ____ of a rope fashioned from knotted bedsheets.", answers: ["means"], explanation: "'By means of' is a formal phrase meaning 'using'." },
    { text: "By ____ of its geography, the port controls all access to the strait.", answers: ["virtue"], explanation: "'By virtue of' means 'because of' or 'on the strength of'." },
    { text: "Tellingly, the report stops ____ of recommending an outright ban.", answers: ["short"], explanation: "'Stop short of doing something' means to almost do it but not go that far." },
    { text: "The audience burst ____ laughter before he had even reached the punchline.", answers: ["into"], explanation: "'Burst into laughter/tears' is the fixed collocation for a sudden outburst." },
    { text: "Once the pride of the town, the old theatre has fallen ____ disrepair.", answers: ["into"], explanation: "'Fall into disrepair' is the standard collocation for gradual physical decline." },
    { text: "____ a rule, the ferries do not sail in winds above force nine.", answers: ["as"], explanation: "'As a rule' means generally or usually." },
    { text: "The reopened gallery is drawing visitors from far and ____.", answers: ["wide"], explanation: "'From far and wide' is a fixed idiom meaning from many distant places." },
    { text: "The restructuring was decided over the heads of the staff, ____ a single employee being consulted.", answers: ["without"], explanation: "'Without + noun + -ing' expresses an absent circumstance: 'without anyone being consulted'." },
    { text: "____ of the twins has ever set foot outside the province.", answers: ["neither"], explanation: "'Neither of' is the negative quantifier for exactly two people." },
    { text: "The introductory offer is valid only ____ stocks last.", answers: ["while","whilst"], explanation: "'While stocks last' is the fixed commercial phrase meaning until supplies run out." },
    { text: "____ was it that first proposed the tunnel, more than a century ago?", answers: ["who"], explanation: "Cleft question: 'Who was it that...?' emphasises the identity of the doer." },
    { text: "The senator has repeatedly refused to say ____ she will seek re-election.", answers: ["whether","if"], explanation: "'Whether' (or 'if') introduces an embedded yes/no question after 'say'." },
    { text: "The mountain road will remain closed ____ further notice.", answers: ["until","till","pending"], explanation: "'Until further notice' means for an indefinite period, until a new announcement." },
    { text: "You had ____ book now if you are set on a window seat.", answers: ["better"], explanation: "'Had better + bare infinitive' gives strong advice." },
    { text: "Condemned as unsafe, the tower block was pulled ____ within a month.", answers: ["down"], explanation: "'Pull down' is the phrasal verb meaning to demolish a building." },
    { text: "Her latest film is a radical departure ____ the thrillers that made her name.", answers: ["from"], explanation: "'A departure from' means a change away from what is usual or previous." },
    { text: "____ far as I can tell, these figures have never been independently audited.", answers: ["as","so"], explanation: "'As/So far as I can tell' is a fixed hedge meaning 'to the extent that I can judge'." },
    { text: "The town is famous, ____ other things, for its mustard and its cathedral.", answers: ["among","amongst"], explanation: "'Among(st) other things' signals that the list is not exhaustive." },
    { text: "Written off before kick-off, the visitors pulled it off against ____ the odds.", answers: ["all"], explanation: "'Against all the odds' means despite it seeming almost impossible." },
    { text: "It remains to be ____ whether the fragile truce will survive the winter.", answers: ["seen"], explanation: "'It remains to be seen whether' is a fixed phrase meaning the outcome is still unknown." },
    { text: "Legally speaking, the minister is ____ no obligation to publish her diary.", answers: ["under"], explanation: "'Be under no obligation to do something' means not to be required to do it." },
    { text: "All passwords must be changed every ninety days ____ fail.", answers: ["without"], explanation: "'Without fail' means always, with no exceptions." },
    { text: "The forgery is superb; only an expert could tell one painting ____ the other.", answers: ["from"], explanation: "'Tell one thing from another' means to distinguish between them." },
    { text: "After a two-year battle, the court found in ____ of the plaintiff.", answers: ["favour","favor"], explanation: "'Find in favour of someone' is the legal phrase for ruling on someone's side." },
    { text: "____ what has been a turbulent year for retail, the chain's profits held steady.", answers: ["in"], explanation: "'In what has been...' embeds a nominal relative clause after the preposition 'in'." },
    { text: "Not once ____ he acknowledged the sources on which his data depend.", answers: ["has"], explanation: "Fronted 'Not once' triggers inversion with the perfect auxiliary: 'has he acknowledged'." },
    { text: "Nowhere in the contract ____ any mention made of overtime rates.", answers: ["is"], explanation: "Fronted 'Nowhere' requires inversion: 'is any mention made'." },
    { text: "On no account ____ the seal be broken before the inspector arrives.", answers: ["should","must","may"], explanation: "'On no account' fronts the sentence and forces modal inversion: 'should/must the seal be broken'." },
    { text: "The reviews were, ____ the whole, rather more generous than the film deserved.", answers: ["on"], explanation: "'On the whole' means generally, all things considered." },
    { text: "The paper has since been retracted, calling ____ question a decade of research.", answers: ["into"], explanation: "'Call into question' means to cast doubt on something." },
    { text: "The sanctuary relies almost entirely ____ private donations to stay open.", answers: ["on","upon"], explanation: "'Rely on/upon' is the fixed verb-preposition pairing." },
    { text: "During the floods, the village was accessible only ____ boat.", answers: ["by"], explanation: "'By + means of transport' (by boat, by air) expresses the method of travel." },
    { text: "The two insurers merged in May, ____ creating the largest firm in the region.", answers: ["thereby","thus"], explanation: "'Thereby/thus + -ing' expresses the result of the preceding action." }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part2 = QUESTIONS.part2.concat(BANK);
})();
