/* CAE Prep extra bank: part2 wave 3 */
(function () {
  var BANK = [
    { text: "Seldom ____ a proposal met with such immediate and unanimous approval.", answers: ["has"], explanation: "After the negative adverb 'seldom', subject and auxiliary invert; 'has met' fits the present perfect sense." },
    { text: "The violin, ____ varnish has darkened over three centuries, still projects to the back row.", answers: ["whose"], explanation: "'Whose' is the possessive relative pronoun, here referring to the violin's varnish." },
    { text: "Ambitious ____ the plan undoubtedly is, nobody has explained how it will be financed.", answers: ["as", "though"], explanation: "In the concessive pattern 'adjective + as/though + subject + verb', both words mean 'although'." },
    { text: "Had the storm arrived an hour earlier, the regatta would ____ ended in disaster.", answers: ["have"], explanation: "The inverted third conditional 'Had... arrived' requires 'would have + past participle' in the main clause." },
    { text: "____ being interviewed live on air, the minister let slip the date of the election.", answers: ["while", "when", "whilst"], explanation: "'While/when + -ing' introduces a reduced time clause: while she was being interviewed." },
    { text: "The tapestry has hung in the great hall ever ____ the castle was first furnished.", answers: ["since"], explanation: "'Ever since' introduces the starting point of a period continuing to the present, used with the present perfect." },
    { text: "It was only through an anonymous tip-off ____ the smuggling ring was uncovered.", answers: ["that"], explanation: "This is a cleft sentence: 'It was... that...' emphasises the means by which something happened." },
    { text: "The residents would rather the festival ____ moved to the edge of town than cancelled outright.", answers: ["were", "was"], explanation: "'Would rather + subject' takes a past (subjunctive) verb form to express a present preference." },
    { text: "____ the dam not held, three villages downstream would have been swept away.", answers: ["had"], explanation: "Inverted third conditional: 'Had the dam not held' replaces 'If the dam had not held'." },
    { text: "The interview was going smoothly ____ the candidate mentioned his previous employer.", answers: ["until", "till"], explanation: "'Until' marks the point at which the smooth progress stopped." },
    { text: "____ from encouraging cycling, the new lanes seem to have pushed riders onto the pavement.", answers: ["far"], explanation: "'Far from + -ing' means 'not at all'; the opposite of the intended effect occurred." },
    { text: "The clinic treats everyone regardless ____ their ability to pay.", answers: ["of"], explanation: "The fixed phrase is 'regardless of', meaning without being affected by." },
    { text: "You can borrow the telescope on condition ____ you store it away from damp.", answers: ["that"], explanation: "'On condition that' introduces a requirement, similar to 'provided that'." },
    { text: "So poorly ____ the announcement worded that half the staff thought they had been dismissed.", answers: ["was"], explanation: "Fronting 'so + adverb' triggers inversion: 'So poorly was it worded that...'." },
    { text: "Such was the din from the building site ____ the lecture had to be moved.", answers: ["that"], explanation: "'Such + be + noun... that' expresses result: the noise was so great that a consequence followed." },
    { text: "No sooner ____ the curtains opened than a stagehand wandered across the set.", answers: ["had"], explanation: "'No sooner had X happened than Y' uses inversion with the past perfect." },
    { text: "Hardly a week goes ____ without another data breach making the headlines.", answers: ["by"], explanation: "The phrasal verb 'go by' means to pass, used of time." },
    { text: "Under no circumstances ____ the reactor be operated with the coolant valve closed.", answers: ["should", "must", "may"], explanation: "A fronted negative phrase forces inversion of a modal verb expressing prohibition." },
    { text: "Only by comparing the two manuscripts side by side ____ the scribe's alterations become apparent.", answers: ["do", "did"], explanation: "'Only by + -ing' at the start of a sentence requires auxiliary inversion; the plural subject takes 'do/did'." },
    { text: "Not until the ink was analysed ____ the diary shown to be a modern fake.", answers: ["was"], explanation: "'Not until...' fronted causes inversion in the main clause: 'was the diary shown'." },
    { text: "____ the negotiations to break down now, months of quiet diplomacy would be wasted.", answers: ["were"], explanation: "'Were + subject + to-infinitive' is an inverted, formal way of saying 'if the negotiations broke down'." },
    { text: "____ it not for the oxbow lakes, the floodplain would drain far too quickly.", answers: ["were"], explanation: "'Were it not for' is an inverted conditional meaning 'if it were not for'." },
    { text: "Should you ____ any difficulty locating your seat, an usher will gladly assist.", answers: ["have", "experience", "encounter"], explanation: "After inverted 'Should you...', a bare infinitive follows; 'have difficulty (in) -ing' is the standard collocation." },
    { text: "The moment the fraud came ____ light, trading in the shares was suspended.", answers: ["to"], explanation: "The idiom 'come to light' means to become known or be revealed." },
    { text: "The cellist played from memory, ____ was her habit even in rehearsal.", answers: ["as"], explanation: "'As' here is a relative-like conjunction referring to the whole preceding clause: which was her habit." },
    { text: "The report criticises the regulator and government ministers ____.", answers: ["alike"], explanation: "'X and Y alike' means both equally, placed after the second noun." },
    { text: "In ____ but the driest summers, the meadow is too boggy to mow.", answers: ["all"], explanation: "'In all but the driest summers' means in every summer except the very driest." },
    { text: "____ many respects, the sequel improves on the original.", answers: ["in"], explanation: "The fixed phrase 'in many respects' means in many ways." },
    { text: "The two witnesses gave accounts completely at variance ____ each other.", answers: ["with"], explanation: "The formal expression 'at variance with' means in disagreement with." },
    { text: "The castle is open daily, ____ for Christmas Day and Boxing Day.", answers: ["except", "save"], explanation: "'Except for' (or the formal 'save for') introduces the sole exclusions." },
    { text: "The harvest failed for the third year running, ____ which the settlers abandoned the valley.", answers: ["after", "upon", "following"], explanation: "'After/upon which' links the failure to the consequence that followed it." },
    { text: "The soprano fell ill, so the understudy went ____ at half an hour's notice.", answers: ["on"], explanation: "In theatre, to 'go on' means to appear on stage and perform." },
    { text: "Little ____ he know that the buyer at the back of the room was his own daughter.", answers: ["did"], explanation: "Fronted 'little' is negative in force and triggers inversion with the auxiliary 'did'." },
    { text: "____ was the mayor herself who leaked the memo, it later transpired.", answers: ["it"], explanation: "A cleft sentence 'It was X who...' places emphasis on the surprising agent." },
    { text: "What the scheme lacks in glamour, it makes up for ____ sheer usefulness.", answers: ["in"], explanation: "The pattern 'lack in X... make up for in Y' balances a deficiency against a strength." },
    { text: "The glacier calved without warning, sending a wave clean ____ the fjord.", answers: ["across"], explanation: "'Clean across' means entirely from one side to the other." },
    { text: "The archive smelled of dust and beeswax, as archives are apt ____ do.", answers: ["to"], explanation: "'Be apt to + infinitive' means to have a tendency to." },
    { text: "Scarcely ____ the votes been counted when demands for a recount began.", answers: ["had"], explanation: "'Scarcely had X happened when Y' uses past perfect inversion for two closely sequenced events." },
    { text: "The trust has restored a dozen mills, most of ____ now generate electricity.", answers: ["which"], explanation: "'Most of which' is a quantifier plus relative pronoun referring back to the mills." },
    { text: "The critics savaged the production, ____ did nothing to dent ticket sales.", answers: ["which"], explanation: "'Which' introduces a sentential relative clause commenting on the whole preceding statement." },
    { text: "The koala population is recovering, ____ far more slowly than conservationists had hoped.", answers: ["albeit", "though", "if"], explanation: "'Albeit' (or 'though/if') introduces a concessive qualification: recovering, but slowly." },
    { text: "Nowhere else in Europe ____ vines grow at such an altitude.", answers: ["do"], explanation: "The fronted negative 'nowhere else' forces inversion: 'do vines grow'." },
    { text: "The premiere was, by ____ standards, a triumph.", answers: ["any", "all"], explanation: "'By any/all standards' means judged in every reasonable way." },
    { text: "You needn't ____ brought a gift, but it was very kind of you.", answers: ["have"], explanation: "'Needn't have + past participle' says a past action was performed but unnecessary." },
    { text: "The rescue owed as much to luck ____ to skill.", answers: ["as"], explanation: "The comparative frame 'as much to X as to Y' gives equal weight to both factors." },
    { text: "The garrison surrendered rather ____ see the town shelled.", answers: ["than"], explanation: "'Rather than + bare infinitive' expresses the rejected alternative." },
    { text: "The vote was postponed, much to the annoyance of ____ who had travelled overnight to attend.", answers: ["those"], explanation: "'Those who' means the people who; the demonstrative acts as the antecedent of the relative clause." },
    { text: "The manor passed from one spendthrift heir to the ____, shedding land at every turn.", answers: ["next"], explanation: "'From one... to the next' expresses succession through a series." },
    { text: "The orchestra tunes to an A given out ____ the principal oboe.", answers: ["by"], explanation: "'By' marks the agent in this passive construction: the oboe produces the note." },
    { text: "____ having been warned twice, the trawler entered the exclusion zone.", answers: ["despite"], explanation: "'Despite + -ing' introduces a concession; a warning did not prevent the action." },
    { text: "____ intent on winning was he that he barely registered the roar of the crowd.", answers: ["so"], explanation: "Fronted 'So + adjective + was he that...' is an emphatic inverted result structure." },
    { text: "The inquiry heard the informant's evidence ____ camera to protect her identity.", answers: ["in"], explanation: "The legal expression 'in camera' means in private, not in open court." },
    { text: "The species was believed extinct ____ a colony was found on a remote atoll in 2019.", answers: ["until", "till"], explanation: "'Until' marks the point when the belief changed." },
    { text: "There being ____ further questions, the chair brought the meeting to a close.", answers: ["no"], explanation: "The absolute participle clause 'There being no...' formally states the reason for closing." },
    { text: "The recipe hasn't changed ____ so much as a gram since 1907.", answers: ["by"], explanation: "'By' expresses the margin of change; 'not by so much as' emphasises how tiny it is." },
    { text: "It is essential that every diver ____ accompanied by a qualified partner.", answers: ["be"], explanation: "After 'It is essential that', the subjunctive 'be' is used rather than 'is'." },
    { text: "The union demanded that the roster ____ redrawn from scratch.", answers: ["be"], explanation: "Verbs like 'demand' take the subjunctive in the that-clause: 'that it be redrawn'." },
    { text: "The novel reads as ____ it had been translated twice and back again.", answers: ["if", "though"], explanation: "'As if/as though' introduces an unreal comparison, here with the past perfect." },
    { text: "Much ____ I admire her paintings, I could not live with one on my wall.", answers: ["as", "though"], explanation: "'Much as' is a concessive conjunction meaning 'although... very much'." },
    { text: "The comet's tail proved brighter ____ any of the forecasts had suggested.", answers: ["than"], explanation: "The comparative 'brighter' requires 'than' to introduce the standard of comparison." },
    { text: "The chairman spoke first, followed ____ turn by each of the trustees.", answers: ["in"], explanation: "'In turn' means one after another in sequence." },
    { text: "The ruling sets a precedent, the implications of ____ will take years to unfold.", answers: ["which"], explanation: "'The implications of which' is a formal relative structure referring back to the precedent." },
    { text: "____ do you suppose left the gate unbolted last night?", answers: ["who"], explanation: "'Who' is the subject interrogative pronoun; 'do you suppose' is an embedded comment." },
    { text: "The village makes ____ living largely from oysters and summer visitors.", answers: ["its"], explanation: "The possessive determiner 'its' refers back to the village in the idiom 'make a/its living'." },
    { text: "The trek is demanding but by no ____ beyond a reasonably fit beginner.", answers: ["means"], explanation: "'By no means' is a fixed phrase meaning 'not at all'." },
    { text: "The mural survived the renovation purely ____ chance; the contractors ran out of paint.", answers: ["by"], explanation: "'By chance' means accidentally, without planning." },
    { text: "The senator dodged the question, ____ she has done at every press conference this month.", answers: ["as"], explanation: "'As' refers back to the whole action: dodging, which she has done repeatedly." },
    { text: "The plant flowers only once ____ decade, and then for a single night.", answers: ["a"], explanation: "The indefinite article expresses frequency: once a decade, i.e. once per decade." },
    { text: "The path forks at the cairn; ____ branch leads eventually to the summit.", answers: ["either"], explanation: "'Either' before a singular noun means each of the two options equally." },
    { text: "The board could not agree, so the casting vote fell ____ the chair.", answers: ["to"], explanation: "A duty or right 'falls to' the person responsible for exercising it." },
    { text: "Exhausted ____ they were, the climbers refused to abandon the summit bid.", answers: ["though", "as"], explanation: "'Adjective + though/as + subject + verb' is a concessive inversion meaning 'although they were exhausted'." },
    { text: "The tide turned, and with ____ the fortunes of the whole campaign.", answers: ["it"], explanation: "'With it' refers back to the tide; the campaign's fortunes turned along with it." },
    { text: "The scholarship covers tuition; living costs, ____, are the student's own affair.", answers: ["however", "though"], explanation: "'However' as a mid-position connector contrasts the two arrangements." },
    { text: "The bakery's sourdough sells out ____ nine most mornings.", answers: ["by"], explanation: "'By nine' means no later than nine o'clock." },
    { text: "The two theories cannot ____ be right; one at least must fall.", answers: ["both"], explanation: "'Cannot both be right' means it is impossible for the two together to be correct." },
    { text: "The pier was rebuilt after the fire, only for a storm to wreck it ____ again.", answers: ["yet", "once"], explanation: "'Yet again' (or 'once again') emphasises an exasperating repetition." },
    { text: "The clause is buried in ____ small print that few borrowers ever read it.", answers: ["such"], explanation: "'Such + (adjective) noun + that' expresses result before an uncountable noun phrase." },
    { text: "The mayor was re-elected, ____ with a much reduced majority.", answers: ["albeit", "though", "if"], explanation: "'Albeit' introduces a qualifying concession within the same clause." },
    { text: "The debate generated more heat ____ light, as such debates tend to.", answers: ["than"], explanation: "The idiom 'more heat than light' means more anger than understanding; 'than' completes the comparison." },
    { text: "The keys were nowhere to ____ found, so the caretaker forced the lock.", answers: ["be"], explanation: "'Nowhere to be found' is a fixed passive infinitive expression meaning impossible to locate." },
    { text: "The whole cast, myself ____, was reduced to tears at the final curtain.", answers: ["included"], explanation: "'X included' placed after a pronoun means that person too belongs to the group." },
    { text: "The lecture theatre holds three hundred at ____ push.", answers: ["a"], explanation: "'At a push' means only with difficulty, as an absolute maximum." },
    { text: "____ accounts for the sudden collapse of a colony that had thrived for decades?", answers: ["what"], explanation: "'What' serves as the subject of the question: what thing explains the collapse." },
    { text: "The fine amounts to little short ____ a week's wages for most residents.", answers: ["of"], explanation: "'Little short of' means almost the same as, nearly." },
    { text: "The ambassador insisted ____ meeting the hostages' families in person.", answers: ["on", "upon"], explanation: "The verb 'insist' takes the dependent preposition 'on/upon' before a gerund." },
    { text: "The species is protected by law; even ____, poaching persists.", answers: ["so"], explanation: "'Even so' means despite that fact." },
    { text: "The ferry crossing takes six hours, give or ____ half an hour depending on the tide.", answers: ["take"], explanation: "'Give or take' is a fixed expression indicating an approximate margin." },
    { text: "Not only ____ the drought ruined the harvest, it has emptied the reservoirs too.", answers: ["has"], explanation: "Fronted 'not only' triggers inversion with the auxiliary of the present perfect." },
    { text: "The bell tower has leaned a little further every year for as ____ back as records exist.", answers: ["far"], explanation: "'As far back as' extends a time reference to the earliest available point." },
    { text: "Opinions differ as to ____ the manuscript should be restored at all.", answers: ["whether"], explanation: "'As to whether' introduces an indirect yes/no question about which people disagree." },
    { text: "The stray was adopted by the fire crew and has lived at the station ever ____.", answers: ["since"], explanation: "'Ever since' used adverbially at the end of a clause means from that time until now." },
    { text: "The trial drug performed no better than the placebo, and in some patients considerably ____.", answers: ["worse"], explanation: "The comparative 'worse' contrasts with 'no better', completing the parallel structure." },
    { text: "Even at close quarters, the examiner could not tell the twins ____.", answers: ["apart"], explanation: "'Tell X apart' means to distinguish between two very similar people or things." },
    { text: "The volunteers worked around the clock, and it is to them ____ the credit belongs.", answers: ["that"], explanation: "A cleft with a fronted prepositional phrase: 'it is to them that...' emphasises the recipients." },
    { text: "The manuscript will be displayed under glass, and rightly ____, given its fragility.", answers: ["so"], explanation: "'Rightly so' uses 'so' as a pro-form standing for the whole previous statement." },
    { text: "____ the applicants were all rejected says more about the process than about them.", answers: ["that"], explanation: "A that-clause acts as the subject of the sentence: 'That they were rejected says...'." },
    { text: "The chalet sleeps six ____ a pinch.", answers: ["at"], explanation: "'At a pinch' means if absolutely necessary, though not comfortably." },
    { text: "The reforms were welcomed by economists but met ____ fierce resistance from the unions.", answers: ["with"], explanation: "'Meet with resistance/approval' is the collocation for encountering a reaction." },
    { text: "The tunnel floods at spring tides, ____ which times the path along the cliff must be used.", answers: ["at", "during"], explanation: "'At which times' is a formal relative phrase referring back to the spring tides." },
    { text: "The professor is on sabbatical, so her seminars have been taken ____ by a colleague.", answers: ["over"], explanation: "'Take over' means to assume responsibility for something from someone else." },
    { text: "The country's exports consist largely ____ copper and cut flowers.", answers: ["of"], explanation: "'Consist of' is the fixed verb-preposition pairing for composition." },
    { text: "The raft would have been spotted on the first pass ____ for the fog.", answers: ["but"], explanation: "'But for' means 'if it had not been for', introducing the factor that prevented something." },
    { text: "The tenancy may be terminated by ____ party on two months' notice.", answers: ["either"], explanation: "'Either party' means whichever of the two parties chooses to act." },
    { text: "The plot is preposterous, but that is beside the ____; the dialogue simply sparkles.", answers: ["point"], explanation: "'Beside the point' means irrelevant to the matter being judged." },
    { text: "The city has changed beyond ____ recognition since the shipyards closed.", answers: ["all"], explanation: "'Beyond all recognition' intensifies the idiom: changed so much as to be unrecognisable." },
    { text: "The choir rehearses on Tuesdays except in exam season, ____ attendance becomes optional.", answers: ["when"], explanation: "'When' is a relative adverb referring back to exam season." },
    { text: "The auditors combed the ledgers to no ____; the missing funds were never traced.", answers: ["avail"], explanation: "'To no avail' is a fixed phrase meaning without success." },
    { text: "The bees do the pollinating; humans, for the most ____, merely take the credit.", answers: ["part"], explanation: "'For the most part' means generally, in most cases." },
    { text: "The mine closed in 1984, taking with ____ the livelihood of half the valley.", answers: ["it"], explanation: "'Taking with it' means the closure carried away the livelihoods; 'it' refers to the mine's closing." },
    { text: "The safety card is printed in six languages, none of ____ the cabin crew actually speak.", answers: ["which"], explanation: "'None of which' combines a quantifier with the relative pronoun for the languages." },
    { text: "The gallery insured the loan for far more ____ it was later found to be worth.", answers: ["than"], explanation: "'More... than' completes the comparison between the insured sum and the true value." },
    { text: "The chairman resigned at once, ____ sparing the board the trouble of dismissing him.", answers: ["thereby", "thus"], explanation: "'Thereby/thus + -ing' shows the result achieved by the action just mentioned." },
    { text: "____ arrives first should switch on the ovens and unlock the yard.", answers: ["whoever"], explanation: "'Whoever' means 'the person who, no matter who', acting as the subject." },
    { text: "You can pay in instalments or, ____ you prefer, settle the whole sum up front.", answers: ["if", "should"], explanation: "'If you prefer' offers an alternative conditional on the listener's preference." },
    { text: "The border reopened last month, allowing divided families to visit one ____ at last.", answers: ["another"], explanation: "The reciprocal pronoun 'one another' means each visiting the other." },
    { text: "The peninsula is all ____ cut off in winter, reachable only by snowmobile.", answers: ["but"], explanation: "'All but' means almost completely." },
    { text: "The soup could do with a little ____ in the way of seasoning, but otherwise it is superb.", answers: ["more"], explanation: "'A little more in the way of X' is a hedged way of saying it needs additional X." },
    { text: "The verdict, ____ it disappointed the family, at least brought the ordeal to an end.", answers: ["while", "though", "although", "whilst"], explanation: "'While/though' introduces a concessive clause acknowledging the disappointment." },
    { text: "The bursary goes to ____ candidate shows the greatest promise, regardless of background.", answers: ["whichever", "whatever"], explanation: "'Whichever + noun' means the one, no matter which, that meets the condition." },
    { text: "The stadium was barely half full, ____ the club blamed on the televised kick-off time.", answers: ["which"], explanation: "'Which' refers to the whole preceding fact and serves as the object of 'blamed'." },
    { text: "The engineers worked ____ the assumption that the bedrock was granite; it turned out to be clay.", answers: ["on", "under"], explanation: "'On/under the assumption that' means basing one's actions on a supposed fact." },
    { text: "The negotiations are at ____ delicate a stage for any public comment.", answers: ["too"], explanation: "'Too + adjective + a + noun' is the required order: at too delicate a stage." },
    { text: "The postmistress knows everyone's business, or likes to think she ____.", answers: ["does"], explanation: "'Does' substitutes for the whole verb phrase 'knows everyone's business'." },
    { text: "The fresco owes its survival to having been whitewashed ____ than destroyed.", answers: ["rather"], explanation: "'Rather than' contrasts what happened with the alternative that did not." },
    { text: "The trawlermen put to sea in all weathers, as their fathers had done ____ them.", answers: ["before"], explanation: "'Before them' means in earlier generations, preceding the present ones." },
    { text: "The award came too late for the poet, ____ had died the previous winter.", answers: ["who"], explanation: "'Who' introduces a non-defining relative clause about the poet." },
    { text: "The refit will take eight months, during ____ time the ferry route will be suspended.", answers: ["which"], explanation: "'During which time' is a formal relative phrase meaning throughout that period." },
    { text: "The syllabus assumes no prior knowledge ____ of statistics or of programming.", answers: ["either"], explanation: "'Either... or' pairs the two excluded areas; 'either' precedes the first." },
    { text: "The orchid mimics the wasp so faithfully ____ males attempt to mate with the flower.", answers: ["that"], explanation: "'So + adverb + that' introduces the resulting behaviour." },
    { text: "The mill wheel grinds no corn these days; it is kept turning for old times' ____.", answers: ["sake"], explanation: "'For old times' sake' means in memory of the past, out of sentiment." }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part2 = QUESTIONS.part2.concat(BANK);
})();
