/* CAE Prep extra bank: part2 wave 2 */
(function () {
  var BANK = [
    { text: "Rarely ____ a documentary provoked such a fierce backlash from the scientific community.", answers: ["has"], explanation: "After the negative adverb 'rarely' at the start of a sentence, subject and auxiliary invert: 'rarely has a documentary provoked'." },
    { text: "The lighthouse keeper's logbooks, many of ____ date back to the 1850s, are being digitised.", answers: ["which"], explanation: "In a non-defining relative clause with a quantifier, 'many of which' refers back to the logbooks." },
    { text: "____ the ferry to be withdrawn, the island would lose its only year-round link to the mainland.", answers: ["were"], explanation: "Inverted conditional: 'Were the ferry to be withdrawn' is a formal alternative to 'If the ferry were to be withdrawn'." },
    { text: "It was the violinist's phrasing, rather than her technique, ____ won over the sceptical jury.", answers: ["that", "which"], explanation: "This is a cleft sentence ('It was X that...'); 'that' (or 'which') completes the emphasised structure." },
    { text: "The reef has recovered to some extent, ____ nowhere near its former abundance.", answers: ["though", "albeit", "but", "if"], explanation: "A concessive linker introduces the contrast: 'though/albeit/but/if nowhere near its former abundance'." },
    { text: "____ having rehearsed the speech for weeks, he froze the moment the cameras rolled.", answers: ["despite", "notwithstanding"], explanation: "'Despite' (or formal 'notwithstanding') is followed by an -ing form to express concession." },
    { text: "The committee insisted that the report ____ published in full, appendices included.", answers: ["be"], explanation: "After 'insist that', the subjunctive uses the base form: 'that the report be published'." },
    { text: "Little ____ the villagers suspect that the quiet newcomer was a celebrated novelist.", answers: ["did"], explanation: "The negative adverbial 'little' triggers inversion with the auxiliary: 'Little did the villagers suspect'." },
    { text: "The orchard yields barely a tenth of ____ it produced in its heyday.", answers: ["what"], explanation: "'What' acts as a fused relative meaning 'that which': a tenth of what it produced." },
    { text: "Cyclists must dismount ____ crossing the footbridge during peak hours.", answers: ["when", "while", "before"], explanation: "A conjunction plus -ing form: 'when/while/before crossing' is a reduced time clause." },
    { text: "The archive was saved from the flood thanks ____ the quick thinking of two librarians.", answers: ["to"], explanation: "The fixed expression 'thanks to' attributes a positive outcome to a cause." },
    { text: "____ all intents and purposes, the negotiations ended the moment the delegation walked out.", answers: ["to"], explanation: "The idiom 'to all intents and purposes' means 'in effect, virtually'." },
    { text: "The glacier is retreating at ____ rate of nearly forty metres a year.", answers: ["a", "the"], explanation: "The pattern 'at a/the rate of + measurement' requires an article before 'rate'." },
    { text: "He tends to speak his mind, ____ the consequences.", answers: ["whatever"], explanation: "'Whatever the consequences' is an elliptical concessive clause meaning 'no matter what the consequences are'." },
    { text: "The manuscript might never have surfaced ____ it not been mislabelled in the first place.", answers: ["had"], explanation: "Inverted third conditional: 'had it not been mislabelled' replaces 'if it had not been mislabelled'." },
    { text: "____ the naked eye, the two diamonds are utterly indistinguishable.", answers: ["to"], explanation: "The fixed phrase 'to the naked eye' means 'as seen without magnification'." },
    { text: "The trail is passable in summer; in winter, ____ the other hand, it demands full alpine equipment.", answers: ["on"], explanation: "The contrastive discourse marker is 'on the other hand'." },
    { text: "Every effort is ____ made to reunite lost luggage with its owners.", answers: ["being"], explanation: "Present continuous passive: 'is being made' describes an ongoing process." },
    { text: "The apiary produces honey ____ flavour varies with whatever happens to be flowering.", answers: ["whose"], explanation: "'Whose' is the possessive relative pronoun, used here for a thing: honey whose flavour varies." },
    { text: "The senator would not confirm the figures, ____ would she deny them outright.", answers: ["nor", "neither"], explanation: "'Nor/neither + inverted auxiliary' adds a second negative statement: 'nor would she deny them'." },
    { text: "It is high time the ferry timetable ____ brought into line with the trains.", answers: ["was", "were"], explanation: "After 'it is high time', a past form (or subjunctive 'were') expresses that something should already have happened." },
    { text: "The fresco had deteriorated to ____ an extent that restoration was deemed impossible.", answers: ["such"], explanation: "The pattern 'to such an extent that' expresses degree leading to a result." },
    { text: "Not for nothing ____ Venice known as La Serenissima.", answers: ["is", "was"], explanation: "The fronted negative phrase 'not for nothing' forces inversion: 'Not for nothing is Venice known...'." },
    { text: "The recipe calls ____ a pinch of saffron, which accounts for its golden hue.", answers: ["for"], explanation: "The phrasal verb 'call for' means 'to require' an ingredient or action." },
    { text: "Should the drought persist, water will have to be rationed, ____ it or not.", answers: ["like"], explanation: "The fixed expression 'like it or not' means 'whether or not you approve'." },
    { text: "Take an umbrella, ____ case the forecast turns out to be right for once.", answers: ["in"], explanation: "'In case' introduces a precaution against a possible event." },
    { text: "The tenor was in magnificent voice, a fact ____ which every critic remarked.", answers: ["on", "upon"], explanation: "The verb 'remark' takes the preposition 'on/upon': 'a fact on which every critic remarked'." },
    { text: "The vaccine must be stored at minus seventy degrees, failing ____ it rapidly loses potency.", answers: ["which"], explanation: "The formal connector 'failing which' means 'and if this is not done'." },
    { text: "____ a stroke, the new tariff wiped out the exporters' entire margin.", answers: ["at"], explanation: "The idiom 'at a stroke' means 'with a single sudden action'." },
    { text: "The documentary lets the survivors speak ____ themselves, with no narrator to guide us.", answers: ["for"], explanation: "'Speak for themselves/oneself' means to express one's own view directly." },
    { text: "So convincing was the forgery ____ it hung in the museum for thirty years.", answers: ["that"], explanation: "Inverted 'so + adjective' pattern: 'So convincing was the forgery that...' expresses result." },
    { text: "The observatory sits at 5,000 metres, ____ makes it the highest of its kind.", answers: ["which"], explanation: "'Which' introduces a sentential relative clause commenting on the whole preceding statement." },
    { text: "Book early, ____ you risk paying double for the same cabin.", answers: ["or", "otherwise"], explanation: "'Or/otherwise' after an imperative introduces the negative consequence of not complying." },
    { text: "It was not until the thaw ____ the climbers' tent was finally recovered.", answers: ["that"], explanation: "Cleft structure: 'It was not until X that Y happened' emphasises the time element." },
    { text: "The two dialects are mutually intelligible, ____ with some effort on both sides.", answers: ["albeit", "though", "if"], explanation: "'Albeit/though/if' introduces a concessive qualification: intelligible, albeit with some effort." },
    { text: "The curator would rather the sketches ____ displayed under subdued lighting.", answers: ["were"], explanation: "'Would rather + subject' takes a past subjunctive: 'would rather the sketches were displayed'." },
    { text: "The premium depends on the driver's age, ____ well as on the vehicle's value.", answers: ["as"], explanation: "The additive linker 'as well as' means 'in addition to'." },
    { text: "____ things stand, the tunnel will not open before the end of the decade.", answers: ["as"], explanation: "The fixed expression 'as things stand' means 'in the current situation'." },
    { text: "The colony collapsed within weeks, ____ beekeepers still cannot fully explain.", answers: ["which"], explanation: "'Which' refers back to the entire event of the collapse in a sentential relative clause." },
    { text: "Try as they ____, the engineers could not trace the source of the vibration.", answers: ["might"], explanation: "The concessive formula 'try as they might' means 'however hard they tried'." },
    { text: "The applause died ____ almost as soon as the conductor raised his baton.", answers: ["down", "away"], explanation: "The phrasal verb 'die down/away' means to gradually fade to silence." },
    { text: "The fort was built ____ the orders of a king who never once visited it.", answers: ["on"], explanation: "The phrase 'on the orders of' means 'as commanded by'." },
    { text: "There is little to choose ____ the two finalists in terms of raw talent.", answers: ["between"], explanation: "The idiom 'little to choose between' means the two are almost equal." },
    { text: "Hard ____ it is to believe, the entire score was composed in a single weekend.", answers: ["as", "though"], explanation: "Fronted concessive structure: 'Hard as/though it is to believe' means 'although it is hard to believe'." },
    { text: "The lease expires next spring, by ____ time the studio hopes to have relocated.", answers: ["which"], explanation: "'By which time' links a deadline to the preceding clause in formal relative style." },
    { text: "The chef refuses to open a second restaurant for fear ____ diluting the first.", answers: ["of"], explanation: "The pattern 'for fear of + -ing' expresses a precaution against an undesired outcome." },
    { text: "No matter ____ carefully the nets are checked, some plastic always slips through.", answers: ["how"], explanation: "'No matter how + adverb' forms a concessive clause: however carefully they are checked." },
    { text: "The witness spoke so softly ____ to be almost inaudible from the gallery.", answers: ["as"], explanation: "The formal result pattern 'so + adverb + as to + infinitive' expresses degree." },
    { text: "The typeface was designed with legibility ____ mind, even at the smallest sizes.", answers: ["in"], explanation: "The fixed phrase 'with something in mind' means it was a deliberate consideration." },
    { text: "____ we to lose the appeal, the demolition could begin within days.", answers: ["were"], explanation: "Inverted hypothetical conditional: 'Were we to lose' equals 'If we were to lose'." },
    { text: "Success in translation lies not in fidelity alone ____ in capturing a voice.", answers: ["but"], explanation: "The correlative 'not... but...' contrasts what something is not with what it is." },
    { text: "The reservoir is now ____ full capacity for the first time in a decade.", answers: ["at"], explanation: "The collocation is 'at full capacity', meaning completely full." },
    { text: "____ whom should I address the letter of complaint?", answers: ["to"], explanation: "The verb pattern is 'address a letter to someone'; the preposition is fronted before 'whom' in formal questions." },
    { text: "The comet will not be visible again ____ another seventy-six years.", answers: ["for"], explanation: "'For' introduces the duration: not visible for another seventy-six years." },
    { text: "The village lay cut ____ for six days after the avalanche.", answers: ["off"], explanation: "The phrasal verb 'cut off' means isolated or without access." },
    { text: "The cottage comes complete ____ its own jetty and boathouse.", answers: ["with"], explanation: "The fixed pattern 'come complete with' means to include something as part of the package." },
    { text: "The auditors uncovered discrepancies too numerous ____ list in a single report.", answers: ["to"], explanation: "The pattern 'too + adjective + to + infinitive' expresses excess: too numerous to list." },
    { text: "The falcon population has trebled since the pesticide ban, proof, ____ any were needed, that regulation works.", answers: ["if"], explanation: "The parenthetical 'if any were needed' means 'supposing proof were required at all'." },
    { text: "Far ____ being a deterrent, the fines seem to have been priced in as a cost of business.", answers: ["from"], explanation: "'Far from + -ing' asserts that the opposite of the stated idea is true." },
    { text: "The old mill has been converted ____ artists' studios.", answers: ["into"], explanation: "The verb 'convert' takes 'into' to describe a change of function or form." },
    { text: "Not ____ accustomed to the altitude, the film crew struggled badly.", answers: ["being"], explanation: "A negative participle clause: 'Not being accustomed to' gives the reason for the struggle." },
    { text: "The satellite went silent mid-orbit, never ____ be heard from again.", answers: ["to"], explanation: "'Never to be heard from again' is an infinitive of (non-)outcome describing what followed." },
    { text: "The inquiry found the airline ____ blame for the near miss.", answers: ["to"], explanation: "The fixed expression 'to blame (for)' means responsible for something bad." },
    { text: "____ short of a miracle can save the season now.", answers: ["nothing"], explanation: "'Nothing short of X' means only X, and nothing less dramatic, would suffice." },
    { text: "The vineyard has been in the same family ____ five generations.", answers: ["for"], explanation: "With the present perfect, 'for' marks the length of a period: for five generations." },
    { text: "The plot twists come thick and fast, ____ times almost too fast to follow.", answers: ["at"], explanation: "The adverbial 'at times' means 'sometimes, occasionally'." },
    { text: "Whether the fresco is genuine ____ a later imitation remains hotly contested.", answers: ["or"], explanation: "'Whether... or...' presents the two alternatives under dispute." },
    { text: "____ little remains of the abbey is fenced off for safety.", answers: ["what"], explanation: "'What' is a fused relative meaning 'the (little) amount that': what little remains." },
    { text: "The negotiations dragged on late into the night, ____ no agreement in sight.", answers: ["with"], explanation: "The absolute construction 'with + noun + complement' adds attendant circumstances: with no agreement in sight." },
    { text: "Only when the tide recedes ____ the shipwreck become visible.", answers: ["does"], explanation: "'Only when...' at the front of a sentence triggers auxiliary inversion in the main clause." },
    { text: "Rumour has ____ that the two chains are on the point of merging.", answers: ["it"], explanation: "The fixed expression 'rumour has it that' means 'it is rumoured that'." },
    { text: "____ was once a thriving fishing port is now a marina for weekend sailors.", answers: ["what"], explanation: "'What' introduces a nominal relative clause acting as the subject: 'that which was once a port'." },
    { text: "The panel deemed the bridge design flawed ____ its very conception.", answers: ["in", "from"], explanation: "'Flawed in/from its very conception' means defective from the earliest stage of the idea." },
    { text: "The tenor's farewell tour was, ____ effect, a year-long lap of honour.", answers: ["in"], explanation: "The discourse marker 'in effect' means 'in practical terms, essentially'." },
    { text: "Not one delegate raised a hand, ____ did anyone speak against the motion.", answers: ["nor", "neither"], explanation: "'Nor/neither + inverted auxiliary' continues a negative statement: nor did anyone speak." },
    { text: "The refund will be processed within ten days ____ receipt of the faulty goods.", answers: ["of"], explanation: "The formal pattern 'within X days of + event' fixes the deadline relative to that event." },
    { text: "____ hindsight, the warning signs had been there all along.", answers: ["in", "with"], explanation: "'In/with hindsight' means looking back with knowledge one lacked at the time." },
    { text: "The summit ended ____ either side conceding an inch.", answers: ["without"], explanation: "'Without + noun + -ing' expresses that the action did not happen: without either side conceding." },
    { text: "He paused, as ____ weighing whether to say more.", answers: ["if", "though"], explanation: "'As if/though + -ing' describes an appearance or impression: as if weighing his words." },
    { text: "The keynote overran ____ a full twenty minutes, throwing the whole schedule out.", answers: ["by"], explanation: "'By' expresses the margin of excess: overran by twenty minutes." },
    { text: "The bakery has changed hands three times, each owner less successful ____ the last.", answers: ["than"], explanation: "The comparative 'less successful' requires 'than' before the point of comparison." },
    { text: "It is ____ wonder the cellars flood, given the river runs beneath the street.", answers: ["no", "little", "small"], explanation: "The idiom 'it is no/little/small wonder (that)' means the outcome is unsurprising." },
    { text: "The choir sang as ____ their lives depended on it.", answers: ["if", "though"], explanation: "'As if/though' introduces an unreal comparison describing the intensity of the singing." },
    { text: "The dig was suspended ____ a dispute over who owns the land could be resolved.", answers: ["until", "till"], explanation: "'Until/till' marks the point up to which the suspension lasts." },
    { text: "Weather ____, the eclipse should be visible from the entire east coast.", answers: ["permitting"], explanation: "The fixed absolute phrase 'weather permitting' means 'if the weather allows'." },
    { text: "The detective said nothing, ____ her silence spoke volumes.", answers: ["but", "though", "yet"], explanation: "A contrastive conjunction links the clauses: she said nothing, but/yet her silence was eloquent." },
    { text: "____ my knowledge, no one has ever swum the strait in winter.", answers: ["to"], explanation: "The fixed phrase 'to my knowledge' means 'as far as I know'." },
    { text: "____ many as forty species of orchid grow within the reserve.", answers: ["as"], explanation: "The quantifying pattern 'as many as forty' emphasises that the number is surprisingly high." },
    { text: "The team pressed forward in numbers, leaving ____ exposed at the back.", answers: ["themselves"], explanation: "The reflexive pronoun 'themselves' refers back to the team as the object of 'leaving'." },
    { text: "The judge ruled that the evidence, ____ compelling, had been unlawfully obtained.", answers: ["however", "though", "albeit", "while"], explanation: "A concessive word before the adjective: 'however/though/albeit compelling' concedes its strength." },
    { text: "The prices are steep, but you get ____ you pay for.", answers: ["what"], explanation: "The idiom 'you get what you pay for' uses 'what' as a fused relative pronoun." },
    { text: "Roughly one ____ five adults in the survey admitted to skipping breakfast.", answers: ["in"], explanation: "Proportions are expressed with 'one in five', meaning twenty per cent." },
    { text: "The film is based, ____ loosely, on a true story of wartime espionage.", answers: ["albeit", "if", "though", "however"], explanation: "A concessive qualifier before the adverb: 'albeit/if loosely' means 'although only loosely'." },
    { text: "Not a single lifeboat drill had been carried ____ before the voyage.", answers: ["out"], explanation: "The phrasal verb 'carry out' means to perform or conduct a procedure." },
    { text: "The two paintings hang side ____ side in the west gallery.", answers: ["by"], explanation: "The fixed expression 'side by side' means next to each other." },
    { text: "____ per the terms of the will, the cottage passes to the youngest niece.", answers: ["as"], explanation: "The formal phrase 'as per' means 'in accordance with'." },
    { text: "The engine cut out mid-flight and, worse ____, the radio failed too.", answers: ["still", "yet"], explanation: "'Worse still/yet' introduces an additional and more serious problem." },
    { text: "The council has ____ to respond to the petition, three months on.", answers: ["yet"], explanation: "'Have yet to + infinitive' means the action has still not happened." },
    { text: "The garden opens to the public once a year, usually ____ late May.", answers: ["in"], explanation: "The preposition 'in' is used with parts of months: in late May." },
    { text: "The couple made it to the wedding ____ having their flight cancelled twice.", answers: ["despite", "notwithstanding"], explanation: "'Despite/notwithstanding + -ing' concedes an obstacle that did not prevent the outcome." },
    { text: "One drug proved effective in trials; the ____ was quietly abandoned.", answers: ["other"], explanation: "With two items, 'the other' refers to the remaining one of the pair." },
    { text: "The lecture ran an hour ____ schedule, to nobody's surprise.", answers: ["behind", "over"], explanation: "'Behind schedule' (or informally 'over schedule') means later than planned." },
    { text: "Every ____ often, the volcano vents a plume of steam.", answers: ["so"], explanation: "The fixed expression 'every so often' means 'occasionally'." },
    { text: "The startup was valued ____ two billion at its peak.", answers: ["at"], explanation: "The verb 'value' takes 'at' before the figure: valued at two billion." },
    { text: "The path is steep and, in places, little more ____ a scramble over loose rock.", answers: ["than"], explanation: "'Little more than' means 'hardly anything other than', requiring 'than' after the comparative 'more'." },
    { text: "The stadium roof retracts in ____ under eight minutes.", answers: ["just", "well"], explanation: "'Just under' means slightly less than; 'well under' means considerably less than." },
    { text: "The two towers differ in height ____ a matter of centimetres.", answers: ["by"], explanation: "'By' expresses the margin of difference: differ by a matter of centimetres." },
    { text: "The garrison held out for months ____ overwhelming odds.", answers: ["against", "despite"], explanation: "'Against/despite overwhelming odds' means in the face of a very unfavourable situation." },
    { text: "____ time the choir meets, a different member chooses the programme.", answers: ["each", "every"], explanation: "'Each/every time' functions as a conjunction meaning 'whenever'." },
    { text: "The heron stood motionless, for ____ the world a statue carved in grey.", answers: ["all"], explanation: "The idiom 'for all the world (like)' means 'exactly as if it were'." },
    { text: "The premiere was postponed ____ account of a dispute over royalties.", answers: ["on"], explanation: "The formal phrase 'on account of' means 'because of'." },
    { text: "The trial run exposed flaws that no ____ of simulation had predicted.", answers: ["amount"], explanation: "'No amount of X' means that even a very large quantity of X would not have sufficed." },
    { text: "The whale surfaced barely a boat's length ____ from the astonished tourists.", answers: ["away"], explanation: "'Away from' expresses distance: a boat's length away from the tourists." },
    { text: "____ does the handbook mention compensation, nor does the contract.", answers: ["nowhere", "neither"], explanation: "A fronted negative ('Nowhere/Neither') forces inversion and pairs with the following 'nor' clause." },
    { text: "The recipe works just as well ____ you substitute honey for sugar.", answers: ["if", "when"], explanation: "'If/when' introduces the condition under which the recipe still works." },
    { text: "The ambassador is nothing if ____ diplomatic in her public statements.", answers: ["not"], explanation: "The idiom 'nothing if not + adjective' strongly asserts the quality: extremely diplomatic." },
    { text: "The orchard was planted ____ the express instruction of the composer himself.", answers: ["at", "on"], explanation: "'At/on the instruction of' means as ordered or requested by someone." },
    { text: "____ so many of his generation, he learned English from the radio.", answers: ["like"], explanation: "'Like' introduces a comparison with a noun phrase: like so many of his generation." },
    { text: "The results have been double-checked, so there can be no question ____ a recount.", answers: ["of"], explanation: "The pattern 'no question of + noun/-ing' means the possibility is excluded." },
    { text: "The city grew rich ____ the back of the spice trade.", answers: ["on", "off"], explanation: "The idiom 'on/off the back of' means as a result of, or by exploiting, something." },
    { text: "Few inventions have changed daily life to the degree ____ the smartphone has.", answers: ["that"], explanation: "'To the degree that' introduces the clause of comparison or extent." },
    { text: "The witness could not say for ____ whether the car had stopped at the lights.", answers: ["certain", "sure"], explanation: "The fixed phrase 'for certain/for sure' means 'with complete certainty'." },
    { text: "The monastery brews its own ale, the proceeds of ____ fund its restoration.", answers: ["which"], explanation: "'The proceeds of which' is a formal relative structure referring back to the ale sales." },
    { text: "____ it any wonder the show was cancelled, given the ratings?", answers: ["is", "was"], explanation: "The rhetorical question 'Is/Was it any wonder...?' implies the outcome was entirely predictable." },
    { text: "The floodwater rose so fast that residents had no choice ____ to abandon their homes.", answers: ["but"], explanation: "The pattern 'no choice but to + infinitive' means the action was unavoidable." },
    { text: "The fresco was restored at great expense, only ____ vandals to deface it within a week.", answers: ["for"], explanation: "'Only for + noun + to-infinitive' introduces an ironic or disappointing sequel." },
    { text: "The senator's memoir, due ____ next spring, is already courting controversy.", answers: ["out"], explanation: "'Due out' means scheduled to be published or released." },
    { text: "The band split up ____ the height of their fame, never to reunite.", answers: ["at"], explanation: "The fixed phrase 'at the height of' means at the peak or most intense point." },
    { text: "So ____ as the levee holds, the town has nothing to fear.", answers: ["long"], explanation: "The conjunction 'so long as' means 'provided that, on condition that'." },
    { text: "The costume department made do ____ whatever fabric could be found in wartime.", answers: ["with"], explanation: "The phrasal expression 'make do with' means to manage using an inferior substitute." }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part2 = QUESTIONS.part2.concat(BANK);
})();
