(function () {
var BANK = [
  {
    id: "c-rgap4-01",
    title: "The Rivers Beneath the Streets",
    segments: [
      "Stand over a certain grating on a quiet street in almost any old city and, when the traffic pauses, you will hear it: the unmistakable rush of moving water, metres below the tarmac. It is not a leaking main. It is a river — one with a name, a source and, once, salmon — flowing through the dark exactly where it has always flowed, under offices and bus lanes that have forgotten it exists.",
      "The burial was, by the standards of its time, a triumph. Disease retreated, land values soared on the new streets, and the city gained boulevards where there had been stinking gullies. But the engineers had not abolished the rivers; they had merely deferred them, and the costs of that deferral are now falling due.",
      "Hydrologists were the first to take that ghost seriously, but they are no longer alone. Local historians publish maps of the vanished watercourses, artists mark their routes with brass studs in the pavement, and guided walks trace valleys that survive only as gentle dips in otherwise inexplicable places.",
      "The engineering case for such restorations is surprisingly strong. An open channel carries storm water that no buried pipe can match, a corridor of water cools the streets around it in heatwaves, and species return with a speed that startles even the ecologists who predicted it.",
      "Advocates concede the point and answer it with selectivity. Nobody proposes exhuming a river beneath a railway terminus; the candidates are stretches under parks, car parks and sites already scheduled for redevelopment, where the digging must happen anyway and a stream costs little more than another culvert.",
      "Sceptics enjoy pointing out that the celebrated stream is not entirely natural — its flow is partly maintained by pumping, its banks are engineered, and its restoration displaced traders whose grievances outlasted the ribbon-cutting. As a piece of hydrology it is imperfect; even its admirers concede as much.",
      "So the next time you cross a street that dips for no obvious reason, or pass a grating that seems to whisper, pause. The city has a memory, and it flows downhill. What the nineteenth century buried in brick, the twenty-first is learning, cautiously and stretch by stretch, to forgive."
    ],
    options: [
      "Out of that renewed attention has grown something considerably more ambitious than nostalgia. Daylighting — the practice of excavating a culverted stream and returning it to the open air — has moved from fringe proposal to municipal policy, with completed schemes in Zurich, Seoul and a scatter of smaller towns that discovered a river was the cheapest park they could build.",
      "The aqueducts of the ancient world worked on the opposite principle, carrying clean water into cities across arches that advertised the achievement to every approaching traveller, and their builders would have found the idea of hiding a watercourse frankly incomprehensible.",
      "These rivers were not lost by accident. As the city swelled, its streams became open sewers, blamed with some justice for the epidemics that repeatedly emptied the districts along their banks, and the Victorians responded with characteristic confidence: they entombed them, one by one, in brick culverts, and laid streets over the top.",
      "The showcase for the movement remains the stream in central Seoul, released in the early 2000s from beneath an elevated motorway that was demolished to free it. Summer temperatures along the corridor dropped measurably, wildlife returned to the heart of a megacity, and the walkway now draws tens of thousands of visitors a day.",
      "Chief among those deferred costs is flooding. A buried river still drains its ancient valley, but through a pipe sized for the rainfall of 1860, and when a modern storm exceeds that allowance the water goes looking for its old route — surfacing in basements and junctions that appear on no floodplain map, yet follow, street by street, the course of the vanished stream.",
      "Perhaps, though, the symbolism is not a weakness but the point. A city that uncovers a river is making an unusual public admission — that an earlier generation's confident engineering created problems as well as solving them — and citizens who have watched one buried mistake corrected begin to ask, usefully, what else lies under their feet.",
      "Yet the objections are not trivial. A culverted river typically has a working street above it, with gas mains, fibre optics and sewers braided around the old brickwork, so that exhuming even a few hundred metres means years of diversions and a bill that makes councillors blanch. Daylighting is cheap only where the land above is already empty."
    ],
    answers: [2, 4, 0, 6, 3, 5],
    explanations: [
      "The opening segment describes a named river flowing beneath the street; the correct paragraph's \"These rivers were not lost by accident\" refers straight back to it and explains the Victorian entombment, which the next segment then calls \"The burial... a triumph\".",
      "The previous segment ends with deferral and \"costs... now falling due\"; the correct paragraph opens \"Chief among those deferred costs is flooding\" and its image of water following \"the course of the vanished stream\" supplies the \"ghost\" the next segment says hydrologists took seriously.",
      "The previous segment lists historians, artists and guided walks; \"Out of that renewed attention has grown something considerably more ambitious than nostalgia\" picks up exactly that attention and introduces daylighting, the \"restorations\" whose engineering case the next segment assesses.",
      "The previous segment gives the engineering case in favour; the correct paragraph's \"Yet the objections are not trivial\" turns to cost and disruption, and the next segment's \"Advocates concede the point and answer it with selectivity\" responds directly to those objections.",
      "The previous segment says candidates are parks and redevelopment sites; the correct paragraph presents \"The showcase for the movement\", the Seoul stream, and the next segment's \"the celebrated stream is not entirely natural\" refers straight back to that showcase.",
      "The previous segment lists the sceptics' complaints that the scheme is symbolic and imperfect; \"Perhaps, though, the symbolism is not a weakness but the point\" answers them directly, and its citizens asking \"what else lies under their feet\" leads into the closing segment's dipping streets and whispering gratings."
    ]
  },
  {
    id: "c-rgap4-02",
    title: "A Second Life for the Red Phone Box",
    segments: [
      "It stands on the village green as it has stood for ninety years: cast iron, imperial red, its small panes polished by somebody who evidently cares. Only when you pull open the heavy door does the twenty-first century intrude, for where the telephone once hung there is now a shelf of paperbacks, a notice about the summer fete, and a box of dog biscuits labelled 'help yourself'.",
      "Rather than scrap the survivors wholesale, the operator tried something stranger: it offered them for adoption. For the price of one pound, a parish council or community group could buy the kiosk outright — the company kept the phone line, or removed it — and take on the little building's future itself.",
      "Defibrillators are only the most practical of the conversions. Elsewhere the kiosks have become miniature art galleries hung with a single painting, seed-exchange cupboards, information points for coastal walkers, and, in at least one enterprising village, the smallest coffee shop in the country, staffed through a hatch on Saturday mornings.",
      "Not every adoption flourishes, however. Walk through some villages and you will find a kiosk with mould creeping up the glass, a heap of swollen paperbacks and a laminated notice from 2019 — adopted with enthusiasm, then quietly abandoned when the founding volunteer moved away.",
      "Beyond utility, there is a quieter argument about heritage. The kiosk is one of the few pieces of street furniture ever produced by a celebrated architect, its proportions borrowed, so the story goes, from a neoclassical tomb, and several hundred examples are formally listed as structures of historic interest.",
      "That principle — conservation through usefulness — has begun to travel. Redundant signal boxes now serve as heritage centres, defunct ticket offices as florists, and a Victorian pumping station as a climbing wall, each spared demolition not by sentiment alone but by the discovery of a job it could still do.",
      "Back on the green, the light inside the kiosk clicks on at dusk, as it always did. The telephone is long gone and nobody under forty has ever used one in anger, yet the little red building is arguably busier now than in its working life. Obsolescence, it turns out, is not a verdict. It is an invitation."
    ],
    options: [
      "By a wide margin, the most popular choice has been the public-access defibrillator. The kiosk turns out to be almost perfectly designed for the role: it stands at the recognised centre of its community, it is visible from a distance, it is lit, and it already has the electrical supply the equipment needs.",
      "There is a paradox in that kind of protection, though, which conservationists have learned the hard way: a structure preserved purely as an ornament begins to die on the day it is sealed. Listing can stop a kiosk being removed, but only a reason to open its door — books, a defibrillator, coffee — keeps it painted, repaired and loved.",
      "The first telephone exchanges were staffed almost entirely by young women, chosen, the companies said, for their patience and precise diction, and the etiquette they improvised — the greetings, the apologies for delay — shaped how strangers speak to each other on the line to this day.",
      "The pattern in the failures is instructive, and it is not about money. The adoptions that endure have a named custodian rather than a vague committee, a purpose matched to a real local need rather than a passing fashion, and a rota that survives the departure of whoever had the original idea.",
      "The offer was born of unsentimental arithmetic. Mobile phones had reduced calls from many rural kiosks to a handful a year, while each box still cost hundreds of pounds annually to clean, power and repair, and the operator had begun applying to remove them by the thousand — to the fury of villages that rarely used them but could not imagine the lane without one.",
      "Its defenders would add one caveat before the idea is applied everywhere: adaptation has limits. The kiosk lends itself to rescue because it is small, ubiquitous and adored; a redundant power station or a dying shopping centre poses the same question at a scale where a shelf of paperbacks and a rota of volunteers cannot be the answer.",
      "One village in the Yorkshire Dales illustrates the appeal. Its book-exchange kiosk, stocked and weeded by a retired teacher, now shifts more volumes each month than the mobile library that visits fortnightly, and it has never once been vandalised — a statistic the parish council quotes with the pride other places reserve for sports trophies."
    ],
    answers: [4, 0, 6, 3, 1, 5],
    explanations: [
      "The opening segment shows a kiosk converted to a book shelf; the next segment begins \"Rather than scrap the survivors wholesale\", so the gap must first explain why scrapping was on the table — the correct paragraph's \"unsentimental arithmetic\" of vanishing calls and mounting costs does exactly that.",
      "The previous segment describes the one-pound adoption scheme; the correct paragraph announces \"the most popular choice has been the public-access defibrillator\", which the next segment picks up directly with \"Defibrillators are only the most practical of the conversions\".",
      "The previous segment lists galleries, seed swaps and the tiny coffee shop; the correct paragraph's Yorkshire book-exchange anecdote \"illustrates the appeal\" with a concrete success, before the next segment turns with \"Not every adoption flourishes, however\".",
      "The previous segment describes the mouldering, abandoned kiosk; the correct paragraph opens \"The pattern in the failures is instructive\" and explains what the enduring adoptions share, after which the next segment moves \"Beyond utility\" to the heritage argument.",
      "The previous segment explains the kiosk's architectural pedigree and listed status; the correct paragraph's \"There is a paradox in that kind of protection\" refers straight back to listing, and its \"conservation through usefulness\" conclusion is named as \"That principle\" in the next segment.",
      "The previous segment extends the principle to signal boxes and pumping stations; the correct paragraph's \"Its defenders would add one caveat before the idea is applied everywhere\" qualifies precisely that expansion, and its note that the kiosk is \"small, ubiquitous and adored\" sets up the affectionate closing scene on the green."
    ]
  },
  {
    id: "c-rgap4-03",
    title: "Waiting for the Fish Hawk",
    segments: [
      "The nest is a metre of tangled sticks on top of a pole that volunteers sank into the marsh five springs ago, and this July, for the first time in living memory, there is a chick in it. Through the telescope you can see the absurd reptilian head swivel whenever its mother returns with a fish, and the retired couple who staff the viewing hide describe the sight to visitors in the tone people usually reserve for grandchildren.",
      "For most of the twentieth century that absence was assumed to be permanent, a closed chapter in the county's natural history. What changed was not the birds but the science: conservationists learned, from projects abroad, that a species faithful to its birthplace could be given a new birthplace on purpose.",
      "The imprinting is the heart of the method. An osprey fixes on the place it first flew, not the place it hatched, and when the young birds return from two winters in West Africa it is the adopted marsh, not their distant natal loch, that they treat as home.",
      "One returning bird does not make a population, of course. Ospreys pair slowly, first breeding attempts often fail, and the project's own models suggested a decade before the colony could survive without further translocations — a timescale the volunteers recite with surprising cheerfulness.",
      "That income matters, because goodwill is the project's real infrastructure. The fishing lakes that once had reason to resent a fish-eating hawk now advertise it; landowners compete to host nest platforms; and the anglers' association, initially the scheme's loudest critic, presented the project with a donated telescope last year.",
      "Against those odds, the curve nonetheless bends upwards. Four pairs now hold territories where five years ago there were none, a bird from the first cohort has been photographed prospecting a river valley two counties away, and the project's biologist has begun, cautiously, to use the word 'population'.",
      "This summer's chick was ringed last week, a blue band with white letters fitted in ninety careful seconds while its parents circled overhead. In two years, if the sea and the Sahara and the gauntlet of the flyway permit, a telescope in the hide will pick out those letters again. Somebody will be watching. Somebody, by then, will have been watching for a very long time."
    ],
    options: [
      "The gamble has paid for itself in ways the grant applications never predicted. The webcam trained on the nest attracts a million views a season, the viewing hide has a visitors' book signed from eleven countries, and the village shop, pub and bed-and-breakfasts now speak of 'osprey season' as their busiest weeks of the year.",
      "The birds did not leave; they were removed. Ospreys take fish, visibly and dramatically, and the nineteenth century treated that as a hanging offence: gamekeepers shot the adults, collectors paid handsomely for the eggs, and taxidermists paid better still for the birds themselves, until the last nest in the region was robbed and the sky stayed empty.",
      "It is a lesson in institutional patience as much as in ecology. A translocation runs on timescales that mock the three-year funding cycle and outlast the careers of the people who begin it, and the project's founding director, now retired, admits she always knew she was planting a wood she might never sit in.",
      "Translocation, as the technique is called, sounds simpler than it is. Chicks are taken, under licence, from a robust population elsewhere — never more than one from a brood — reared in open-topped pens overlooking the release site, and fed by unseen hands until the day they fly, so that no bird ever associates food with a human being.",
      "Beavers, reintroduced to several river systems over the same period, illustrate a different dynamic entirely: as engineers rather than predators they remake the landscape around them, and the arguments they provoke concern flooded pasture and felled trees rather than the fate of the animals themselves.",
      "The years that followed the first releases tested that cheerfulness severely. Migration swallowed the young birds and returned nothing: one spring passed with empty skies, then a second, and the project's committee had privately drafted a statement conceding failure when a bird wearing a blue ring appeared over the marsh on a windy April morning and began, unbelievably, to add sticks to a platform.",
      "The route home is the project's one unmanageable variable. Between the marsh and the wintering grounds lie storm systems, illegal shooting around fish farms on one stretch of coast, and trapping on another, and ringing data suggest that roughly half of all fledglings never survive to make the return journey at all."
    ],
    answers: [1, 3, 5, 0, 6, 2],
    explanations: [
      "The opening segment celebrates the first chick \"in living memory\", implying a long absence; the correct paragraph's \"The birds did not leave; they were removed\" explains that absence through persecution, which the next segment then calls \"that absence... assumed to be permanent\".",
      "The previous segment says a species \"could be given a new birthplace on purpose\"; the correct paragraph names and describes the technique — \"Translocation, as the technique is called\" — and its rearing-to-flight detail sets up the next segment's \"The imprinting is the heart of the method\".",
      "The previous segment ends with volunteers reciting a daunting timescale \"with surprising cheerfulness\"; the correct paragraph opens \"The years that followed the first releases tested that cheerfulness severely\" and its blue-ringed returnee makes sense of the colony's later growth.",
      "The gap follows the near-failure story and precedes \"That income matters\"; the correct paragraph is the only one describing income — webcam views, the visitors' book and the village's \"osprey season\" — which the next segment picks up as the funding of goodwill.",
      "The previous segment describes hard-won local goodwill; the correct paragraph turns to \"the project's one unmanageable variable\", the migration route and its fifty-per-cent losses, and the next segment's \"Against those odds\" refers directly back to that mortality.",
      "The previous segment reports four pairs and cautious talk of a 'population'; the correct paragraph draws the wider moral — \"a lesson in institutional patience\" with the director \"planting a wood she might never sit in\" — which the final segment's long watch over the ringed chick echoes."
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.gap = window.READING.gap.concat(BANK);
})();
