/* CAE Prep extra bank: speaking */
(function () {
  var BANK = [
    { question: "To what extent should governments regulate social media platforms?", bullets: ["free expression vs harmful content", "who decides what counts as misinformation", "self-regulation by companies — does it work?"] },
    { question: "Is it better to specialise deeply in one field or to develop a broad range of skills?", bullets: ["job security in a changing economy", "how innovation often happens between disciplines", "personal satisfaction and identity"] },
    { question: "How has globalisation changed the way young people see their own culture?", bullets: ["exposure to global entertainment and fashion", "pride in local traditions — stronger or weaker?", "hybrid identities and belonging"] },
    { question: "Should city centres be designed primarily for people rather than cars?", bullets: ["effects on local businesses and deliveries", "air quality and public health", "who might be disadvantaged by car-free zones"] },
    { question: "What responsibilities do wealthy countries have towards poorer ones?", bullets: ["aid vs fair trade arrangements", "climate change and historical responsibility", "sharing knowledge, medicine and technology"] },
    { question: "Is artificial intelligence more likely to create jobs or destroy them?", bullets: ["which kinds of work are most at risk", "new roles that didn't exist a decade ago", "how education systems should respond"] },
    { question: "How far should parents influence their children's career choices?", bullets: ["experience and guidance vs living someone else's dream", "financial realities of certain professions", "cultural expectations in different societies"] },
    { question: "Do international sporting events bring nations together or fuel rivalry?", bullets: ["shared celebration across borders", "nationalism and political tension", "the cost to host cities and who benefits"] },
    { question: "Should museums return cultural artefacts to their countries of origin?", bullets: ["where objects can be best preserved and seen", "historical justice and ownership", "possible compromises such as loans and replicas"] },
    { question: "Is it ethical to use animals in scientific research?", bullets: ["medical breakthroughs that relied on animal testing", "alternatives such as computer modelling", "where society should draw the line"] },
    { question: "How does advertising aimed at children differ from advertising aimed at adults, and should it be restricted?", bullets: ["children's ability to recognise persuasion", "pester power and family budgets", "responsibility of parents vs regulators"] },
    { question: "What makes a city genuinely liveable?", bullets: ["housing costs and public transport", "green space, safety and noise", "community feeling vs anonymity"] },
    { question: "Should university education be free for everyone?", bullets: ["who actually benefits from degrees", "taxpayer cost and alternative uses of the money", "effects on the value of a degree"] },
    { question: "How much privacy should people be willing to give up for security?", bullets: ["surveillance cameras and facial recognition", "data collected by governments vs companies", "whether 'nothing to hide' is a good argument"] },
    { question: "Is remote working good for society as a whole?", bullets: ["effects on city centres and small businesses", "work-life boundaries at home", "opportunities for people outside big cities"] },
    { question: "Do celebrities have a duty to be good role models?", bullets: ["influence over young audiences", "the right to a private life", "whether fame automatically brings responsibility"] },
    { question: "Should voting in national elections be compulsory?", bullets: ["participation vs personal freedom", "quality of decisions by unwilling voters", "other ways to increase engagement"] },
    { question: "How is streaming changing the film and music industries?", bullets: ["income for artists and creators", "attention spans and binge culture", "survival of cinemas and live venues"] },
    { question: "What are the consequences of societies becoming increasingly cashless?", bullets: ["convenience and reduced crime", "exclusion of older or poorer people", "every purchase leaving a data trail"] },
    { question: "Is competition in schools helpful or harmful for students?", bullets: ["motivation and preparation for adult life", "stress and effects on weaker students", "cooperation as an alternative model"] },
    { question: "Should governments do more to protect endangered languages?", bullets: ["language as a carrier of culture and knowledge", "practical costs of bilingual services and schooling", "whether language death is simply natural change"] },
    { question: "How has tourism changed the character of famous destinations?", bullets: ["economic benefits for local people", "crowding, prices and loss of authenticity", "responsible ways to travel"] },
    { question: "Are traditional news organisations still necessary in the age of social media?", bullets: ["professional verification vs speed", "who pays for investigative journalism", "echo chambers and algorithmic feeds"] },
    { question: "Should employers be allowed to monitor their employees' work online?", bullets: ["productivity and security concerns", "trust and workplace morale", "where monitoring becomes surveillance"] },
    { question: "What role should nuclear power play in fighting climate change?", bullets: ["reliable low-carbon electricity", "waste, accidents and public fear", "cost compared with wind and solar"] },
    { question: "Is it fair that top athletes and entertainers earn far more than doctors and teachers?", bullets: ["market demand and rare talent", "social value of different professions", "whether salaries can or should be controlled"] },
    { question: "How important is it for children to grow up with access to nature?", bullets: ["physical and mental health effects", "urban childhoods and screen time", "what schools and cities can do"] },
    { question: "Should scientific research be driven by curiosity or by practical usefulness?", bullets: ["unexpected benefits of pure research", "urgent problems needing solutions now", "who should decide funding priorities"] },
    { question: "Do loyalty to a company and job security still exist, and do they matter?", bullets: ["frequent job changes as the new normal", "what employers owe their staff", "freelancing and the gig economy"] },
    { question: "How should societies balance economic growth with environmental protection?", bullets: ["jobs that depend on polluting industries", "green technology as an opportunity", "whose lifestyle has to change most"] },
    { question: "Is space exploration a worthwhile use of public money?", bullets: ["scientific knowledge and technological spin-offs", "problems on Earth that need funding first", "private companies taking over the role"] },
    { question: "What effect does living abroad have on a person's view of their home country?", bullets: ["seeing familiar things with fresh eyes", "idealising or criticising home from a distance", "returning changed — reverse culture shock"] },
    { question: "Should junk food be taxed in the same way as tobacco?", bullets: ["public health costs of poor diet", "personal freedom and food choices", "effects on low-income households"] },
    { question: "How valuable is learning history for dealing with the present?", bullets: ["patterns that repeat across generations", "whose version of history gets taught", "the danger of drawing the wrong lessons"] },
    { question: "Are smart devices in the home more of a convenience or a risk?", bullets: ["comfort, energy saving and accessibility", "hacking and data collection", "dependence on technology for basic tasks"] },
    { question: "Should there be limits on how much land and housing investors can own?", bullets: ["housing as a home vs an investment", "effects on rents and first-time buyers", "property rights and market freedom"] },
    { question: "What do we lose and gain when shopping moves online?", bullets: ["choice, prices and convenience", "empty high streets and local jobs", "packaging, deliveries and the environment"] },
    { question: "Is failure a necessary part of success?", bullets: ["what setbacks teach that success cannot", "cultures that punish vs tolerate failure", "when persistence becomes stubbornness"] },
    { question: "Should organ donation be automatic unless people opt out?", bullets: ["lives saved by higher donation rates", "consent and family wishes", "trust in the medical system"] },
    { question: "How much influence should public opinion have on scientific policy, such as vaccination or GM food?", bullets: ["democracy vs expertise", "fear and misinformation shaping debates", "how scientists could communicate better"] },
    { question: "Do school uniforms and dress codes serve a useful purpose?", bullets: ["equality and reduced peer pressure", "self-expression and individuality", "preparation for workplace expectations"] },
    { question: "What are the long-term effects of growing up with social media?", bullets: ["friendship, comparison and self-image", "skills in presenting oneself publicly", "a permanent record of teenage mistakes"] },
    { question: "Should cities invest more in preserving old buildings or in constructing new ones?", bullets: ["character and identity of a place", "housing shortages and modern needs", "adapting old buildings for new uses"] },
    { question: "Is volunteering abroad genuinely helpful, or can it do more harm than good?", bullets: ["skills volunteers actually bring", "dependence and taking local jobs", "who benefits more — hosts or volunteers"] },
    { question: "How will driverless vehicles change everyday life if they become common?", bullets: ["safety compared with human drivers", "jobs in transport and delivery", "who is responsible when things go wrong"] },
    { question: "Should the working week be shortened to four days?", bullets: ["productivity and employee wellbeing", "industries where it may be impossible", "what people would do with the extra day"] },
    { question: "What makes some people more resistant to advertising and persuasion than others?", bullets: ["education and critical thinking", "experience of being misled", "whether anyone is truly immune"] },
    { question: "Is it better for a country to produce its own food and goods or to rely on international trade?", bullets: ["security of supply in a crisis", "efficiency and lower prices through trade", "environmental cost of transporting goods"] }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  SPEAKING = SPEAKING.concat(BANK);
})();
