/* CAE Prep extra bank: vocab wave 4 */
(function () {
  var BANK = [
    /* ===== Emotions & mental states ===== */
    { front: "elated", pos: "adj.", def: "extremely happy and excited", example: "She was elated when she heard she had won the scholarship.", zh: "興高采烈的" },
    { front: "despondent", pos: "adj.", def: "very unhappy and without hope", example: "He grew despondent after months of unsuccessful job applications.", zh: "沮喪的；灰心的" },
    { front: "distraught", pos: "adj.", def: "extremely upset and agitated", example: "The distraught mother searched the park for her missing son.", zh: "心煩意亂的" },
    { front: "forlorn", pos: "adj.", def: "lonely, sad and uncared for", example: "A forlorn figure sat alone on the empty platform.", zh: "孤寂淒涼的" },
    { front: "jubilant", pos: "adj.", def: "feeling great happiness because of a success", example: "Jubilant fans poured onto the streets after the final whistle.", zh: "歡欣鼓舞的" },
    { front: "euphoria", pos: "n.", def: "an intense feeling of happiness and excitement", example: "The euphoria of graduation day soon gave way to job-hunting anxiety.", zh: "狂喜；亢奮" },
    { front: "melancholy", pos: "n.", def: "a deep, thoughtful sadness", example: "There is a gentle melancholy running through all her early songs.", zh: "憂鬱" },
    { front: "apathy", pos: "n.", def: "a lack of interest, enthusiasm or concern", example: "Voter apathy meant fewer than half the residents turned up.", zh: "冷漠；無動於衷" },
    { front: "agitated", pos: "adj.", def: "troubled, nervous and unable to stay calm", example: "He became increasingly agitated as the delay stretched into hours.", zh: "焦躁不安的" },
    { front: "bewildered", pos: "adj.", def: "completely confused and unsure what to do", example: "The new students looked bewildered by the campus layout.", zh: "困惑不解的" },
    { front: "flustered", pos: "adj.", def: "nervous and confused, especially because of pressure", example: "She got flustered when the interviewer fired three questions at once.", zh: "慌張的" },
    { front: "mortified", pos: "adj.", def: "extremely embarrassed or ashamed", example: "He was mortified to realise his microphone had been on the whole time.", zh: "羞愧難當的" },
    { front: "petrified", pos: "adj.", def: "so frightened that you cannot move or think", example: "I was petrified when the turbulence suddenly worsened.", zh: "嚇呆的" },
    { front: "dismay", pos: "n.", def: "a feeling of shock and disappointment", example: "To our dismay, the concert was cancelled at the last minute.", zh: "沮喪；驚愕" },
    { front: "anguish", pos: "n.", def: "severe mental or physical suffering", example: "Nothing could ease the anguish of losing her closest friend.", zh: "極度痛苦" },
    { front: "exhilarated", pos: "adj.", def: "very happy, excited and full of energy", example: "We felt exhilarated after skiing down the steepest slope.", zh: "興奮雀躍的" },
    { front: "infuriate", pos: "v.", def: "to make someone extremely angry", example: "His habit of interrupting infuriates his colleagues.", zh: "激怒" },
    { front: "unnerve", pos: "v.", def: "to make someone feel anxious or lose confidence", example: "The examiner's silence unnerved even the best candidates.", zh: "使不安；使失去信心" },
    { front: "disconcerting", pos: "adj.", def: "making you feel uncomfortable, confused or worried", example: "It was disconcerting to find the office completely empty at noon.", zh: "令人不安的" },
    { front: "poignant", pos: "adj.", def: "causing a strong feeling of sadness or sympathy", example: "The film ends with a poignant farewell at the railway station.", zh: "令人辛酸感傷的" },
    { front: "wistful", pos: "adj.", def: "sad because you are thinking about something you cannot have", example: "She cast a wistful glance at the house where she grew up.", zh: "惆悵的；渴望的" },
    { front: "sullen", pos: "adj.", def: "silent and bad-tempered", example: "The teenager gave a sullen shrug and refused to explain.", zh: "慍怒不語的" },
    { front: "morose", pos: "adj.", def: "gloomy, unhappy and unwilling to talk", example: "He became morose and withdrawn after the divorce.", zh: "鬱鬱寡歡的" },
    { front: "irritable", pos: "adj.", def: "becoming annoyed very easily", example: "Lack of sleep makes me irritable and forgetful.", zh: "易怒的" },
    { front: "jittery", pos: "adj.", def: "nervous and unable to relax", example: "Too much coffee left her jittery before the presentation.", zh: "緊張不安的" },
    { front: "trepidation", pos: "n.", def: "a feeling of fear or anxiety about something that is going to happen", example: "She opened the exam results with considerable trepidation.", zh: "惶恐；忐忑" },
    { front: "dread", pos: "n.", def: "a strong feeling of fear about something that may happen", example: "He waited for the diagnosis with a growing sense of dread.", zh: "恐懼；擔憂" },
    { front: "yearn", pos: "v.", def: "to want something very much, especially something difficult to get", example: "After years abroad, she yearned for the sounds of her hometown.", zh: "渴望" },
    { front: "loathe", pos: "v.", def: "to hate someone or something intensely", example: "He loathes being told what to do.", zh: "厭惡" },
    { front: "smug", pos: "adj.", def: "too pleased with yourself in an annoying way", example: "She gave a smug smile when her prediction came true.", zh: "自鳴得意的" },
    { front: "indignant", pos: "adj.", def: "angry because of unfair treatment", example: "Passengers were indignant at being charged twice for the same ticket.", zh: "憤慨的" },
    { front: "livid", pos: "adj.", def: "extremely angry", example: "Dad was livid when he saw the dent in the car.", zh: "大為光火的" },
    { front: "seething", pos: "adj.", def: "feeling intense anger without fully showing it", example: "She was seething after being blamed for a mistake she never made.", zh: "怒火中燒的" },
    { front: "overwrought", pos: "adj.", def: "extremely upset, anxious and unable to stay calm", example: "The overwrought witness had to pause several times during her testimony.", zh: "過度緊張激動的" },
    { front: "composure", pos: "n.", def: "the state of being calm and in control of your feelings", example: "The pilot kept his composure throughout the emergency landing.", zh: "沉著鎮定" },
    { front: "serenity", pos: "n.", def: "a state of calm and peace", example: "The serenity of the mountain lake made all our worries melt away.", zh: "寧靜；安詳" },
    { front: "gratification", pos: "n.", def: "a feeling of pleasure and satisfaction", example: "Social media offers instant gratification but little lasting joy.", zh: "滿足感" },
    { front: "pang", pos: "n.", def: "a sudden sharp feeling of pain or an unpleasant emotion", example: "He felt a pang of guilt as he deleted her message unread.", zh: "一陣劇痛（或愧疚、悲傷）" },
    { front: "qualm", pos: "n.", def: "a feeling of doubt or worry about whether what you are doing is right", example: "She had no qualms about reporting the fraud to the police.", zh: "疑慮；顧忌" },
    { front: "unease", pos: "n.", def: "a feeling of worry or slight fear", example: "There was a growing sense of unease as the storm approached.", zh: "不安" },
    { front: "downcast", pos: "adj.", def: "sad and without hope", example: "The players looked downcast as they left the pitch.", zh: "垂頭喪氣的" },
    { front: "crestfallen", pos: "adj.", def: "sad and disappointed, especially after a failure", example: "He was crestfallen when his proposal was rejected outright.", zh: "沮喪失望的" },
    { front: "disillusioned", pos: "adj.", def: "disappointed because something is not as good as you believed", example: "Many young doctors become disillusioned with the long hours.", zh: "幻滅的；醒悟的" },
    { front: "ambivalent", pos: "adj.", def: "having mixed or contradictory feelings about something", example: "I remain ambivalent about moving abroad for work.", zh: "心情矛盾的" },
    { front: "ecstatic", pos: "adj.", def: "feeling extreme happiness", example: "The team were ecstatic about reaching the final for the first time.", zh: "欣喜若狂的" },
    { front: "inconsolable", pos: "adj.", def: "so sad that no one can make you feel better", example: "The child was inconsolable when her dog went missing.", zh: "悲痛欲絕的" },
    { front: "fixation", pos: "n.", def: "an interest in something that is too strong and not healthy", example: "His fixation with tidiness drives his flatmates mad.", zh: "迷戀；執念" },
    { front: "introspective", pos: "adj.", def: "tending to examine your own thoughts and feelings", example: "The illness left him quieter and more introspective.", zh: "內省的" },
    { front: "placid", pos: "adj.", def: "calm and not easily excited or upset", example: "Despite the chaos around her, she remained utterly placid.", zh: "平和的；溫順的" },
    { front: "stoical", pos: "adj.", def: "accepting pain or trouble without complaining", example: "He remained stoical throughout the painful treatment.", zh: "堅忍的" },
    { front: "choke up", pos: "phr. v.", def: "to become unable to speak because of strong emotion", example: "She choked up while thanking her parents in the speech.", zh: "（因激動）哽咽說不出話" },
    { front: "well up", pos: "phr. v.", def: "(of tears or emotion) to rise and become impossible to hide", example: "Tears welled up in his eyes as the anthem played.", zh: "（淚水、情緒）湧上" },
    { front: "break down", pos: "phr. v.", def: "to lose control of your feelings and start crying", example: "She broke down when she heard the news of the accident.", zh: "情緒崩潰；痛哭" },
    { front: "simmer down", pos: "phr. v.", def: "to become calm again after being angry", example: "Give him an hour to simmer down before you apologise.", zh: "冷靜下來" },
    { front: "perk up", pos: "phr. v.", def: "to become more cheerful or energetic", example: "She perked up considerably once the coffee arrived.", zh: "振作起來；來精神" },
    { front: "snap at", pos: "phr. v.", def: "to speak to someone in a sudden, angry way", example: "Sorry I snapped at you earlier; I was exhausted.", zh: "厲聲斥責" },
    { front: "flip out", pos: "phr. v.", def: "to suddenly become extremely angry or lose control", example: "He completely flipped out when he saw the scratch on his bike.", zh: "勃然大怒；失控" },
    { front: "chicken out", pos: "phr. v.", def: "to decide not to do something because you are afraid", example: "I was going to try the bungee jump but chickened out at the last second.", zh: "臨陣退縮" },
    { front: "wallow in", pos: "phr. v.", def: "to allow yourself to feel an unhappy emotion for too long, almost with enjoyment", example: "Stop wallowing in self-pity and start looking for solutions.", zh: "沉溺於（負面情緒）" },
    { front: "shy away from", pos: "phr. v.", def: "to avoid doing something because you are nervous or afraid", example: "He shies away from any conversation about his feelings.", zh: "迴避；退避" },
    { front: "brood over", pos: "phr. v.", def: "to keep thinking about something that upsets you", example: "There is no point brooding over a decision you cannot change.", zh: "鬱悶地反覆想" },
    { front: "dwell on", pos: "phr. v.", def: "to think or talk about something unpleasant for too long", example: "Try not to dwell on your mistakes; learn from them and move on.", zh: "老是想著；糾結於" },
    { front: "fret over", pos: "phr. v.", def: "to worry about something, often unnecessarily", example: "She fretted over every detail of the wedding for months.", zh: "為……煩惱焦慮" },
    { front: "stress out", pos: "phr. v.", def: "to make someone feel very anxious and tired", example: "Deadlines at work are really stressing me out this month.", zh: "使緊張焦慮" },
    { front: "psych up", pos: "phr. v.", def: "to prepare yourself mentally for something difficult", example: "The runners psyched themselves up before the final.", zh: "做好心理準備；打氣" },
    { front: "tense up", pos: "phr. v.", def: "to become nervous, with stiff muscles", example: "I always tense up when the dentist picks up the drill.", zh: "（身體、心情）緊繃" },
    { front: "loosen up", pos: "phr. v.", def: "to become more relaxed", example: "A couple of jokes helped the audience loosen up.", zh: "放鬆" },
    { front: "crack up", pos: "phr. v.", def: "to suddenly laugh a lot, or to become mentally exhausted", example: "The whole class cracked up at his impression of the teacher.", zh: "大笑；崩潰" },
    { front: "choke back", pos: "phr. v.", def: "to force yourself not to show a strong emotion", example: "She choked back tears as she read out the farewell letter.", zh: "強忍住（淚水、情緒）" },
    { front: "mope around", pos: "phr. v.", def: "to move about aimlessly feeling sad and sorry for yourself", example: "He has been moping around the house since the break-up.", zh: "悶悶不樂地晃來晃去" },
    { front: "give in to", pos: "phr. v.", def: "to stop resisting a desire, demand or pressure", example: "She refused to give in to despair even in the darkest weeks.", zh: "向……屈服" },
    { front: "grow out of", pos: "phr. v.", def: "to stop doing or feeling something as you become older", example: "Most children grow out of their fear of the dark.", zh: "（隨年齡增長）擺脫" },
    { front: "on cloud nine", pos: "idiom", def: "extremely happy", example: "She has been on cloud nine since the proposal.", zh: "樂上雲霄；欣喜若狂" },
    { front: "at the end of your tether", pos: "idiom", def: "having no more patience or strength left", example: "After a week of sleepless nights, the new parents were at the end of their tether.", zh: "忍無可忍；筋疲力竭" },
    { front: "a nervous wreck", pos: "idiom", def: "a person who is extremely anxious and exhausted", example: "By the time the results came out, I was a nervous wreck.", zh: "精神緊張到崩潰的人" },
    { front: "on edge", pos: "idiom", def: "nervous and unable to relax", example: "Everyone was on edge waiting for the storm to hit.", zh: "緊張不安" },
    { front: "hit rock bottom", pos: "idiom", def: "to reach the lowest possible emotional point", example: "He hit rock bottom after losing both his job and his flat.", zh: "跌到谷底" },
    { front: "a lump in your throat", pos: "idiom", def: "a tight feeling in your throat caused by emotion", example: "I had a lump in my throat as the plane took off.", zh: "哽咽；喉頭一緊" },
    { front: "butterflies in your stomach", pos: "idiom", def: "a nervous, fluttering feeling before an important event", example: "I always get butterflies in my stomach before going on stage.", zh: "緊張得心裡七上八下" },
    { front: "on tenterhooks", pos: "idiom", def: "waiting anxiously to find out what will happen", example: "We were on tenterhooks until the surgeon came out to speak to us.", zh: "提心吊膽地等待" },
    { front: "scared stiff", pos: "idiom", def: "extremely frightened", example: "She is scared stiff of spiders, even tiny ones.", zh: "嚇得動彈不得" },
    { front: "bear a grudge", pos: "idiom", def: "to continue feeling resentment towards someone", example: "He still bears a grudge against the referee from that match.", zh: "懷恨在心" },
    { front: "green with envy", pos: "idiom", def: "very jealous of someone", example: "Her colleagues were green with envy when she got the corner office.", zh: "非常嫉妒；眼紅" },
    { front: "hot under the collar", pos: "idiom", def: "angry or embarrassed", example: "He gets hot under the collar whenever anyone questions his driving.", zh: "惱火；面紅耳赤" },
    { front: "in high spirits", pos: "idiom", def: "cheerful and full of energy", example: "The team set off in high spirits despite the rain.", zh: "情緒高昂" },
    { front: "at your wits' end", pos: "idiom", def: "so worried that you do not know what to do next", example: "I am at my wits' end trying to get the baby to sleep.", zh: "束手無策" },
    { front: "a weight off your shoulders", pos: "idiom", def: "a great feeling of relief after a worry is removed", example: "Paying off the loan was a huge weight off my shoulders.", zh: "如釋重負" },
    { front: "mixed feelings", pos: "collocation", def: "both positive and negative emotions about the same thing", example: "I have mixed feelings about leaving the company after ten years.", zh: "喜憂參半的心情" },
    { front: "tear your hair out", pos: "idiom", def: "to be extremely anxious or frustrated about something", example: "She was tearing her hair out over the endless paperwork.", zh: "急得抓狂" },
    { front: "put a brave face on it", pos: "idiom", def: "to pretend to be happy when you are actually upset", example: "He put a brave face on it, but the redundancy hit him hard.", zh: "強顏歡笑" },
    /* ===== Science, technology & innovation ===== */
    { front: "catalyst", pos: "n.", def: "something that causes an important change or event to happen", example: "The funding cut acted as a catalyst for reforming the whole lab.", zh: "催化劑；促成因素" },
    { front: "synthesise", pos: "v.", def: "to produce a substance by combining chemicals, or to combine ideas", example: "The team synthesised a new compound that kills resistant bacteria.", zh: "合成；綜合" },
    { front: "molecular", pos: "adj.", def: "relating to molecules", example: "Advances in molecular biology have transformed cancer research.", zh: "分子的" },
    { front: "genome", pos: "n.", def: "the complete set of genetic material of an organism", example: "Scientists have now mapped the genome of thousands of species.", zh: "基因組" },
    { front: "mutation", pos: "n.", def: "a permanent change in the genetic material of a living thing", example: "A single mutation made the virus far more transmissible.", zh: "突變" },
    { front: "propulsion", pos: "n.", def: "the force that drives a vehicle forward", example: "The probe uses ion propulsion to travel between planets.", zh: "推進（力）" },
    { front: "trajectory", pos: "n.", def: "the curved path of an object moving through space, or the path of development", example: "Engineers adjusted the rocket's trajectory minutes after launch.", zh: "軌跡；發展路線" },
    { front: "inertia", pos: "n.", def: "the tendency to stay unchanged, or a lack of energy to act", example: "Institutional inertia delayed the adoption of the new system for years.", zh: "慣性；惰性" },
    { front: "combustion", pos: "n.", def: "the process of burning", example: "The internal combustion engine is slowly giving way to electric motors.", zh: "燃燒" },
    { front: "semiconductor", pos: "n.", def: "a material used to make computer chips", example: "The global shortage of semiconductors halted car production.", zh: "半導體" },
    { front: "nanotechnology", pos: "n.", def: "science that works with extremely small structures and materials", example: "Nanotechnology may allow drugs to target individual cells.", zh: "奈米科技" },
    { front: "biotechnology", pos: "n.", def: "the use of living things in industrial and scientific processes", example: "Biotechnology firms are racing to develop lab-grown meat.", zh: "生物科技" },
    { front: "interface", pos: "n.", def: "the way a program or device presents itself to the user", example: "The app's interface is so intuitive that no manual is needed.", zh: "介面" },
    { front: "bandwidth", pos: "n.", def: "the amount of data a connection can carry", example: "Streaming in 4K eats up an enormous amount of bandwidth.", zh: "頻寬" },
    { front: "latency", pos: "n.", def: "the delay before data begins to transfer", example: "Online gamers complain about even a few milliseconds of latency.", zh: "延遲" },
    { front: "scalability", pos: "n.", def: "the ability of a system to handle growth", example: "Investors questioned the scalability of the start-up's business model.", zh: "可擴充性" },
    { front: "firmware", pos: "n.", def: "permanent software programmed into a device", example: "A firmware update fixed the camera's focusing problem.", zh: "韌體" },
    { front: "open-source", pos: "adj.", def: "(of software) free for anyone to use and modify", example: "The project runs entirely on open-source software.", zh: "開放原始碼的" },
    { front: "crowdsourcing", pos: "n.", def: "getting ideas, work or funding from a large group of people online", example: "The map of flood damage was built through crowdsourcing.", zh: "群眾外包" },
    { front: "disruptive", pos: "adj.", def: "changing an industry in a radical, innovative way", example: "Ride-hailing apps were a disruptive force in the taxi industry.", zh: "顛覆性的" },
    { front: "ingenuity", pos: "n.", def: "skill at inventing clever solutions", example: "Fixing the antenna in orbit required remarkable ingenuity.", zh: "獨創力；巧思" },
    { front: "ingenious", pos: "adj.", def: "very clever and original", example: "She came up with an ingenious way to cool the servers cheaply.", zh: "巧妙的" },
    { front: "patent", pos: "n.", def: "the official legal right to be the only maker or seller of an invention", example: "The company filed a patent for its folding screen technology.", zh: "專利" },
    { front: "inception", pos: "n.", def: "the beginning of an organisation or project", example: "The lab has published over a thousand papers since its inception.", zh: "創立；開端" },
    { front: "iteration", pos: "n.", def: "a new version of something that is repeatedly improved", example: "Each iteration of the prototype was lighter than the last.", zh: "迭代；反覆改良的版本" },
    { front: "calibrate", pos: "v.", def: "to adjust an instrument so it measures accurately", example: "The sensors must be calibrated before every experiment.", zh: "校準" },
    { front: "configure", pos: "v.", def: "to arrange equipment or software for a particular task", example: "It took an hour to configure the router for the new network.", zh: "設定；配置" },
    { front: "troubleshoot", pos: "v.", def: "to trace and correct faults in a system", example: "The manual explains how to troubleshoot common printer errors.", zh: "排除故障" },
    { front: "decipher", pos: "v.", def: "to succeed in understanding something difficult to read or interpret", example: "It took researchers decades to decipher the ancient script.", zh: "破譯；解讀" },
    { front: "extrapolate", pos: "v.", def: "to estimate something unknown from known facts", example: "You cannot extrapolate national trends from one small survey.", zh: "推斷；外推" },
    { front: "hypothesise", pos: "v.", def: "to suggest a possible explanation that has not yet been proved", example: "Astronomers hypothesise that the planet once held liquid water.", zh: "提出假設" },
    { front: "pinpoint", pos: "v.", def: "to find or identify something exactly", example: "The new software can pinpoint the source of the leak within metres.", zh: "精確找出" },
    { front: "propel", pos: "v.", def: "to push or drive something forward", example: "The breakthrough propelled the small firm to global prominence.", zh: "推進；推動" },
    { front: "retrieval", pos: "n.", def: "the process of getting back stored information", example: "The crash made data retrieval from the old server impossible.", zh: "檢索；取回" },
    { front: "spearhead", pos: "v.", def: "to lead an important activity or movement", example: "She spearheaded the university's push into quantum computing.", zh: "帶頭；領導" },
    { front: "trailblazer", pos: "n.", def: "a person who is the first to do something new", example: "Ada Lovelace was a trailblazer in the history of computing.", zh: "開拓者；先驅" },
    { front: "brainchild", pos: "n.", def: "an idea or invention created by a particular person", example: "The solar car project was the brainchild of two engineering students.", zh: "（某人的）發明；心血結晶" },
    { front: "augment", pos: "v.", def: "to increase the value, size or effectiveness of something", example: "The headset augments the real world with digital images.", zh: "擴增；增強" },
    { front: "futuristic", pos: "adj.", def: "looking extremely modern, as if from the future", example: "The showroom was full of futuristic concept cars.", zh: "未來感的" },
    { front: "aerodynamic", pos: "adj.", def: "shaped to move through air with as little resistance as possible", example: "The bike's aerodynamic frame shaves seconds off every lap.", zh: "符合空氣動力學的" },
    { front: "microchip", pos: "n.", def: "a tiny piece of silicon containing electronic circuits", example: "A single microchip now holds billions of transistors.", zh: "微晶片" },
    { front: "malware", pos: "n.", def: "software designed to damage or gain access to a computer system", example: "The hospital's records were locked by malware for three days.", zh: "惡意軟體" },
    { front: "phishing", pos: "n.", def: "tricking people online into revealing passwords or bank details", example: "Staff receive training on how to spot phishing emails.", zh: "網路釣魚" },
    { front: "biometric", pos: "adj.", def: "using measurements of the body, such as fingerprints, for identification", example: "The airport has switched to biometric passport gates.", zh: "生物辨識的" },
    { front: "forefront", pos: "n.", def: "the leading position in an important activity", example: "The institute is at the forefront of battery research.", zh: "最前線；領先地位" },
    { front: "overhaul", pos: "v.", def: "to examine and improve a system or machine completely", example: "The airline overhauled its booking system after repeated crashes.", zh: "徹底檢修；全面改革" },
    { front: "foolproof", pos: "adj.", def: "so well designed that it cannot fail or be used wrongly", example: "No security system is entirely foolproof.", zh: "萬無一失的" },
    { front: "rudimentary", pos: "adj.", def: "basic and not highly developed", example: "The first mobile phones had only rudimentary text functions.", zh: "初步的；簡陋的" },
    { front: "robotics", pos: "n.", def: "the science of designing and operating robots", example: "Advances in robotics are transforming warehouse work.", zh: "機器人學" },
    { front: "obsolescence", pos: "n.", def: "the process of becoming outdated and no longer used", example: "Rapid software updates push older devices into obsolescence.", zh: "過時；淘汰" },
    { front: "tinker with", pos: "phr. v.", def: "to make small changes to something to repair or improve it", example: "He spends every weekend tinkering with his old motorbike.", zh: "小修小改；擺弄" },
    { front: "hack into", pos: "phr. v.", def: "to secretly gain access to a computer system without permission", example: "Someone hacked into the company's payroll database.", zh: "駭入" },
    { front: "scale up", pos: "phr. v.", def: "to increase the size or amount of something", example: "The lab is scaling up production of the vaccine.", zh: "擴大規模" },
    { front: "ramp up", pos: "phr. v.", def: "to increase activity or production quickly", example: "Chipmakers ramped up output to meet the surge in demand.", zh: "快速提高；加緊" },
    { front: "feed into", pos: "phr. v.", def: "to contribute to a process or result", example: "The sensor readings feed into a central forecasting model.", zh: "輸入；匯入（成為一部分）" },
    { front: "link up", pos: "phr. v.", def: "to connect two or more machines, systems or people", example: "The satellites link up to provide global coverage.", zh: "連接；聯結" },
    { front: "conk out", pos: "phr. v.", def: "(of a machine) to suddenly stop working", example: "The projector conked out halfway through the demonstration.", zh: "（機器）突然壞掉" },
    { front: "act up", pos: "phr. v.", def: "(of a machine or body part) to behave badly or not work properly", example: "My laptop has been acting up ever since the update.", zh: "出毛病；不聽使喚" },
    { front: "give out", pos: "phr. v.", def: "to stop working because of age or overuse", example: "The engine finally gave out after thirty years of service.", zh: "（機器、身體）失靈；停擺" },
    { front: "power down", pos: "phr. v.", def: "to switch a machine off completely", example: "Please power down all devices before the inspection.", zh: "關機" },
    { front: "key in", pos: "phr. v.", def: "to enter information using a keyboard", example: "Key in your code and press the green button.", zh: "鍵入；輸入" },
    { front: "boot up", pos: "phr. v.", def: "to start a computer", example: "The old desktop takes five minutes to boot up.", zh: "開機" },
    { front: "log off", pos: "phr. v.", def: "to finish using a computer system", example: "Remember to log off before you leave the shared terminal.", zh: "登出" },
    { front: "flesh out", pos: "phr. v.", def: "to add more detail to an idea or plan", example: "The engineers fleshed out the concept into a full design.", zh: "充實（構想）細節" },
    { front: "mock up", pos: "phr. v.", def: "to make a model of something to show how it will look", example: "Designers mocked up the new dashboard in a single afternoon.", zh: "做出模型（樣品）" },
    { front: "think up", pos: "phr. v.", def: "to invent an idea or plan using your imagination", example: "They had to think up a cheaper way to launch satellites.", zh: "想出" },
    { front: "dream up", pos: "phr. v.", def: "to invent something unusual or imaginative", example: "Who dreamed up the idea of a phone you can fold in half?", zh: "憑空想出" },
    { front: "hit upon", pos: "phr. v.", def: "to suddenly discover a good idea or solution", example: "She hit upon the solution while cycling home.", zh: "突然想到" },
    { front: "stumble upon", pos: "phr. v.", def: "to discover something by chance", example: "The researchers stumbled upon the effect while testing something else.", zh: "偶然發現" },
    { front: "toy with", pos: "phr. v.", def: "to consider an idea casually without deciding", example: "We are toying with the idea of automating the whole line.", zh: "隨意考慮；把玩（想法）" },
    { front: "map out", pos: "phr. v.", def: "to plan something carefully and in detail", example: "The team mapped out a five-year research programme.", zh: "詳細規劃" },
    { front: "plug into", pos: "phr. v.", def: "to connect to a system, network or source of power", example: "The start-up plugged into a global network of investors.", zh: "接入；連上" },
    { front: "a quantum leap", pos: "idiom", def: "a sudden, huge improvement or advance", example: "The new telescope represents a quantum leap in imaging power.", zh: "重大突破；飛躍" },
    { front: "ahead of its time", pos: "idiom", def: "too advanced or modern to be appreciated when it appears", example: "The electric car of the 1990s was simply ahead of its time.", zh: "超越時代的" },
    { front: "push the boundaries", pos: "idiom", def: "to go beyond accepted limits in a field", example: "Her lab keeps pushing the boundaries of gene editing.", zh: "突破界限" },
    { front: "think outside the box", pos: "idiom", def: "to think creatively rather than in traditional ways", example: "Solving the storage problem required thinking outside the box.", zh: "跳脫框架思考" },
    { front: "the next big thing", pos: "idiom", def: "something new expected to become extremely popular or important", example: "Analysts are calling brain-computer interfaces the next big thing.", zh: "下一個熱門新事物" },
    { front: "in leaps and bounds", pos: "idiom", def: "improving very quickly", example: "Translation software has improved in leaps and bounds.", zh: "突飛猛進" },
    { front: "put through its paces", pos: "idiom", def: "to test something thoroughly to see what it can do", example: "Reviewers put the new drone through its paces in high winds.", zh: "徹底測試" },
    { front: "bounce ideas off", pos: "idiom", def: "to discuss ideas with someone to get their reaction", example: "I like having a colleague to bounce ideas off.", zh: "與人交流激盪想法" },
    { front: "cloud computing", pos: "collocation", def: "using remote servers on the internet to store and process data", example: "The firm moved all its records to cloud computing services.", zh: "雲端運算" },
    { front: "machine learning", pos: "collocation", def: "the ability of computers to learn from data without explicit programming", example: "Machine learning now powers most recommendation systems.", zh: "機器學習" },
    { front: "artificial intelligence", pos: "collocation", def: "computer systems able to perform tasks that normally require human intelligence", example: "Artificial intelligence is reshaping everything from law to logistics.", zh: "人工智慧" },
    { front: "virtual reality", pos: "collocation", def: "a computer-generated environment that seems real to the user", example: "Surgeons now rehearse operations in virtual reality.", zh: "虛擬實境" },
    { front: "genetic engineering", pos: "collocation", def: "changing the genes of a living thing deliberately", example: "Genetic engineering could make crops resistant to drought.", zh: "基因工程" },
    { front: "a beta version", pos: "collocation", def: "an early version of software released for testing", example: "Users of the beta version reported dozens of bugs.", zh: "測試版" },
    { front: "a data breach", pos: "collocation", def: "an incident in which private information is stolen or exposed", example: "The data breach exposed millions of customer passwords.", zh: "資料外洩" },
    { front: "a trial run", pos: "collocation", def: "a test of how something new works before using it properly", example: "We gave the booking system a trial run before the launch.", zh: "試運行" },
    { front: "on the blink", pos: "idiom", def: "(of a machine) not working properly", example: "The office printer has been on the blink all week.", zh: "（機器）出故障" },
    { front: "up and running", pos: "idiom", def: "operating fully and correctly", example: "The new servers should be up and running by Monday.", zh: "正常運作中" },
    /* ===== Environment & climate ===== */
    { front: "smog", pos: "n.", def: "polluted air that hangs over a city like fog", example: "A thick blanket of smog forced schools to close for two days.", zh: "霧霾" },
    { front: "haze", pos: "n.", def: "air that is difficult to see through because of heat, dust or smoke", example: "The hills disappeared behind a haze of wildfire smoke.", zh: "霾；薄霧" },
    { front: "runoff", pos: "n.", def: "rainwater that flows off land, often carrying pollution", example: "Fertiliser runoff from the farms is poisoning the river.", zh: "地表逕流" },
    { front: "groundwater", pos: "n.", def: "water held underground in soil and rock", example: "Decades of over-pumping have depleted the region's groundwater.", zh: "地下水" },
    { front: "wetland", pos: "n.", def: "an area of land partly covered by water, such as a marsh", example: "The wetland shelters thousands of migrating birds each spring.", zh: "濕地" },
    { front: "permafrost", pos: "n.", def: "ground that remains frozen all year round", example: "Thawing permafrost is releasing huge quantities of methane.", zh: "永凍土" },
    { front: "desertification", pos: "n.", def: "the process by which fertile land becomes desert", example: "Overgrazing has accelerated desertification across the region.", zh: "沙漠化" },
    { front: "reforestation", pos: "n.", def: "planting trees again on land where forests were destroyed", example: "The reforestation scheme aims to plant ten million trees.", zh: "再造林" },
    { front: "overfishing", pos: "n.", def: "catching so many fish that stocks cannot recover", example: "Overfishing has left the cod population close to collapse.", zh: "過度捕撈" },
    { front: "poaching", pos: "n.", def: "the illegal hunting of animals", example: "Rangers use drones to combat elephant poaching.", zh: "盜獵" },
    { front: "cull", pos: "v.", def: "to kill a number of animals to control their population", example: "The government decided to cull deer to protect young woodland.", zh: "撲殺（以控制數量）" },
    { front: "invasive", pos: "adj.", def: "(of a species) spreading harmfully where it does not naturally belong", example: "Invasive weeds are choking the native plants along the riverbank.", zh: "（物種）入侵的" },
    { front: "indigenous", pos: "adj.", def: "naturally existing in a place rather than arriving from elsewhere", example: "The reserve protects plants indigenous to the island.", zh: "原生的；土生土長的" },
    { front: "flora", pos: "n.", def: "all the plants of a particular area", example: "The valley's flora includes several species found nowhere else.", zh: "植物群" },
    { front: "fauna", pos: "n.", def: "all the animals of a particular area", example: "Logging threatens the forest's rich fauna.", zh: "動物群" },
    { front: "canopy", pos: "n.", def: "the upper layer of branches and leaves in a forest", example: "Little sunlight penetrates the dense rainforest canopy.", zh: "（森林）樹冠層" },
    { front: "microplastics", pos: "n.", def: "tiny pieces of plastic that pollute water and soil", example: "Microplastics have been found in drinking water worldwide.", zh: "微塑膠" },
    { front: "biodegradable", pos: "adj.", def: "able to decay naturally without harming the environment", example: "The cafe switched to biodegradable cups and cutlery.", zh: "可生物分解的" },
    { front: "compost", pos: "n.", def: "decayed organic material used to improve soil", example: "We turn all our kitchen waste into compost for the garden.", zh: "堆肥" },
    { front: "incineration", pos: "n.", def: "burning waste at high temperatures to destroy it", example: "Critics say incineration merely turns rubbish into air pollution.", zh: "焚化" },
    { front: "toxin", pos: "n.", def: "a poisonous substance", example: "The algae release toxins that can kill fish in large numbers.", zh: "毒素" },
    { front: "hazardous", pos: "adj.", def: "dangerous, especially to health or safety", example: "The factory was fined for dumping hazardous waste.", zh: "有害的；危險的" },
    { front: "seep", pos: "v.", def: "(of liquid or gas) to flow slowly through small openings", example: "Chemicals from the landfill seeped into the water supply.", zh: "滲漏" },
    { front: "submerge", pos: "v.", def: "to go or put completely under water", example: "Rising seas could submerge much of the coastal plain.", zh: "淹沒" },
    { front: "inundate", pos: "v.", def: "to flood an area, or to overwhelm with things to deal with", example: "The storm surge inundated whole neighbourhoods.", zh: "淹沒；使應接不暇" },
    { front: "mitigate", pos: "v.", def: "to make something harmful less severe", example: "Coastal wetlands help mitigate the effects of storm surges.", zh: "緩解；減輕" },
    { front: "precarious", pos: "adj.", def: "not safe or certain; likely to fail or fall", example: "The glacier's retreat has left the village water supply precarious.", zh: "不穩固的；岌岌可危的" },
    { front: "finite", pos: "adj.", def: "having a limit; not endless", example: "Fossil fuels are a finite resource we are burning at speed.", zh: "有限的" },
    { front: "avert", pos: "v.", def: "to prevent something bad from happening", example: "Rapid emissions cuts could still avert the worst outcomes.", zh: "避免；防止" },
    { front: "exacerbate", pos: "v.", def: "to make a bad situation worse", example: "Deforestation exacerbates flooding downstream.", zh: "使惡化；加劇" },
    { front: "aggravate", pos: "v.", def: "to make a problem or illness worse", example: "The drought was aggravated by decades of poor water management.", zh: "加重；使惡化" },
    { front: "diminish", pos: "v.", def: "to become or make smaller or less important", example: "Fish stocks have diminished sharply over the past decade.", zh: "減少；縮減" },
    { front: "decimate", pos: "v.", def: "to destroy a large proportion of something", example: "Disease has decimated the region's bee population.", zh: "大量毀滅" },
    { front: "ravage", pos: "v.", def: "to damage something severely", example: "Wildfires ravaged thousands of hectares of forest last summer.", zh: "蹂躪；嚴重破壞" },
    { front: "barren", pos: "adj.", def: "(of land) unable to produce plants or crops", example: "Years of erosion turned the hillside into barren rock.", zh: "貧瘠的" },
    { front: "geothermal", pos: "adj.", def: "relating to heat from inside the earth", example: "Iceland heats most of its homes with geothermal energy.", zh: "地熱的" },
    { front: "hydroelectric", pos: "adj.", def: "producing electricity from the power of moving water", example: "The hydroelectric dam supplies a third of the country's power.", zh: "水力發電的" },
    { front: "turbine", pos: "n.", def: "a machine with blades turned by water, steam or wind to produce power", example: "Each offshore turbine can power thousands of homes.", zh: "渦輪機" },
    { front: "retrofit", pos: "v.", def: "to add new equipment or features to something built earlier", example: "The council plans to retrofit older buildings with insulation.", zh: "改裝；翻新加裝" },
    { front: "insulation", pos: "n.", def: "material that stops heat, sound or electricity from escaping", example: "Better insulation could cut household energy bills in half.", zh: "隔熱（材料）；絕緣" },
    { front: "conservationist", pos: "n.", def: "a person who works to protect the natural environment", example: "Conservationists are lobbying to expand the marine reserve.", zh: "自然保育人士" },
    { front: "deciduous", pos: "adj.", def: "(of trees) losing leaves in autumn", example: "The deciduous woodland turns gold and crimson in October.", zh: "落葉性的" },
    { front: "pollinate", pos: "v.", def: "to carry pollen so that plants can produce seeds", example: "A third of our food crops are pollinated by insects.", zh: "授粉" },
    { front: "vegetation", pos: "n.", def: "the plants of an area considered as a whole", example: "Dense vegetation covered the abandoned quarry within a decade.", zh: "植被" },
    { front: "undergrowth", pos: "n.", def: "bushes and small plants growing under trees", example: "The fire spread quickly through the dry undergrowth.", zh: "林下灌叢" },
    { front: "sanctuary", pos: "n.", def: "a protected place for wildlife, or a place of safety", example: "The rescued orangutans now live in a forest sanctuary.", zh: "保護區；庇護所" },
    { front: "scavenger", pos: "n.", def: "an animal that feeds on dead animals or waste", example: "Vultures are nature's most efficient scavengers.", zh: "食腐動物" },
    { front: "predator", pos: "n.", def: "an animal that hunts and eats other animals", example: "Removing the top predator threw the whole ecosystem off balance.", zh: "掠食者" },
    { front: "migratory", pos: "adj.", def: "(of animals) travelling regularly between different regions", example: "Light pollution disorients migratory birds at night.", zh: "遷徙的" },
    { front: "wilderness", pos: "n.", def: "a large natural area untouched by human activity", example: "Alaska contains some of the last true wilderness on earth.", zh: "荒野" },
    { front: "chop down", pos: "phr. v.", def: "to cut through a tree so that it falls", example: "Protesters chained themselves to the oaks to stop them being chopped down.", zh: "砍倒" },
    { front: "eat away at", pos: "phr. v.", def: "to gradually destroy or reduce something", example: "The rising tide is eating away at the coastline every year.", zh: "逐漸侵蝕" },
    { front: "eat into", pos: "phr. v.", def: "to use up or reduce something valuable gradually", example: "Urban expansion keeps eating into the surrounding farmland.", zh: "蠶食；侵占" },
    { front: "taper off", pos: "phr. v.", def: "to decrease gradually", example: "Rainfall tapers off sharply after the monsoon ends.", zh: "逐漸減少" },
    { front: "peter out", pos: "phr. v.", def: "to gradually come to an end or disappear", example: "The stream peters out before it reaches the valley floor.", zh: "逐漸消失；枯竭" },
    { front: "die off", pos: "phr. v.", def: "to die one by one until none are left", example: "Without the wetland, the frogs began to die off.", zh: "相繼死亡" },
    { front: "kill off", pos: "phr. v.", def: "to destroy living things completely", example: "The chemical spill killed off nearly everything in the lake.", zh: "使滅絕；徹底消滅" },
    { front: "clog up", pos: "phr. v.", def: "to block something so that nothing can pass through", example: "Plastic bags clog up the city's drains and cause flooding.", zh: "堵塞" },
    { front: "wash away", pos: "phr. v.", def: "(of water) to carry something away completely", example: "The floods washed away the topsoil from the fields.", zh: "沖走" },
    { front: "sweep away", pos: "phr. v.", def: "to remove or destroy something quickly and completely", example: "The landslide swept away the road below the village.", zh: "席捲而去；摧毀" },
    { front: "wash up", pos: "phr. v.", def: "(of the sea) to carry something onto the shore", example: "Dead seabirds have been washing up along the coast.", zh: "沖上岸" },
    { front: "spew out", pos: "phr. v.", def: "to send out large amounts of something with force", example: "The old power station spews out tonnes of ash daily.", zh: "噴出；大量排放" },
    { front: "belch out", pos: "phr. v.", def: "to send out large amounts of smoke or gas", example: "Factory chimneys belched out black smoke over the town.", zh: "噴吐（濃煙、廢氣）" },
    { front: "pump out", pos: "phr. v.", def: "to produce or send out something in large quantities", example: "The plant pumps out carbon dioxide around the clock.", zh: "大量排出" },
    { front: "seal off", pos: "phr. v.", def: "to close an area so that nothing can enter or leave", example: "Officials sealed off the beach after the oil reached shore.", zh: "封鎖" },
    { front: "tail off", pos: "phr. v.", def: "to become gradually smaller or weaker", example: "Salmon numbers tail off dramatically beyond the dam.", zh: "逐漸下降" },
    { front: "swallow up", pos: "phr. v.", def: "to take in and make something disappear", example: "The advancing desert has swallowed up entire villages.", zh: "吞沒" },
    { front: "encroach on", pos: "phr. v.", def: "to gradually take more of someone's land, rights or space", example: "New housing estates keep encroaching on the green belt.", zh: "侵占；蠶食" },
    { front: "bounce back", pos: "phr. v.", def: "to recover quickly after damage or difficulty", example: "Given time, marine ecosystems can bounce back remarkably well.", zh: "迅速恢復" },
    { front: "dry out", pos: "phr. v.", def: "to become completely dry", example: "Peat bogs release carbon when they dry out.", zh: "乾涸；變乾" },
    { front: "a tipping point", pos: "idiom", def: "the moment when small changes become big enough to cause a major, often unstoppable, change", example: "Scientists warn the ice sheet may be nearing a tipping point.", zh: "臨界點" },
    { front: "the point of no return", pos: "idiom", def: "the stage after which it is impossible to go back or undo the damage", example: "Once the rainforest is gone, we will have passed the point of no return.", zh: "不可逆轉的地步" },
    { front: "rising sea levels", pos: "collocation", def: "the increase in the height of the world's oceans", example: "Rising sea levels threaten dozens of island nations.", zh: "海平面上升" },
    { front: "extreme weather events", pos: "collocation", def: "unusually severe weather such as heatwaves, floods or storms", example: "Insurers are alarmed by the growing cost of extreme weather events.", zh: "極端天氣事件" },
    { front: "the ozone layer", pos: "collocation", def: "the layer of gas that protects the earth from harmful rays", example: "Banning CFCs allowed the ozone layer to begin healing.", zh: "臭氧層" },
    { front: "an oil spill", pos: "collocation", def: "an accident in which oil escapes into the sea or onto land", example: "The oil spill coated hundreds of kilometres of coastline.", zh: "漏油事件" },
    { front: "a wind farm", pos: "collocation", def: "a group of wind turbines producing electricity", example: "The offshore wind farm will power half a million homes.", zh: "風力發電場" },
    { front: "net zero", pos: "collocation", def: "a balance between the greenhouse gases produced and those removed", example: "The city has pledged to reach net zero by 2040.", zh: "淨零排放" },
    { front: "greenhouse gases", pos: "collocation", def: "gases such as carbon dioxide that trap heat in the atmosphere", example: "Agriculture accounts for a surprising share of greenhouse gases.", zh: "溫室氣體" },
    { front: "coral bleaching", pos: "collocation", def: "the whitening and dying of coral caused by warmer seas", example: "The reef suffered its worst coral bleaching on record.", zh: "珊瑚白化" },
    { front: "a nature reserve", pos: "collocation", def: "an area of land protected for its wildlife", example: "The old quarry has been turned into a thriving nature reserve.", zh: "自然保護區" },
    { front: "an endangered species", pos: "collocation", def: "a type of animal or plant at risk of dying out", example: "The snow leopard remains an endangered species despite protection.", zh: "瀕危物種" },
    { front: "throwaway culture", pos: "collocation", def: "a way of life in which people discard things rather than repair them", example: "Cheap fashion has fuelled a throwaway culture.", zh: "拋棄式文化" },
    { front: "carbon-neutral", pos: "adj.", def: "not adding to the total amount of carbon dioxide in the atmosphere", example: "The brewery claims to be fully carbon-neutral.", zh: "碳中和的" },
    { front: "energy-efficient", pos: "adj.", def: "using little energy to work effectively", example: "Energy-efficient appliances quickly pay for themselves.", zh: "節能的" },
    { front: "off-grid", pos: "adj.", def: "not connected to public supplies of electricity, gas or water", example: "The cabin is completely off-grid, powered by solar panels.", zh: "離網的；不依賴公共電網的" },
    { front: "not see the wood for the trees", pos: "idiom", def: "to miss the main point because of focusing on small details", example: "With so many statistics, the report cannot see the wood for the trees.", zh: "見樹不見林" },
    { front: "make hay while the sun shines", pos: "idiom", def: "to take advantage of a good situation while it lasts", example: "Farmers made hay while the sun shone and harvested early.", zh: "把握良機" },
    { front: "a force of nature", pos: "idiom", def: "a person or thing with unstoppable energy or power", example: "The campaign's young founder is a force of nature.", zh: "勢不可擋的人（或力量）" },
    { front: "the tide is turning", pos: "idiom", def: "the situation is beginning to change, often for the better", example: "The tide is turning against single-use packaging.", zh: "形勢正在轉變" },
    /* ===== Art, literature & performance ===== */
    { front: "allegory", pos: "n.", def: "a story in which the characters and events represent deeper ideas", example: "The novel works as an allegory of political corruption.", zh: "寓言；諷喻" },
    { front: "metaphor", pos: "n.", def: "a way of describing something by calling it something else", example: "The poet uses the storm as a metaphor for grief.", zh: "隱喻" },
    { front: "imagery", pos: "n.", def: "language that produces pictures in the reader's mind", example: "The chapter is full of vivid imagery of the frozen north.", zh: "意象" },
    { front: "symbolism", pos: "n.", def: "the use of symbols to represent ideas in art or literature", example: "Critics have written volumes on the symbolism of the white whale.", zh: "象徵手法" },
    { front: "protagonist", pos: "n.", def: "the main character in a story, play or film", example: "The protagonist spends the whole novel searching for her father.", zh: "主角" },
    { front: "antagonist", pos: "n.", def: "the main character who opposes the hero", example: "The antagonist is far more interesting than the hero himself.", zh: "反派；對立角色" },
    { front: "subplot", pos: "n.", def: "a secondary story within a novel, play or film", example: "The romantic subplot lightens an otherwise grim thriller.", zh: "支線劇情" },
    { front: "cliffhanger", pos: "n.", def: "an exciting ending that leaves the audience in suspense", example: "Every episode ends on a cliffhanger to keep viewers hooked.", zh: "懸念結尾" },
    { front: "memoir", pos: "n.", def: "a written account of the author's own life and experiences", example: "Her memoir of growing up backstage became a bestseller.", zh: "回憶錄" },
    { front: "anthology", pos: "n.", def: "a collection of poems, stories or songs by different writers", example: "The anthology gathers short fiction from across Southeast Asia.", zh: "選集" },
    { front: "prose", pos: "n.", def: "ordinary written language, not poetry", example: "Her prose is spare, precise and quietly devastating.", zh: "散文；散文體" },
    { front: "verse", pos: "n.", def: "writing arranged in lines with rhythm; poetry", example: "The play mixes prose with passages of blank verse.", zh: "韻文；詩句" },
    { front: "stanza", pos: "n.", def: "a group of lines forming a unit in a poem", example: "The final stanza returns to the image of the empty house.", zh: "詩節" },
    { front: "novella", pos: "n.", def: "a short novel", example: "The novella can be read comfortably in a single evening.", zh: "中篇小說" },
    { front: "manuscript", pos: "n.", def: "the text of a book before it is printed", example: "The publisher rejected the manuscript three times before accepting it.", zh: "手稿" },
    { front: "excerpt", pos: "n.", def: "a short piece taken from a longer book, film or piece of music", example: "The magazine printed an excerpt from her forthcoming novel.", zh: "節錄" },
    { front: "epilogue", pos: "n.", def: "a final section that comments on or concludes a book or play", example: "The epilogue reveals what became of each character.", zh: "後記；尾聲" },
    { front: "prologue", pos: "n.", def: "an introductory section of a book or play", example: "The prologue hints at the tragedy to come.", zh: "序幕；開場白" },
    { front: "critique", pos: "n.", def: "a detailed judgement of a piece of work", example: "Her essay offers a sharp critique of the director's late films.", zh: "評論" },
    { front: "rendition", pos: "n.", def: "a particular performance of a song or piece of music", example: "Her jazz rendition of the folk song brought the house to silence.", zh: "演繹；表演版本" },
    { front: "repertoire", pos: "n.", def: "all the pieces a performer or company can perform", example: "The pianist has an unusually wide repertoire.", zh: "曲目；戲碼" },
    { front: "improvise", pos: "v.", def: "to perform without preparation, inventing as you go", example: "The actors improvised an entire scene when the set collapsed.", zh: "即興表演" },
    { front: "understudy", pos: "n.", def: "an actor who learns a role in order to replace the usual performer", example: "The understudy stepped in at two hours' notice and triumphed.", zh: "替補演員" },
    { front: "matinee", pos: "n.", def: "an afternoon performance of a play or film", example: "Tickets for the Saturday matinee are half price.", zh: "日場演出" },
    { front: "encore", pos: "n.", def: "an extra performance given because the audience demands it", example: "The band played three encores before the lights came up.", zh: "安可曲" },
    { front: "choreography", pos: "n.", def: "the arrangement of steps and movements in a dance", example: "The show's choreography blends ballet with street dance.", zh: "編舞" },
    { front: "ensemble", pos: "n.", def: "a group of musicians, actors or dancers performing together", example: "The film relies on a superb ensemble rather than one star.", zh: "合奏團；全體演員" },
    { front: "virtuoso", pos: "n.", def: "a person extremely skilled at something, especially music", example: "The young violinist is already hailed as a virtuoso.", zh: "演奏名家" },
    { front: "monologue", pos: "n.", def: "a long speech by one actor or speaker", example: "The play opens with a fifteen-minute monologue.", zh: "獨白" },
    { front: "backdrop", pos: "n.", def: "the painted scenery behind a stage, or the setting of events", example: "The story unfolds against the backdrop of the civil war.", zh: "背景；布景" },
    { front: "riveting", pos: "adj.", def: "so interesting that you cannot look away", example: "Her account of the trial is absolutely riveting.", zh: "引人入勝的" },
    { front: "gripping", pos: "adj.", def: "holding your attention completely", example: "The documentary is a gripping study of obsession.", zh: "扣人心弦的" },
    { front: "compelling", pos: "adj.", def: "extremely interesting and convincing", example: "The novel offers a compelling portrait of a city in decline.", zh: "引人入勝且有說服力的" },
    { front: "engrossing", pos: "adj.", def: "taking all your attention", example: "I found the biography so engrossing I missed my stop.", zh: "使人全神貫注的" },
    { front: "spellbinding", pos: "adj.", def: "holding your complete attention as if by magic", example: "Her spellbinding performance earned a ten-minute ovation.", zh: "令人著迷的" },
    { front: "lacklustre", pos: "adj.", def: "lacking energy, excitement or brilliance", example: "Critics dismissed the sequel as lacklustre and predictable.", zh: "乏善可陳的" },
    { front: "underwhelming", pos: "adj.", def: "failing to impress", example: "After all the hype, the exhibition itself was rather underwhelming.", zh: "令人失望的；不如預期的" },
    { front: "overrated", pos: "adj.", def: "considered better than it really is", example: "Many readers now regard the novel as wildly overrated.", zh: "被高估的" },
    { front: "derivative", pos: "adj.", def: "copied from something else and lacking originality", example: "Reviewers found the film derivative of earlier space epics.", zh: "缺乏原創性的" },
    { front: "hackneyed", pos: "adj.", def: "used so often that it has become boring", example: "The script leans on hackneyed lines about following your dreams.", zh: "陳腔濫調的" },
    { front: "thought-provoking", pos: "adj.", def: "making people think seriously about a subject", example: "It is a thought-provoking play about memory and blame.", zh: "發人深省的" },
    { front: "surreal", pos: "adj.", def: "strange and dreamlike", example: "The stage design creates a surreal, floating world.", zh: "超現實的" },
    { front: "minimalist", pos: "adj.", def: "using very simple forms and very few elements", example: "The gallery's minimalist rooms let the sculptures breathe.", zh: "極簡主義的" },
    { front: "ornate", pos: "adj.", def: "decorated with a lot of complicated detail", example: "The opera house has a famously ornate gilded ceiling.", zh: "華麗的；裝飾繁複的" },
    { front: "intricate", pos: "adj.", def: "having many small details or parts arranged in a complicated way", example: "The carpet's intricate patterns took years to weave.", zh: "精細複雜的" },
    { front: "mural", pos: "n.", def: "a large painting done directly on a wall", example: "A vast mural of the city's history covers the station wall.", zh: "壁畫" },
    { front: "replica", pos: "n.", def: "an exact copy of something", example: "The museum displays a full-scale replica of the ancient ship.", zh: "複製品" },
    { front: "typecast", pos: "v.", def: "to repeatedly give an actor the same kind of role", example: "After the sitcom, he was typecast as the hapless best friend.", zh: "使（演員）定型" },
    { front: "blockbuster", pos: "n.", def: "a film or book that is hugely successful commercially", example: "The studio releases one superhero blockbuster every summer.", zh: "賣座大片" },
    { front: "sequel", pos: "n.", def: "a book or film that continues an earlier story", example: "The sequel picks up ten years after the original ended.", zh: "續集" },
    { front: "act out", pos: "phr. v.", def: "to perform the events of a story or situation", example: "The children acted out the legend in front of the whole school.", zh: "演出；把……表演出來" },
    { front: "belt out", pos: "phr. v.", def: "to sing or play something loudly and with energy", example: "The crowd belted out the chorus along with the band.", zh: "高聲唱出" },
    { front: "leaf through", pos: "phr. v.", def: "to turn the pages of a book quickly without reading closely", example: "She leafed through the catalogue while waiting for the curator.", zh: "隨手翻閱" },
    { front: "flick through", pos: "phr. v.", def: "to look quickly through a book or magazine", example: "I only flicked through the script, but the dialogue looks sharp.", zh: "快速翻看" },
    { front: "carry off", pos: "phr. v.", def: "to succeed in doing something difficult, such as a role or style", example: "Few actors could carry off both roles in the same evening.", zh: "成功勝任；駕馭" },
    { front: "walk out", pos: "phr. v.", def: "to leave a performance or meeting suddenly to show disapproval", example: "Dozens of spectators walked out before the interval.", zh: "中途離席（以示不滿）" },
    { front: "bring out", pos: "phr. v.", def: "to publish or release a new book, album or product", example: "The band brings out a new album every other year.", zh: "推出；出版" },
    { front: "polish up", pos: "phr. v.", def: "to improve a skill or piece of work with extra effort", example: "She spent the weekend polishing up the final chapter.", zh: "潤飾；精進" },
    { front: "play out", pos: "phr. v.", def: "to develop and happen in a particular way", example: "The family drama plays out over a single sweltering summer.", zh: "上演；展開" },
    { front: "sit through", pos: "phr. v.", def: "to stay until the end of something long or boring", example: "We sat through three hours of speeches before the premiere.", zh: "耐著性子看完" },
    { front: "drown out", pos: "phr. v.", def: "to be so loud that another sound cannot be heard", example: "The applause drowned out the actor's final line.", zh: "蓋過（聲音）" },
    { front: "fade out", pos: "phr. v.", def: "to disappear gradually, especially sound or picture", example: "The music fades out as the credits begin to roll.", zh: "淡出" },
    { front: "sketch out", pos: "phr. v.", def: "to describe or draw something in a rough, simple way", example: "The director sketched out the scene on the back of a napkin.", zh: "概略勾勒" },
    { front: "dash off", pos: "phr. v.", def: "to write or draw something very quickly", example: "He dashed off the melody in twenty minutes on a hotel piano.", zh: "匆匆寫成" },
    { front: "pore over", pos: "phr. v.", def: "to study or read something very carefully", example: "Scholars still pore over her notebooks for hidden meanings.", zh: "仔細研讀" },
    { front: "wade through", pos: "phr. v.", def: "to read or deal with something long and boring with effort", example: "I had to wade through six hundred pages of footnotes.", zh: "費力讀完" },
    { front: "come across", pos: "phr. v.", def: "to give a particular impression to others", example: "On stage she comes across as effortlessly confident.", zh: "給人……印象" },
    { front: "run over", pos: "phr. v.", def: "to practise or quickly review something such as lines or a plan", example: "The actors ran over their lines one last time before the curtain rose.", zh: "快速排練；複習一遍" },
    { front: "get into", pos: "phr. v.", def: "to start enjoying something, or to become involved in it", example: "It took me fifty pages to get into the novel, but then I was hooked.", zh: "開始投入；迷上" },
    { front: "round off", pos: "phr. v.", def: "to finish something in a satisfying way", example: "The orchestra rounded off the evening with a joyful waltz.", zh: "圓滿結束" },
    { front: "shoot to fame", pos: "idiom", def: "to become famous very suddenly", example: "She shot to fame after one video of her singing went viral.", zh: "一夕成名" },
    { front: "a claim to fame", pos: "idiom", def: "the one thing that makes a person or place famous", example: "The town's main claim to fame is a very old bridge.", zh: "成名的緣由" },
    { front: "in the public eye", pos: "idiom", def: "seen and discussed by the public through the media", example: "Life in the public eye left her craving privacy.", zh: "受公眾矚目" },
    { front: "a one-hit wonder", pos: "idiom", def: "an artist famous for only one successful work", example: "Critics wrote them off as a one-hit wonder, then came the second album.", zh: "曇花一現的藝人" },
    { front: "top the charts", pos: "idiom", def: "to be the best-selling song or album", example: "The single topped the charts in fourteen countries.", zh: "登上排行榜冠軍" },
    { front: "bring the house down", pos: "idiom", def: "to perform so well that the audience reacts with huge enthusiasm", example: "Her final aria brought the house down.", zh: "博得滿堂彩" },
    { front: "a standing ovation", pos: "collocation", def: "an occasion when the audience stands up to applaud", example: "The cast received a ten-minute standing ovation.", zh: "起立鼓掌" },
    { front: "a page-turner", pos: "idiom", def: "a book so exciting that you keep reading", example: "The thriller is a real page-turner; I finished it in one night.", zh: "令人欲罷不能的書" },
    { front: "a plot twist", pos: "collocation", def: "an unexpected development in a story", example: "The plot twist in the final chapter changes everything.", zh: "劇情轉折" },
    { front: "off the cuff", pos: "idiom", def: "without preparation", example: "His best jokes were all delivered off the cuff.", zh: "即興地" },
    { front: "behind the scenes", pos: "idiom", def: "in private, where the public cannot see", example: "A documentary crew filmed the chaos behind the scenes.", zh: "幕後" },
    { front: "take centre stage", pos: "idiom", def: "to become the most important focus of attention", example: "Questions about authorship took centre stage at the festival.", zh: "成為焦點" },
    { front: "waiting in the wings", pos: "idiom", def: "ready to act or take over when needed", example: "A generation of young directors is waiting in the wings.", zh: "蓄勢待發" },
    { front: "a hard act to follow", pos: "idiom", def: "someone so good that whoever comes next will seem worse", example: "The retiring conductor is a hard act to follow.", zh: "難以超越的前人" },
    { front: "in the limelight", pos: "idiom", def: "receiving a lot of public attention", example: "After decades in the limelight, she retired to a quiet village.", zh: "備受矚目" },
    { front: "play to the gallery", pos: "idiom", def: "to behave in a way intended to please the audience rather than doing what is right", example: "His speeches play to the gallery instead of addressing the facts.", zh: "譁眾取寵" },
    { front: "a dress rehearsal", pos: "collocation", def: "the final practice of a performance with costumes and scenery", example: "The dress rehearsal was a disaster, yet opening night was flawless.", zh: "彩排；總排練" },
    { front: "critical acclaim", pos: "collocation", def: "praise from professional critics", example: "The debut novel won critical acclaim but sold few copies.", zh: "評論界讚譽" },
    { front: "a captive audience", pos: "idiom", def: "people who listen because they cannot leave", example: "On a long flight, the crew has a captive audience for its announcements.", zh: "不得不聽的觀眾" },
    { front: "make it big", pos: "idiom", def: "to become very successful and famous", example: "He moved to the capital determined to make it big in film.", zh: "功成名就" },
    /* ===== Health & medicine ===== */
    { front: "onset", pos: "n.", def: "the beginning of something, especially something unpleasant", example: "Early treatment can delay the onset of symptoms.", zh: "（疾病等的）發作；開始" },
    { front: "outbreak", pos: "n.", def: "the sudden start of disease, war or violence", example: "An outbreak of measles closed two schools in the district.", zh: "爆發" },
    { front: "pandemic", pos: "n.", def: "a disease spreading across many countries at the same time", example: "The pandemic changed working habits almost overnight.", zh: "全球大流行病" },
    { front: "immunise", pos: "v.", def: "to protect someone against a disease, usually by vaccination", example: "All infants are immunised against polio free of charge.", zh: "使免疫；接種疫苗" },
    { front: "antibody", pos: "n.", def: "a protein the body produces to fight infection", example: "Blood tests showed she had antibodies against the virus.", zh: "抗體" },
    { front: "placebo", pos: "n.", def: "a substance with no medical effect given as if it were medicine", example: "Half the volunteers received the drug and half a placebo.", zh: "安慰劑" },
    { front: "dosage", pos: "n.", def: "the amount of medicine to be taken at one time", example: "The doctor lowered the dosage after the side effects appeared.", zh: "劑量" },
    { front: "over-the-counter", pos: "adj.", def: "(of medicine) available without a prescription", example: "Most over-the-counter painkillers are safe if used correctly.", zh: "非處方的" },
    { front: "practitioner", pos: "n.", def: "a person who works in a profession such as medicine", example: "See a qualified practitioner before starting any new treatment.", zh: "執業者；開業醫師" },
    { front: "anaesthetic", pos: "n.", def: "a substance that stops you feeling pain", example: "The operation was performed under general anaesthetic.", zh: "麻醉劑" },
    { front: "incision", pos: "n.", def: "a cut made into the body during an operation", example: "Modern surgery often needs only a tiny incision.", zh: "切口" },
    { front: "biopsy", pos: "n.", def: "the removal of tissue from the body to test for disease", example: "The biopsy confirmed that the lump was harmless.", zh: "切片檢查" },
    { front: "benign", pos: "adj.", def: "(of a tumour) not cancerous; not harmful", example: "To everyone's relief, the growth turned out to be benign.", zh: "良性的" },
    { front: "malignant", pos: "adj.", def: "(of a tumour) cancerous and likely to spread", example: "The scan revealed a small malignant tumour in the lung.", zh: "惡性的" },
    { front: "screening", pos: "n.", def: "testing many people to detect a disease early", example: "Regular screening has cut deaths from cervical cancer dramatically.", zh: "篩檢" },
    { front: "referral", pos: "n.", def: "the act of sending a patient to see a specialist", example: "You need a referral from your GP to see the cardiologist.", zh: "轉診" },
    { front: "outpatient", pos: "n.", def: "a patient treated at a hospital without staying overnight", example: "The procedure is now done on an outpatient basis.", zh: "門診病人" },
    { front: "mortality", pos: "n.", def: "the number of deaths in a particular situation or period", example: "Infant mortality has fallen sharply over the past fifty years.", zh: "死亡率" },
    { front: "terminal", pos: "adj.", def: "(of an illness) leading gradually to death and unable to be cured", example: "He spent his final months in a hospice for the terminally ill.", zh: "末期的；不治的" },
    { front: "incurable", pos: "adj.", def: "impossible to cure", example: "The condition is incurable but can be managed with medication.", zh: "無法治癒的" },
    { front: "hereditary", pos: "adj.", def: "passed from parents to children through the genes", example: "Some forms of heart disease are strongly hereditary.", zh: "遺傳性的" },
    { front: "intolerance", pos: "n.", def: "the inability to digest a certain food without becoming ill", example: "A lactose intolerance means she avoids most dairy products.", zh: "（食物）不耐症" },
    { front: "deficiency", pos: "n.", def: "a lack of something the body needs", example: "An iron deficiency left her constantly exhausted.", zh: "缺乏（症）" },
    { front: "supplement", pos: "n.", def: "a substance taken to add nutrients to your diet", example: "Doctors recommend a vitamin D supplement in winter.", zh: "補充劑" },
    { front: "metabolism", pos: "n.", def: "the chemical processes in the body that turn food into energy", example: "Your metabolism naturally slows as you age.", zh: "新陳代謝" },
    { front: "dehydration", pos: "n.", def: "the harmful loss of too much water from the body", example: "Several runners were treated for dehydration at the finish line.", zh: "脫水" },
    { front: "ailing", pos: "adj.", def: "ill and not improving; weak", example: "She gave up her job to care for her ailing father.", zh: "生病的；虛弱的" },
    { front: "frail", pos: "adj.", def: "physically weak, especially because of age", example: "The frail patient could no longer manage the stairs.", zh: "體弱的" },
    { front: "bedridden", pos: "adj.", def: "unable to leave your bed because of illness or age", example: "After the fall, he was bedridden for nearly two months.", zh: "臥床不起的" },
    { front: "housebound", pos: "adj.", def: "unable to leave your house because of illness or age", example: "Volunteers deliver meals to housebound residents.", zh: "困居家中的" },
    { front: "convalescence", pos: "n.", def: "the period of getting better after an illness or operation", example: "She spent her convalescence at her sister's house by the sea.", zh: "康復期" },
    { front: "recuperate", pos: "v.", def: "to get back your health and strength after illness", example: "He is recuperating at home after the knee operation.", zh: "休養復原" },
    { front: "spasm", pos: "n.", def: "a sudden, uncontrollable tightening of a muscle", example: "A back spasm forced the tennis player to retire from the match.", zh: "痙攣" },
    { front: "inflammation", pos: "n.", def: "a red, swollen and painful reaction in part of the body", example: "The cream reduces inflammation around the joint.", zh: "發炎" },
    { front: "fracture", pos: "n.", def: "a break or crack in a bone", example: "The X-ray showed a hairline fracture in her wrist.", zh: "骨折" },
    { front: "sprain", pos: "v.", def: "to injure a joint by twisting it suddenly", example: "He sprained his ankle stepping off the kerb.", zh: "扭傷" },
    { front: "dislocate", pos: "v.", def: "to force a bone out of its normal position at a joint", example: "The goalkeeper dislocated his shoulder in the collision.", zh: "使脫臼" },
    { front: "concussion", pos: "n.", def: "a brain injury caused by a blow to the head", example: "Players with suspected concussion must leave the pitch immediately.", zh: "腦震盪" },
    { front: "nausea", pos: "n.", def: "the feeling that you are going to vomit", example: "The new tablets caused dizziness and mild nausea.", zh: "噁心" },
    { front: "migraine", pos: "n.", def: "an extremely painful headache, often with sickness and sensitivity to light", example: "She lies in a dark room whenever a migraine strikes.", zh: "偏頭痛" },
    { front: "excruciating", pos: "adj.", def: "extremely painful", example: "The pain from the trapped nerve was excruciating.", zh: "劇痛難忍的" },
    { front: "throbbing", pos: "adj.", def: "(of pain) beating strongly and regularly", example: "He woke with a throbbing pain behind one eye.", zh: "抽痛的" },
    { front: "quarantine", pos: "n.", def: "a period of isolation to stop disease from spreading", example: "Arriving travellers faced ten days of quarantine.", zh: "檢疫隔離" },
    { front: "airborne", pos: "adj.", def: "carried through the air, especially of diseases or particles", example: "The virus turned out to be airborne, spreading through crowded rooms.", zh: "空氣傳播的" },
    { front: "sterilise", pos: "v.", def: "to make something completely free from bacteria", example: "All surgical instruments are sterilised between operations.", zh: "消毒滅菌" },
    { front: "disinfect", pos: "v.", def: "to clean something with a substance that kills bacteria", example: "Staff disinfect the ward twice a day.", zh: "消毒" },
    { front: "resuscitate", pos: "v.", def: "to bring someone back to consciousness, especially after their heart stops", example: "Paramedics resuscitated the swimmer on the beach.", zh: "使甦醒；急救復甦" },
    { front: "paramedic", pos: "n.", def: "a person trained to give emergency medical treatment", example: "Paramedics reached the crash site within minutes.", zh: "緊急救護員" },
    { front: "diagnose", pos: "v.", def: "to identify the exact illness a patient has", example: "She was finally diagnosed with a rare thyroid disorder.", zh: "診斷" },
    { front: "preventative", pos: "adj.", def: "intended to stop illness or problems before they start", example: "Preventative care is far cheaper than emergency treatment.", zh: "預防性的" },
    { front: "shake off", pos: "phr. v.", def: "to get rid of a minor illness or problem", example: "I cannot seem to shake off this cough.", zh: "擺脫（小病、困擾）" },
    { front: "break out in", pos: "phr. v.", def: "to suddenly become covered in spots, a rash or sweat", example: "He breaks out in a rash whenever he eats shellfish.", zh: "突然冒出（疹子、冷汗）" },
    { front: "keel over", pos: "phr. v.", def: "to fall over suddenly, especially after feeling faint", example: "One of the marchers keeled over in the midday heat.", zh: "昏倒；突然倒下" },
    { front: "come to", pos: "phr. v.", def: "to become conscious again", example: "When she came to, she was lying in a hospital bed.", zh: "甦醒過來" },
    { front: "black out", pos: "phr. v.", def: "to lose consciousness suddenly", example: "He blacked out for a few seconds after hitting his head.", zh: "昏厥" },
    { front: "waste away", pos: "phr. v.", def: "to become thinner and weaker over time", example: "Without treatment, patients simply waste away.", zh: "日漸消瘦衰弱" },
    { front: "go down with", pos: "phr. v.", def: "to catch an illness", example: "Half the office went down with flu the same week.", zh: "染上（疾病）" },
    { front: "slim down", pos: "phr. v.", def: "to become thinner, especially by dieting", example: "He slimmed down considerably before the wedding.", zh: "瘦身" },
    { front: "work off", pos: "phr. v.", def: "to get rid of something, such as weight or stress, through activity", example: "A long run helps me work off the tension of the day.", zh: "（藉活動）消耗掉" },
    { front: "burn off", pos: "phr. v.", def: "to use energy or calories through exercise", example: "Cycling to work burns off last night's dessert.", zh: "燃燒（熱量）" },
    { front: "tone up", pos: "phr. v.", def: "to make your muscles firmer and stronger", example: "These exercises tone up the core without any equipment.", zh: "緊實（肌肉）" },
    { front: "limber up", pos: "phr. v.", def: "to stretch and warm your muscles before exercise", example: "The dancers limbered up in the corridor before class.", zh: "熱身；舒展筋骨" },
    { front: "come out in", pos: "phr. v.", def: "to suddenly have spots or a rash appear on your skin", example: "She came out in hives after touching the plant.", zh: "（皮膚）冒出（疹子）" },
    { front: "stitch up", pos: "phr. v.", def: "to sew a wound together", example: "The cut needed to be stitched up at the clinic.", zh: "縫合（傷口）" },
    { front: "sleep off", pos: "phr. v.", def: "to recover from something by sleeping", example: "He went to bed early to sleep off the jet lag.", zh: "以睡眠消除（不適）" },
    { front: "seize up", pos: "phr. v.", def: "(of muscles or machines) to stop moving or working suddenly", example: "My back seized up after hours of digging in the garden.", zh: "（肌肉、機器）卡住不動" },
    { front: "pass away", pos: "phr. v.", def: "to die (a gentle, polite expression)", example: "Her grandfather passed away peacefully in his sleep.", zh: "過世（委婉語）" },
    { front: "come off", pos: "phr. v.", def: "to stop taking a medicine or drug", example: "She came off the painkillers gradually under supervision.", zh: "停用（藥物）" },
    { front: "nod off", pos: "phr. v.", def: "to fall asleep without intending to", example: "Dad nodded off in front of the television again.", zh: "打瞌睡" },
    { front: "drift off", pos: "phr. v.", def: "to fall asleep gradually", example: "I drifted off before the end of the film.", zh: "漸漸入睡" },
    { front: "a splitting headache", pos: "collocation", def: "an extremely painful headache", example: "I woke up with a splitting headache and had to cancel the meeting.", zh: "劇烈頭痛" },
    { front: "on your last legs", pos: "idiom", def: "extremely tired, ill or close to breaking down", example: "After three night shifts in a row, I was on my last legs.", zh: "精疲力竭；快撐不住" },
    { front: "at death's door", pos: "idiom", def: "so ill that you may die", example: "Last winter he was at death's door with pneumonia.", zh: "命在旦夕" },
    { front: "a new lease of life", pos: "idiom", def: "renewed energy and enthusiasm, often after illness", example: "The hip replacement gave her a new lease of life.", zh: "重獲新生；恢復活力" },
    { front: "recharge your batteries", pos: "idiom", def: "to rest in order to regain your energy", example: "A weekend by the coast is my way of recharging my batteries.", zh: "充電；恢復精力" },
    { front: "burn the candle at both ends", pos: "idiom", def: "to exhaust yourself by working late and getting up early", example: "You cannot burn the candle at both ends and expect to stay healthy.", zh: "蠟燭兩頭燒" },
    { front: "undergo surgery", pos: "collocation", def: "to have a medical operation", example: "He will undergo surgery on his knee next month.", zh: "接受手術" },
    { front: "a course of antibiotics", pos: "collocation", def: "a series of doses of medicine that kills bacteria", example: "Always finish the full course of antibiotics.", zh: "一個療程的抗生素" },
    { front: "a nervous breakdown", pos: "collocation", def: "a period of severe mental illness caused by stress", example: "Overwork drove him to the edge of a nervous breakdown.", zh: "精神崩潰" },
    { front: "a panic attack", pos: "collocation", def: "a sudden period of intense fear with physical symptoms", example: "She had a panic attack in the crowded lift.", zh: "恐慌發作" },
    { front: "skin and bone", pos: "idiom", def: "extremely thin", example: "After weeks of illness, the poor dog was all skin and bone.", zh: "瘦得皮包骨" },
    { front: "off-colour", pos: "idiom", def: "slightly ill", example: "I stayed home because I was feeling a bit off-colour.", zh: "身體不舒服" },
    { front: "a bitter pill to swallow", pos: "idiom", def: "an unpleasant fact that is hard to accept", example: "Losing the title in the final minute was a bitter pill to swallow.", zh: "難以接受的事實" },
    { front: "just what the doctor ordered", pos: "idiom", def: "exactly what is needed to make you feel better", example: "A quiet week in the mountains was just what the doctor ordered.", zh: "正合所需" },
    { front: "prevention is better than cure", pos: "idiom", def: "it is better to stop a problem happening than to fix it later", example: "We vaccinate early because prevention is better than cure.", zh: "預防勝於治療" },
    { front: "life expectancy", pos: "collocation", def: "the average number of years a person is expected to live", example: "Life expectancy has risen by a decade since the 1960s.", zh: "平均壽命" },
    { front: "intensive care", pos: "collocation", def: "hospital treatment for people who are dangerously ill", example: "She spent four days in intensive care after the crash.", zh: "加護病房（治療）" },
    { front: "an adverse reaction", pos: "collocation", def: "an unwanted, harmful response to a drug or treatment", example: "A small number of patients had an adverse reaction to the vaccine.", zh: "不良反應" },
    { front: "a blood transfusion", pos: "collocation", def: "the process of putting new blood into a person's body", example: "The accident victim needed an urgent blood transfusion.", zh: "輸血" },
    { front: "vital signs", pos: "collocation", def: "measurements such as pulse and temperature that show a person is alive", example: "Nurses monitored his vital signs through the night.", zh: "生命徵象" }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
