/* CAE Prep extra bank: vocab wave 3 */
(function () {
  var BANK = [
    /* ---------- media / journalism ---------- */
    { front: "scoop", pos: "n.", def: "an exciting news story reported by one newspaper before all the others", example: "The young reporter landed the scoop of the decade when the minister confessed to her.", zh: "獨家新聞" },
    { front: "tabloid", pos: "n.", def: "a small-format newspaper focusing on sensational stories and celebrities", example: "The tabloids were full of wild speculation about the singer's private life.", zh: "小報、八卦報" },
    { front: "broadsheet", pos: "n.", def: "a serious newspaper printed on large paper, associated with quality journalism", example: "He writes long analytical pieces for one of the national broadsheets.", zh: "大報、嚴肅報紙" },
    { front: "editorial", pos: "n.", def: "an article expressing the official opinion of a newspaper's editors", example: "The paper ran a scathing editorial criticising the government's housing policy.", zh: "社論" },
    { front: "columnist", pos: "n.", def: "a journalist who writes a regular opinion article for a publication", example: "She spent ten years as a political columnist before moving into television.", zh: "專欄作家" },
    { front: "correspondent", pos: "n.", def: "a journalist who reports on a particular subject or from a particular place", example: "Our foreign correspondent has been covering the crisis from the capital.", zh: "特派記者、通訊記者" },
    { front: "circulation", pos: "n.", def: "the number of copies of a newspaper or magazine that are sold", example: "The magazine's circulation has halved since readers moved online.", zh: "發行量" },
    { front: "readership", pos: "n.", def: "the collective group of people who read a particular publication", example: "The paper's readership is older and more conservative than its rivals'.", zh: "讀者群" },
    { front: "coverage", pos: "n.", def: "the reporting of news and events in the media", example: "The election received round-the-clock coverage on every channel.", zh: "新聞報導" },
    { front: "defamation", pos: "n.", def: "the act of damaging someone's reputation by saying or writing false things", example: "The actor sued the website for defamation after it published the false claims.", zh: "誹謗" },
    { front: "censor", pos: "v.", def: "to officially remove parts of a book, film or report considered unacceptable", example: "The wartime authorities censored every letter the soldiers sent home.", zh: "審查、刪剪" },
    { front: "publicise", pos: "v.", def: "to make information widely known to the public", example: "The charity used the interview to publicise its winter appeal.", zh: "宣傳、公開" },
    { front: "sensationalise", pos: "v.", def: "to present a story in a way that makes it seem more shocking than it really is", example: "Critics accused the channel of sensationalising the tragedy for ratings.", zh: "以聳動手法報導" },
    { front: "credibility", pos: "n.", def: "the quality of being trusted and believed in", example: "Publishing an unverified rumour cost the site much of its credibility.", zh: "可信度" },
    { front: "disclosure", pos: "n.", def: "the act of making secret or new information known to the public", example: "The disclosure of the leaked memos triggered a parliamentary inquiry.", zh: "揭露、披露" },
    { front: "whistle-blower", pos: "n.", def: "a person who reveals wrongdoing within an organisation to the public", example: "A whistle-blower inside the bank passed the documents to journalists.", zh: "吹哨者、揭弊者" },
    { front: "exposé", pos: "n.", def: "a news report that reveals shocking hidden facts about someone or something", example: "Her exposé of conditions in the care homes forced an official inquiry.", zh: "揭密報導" },
    { front: "retraction", pos: "n.", def: "a formal statement withdrawing something previously said or published", example: "The editor printed a retraction and apologised to the family.", zh: "撤回聲明" },
    { front: "fabricate", pos: "v.", def: "to invent false information in order to deceive people", example: "He was fired for fabricating quotes from sources who never existed.", zh: "捏造、編造" },
    { front: "footage", pos: "n.", def: "film or video material showing a particular event", example: "Dramatic footage of the rescue was broadcast around the world.", zh: "影像片段" },
    { front: "bulletin", pos: "n.", def: "a short official news report broadcast or published regularly", example: "The evening news bulletin led with the story of the flooding.", zh: "新聞快報" },
    { front: "clickbait", pos: "n.", def: "online content with a misleadingly dramatic headline designed to attract clicks", example: "The site relies on clickbait headlines that rarely match the actual articles.", zh: "點擊誘餌、釣魚標題" },
    { front: "paywall", pos: "n.", def: "a system that blocks access to online content unless the user pays", example: "Most quality newspapers have now put their journalism behind a paywall.", zh: "付費牆" },
    { front: "disinformation", pos: "n.", def: "false information spread deliberately to deceive people", example: "The report traced the disinformation campaign back to a network of fake accounts.", zh: "假訊息、蓄意造假的資訊" },
    { front: "hearsay", pos: "n.", def: "information you have heard from others that may not be true", example: "The article was based on hearsay rather than any documented evidence.", zh: "道聽塗說、傳聞" },
    { front: "embargo", pos: "n.", def: "an official order preventing information from being published before a certain time", example: "The details of the report are under embargo until Friday morning.", zh: "發布禁令" },
    { front: "op-ed", pos: "n.", def: "an opinion article in a newspaper written by someone who is not on its staff", example: "The professor wrote an op-ed arguing against the proposed reforms.", zh: "評論版投書" },
    { front: "slant", pos: "n.", def: "a particular biased way of presenting information", example: "Every outlet gave the same story a completely different slant.", zh: "報導角度、偏向" },
    { front: "smear", pos: "v.", def: "to try to damage someone's reputation by spreading unpleasant stories", example: "Rival politicians attempted to smear her with rumours about her finances.", zh: "抹黑" },
    { front: "soundbite", pos: "n.", def: "a short memorable phrase from a speech, used especially in news reports", example: "Modern politicians speak in soundbites designed for the evening news.", zh: "金句、簡短引語" },
    { front: "spin", pos: "n.", def: "a way of presenting information that makes it seem more favourable", example: "The press office put a positive spin on the disappointing figures.", zh: "輿論操作、話術包裝" },
    { front: "watchdog", pos: "n.", def: "an organisation that monitors companies or industries to protect the public", example: "The media watchdog fined the broadcaster for misleading its viewers.", zh: "監督機構" },
    { front: "outlet", pos: "n.", def: "a company that publishes or broadcasts news", example: "Several major news outlets declined to run the unverified story.", zh: "媒體機構、通路" },
    { front: "newsworthy", pos: "adj.", def: "interesting or important enough to be reported as news", example: "Editors must decide daily which of hundreds of events are truly newsworthy.", zh: "具新聞價值的" },
    { front: "hard-hitting", pos: "adj.", def: "direct, forceful and honest in criticising something", example: "Her hard-hitting documentary exposed conditions inside the factories.", zh: "犀利的、直言不諱的" },
    { front: "in-depth", pos: "adj.", def: "thorough and detailed, covering all aspects of a subject", example: "The site is known for in-depth investigations that take months to complete.", zh: "深入的" },
    { front: "verify", pos: "v.", def: "to check that something is true or accurate", example: "Reporters must verify every claim with at least two independent sources.", zh: "查證、核實" },
    { front: "syndicated", pos: "adj.", def: "sold to and published by many different newspapers or stations at once", example: "His syndicated column appears in over two hundred papers worldwide.", zh: "聯合供稿的" },
    { front: "byline", pos: "n.", def: "a line at the top of an article giving the writer's name", example: "It was her first byline in a national newspaper, and she framed it.", zh: "作者署名" },
    { front: "paparazzi", pos: "n.", def: "photographers who follow celebrities to take pictures of them to sell", example: "The couple left through a side entrance to avoid the waiting paparazzi.", zh: "狗仔隊" },
    { front: "anchor", pos: "n.", def: "the main presenter of a television or radio news programme", example: "The veteran anchor stayed calm as the breaking story unfolded live.", zh: "新聞主播" },
    { front: "leak out", pos: "phr. v.", def: "to become known to the public despite attempts to keep it secret", example: "Details of the merger leaked out days before the official announcement.", zh: "（消息）走漏" },
    { front: "hush up", pos: "phr. v.", def: "to prevent people from finding out about something embarrassing", example: "The club tried to hush up the scandal, but a player spoke to the press.", zh: "掩蓋、封鎖消息" },
    { front: "call out", pos: "phr. v.", def: "to publicly criticise someone for their bad behaviour", example: "The presenter was called out online for misquoting the study.", zh: "公開點名批評" },
    { front: "dig up", pos: "phr. v.", def: "to discover hidden or forgotten information through research", example: "The journalist dug up court records that contradicted the official account.", zh: "挖掘（資料、內幕）" },
    { front: "put out", pos: "phr. v.", def: "to publish or broadcast a statement or piece of information", example: "The company put out a brief statement denying all the allegations.", zh: "發布、發表" },
    { front: "play up", pos: "phr. v.", def: "to emphasise something to make it seem more important than it is", example: "The headlines played up the conflict between the two ministers.", zh: "誇大渲染" },
    { front: "tune in", pos: "phr. v.", def: "to watch or listen to a particular broadcast", example: "Millions tuned in to watch the leaders' final debate.", zh: "收看、收聽" },
    { front: "chase up", pos: "phr. v.", def: "to contact someone again in order to get information or action you are waiting for", example: "The reporter spent the morning chasing up sources who had gone quiet.", zh: "追問、催辦" },
    { front: "wheel out", pos: "phr. v.", def: "to present the same person or explanation yet again, in an unoriginal way", example: "Whenever there is a crisis, the channel wheels out the same three experts.", zh: "又搬出（老面孔、老說法）" },
    { front: "follow up", pos: "phr. v.", def: "to find out more about something or take further action on it", example: "The desk editor asked him to follow up the anonymous tip.", zh: "追蹤（報導）、跟進" },
    { front: "blow up", pos: "phr. v.", def: "to suddenly become a major story or serious situation", example: "What began as a local dispute blew up into a national controversy.", zh: "（事件）鬧大、爆發" },
    { front: "pick up on", pos: "phr. v.", def: "to notice something and react to it or report it", example: "Foreign media quickly picked up on the unusual wording of the speech.", zh: "注意到並回應" },
    { front: "weigh in", pos: "phr. v.", def: "to join a discussion by giving a forceful opinion", example: "Celebrities and politicians alike weighed in on the debate online.", zh: "加入討論、發表意見" },
    { front: "come forward", pos: "phr. v.", def: "to offer information or help, especially to authorities or the press", example: "Three more witnesses came forward after the appeal was broadcast.", zh: "挺身而出提供資訊" },
    { front: "stir up", pos: "phr. v.", def: "to deliberately cause trouble, anger or strong emotion", example: "The commentator was accused of stirring up hostility towards immigrants.", zh: "煽動、挑起" },
    { front: "run with", pos: "phr. v.", def: "to decide to publish or proceed with a story or idea", example: "Despite thin evidence, the editor decided to run with the story.", zh: "採用（報導）、放手進行" },
    { front: "dumb down", pos: "phr. v.", def: "to make something simpler and less intellectually demanding", example: "Critics complain that television news has been dumbed down for ratings.", zh: "淺薄化、降低知識水準" },
    { front: "drag up", pos: "phr. v.", def: "to mention something unpleasant from the past that people want to forget", example: "The interviewer dragged up a scandal from twenty years earlier.", zh: "重提（舊事、醜聞）" },
    { front: "latch onto", pos: "phr. v.", def: "to become very interested in an idea or story and refuse to let it go", example: "The press latched onto a single careless remark and repeated it for weeks.", zh: "抓住不放、緊咬" },
    { front: "hit the headlines", pos: "idiom", def: "to be reported prominently in the news", example: "The tiny village hit the headlines when a meteorite landed in a field.", zh: "登上新聞頭條" },
    { front: "off the record", pos: "idiom", def: "said unofficially and not intended to be reported or quoted", example: "Speaking off the record, the official admitted the policy had failed.", zh: "私下透露、不得引述" },
    { front: "hot off the press", pos: "idiom", def: "very recently printed or published; brand new", example: "Here are the results, hot off the press from the counting centre.", zh: "剛出爐的（消息）" },
    { front: "breaking news", pos: "collocation", def: "news that is currently happening and being reported as it develops", example: "The programme was interrupted by breaking news of the resignation.", zh: "突發新聞" },
    { front: "a media frenzy", pos: "collocation", def: "a period of intense and excited media attention on a story", example: "The trial sparked a media frenzy, with reporters camped outside the court.", zh: "媒體瘋狂追逐" },
    { front: "freedom of the press", pos: "collocation", def: "the right of the media to report news without government control", example: "The new law was condemned as an attack on freedom of the press.", zh: "新聞自由" },
    { front: "hold a press conference", pos: "collocation", def: "to organise a meeting at which journalists can ask questions", example: "The mayor held a press conference to address the corruption claims.", zh: "召開記者會" },
    { front: "take it with a pinch of salt", pos: "idiom", def: "to not completely believe something because it may not be accurate", example: "He tends to exaggerate, so take his version of events with a pinch of salt.", zh: "半信半疑、姑且聽之" },
    { front: "no smoke without fire", pos: "idiom", def: "rumours usually have some basis in truth", example: "She denies everything, but people whisper that there is no smoke without fire.", zh: "無風不起浪" },
    { front: "get wind of", pos: "idiom", def: "to hear about something secret or private, often indirectly", example: "Once reporters got wind of the deal, the share price soared.", zh: "聽到風聲" },
    { front: "spill the beans", pos: "idiom", def: "to reveal secret information, often unintentionally", example: "An assistant spilled the beans about the surprise reshuffle.", zh: "洩露祕密" },
    { front: "keep someone posted", pos: "idiom", def: "to continue giving someone the latest news about a situation", example: "The desk asked the reporter to keep them posted on any developments.", zh: "隨時告知最新消息" },
    { front: "hear it through the grapevine", pos: "idiom", def: "to learn news informally through gossip or rumour", example: "I heard it through the grapevine that the editor is about to resign.", zh: "小道消息聽來的" },
    { front: "a smear campaign", pos: "collocation", def: "an organised effort to damage someone's reputation with false stories", example: "The candidate claimed she was the victim of a coordinated smear campaign.", zh: "抹黑行動" },
    { front: "front-page news", pos: "collocation", def: "a story important enough to appear on the first page of a newspaper", example: "In this quiet town, a stolen bicycle can be front-page news.", zh: "頭版新聞" },
    /* ---------- urban life / housing ---------- */
    { front: "gentrification", pos: "n.", def: "the process by which a poor area becomes wealthier, pushing out original residents", example: "Gentrification has driven long-standing families out of the neighbourhood.", zh: "仕紳化、都市中產化" },
    { front: "tenant", pos: "n.", def: "a person who pays rent to live in a property owned by someone else", example: "The new law gives tenants greater protection against sudden rent rises.", zh: "房客、承租人" },
    { front: "landlord", pos: "n.", def: "a person who owns a property and rents it out to others", example: "Their landlord refused to repair the leaking roof for months.", zh: "房東" },
    { front: "eviction", pos: "n.", def: "the act of legally forcing someone to leave the property they live in", example: "The family faced eviction after falling three months behind with the rent.", zh: "驅逐、迫遷" },
    { front: "mortgage", pos: "n.", def: "a loan from a bank used to buy a house, repaid over many years", example: "With interest rates climbing, their monthly mortgage payments nearly doubled.", zh: "房屋貸款" },
    { front: "dilapidated", pos: "adj.", def: "old and in very poor condition because of neglect", example: "The council finally demolished the dilapidated warehouses by the canal.", zh: "破敗失修的" },
    { front: "derelict", pos: "adj.", def: "abandoned and in a ruined state, no longer used or cared for", example: "Artists have turned the derelict factory into a thriving studio space.", zh: "廢棄的" },
    { front: "refurbish", pos: "v.", def: "to clean, repair and improve a building or room", example: "The Victorian station has been beautifully refurbished at great expense.", zh: "翻新、整修" },
    { front: "renovate", pos: "v.", def: "to repair and improve an old building so it is in good condition again", example: "They spent two years renovating the farmhouse themselves.", zh: "翻修、改建" },
    { front: "amenity", pos: "n.", def: "a useful or pleasant facility in a place, such as shops or parks", example: "The estate lacks basic amenities such as a chemist or a post office.", zh: "生活機能、便利設施" },
    { front: "tranquil", pos: "adj.", def: "calm, quiet and peaceful", example: "Despite being minutes from the motorway, the garden square feels remarkably tranquil.", zh: "寧靜的" },
    { front: "infrastructure", pos: "n.", def: "the basic systems a city needs, such as roads, power and water supply", example: "Decades of underinvestment have left the city's infrastructure crumbling.", zh: "基礎建設" },
    { front: "metropolis", pos: "n.", def: "a very large and busy city", example: "She swapped village life for the noise and pace of the metropolis.", zh: "大都會" },
    { front: "municipality", pos: "n.", def: "a town or district with its own local government", example: "The municipality approved funding for three new cycle routes.", zh: "市政當局、自治市" },
    { front: "overcrowding", pos: "n.", def: "a situation where too many people live or gather in too small a space", example: "Overcrowding in the tower blocks has reached dangerous levels.", zh: "過度擁擠" },
    { front: "slum", pos: "n.", def: "a very poor and crowded area of a city with bad housing conditions", example: "Millions of the city's residents still live in sprawling slums.", zh: "貧民窟" },
    { front: "high-rise", pos: "adj.", def: "describing a very tall building with many floors", example: "Rows of high-rise apartment blocks now dominate the skyline.", zh: "高樓層的" },
    { front: "pedestrianise", pos: "v.", def: "to close a street to traffic so that only people on foot can use it", example: "Since the old town was pedestrianised, local cafés have flourished.", zh: "改為行人徒步區" },
    { front: "zoning", pos: "n.", def: "official rules about what kinds of buildings are allowed in each area", example: "Strict zoning laws prevent factories from being built near schools.", zh: "土地分區管制" },
    { front: "squatter", pos: "n.", def: "a person who lives in an empty building without permission or payment", example: "Squatters moved into the abandoned office block last winter.", zh: "違法佔住者" },
    { front: "lease", pos: "n.", def: "a legal contract allowing someone to use a property for a fixed period", example: "Their lease runs out in June, and the landlord wants to raise the rent.", zh: "租約" },
    { front: "sublet", pos: "v.", def: "to rent out a property that you yourself are renting from someone else", example: "She sublets the spare room to a student to help cover the rent.", zh: "轉租" },
    { front: "cramped", pos: "adj.", def: "uncomfortably small and without enough space", example: "Four of them share a cramped flat above the takeaway.", zh: "狹窄擁擠的" },
    { front: "leafy", pos: "adj.", def: "having many trees; describing a pleasant, prosperous residential area", example: "They moved from the crowded centre to a leafy suburb near the river.", zh: "綠樹成蔭的（住宅區）" },
    { front: "deprived", pos: "adj.", def: "lacking the money, services and conditions needed for a decent life", example: "The programme funds breakfast clubs in the city's most deprived districts.", zh: "貧困的、資源匱乏的" },
    { front: "run-down", pos: "adj.", def: "in poor condition because of neglect or lack of money", example: "They bought a run-down terrace house and restored it room by room.", zh: "破舊的、年久失修的" },
    { front: "residential", pos: "adj.", def: "consisting of houses rather than offices or factories", example: "Lorries are banned from the quiet residential streets after dark.", zh: "住宅（區）的" },
    { front: "outskirts", pos: "n.", def: "the outer areas of a town or city, far from the centre", example: "Rents are cheaper on the outskirts, but the commute is punishing.", zh: "市郊、外圍地帶" },
    { front: "vicinity", pos: "n.", def: "the area near or surrounding a particular place", example: "There are three primary schools in the immediate vicinity of the estate.", zh: "鄰近地區" },
    { front: "proximity", pos: "n.", def: "the state of being near something in distance", example: "The flat's proximity to the station adds thousands to its price.", zh: "鄰近、接近" },
    { front: "dwelling", pos: "n.", def: "a formal word for a house or place where someone lives", example: "The plans include two hundred new dwellings on the old airfield.", zh: "住所、住宅" },
    { front: "occupancy", pos: "n.", def: "the act of living in or using a building, or the number of people doing so", example: "The fire regulations limit occupancy of the hall to two hundred people.", zh: "居住、使用率" },
    { front: "uninhabitable", pos: "adj.", def: "impossible to live in because of poor or dangerous conditions", example: "The flooding left dozens of ground-floor flats uninhabitable.", zh: "不宜居住的" },
    { front: "eyesore", pos: "n.", def: "a building or object that is very ugly compared with its surroundings", example: "Residents want the half-finished car park demolished — it is a complete eyesore.", zh: "礙眼的建物、有礙觀瞻之物" },
    { front: "nuisance", pos: "n.", def: "a person, thing or situation that causes annoyance or problems", example: "The all-night construction work became a serious nuisance to residents.", zh: "擾人的事物、公害" },
    { front: "curb", pos: "v.", def: "to control or limit something undesirable", example: "New parking restrictions were introduced to curb traffic in the centre.", zh: "抑制、遏止" },
    { front: "revitalise", pos: "v.", def: "to bring new life and energy to a place or organisation", example: "The waterfront project has revitalised a once-neglected district.", zh: "使重現活力" },
    { front: "regeneration", pos: "n.", def: "the improvement of a run-down urban area through investment and rebuilding", example: "The regeneration scheme promises new homes, shops and a public square.", zh: "都市更新、再生" },
    { front: "urbanisation", pos: "n.", def: "the process by which more people move to live in cities", example: "Rapid urbanisation has strained the region's water and transport systems.", zh: "都市化" },
    { front: "landmark", pos: "n.", def: "a famous building or feature that is easily recognised", example: "The clock tower is the city's best-known landmark.", zh: "地標" },
    { front: "do up", pos: "phr. v.", def: "to repair and decorate a house or room", example: "They bought the cheapest house on the street and did it up over five years.", zh: "整修、裝潢（房子）" },
    { front: "double up", pos: "phr. v.", def: "to share a room or space with someone because there is not enough for everyone", example: "With rents so high, many graduates double up in tiny studio flats.", zh: "合住、擠一間" },
    { front: "knock down", pos: "phr. v.", def: "to destroy a building deliberately", example: "The old cinema was knocked down to make way for luxury flats.", zh: "拆除" },
    { front: "board up", pos: "phr. v.", def: "to cover windows or doors with wooden boards, usually because a building is empty", example: "Half the shops on the high street have been boarded up.", zh: "用木板封住" },
    { front: "settle in", pos: "phr. v.", def: "to become comfortable and familiar with a new home or situation", example: "It took the children a term to settle in after the move to the city.", zh: "安頓下來、適應新環境" },
    { front: "spruce up", pos: "phr. v.", def: "to make a place look cleaner, tidier and more attractive", example: "Volunteers spruced up the square with flowers and fresh paint.", zh: "打理、美化" },
    { front: "fence off", pos: "phr. v.", def: "to separate an area with a fence so people cannot enter", example: "The demolition site has been fenced off for safety reasons.", zh: "用圍籬隔開" },
    { front: "cordon off", pos: "phr. v.", def: "to prevent people entering an area by surrounding it with barriers or officers", example: "Police cordoned off two streets after the gas leak was discovered.", zh: "封鎖（區域）" },
    { front: "rent out", pos: "phr. v.", def: "to allow someone to use your property in exchange for regular payment", example: "They rent out the basement flat to cover their own mortgage.", zh: "出租" },
    { front: "kick out", pos: "phr. v.", def: "to force someone to leave a place, informally", example: "The landlord threatened to kick them out over the noise complaints.", zh: "趕走、逐出" },
    { front: "fix up", pos: "phr. v.", def: "to repair or improve a building or object", example: "He spends his weekends fixing up the old houseboat he bought.", zh: "修繕、修理" },
    { front: "close down", pos: "phr. v.", def: "to stop operating permanently, or to force a business to stop", example: "One by one, the independent shops on the parade have closed down.", zh: "歇業、關閉" },
    { front: "pop up", pos: "phr. v.", def: "to appear suddenly and often unexpectedly", example: "Trendy coffee bars keep popping up in the old industrial quarter.", zh: "突然出現、冒出" },
    { front: "hem in", pos: "phr. v.", def: "to surround a place closely so there is no room to move or expand", example: "The little park is hemmed in by office towers on every side.", zh: "包圍、圍住" },
    { front: "camp out", pos: "phr. v.", def: "to stay somewhere temporarily, often in uncomfortable conditions", example: "Buyers camped out overnight to secure one of the new flats.", zh: "紮營守候、暫住" },
    { front: "hollow out", pos: "phr. v.", def: "to remove the vital inner parts of something, leaving only a shell", example: "Online shopping has hollowed out many town centres.", zh: "掏空、使空洞化" },
    { front: "block off", pos: "phr. v.", def: "to close a road or passage so people or vehicles cannot pass", example: "The main avenue was blocked off for the street festival.", zh: "封閉（道路）" },
    { front: "smarten up", pos: "phr. v.", def: "to make something or someone look neater and more attractive", example: "The council has smartened up the seafront with new lighting and benches.", zh: "使變得體面、整潔" },
    { front: "back onto", pos: "phr. v.", def: "to have the back part facing or next to something", example: "The garden backs onto the railway line, so it can get noisy.", zh: "背面緊鄰" },
    { front: "urban sprawl", pos: "collocation", def: "the uncontrolled spreading of a city into surrounding countryside", example: "Urban sprawl has swallowed up the farmland that once ringed the town.", zh: "都市蔓延" },
    { front: "commuter belt", pos: "collocation", def: "the area around a city where many people live and travel into the city to work", example: "House prices in the commuter belt have risen faster than in the capital.", zh: "通勤圈" },
    { front: "housing shortage", pos: "collocation", def: "a situation in which there are not enough homes for the people who need them", example: "The housing shortage has pushed rents beyond the reach of young workers.", zh: "住宅短缺" },
    { front: "on your doorstep", pos: "idiom", def: "very close to where you live", example: "With the park and the metro on your doorstep, the flat is ideal.", zh: "近在家門口" },
    { front: "a stone's throw away", pos: "idiom", def: "a very short distance away", example: "The cottage is a stone's throw away from the harbour.", zh: "近在咫尺" },
    { front: "house-hunting", pos: "n.", def: "the activity of looking for a house or flat to buy or rent", example: "After months of house-hunting, they finally found a place they could afford.", zh: "找房子" },
    { front: "get on the property ladder", pos: "idiom", def: "to buy your first home, usually a small one, hoping to buy better ones later", example: "Without help from her parents, she could never have got on the property ladder.", zh: "買下第一間房、踏入房市" },
    { front: "put down roots", pos: "idiom", def: "to settle in a place and make it your long-term home", example: "After years of moving around, they finally put down roots in a seaside town.", zh: "落地生根、定居" },
    { front: "a no-go area", pos: "collocation", def: "a district considered too dangerous to enter", example: "The estate was once dismissed as a no-go area, but it has changed completely.", zh: "危險禁區" },
    { front: "within walking distance", pos: "collocation", def: "close enough to reach on foot", example: "Two schools and a supermarket are within walking distance of the estate.", zh: "步行可達的範圍內" },
    { front: "the hustle and bustle", pos: "collocation", def: "the noisy, busy activity of a crowded place", example: "She loves the hustle and bustle of the morning market.", zh: "熙攘喧囂" },
    { front: "prime location", pos: "collocation", def: "an ideal position for a home or business, usually central and desirable", example: "The restaurant occupies a prime location overlooking the river.", zh: "黃金地段" },
    { front: "inner city", pos: "collocation", def: "the central part of a city, often associated with social problems", example: "The charity runs youth clubs in several inner city neighbourhoods.", zh: "市中心（貧困）地區" },
    { front: "living conditions", pos: "collocation", def: "the circumstances in which people live, such as housing quality and comfort", example: "Inspectors described the living conditions in the hostel as appalling.", zh: "居住環境" },
    { front: "home from home", pos: "idiom", def: "a place where you feel as comfortable as in your own home", example: "The little guesthouse became a home from home during his long stays.", zh: "賓至如歸之處" },
    /* ---------- money / consumerism ---------- */
    { front: "thrifty", pos: "adj.", def: "careful with money and avoiding waste", example: "My thrifty grandmother saved every jar and reused every envelope.", zh: "節儉的" },
    { front: "frugal", pos: "adj.", def: "spending very little money and only on what is necessary", example: "Years of frugal living allowed them to retire early.", zh: "省吃儉用的" },
    { front: "extravagant", pos: "adj.", def: "spending much more money than is necessary or reasonable", example: "He apologised for the extravagant gift, but she was secretly delighted.", zh: "奢侈的、揮霍的" },
    { front: "exorbitant", pos: "adj.", def: "far too expensive; unreasonably high in price", example: "Tourists complain about the exorbitant prices at the airport cafés.", zh: "（價格）過高的、離譜的" },
    { front: "affluent", pos: "adj.", def: "wealthy; having plenty of money", example: "The boutique targets affluent shoppers in the financial district.", zh: "富裕的" },
    { front: "destitute", pos: "adj.", def: "extremely poor, lacking even basic necessities", example: "The collapse of the bank left thousands of savers destitute.", zh: "一貧如洗的" },
    { front: "splurge", pos: "v.", def: "to spend a lot of money on something enjoyable but unnecessary", example: "After her bonus arrived, she splurged on a designer handbag.", zh: "揮霍、大買特買" },
    { front: "haggle", pos: "v.", def: "to argue about the price of something in order to pay less", example: "He haggled with the stallholder for ten minutes over an old lamp.", zh: "討價還價" },
    { front: "overpriced", pos: "adj.", def: "costing more than it is really worth", example: "The food was decent but hopelessly overpriced for the portion size.", zh: "定價過高的" },
    { front: "instalment", pos: "n.", def: "one of several regular payments made to pay off a debt", example: "They are paying for the sofa in twelve monthly instalments.", zh: "分期付款（的一期）" },
    { front: "arrears", pos: "n.", def: "money that is owed and should already have been paid", example: "The tenants were two months in arrears with their rent.", zh: "欠款、拖欠" },
    { front: "creditor", pos: "n.", def: "a person or company that money is owed to", example: "The firm's creditors agreed to accept half of what they were owed.", zh: "債權人" },
    { front: "debtor", pos: "n.", def: "a person or company that owes money", example: "The court can order debtors to repay a fixed sum each month.", zh: "債務人" },
    { front: "insolvent", pos: "adj.", def: "unable to pay the money you owe", example: "The auditors declared the retailer insolvent last spring.", zh: "無力償債的" },
    { front: "overdraft", pos: "n.", def: "an arrangement allowing you to spend more money than you have in your bank account", example: "By the end of the month he was deep into his overdraft again.", zh: "透支額度" },
    { front: "pawn", pos: "v.", def: "to leave a valuable object with a shop as security for borrowed money", example: "She pawned her wedding ring to pay the electricity bill.", zh: "典當" },
    { front: "counterfeit", pos: "adj.", def: "made as an illegal copy in order to deceive people", example: "Customs officers seized thousands of counterfeit watches at the port.", zh: "偽造的、仿冒的" },
    { front: "consumerism", pos: "n.", def: "the belief that buying and owning things is important, or the culture based on it", example: "The documentary examines how consumerism shapes our sense of identity.", zh: "消費主義" },
    { front: "materialistic", pos: "adj.", def: "caring more about money and possessions than about ideas or values", example: "He dismissed the city crowd as shallow and materialistic.", zh: "物質主義的" },
    { front: "hoard", pos: "v.", def: "to collect and store large amounts of something, often secretly", example: "During the shortage, some shoppers hoarded tins and cooking oil.", zh: "囤積" },
    { front: "squander", pos: "v.", def: "to waste money, time or opportunities carelessly", example: "He squandered his inheritance on failed schemes within three years.", zh: "揮霍、浪費" },
    { front: "windfall", pos: "n.", def: "an amount of money received unexpectedly", example: "The unexpected windfall from her aunt's will paid off the car loan.", zh: "意外之財" },
    { front: "outlay", pos: "n.", def: "an amount of money spent for a particular purpose, especially to start something", example: "Setting up the food truck required an initial outlay of ten thousand pounds.", zh: "初期支出、費用" },
    { front: "markup", pos: "n.", def: "the amount added to the cost of something to determine its selling price", example: "Restaurants typically apply a huge markup on bottled wine.", zh: "加價幅度" },
    { front: "reimburse", pos: "v.", def: "to pay money back to someone who has spent it on your behalf", example: "The company will reimburse you for travel expenses within two weeks.", zh: "報銷、償還" },
    { front: "skimp", pos: "v.", def: "to spend less money or effort on something than it really needs", example: "The builders skimped on materials, and the cracks soon appeared.", zh: "節省、偷工減料" },
    { front: "lavish", pos: "adj.", def: "impressively expensive, generous or luxurious", example: "The launch party was a lavish affair with champagne and live music.", zh: "奢華的、鋪張的" },
    { front: "miserly", pos: "adj.", def: "hating to spend money; mean with money", example: "Their miserly uncle refused even to heat the house in winter.", zh: "吝嗇的" },
    { front: "stingy", pos: "adj.", def: "unwilling to spend or give money; not generous", example: "Don't be so stingy — it's your turn to buy the coffees.", zh: "小氣的" },
    { front: "hard-up", pos: "adj.", def: "having very little money, especially temporarily", example: "As hard-up students, we lived on pasta and market vegetables.", zh: "手頭拮据的" },
    { front: "retailer", pos: "n.", def: "a business that sells goods directly to the public", example: "Online retailers have slashed prices ahead of the holiday season.", zh: "零售商" },
    { front: "wholesale", pos: "adj.", def: "relating to the selling of goods in large quantities to shops rather than customers", example: "He buys flowers at wholesale prices and sells them at the weekend market.", zh: "批發的" },
    { front: "warranty", pos: "n.", def: "a written promise to repair or replace a product if it breaks within a period", example: "The washing machine failed a week after the warranty expired.", zh: "保固" },
    { front: "depreciate", pos: "v.", def: "to lose value over time", example: "A new car depreciates the moment you drive it out of the showroom.", zh: "貶值、折舊" },
    { front: "premium", pos: "n.", def: "an amount above the usual price, or a regular payment for insurance", example: "Shoppers will pay a premium for anything labelled organic.", zh: "溢價；保險費" },
    { front: "surcharge", pos: "n.", def: "an extra amount of money added to the usual cost", example: "The airline adds a hefty surcharge for paying by credit card.", zh: "附加費" },
    { front: "levy", pos: "v.", def: "to officially demand payment of a tax or charge", example: "The city plans to levy a tax on single-use packaging.", zh: "課徵、徵收" },
    { front: "rebate", pos: "n.", def: "an amount of money returned to you, often from tax or a purchase", example: "Households installing solar panels qualify for a government rebate.", zh: "退款、退稅" },
    { front: "cost-effective", pos: "adj.", def: "giving good value in relation to the money spent", example: "Insulating the loft is the most cost-effective way to cut heating bills.", zh: "符合成本效益的" },
    { front: "knock-off", pos: "n.", def: "a cheap copy of an expensive product", example: "The bag looked genuine, but it turned out to be a knock-off.", zh: "仿冒品、山寨貨" },
    { front: "gimmick", pos: "n.", def: "a trick or feature designed to attract attention rather than provide real value", example: "The free gift is just a marketing gimmick to draw shoppers in.", zh: "花招、噱頭" },
    { front: "put by", pos: "phr. v.", def: "to save money gradually for future use", example: "She puts a little by every week for the children's school trips.", zh: "積攢、存錢" },
    { front: "save up", pos: "phr. v.", def: "to keep money over time in order to buy something", example: "The children are saving up for a games console between them.", zh: "存錢" },
    { front: "set aside", pos: "phr. v.", def: "to keep money or time for a particular purpose", example: "Try to set aside ten percent of your salary every month.", zh: "留存、撥出" },
    { front: "dip into", pos: "phr. v.", def: "to take some money from an amount you have saved", example: "They had to dip into their savings to cover the roof repairs.", zh: "動用（積蓄）" },
    { front: "run up", pos: "phr. v.", def: "to allow debts or bills to accumulate to a large amount", example: "He ran up an enormous bill on his father's credit card.", zh: "積欠（債務、帳單）" },
    { front: "pay up", pos: "phr. v.", def: "to pay money that you owe, especially unwillingly", example: "The insurer finally paid up after months of excuses.", zh: "（不情願地）付清" },
    { front: "rip off", pos: "phr. v.", def: "to charge someone far too much money for something", example: "That taxi driver ripped us off — the fare should have been half that.", zh: "敲竹槓、坑錢" },
    { front: "shell out", pos: "phr. v.", def: "to pay money for something, often reluctantly", example: "Parents shell out hundreds every year on school uniforms.", zh: "掏錢、破費" },
    { front: "scrape by", pos: "phr. v.", def: "to manage to live with barely enough money", example: "On a trainee's wage, she just about scrapes by each month.", zh: "勉強度日" },
    { front: "get by", pos: "phr. v.", def: "to manage to survive or deal with a situation with what you have", example: "We got by on one salary while he retrained as a nurse.", zh: "勉強應付、過得去" },
    { front: "live off", pos: "phr. v.", def: "to depend on a particular source of money or food to survive", example: "He lived off his savings for a year while writing the novel.", zh: "靠…生活" },
    { front: "cough up", pos: "phr. v.", def: "to provide money unwillingly", example: "The club was forced to cough up a large fine for the fans' behaviour.", zh: "不甘願地付錢" },
    { front: "chip in", pos: "phr. v.", def: "to contribute some money towards a shared cost", example: "Everyone in the office chipped in for her leaving present.", zh: "湊錢、出份子" },
    { front: "stump up", pos: "phr. v.", def: "to pay an amount of money reluctantly", example: "Fans must stump up eighty pounds for a ticket to the final.", zh: "被迫掏出（錢）" },
    { front: "snap up", pos: "phr. v.", def: "to buy something quickly because it is cheap or in demand", example: "Bargain hunters snapped up the discounted televisions within an hour.", zh: "搶購" },
    { front: "shop around", pos: "phr. v.", def: "to compare prices in different shops before buying", example: "It pays to shop around before renewing your car insurance.", zh: "貨比三家" },
    { front: "pay down", pos: "phr. v.", def: "to reduce a debt by paying part of what is owed", example: "They used the inheritance to pay down the mortgage.", zh: "償還（部分債務）" },
    { front: "fritter away", pos: "phr. v.", def: "to waste money or time gradually on unimportant things", example: "He frittered away his allowance on snacks and phone games.", zh: "一點一滴浪費掉" },
    { front: "settle up", pos: "phr. v.", def: "to pay what you owe at the end of a period or event", example: "Let me settle up with the waiter and then we can go.", zh: "結清帳款" },
    { front: "disposable income", pos: "collocation", def: "the money left to spend after taxes and essential costs are paid", example: "Rising rents have eaten into young people's disposable income.", zh: "可支配所得" },
    { front: "purchasing power", pos: "collocation", def: "the amount of goods and services that money can buy", example: "Inflation has quietly eroded the purchasing power of pensions.", zh: "購買力" },
    { front: "impulse buying", pos: "collocation", def: "buying things suddenly without planning to", example: "Supermarkets place sweets by the tills to encourage impulse buying.", zh: "衝動購物" },
    { front: "cost of living", pos: "collocation", def: "the amount of money needed for basic expenses such as food and housing", example: "The cost of living in the capital is nearly double the national average.", zh: "生活成本" },
    { front: "value for money", pos: "collocation", def: "worth the amount paid; good quality relative to price", example: "The set menu is excellent value for money at fifteen pounds.", zh: "物超所值" },
    { front: "tighten your belt", pos: "idiom", def: "to spend less money because you have less than before", example: "With the factory on short hours, everyone in town is tightening their belts.", zh: "勒緊褲帶、節省開支" },
    { front: "burn a hole in your pocket", pos: "idiom", def: "said of money you are eager to spend as soon as you have it", example: "His birthday money was burning a hole in his pocket by lunchtime.", zh: "有錢就手癢想花" },
    { front: "money down the drain", pos: "idiom", def: "money that has been completely wasted", example: "The unused gym membership was just money down the drain.", zh: "白花的錢、打水漂" },
    { front: "daylight robbery", pos: "idiom", def: "a situation where you are charged far too much money", example: "Nine pounds for a small coffee? That's daylight robbery.", zh: "獅子大開口、搶錢" },
    { front: "cost an arm and a leg", pos: "idiom", def: "to be extremely expensive", example: "Repairing the roof after the storm cost us an arm and a leg.", zh: "貴得要命" },
    { front: "live beyond your means", pos: "idiom", def: "to spend more money than you earn or can afford", example: "Easy credit tempted many households to live beyond their means.", zh: "入不敷出、過度消費" },
    { front: "a nest egg", pos: "idiom", def: "a sum of money saved for the future", example: "Decades of careful saving left them a comfortable nest egg for retirement.", zh: "養老金、儲備金" },
    { front: "foot the bill", pos: "idiom", def: "to pay for something, especially something expensive", example: "Taxpayers will ultimately foot the bill for the failed project.", zh: "買單、承擔費用" },
    { front: "on a shoestring", pos: "idiom", def: "done with very little money", example: "They travelled across South America on a shoestring, staying in hostels.", zh: "以極少的預算" },
    { front: "keeping up with the Joneses", pos: "idiom", def: "trying to own the same expensive things as your neighbours or friends", example: "They bought the new car purely out of keeping up with the Joneses.", zh: "與人攀比、跟風炫耀" },
    /* ---------- history / tradition ---------- */
    { front: "archaic", pos: "adj.", def: "extremely old-fashioned and no longer used", example: "The contract was written in archaic legal language nobody could follow.", zh: "古老的、過時的" },
    { front: "medieval", pos: "adj.", def: "relating to the Middle Ages in European history", example: "The medieval walls still encircle the oldest part of the town.", zh: "中世紀的" },
    { front: "dynasty", pos: "n.", def: "a series of rulers from the same family, or a powerful family over generations", example: "The palace was built at the height of the dynasty's power.", zh: "王朝、朝代" },
    { front: "imperial", pos: "adj.", def: "relating to an empire or its ruler", example: "The museum's imperial collection includes robes worn by the last emperor.", zh: "帝國的" },
    { front: "colonial", pos: "adj.", def: "relating to a country's control of other territories, or that period", example: "Many street names in the port date from the colonial era.", zh: "殖民（時期）的" },
    { front: "artefact", pos: "n.", def: "an object made by humans in the past that has historical interest", example: "Divers recovered hundreds of artefacts from the sunken merchant ship.", zh: "文物、手工製品" },
    { front: "excavation", pos: "n.", def: "the careful digging up of an area to find ancient remains", example: "The excavation revealed a Roman villa beneath the school playing field.", zh: "考古挖掘" },
    { front: "chronicle", pos: "n.", def: "a written record of historical events in the order they happened", example: "The monk's chronicle is our only account of the town's early years.", zh: "編年史" },
    { front: "archive", pos: "n.", def: "a collection of historical documents, or the place where they are kept", example: "She spent the summer in the national archive researching wartime letters.", zh: "檔案（館）" },
    { front: "relic", pos: "n.", def: "an object or custom surviving from an earlier time", example: "The rusting crane is a relic of the city's shipbuilding past.", zh: "遺物、遺跡" },
    { front: "ancestral", pos: "adj.", def: "belonging to or inherited from your ancestors", example: "The family finally returned to their ancestral village after fifty years.", zh: "祖傳的、祖先的" },
    { front: "descendant", pos: "n.", def: "a person related to someone who lived in the past", example: "Descendants of the original settlers gathered for the anniversary.", zh: "後裔、子孫" },
    { front: "lineage", pos: "n.", def: "the series of families from which a person is descended", example: "The horse's lineage can be traced back over two centuries.", zh: "血統、世系" },
    { front: "folklore", pos: "n.", def: "the traditional stories, customs and beliefs of a community", example: "According to local folklore, the lake is home to a sleeping giant.", zh: "民間傳說" },
    { front: "ritual", pos: "n.", def: "a set of actions performed in a fixed order, often for religious reasons", example: "The harvest ritual has been performed in the village square for centuries.", zh: "儀式" },
    { front: "customary", pos: "adj.", def: "usual or traditional in a particular society or situation", example: "It is customary to bring a small gift when visiting someone's home.", zh: "慣例的、習俗上的" },
    { front: "commemorate", pos: "v.", def: "to honour the memory of an important person or event", example: "A new statue was unveiled to commemorate the fallen miners.", zh: "紀念" },
    { front: "centenary", pos: "n.", def: "the one hundredth anniversary of an event", example: "The theatre marked its centenary with a season of classic plays.", zh: "一百週年" },
    { front: "memorial", pos: "n.", def: "a structure or object created to remind people of a person or event", example: "Fresh flowers are laid at the war memorial every November.", zh: "紀念碑、紀念物" },
    { front: "posterity", pos: "n.", def: "the people who will live in the future", example: "The letters were carefully preserved for posterity.", zh: "後世、後代" },
    { front: "bygone", pos: "adj.", def: "belonging to a past period of time", example: "The steam fair recreates the sights and sounds of a bygone age.", zh: "過去的、昔日的" },
    { front: "antiquated", pos: "adj.", def: "old-fashioned and no longer suitable for modern needs", example: "The court's antiquated procedures baffle anyone who encounters them.", zh: "陳舊過時的" },
    { front: "primitive", pos: "adj.", def: "belonging to a very early stage of development; very simple", example: "The first settlers survived the winters in primitive turf huts.", zh: "原始的、簡陋的" },
    { front: "feudal", pos: "adj.", def: "relating to the medieval social system in which people worked land for a lord", example: "Under the feudal system, peasants owed labour and loyalty to the landowner.", zh: "封建的" },
    { front: "monarchy", pos: "n.", def: "a system of government with a king or queen as head of state", example: "The country abolished its monarchy after the revolution.", zh: "君主制" },
    { front: "abdicate", pos: "v.", def: "to give up the position of king or queen", example: "The ageing king abdicated in favour of his eldest daughter.", zh: "退位" },
    { front: "reign", pos: "n.", def: "the period during which a king or queen rules", example: "The cathedral was completed during the reign of the second Edward.", zh: "在位期間、統治" },
    { front: "conquest", pos: "n.", def: "the act of taking control of a country or people by force", example: "The conquest of the islands changed their language and religion forever.", zh: "征服" },
    { front: "uprising", pos: "n.", def: "an act of rebellion by a group of people against those in power", example: "The failed uprising was brutally suppressed within a week.", zh: "起義、暴動" },
    { front: "revolt", pos: "n.", def: "a violent refusal by people to accept someone's authority", example: "Heavy taxation sparked a peasants' revolt across the province.", zh: "反叛、造反" },
    { front: "turmoil", pos: "n.", def: "a state of great confusion, disorder or uncertainty", example: "The country descended into political turmoil after the king's death.", zh: "動盪、混亂" },
    { front: "milestone", pos: "n.", def: "a very important event or stage in the development of something", example: "The signing of the treaty was a milestone in the two nations' history.", zh: "里程碑" },
    { front: "predecessor", pos: "n.", def: "the person or thing that came before another in a role or position", example: "The new museum is three times the size of its predecessor.", zh: "前任、前身" },
    { front: "forebear", pos: "n.", def: "an ancestor; a member of your family from long ago", example: "Her forebears farmed this valley for six generations.", zh: "祖先" },
    { front: "restoration", pos: "n.", def: "the work of returning something old to its original condition", example: "The restoration of the frescoes took a team of experts ten years.", zh: "修復" },
    { front: "authenticity", pos: "n.", def: "the quality of being genuine and not a copy or fake", example: "Experts questioned the authenticity of the newly discovered manuscript.", zh: "真實性、真品性" },
    { front: "nostalgia", pos: "n.", def: "a warm feeling of pleasure and slight sadness when remembering the past", example: "The old songs filled the room with nostalgia for their student days.", zh: "懷舊之情" },
    { front: "quaint", pos: "adj.", def: "attractively old-fashioned or unusual", example: "The quaint fishing village has barely changed in a hundred years.", zh: "古色古香的" },
    { front: "time-honoured", pos: "adj.", def: "respected because it has existed for a long time", example: "The bread is still baked according to a time-honoured recipe.", zh: "歷史悠久的、行之有年的" },
    { front: "deep-rooted", pos: "adj.", def: "strongly established and very difficult to change", example: "Deep-rooted customs govern how weddings are celebrated here.", zh: "根深蒂固的" },
    { front: "sacred", pos: "adj.", def: "considered holy or deserving of great respect", example: "The grove was sacred to the islanders, and no tree could be cut there.", zh: "神聖的" },
    { front: "date back to", pos: "phr. v.", def: "to have existed since a particular time in the past", example: "Parts of the abbey date back to the eleventh century.", zh: "追溯至、始於" },
    { front: "hold onto", pos: "phr. v.", def: "to keep something and refuse to give it up", example: "The community has held onto its dialect despite a century of change.", zh: "保留、堅守" },
    { front: "go down in history", pos: "idiom", def: "to be remembered for a long time as part of history", example: "The signing ceremony will go down in history as the moment peace began.", zh: "名留青史、載入史冊" },
    { front: "carry on", pos: "phr. v.", def: "to continue doing something, especially a tradition or activity", example: "His grandchildren have carried on the family boat-building trade.", zh: "繼續、延續" },
    { front: "hark back to", pos: "phr. v.", def: "to remind you of or refer back to something from the past", example: "The building's arches hark back to the grand stations of the steam age.", zh: "令人回想起、追憶" },
    { front: "stem from", pos: "phr. v.", def: "to have developed from something in the past; to originate in", example: "Many of the festival's rituals stem from ancient harvest ceremonies.", zh: "源自於" },
    { front: "trace back", pos: "phr. v.", def: "to find the origin of something by examining its history", example: "Genealogists traced the family back to a blacksmith born in 1640.", zh: "追溯" },
    { front: "hail from", pos: "phr. v.", def: "to come originally from a particular place", example: "The composer hailed from a small mining town in the north.", zh: "來自、出身於" },
    { front: "pass on", pos: "phr. v.", def: "to give knowledge, skills or objects to people who live after you", example: "Elders gather weekly to pass on the old stories to the children.", zh: "傳授、傳遞" },
    { front: "keep up", pos: "phr. v.", def: "to continue a custom or practice without letting it end", example: "They still keep up the tradition of first-footing at New Year.", zh: "保持、維持（習俗）" },
    { front: "pass down", pos: "phr. v.", def: "to transmit knowledge, customs or possessions to younger generations", example: "The weaving patterns are passed down orally, never written out.", zh: "代代相傳" },
    { front: "spring from", pos: "phr. v.", def: "to be caused by or originate from something", example: "The town's wealth sprang from the wool trade of the fifteenth century.", zh: "源於、起因於" },
    { front: "cling to", pos: "phr. v.", def: "to refuse to give up a belief, custom or hope", example: "The islanders cling to customs their mainland cousins abandoned long ago.", zh: "堅守、緊抓不放" },
    { front: "revert to", pos: "phr. v.", def: "to return to a former state, practice or subject", example: "After the experiment failed, the school reverted to traditional teaching.", zh: "恢復、回復到" },
    { front: "give way to", pos: "phr. v.", def: "to be replaced by something newer", example: "Horse-drawn carts gradually gave way to motor lorries in the 1920s.", zh: "被…取代、讓位給" },
    { front: "fade away", pos: "phr. v.", def: "to disappear slowly and gradually", example: "The dialect is fading away as the older generation passes on.", zh: "逐漸消逝" },
    { front: "root out", pos: "phr. v.", def: "to find and remove something undesirable completely", example: "The new abbot vowed to root out corruption in the monastery.", zh: "剷除、根除" },
    { front: "look back on", pos: "phr. v.", def: "to think about a time or event in your past", example: "She looks back on her village childhood with great fondness.", zh: "回顧、回憶" },
    { front: "usher in", pos: "phr. v.", def: "to mark the beginning of a new period or important change", example: "The printing press ushered in an age of mass literacy.", zh: "開啟、迎來（新時代）" },
    { front: "break with tradition", pos: "collocation", def: "to deliberately do something differently from the way it was done before", example: "The young chef broke with tradition by serving the feast as street food.", zh: "打破傳統" },
    { front: "time immemorial", pos: "idiom", def: "a time so long ago that nobody can remember it", example: "Shepherds have driven their flocks over this pass since time immemorial.", zh: "遠古以來、自古" },
    { front: "a rite of passage", pos: "idiom", def: "an event marking an important stage in someone's life", example: "The solo hike is a rite of passage for teenagers in the region.", zh: "成年禮、人生重要儀式" },
    { front: "steeped in history", pos: "collocation", def: "full of historical associations and traditions", example: "Every alleyway of the old quarter is steeped in history.", zh: "充滿歷史氛圍的" },
    { front: "the good old days", pos: "idiom", def: "an earlier period of time remembered as better than the present", example: "Grandad loves telling us about the good old days before television.", zh: "美好的舊時光" },
    { front: "a turning point", pos: "collocation", def: "a moment when an important change begins to happen", example: "The battle proved a turning point in the long war for independence.", zh: "轉捩點" },
    { front: "living memory", pos: "collocation", def: "the period of time that people still alive can remember", example: "It was the worst flood in living memory, the elders agreed.", zh: "世人記憶所及（的年代）" },
    { front: "pass the torch", pos: "idiom", def: "to give your duties or role to a younger person who continues the work", example: "After forty years leading the choir, she passed the torch to her student.", zh: "傳承衣缽、交棒" },
    { front: "ancient history", pos: "idiom", def: "something from the past that is no longer important or relevant", example: "Our old quarrel is ancient history — we made peace years ago.", zh: "陳年往事" },
    { front: "set in stone", pos: "idiom", def: "fixed and impossible to change", example: "The seating plan for the ceremony is traditional but not set in stone.", zh: "板上釘釘、不可更改" },
    { front: "a thing of the past", pos: "idiom", def: "something that no longer exists or happens", example: "Handwritten letters have become a thing of the past for most people.", zh: "過時之物、成為歷史" },
    { front: "turn back the clock", pos: "idiom", def: "to return to a way things were in the past", example: "The festival turns back the clock with costumes, carts and candlelight.", zh: "讓時光倒流" },
    { front: "a blast from the past", pos: "idiom", def: "something that suddenly and strongly reminds you of an earlier time", example: "Hearing that jingle again was a real blast from the past.", zh: "勾起回憶的舊事物" },
    { front: "keep tradition alive", pos: "collocation", def: "to make sure a custom continues to be practised", example: "The dance school works hard to keep tradition alive among city children.", zh: "延續傳統" },
    { front: "national identity", pos: "collocation", def: "the shared sense of culture and belonging felt by the people of a nation", example: "The epic poems became central to the country's national identity.", zh: "國族認同" },
    /* ---------- weather / natural phenomena ---------- */
    { front: "torrential", pos: "adj.", def: "describing rain that falls extremely heavily", example: "Torrential rain turned the campsite into a sea of mud overnight.", zh: "傾盆的（大雨）" },
    { front: "downpour", pos: "n.", def: "a sudden, very heavy fall of rain", example: "We sheltered in a doorway until the downpour eased.", zh: "傾盆大雨" },
    { front: "blizzard", pos: "n.", def: "a severe snowstorm with strong winds and poor visibility", example: "The climbers were trapped in their tent for two days by a blizzard.", zh: "暴風雪" },
    { front: "gale", pos: "n.", def: "a very strong wind", example: "Ferries were cancelled as gales battered the coast.", zh: "強風、大風" },
    { front: "gust", pos: "n.", def: "a sudden, brief rush of strong wind", example: "A sudden gust snatched the umbrella out of her hands.", zh: "陣風" },
    { front: "hail", pos: "n.", def: "small balls of ice that fall like rain", example: "Hail the size of marbles dented cars across the valley.", zh: "冰雹" },
    { front: "sleet", pos: "n.", def: "a mixture of rain and partly melted snow", example: "The drizzle turned to sleet as the temperature dropped.", zh: "雨夾雪" },
    { front: "muggy", pos: "adj.", def: "unpleasantly warm and humid", example: "The muggy August nights made it almost impossible to sleep.", zh: "悶熱潮濕的" },
    { front: "humid", pos: "adj.", def: "containing a lot of water vapour; damp and warm", example: "The air grows unbearably humid in the weeks before the monsoon.", zh: "潮濕悶熱的" },
    { front: "sweltering", pos: "adj.", def: "uncomfortably hot", example: "They queued for hours in the sweltering afternoon heat.", zh: "酷熱難耐的" },
    { front: "scorching", pos: "adj.", def: "extremely hot", example: "Nothing moved in the village during the scorching midday hours.", zh: "灼熱的" },
    { front: "overcast", pos: "adj.", def: "covered with clouds; dull and grey", example: "The sky stayed overcast all week, and the washing never dried.", zh: "陰天的、多雲的" },
    { front: "avalanche", pos: "n.", def: "a large mass of snow and ice sliding rapidly down a mountain", example: "The road through the pass is closed whenever avalanche risk is high.", zh: "雪崩" },
    { front: "landslide", pos: "n.", def: "a mass of earth and rock sliding down a slope", example: "Heavy rains triggered a landslide that buried part of the highway.", zh: "山崩、土石流" },
    { front: "tremor", pos: "n.", def: "a small earthquake or shaking movement of the ground", example: "Residents felt a mild tremor but no damage was reported.", zh: "輕微地震、震動" },
    { front: "aftershock", pos: "n.", def: "a smaller earthquake following the main one", example: "Aftershocks continued to rattle the city for several days.", zh: "餘震" },
    { front: "eruption", pos: "n.", def: "an explosion of a volcano sending out lava, ash and gas", example: "The eruption blanketed nearby farms in a layer of grey ash.", zh: "火山爆發" },
    { front: "cyclone", pos: "n.", def: "a violent tropical storm with rotating winds", example: "The cyclone tore roofs from houses along the entire coastline.", zh: "氣旋、熱帶風暴" },
    { front: "monsoon", pos: "n.", def: "a seasonal wind bringing heavy rain to South Asia, or the rainy season itself", example: "Farmers wait anxiously for the monsoon to break each June.", zh: "季風（雨季）" },
    { front: "heatwave", pos: "n.", def: "a period of unusually hot weather", example: "The prolonged heatwave strained the country's power grid.", zh: "熱浪" },
    { front: "frost", pos: "n.", def: "a thin white layer of ice that forms in freezing conditions", example: "An early frost destroyed half the orchard's blossom.", zh: "霜" },
    { front: "thaw", pos: "v.", def: "to become warmer so that snow and ice melt", example: "When the river finally thawed, the valley flooded within days.", zh: "解凍、融化" },
    { front: "deluge", pos: "n.", def: "a severe flood or an overwhelming quantity of rain", example: "The deluge washed away bridges that had stood for a century.", zh: "洪水、暴雨" },
    { front: "precipitation", pos: "n.", def: "rain, snow, sleet or hail that falls from the sky", example: "The desert receives almost no precipitation for months at a time.", zh: "降水" },
    { front: "atmospheric", pos: "adj.", def: "relating to the air surrounding the earth", example: "Sudden changes in atmospheric pressure often precede a storm.", zh: "大氣的" },
    { front: "turbulent", pos: "adj.", def: "moving violently and unpredictably, as air or water", example: "The small plane bounced through turbulent air over the mountains.", zh: "亂流的、洶湧的" },
    { front: "treacherous", pos: "adj.", def: "dangerous in a hidden or unpredictable way", example: "Black ice made the mountain roads treacherous before dawn.", zh: "暗藏危險的" },
    { front: "inclement", pos: "adj.", def: "unpleasantly cold, wet or stormy (formal)", example: "The ceremony was moved indoors owing to inclement weather.", zh: "（天氣）惡劣的" },
    { front: "erratic", pos: "adj.", def: "irregular and unpredictable in pattern or behaviour", example: "Increasingly erratic rainfall is making harvests hard to plan.", zh: "反覆無常的" },
    { front: "temperate", pos: "adj.", def: "having mild temperatures, neither very hot nor very cold", example: "The islands enjoy a temperate climate all year round.", zh: "溫帶的、溫和的" },
    { front: "visibility", pos: "n.", def: "the distance you can see, depending on weather conditions", example: "Fog reduced visibility on the motorway to fifty metres.", zh: "能見度" },
    { front: "evaporate", pos: "v.", def: "to change from liquid into vapour and disappear", example: "In the fierce heat, the shallow lake evaporates almost entirely.", zh: "蒸發" },
    { front: "condensation", pos: "n.", def: "drops of water formed when warm vapour touches a cold surface", example: "Each winter morning the windows are thick with condensation.", zh: "凝結（的水珠）" },
    { front: "windswept", pos: "adj.", def: "exposed to strong winds; blown untidy by the wind", example: "The lighthouse stands on a windswept headland above the cliffs.", zh: "強風吹拂的" },
    { front: "parched", pos: "adj.", def: "extremely dry because of a lack of rain", example: "The parched fields cracked open under the relentless sun.", zh: "乾涸的、焦乾的" },
    { front: "sodden", pos: "adj.", def: "completely soaked with water", example: "We squelched home across the sodden meadow.", zh: "濕透的" },
    { front: "drenched", pos: "adj.", def: "extremely wet, usually from rain", example: "They arrived at the pub drenched and laughing after the storm.", zh: "淋濕的" },
    { front: "glacial", pos: "adj.", def: "extremely cold, or relating to glaciers", example: "A glacial wind swept down from the peaks at nightfall.", zh: "冰冷的、冰河的" },
    { front: "seismic", pos: "adj.", def: "relating to earthquakes or movements of the earth's crust", example: "The observatory monitors seismic activity along the fault line.", zh: "地震的" },
    { front: "molten", pos: "adj.", def: "melted into liquid by extreme heat, especially rock or metal", example: "Rivers of molten lava crept slowly towards the abandoned village.", zh: "熔化的" },
    { front: "ominous", pos: "adj.", def: "suggesting that something bad is about to happen", example: "Ominous black clouds gathered over the bay as we set sail.", zh: "不祥的" },
    { front: "die down", pos: "phr. v.", def: "to become gradually weaker or calmer", example: "We waited in the harbour until the wind died down.", zh: "（風勢等）減弱、平息" },
    { front: "bear down on", pos: "phr. v.", def: "to move towards someone or something in a fast and threatening way", example: "Satellite images showed the hurricane bearing down on the coast.", zh: "直逼而來、逼近" },
    { front: "set in", pos: "phr. v.", def: "to begin and seem likely to continue, especially bad weather", example: "The rain set in at noon and did not stop until the next morning.", zh: "（壞天氣）開始並持續" },
    { front: "blow over", pos: "phr. v.", def: "to pass and come to an end without serious effects", example: "The forecasters promised the storm would blow over by dawn.", zh: "（風暴、風波）平息" },
    { front: "clear up", pos: "phr. v.", def: "to become brighter and free of rain or cloud", example: "If it clears up later, we can eat outside on the terrace.", zh: "（天氣）放晴" },
    { front: "brighten up", pos: "phr. v.", def: "to become sunnier, or to make something more cheerful", example: "The morning was grey, but it brightened up by lunchtime.", zh: "轉晴、變明亮" },
    { front: "cloud over", pos: "phr. v.", def: "to become covered with clouds", example: "The sky clouded over just as the match was about to start.", zh: "轉陰、烏雲密布" },
    { front: "pour down", pos: "phr. v.", def: "to rain very heavily", example: "It poured down all weekend, so the fête was cancelled.", zh: "下傾盆大雨" },
    { front: "freeze over", pos: "phr. v.", def: "to become covered with a layer of ice", example: "The pond freezes over most winters, and children skate on it.", zh: "結冰、封凍" },
    { front: "melt away", pos: "phr. v.", def: "to disappear gradually, like snow in warm weather", example: "By March the last drifts of snow had melted away from the hills.", zh: "逐漸融化消失" },
    { front: "cool down", pos: "phr. v.", def: "to become lower in temperature", example: "The evenings cool down quickly once the sun drops behind the ridge.", zh: "變涼、降溫" },
    { front: "let up", pos: "phr. v.", def: "to become weaker or stop, especially rain or pressure", example: "The rain finally let up long enough for us to reach the car.", zh: "（雨勢等）減弱、停歇" },
    { front: "beat down", pos: "phr. v.", def: "to shine with great heat, or to fall heavily (of sun or rain)", example: "The sun beat down mercilessly on the harvesters all afternoon.", zh: "（烈日）曝曬；（雨）猛打" },
    { front: "bucket down", pos: "phr. v.", def: "to rain extremely heavily (informal)", example: "Take the big umbrella — it's bucketing down out there.", zh: "下大雨（口語）" },
    { front: "close in", pos: "phr. v.", def: "to gradually surround, especially of darkness, fog or bad weather", example: "The fog closed in, and soon we could not see the path at all.", zh: "（霧、夜色）逼近籠罩" },
    { front: "roll in", pos: "phr. v.", def: "to arrive in large amounts or masses, like clouds or waves", example: "Thick sea mist rolled in across the bay before sunset.", zh: "（雲霧）滾滾而來" },
    { front: "mist over", pos: "phr. v.", def: "to become covered with mist or a thin layer of moisture", example: "The valley mists over most autumn mornings until the sun breaks through.", zh: "被薄霧籠罩、起霧" },
    { front: "come down", pos: "phr. v.", def: "to fall from the sky, especially rain or snow", example: "The snow came down so thickly that the roads vanished within an hour.", zh: "（雨雪）落下" },
    { front: "hold off", pos: "phr. v.", def: "to not begin, especially rain; to delay", example: "Luckily the rain held off until the last guests had left the garden.", zh: "（雨）暫不下；延遲" },
    { front: "a cold snap", pos: "collocation", def: "a sudden short period of very cold weather", example: "A late cold snap in April damaged the young vines.", zh: "驟寒、寒流來襲" },
    { front: "flash floods", pos: "collocation", def: "sudden severe floods caused by very heavy rain", example: "Flash floods swept cars down the high street within minutes.", zh: "暴洪、山洪" },
    { front: "gale-force winds", pos: "collocation", def: "winds strong enough to cause damage", example: "Gale-force winds brought down power lines across the county.", zh: "強風、烈風" },
    { front: "dense fog", pos: "collocation", def: "very thick fog that makes it difficult to see", example: "Dense fog delayed dozens of flights out of the capital.", zh: "濃霧" },
    { front: "freak weather", pos: "collocation", def: "very unusual and unexpected weather", example: "Freak weather brought snow to the beaches in the middle of summer.", zh: "反常天氣" },
    { front: "the calm before the storm", pos: "idiom", def: "a quiet period just before a time of great activity or trouble", example: "The office feels peaceful now, but it's just the calm before the storm.", zh: "暴風雨前的寧靜" },
    { front: "come rain or shine", pos: "idiom", def: "whatever happens; regardless of the weather", example: "He swims in the sea every morning, come rain or shine.", zh: "風雨無阻" },
    { front: "it never rains but it pours", pos: "idiom", def: "when one bad thing happens, many others tend to follow", example: "The car broke down the same week the boiler failed — it never rains but it pours.", zh: "禍不單行" },
    { front: "save it for a rainy day", pos: "idiom", def: "to keep money or resources for a time when they will be needed", example: "Put some of the bonus aside and save it for a rainy day.", zh: "未雨綢繆、存以備用" },
    { front: "under a cloud", pos: "idiom", def: "suspected of having done something wrong; in disgrace", example: "The manager left the club under a cloud after the betting scandal.", zh: "蒙上陰影、受到懷疑" },
    { front: "a storm in a teacup", pos: "idiom", def: "a lot of fuss about something unimportant", example: "The row over the office kettle was a storm in a teacup.", zh: "小題大作、茶壺裡的風暴" },
    { front: "weather the storm", pos: "idiom", def: "to survive a difficult period without serious harm", example: "The family firm weathered the storm of the recession better than most.", zh: "度過難關" },
    { front: "take a rain check", pos: "idiom", def: "to politely refuse an offer while suggesting you may accept it later", example: "I'll have to take a rain check on dinner — I'm on deadline tonight.", zh: "改天再約、下次再說" },
    { front: "snowed under", pos: "idiom", def: "having far too much work to deal with", example: "She's completely snowed under with marking this week.", zh: "忙得不可開交" },
    { front: "every cloud has a silver lining", pos: "idiom", def: "every difficult situation has some positive aspect", example: "Losing that job led him to start his own café — every cloud has a silver lining.", zh: "塞翁失馬、否極泰來" },
    /* ---------- work / leadership / management ---------- */
    { front: "delegate", pos: "v.", def: "to give part of your work or authority to someone in a lower position", example: "A good manager learns to delegate rather than do everything herself.", zh: "授權、委派" },
    { front: "oversee", pos: "v.", def: "to watch and direct work to make sure it is done correctly", example: "She was hired to oversee the merger of the two departments.", zh: "監督、督導" },
    { front: "subordinate", pos: "n.", def: "a person who has a less important position than you in an organisation", example: "He treats his subordinates with the same respect as the directors.", zh: "下屬" },
    { front: "hierarchy", pos: "n.", def: "a system in which people are ranked according to status or authority", example: "Ideas rarely travel upwards through the company's rigid hierarchy.", zh: "階層體系" },
    { front: "absenteeism", pos: "n.", def: "the habit of frequently staying away from work without good reason", example: "Absenteeism fell sharply once flexible hours were introduced.", zh: "曠職、缺勤（現象）" },
    { front: "burnout", pos: "n.", def: "extreme exhaustion caused by working too hard for too long", example: "The clinic has seen a sharp rise in burnout among young teachers.", zh: "職業倦怠" },
    { front: "workload", pos: "n.", def: "the amount of work a person or organisation has to do", example: "Her workload doubled when two colleagues left and were not replaced.", zh: "工作量" },
    { front: "appraisal", pos: "n.", def: "a formal assessment of an employee's performance", example: "At her annual appraisal, she asked to be considered for promotion.", zh: "績效考核" },
    { front: "demote", pos: "v.", def: "to move someone to a less important position", example: "After the botched launch, the project lead was quietly demoted.", zh: "降職" },
    { front: "vocation", pos: "n.", def: "a job you do because you feel it is your purpose in life", example: "For her, nursing was never just a job but a true vocation.", zh: "天職、使命" },
    { front: "tenure", pos: "n.", def: "the period during which someone holds a position, or the right to keep it permanently", example: "During his tenure as chairman, profits tripled.", zh: "任期；終身職" },
    { front: "apprenticeship", pos: "n.", def: "a period of training in which you learn a skilled trade while working", example: "He completed a four-year apprenticeship with a master carpenter.", zh: "學徒訓練" },
    { front: "remuneration", pos: "n.", def: "payment for work or services (formal)", example: "The advert promised generous remuneration for the right candidate.", zh: "報酬、薪酬" },
    { front: "perk", pos: "n.", def: "an extra benefit you receive from your job besides your salary", example: "Free travel is one of the best perks of working for the airline.", zh: "職務福利" },
    { front: "flair", pos: "n.", def: "a natural talent or stylish skill for doing something", example: "She runs the accounts with efficiency and the events with real flair.", zh: "天賦、才華" },
    { front: "headhunt", pos: "v.", def: "to persuade someone to leave their job and work for another company", example: "She was headhunted by a rival firm offering twice her salary.", zh: "挖角" },
    { front: "shortlist", pos: "v.", def: "to put someone on a small final list of candidates for a job or prize", example: "Only four of the two hundred applicants were shortlisted for interview.", zh: "列入決選名單" },
    { front: "credentials", pos: "n.", def: "qualifications and experience that make someone suitable for a role", example: "Nobody questioned her credentials — she had run three hospitals before.", zh: "資歷、資格" },
    { front: "calibre", pos: "n.", def: "the level of quality or ability of a person or thing", example: "It is rare to find candidates of this calibre outside the capital.", zh: "水準、素質" },
    { front: "proficiency", pos: "n.", def: "a high degree of skill in doing something", example: "The role requires proficiency in at least two European languages.", zh: "精通、熟練" },
    { front: "initiative", pos: "n.", def: "the ability to act and make decisions without being told what to do", example: "We want people who show initiative rather than wait for instructions.", zh: "主動性；倡議" },
    { front: "autonomy", pos: "n.", def: "the freedom to make your own decisions without being controlled", example: "The regional offices enjoy considerable autonomy over hiring.", zh: "自主權" },
    { front: "accountability", pos: "n.", def: "the state of being responsible for decisions and answerable for results", example: "The inquiry called for clearer lines of accountability at the top.", zh: "問責、當責" },
    { front: "micromanage", pos: "v.", def: "to control every small detail of other people's work", example: "His habit of micromanaging drove three assistants to resign.", zh: "微觀管理、事事插手" },
    { front: "arbitration", pos: "n.", def: "the settling of a dispute by an official person or body chosen by both sides", example: "The pay dispute went to arbitration after talks broke down.", zh: "仲裁" },
    { front: "grievance", pos: "n.", def: "a complaint, especially about unfair treatment at work", example: "The union filed a formal grievance over the new shift patterns.", zh: "申訴、不滿" },
    { front: "understaffed", pos: "adj.", def: "not having enough employees to do the work properly", example: "The ward is so understaffed that nurses regularly skip their breaks.", zh: "人手不足的" },
    { front: "menial", pos: "adj.", def: "describing work that is boring, low-status and requires no skill", example: "He spent his first year doing menial tasks like filing and photocopying.", zh: "卑微瑣碎的（工作）" },
    { front: "monotonous", pos: "adj.", def: "boring because it never changes", example: "The monotonous assembly-line work numbed her mind by mid-morning.", zh: "單調乏味的" },
    { front: "camaraderie", pos: "n.", def: "a feeling of friendship and trust among people who work together", example: "What she misses most about the newsroom is the camaraderie of the night shift.", zh: "同袍情誼、革命情感" },
    { front: "visionary", pos: "adj.", def: "having original ideas about the future and the imagination to achieve them", example: "The company owes its rise to one visionary engineer.", zh: "有遠見的" },
    { front: "domineering", pos: "adj.", def: "trying to control others without considering their feelings or wishes", example: "His domineering style left senior staff afraid to voice objections.", zh: "專橫跋扈的" },
    { front: "decisive", pos: "adj.", def: "able to make decisions quickly and confidently", example: "In a crisis, the crew needs a captain who is calm and decisive.", zh: "果斷的" },
    { front: "workaholic", pos: "n.", def: "a person who works compulsively and finds it hard to stop", example: "A self-confessed workaholic, he answered emails on his wedding day.", zh: "工作狂" },
    { front: "indispensable", pos: "adj.", def: "so important or useful that you cannot manage without it", example: "Within a year, the quiet new analyst had made herself indispensable.", zh: "不可或缺的" },
    { front: "hands-on", pos: "adj.", def: "personally involved in doing something rather than just directing it", example: "She is a hands-on manager who still visits every site each month.", zh: "親力親為的、實作的" },
    { front: "figurehead", pos: "n.", def: "a leader with no real power who represents an organisation", example: "The president is a mere figurehead; the board makes every decision.", zh: "有名無實的領袖" },
    { front: "protégé", pos: "n.", def: "a young person who is guided and supported by an older, experienced person", example: "The retiring editor handed the magazine to her longtime protégé.", zh: "門生、受提攜者" },
    { front: "workforce", pos: "n.", def: "all the people who work for a company or in a country", example: "Nearly a third of the workforce now works from home twice a week.", zh: "勞動力、員工總數" },
    { front: "backlog", pos: "n.", def: "an accumulation of work that should already have been done", example: "The court is struggling with a backlog of thousands of cases.", zh: "積壓的工作" },
    { front: "incompetent", pos: "adj.", def: "lacking the skill or ability to do a job properly", example: "The report blamed the delays on incompetent management.", zh: "不稱職的、無能的" },
    { front: "step up", pos: "phr. v.", def: "to take responsibility or increase effort when it is needed", example: "When the manager fell ill, her deputy stepped up impressively.", zh: "挺身承擔、加強" },
    { front: "sign off on", pos: "phr. v.", def: "to give official approval to something", example: "The finance director refused to sign off on the inflated budget.", zh: "批准、核可" },
    { front: "slack off", pos: "phr. v.", def: "to work less hard than you should", example: "The team tends to slack off once the quarterly targets are met.", zh: "偷懶、鬆懈" },
    { front: "knuckle down", pos: "phr. v.", def: "to start working seriously and with effort", example: "With the deadline looming, everyone finally knuckled down.", zh: "開始認真苦幹" },
    { front: "get ahead", pos: "phr. v.", def: "to be more successful than others in your career", example: "She learned early that getting ahead meant volunteering for the hard jobs.", zh: "出人頭地、往上爬" },
    { front: "fill in for", pos: "phr. v.", def: "to do someone's job temporarily while they are away", example: "Could you fill in for Marta at the reception desk this afternoon?", zh: "代班、代理" },
    { front: "answer to", pos: "phr. v.", def: "to be responsible to someone and explain your actions to them", example: "As regional head, she answers directly to the chief executive.", zh: "對…負責、聽命於" },
    { front: "get down to", pos: "phr. v.", def: "to finally start doing something that needs attention", example: "Coffee finished, they got down to the serious business of budgeting.", zh: "著手認真做" },
    { front: "soldier on", pos: "phr. v.", def: "to continue doing something despite difficulties", example: "Half the team had flu, but the rest soldiered on to finish the audit.", zh: "咬牙撐下去" },
    { front: "muddle through", pos: "phr. v.", def: "to manage to do something despite lacking skill or organisation", example: "Nobody had run an event before, but somehow we muddled through.", zh: "勉強應付過去" },
    { front: "beaver away", pos: "phr. v.", def: "to work very hard at something for a long time", example: "She has been beavering away at the report all weekend.", zh: "埋頭苦幹" },
    { front: "clock in", pos: "phr. v.", def: "to record the time you arrive at work", example: "Factory staff clock in at seven and take their first break at ten.", zh: "打卡上班" },
    { front: "knock off", pos: "phr. v.", def: "to stop working at the end of the day (informal)", example: "On Fridays we knock off early and head to the café on the corner.", zh: "收工、下班" },
    { front: "pitch in", pos: "phr. v.", def: "to join others and help with work that needs doing", example: "Everyone pitched in to pack the orders before the courier arrived.", zh: "一起幫忙" },
    { front: "step in", pos: "phr. v.", def: "to become involved in a situation in order to help or take control", example: "Head office stepped in when the branch missed its targets for a third quarter.", zh: "介入、出面處理" },
    { front: "move up", pos: "phr. v.", def: "to advance to a higher position or level", example: "She moved up quickly, making partner before she turned thirty-five.", zh: "升遷、晉升" },
    { front: "sound out", pos: "phr. v.", def: "to try to discover someone's opinion by talking to them indirectly", example: "Before announcing the change, he sounded out the senior staff privately.", zh: "試探（意見）" },
    { front: "wind down", pos: "phr. v.", def: "to gradually reduce activity, or to relax after work", example: "The plant is winding down production ahead of its closure in June.", zh: "逐步縮減；放鬆" },
    { front: "press ahead", pos: "phr. v.", def: "to continue with a plan in a determined way despite opposition", example: "The board pressed ahead with the restructuring despite the strike threat.", zh: "堅持推進" },
    { front: "the daily grind", pos: "idiom", def: "the boring, repetitive routine of everyday work", example: "The lottery win freed her from the daily grind at last.", zh: "日常苦差、例行公事" },
    { front: "climb the career ladder", pos: "idiom", def: "to advance step by step to higher positions at work", example: "He sacrificed weekends and holidays to climb the career ladder.", zh: "在職涯階梯上攀升" },
    { front: "meet a deadline", pos: "collocation", def: "to finish a task by the required time", example: "The translators worked through the night to meet the deadline.", zh: "趕上期限" },
    { front: "work-life balance", pos: "collocation", def: "a healthy division of time between your job and your personal life", example: "The four-day week was introduced to improve staff work-life balance.", zh: "工作與生活的平衡" },
    { front: "pull your weight", pos: "idiom", def: "to do your fair share of the work", example: "Resentment grows quickly when one team member doesn't pull their weight.", zh: "盡自己的本分" },
    { front: "go the extra mile", pos: "idiom", def: "to make more effort than is expected of you", example: "She always goes the extra mile for clients, and they stay loyal.", zh: "加倍付出、多走一里路" },
    { front: "learn the ropes", pos: "idiom", def: "to learn how to do a new job or activity", example: "The first month is just about learning the ropes from the senior staff.", zh: "摸熟門路、學會訣竅" },
    { front: "call the shots", pos: "idiom", def: "to be the person who makes the important decisions", example: "Officially they are partners, but everyone knows who calls the shots.", zh: "作主、發號施令" },
    { front: "in the driving seat", pos: "idiom", def: "in control of a situation", example: "With the rival firm collapsing, we are firmly in the driving seat now.", zh: "居主導地位" },
    { front: "pass the buck", pos: "idiom", def: "to make someone else take responsibility for a problem", example: "Each department passed the buck until nobody would own the mistake.", zh: "推卸責任" },
    { front: "a tall order", pos: "idiom", def: "a task that is very difficult to achieve", example: "Doubling sales in six months is a tall order for any team.", zh: "艱鉅的任務" },
    { front: "up to your ears", pos: "idiom", def: "extremely busy or deeply involved in something", example: "I can't take the call — I'm up to my ears in invoices.", zh: "忙得焦頭爛額" },
    { front: "get the sack", pos: "idiom", def: "to be dismissed from your job", example: "He got the sack for repeatedly falsifying his timesheets.", zh: "被開除" },
    { front: "a team player", pos: "collocation", def: "someone who works well with others towards a shared goal", example: "Brilliant but impossible to manage, he was never a team player.", zh: "有團隊精神的人" },
    { front: "lead by example", pos: "idiom", def: "to show others how to behave by doing it yourself", example: "She leads by example, always the first to arrive and the last to leave.", zh: "以身作則" },
    { front: "notice period", pos: "collocation", def: "the length of time you must continue working after resigning from a job", example: "Her contract stipulates a three-month notice period for senior staff.", zh: "離職預告期" }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
