/* CAE Prep extra bank: vocab wave 1 */
(function () {
  var BANK = [
    /* === Society & Politics === */
    { front: "legislation", pos: "n.", def: "laws considered as a whole, or the process of making them", example: "New legislation on data privacy will come into force next year.", zh: "立法；法律" },
    { front: "mandate", pos: "n.", def: "the authority to carry out a policy, given by voters to a winner", example: "The government claims it has a clear mandate to raise taxes.", zh: "授權；委任" },
    { front: "constituency", pos: "n.", def: "a district whose voters elect a representative", example: "She has represented this rural constituency for over a decade.", zh: "選區" },
    { front: "referendum", pos: "n.", def: "a direct vote by all citizens on a single political question", example: "The country held a referendum on whether to join the union.", zh: "公民投票" },
    { front: "bureaucracy", pos: "n.", def: "complicated official rules and procedures that cause delay", example: "Starting a business here involves endless bureaucracy.", zh: "官僚體制" },
    { front: "disparity", pos: "n.", def: "a great and often unfair difference between groups", example: "The disparity between rich and poor regions keeps widening.", zh: "差距；不均" },
    { front: "marginalise", pos: "v.", def: "to treat a group as unimportant and push them to the edge of society", example: "Cuts to public transport tend to marginalise elderly residents.", zh: "使邊緣化" },
    { front: "advocate", pos: "v.", def: "to publicly support a particular idea or course of action", example: "Many economists advocate a shorter working week.", zh: "提倡；擁護" },
    { front: "enforce", pos: "v.", def: "to make people obey a law or rule", example: "The new speed limits are strictly enforced by cameras.", zh: "執行（法律）" },
    { front: "abolish", pos: "v.", def: "to officially end a law, system or practice", example: "Parliament voted to abolish the outdated tax.", zh: "廢除" },
    { front: "amendment", pos: "n.", def: "a formal change made to a law or document", example: "Senators proposed an amendment to soften the bill.", zh: "修正案" },
    { front: "coalition", pos: "n.", def: "a temporary alliance of political parties or groups", example: "No party won a majority, so a coalition was formed.", zh: "聯合政府；聯盟" },
    { front: "dissent", pos: "n.", def: "strong disagreement with an official or majority opinion", example: "The regime tolerates little political dissent.", zh: "異議" },
    { front: "propaganda", pos: "n.", def: "biased or misleading information used to promote a cause", example: "The posters were dismissed as crude government propaganda.", zh: "政治宣傳" },
    { front: "censorship", pos: "n.", def: "the official suppression of books, media or speech", example: "Journalists protested against the tightening censorship of the press.", zh: "審查制度" },
    { front: "sovereignty", pos: "n.", def: "the power of a country to govern itself", example: "Critics argued the treaty would erode national sovereignty.", zh: "主權" },
    { front: "austerity", pos: "n.", def: "severe cuts in government spending during hard economic times", example: "Years of austerity have left public services underfunded.", zh: "撙節；財政緊縮" },
    { front: "subsidise", pos: "v.", def: "to pay part of the cost of something to keep its price low", example: "The state continues to subsidise public transport heavily.", zh: "補貼" },
    { front: "electorate", pos: "n.", def: "all the people in a country who are entitled to vote", example: "Only half the electorate bothered to vote this time.", zh: "全體選民" },
    { front: "incumbent", pos: "n.", def: "the person who currently holds an official position", example: "The incumbent faces a strong challenge from a younger rival.", zh: "現任者" },
    { front: "oppress", pos: "v.", def: "to govern or treat people in a cruel and unfair way", example: "The regime used the secret police to oppress its critics.", zh: "壓迫" },
    { front: "turnout", pos: "n.", def: "the number of people who vote in an election or attend an event", example: "Bad weather was blamed for the low voter turnout.", zh: "投票率；出席人數" },
    { front: "grassroots", pos: "adj.", def: "involving ordinary people in a movement rather than its leaders", example: "The campaign began as a grassroots movement in small towns.", zh: "草根的；基層的" },
    { front: "partisan", pos: "adj.", def: "strongly supporting one party or side without considering others", example: "The debate quickly descended into partisan point-scoring.", zh: "黨派性的；偏袒的" },
    { front: "welfare", pos: "n.", def: "money and help provided by the government to people in need", example: "The reforms will affect families who depend on welfare.", zh: "社會福利" },
    { front: "impartial", pos: "adj.", def: "not supporting any side; fair and neutral", example: "Judges are expected to remain impartial at all times.", zh: "公正不偏的" },
    { front: "exploit", pos: "v.", def: "to treat someone unfairly in order to benefit from their work", example: "The factory was accused of exploiting migrant workers.", zh: "剝削" },
    { front: "segregation", pos: "n.", def: "the enforced separation of different groups of people", example: "The museum documents the era of racial segregation.", zh: "隔離（政策）" },
    { front: "crack down on", pos: "phr. v.", def: "to take severe action to stop illegal or unwanted behaviour", example: "Police have promised to crack down on illegal parking.", zh: "嚴厲打擊；取締" },
    { front: "step down", pos: "phr. v.", def: "to resign from an important job or position", example: "The minister was forced to step down over the scandal.", zh: "辭職；下台" },
    { front: "phase out", pos: "phr. v.", def: "to stop using something gradually over a period of time", example: "The city plans to phase out diesel buses by 2030.", zh: "逐步淘汰" },
    { front: "push through", pos: "phr. v.", def: "to get a law or plan officially accepted despite opposition", example: "The government pushed the reform through parliament in a week.", zh: "強行通過" },
    { front: "vote down", pos: "phr. v.", def: "to defeat a proposal by voting against it", example: "The council voted down the plan for a new stadium.", zh: "投票否決" },
    { front: "speak out", pos: "phr. v.", def: "to publicly state your opinion, especially in protest", example: "Few employees dared to speak out against the policy.", zh: "公開表態；直言" },
    { front: "do away with", pos: "phr. v.", def: "to get rid of something completely; to abolish", example: "Some schools want to do away with homework entirely.", zh: "廢除；取消" },
    { front: "draw up", pos: "phr. v.", def: "to prepare a plan, list or document in writing", example: "Lawyers were asked to draw up a new contract.", zh: "草擬；制定" },
    { front: "clamp down on", pos: "phr. v.", def: "to become much stricter in order to stop something", example: "Regulators are clamping down on misleading advertisements.", zh: "壓制；嚴格管制" },
    { front: "hand over", pos: "phr. v.", def: "to give power, control or possession to someone else", example: "The outgoing president will hand over power in January.", zh: "移交" },
    { front: "bring in", pos: "phr. v.", def: "to introduce a new law, rule or system", example: "The company brought in stricter safety procedures last year.", zh: "引進；制定（新規）" },
    { front: "stand up for", pos: "phr. v.", def: "to defend a person, principle or right that is being attacked", example: "You should stand up for your beliefs even under pressure.", zh: "捍衛；聲援" },
    { front: "sweeping reforms", pos: "collocation", def: "major changes that affect many parts of a system", example: "The new leader promised sweeping reforms of the health service.", zh: "大刀闊斧的改革" },
    { front: "public outcry", pos: "collocation", def: "a strong expression of anger by many people", example: "The decision to close the library caused a public outcry.", zh: "公眾強烈抗議" },
    { front: "a level playing field", pos: "idiom", def: "a situation in which everyone has an equal chance of success", example: "Small firms want a level playing field when bidding for contracts.", zh: "公平競爭的環境" },
    { front: "red tape", pos: "idiom", def: "excessive official rules and paperwork that delay action", example: "Farmers complain about the red tape involved in applying for grants.", zh: "繁文縟節" },
    { front: "toe the party line", pos: "idiom", def: "to say or do what your political party officially expects", example: "Rebel MPs refused to toe the party line on the vote.", zh: "服從黨的路線" },
    { front: "take office", pos: "collocation", def: "to officially begin an important government position", example: "She will take office as mayor next month.", zh: "就職；上任" },
    { front: "come to power", pos: "collocation", def: "to begin to rule or control a country", example: "The party came to power after a landslide election.", zh: "上台執政" },
    { front: "a landslide victory", pos: "collocation", def: "an election win by an extremely large margin", example: "Polls predict a landslide victory for the opposition.", zh: "壓倒性勝利" },
    { front: "law-abiding citizen", pos: "collocation", def: "a person who always obeys the law", example: "The new powers worry many law-abiding citizens.", zh: "守法公民" },
    { front: "the general public", pos: "collocation", def: "ordinary people in society as a whole", example: "The gardens are open to the general public at weekends.", zh: "一般大眾" },
    /* === Science & Research === */
    { front: "hypothesis", pos: "n.", def: "an idea suggested as an explanation that has not yet been proved", example: "The results appear to support our original hypothesis.", zh: "假設" },
    { front: "empirical", pos: "adj.", def: "based on observation or experiment rather than theory", example: "There is little empirical evidence for this popular belief.", zh: "以實證為依據的" },
    { front: "plausible", pos: "adj.", def: "seeming likely to be true or reasonable", example: "Her explanation sounds plausible, but we need proof.", zh: "貌似合理的" },
    { front: "methodology", pos: "n.", def: "the set of methods used in a piece of research", example: "Critics questioned the methodology of the survey.", zh: "研究方法" },
    { front: "correlation", pos: "n.", def: "a connection between two things in which one changes as the other does", example: "Researchers found a strong correlation between sleep and memory.", zh: "相關性" },
    { front: "causation", pos: "n.", def: "the relationship in which one event directly produces another", example: "Correlation alone does not prove causation.", zh: "因果關係" },
    { front: "anomaly", pos: "n.", def: "something that is unusual or different from what is expected", example: "The telescope detected a strange anomaly in the data.", zh: "異常；反常現象" },
    { front: "replicate", pos: "v.", def: "to repeat an experiment to check that its results are reliable", example: "Other labs have failed to replicate the famous study.", zh: "重複驗證；複製" },
    { front: "sceptical", pos: "adj.", def: "doubting that something is true or useful", example: "Many scientists remain sceptical about the miracle cure.", zh: "持懷疑態度的" },
    { front: "rigorous", pos: "adj.", def: "done carefully, thoroughly and with great attention to detail", example: "Every drug must pass rigorous clinical testing.", zh: "嚴謹的" },
    { front: "breakthrough", pos: "n.", def: "an important discovery that helps solve a problem", example: "The vaccine represents a major breakthrough in cancer research.", zh: "重大突破" },
    { front: "phenomenon", pos: "n.", def: "a fact or event that can be observed, especially an unusual one", example: "Scientists are still studying the phenomenon of ball lightning.", zh: "現象" },
    { front: "inconclusive", pos: "adj.", def: "not leading to a definite result or decision", example: "The trial results were inconclusive, so testing continues.", zh: "無定論的" },
    { front: "deduce", pos: "v.", def: "to reach an answer by reasoning from known facts", example: "From the fossils, we can deduce what the climate was like.", zh: "推論；演繹" },
    { front: "infer", pos: "v.", def: "to form an opinion from evidence rather than direct statement", example: "Readers can infer the author's attitude from her word choice.", zh: "推斷" },
    { front: "quantify", pos: "v.", def: "to measure or express something as an amount or number", example: "It is hard to quantify the damage caused by stress.", zh: "量化" },
    { front: "specimen", pos: "n.", def: "an example of something, especially one examined scientifically", example: "The botanist collected a rare specimen of mountain orchid.", zh: "樣本；標本" },
    { front: "simulate", pos: "v.", def: "to create conditions artificially that imitate real ones", example: "The chamber can simulate the extreme cold of deep space.", zh: "模擬" },
    { front: "validate", pos: "v.", def: "to prove that something is correct or officially acceptable", example: "Independent tests were needed to validate the findings.", zh: "驗證；證實" },
    { front: "negligible", pos: "adj.", def: "so small as to be not worth considering", example: "The side effects of the treatment are negligible.", zh: "微不足道的" },
    { front: "preliminary", pos: "adj.", def: "happening before a main event or study as preparation", example: "Preliminary results suggest the therapy is safe.", zh: "初步的" },
    { front: "unprecedented", pos: "adj.", def: "never having happened or existed before", example: "The data was shared at an unprecedented speed during the pandemic.", zh: "史無前例的" },
    { front: "consensus", pos: "n.", def: "general agreement among a group of people", example: "There is a broad scientific consensus on the causes of warming.", zh: "共識" },
    { front: "refute", pos: "v.", def: "to prove that a statement or theory is wrong", example: "New evidence appears to refute the earlier claims.", zh: "駁斥；反駁" },
    { front: "speculate", pos: "v.", def: "to guess about something without knowing all the facts", example: "Astronomers can only speculate about what lies inside the black hole.", zh: "推測" },
    { front: "scrutinise", pos: "v.", def: "to examine something very carefully", example: "Reviewers scrutinise every figure before publication.", zh: "仔細審查" },
    { front: "variable", pos: "n.", def: "a factor in an experiment that can change or be changed", example: "Temperature was the only variable we altered in the test.", zh: "變數" },
    { front: "criterion", pos: "n.", def: "a standard used for judging or deciding something", example: "Reliability is the main criterion for selecting instruments.", zh: "標準；準則" },
    { front: "carry out", pos: "phr. v.", def: "to do and complete a task, experiment or piece of research", example: "The team carried out a series of field experiments.", zh: "進行；執行" },
    { front: "account for", pos: "phr. v.", def: "to explain the reason for something or form a part of a total", example: "Genetics may account for half of the difference in results.", zh: "解釋；占（比例）" },
    { front: "rule out", pos: "phr. v.", def: "to decide that something is impossible or not suitable", example: "Doctors ruled out infection as the cause of the fever.", zh: "排除" },
    { front: "set out", pos: "phr. v.", def: "to begin a task with a particular aim", example: "The study set out to test whether music improves concentration.", zh: "著手；旨在" },
    { front: "come up with", pos: "phr. v.", def: "to think of an idea, plan or solution", example: "Engineers came up with an ingenious fix for the leak.", zh: "想出；提出" },
    { front: "narrow down", pos: "phr. v.", def: "to reduce the number of possibilities being considered", example: "We narrowed the candidates down to three theories.", zh: "縮小範圍" },
    { front: "build on", pos: "phr. v.", def: "to use earlier work or success as a base for further progress", example: "The project builds on decades of climate research.", zh: "以…為基礎發展" },
    { front: "point to", pos: "phr. v.", def: "to suggest that something is true or likely", example: "All the evidence points to a bacterial cause.", zh: "顯示；表明" },
    { front: "factor in", pos: "phr. v.", def: "to include something when making a calculation or decision", example: "The model factors in wind speed and humidity.", zh: "將…納入考量" },
    { front: "single out", pos: "phr. v.", def: "to choose one person or thing from a group for special attention", example: "The report singled out sugar as the main dietary culprit.", zh: "特別挑出" },
    { front: "home in on", pos: "phr. v.", def: "to direct attention towards one particular target", example: "The researchers homed in on a single faulty gene.", zh: "鎖定；聚焦於" },
    { front: "boil down to", pos: "phr. v.", def: "to have something as the main or basic cause", example: "The debate boils down to a question of funding.", zh: "歸結為" },
    { front: "margin of error", pos: "collocation", def: "the amount by which a measurement or estimate might be wrong", example: "The poll has a margin of error of three percent.", zh: "誤差範圍" },
    { front: "conduct an experiment", pos: "collocation", def: "to organise and perform a scientific test", example: "Students conducted an experiment on plant growth in the dark.", zh: "進行實驗" },
    { front: "a body of evidence", pos: "collocation", def: "a large collected amount of proof supporting an idea", example: "A growing body of evidence links noise pollution to stress.", zh: "大量證據" },
    { front: "trial and error", pos: "collocation", def: "a way of solving problems by trying methods until one works", example: "The recipe was perfected through years of trial and error.", zh: "反覆試驗；試誤法" },
    { front: "draw a conclusion", pos: "collocation", def: "to decide what is true after considering the evidence", example: "It is too early to draw any firm conclusions from the data.", zh: "得出結論" },
    { front: "peer review", pos: "collocation", def: "the evaluation of academic work by other experts in the field", example: "The paper passed peer review after two revisions.", zh: "同儕審查" },
    { front: "uncharted territory", pos: "idiom", def: "a situation or subject that is completely new and unfamiliar", example: "Editing human genes takes medicine into uncharted territory.", zh: "未知領域" },
    { front: "the tip of the iceberg", pos: "idiom", def: "a small visible part of a much larger hidden problem", example: "The reported cases may be just the tip of the iceberg.", zh: "冰山一角" },
    { front: "shed light on", pos: "idiom", def: "to help people understand something by providing new information", example: "The diary sheds light on daily life in the ancient city.", zh: "闡明；使…明朗" },
    { front: "state-of-the-art", pos: "collocation", def: "using the most modern and advanced methods or technology", example: "The lab is equipped with state-of-the-art scanners.", zh: "最先進的" },
    /* === Business & Economy === */
    { front: "recession", pos: "n.", def: "a period when a country's economy shrinks and trade declines", example: "Thousands of shops closed during the recession.", zh: "經濟衰退" },
    { front: "inflation", pos: "n.", def: "a general rise in prices over time", example: "Wages have failed to keep pace with inflation.", zh: "通貨膨脹" },
    { front: "revenue", pos: "n.", def: "the income a company or government receives", example: "Advertising provides most of the site's revenue.", zh: "營收；歲入" },
    { front: "turnover", pos: "n.", def: "the total business a company does, or the rate at which staff leave", example: "The firm doubled its annual turnover in three years.", zh: "營業額；人員流動率" },
    { front: "monopoly", pos: "n.", def: "complete control of a market by one company", example: "The regulator broke up the railway monopoly.", zh: "壟斷" },
    { front: "merger", pos: "n.", def: "the joining of two companies into one", example: "The merger created the largest bank in the region.", zh: "（公司）合併" },
    { front: "entrepreneur", pos: "n.", def: "a person who starts a business and takes financial risks", example: "The young entrepreneur launched three start-ups before thirty.", zh: "企業家；創業者" },
    { front: "incentive", pos: "n.", def: "something that encourages a person to do something", example: "Tax breaks give firms an incentive to hire apprentices.", zh: "誘因；獎勵" },
    { front: "lucrative", pos: "adj.", def: "producing a great deal of money", example: "She turned down a lucrative offer from a rival firm.", zh: "利潤豐厚的" },
    { front: "viable", pos: "adj.", def: "able to work successfully or make a profit", example: "Without more customers, the cafe is simply not viable.", zh: "可行的；能存活的" },
    { front: "redundancy", pos: "n.", def: "the loss of a job because it is no longer needed", example: "The factory announced two hundred redundancies.", zh: "裁員；資遣" },
    { front: "outsource", pos: "v.", def: "to arrange for work to be done by an outside company", example: "Many firms outsource customer service to cut costs.", zh: "外包" },
    { front: "downturn", pos: "n.", def: "a decline in economic or business activity", example: "The tourism sector was hit hard by the downturn.", zh: "（經濟）低迷" },
    { front: "surplus", pos: "n.", def: "an amount that is more than what is needed or spent", example: "The budget produced a small surplus this year.", zh: "盈餘；過剩" },
    { front: "deficit", pos: "n.", def: "the amount by which spending is greater than income", example: "The government is struggling to reduce the trade deficit.", zh: "赤字；逆差" },
    { front: "volatile", pos: "adj.", def: "likely to change suddenly and unpredictably", example: "Oil prices have been extremely volatile this quarter.", zh: "波動劇烈的" },
    { front: "stakeholder", pos: "n.", def: "a person or group with an interest in a business or project", example: "All stakeholders were consulted before the redesign.", zh: "利害關係人" },
    { front: "dividend", pos: "n.", def: "a share of profits paid to a company's shareholders", example: "The board decided to raise the annual dividend.", zh: "股息；紅利" },
    { front: "asset", pos: "n.", def: "something valuable owned by a person or company", example: "The brand name is the company's most valuable asset.", zh: "資產" },
    { front: "liability", pos: "n.", def: "a debt, or a person or thing that causes problems", example: "The ageing factory has become a financial liability.", zh: "負債；累贅" },
    { front: "bankruptcy", pos: "n.", def: "the legal state of being unable to pay your debts", example: "The airline filed for bankruptcy last spring.", zh: "破產" },
    { front: "subsidiary", pos: "n.", def: "a company that is owned by a larger company", example: "The group runs a software subsidiary in Dublin.", zh: "子公司" },
    { front: "commodity", pos: "n.", def: "a raw material or product that can be bought and sold", example: "Coffee is the country's most important export commodity.", zh: "大宗商品" },
    { front: "tariff", pos: "n.", def: "a tax on goods coming into or leaving a country", example: "New tariffs on steel angered trading partners.", zh: "關稅" },
    { front: "fluctuate", pos: "v.", def: "to change level or amount frequently", example: "Demand fluctuates sharply with the seasons.", zh: "波動" },
    { front: "streamline", pos: "v.", def: "to make a system simpler and more efficient", example: "The airline streamlined its check-in process.", zh: "簡化；使更有效率" },
    { front: "diversify", pos: "v.", def: "to develop a wider range of products or activities", example: "Farmers were urged to diversify into tourism.", zh: "多角化經營" },
    { front: "expenditure", pos: "n.", def: "the total amount of money spent", example: "Household expenditure on energy rose sharply.", zh: "支出；開銷" },
    { front: "take over", pos: "phr. v.", def: "to gain control of a company or position", example: "A foreign investor is planning to take over the brewery.", zh: "接管；收購" },
    { front: "lay off", pos: "phr. v.", def: "to dismiss workers because there is not enough work", example: "The plant laid off a third of its workforce.", zh: "裁員" },
    { front: "branch out", pos: "phr. v.", def: "to start doing something new in addition to your usual work", example: "The bakery branched out into wedding cakes.", zh: "拓展業務" },
    { front: "sell off", pos: "phr. v.", def: "to sell assets quickly, often cheaply, to raise money", example: "The council sold off several public buildings.", zh: "出售；變賣" },
    { front: "scale back", pos: "phr. v.", def: "to reduce the size or extent of something", example: "The firm scaled back its expansion plans.", zh: "縮減" },
    { front: "pay off", pos: "phr. v.", def: "to finish paying a debt, or to bring a good result", example: "All those late nights finally paid off.", zh: "還清；獲得回報" },
    { front: "cash in on", pos: "phr. v.", def: "to make money from a situation, often unfairly", example: "Street vendors cashed in on the festival crowds.", zh: "趁機牟利" },
    { front: "drum up", pos: "phr. v.", def: "to try hard to get support, business or interest", example: "The band toured tirelessly to drum up publicity.", zh: "招攬；爭取" },
    { front: "fork out", pos: "phr. v.", def: "to pay money for something unwillingly", example: "We had to fork out a fortune for the repairs.", zh: "被迫花錢" },
    { front: "go under", pos: "phr. v.", def: "to fail financially; to go out of business", example: "Dozens of small shops went under during the crisis.", zh: "倒閉" },
    { front: "take on", pos: "phr. v.", def: "to employ someone or accept a new responsibility", example: "The warehouse takes on extra staff before Christmas.", zh: "聘用；承擔" },
    { front: "tide over", pos: "phr. v.", def: "to help someone through a difficult period, especially with money", example: "The loan should tide us over until payday.", zh: "使度過難關" },
    { front: "cut corners", pos: "idiom", def: "to do something cheaply or quickly at the expense of quality", example: "The builder cut corners, and the roof leaked within a year.", zh: "偷工減料" },
    { front: "in the red", pos: "idiom", def: "owing money; operating at a loss", example: "The club has been in the red for two seasons.", zh: "虧損；負債" },
    { front: "break even", pos: "collocation", def: "to earn just enough money to cover your costs", example: "The restaurant expects to break even within a year.", zh: "損益兩平" },
    { front: "a ballpark figure", pos: "collocation", def: "a rough estimate of an amount", example: "Can you give me a ballpark figure for the renovation?", zh: "粗略估計的數字" },
    { front: "drive a hard bargain", pos: "idiom", def: "to negotiate firmly to get the best possible deal", example: "She drives a hard bargain, so prepare your numbers.", zh: "極力討價還價" },
    { front: "make ends meet", pos: "idiom", def: "to have just enough money to pay for necessities", example: "Many families take second jobs just to make ends meet.", zh: "勉強維持生計" },
    { front: "corner the market", pos: "idiom", def: "to control the supply of a product so as to dominate sales", example: "The firm has cornered the market in budget flights.", zh: "壟斷市場" },
    { front: "market share", pos: "collocation", def: "the proportion of total sales that a company has", example: "The brand lost market share to cheaper rivals.", zh: "市場占有率" },
    { front: "supply and demand", pos: "collocation", def: "the balance between how much is available and how much people want", example: "Housing prices are driven by simple supply and demand.", zh: "供給與需求" },
    { front: "a niche market", pos: "collocation", def: "a small specialised section of the market", example: "Handmade vegan shoes serve a profitable niche market.", zh: "利基市場" },
    /* === Emotions & Behaviour === */
    { front: "resentment", pos: "n.", def: "a feeling of anger about being treated unfairly", example: "His constant criticism bred deep resentment among the staff.", zh: "怨恨；不滿" },
    { front: "apprehensive", pos: "adj.", def: "worried or nervous about something that may happen", example: "She felt apprehensive about her first day at the new job.", zh: "憂慮不安的" },
    { front: "complacent", pos: "adj.", def: "too satisfied with yourself and unaware of possible dangers", example: "One good result is no reason to become complacent.", zh: "自滿的" },
    { front: "empathy", pos: "n.", def: "the ability to understand and share another person's feelings", example: "Good nurses combine skill with genuine empathy.", zh: "同理心" },
    { front: "indifferent", pos: "adj.", def: "having no interest in or concern about something", example: "He seemed completely indifferent to the outcome of the vote.", zh: "漠不關心的" },
    { front: "impulsive", pos: "adj.", def: "acting suddenly without thinking about the consequences", example: "Her impulsive purchase left her short of rent money.", zh: "衝動的" },
    { front: "meticulous", pos: "adj.", def: "extremely careful and paying great attention to detail", example: "He kept meticulous records of every conversation.", zh: "一絲不苟的" },
    { front: "obstinate", pos: "adj.", def: "refusing to change your opinion or behaviour despite persuasion", example: "The obstinate old farmer refused to sell his land.", zh: "固執的" },
    { front: "resilient", pos: "adj.", def: "able to recover quickly from difficulties or setbacks", example: "Children are often more resilient than adults expect.", zh: "有韌性的；適應力強的" },
    { front: "spontaneous", pos: "adj.", def: "done naturally and suddenly, without planning", example: "The crowd broke into spontaneous applause.", zh: "自發的；即興的" },
    { front: "wary", pos: "adj.", def: "careful and cautious because of possible danger", example: "Investors are wary of putting money into untested apps.", zh: "警惕的；謹慎的" },
    { front: "exasperated", pos: "adj.", def: "extremely annoyed, especially by something you cannot change", example: "The exasperated teacher repeated the instructions for the fifth time.", zh: "惱怒的" },
    { front: "gullible", pos: "adj.", def: "too willing to believe what other people say; easily deceived", example: "Scammers target gullible shoppers with fake discounts.", zh: "容易受騙的" },
    { front: "aloof", pos: "adj.", def: "distant and not friendly with other people", example: "Colleagues found him aloof, though he was merely shy.", zh: "冷淡的；疏遠的" },
    { front: "remorse", pos: "n.", def: "a strong feeling of guilt about something wrong you have done", example: "The thief showed no remorse in court.", zh: "悔恨；自責" },
    { front: "contempt", pos: "n.", def: "a strong feeling that someone or something deserves no respect", example: "She stared at the cheat with open contempt.", zh: "輕蔑" },
    { front: "envious", pos: "adj.", def: "wishing you had what another person has", example: "He was secretly envious of his brother's success.", zh: "羨慕的；嫉妒的" },
    { front: "humiliate", pos: "v.", def: "to make someone feel ashamed or lose respect in public", example: "The coach humiliated the player in front of the whole team.", zh: "羞辱" },
    { front: "intimidate", pos: "v.", def: "to frighten someone in order to make them do what you want", example: "Witnesses said they had been intimidated into silence.", zh: "恐嚇；威嚇" },
    { front: "provoke", pos: "v.", def: "to deliberately make someone angry, or cause a reaction", example: "The article provoked a storm of angry letters.", zh: "激怒；引發" },
    { front: "restrain", pos: "v.", def: "to stop someone or yourself from doing something", example: "She could barely restrain her laughter during the speech.", zh: "克制；制止" },
    { front: "console", pos: "v.", def: "to comfort someone who is sad or disappointed", example: "Friends tried to console her after the defeat.", zh: "安慰" },
    { front: "cherish", pos: "v.", def: "to love and protect someone or something precious", example: "I cherish the memories of those summer evenings.", zh: "珍愛；珍惜" },
    { front: "despise", pos: "v.", def: "to dislike someone or something intensely and without respect", example: "He despises any form of dishonesty.", zh: "鄙視" },
    { front: "grudge", pos: "n.", def: "a lasting feeling of anger towards someone who has wronged you", example: "She has held a grudge against him since school.", zh: "怨恨；嫌隙" },
    { front: "temperament", pos: "n.", def: "a person's basic nature that affects their behaviour", example: "The two sisters have completely different temperaments.", zh: "性情；氣質" },
    { front: "conscientious", pos: "adj.", def: "careful to do your work properly and thoroughly", example: "She is a conscientious student who never misses a deadline.", zh: "認真盡責的" },
    { front: "assertive", pos: "adj.", def: "expressing opinions confidently and standing up for yourself", example: "The course teaches shy employees to be more assertive.", zh: "堅定自信的" },
    { front: "bottle up", pos: "phr. v.", def: "to hide strong feelings instead of expressing them", example: "Bottling up your anger only makes things worse.", zh: "壓抑（情緒）" },
    { front: "lash out", pos: "phr. v.", def: "to suddenly attack someone physically or with angry words", example: "Under pressure, he lashed out at the reporters.", zh: "猛烈抨擊；發作" },
    { front: "open up", pos: "phr. v.", def: "to start talking honestly about your feelings", example: "It took months before she opened up about her childhood.", zh: "敞開心扉" },
    { front: "put up with", pos: "phr. v.", def: "to tolerate something unpleasant without complaining", example: "I refuse to put up with his rudeness any longer.", zh: "忍受" },
    { front: "look down on", pos: "phr. v.", def: "to consider someone or something inferior", example: "She felt her in-laws looked down on her job.", zh: "看不起" },
    { front: "get carried away", pos: "phr. v.", def: "to become so excited that you lose control of your behaviour", example: "He got carried away at the auction and overspent badly.", zh: "得意忘形；失控" },
    { front: "fall out", pos: "phr. v.", def: "to stop being friends after an argument", example: "The two partners fell out over money.", zh: "鬧翻；失和" },
    { front: "make up", pos: "phr. v.", def: "to become friends again after a disagreement", example: "They argued at dinner but made up by morning.", zh: "和好" },
    { front: "wind up", pos: "phr. v.", def: "to deliberately annoy or tease someone", example: "Ignore him; he is only trying to wind you up.", zh: "故意激怒；捉弄" },
    { front: "freak out", pos: "phr. v.", def: "to become extremely frightened, angry or upset", example: "She freaked out when she saw the spider on her desk.", zh: "嚇壞；抓狂" },
    { front: "own up", pos: "phr. v.", def: "to admit that you have done something wrong", example: "Nobody owned up to breaking the window.", zh: "坦白承認" },
    { front: "warm to", pos: "phr. v.", def: "to begin to like someone or something", example: "The audience quickly warmed to the nervous young comedian.", zh: "開始喜歡" },
    { front: "lose your temper", pos: "collocation", def: "to suddenly become very angry", example: "He lost his temper and slammed the door.", zh: "發脾氣" },
    { front: "burst into tears", pos: "collocation", def: "to suddenly start crying", example: "She burst into tears when she heard the news.", zh: "突然大哭" },
    { front: "over the moon", pos: "idiom", def: "extremely happy and pleased", example: "They were over the moon about the new baby.", zh: "欣喜若狂" },
    { front: "down in the dumps", pos: "idiom", def: "feeling sad and without hope", example: "He has been down in the dumps since the team lost.", zh: "情緒低落" },
    { front: "keep a straight face", pos: "idiom", def: "to stop yourself from laughing or smiling", example: "I could hardly keep a straight face during his excuse.", zh: "忍住不笑" },
    { front: "get cold feet", pos: "idiom", def: "to suddenly become too nervous to do something planned", example: "The groom got cold feet the night before the wedding.", zh: "臨陣退縮" },
    { front: "blow things out of proportion", pos: "idiom", def: "to treat a small problem as if it were very serious", example: "It was a tiny mistake; stop blowing things out of proportion.", zh: "小題大作" },
    { front: "a shoulder to cry on", pos: "idiom", def: "someone who listens sympathetically to your problems", example: "Whenever life gets hard, my sister is a shoulder to cry on.", zh: "可傾訴的對象" },
    { front: "take it out on", pos: "idiom", def: "to treat someone badly because you are upset about something else", example: "Do not take your work stress out on the children.", zh: "拿…出氣" },
    { front: "let off steam", pos: "idiom", def: "to release strong feelings or energy through activity", example: "A long run helps me let off steam after a stressful day.", zh: "發洩情緒" },
    /* === Environment === */
    { front: "sustainable", pos: "adj.", def: "able to continue without harming the environment or running out", example: "The village switched to sustainable farming methods.", zh: "永續的" },
    { front: "deforestation", pos: "n.", def: "the cutting down of forests over a large area", example: "Deforestation has destroyed much of the island's wildlife.", zh: "森林砍伐" },
    { front: "biodiversity", pos: "n.", def: "the variety of plant and animal life in an area", example: "Wetlands support an astonishing level of biodiversity.", zh: "生物多樣性" },
    { front: "emission", pos: "n.", def: "gas or other substance sent out into the air", example: "The law sets strict limits on carbon emissions.", zh: "排放（物）" },
    { front: "contamination", pos: "n.", def: "the process of making something dirty or poisonous", example: "Tests revealed contamination of the local water supply.", zh: "污染" },
    { front: "habitat", pos: "n.", def: "the natural environment where an animal or plant lives", example: "Urban sprawl is destroying the birds' natural habitat.", zh: "棲息地" },
    { front: "depletion", pos: "n.", def: "the reduction of something valuable so that little remains", example: "Overfishing has caused the rapid depletion of cod stocks.", zh: "耗竭；枯竭" },
    { front: "renewable", pos: "adj.", def: "coming from a source that is naturally replaced, like wind or sun", example: "The island now runs entirely on renewable power.", zh: "可再生的" },
    { front: "irreversible", pos: "adj.", def: "impossible to change back to a previous state", example: "Scientists warn the damage to the reef may be irreversible.", zh: "不可逆轉的" },
    { front: "extinction", pos: "n.", def: "the complete disappearance of a species", example: "The rhino has been hunted to the edge of extinction.", zh: "滅絕" },
    { front: "pollutant", pos: "n.", def: "a substance that makes air, water or soil dirty", example: "Factories released dangerous pollutants into the river.", zh: "污染物" },
    { front: "conservation", pos: "n.", def: "the protection of nature and wildlife", example: "She works for a marine conservation charity.", zh: "（自然）保育" },
    { front: "degradation", pos: "n.", def: "the process of something becoming worse in quality", example: "Soil degradation threatens harvests across the region.", zh: "退化；惡化" },
    { front: "drought", pos: "n.", def: "a long period with little or no rain", example: "The worst drought in decades ruined the maize crop.", zh: "乾旱" },
    { front: "famine", pos: "n.", def: "an extreme lack of food affecting a large area", example: "The failed harvests brought the region close to famine.", zh: "饑荒" },
    { front: "scarcity", pos: "n.", def: "a situation in which there is not enough of something", example: "Water scarcity is forcing farmers to change crops.", zh: "短缺；匱乏" },
    { front: "erosion", pos: "n.", def: "the gradual wearing away of land by wind or water", example: "Coastal erosion has swallowed several cliff-top houses.", zh: "侵蝕" },
    { front: "ecosystem", pos: "n.", def: "all the living things in an area and how they interact", example: "A single invasive species can upset an entire ecosystem.", zh: "生態系統" },
    { front: "endangered", pos: "adj.", def: "at risk of dying out completely", example: "The reserve protects several endangered big cats.", zh: "瀕危的" },
    { front: "pesticide", pos: "n.", def: "a chemical used to kill insects that damage crops", example: "Residues of pesticide were found in the honey.", zh: "殺蟲劑；農藥" },
    { front: "landfill", pos: "n.", def: "a place where waste is buried in the ground", example: "Most of the city's rubbish still ends up in landfill.", zh: "垃圾掩埋場" },
    { front: "sewage", pos: "n.", def: "waste water and material carried away from buildings in pipes", example: "Untreated sewage was pumped straight into the bay.", zh: "污水" },
    { front: "replenish", pos: "v.", def: "to fill something up again or restore a supply", example: "Heavy winter rains replenished the reservoirs.", zh: "補充；重新裝滿" },
    { front: "dwindle", pos: "v.", def: "to become gradually smaller or fewer", example: "Fish stocks have dwindled to a fraction of former levels.", zh: "逐漸減少" },
    { front: "arid", pos: "adj.", def: "very dry with little rain, so few plants grow", example: "Little survives in the arid interior of the country.", zh: "乾旱的；貧瘠的" },
    { front: "lush", pos: "adj.", def: "growing thickly and healthily; rich in vegetation", example: "The valley is famous for its lush green meadows.", zh: "蒼翠繁茂的" },
    { front: "pristine", pos: "adj.", def: "completely clean and unspoiled, in original condition", example: "Tourists flock to the island's pristine beaches.", zh: "原始純淨的" },
    { front: "offset", pos: "v.", def: "to balance one effect with an opposite one", example: "The airline plants trees to offset its carbon emissions.", zh: "抵銷" },
    { front: "die out", pos: "phr. v.", def: "to disappear completely as a species or custom", example: "Many local dialects are slowly dying out.", zh: "滅絕；消失" },
    { front: "run out", pos: "phr. v.", def: "to use all of something and have none left", example: "At this rate, the town will run out of clean water.", zh: "用完；耗盡" },
    { front: "use up", pos: "phr. v.", def: "to finish a supply of something completely", example: "We are using up resources faster than the planet can replace them.", zh: "用光" },
    { front: "cut down on", pos: "phr. v.", def: "to reduce the amount of something you use or do", example: "The family cut down on plastic packaging.", zh: "減少" },
    { front: "dispose of", pos: "phr. v.", def: "to get rid of something, especially waste", example: "Chemicals must be disposed of at a licensed site.", zh: "處理；丟棄" },
    { front: "wipe out", pos: "phr. v.", def: "to destroy something completely", example: "The disease wiped out entire colonies of frogs.", zh: "徹底消滅" },
    { front: "spring up", pos: "phr. v.", def: "to appear suddenly and in large numbers", example: "Wind farms have sprung up all along the coast.", zh: "湧現" },
    { front: "dry up", pos: "phr. v.", def: "to lose all water, or come to an end", example: "The river dries up completely in late summer.", zh: "乾涸；枯竭" },
    { front: "give off", pos: "phr. v.", def: "to produce heat, light, gas or a smell", example: "Rotting waste gives off methane, a powerful greenhouse gas.", zh: "散發；釋放" },
    { front: "soak up", pos: "phr. v.", def: "to absorb liquid, energy or attention", example: "Mangrove forests soak up huge amounts of carbon.", zh: "吸收" },
    { front: "clean up", pos: "phr. v.", def: "to remove dirt or pollution from a place", example: "Volunteers spent the weekend cleaning up the riverbank.", zh: "清理" },
    { front: "level off", pos: "phr. v.", def: "to stop rising or falling and remain steady", example: "Global emissions may finally be levelling off.", zh: "趨於平穩" },
    { front: "carbon footprint", pos: "collocation", def: "the amount of carbon dioxide a person or activity produces", example: "Cycling to work halved my carbon footprint.", zh: "碳足跡" },
    { front: "fossil fuels", pos: "collocation", def: "fuels such as coal, oil and gas formed from ancient organisms", example: "The treaty aims to end dependence on fossil fuels.", zh: "化石燃料" },
    { front: "environmentally friendly", pos: "collocation", def: "not harmful to the environment", example: "The hotel switched to environmentally friendly cleaning products.", zh: "環保的" },
    { front: "a drop in the ocean", pos: "idiom", def: "an amount too small to make any real difference", example: "The donation is welcome, but it is a drop in the ocean.", zh: "杯水車薪" },
    { front: "harness solar power", pos: "collocation", def: "to capture and use the energy of the sun", example: "New panels let remote farms harness solar power cheaply.", zh: "利用太陽能" },
    { front: "take its toll", pos: "idiom", def: "to cause gradual serious harm or damage", example: "Decades of pollution have taken their toll on the lake.", zh: "造成損害" },
    { front: "raise awareness", pos: "collocation", def: "to make more people know about a problem", example: "The film raised awareness of plastic waste in the oceans.", zh: "提高意識" },
    { front: "on the brink of collapse", pos: "collocation", def: "very close to complete failure or breakdown", example: "Overfishing has left the ecosystem on the brink of collapse.", zh: "瀕臨崩潰" },
    { front: "go green", pos: "idiom", def: "to change your habits to protect the environment", example: "The company went green by banning single-use cups.", zh: "轉向環保生活" },
    { front: "single-use plastic", pos: "collocation", def: "plastic items designed to be used once and thrown away", example: "The city banned single-use plastic in food stalls.", zh: "一次性塑膠" },
    /* === Communication & Argument === */
    { front: "assert", pos: "v.", def: "to state something firmly as true", example: "The lawyer asserted that her client had never left the house.", zh: "斷言；主張" },
    { front: "contradict", pos: "v.", def: "to say the opposite of what someone else has said", example: "The witness statements contradict each other.", zh: "反駁；與…矛盾" },
    { front: "undermine", pos: "v.", def: "to gradually weaken someone's authority or an argument", example: "The leaked emails undermined the minister's credibility.", zh: "削弱；暗中破壞" },
    { front: "concede", pos: "v.", def: "to admit that something is true although you dislike admitting it", example: "He conceded that his rival had made a fair point.", zh: "承認；讓步" },
    { front: "articulate", pos: "adj.", def: "able to express thoughts and ideas clearly and effectively", example: "She is remarkably articulate for a twelve-year-old.", zh: "口才好的；表達清晰的" },
    { front: "coherent", pos: "adj.", def: "logical and well organised; easy to follow", example: "The essay lacks a coherent argument.", zh: "連貫的；有條理的" },
    { front: "ambiguous", pos: "adj.", def: "having more than one possible meaning; unclear", example: "The contract wording is dangerously ambiguous.", zh: "模稜兩可的" },
    { front: "persuasive", pos: "adj.", def: "good at making people believe or do something", example: "She made a persuasive case for delaying the launch.", zh: "有說服力的" },
    { front: "rebuttal", pos: "n.", def: "a statement arguing that a claim or criticism is false", example: "The professor published a point-by-point rebuttal of the article.", zh: "反駁" },
    { front: "allege", pos: "v.", def: "to claim that someone has done something wrong without proof", example: "The report alleges that funds were secretly diverted.", zh: "指控；聲稱" },
    { front: "imply", pos: "v.", def: "to suggest something without saying it directly", example: "Her tone implied that she doubted the whole story.", zh: "暗示" },
    { front: "insinuate", pos: "v.", def: "to suggest something unpleasant indirectly", example: "Are you insinuating that I took the money?", zh: "含沙射影地指出" },
    { front: "exaggerate", pos: "v.", def: "to describe something as larger or more important than it is", example: "He tends to exaggerate the dangers of city life.", zh: "誇大" },
    { front: "downplay", pos: "v.", def: "to make something seem less important than it really is", example: "Officials tried to downplay the extent of the leak.", zh: "淡化；輕描淡寫" },
    { front: "candid", pos: "adj.", def: "honest and direct, even when the truth is uncomfortable", example: "She gave a candid account of her failures as a manager.", zh: "坦率的" },
    { front: "blunt", pos: "adj.", def: "saying exactly what you think without trying to be polite", example: "His blunt reply offended half the room.", zh: "直言不諱的" },
    { front: "tactful", pos: "adj.", def: "careful not to say things that upset or embarrass people", example: "A tactful reminder worked better than an angry email.", zh: "得體的；圓融的" },
    { front: "eloquent", pos: "adj.", def: "using language fluently and expressively in a moving way", example: "Her eloquent speech brought the audience to tears.", zh: "雄辯的；動人的" },
    { front: "verbose", pos: "adj.", def: "using more words than necessary", example: "The report is so verbose that the key point is buried.", zh: "冗長囉嗦的" },
    { front: "concise", pos: "adj.", def: "expressing much in few words; brief and clear", example: "Keep your summary concise and to the point.", zh: "簡明扼要的" },
    { front: "digress", pos: "v.", def: "to move away from the main subject when speaking or writing", example: "The lecturer digressed into stories about his student days.", zh: "離題" },
    { front: "elaborate", pos: "v.", def: "to explain something in more detail", example: "Could you elaborate on how the scheme would be funded?", zh: "詳細說明" },
    { front: "reiterate", pos: "v.", def: "to repeat something in order to emphasise it", example: "The captain reiterated the importance of teamwork.", zh: "重申" },
    { front: "retract", pos: "v.", def: "to formally withdraw a statement or accusation", example: "The newspaper was forced to retract its false claims.", zh: "撤回（言論）" },
    { front: "convey", pos: "v.", def: "to communicate an idea, feeling or message", example: "The painting conveys a deep sense of loneliness.", zh: "傳達" },
    { front: "dispute", pos: "v.", def: "to argue that something is not true or correct", example: "Nobody disputes the figures, only what they mean.", zh: "對…提出異議" },
    { front: "notion", pos: "n.", def: "an idea, belief or opinion about something", example: "He rejected the notion that talent matters more than practice.", zh: "觀念；想法" },
    { front: "stance", pos: "n.", def: "a publicly stated opinion or attitude on an issue", example: "The party softened its stance on immigration.", zh: "立場" },
    { front: "put forward", pos: "phr. v.", def: "to suggest an idea, plan or proposal for discussion", example: "She put forward a bold plan to redesign the square.", zh: "提出" },
    { front: "bear out", pos: "phr. v.", def: "to confirm that something is true", example: "The statistics bear out what teachers have long suspected.", zh: "證實" },
    { front: "talk over", pos: "phr. v.", def: "to discuss a problem or plan thoroughly with someone", example: "Let us talk it over before making a final decision.", zh: "商量；詳談" },
    { front: "spell out", pos: "phr. v.", def: "to explain something clearly and in detail", example: "The contract spells out exactly who pays for repairs.", zh: "講清楚；詳述" },
    { front: "gloss over", pos: "phr. v.", def: "to avoid discussing something embarrassing by treating it briefly", example: "The report glosses over the project's early failures.", zh: "掩飾；含糊帶過" },
    { front: "sum up", pos: "phr. v.", def: "to state the main points of something briefly", example: "To sum up, the benefits clearly justify the cost.", zh: "總結" },
    { front: "touch on", pos: "phr. v.", def: "to mention a subject briefly", example: "The lecture only touched on the ethical questions.", zh: "略微提及" },
    { front: "hit back", pos: "phr. v.", def: "to reply angrily to criticism or an attack", example: "The actor hit back at the tabloid rumours online.", zh: "回擊；反駁" },
    { front: "butt in", pos: "phr. v.", def: "to interrupt a conversation rudely", example: "Sorry to butt in, but there is an urgent call for you.", zh: "插嘴；打斷" },
    { front: "get across", pos: "phr. v.", def: "to make people understand an idea successfully", example: "Diagrams helped her get the concept across to beginners.", zh: "使…被理解" },
    { front: "brush aside", pos: "phr. v.", def: "to refuse to consider something seriously; to dismiss", example: "The CEO brushed aside concerns about safety.", zh: "漠視；不予理會" },
    { front: "read into", pos: "phr. v.", def: "to find extra meaning in something that may not be intended", example: "Do not read too much into one short email.", zh: "過度解讀" },
    { front: "a heated debate", pos: "collocation", def: "an angry, passionate discussion", example: "The proposal sparked a heated debate in the town hall.", zh: "激烈辯論" },
    { front: "get to the point", pos: "idiom", def: "to start talking about the most important thing directly", example: "We only have five minutes, so please get to the point.", zh: "直接切入重點" },
    { front: "beat around the bush", pos: "idiom", def: "to avoid saying something directly", example: "Stop beating around the bush and tell me what went wrong.", zh: "拐彎抹角" },
    { front: "play devil's advocate", pos: "idiom", def: "to argue the opposite view just to test an idea", example: "Let me play devil's advocate: what if sales actually fall?", zh: "故意唱反調（以檢驗論點）" },
    { front: "find common ground", pos: "collocation", def: "to discover opinions or interests that people share", example: "Mediators helped the two sides find common ground.", zh: "找到共識" },
    { front: "miss the point", pos: "collocation", def: "to fail to understand the main idea of something", example: "Arguing about the price misses the point entirely.", zh: "沒抓到重點" },
    { front: "at cross purposes", pos: "idiom", def: "confused because people think they are talking about the same thing but are not", example: "We argued for an hour before realising we were at cross purposes.", zh: "雞同鴨講；相互誤解" },
    { front: "food for thought", pos: "idiom", def: "something that makes you think carefully", example: "Her talk on failure gave the graduates real food for thought.", zh: "值得深思的事" },
    { front: "put words in someone's mouth", pos: "idiom", def: "to claim wrongly that someone said a particular thing", example: "I never said that; stop putting words in my mouth.", zh: "硬說某人說過某話" },
    { front: "bite your tongue", pos: "idiom", def: "to stop yourself from saying what you really think", example: "I had to bite my tongue when he blamed the interns.", zh: "忍住不說" },
    /* === Culture & Arts === */
    { front: "aesthetic", pos: "adj.", def: "relating to beauty and the appreciation of beautiful things", example: "The bridge was designed with aesthetic as well as practical concerns in mind.", zh: "美學的；審美的" },
    { front: "masterpiece", pos: "n.", def: "a work of art done with extraordinary skill", example: "Many critics consider this novel her masterpiece.", zh: "傑作" },
    { front: "acclaim", pos: "n.", def: "public praise and approval", example: "The debut album won international acclaim.", zh: "讚譽" },
    { front: "avant-garde", pos: "adj.", def: "extremely modern and experimental in style", example: "The gallery specialises in avant-garde installations.", zh: "前衛的" },
    { front: "contemporary", pos: "adj.", def: "belonging to the present time; modern", example: "The museum mixes classical works with contemporary art.", zh: "當代的" },
    { front: "evocative", pos: "adj.", def: "bringing strong images, memories or feelings to mind", example: "The film's evocative soundtrack recalls the 1960s.", zh: "喚起情感的" },
    { front: "heritage", pos: "n.", def: "the traditions and buildings passed down from the past", example: "The old town is part of the nation's cultural heritage.", zh: "文化遺產" },
    { front: "iconic", pos: "adj.", def: "very famous and representing a particular idea or time", example: "The red phone box remains an iconic symbol of Britain.", zh: "具代表性的" },
    { front: "mainstream", pos: "adj.", def: "accepted by or popular among most people", example: "Electronic music finally crossed into the mainstream charts.", zh: "主流的" },
    { front: "obscure", pos: "adj.", def: "not well known; difficult to understand", example: "He collects records by obscure jazz musicians.", zh: "鮮為人知的；晦澀的" },
    { front: "parody", pos: "n.", def: "a humorous imitation of a serious work or style", example: "The sketch is a parody of television cooking shows.", zh: "諧仿；惡搞作品" },
    { front: "portray", pos: "v.", def: "to represent or describe someone in a particular way", example: "The film portrays the queen as lonely and misunderstood.", zh: "描繪；飾演" },
    { front: "revival", pos: "n.", def: "the process of something becoming popular or active again", example: "Vinyl records are enjoying an unexpected revival.", zh: "復興；再度流行" },
    { front: "satire", pos: "n.", def: "humour that criticises people or institutions by mocking them", example: "The play is a biting satire on celebrity culture.", zh: "諷刺（作品）" },
    { front: "exquisite", pos: "adj.", def: "extremely beautiful and delicately made", example: "The palace is decorated with exquisite hand-painted tiles.", zh: "精美絕倫的" },
    { front: "mediocre", pos: "adj.", def: "of only average or fairly low quality", example: "Critics dismissed the sequel as mediocre.", zh: "平庸的" },
    { front: "captivating", pos: "adj.", def: "holding attention completely; fascinating", example: "Her captivating performance kept the audience silent for two hours.", zh: "迷人的" },
    { front: "immerse", pos: "v.", def: "to involve yourself deeply in an activity or experience", example: "He moved to Seville to immerse himself in flamenco culture.", zh: "沉浸；投入" },
    { front: "patron", pos: "n.", def: "a person who gives money to support the arts or an artist", example: "The composer depended on a wealthy patron for his living.", zh: "贊助人" },
    { front: "prestigious", pos: "adj.", def: "respected and admired as very important or high quality", example: "She won a place at a prestigious drama school.", zh: "聲望崇高的" },
    { front: "timeless", pos: "adj.", def: "not affected by the passing of time or changing fashions", example: "The novel deals with the timeless theme of love and loss.", zh: "永恆的；不受時間影響的" },
    { front: "versatile", pos: "adj.", def: "able to do many different things well", example: "He is a versatile actor, equally at home in comedy and tragedy.", zh: "多才多藝的" },
    { front: "anecdote", pos: "n.", def: "a short, entertaining story about a real person or event", example: "The biography is full of amusing anecdotes about the director.", zh: "軼事" },
    { front: "depict", pos: "v.", def: "to show or represent something in a picture or story", example: "The mural depicts the city's history in vivid colour.", zh: "描繪" },
    { front: "flourish", pos: "v.", def: "to grow or develop successfully", example: "Street art has flourished in the district since the festival began.", zh: "蓬勃發展" },
    { front: "narrative", pos: "n.", def: "a story, or the way a story is told", example: "The novel's narrative jumps between three generations.", zh: "敘事" },
    { front: "connoisseur", pos: "n.", def: "an expert judge of art, food or another matter of taste", example: "Only a true connoisseur could tell the two wines apart.", zh: "行家；鑑賞家" },
    { front: "curator", pos: "n.", def: "a person in charge of a museum or gallery collection", example: "The curator spent years assembling the exhibition.", zh: "策展人" },
    { front: "take up", pos: "phr. v.", def: "to start doing a new hobby or activity", example: "She took up pottery after retiring.", zh: "開始從事" },
    { front: "catch on", pos: "phr. v.", def: "to become popular or fashionable", example: "The dance craze caught on in schools across the country.", zh: "流行起來" },
    { front: "come out", pos: "phr. v.", def: "to be published or released to the public", example: "Her second novel comes out in the autumn.", zh: "出版；上映" },
    { front: "put on", pos: "phr. v.", def: "to organise and present a show or event", example: "The drama club puts on a musical every spring.", zh: "上演；舉辦" },
    { front: "sell out", pos: "phr. v.", def: "to be bought completely, leaving no tickets or stock", example: "The concert sold out within minutes.", zh: "售罄" },
    { front: "draw on", pos: "phr. v.", def: "to use knowledge or experience as a source", example: "The songwriter draws on her childhood in the mountains.", zh: "汲取；取材於" },
    { front: "live up to", pos: "phr. v.", def: "to be as good as what was expected or promised", example: "The sequel never quite lives up to the original.", zh: "不辜負；符合（期望）" },
    { front: "stand out", pos: "phr. v.", def: "to be clearly better or more noticeable than others", example: "One painting stood out from everything else in the show.", zh: "脫穎而出" },
    { front: "take off", pos: "phr. v.", def: "to suddenly become successful or popular", example: "Her career took off after the film festival award.", zh: "迅速走紅；起飛" },
    { front: "tone down", pos: "phr. v.", def: "to make something less extreme or offensive", example: "The director toned down the violence for the TV version.", zh: "緩和；淡化" },
    { front: "churn out", pos: "phr. v.", def: "to produce large amounts of something quickly, often carelessly", example: "The studio churns out three romantic comedies a year.", zh: "粗製濫造地大量生產" },
    { front: "dabble in", pos: "phr. v.", def: "to try an activity casually without serious commitment", example: "He dabbles in photography at the weekends.", zh: "涉獵；淺嘗" },
    { front: "rave reviews", pos: "collocation", def: "extremely enthusiastic praise from critics", example: "The new opera opened to rave reviews.", zh: "極高評價" },
    { front: "a box-office hit", pos: "collocation", def: "a film that earns a great deal of money", example: "Against all predictions, the quiet drama became a box-office hit.", zh: "賣座電影" },
    { front: "strike a chord", pos: "idiom", def: "to cause people to feel sympathy or emotional connection", example: "The song about leaving home struck a chord with migrant workers.", zh: "引起共鳴" },
    { front: "steal the show", pos: "idiom", def: "to attract more attention and praise than anyone else", example: "The eight-year-old violinist completely stole the show.", zh: "搶盡風頭" },
    { front: "an acquired taste", pos: "idiom", def: "something people only learn to like after trying it several times", example: "His experimental jazz is very much an acquired taste.", zh: "需培養才能欣賞的品味" },
    { front: "larger than life", pos: "idiom", def: "more exciting, colourful or extreme than most people", example: "The novelist was a larger-than-life character who told endless stories.", zh: "非凡出眾的；戲劇性十足的" },
    { front: "stand the test of time", pos: "idiom", def: "to remain popular or valued for a very long time", example: "Few pop songs stand the test of time like this one.", zh: "經得起時間考驗" },
    { front: "a household name", pos: "idiom", def: "a person or brand known by almost everyone", example: "One viral video turned the chef into a household name.", zh: "家喻戶曉的名字" },
    { front: "run-of-the-mill", pos: "idiom", def: "ordinary and not special or exciting", example: "It was a run-of-the-mill thriller with a predictable ending.", zh: "普普通通的" },
    { front: "artistic licence", pos: "collocation", def: "the freedom of artists to change facts for effect", example: "The film takes considerable artistic licence with the true story.", zh: "藝術創作自由" },
    /* === Health === */
    { front: "ailment", pos: "n.", def: "an illness, usually one that is not serious", example: "The pharmacist can advise on minor ailments.", zh: "小病；不適" },
    { front: "chronic", pos: "adj.", def: "lasting a long time and difficult to cure", example: "She has suffered from chronic back pain for years.", zh: "慢性的" },
    { front: "acute", pos: "adj.", def: "sudden, severe and requiring quick treatment", example: "He was rushed to hospital with acute appendicitis.", zh: "急性的；劇烈的" },
    { front: "contagious", pos: "adj.", def: "spreading from one person to another by contact", example: "Keep the patient isolated while the infection is contagious.", zh: "接觸傳染的" },
    { front: "epidemic", pos: "n.", def: "a sudden spread of a disease among many people", example: "The city struggled to contain the flu epidemic.", zh: "流行病；疫情" },
    { front: "immunity", pos: "n.", def: "the body's ability to resist a disease", example: "The vaccine gives long-lasting immunity to the virus.", zh: "免疫力" },
    { front: "diagnosis", pos: "n.", def: "the identification of an illness by examining symptoms", example: "An early diagnosis greatly improves the chances of recovery.", zh: "診斷" },
    { front: "prognosis", pos: "n.", def: "a doctor's judgement of how an illness will develop", example: "Thanks to the new treatment, her prognosis is excellent.", zh: "預後" },
    { front: "sedentary", pos: "adj.", def: "involving a lot of sitting and little exercise", example: "A sedentary lifestyle raises the risk of heart disease.", zh: "久坐不動的" },
    { front: "obesity", pos: "n.", def: "the condition of being dangerously overweight", example: "Childhood obesity has doubled in a generation.", zh: "肥胖症" },
    { front: "fatigue", pos: "n.", def: "extreme tiredness, physical or mental", example: "Pilots must report any signs of fatigue before flying.", zh: "疲勞" },
    { front: "insomnia", pos: "n.", def: "the inability to sleep", example: "Worry about exams gave him weeks of insomnia.", zh: "失眠" },
    { front: "alleviate", pos: "v.", def: "to make pain or a problem less severe", example: "Gentle stretching can alleviate muscle stiffness.", zh: "減輕；緩解" },
    { front: "deteriorate", pos: "v.", def: "to become progressively worse", example: "Without treatment, his eyesight will continue to deteriorate.", zh: "惡化" },
    { front: "rehabilitate", pos: "v.", def: "to help someone return to health or normal life", example: "The clinic rehabilitates athletes after major injuries.", zh: "使康復" },
    { front: "therapeutic", pos: "adj.", def: "helping to cure illness or reduce stress", example: "Many people find gardening deeply therapeutic.", zh: "有療效的；療癒的" },
    { front: "debilitating", pos: "adj.", def: "making someone very weak and unable to function normally", example: "Migraines can be utterly debilitating.", zh: "使人衰弱的" },
    { front: "susceptible", pos: "adj.", def: "easily affected or harmed by something", example: "Smokers are more susceptible to chest infections.", zh: "易受影響的；易感染的" },
    { front: "hygiene", pos: "n.", def: "the practice of keeping clean to prevent disease", example: "Good hand hygiene stops germs from spreading.", zh: "衛生" },
    { front: "transplant", pos: "n.", def: "an operation to move an organ from one body to another", example: "He is on the waiting list for a kidney transplant.", zh: "（器官）移植" },
    { front: "remission", pos: "n.", def: "a period when a serious illness improves or disappears", example: "Her cancer has been in remission for five years.", zh: "（病情）緩解期" },
    { front: "relapse", pos: "n.", def: "a return of an illness after apparent recovery", example: "Stopping the medication too early can trigger a relapse.", zh: "復發" },
    { front: "wholesome", pos: "adj.", def: "good for your health and well-being", example: "The cafe serves simple, wholesome food.", zh: "有益健康的" },
    { front: "invigorating", pos: "adj.", def: "making you feel fresher, healthier and more energetic", example: "There is nothing like an invigorating swim before breakfast.", zh: "使人精神振奮的" },
    { front: "addictive", pos: "adj.", def: "causing a strong harmful need to keep having or doing something", example: "The painkillers proved dangerously addictive.", zh: "使人上癮的" },
    { front: "strenuous", pos: "adj.", def: "needing great physical effort and energy", example: "Avoid strenuous exercise for a week after the operation.", zh: "費力的；劇烈的" },
    { front: "longevity", pos: "n.", def: "long life; the length of a person's life", example: "Researchers link the islanders' longevity to their diet.", zh: "長壽" },
    { front: "well-being", pos: "n.", def: "the state of feeling healthy, comfortable and happy", example: "Regular breaks improve both productivity and well-being.", zh: "身心健康；福祉" },
    { front: "come down with", pos: "phr. v.", def: "to begin to suffer from an illness", example: "Half the office came down with a cold last week.", zh: "染上（病）" },
    { front: "get over", pos: "phr. v.", def: "to recover from an illness or an unpleasant experience", example: "It took her a month to get over the flu.", zh: "康復；恢復" },
    { front: "pass out", pos: "phr. v.", def: "to lose consciousness suddenly", example: "He passed out from the heat during the parade.", zh: "昏倒" },
    { front: "come round", pos: "phr. v.", def: "to become conscious again", example: "She came round a few minutes after fainting.", zh: "甦醒" },
    { front: "fight off", pos: "phr. v.", def: "to resist an illness and prevent it from developing", example: "A strong immune system helps you fight off infections.", zh: "抵抗（疾病）" },
    { front: "flare up", pos: "phr. v.", def: "to suddenly become worse or more painful again", example: "His old knee injury flared up during the marathon.", zh: "（舊疾）復發；突然加劇" },
    { front: "pull through", pos: "phr. v.", def: "to survive a serious illness or difficult situation", example: "The surgeons say she should pull through.", zh: "渡過難關；痊癒" },
    { front: "wear off", pos: "phr. v.", def: "to gradually stop having an effect", example: "The anaesthetic wore off within an hour.", zh: "（藥效等）逐漸消退" },
    { front: "throw up", pos: "phr. v.", def: "to vomit", example: "The rough ferry crossing made several passengers throw up.", zh: "嘔吐" },
    { front: "cut out", pos: "phr. v.", def: "to stop eating or doing something, especially for health", example: "The doctor told him to cut out fried food completely.", zh: "戒除；停止攝取" },
    { front: "build up", pos: "phr. v.", def: "to increase or strengthen something gradually", example: "Light training helps patients build up their strength again.", zh: "逐漸增強" },
    { front: "swell up", pos: "phr. v.", def: "to become larger and rounder than normal after injury", example: "Her ankle swelled up badly after the fall.", zh: "腫脹" },
    { front: "a balanced diet", pos: "collocation", def: "a diet containing the right amounts of different foods", example: "A balanced diet matters more than any supplement.", zh: "均衡飲食" },
    { front: "under the weather", pos: "idiom", def: "feeling slightly ill", example: "I stayed home because I was feeling under the weather.", zh: "身體不舒服" },
    { front: "on the mend", pos: "idiom", def: "getting better after an illness or injury", example: "After a rough week, Grandpa is finally on the mend.", zh: "逐漸康復" },
    { front: "a clean bill of health", pos: "idiom", def: "an official statement that someone is completely healthy", example: "The check-up gave her a clean bill of health.", zh: "健康無虞的證明" },
    { front: "make a full recovery", pos: "collocation", def: "to become completely healthy again after illness or injury", example: "Doctors expect the striker to make a full recovery.", zh: "完全康復" },
    { front: "run in the family", pos: "idiom", def: "to be a common feature or condition among family members", example: "Heart trouble runs in the family, so he gets tested yearly.", zh: "家族遺傳" },
    { front: "back on your feet", pos: "idiom", def: "healthy or successful again after illness or trouble", example: "A week of rest and you will be back on your feet.", zh: "恢復健康；東山再起" },
    { front: "out of shape", pos: "collocation", def: "not physically fit", example: "Months at a desk left him badly out of shape.", zh: "身材走樣；體能差" },
    { front: "a health hazard", pos: "collocation", def: "something that is dangerous to people's health", example: "The mouldy old building was declared a health hazard.", zh: "健康危害" },
    { front: "fit as a fiddle", pos: "idiom", def: "in excellent physical condition", example: "At eighty, my grandmother is still fit as a fiddle.", zh: "非常健康" },
    /* === Technology === */
    { front: "obsolete", pos: "adj.", def: "no longer used because something newer exists", example: "Fax machines are now practically obsolete.", zh: "過時的；淘汰的" },
    { front: "cutting-edge", pos: "adj.", def: "extremely modern and at the newest stage of development", example: "The start-up develops cutting-edge battery technology.", zh: "尖端的" },
    { front: "automation", pos: "n.", def: "the use of machines to do work previously done by people", example: "Automation has transformed the car assembly line.", zh: "自動化" },
    { front: "algorithm", pos: "n.", def: "a set of rules a computer follows to solve a problem", example: "The app's algorithm decides which videos you see next.", zh: "演算法" },
    { front: "encryption", pos: "n.", def: "the process of converting data into a secret code", example: "The messaging service uses end-to-end encryption.", zh: "加密" },
    { front: "surveillance", pos: "n.", def: "the close watching of people, especially with cameras", example: "The square is under constant video surveillance.", zh: "監控" },
    { front: "breach", pos: "n.", def: "an act of breaking a rule, agreement or security system", example: "The breach exposed millions of customer passwords.", zh: "違反；（資安）漏洞事件" },
    { front: "vulnerability", pos: "n.", def: "a weakness that can be attacked or exploited", example: "Hackers exploited a vulnerability in the login page.", zh: "弱點；漏洞" },
    { front: "glitch", pos: "n.", def: "a small fault that stops something working smoothly", example: "A software glitch delayed flights for two hours.", zh: "小故障" },
    { front: "compatibility", pos: "n.", def: "the ability of devices or programs to work together", example: "Check the compatibility of the printer with your laptop.", zh: "相容性" },
    { front: "prototype", pos: "n.", def: "the first model of a product used for testing", example: "Engineers unveiled a working prototype of the electric plane.", zh: "原型機" },
    { front: "malfunction", pos: "n.", def: "a failure of a machine to work correctly", example: "The crash was caused by a sensor malfunction.", zh: "故障" },
    { front: "seamless", pos: "adj.", def: "happening smoothly without interruptions or problems", example: "The update promises a seamless transition between devices.", zh: "無縫的；流暢的" },
    { front: "intuitive", pos: "adj.", def: "easy to understand and use without instruction", example: "Even my grandfather finds the interface intuitive.", zh: "直覺好用的" },
    { front: "ubiquitous", pos: "adj.", def: "seeming to be everywhere at the same time", example: "Smartphones have become ubiquitous in classrooms.", zh: "無所不在的" },
    { front: "proliferation", pos: "n.", def: "a rapid increase in number or spread", example: "The proliferation of streaming services is fragmenting audiences.", zh: "激增；擴散" },
    { front: "digitise", pos: "v.", def: "to convert information into a digital form", example: "The library is digitising its collection of old maps.", zh: "數位化" },
    { front: "cybersecurity", pos: "n.", def: "protection of computers and data against attack", example: "The bank doubled its spending on cybersecurity.", zh: "網路安全" },
    { front: "misinformation", pos: "n.", def: "false information spread without necessarily intending harm", example: "Health misinformation spreads faster than the corrections.", zh: "錯誤資訊" },
    { front: "anonymity", pos: "n.", def: "the state of remaining unknown or unnamed", example: "Online anonymity can encourage abusive behaviour.", zh: "匿名性" },
    { front: "connectivity", pos: "n.", def: "the ability to connect to the internet or other systems", example: "Rural areas still suffer from poor connectivity.", zh: "連線能力" },
    { front: "pioneering", pos: "adj.", def: "introducing new ideas or methods for the first time", example: "Her pioneering work on touchscreens changed the industry.", zh: "開創性的" },
    { front: "revolutionise", pos: "v.", def: "to change something completely and fundamentally", example: "Cheap sensors have revolutionised weather forecasting.", zh: "徹底改變" },
    { front: "emulate", pos: "v.", def: "to copy something admired, or imitate another system", example: "Rivals have tried and failed to emulate the phone's design.", zh: "仿效" },
    { front: "render", pos: "v.", def: "to cause something to be in a particular state", example: "The update rendered thousands of older devices useless.", zh: "使成為；使變得" },
    { front: "wearable", pos: "adj.", def: "designed to be worn on the body, as with smart devices", example: "Wearable trackers now monitor sleep as well as steps.", zh: "穿戴式的" },
    { front: "autonomous", pos: "adj.", def: "able to operate independently without human control", example: "Autonomous delivery robots roam the campus paths.", zh: "自主的；自動的" },
    { front: "immersive", pos: "adj.", def: "seeming to surround you so that you feel completely involved", example: "The headset creates a fully immersive training environment.", zh: "沉浸式的" },
    { front: "back up", pos: "phr. v.", def: "to make a copy of computer data for safety", example: "Back up your files before installing the update.", zh: "備份" },
    { front: "shut down", pos: "phr. v.", def: "to stop a machine or system from operating", example: "The plant shut down its servers during the storm.", zh: "關閉；停機" },
    { front: "scroll through", pos: "phr. v.", def: "to move through content on a screen", example: "She scrolled through hundreds of photos to find the right one.", zh: "滑動瀏覽" },
    { front: "zoom in", pos: "phr. v.", def: "to make an image appear larger and closer", example: "Zoom in on the corner of the map to see the trail.", zh: "放大（畫面）" },
    { front: "hook up", pos: "phr. v.", def: "to connect a machine to a power source or another device", example: "Can you hook the console up to the projector?", zh: "連接（設備）" },
    { front: "phase in", pos: "phr. v.", def: "to introduce something gradually in stages", example: "The school will phase in tablets one year group at a time.", zh: "逐步引進" },
    { front: "roll out", pos: "phr. v.", def: "to launch a new product or service widely", example: "The feature will be rolled out to all users next month.", zh: "推出；全面上線" },
    { front: "keep up with", pos: "phr. v.", def: "to stay informed about or move at the same speed as", example: "It is hard to keep up with every new social platform.", zh: "跟上" },
    { front: "iron out", pos: "phr. v.", def: "to remove small problems or difficulties", example: "Developers are still ironing out bugs in the beta version.", zh: "解決（小問題）" },
    { front: "crop up", pos: "phr. v.", def: "to appear or happen unexpectedly", example: "The same error kept cropping up after every restart.", zh: "突然出現" },
    { front: "sign up for", pos: "phr. v.", def: "to register for a service, course or account", example: "Millions signed up for the free trial in the first week.", zh: "註冊；報名" },
    { front: "switch over", pos: "phr. v.", def: "to change completely from one system to another", example: "The office switched over to cloud storage last year.", zh: "轉換（系統）" },
    { front: "the digital divide", pos: "collocation", def: "the gap between people with and without access to technology", example: "Remote learning exposed the digital divide between households.", zh: "數位落差" },
    { front: "a double-edged sword", pos: "idiom", def: "something with both good and bad effects", example: "Social media fame is a double-edged sword for teenagers.", zh: "雙面刃" },
    { front: "at the touch of a button", pos: "idiom", def: "very easily and immediately, using technology", example: "You can now order groceries at the touch of a button.", zh: "一鍵之間；輕而易舉" },
    { front: "second nature", pos: "idiom", def: "something so familiar you do it without thinking", example: "After a month, using the shortcuts became second nature.", zh: "習慣成自然" },
    { front: "teething problems", pos: "idiom", def: "small difficulties at the start of a new project", example: "The ticket app had the usual teething problems at launch.", zh: "初期問題" },
    { front: "grind to a halt", pos: "idiom", def: "to slow down gradually and then stop completely", example: "The whole network ground to a halt during the outage.", zh: "陷入停頓" },
    { front: "a game changer", pos: "collocation", def: "something that completely alters how things are done", example: "Instant translation could be a game changer for travellers.", zh: "改變局勢的事物" },
    { front: "user-friendly", pos: "collocation", def: "easy for people to use or understand", example: "The redesigned website is far more user-friendly.", zh: "容易使用的" },
    { front: "reinvent the wheel", pos: "idiom", def: "to waste time creating something that already exists", example: "Use the standard library instead of reinventing the wheel.", zh: "白費工夫重做已有之事" },
    { front: "planned obsolescence", pos: "collocation", def: "designing products to become useless quickly so people buy more", example: "Critics accuse phone makers of planned obsolescence.", zh: "計畫性淘汰" }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
