/* CAE Prep extra bank: vocab wave 5 */
(function () {
  var BANK = [
    /* === Politics & international relations === */
    { front: "diplomacy", pos: "n.", def: "the management of relations between countries through discussion and negotiation", example: "The border dispute was eventually settled through patient diplomacy rather than force.", zh: "外交；外交手腕" },
    { front: "envoy", pos: "n.", def: "an official representative sent by one government to another", example: "A special envoy was dispatched to the region to oversee the peace negotiations.", zh: "特使；使節" },
    { front: "treaty", pos: "n.", def: "a formal written agreement between two or more countries", example: "Both nations signed a treaty banning the testing of nuclear weapons.", zh: "條約" },
    { front: "ceasefire", pos: "n.", def: "an agreement to stop fighting for a period of time", example: "The ceasefire collapsed within days when shelling resumed along the border.", zh: "停火協議" },
    { front: "ratify", pos: "v.", def: "to give formal approval to an agreement so that it becomes valid", example: "Parliament must ratify the trade agreement before it can take effect.", zh: "批准；正式通過" },
    { front: "veto", pos: "v.", def: "to officially refuse to allow a proposed law or decision", example: "The president threatened to veto any bill that raised taxes on small businesses.", zh: "否決" },
    { front: "sanction", pos: "n.", def: "an official penalty, especially one country limiting trade with another", example: "Economic sanctions were imposed on the regime after it violated the treaty.", zh: "制裁" },
    { front: "bilateral", pos: "adj.", def: "involving two countries or two sides", example: "The two governments held bilateral talks on immigration and border security.", zh: "雙邊的" },
    { front: "unilateral", pos: "adj.", def: "done by one country or group without the agreement of others", example: "The unilateral withdrawal from the pact angered several long-standing allies.", zh: "單方面的" },
    { front: "multilateral", pos: "adj.", def: "involving several countries or parties", example: "Climate change can only be tackled through multilateral cooperation.", zh: "多邊的" },
    { front: "annex", pos: "v.", def: "to take control of a territory and add it to your own country, usually by force", example: "The empire annexed the neighbouring province after a brief military campaign.", zh: "併吞（領土）" },
    { front: "secede", pos: "v.", def: "to formally withdraw from a country or organisation and become independent", example: "The region voted overwhelmingly to secede from the federation.", zh: "脫離（國家或聯邦）" },
    { front: "coup", pos: "n.", def: "a sudden, often violent, seizure of power from a government", example: "The elected president was ousted in a military coup last spring.", zh: "政變" },
    { front: "regime", pos: "n.", def: "a government, especially an authoritarian one", example: "The regime silenced journalists who dared to criticise its policies.", zh: "政權（尤指專制政權）" },
    { front: "autocracy", pos: "n.", def: "a system of government in which one person has unlimited power", example: "The country drifted from fragile democracy towards outright autocracy.", zh: "獨裁政體" },
    { front: "totalitarian", pos: "adj.", def: "relating to a system in which the state controls every aspect of life", example: "The novel depicts a totalitarian state where even private thoughts are policed.", zh: "極權主義的" },
    { front: "alliance", pos: "n.", def: "a formal agreement between countries or groups to work together", example: "The two nations formed a defensive alliance against their common rival.", zh: "同盟；聯盟" },
    { front: "asylum", pos: "n.", def: "protection given by a state to someone fleeing persecution", example: "The dissident writer was granted political asylum in Sweden.", zh: "政治庇護" },
    { front: "deport", pos: "v.", def: "to force a foreigner to leave a country, usually for legal reasons", example: "He was deported after officials discovered his visa had expired years earlier.", zh: "驅逐出境" },
    { front: "extradite", pos: "v.", def: "to send someone accused of a crime back to the country where it was committed", example: "The suspect fought for years against being extradited to face fraud charges.", zh: "引渡" },
    { front: "repatriate", pos: "v.", def: "to send someone back to their own country", example: "After the war ended, thousands of refugees were repatriated to their homeland.", zh: "遣返回國" },
    { front: "escalate", pos: "v.", def: "to become or make more intense or serious", example: "Diplomats fear the skirmishes could escalate into a full-scale conflict.", zh: "（使）升級；（使）惡化" },
    { front: "defuse", pos: "v.", def: "to make a dangerous or tense situation calmer", example: "The foreign minister flew in to defuse the escalating diplomatic row.", zh: "化解（緊張局勢）" },
    { front: "mediate", pos: "v.", def: "to try to end a disagreement between two sides by talking to both", example: "The UN offered to mediate between the government and the rebel forces.", zh: "調停；斡旋" },
    { front: "broker", pos: "v.", def: "to arrange the details of an agreement between opposing sides", example: "Norway helped broker a historic peace deal between the warring factions.", zh: "促成（協議）" },
    { front: "lobby", pos: "v.", def: "to try to influence politicians to support a particular cause", example: "Environmental groups lobbied hard for stricter emissions targets.", zh: "遊說" },
    { front: "manifesto", pos: "n.", def: "a public statement of a political party's aims and policies", example: "The party's manifesto promised sweeping investment in public transport.", zh: "（政黨的）宣言、政綱" },
    { front: "dissident", pos: "n.", def: "a person who publicly opposes an authoritarian government", example: "The dissident spent a decade in prison for organising peaceful protests.", zh: "異議人士" },
    { front: "exile", pos: "n.", def: "the state of being forced to live away from your own country", example: "The former leader has lived in exile since the coup.", zh: "流亡；放逐" },
    { front: "topple", pos: "v.", def: "to remove a government or leader from power", example: "Mass protests eventually toppled the corrupt administration.", zh: "推翻（政府、領袖）" },
    { front: "destabilise", pos: "v.", def: "to make a government, country or system less stable", example: "Foreign interference threatened to destabilise the fragile new democracy.", zh: "使動盪；破壞穩定" },
    { front: "intervention", pos: "n.", def: "the act of becoming involved in a situation to influence its outcome", example: "Critics argued that military intervention would only worsen the crisis.", zh: "干預；介入" },
    { front: "repeal", pos: "v.", def: "to officially end a law so that it is no longer valid", example: "Campaigners are urging the government to repeal the outdated legislation.", zh: "廢除（法律）" },
    { front: "insurgency", pos: "n.", def: "an organised armed rebellion against a government", example: "The army has struggled to contain the insurgency in the northern provinces.", zh: "叛亂；暴動" },
    { front: "pull out of", pos: "phr. v.", def: "to withdraw from an agreement, organisation or activity", example: "The government decided to pull out of the international accord altogether.", zh: "退出（協議、組織）" },
    { front: "break off", pos: "phr. v.", def: "to end something suddenly, such as talks or a relationship", example: "The two countries broke off diplomatic relations after the spying scandal.", zh: "中斷（會談、關係）" },
    { front: "side with", pos: "phr. v.", def: "to support one person or group in a disagreement", example: "Most smaller nations sided with the proposal to reform the voting system.", zh: "支持（某一方）；站在…那邊" },
    { front: "stand down", pos: "phr. v.", def: "to resign from an official position", example: "The minister stood down amid allegations of misusing public funds.", zh: "辭職；退位" },
    { front: "swear in", pos: "phr. v.", def: "to make someone officially take up a position by taking a formal oath", example: "The new prime minister was sworn in at a ceremony on Monday.", zh: "宣誓就職" },
    { front: "run for", pos: "phr. v.", def: "to be a candidate in an election", example: "She announced her intention to run for mayor next year.", zh: "競選（職位）" },
    { front: "bow to", pos: "phr. v.", def: "to finally agree to do what others demand, unwillingly", example: "The government bowed to public pressure and scrapped the unpopular tax.", zh: "屈服於（壓力、要求）" },
    { front: "rally behind", pos: "phr. v.", def: "to join together to support a person or cause", example: "Voters rallied behind the young candidate after the televised debate.", zh: "團結支持" },
    { front: "prop up", pos: "phr. v.", def: "to support a weak government, economy or system to stop it failing", example: "Foreign loans have propped up the failing regime for decades.", zh: "扶持；支撐（搖搖欲墜的體制）" },
    { front: "rein in", pos: "phr. v.", def: "to control something more strictly, especially spending or power", example: "The new law is designed to rein in the power of the security services.", zh: "控制；約束" },
    { front: "hammer out", pos: "phr. v.", def: "to reach an agreement after long and difficult discussion", example: "Negotiators worked through the night to hammer out a compromise.", zh: "（經艱苦協商）達成（協議）" },
    { front: "fend off", pos: "phr. v.", def: "to defend yourself against criticism, attacks or unwanted demands", example: "The spokesperson spent the briefing fending off questions about the leak.", zh: "抵擋；避開（批評、攻擊）" },
    { front: "stave off", pos: "phr. v.", def: "to prevent something bad from happening, at least temporarily", example: "Emergency talks were held to stave off a full-blown diplomatic crisis.", zh: "暫時避免；延緩（壞事發生）" },
    { front: "bail out", pos: "phr. v.", def: "to rescue a country, company or person from financial collapse", example: "Taxpayers were furious that the state had to bail out the failing banks.", zh: "（財務上）救助、紓困" },
    { front: "break away", pos: "phr. v.", def: "to leave a political party, country or group to form a separate one", example: "Several MPs broke away to found a new centrist party.", zh: "脫離（政黨、團體）" },
    { front: "hold out for", pos: "phr. v.", def: "to refuse to accept an offer, waiting for a better one", example: "The union is holding out for a significantly better pay deal.", zh: "堅持等待（更好的條件）" },
    { front: "cave in", pos: "phr. v.", def: "to stop resisting and agree to demands", example: "After weeks of strikes, the ministry finally caved in to the workers' demands.", zh: "讓步；屈服" },
    { front: "back out of", pos: "phr. v.", def: "to withdraw from an arrangement you had agreed to", example: "The delegation backed out of the summit at the last minute.", zh: "退出；反悔（承諾）" },
    { front: "patch up", pos: "phr. v.", def: "to repair a relationship or settle a disagreement, often temporarily", example: "The two leaders met privately to patch up their strained relationship.", zh: "修補（關係）；平息（爭執）" },
    { front: "carve up", pos: "phr. v.", def: "to divide land, power or a market between groups, often unfairly", example: "The colonial powers carved up the continent with little regard for its peoples.", zh: "瓜分" },
    { front: "buy off", pos: "phr. v.", def: "to pay someone so that they stop opposing you or causing trouble", example: "The regime tried to buy off its critics with lucrative government posts.", zh: "收買" },
    { front: "push for", pos: "phr. v.", def: "to demand something repeatedly and forcefully", example: "Opposition parties are pushing for an independent inquiry into the scandal.", zh: "極力爭取；施壓要求" },
    { front: "fall through", pos: "phr. v.", def: "to fail to happen or be completed, especially a plan or deal", example: "The ceasefire agreement fell through when neither side would compromise.", zh: "（計畫、協議）告吹、落空" },
    { front: "rise up", pos: "phr. v.", def: "to rebel against a government or authority", example: "The population rose up against decades of authoritarian rule.", zh: "起義；反抗" },
    { front: "foreign policy", pos: "collocation", def: "a government's strategy in dealing with other nations", example: "The new administration signalled a major shift in foreign policy towards Asia.", zh: "外交政策" },
    { front: "diplomatic immunity", pos: "collocation", def: "the special legal protection given to foreign diplomats", example: "The attaché claimed diplomatic immunity to avoid prosecution.", zh: "外交豁免權" },
    { front: "arms race", pos: "collocation", def: "competition between countries to build the most powerful weapons", example: "Analysts warn that the region is sliding into a dangerous arms race.", zh: "軍備競賽" },
    { front: "balance of power", pos: "collocation", def: "a situation in which strength is evenly distributed so no side dominates", example: "The alliance was designed to preserve the balance of power in Europe.", zh: "權力平衡；均勢" },
    { front: "sever ties", pos: "collocation", def: "to end a relationship or connection completely", example: "The government severed ties with the rogue state after the missile test.", zh: "斷絕關係" },
    { front: "strained relations", pos: "collocation", def: "a relationship marked by tension and distrust", example: "The espionage affair led to strained relations between the two capitals.", zh: "緊張的關係" },
    { front: "a show of force", pos: "collocation", def: "a demonstration of military or political strength intended to intimidate", example: "The naval exercises were widely seen as a show of force aimed at its neighbour.", zh: "武力展示" },
    { front: "a power vacuum", pos: "collocation", def: "a situation where no one is clearly in control after a leader's fall", example: "The dictator's sudden death left a power vacuum that rival factions rushed to fill.", zh: "權力真空" },
    { front: "a puppet government", pos: "collocation", def: "a government that is controlled by a more powerful outside force", example: "The occupying army installed a puppet government loyal to its interests.", zh: "傀儡政府" },
    { front: "extend an olive branch", pos: "idiom", def: "to make a gesture of peace towards an opponent", example: "In his speech, the president extended an olive branch to his fiercest critics.", zh: "伸出橄欖枝；主動求和" },
    { front: "behind closed doors", pos: "idiom", def: "in private, hidden from public view", example: "The real negotiations took place behind closed doors, away from the cameras.", zh: "閉門地；祕密地" },
    { front: "a political minefield", pos: "idiom", def: "a subject or situation full of hidden political dangers", example: "Pension reform is a political minefield that most governments prefer to avoid.", zh: "政治地雷區；棘手的政治議題" },
    /* === Verbs of speech & argument === */
    { front: "contend", pos: "v.", def: "to argue or claim that something is true", example: "The defence contends that the evidence was obtained illegally.", zh: "主張；聲稱" },
    { front: "allude", pos: "v.", def: "to mention something indirectly without saying it openly", example: "In her farewell speech she alluded to tensions within the board.", zh: "暗指；間接提及" },
    { front: "proclaim", pos: "v.", def: "to announce something publicly and officially", example: "The rebels proclaimed victory before the fighting had even finished.", zh: "宣告；聲明" },
    { front: "denounce", pos: "v.", def: "to criticise someone or something publicly and strongly", example: "Human rights groups denounced the crackdown as brutal and unlawful.", zh: "公開譴責" },
    { front: "rebuke", pos: "v.", def: "to criticise someone sharply, usually with authority", example: "The judge rebuked the lawyer for repeatedly interrupting the witness.", zh: "斥責；訓斥" },
    { front: "reproach", pos: "v.", def: "to express disappointment or blame towards someone", example: "She gently reproached him for forgetting their anniversary again.", zh: "責備；責怪" },
    { front: "admonish", pos: "v.", def: "to warn or criticise someone mildly but firmly", example: "The teacher admonished the students for arriving late to the exam.", zh: "告誡；勸誡" },
    { front: "corroborate", pos: "v.", def: "to provide evidence that supports a statement or claim", example: "Two independent witnesses corroborated her account of the accident.", zh: "證實；佐證" },
    { front: "substantiate", pos: "v.", def: "to prove a claim with evidence or facts", example: "He was unable to substantiate his allegations with any documents.", zh: "證實；提出證據支持" },
    { front: "debunk", pos: "v.", def: "to show that a widely believed idea is false", example: "The documentary debunks several myths about vaccination.", zh: "揭穿（謬論）；駁斥" },
    { front: "bicker", pos: "v.", def: "to argue about unimportant things", example: "The committee spent an hour bickering over the wording of one sentence.", zh: "為小事爭吵" },
    { front: "wrangle", pos: "v.", def: "to argue noisily or for a long time, especially over a complicated issue", example: "Lawyers wrangled for months over the terms of the settlement.", zh: "激烈爭論" },
    { front: "retort", pos: "v.", def: "to reply quickly and sharply, often angrily or wittily", example: "When asked if he was tired, he retorted that he could work all night.", zh: "反駁；回嘴" },
    { front: "interject", pos: "v.", def: "to say something suddenly that interrupts someone else", example: "May I interject a brief comment before we move on?", zh: "插話" },
    { front: "lament", pos: "v.", def: "to express deep sadness or regret about something", example: "Critics lament the decline of serious journalism in the digital age.", zh: "哀嘆；痛惜" },
    { front: "grumble", pos: "v.", def: "to complain in a quiet but bad-tempered way", example: "Commuters grumbled about yet another rise in rail fares.", zh: "發牢騷；抱怨" },
    { front: "coax", pos: "v.", def: "to persuade someone gently and patiently to do something", example: "It took ages to coax the frightened child into the dentist's chair.", zh: "哄勸；勸誘" },
    { front: "cajole", pos: "v.", def: "to persuade someone by flattery or persistent gentle pressure", example: "She cajoled her reluctant colleagues into staying late to finish the report.", zh: "甜言蜜語地哄騙、勸誘" },
    { front: "divulge", pos: "v.", def: "to reveal information that should be kept secret", example: "The spokesperson refused to divulge the names of the investors.", zh: "洩露（祕密）" },
    { front: "disclose", pos: "v.", def: "to make previously secret information known", example: "Companies must disclose any payments made to political parties.", zh: "揭露；公開" },
    { front: "purport", pos: "v.", def: "to claim to be or do something, especially falsely", example: "The letter purports to be from the tax office, but it is clearly a scam.", zh: "聲稱；佯稱" },
    { front: "uphold", pos: "v.", def: "to defend or maintain a principle, law or decision", example: "The court upheld the original ruling despite the appeal.", zh: "維護；維持（原判）" },
    { front: "rebut", pos: "v.", def: "to argue that a statement or criticism is false", example: "The minister rebutted claims that the figures had been manipulated.", zh: "反駁" },
    { front: "endorse", pos: "v.", def: "to publicly declare your support for someone or something", example: "Several leading scientists have endorsed the new climate report.", zh: "公開支持；背書" },
    { front: "concur", pos: "v.", def: "to agree with someone or share an opinion", example: "The second doctor concurred with the original diagnosis.", zh: "同意；意見一致" },
    { front: "acquiesce", pos: "v.", def: "to accept something reluctantly without protest", example: "Faced with unanimous opposition, he acquiesced to the committee's decision.", zh: "默許；勉強同意" },
    { front: "recount", pos: "v.", def: "to describe events in detail, especially from experience", example: "The survivor recounted how the crew had battled the storm for hours.", zh: "詳述；敘述" },
    { front: "rant", pos: "v.", def: "to speak or complain loudly, angrily and at length", example: "He spent the entire meeting ranting about the parking situation.", zh: "咆哮；激烈抱怨" },
    { front: "waffle", pos: "v.", def: "to talk at length without saying anything clear or useful", example: "Stop waffling and tell us exactly what went wrong.", zh: "說話含糊冗長；打太極" },
    { front: "hedge", pos: "v.", def: "to avoid giving a direct answer or commitment", example: "When pressed on the tax question, the candidate hedged.", zh: "含糊其辭；避免正面回答" },
    { front: "stipulate", pos: "v.", def: "to state exactly what must be done as part of an agreement", example: "The contract stipulates that payment must be made within thirty days.", zh: "（合約中）明確規定" },
    { front: "deride", pos: "v.", def: "to mock or express contempt for someone or something", example: "Critics derided the proposal as hopelessly unrealistic.", zh: "嘲笑；奚落" },
    { front: "blurt out", pos: "phr. v.", def: "to say something suddenly without thinking, often revealing a secret", example: "In his panic, he blurted out the surprise party plans.", zh: "脫口而出" },
    { front: "talk round", pos: "phr. v.", def: "to persuade someone to change their mind and agree with you", example: "She was against the move at first, but we managed to talk her round.", zh: "說服（某人改變主意）" },
    { front: "win over", pos: "phr. v.", def: "to gain someone's support or approval by persuading them", example: "Her passionate speech won over even the most sceptical members of the audience.", zh: "贏得（支持）；說服" },
    { front: "shoot down", pos: "phr. v.", def: "to reject an idea or argument forcefully", example: "Every suggestion I made was immediately shot down by the manager.", zh: "斷然否決（想法）" },
    { front: "pick apart", pos: "phr. v.", def: "to criticise something by finding every fault in it", example: "The professor picked apart the student's argument point by point.", zh: "逐一批駁；挑毛病" },
    { front: "chime in", pos: "phr. v.", def: "to join a conversation by adding a comment", example: "Feel free to chime in if you have anything to add.", zh: "插話附和" },
    { front: "pipe up", pos: "phr. v.", def: "to suddenly start speaking, especially after being quiet", example: "A small voice piped up from the back of the room with a brilliant question.", zh: "突然開口說話" },
    { front: "pipe down", pos: "phr. v.", def: "to stop talking or be quieter", example: "The referee told the furious players to pipe down and get on with the game.", zh: "安靜下來；住口" },
    { front: "trail off", pos: "phr. v.", def: "to become gradually quieter and then stop speaking", example: "Her voice trailed off as she realised nobody was listening.", zh: "（說話聲）逐漸變小而停止" },
    { front: "ramble on", pos: "phr. v.", def: "to talk for a long time in a confused or boring way", example: "He rambled on about his fishing trip while everyone checked their phones.", zh: "漫無邊際地說個不停" },
    { front: "drone on", pos: "phr. v.", def: "to talk for a long time in a dull, monotonous voice", example: "The lecturer droned on for two hours without a single pause.", zh: "單調乏味地講個不停" },
    { front: "harp on about", pos: "phr. v.", def: "to keep talking about something in an annoying way", example: "She is always harping on about how things were better in her day.", zh: "喋喋不休地反覆講" },
    { front: "hold forth", pos: "phr. v.", def: "to speak at length about a subject, often pompously", example: "He held forth on the state of modern art to anyone who would listen.", zh: "高談闊論" },
    { front: "come out with", pos: "phr. v.", def: "to say something suddenly and unexpectedly", example: "You never know what outrageous remark she will come out with next.", zh: "突然說出" },
    { front: "put across", pos: "phr. v.", def: "to communicate an idea clearly so others understand it", example: "He struggles to put his ideas across in large meetings.", zh: "清楚表達；傳達" },
    { front: "explain away", pos: "phr. v.", def: "to give reasons for something bad so it seems less serious", example: "The company tried to explain away the safety failures as isolated incidents.", zh: "（找藉口）搪塞、辯解" },
    { front: "thrash out", pos: "phr. v.", def: "to discuss a problem thoroughly until a solution is reached", example: "The details of the merger still need to be thrashed out.", zh: "反覆討論以解決（問題）" },
    { front: "brush off", pos: "phr. v.", def: "to dismiss someone or their comments as unimportant", example: "The CEO brushed off concerns about falling sales.", zh: "對…不予理會" },
    { front: "back down", pos: "phr. v.", def: "to withdraw a claim or demand after opposition", example: "Neither side is willing to back down in the pay dispute.", zh: "讓步；退縮" },
    { front: "clam up", pos: "phr. v.", def: "to suddenly refuse to speak, especially about something sensitive", example: "The witness clammed up as soon as the detective mentioned the money.", zh: "突然閉口不談" },
    { front: "let on", pos: "phr. v.", def: "to reveal a secret, often unintentionally", example: "Don't let on that we already know about the surprise.", zh: "透露（祕密）" },
    { front: "skirt around", pos: "phr. v.", def: "to avoid discussing a difficult topic directly", example: "The report skirts around the question of who was actually responsible.", zh: "迴避（話題）" },
    { front: "fob off", pos: "phr. v.", def: "to give someone a poor excuse or inferior thing to make them stop asking", example: "Customers complained of being fobbed off with vague promises of a refund.", zh: "以藉口敷衍；搪塞" },
    { front: "reel off", pos: "phr. v.", def: "to say a list of things quickly and easily from memory", example: "She reeled off the names of every capital city in Europe.", zh: "一口氣流利說出" },
    { front: "a war of words", pos: "idiom", def: "a prolonged angry public argument between two sides", example: "The two ministers have been locked in a war of words over the budget.", zh: "唇槍舌戰；口水戰" },
    { front: "drive a point home", pos: "idiom", def: "to make sure an argument is fully understood by stating it forcefully", example: "She used shocking statistics to drive her point home.", zh: "把論點講透；強調重點" },
    { front: "make a case for", pos: "collocation", def: "to give good reasons why something should be done", example: "The report makes a strong case for investing in renewable energy.", zh: "提出支持…的理由" },
    { front: "a bone of contention", pos: "idiom", def: "a subject that people continue to argue about", example: "The inheritance remained a bone of contention between the brothers for years.", zh: "爭論的焦點" },
    { front: "split hairs", pos: "idiom", def: "to argue about tiny, unimportant differences", example: "Whether it took five minutes or six is splitting hairs; either way we were late.", zh: "在枝微末節上爭論" },
    { front: "pick holes in", pos: "idiom", def: "to find faults in an argument or plan", example: "It is easy to pick holes in the proposal, but nobody has offered a better one.", zh: "挑…的毛病" },
    { front: "get a word in edgeways", pos: "idiom", def: "to manage to say something when someone else is talking constantly", example: "Once he starts on politics, nobody else can get a word in edgeways.", zh: "（在別人滔滔不絕時）插上話" },
    { front: "have the last word", pos: "idiom", def: "to make the final statement in an argument, appearing to win it", example: "She always has to have the last word, even when she knows she is wrong.", zh: "說最後一句話；爭到最後" },
    { front: "a slip of the tongue", pos: "idiom", def: "a small spoken mistake, saying something you did not intend", example: "Calling her by his ex's name was an unfortunate slip of the tongue.", zh: "口誤；說溜嘴" },
    { front: "set the record straight", pos: "idiom", def: "to correct a false account and tell people the truth", example: "The actor gave an interview to set the record straight about the rumours.", zh: "澄清事實" },
    { front: "in a nutshell", pos: "idiom", def: "expressed very briefly, in a few words", example: "In a nutshell, the project failed because of poor planning.", zh: "簡而言之" },
    { front: "stick to your guns", pos: "idiom", def: "to refuse to change your opinion despite pressure", example: "Everyone told her to drop the case, but she stuck to her guns.", zh: "堅持立場；不讓步" },
    /* === Adjectives of evaluation & degree === */
    { front: "commendable", pos: "adj.", def: "deserving praise and approval", example: "The staff showed commendable patience with the frustrated passengers.", zh: "值得讚揚的" },
    { front: "exemplary", pos: "adj.", def: "extremely good and serving as a model for others", example: "Her conduct throughout the crisis was exemplary.", zh: "堪稱典範的" },
    { front: "impeccable", pos: "adj.", def: "perfect, without any faults", example: "He arrived in an impeccable suit and greeted everyone with impeccable manners.", zh: "無可挑剔的" },
    { front: "flawless", pos: "adj.", def: "with no mistakes or imperfections", example: "The pianist gave a flawless performance of an extremely demanding piece.", zh: "完美無瑕的" },
    { front: "laudable", pos: "adj.", def: "deserving praise, even if not entirely successful", example: "Reducing waste is a laudable aim, but the scheme is poorly designed.", zh: "值得稱許的" },
    { front: "substandard", pos: "adj.", def: "below the usual or required standard", example: "The flats were built with substandard materials and are already crumbling.", zh: "低於標準的" },
    { front: "shoddy", pos: "adj.", def: "badly and carelessly made or done", example: "Customers returned the shoes in droves, complaining of shoddy workmanship.", zh: "粗製濫造的" },
    { front: "abysmal", pos: "adj.", def: "extremely bad, of the lowest quality", example: "The team's abysmal performance saw them lose six matches in a row.", zh: "糟透的；極差的" },
    { front: "dismal", pos: "adj.", def: "very bad and causing a feeling of gloom or failure", example: "Ticket sales for the festival were dismal this year.", zh: "慘淡的；令人沮喪的" },
    { front: "dire", pos: "adj.", def: "extremely serious or terrible", example: "The refugees are living in dire conditions with little access to clean water.", zh: "極嚴重的；悲慘的" },
    { front: "atrocious", pos: "adj.", def: "shockingly bad or unpleasant", example: "We abandoned the picnic because the weather was atrocious.", zh: "糟糕透頂的" },
    { front: "deplorable", pos: "adj.", def: "very bad in a way that deserves strong moral condemnation", example: "Inspectors described the state of the prison as deplorable.", zh: "應受譴責的；惡劣的" },
    { front: "woeful", pos: "adj.", def: "very bad or seriously inadequate", example: "The inquiry exposed a woeful lack of oversight at the ministry.", zh: "糟糕的；嚴重不足的" },
    { front: "second-rate", pos: "adj.", def: "of inferior quality, not the best", example: "Why settle for a second-rate imitation when the original is available?", zh: "二流的；次等的" },
    { front: "overhyped", pos: "adj.", def: "promoted with far more excitement and praise than it deserves", example: "The overhyped gadget sold millions but disappointed almost everyone who bought it.", zh: "被過度吹捧的" },
    { front: "underrated", pos: "adj.", def: "better than most people believe or acknowledge", example: "She is one of the most underrated novelists of her generation.", zh: "被低估的" },
    { front: "phenomenal", pos: "adj.", def: "extraordinarily great or impressive", example: "The app has enjoyed phenomenal success since its launch.", zh: "驚人的；非凡的" },
    { front: "staggering", pos: "adj.", def: "so large or surprising that it is difficult to believe", example: "The renovation cost a staggering forty million pounds.", zh: "驚人的；令人咋舌的" },
    { front: "monumental", pos: "adj.", def: "extremely large, important or serious", example: "Digitising the entire archive was a monumental task.", zh: "巨大的；意義重大的" },
    { front: "colossal", pos: "adj.", def: "extremely large in size, amount or degree", example: "The project was abandoned after running up colossal debts.", zh: "巨大的" },
    { front: "paltry", pos: "adj.", def: "too small to be considered important or useful", example: "The workers rejected the paltry two per cent pay rise.", zh: "微不足道的" },
    { front: "meagre", pos: "adj.", def: "smaller or less than is needed or expected", example: "They survived the winter on meagre rations of rice and beans.", zh: "微薄的；不足的" },
    { front: "minuscule", pos: "adj.", def: "extremely small", example: "The chances of winning the jackpot are minuscule.", zh: "極小的" },
    { front: "marginal", pos: "adj.", def: "very small in amount or effect", example: "The new engine offers only a marginal improvement in fuel efficiency.", zh: "微小的；邊際的" },
    { front: "sizeable", pos: "adj.", def: "fairly large in amount or extent", example: "A sizeable proportion of the budget goes on administration alone.", zh: "相當大的" },
    { front: "copious", pos: "adj.", def: "in very large amounts", example: "She took copious notes during every lecture.", zh: "大量的" },
    { front: "ample", pos: "adj.", def: "more than enough", example: "There is ample evidence that the drug is safe and effective.", zh: "充足的" },
    { front: "undue", pos: "adj.", def: "more than is necessary, reasonable or acceptable", example: "The report was published without undue delay.", zh: "過度的；不適當的" },
    { front: "disproportionate", pos: "adj.", def: "too large or too small in comparison with something else", example: "The punishment seems wholly disproportionate to the offence.", zh: "不成比例的" },
    { front: "inordinate", pos: "adj.", def: "far more than is usual or expected", example: "He spends an inordinate amount of time polishing his car.", zh: "過度的；異常多的" },
    { front: "utter", pos: "adj.", def: "complete or total, used for emphasis", example: "The rehearsal was an utter disaster from start to finish.", zh: "完全的；十足的" },
    { front: "sheer", pos: "adj.", def: "used to emphasise the pure or complete nature of something", example: "It was sheer luck that anyone survived the crash.", zh: "純粹的；全然的" },
    { front: "downright", pos: "adv.", def: "completely or thoroughly, used to emphasise something negative", example: "His comments were not just tactless; they were downright insulting.", zh: "徹頭徹尾地；簡直" },
    { front: "outright", pos: "adj.", def: "complete, total and immediate", example: "Campaigners are demanding an outright ban on the pesticide.", zh: "完全的；徹底的" },
    { front: "middling", pos: "adj.", def: "average in quality or ability, neither good nor bad", example: "The film received middling reviews and quickly disappeared from cinemas.", zh: "中等的；平庸的" },
    { front: "passable", pos: "adj.", def: "acceptable but not particularly good", example: "He speaks passable French, enough to order dinner and ask directions.", zh: "尚可的；過得去的" },
    { front: "top-notch", pos: "adj.", def: "of the highest quality", example: "The hotel is expensive, but the service is absolutely top-notch.", zh: "一流的" },
    { front: "unrivalled", pos: "adj.", def: "better than everything else of the same kind", example: "The museum houses an unrivalled collection of Renaissance drawings.", zh: "無與倫比的" },
    { front: "unparalleled", pos: "adj.", def: "having no equal; greater than anything else", example: "The pandemic caused disruption on an unparalleled scale.", zh: "空前的；無可比擬的" },
    { front: "stellar", pos: "adj.", def: "of exceptionally high quality or standard", example: "She has had a stellar career, winning every major award in her field.", zh: "傑出的；出色的" },
    { front: "uninspiring", pos: "adj.", def: "dull and failing to create interest or enthusiasm", example: "The candidates gave uniformly uninspiring answers at the debate.", zh: "乏味的；平淡無奇的" },
    { front: "unremarkable", pos: "adj.", def: "ordinary and not worth special attention", example: "It was an unremarkable building on an unremarkable street, easy to walk past.", zh: "平凡的；不起眼的" },
    { front: "blatant", pos: "adj.", def: "done openly and without shame, in a way that is very obvious", example: "The referee somehow missed a blatant foul in the penalty area.", zh: "明目張膽的" },
    { front: "flagrant", pos: "adj.", def: "shockingly obvious and offensive, especially of a wrongdoing", example: "The invasion was a flagrant violation of international law.", zh: "公然的；罪惡昭彰的" },
    { front: "glaring", pos: "adj.", def: "very obvious and impossible to ignore, especially a fault", example: "The report contains several glaring errors in its calculations.", zh: "顯眼的；明顯的（錯誤）" },
    { front: "utterly", pos: "adv.", def: "completely, to an extreme degree", example: "I was utterly exhausted after the twelve-hour flight.", zh: "完全地；徹底地" },
    { front: "exceedingly", pos: "adv.", def: "extremely, to a very great degree", example: "The instructions were exceedingly difficult to follow.", zh: "極其；非常" },
    { front: "markedly", pos: "adv.", def: "in a way that is very noticeable", example: "Attitudes towards remote working have changed markedly since the pandemic.", zh: "顯著地" },
    { front: "profoundly", pos: "adv.", def: "very greatly; in a deep and serious way", example: "The experience of living abroad profoundly changed her outlook.", zh: "深深地；深刻地" },
    { front: "vastly", pos: "adv.", def: "to a very great extent", example: "The new system is vastly superior to the one it replaced.", zh: "極大地；大大地" },
    { front: "measure up", pos: "phr. v.", def: "to be good enough or reach the required standard", example: "The new recruit simply failed to measure up, and was let go after a month.", zh: "達到標準；夠格" },
    { front: "stack up", pos: "phr. v.", def: "to compare in quality with something else", example: "How does the budget model stack up against its premium rivals?", zh: "（與…）相比；比得上" },
    { front: "fall short of", pos: "phr. v.", def: "to fail to reach a desired standard or target", example: "Sales fell well short of the company's ambitious forecasts.", zh: "未達到（標準、目標）" },
    { front: "second to none", pos: "idiom", def: "as good as or better than anything else", example: "When it comes to reliability, their after-sales service is second to none.", zh: "首屈一指的" },
    { front: "out of this world", pos: "idiom", def: "extremely good, wonderful", example: "The dessert was out of this world; I ordered a second one immediately.", zh: "好得不得了" },
    { front: "up to scratch", pos: "idiom", def: "reaching an acceptable standard", example: "Half the essays simply were not up to scratch and had to be rewritten.", zh: "達到水準" },
    { front: "a cut above", pos: "idiom", def: "noticeably better than others of the same kind", example: "Her documentaries are a cut above the usual celebrity-driven fare.", zh: "高人一等；略勝一籌" },
    { front: "beyond reproach", pos: "idiom", def: "perfect and impossible to criticise", example: "As a public servant, his integrity was always beyond reproach.", zh: "無可指責的" },
    { front: "leave a lot to be desired", pos: "idiom", def: "to be much worse than it should be", example: "The food was decent, but the service left a lot to be desired.", zh: "還有很大改進空間；不盡理想" },
    { front: "nothing to write home about", pos: "idiom", def: "ordinary, not especially good or exciting", example: "The hotel was clean enough, but the view was nothing to write home about.", zh: "不足掛齒；平平無奇" },
    { front: "par for the course", pos: "idiom", def: "what is normal or expected in a situation, usually something bad", example: "Long delays are par for the course when you fly during the holidays.", zh: "司空見慣；意料之中" },
    { front: "over the top", pos: "idiom", def: "too extreme or exaggerated", example: "The decorations were fun, but the fireworks felt a bit over the top.", zh: "過火的；太誇張的" },
    { front: "few and far between", pos: "idiom", def: "rare and not happening often", example: "Affordable flats in this part of the city are few and far between.", zh: "寥寥無幾；稀少" },
    { front: "far and away", pos: "idiom", def: "by a very great amount; without any doubt", example: "She is far and away the most experienced candidate on the shortlist.", zh: "顯然；遙遙領先地" },
    { front: "a far cry from", pos: "idiom", def: "very different from something, usually much worse or better", example: "The cramped studio was a far cry from the mansion he grew up in.", zh: "與…相去甚遠" },
    { front: "pale in comparison", pos: "idiom", def: "to seem much less important or impressive when compared to something else", example: "Our problems pale in comparison with what the flood victims are facing.", zh: "相形見絀" },
    /* === Time, change & trends === */
    { front: "plummet", pos: "v.", def: "to fall suddenly and steeply in value or amount", example: "Share prices plummeted when the fraud was made public.", zh: "暴跌；驟降" },
    { front: "soar", pos: "v.", def: "to rise very quickly to a high level", example: "Energy bills soared during the coldest winter in decades.", zh: "飆升" },
    { front: "surge", pos: "v.", def: "to increase suddenly and strongly", example: "Demand for air conditioners surged during the heatwave.", zh: "激增" },
    { front: "skyrocket", pos: "v.", def: "to rise extremely quickly to a very high level", example: "Rents in the city centre have skyrocketed over the past five years.", zh: "急遽上漲" },
    { front: "stagnate", pos: "v.", def: "to stop developing or growing", example: "Wages have stagnated while the cost of living keeps climbing.", zh: "停滯不前" },
    { front: "wane", pos: "v.", def: "to become gradually weaker or less", example: "Public enthusiasm for the project waned as costs mounted.", zh: "衰退；減弱" },
    { front: "subside", pos: "v.", def: "to become less intense or return to a normal level", example: "The flood waters finally subsided after three days of dry weather.", zh: "消退；平息" },
    { front: "abate", pos: "v.", def: "to become less strong or severe", example: "The controversy showed no signs of abating even weeks later.", zh: "減弱；緩和" },
    { front: "resurgence", pos: "n.", def: "the return and growth of something after a period of decline", example: "The city has seen a resurgence of interest in traditional crafts.", zh: "復甦；再起" },
    { front: "revamp", pos: "v.", def: "to change and improve the form or structure of something", example: "The airline is revamping its ageing fleet and outdated booking system.", zh: "翻新；改造" },
    { front: "upheaval", pos: "n.", def: "a sudden great change causing confusion or disruption", example: "Moving abroad involved enormous upheaval for the whole family.", zh: "劇變；動盪" },
    { front: "transition", pos: "n.", def: "the process of changing from one state or condition to another", example: "The transition from print to digital publishing was far from smooth.", zh: "轉變；過渡" },
    { front: "flux", pos: "n.", def: "a state of continuous change and instability", example: "With three managers in two years, the club has been in constant flux.", zh: "不斷變動的狀態" },
    { front: "watershed", pos: "n.", def: "an event marking an important change of direction", example: "The verdict was a watershed in the fight for equal pay.", zh: "分水嶺；轉捩點" },
    { front: "incremental", pos: "adj.", def: "happening in a series of small gradual steps", example: "Progress on emissions has been incremental rather than dramatic.", zh: "漸進的" },
    { front: "exponential", pos: "adj.", def: "increasing faster and faster over time", example: "The platform experienced exponential growth in its first two years.", zh: "指數型（成長）的" },
    { front: "imminent", pos: "adj.", def: "about to happen very soon", example: "Dark clouds warned of an imminent storm.", zh: "迫在眉睫的" },
    { front: "impending", pos: "adj.", def: "about to happen soon, usually something unpleasant", example: "Staff were kept in the dark about the impending redundancies.", zh: "即將發生的（多指壞事）" },
    { front: "interim", pos: "adj.", def: "temporary and intended to be used until something permanent exists", example: "An interim government will run the country until fresh elections are held.", zh: "臨時的；過渡的" },
    { front: "transient", pos: "adj.", def: "lasting only a short time; passing quickly", example: "Fame on social media is often transient, vanishing as quickly as it arrives.", zh: "短暫的；轉瞬即逝的" },
    { front: "fleeting", pos: "adj.", def: "lasting for only a very brief moment", example: "I caught a fleeting glimpse of the deer before it vanished into the trees.", zh: "飛逝的；短暫的" },
    { front: "short-lived", pos: "adj.", def: "lasting only a short time", example: "Their joy was short-lived, as the decision was overturned a week later.", zh: "曇花一現的；為時短暫的" },
    { front: "incessant", pos: "adj.", def: "continuing without stopping, especially something unpleasant", example: "The incessant rain turned the festival grounds into a swamp.", zh: "不停的；無休止的" },
    { front: "intermittent", pos: "adj.", def: "stopping and starting repeatedly at irregular intervals", example: "The forecast promises sunshine with intermittent showers.", zh: "斷斷續續的" },
    { front: "sporadic", pos: "adj.", def: "happening occasionally and irregularly", example: "Sporadic protests continued in the capital throughout the summer.", zh: "零星的；偶發的" },
    { front: "overdue", pos: "adj.", def: "not done or happening by the expected time; needed for a long time", example: "This reform is long overdue; experts have demanded it for twenty years.", zh: "逾期的；早該實行的" },
    { front: "premature", pos: "adj.", def: "happening or done too soon, before the proper time", example: "Celebrations proved premature when the result was suddenly overturned.", zh: "過早的" },
    { front: "newfound", pos: "adj.", def: "recently discovered or acquired", example: "He spoke openly about his newfound confidence after therapy.", zh: "新獲得的" },
    { front: "burgeoning", pos: "adj.", def: "growing or developing quickly", example: "The city's burgeoning tech scene is attracting talent from across the region.", zh: "迅速發展的" },
    { front: "prevalent", pos: "adj.", def: "existing commonly or happening frequently in a place or time", example: "Smartphone addiction is increasingly prevalent among teenagers.", zh: "盛行的；普遍的" },
    { front: "pervasive", pos: "adj.", def: "spreading through every part of something", example: "A pervasive sense of unease hung over the office after the layoffs.", zh: "無處不在的；瀰漫的" },
    { front: "rebound", pos: "v.", def: "to recover and rise again after falling", example: "Tourism rebounded strongly once travel restrictions were lifted.", zh: "反彈；回升" },
    { front: "slacken off", pos: "phr. v.", def: "to become slower or less intense", example: "Demand usually slackens off once the holiday season ends.", zh: "減緩；鬆弛下來" },
    { front: "ebb away", pos: "phr. v.", def: "to gradually disappear or become weaker", example: "As the years passed, his hopes of promotion slowly ebbed away.", zh: "逐漸消逝" },
    { front: "rally", pos: "v.", def: "to recover strength or value after a difficult period", example: "The currency rallied after the central bank raised interest rates.", zh: "回升；重振" },
    { front: "creep up", pos: "phr. v.", def: "to increase slowly and gradually, often unnoticed", example: "Prices have been creeping up steadily all year.", zh: "緩慢上升" },
    { front: "shoot up", pos: "phr. v.", def: "to increase very quickly and suddenly", example: "Applications shot up after the university scrapped its fees.", zh: "猛增；暴漲" },
    { front: "drop away", pos: "phr. v.", def: "to become gradually smaller in number or amount", example: "Support for the strike dropped away as the weeks passed.", zh: "逐漸減少" },
    { front: "wither away", pos: "phr. v.", def: "to gradually become weaker until it disappears", example: "Without new members, the once-thriving club slowly withered away.", zh: "逐漸衰亡；枯萎消失" },
    { front: "fizzle out", pos: "phr. v.", def: "to end weakly or in disappointment after a promising start", example: "Their romance fizzled out once the summer was over.", zh: "虎頭蛇尾地結束" },
    { front: "wear on", pos: "phr. v.", def: "to pass slowly, used about time", example: "As the evening wore on, the guests gradually drifted home.", zh: "（時間）緩慢流逝" },
    { front: "drag on", pos: "phr. v.", def: "to continue for longer than necessary or expected", example: "The legal battle dragged on for the best part of a decade.", zh: "拖延；持續過久" },
    { front: "slip by", pos: "phr. v.", def: "to pass quickly and almost unnoticed, used about time or chances", example: "The deadline slipped by before anyone remembered the paperwork.", zh: "（時間）不知不覺流逝" },
    { front: "push back", pos: "phr. v.", def: "to delay something to a later time or date", example: "The launch has been pushed back to the autumn.", zh: "延後" },
    { front: "bring forward", pos: "phr. v.", def: "to move an event to an earlier time or date", example: "The meeting was brought forward to Tuesday because of the holiday.", zh: "提前" },
    { front: "drag out", pos: "phr. v.", def: "to make something last longer than necessary", example: "There is no point dragging out the negotiations any further.", zh: "拖長；使拖延" },
    { front: "die away", pos: "phr. v.", def: "to become gradually fainter until it disappears", example: "The applause slowly died away as the lights dimmed.", zh: "（聲音等）逐漸消失" },
    { front: "set back", pos: "phr. v.", def: "to delay the progress of something", example: "The fire set back construction by at least six months.", zh: "使延誤；阻礙" },
    { front: "creep in", pos: "phr. v.", def: "to begin to appear or happen gradually and unnoticed", example: "Careless mistakes started to creep in as the team grew tired.", zh: "悄悄出現" },
    { front: "edge up", pos: "phr. v.", def: "to increase slowly by small amounts", example: "Unemployment edged up slightly for the third consecutive month.", zh: "小幅上升" },
    { front: "fall off", pos: "phr. v.", def: "to decrease in amount, quality or intensity", example: "Demand for printed newspapers has fallen off dramatically.", zh: "下降；減少" },
    { front: "carry over", pos: "phr. v.", def: "to continue to exist or apply in a new situation or later period", example: "Unused holiday days can be carried over into the following year.", zh: "延續；結轉" },
    { front: "put back", pos: "phr. v.", def: "to delay an event until a later time", example: "The concert has been put back a week because the singer is unwell.", zh: "延期" },
    { front: "hold out", pos: "phr. v.", def: "to last or continue to be enough; to continue resisting", example: "Supplies will only hold out for another few days.", zh: "維持；撐住" },
    { front: "in the foreseeable future", pos: "collocation", def: "for as far ahead in time as we can predict", example: "Petrol cars will remain common in the foreseeable future.", zh: "在可預見的未來" },
    { front: "an emerging trend", pos: "collocation", def: "a pattern of behaviour or development that is starting to appear", example: "Remote-first hiring is an emerging trend among tech start-ups.", zh: "新興趨勢" },
    { front: "a downward spiral", pos: "collocation", def: "a situation that keeps getting worse, with each problem causing another", example: "After losing his job he fell into a downward spiral of debt and depression.", zh: "惡性循環；每況愈下" },
    { front: "gather pace", pos: "collocation", def: "to develop or happen increasingly quickly", example: "The campaign for electoral reform is gathering pace across the country.", zh: "加快步伐；勢頭漸強" },
    { front: "gain traction", pos: "collocation", def: "to gradually become more popular or accepted", example: "The idea of a four-day week is gaining traction among employers.", zh: "逐漸獲得支持、流行" },
    { front: "a sign of the times", pos: "idiom", def: "something typical of the way things are now, often something bad", example: "Shops closing on every high street is a sad sign of the times.", zh: "時代的縮影、寫照" },
    { front: "in this day and age", pos: "idiom", def: "in the modern period, now", example: "In this day and age, there is no excuse for such outdated attitudes.", zh: "在當今時代" },
    { front: "behind the times", pos: "idiom", def: "old-fashioned and not aware of modern developments", example: "Their booking system is hopelessly behind the times.", zh: "跟不上時代的" },
    { front: "the shape of things to come", pos: "idiom", def: "a sign of how things will develop in the future", example: "Driverless delivery vans in the city centre are the shape of things to come.", zh: "未來的預兆；事情發展的雛形" },
    { front: "a sea change", pos: "idiom", def: "a complete and profound transformation", example: "There has been a sea change in public attitudes towards mental health.", zh: "巨變；根本轉變" },
    { front: "on the horizon", pos: "idiom", def: "likely to happen or appear soon", example: "With new treatments on the horizon, doctors are cautiously optimistic.", zh: "即將來臨的" },
    { front: "here to stay", pos: "idiom", def: "permanently established and unlikely to disappear", example: "Whether we like it or not, remote working is here to stay.", zh: "將長久存在" },
    { front: "at a crossroads", pos: "idiom", def: "at a point where an important decision about the future must be made", example: "After a decade in banking, she found herself at a crossroads in her career.", zh: "處於十字路口；面臨抉擇" },
    { front: "wax and wane", pos: "idiom", def: "to increase and decrease repeatedly over time", example: "His enthusiasm for the project waxed and waned over the years.", zh: "盛衰起伏；時強時弱" },
    /* === Social behaviour & etiquette === */
    { front: "etiquette", pos: "n.", def: "the set of rules about polite behaviour in a society or group", example: "Business etiquette in Japan places great importance on exchanging cards properly.", zh: "禮儀；禮節" },
    { front: "decorum", pos: "n.", def: "dignified, socially correct behaviour", example: "The ceremony was conducted with the utmost decorum.", zh: "端莊得體的舉止" },
    { front: "courteous", pos: "adj.", def: "polite and showing respect for others", example: "The staff were unfailingly courteous, even to the rudest customers.", zh: "彬彬有禮的" },
    { front: "tactless", pos: "adj.", def: "carelessly saying things that upset or embarrass people", example: "Asking about her divorce at the dinner party was spectacularly tactless.", zh: "不得體的；不圓滑的" },
    { front: "abrasive", pos: "adj.", def: "rude and unkind in manner, causing offence", example: "His abrasive management style drove several talented employees away.", zh: "粗魯無禮的；令人不快的" },
    { front: "boorish", pos: "adj.", def: "rude, insensitive and ill-mannered", example: "His boorish jokes embarrassed everyone at the table.", zh: "粗野無禮的" },
    { front: "uncouth", pos: "adj.", def: "lacking good manners and refinement", example: "She considered eating with your elbows on the table rather uncouth.", zh: "粗俗的；沒教養的" },
    { front: "unruly", pos: "adj.", def: "difficult to control; behaving in a disorderly way", example: "The teacher struggled to manage the unruly class.", zh: "不守規矩的；難管束的" },
    { front: "impertinent", pos: "adj.", def: "rude and not showing proper respect, especially to someone older or senior", example: "The interviewer apologised for what might seem an impertinent question.", zh: "無禮的；冒失的" },
    { front: "deferential", pos: "adj.", def: "polite and showing respect for someone's status or authority", example: "The junior staff were almost embarrassingly deferential to the chairman.", zh: "恭敬的" },
    { front: "gracious", pos: "adj.", def: "polite, kind and generous, especially towards people of lower status", example: "She was gracious in defeat, warmly congratulating her opponent.", zh: "親切有風度的" },
    { front: "hospitable", pos: "adj.", def: "friendly and generous to guests and visitors", example: "The villagers were remarkably hospitable, insisting we stay for dinner.", zh: "好客的" },
    { front: "amicable", pos: "adj.", def: "done in a friendly way, without argument, especially when ending something", example: "The couple reached an amicable settlement over the house.", zh: "友好的；和睦的" },
    { front: "cordial", pos: "adj.", def: "friendly and polite, though often somewhat formal", example: "Despite their rivalry, relations between the two firms remained cordial.", zh: "熱誠友好的" },
    { front: "obliging", pos: "adj.", def: "willing and eager to help others", example: "The obliging concierge arranged tickets, taxis and even a birthday cake.", zh: "樂於助人的" },
    { front: "accommodating", pos: "adj.", def: "willing to adjust to fit in with the wishes of others", example: "The hotel was very accommodating about our late check-out request.", zh: "通融的；肯遷就的" },
    { front: "unassuming", pos: "adj.", def: "modest and not wanting attention", example: "Despite his fame, he remained an unassuming man who queued like everyone else.", zh: "謙遜低調的" },
    { front: "pretentious", pos: "adj.", def: "trying to appear more important, intelligent or cultured than you are", example: "The menu was full of pretentious descriptions for very ordinary dishes.", zh: "自命不凡的；做作的" },
    { front: "snobbish", pos: "adj.", def: "believing you are better than people of a lower social class", example: "She was too snobbish to shop anywhere but the most exclusive boutiques.", zh: "勢利的" },
    { front: "snub", pos: "v.", def: "to insult someone deliberately by ignoring them", example: "He felt snubbed when his old colleagues held a reunion without him.", zh: "冷落；怠慢" },
    { front: "shun", pos: "v.", def: "to deliberately avoid someone or something", example: "After the scandal, he was shunned by former friends and colleagues alike.", zh: "迴避；排斥" },
    { front: "ostracise", pos: "v.", def: "to exclude someone from a group as a punishment", example: "Villagers who broke the unwritten rules were ostracised by the community.", zh: "排擠；放逐" },
    { front: "antagonise", pos: "v.", def: "to make someone feel angry or hostile towards you", example: "There is no point antagonising the neighbours over such a trivial matter.", zh: "激怒；使產生敵意" },
    { front: "affront", pos: "n.", def: "a remark or action that openly insults or offends someone", example: "He took the seating arrangement as a personal affront.", zh: "公然冒犯；侮辱" },
    { front: "faux pas", pos: "n.", def: "an embarrassing social mistake", example: "Turning up in jeans to a black-tie dinner was an obvious faux pas.", zh: "失禮；社交失態" },
    { front: "gaffe", pos: "n.", def: "an embarrassing public mistake, especially in speech", example: "The minister's latest gaffe dominated the morning headlines.", zh: "（公開場合的）失言、出醜" },
    { front: "mingle", pos: "v.", def: "to move around and talk to different people at a social event", example: "The host encouraged everyone to mingle before dinner was served.", zh: "（社交場合）走動交談" },
    { front: "gatecrash", pos: "v.", def: "to attend a party or event without being invited", example: "A group of students gatecrashed the wedding reception.", zh: "不請自來；闖入（派對）" },
    { front: "protocol", pos: "n.", def: "the accepted system of rules for formal behaviour or official occasions", example: "Strict protocol dictates who greets the visiting head of state first.", zh: "禮賓規範；正式禮節" },
    { front: "taboo", pos: "n.", def: "a subject or behaviour that a culture forbids or avoids discussing", example: "In many workplaces, discussing salaries remains something of a taboo.", zh: "禁忌" },
    { front: "frown upon", pos: "phr. v.", def: "to disapprove of something, often without saying so directly", example: "Arriving empty-handed to a dinner party is generally frowned upon.", zh: "不贊成；看不慣" },
    { front: "fit in", pos: "phr. v.", def: "to be accepted by a group because you are similar to them", example: "It took months before the new student really fitted in at school.", zh: "融入（群體）" },
    { front: "blend in", pos: "phr. v.", def: "to look or behave like those around you so as not to stand out", example: "He dressed plainly, hoping to blend in with the locals.", zh: "融入環境；不引人注意" },
    { front: "butter up", pos: "phr. v.", def: "to flatter someone in order to get something from them", example: "He spent the whole lunch buttering up the client before mentioning the price rise.", zh: "奉承；拍馬屁" },
    { front: "drop in on", pos: "phr. v.", def: "to visit someone informally without arranging it beforehand", example: "We dropped in on my aunt on the way back from the coast.", zh: "順道拜訪" },
    { front: "take to", pos: "phr. v.", def: "to begin to like someone or something quickly", example: "The children took to their new neighbour immediately.", zh: "很快喜歡上" },
    { front: "storm out", pos: "phr. v.", def: "to leave a place angrily and dramatically", example: "She stormed out of the meeting after her proposal was ridiculed.", zh: "憤然離場" },
    { front: "tag along", pos: "phr. v.", def: "to go somewhere with someone, often without being invited", example: "Do you mind if my little brother tags along to the cinema?", zh: "跟著去；尾隨" },
    { front: "hang back", pos: "phr. v.", def: "to stay behind or hesitate to join in because of shyness", example: "While the others introduced themselves, he hung back by the door.", zh: "退縮不前；躊躇" },
    { front: "let your hair down", pos: "idiom", def: "to relax completely and enjoy yourself, forgetting formality", example: "The conference is over, so tonight everyone can let their hair down.", zh: "徹底放鬆；盡情享樂" },
    { front: "lighten up", pos: "phr. v.", def: "to become less serious and more relaxed about something", example: "Lighten up! It was only a joke.", zh: "別太嚴肅；放輕鬆" },
    { front: "play along", pos: "phr. v.", def: "to pretend to agree or cooperate to avoid trouble or keep a secret", example: "I did not believe his story, but I played along to see where it would lead.", zh: "假意配合" },
    { front: "go along with", pos: "phr. v.", def: "to accept or agree with a plan or opinion, sometimes reluctantly", example: "She had doubts about the scheme but went along with it to keep the peace.", zh: "附和；順從" },
    { front: "smooth over", pos: "phr. v.", def: "to make a disagreement or problem seem less serious", example: "He apologised quickly, hoping to smooth over the awkward moment.", zh: "緩和；平息（尷尬、爭執）" },
    { front: "muscle in", pos: "phr. v.", def: "to force your way into a situation where you are not wanted", example: "Bigger firms are trying to muscle in on the local delivery market.", zh: "強行介入；硬擠進" },
    { front: "cosy up to", pos: "phr. v.", def: "to try to become friendly with someone to gain an advantage", example: "Critics accused the paper of cosying up to the government.", zh: "巴結；套近乎" },
    { front: "fawn over", pos: "phr. v.", def: "to praise or give attention to someone excessively to please them", example: "The assistants fawned over the celebrity from the moment she arrived.", zh: "諂媚；曲意逢迎" },
    { front: "ask after", pos: "phr. v.", def: "to ask for news about someone, especially their health", example: "Your grandmother was asking after you at the party.", zh: "問候；探問（某人近況）" },
    { front: "fall in with", pos: "phr. v.", def: "to begin to associate with a group, often a bad one; to agree to a plan", example: "At university he fell in with a crowd who rarely attended lectures.", zh: "結交（一群人）；同意" },
    { front: "look in on", pos: "phr. v.", def: "to make a short visit to check that someone is well", example: "Could you look in on the neighbours while they are recovering?", zh: "順便探望" },
    { front: "chat up", pos: "phr. v.", def: "to talk to someone in a flirtatious way to show romantic interest", example: "He spent the evening trying to chat up the woman at the bar.", zh: "搭訕" },
    { front: "mind your Ps and Qs", pos: "idiom", def: "to be careful to behave politely and avoid offending anyone", example: "Mind your Ps and Qs at the dinner; his parents are very traditional.", zh: "謹言慎行；注意禮貌" },
    { front: "make small talk", pos: "collocation", def: "to have polite conversation about unimportant subjects", example: "He hates making small talk at networking events.", zh: "寒暄；閒聊" },
    { front: "overstay your welcome", pos: "idiom", def: "to stay somewhere longer than your hosts would like", example: "We left before midnight, not wanting to overstay our welcome.", zh: "逗留過久惹人嫌" },
    { front: "the done thing", pos: "idiom", def: "behaviour that is socially acceptable or expected", example: "In those days, it simply was not the done thing to discuss money openly.", zh: "合乎禮俗的行為" },
    { front: "social graces", pos: "collocation", def: "the polite skills and behaviour needed in social situations", example: "Charming and witty, he possessed all the social graces.", zh: "社交禮儀；應對進退" },
    { front: "a social climber", pos: "collocation", def: "someone who tries to gain higher social status by befriending important people", example: "She dismissed him as a social climber who only valued useful friendships.", zh: "攀附權貴者" },
    { front: "keep up appearances", pos: "idiom", def: "to hide problems and pretend everything is fine to maintain your image", example: "Although deep in debt, they kept up appearances with lavish parties.", zh: "維持體面；打腫臉充胖子" },
    { front: "put on airs", pos: "idiom", def: "to behave as if you are more important than you really are", example: "Success never changed her; she refuses to put on airs.", zh: "擺架子；裝腔作勢" },
    { front: "stand on ceremony", pos: "idiom", def: "to behave in a formal way", example: "Please sit anywhere; we don't stand on ceremony in this house.", zh: "拘泥於禮節" },
    { front: "in someone's good books", pos: "idiom", def: "having someone's approval or favour", example: "Washing the dishes every night kept him in his landlady's good books.", zh: "受某人青睞" },
    { front: "rub shoulders with", pos: "idiom", def: "to meet and spend time with famous or important people", example: "As a journalist she rubbed shoulders with ministers and film stars.", zh: "與（名流）交往、接觸" },
    { front: "on first-name terms", pos: "idiom", def: "knowing someone well enough to call them by their first name", example: "He is on first-name terms with half the town council.", zh: "熟到直呼其名的交情" },
    { front: "clear the air", pos: "idiom", def: "to discuss a problem openly in order to end bad feeling", example: "After weeks of tension, the two finally met to clear the air.", zh: "消除隔閡；把話說開" },
    { front: "get off on the wrong foot", pos: "idiom", def: "to start a relationship badly", example: "We got off on the wrong foot, but we are good friends now.", zh: "一開始就不順利；起步失和" },
    /* === Abstract nouns of quality === */
    { front: "integrity", pos: "n.", def: "the quality of being honest and having strong moral principles", example: "Nobody ever questioned the judge's integrity in forty years on the bench.", zh: "正直；誠信" },
    { front: "humility", pos: "n.", def: "the quality of not thinking you are better than others; modesty", example: "She accepted the award with characteristic humility, praising her whole team.", zh: "謙遜" },
    { front: "audacity", pos: "n.", def: "boldness or daring, often shocking in its rudeness", example: "He had the audacity to demand a refund for a meal he had entirely eaten.", zh: "大膽；厚顏" },
    { front: "candour", pos: "n.", def: "the quality of being open and honest, even about difficult matters", example: "With surprising candour, the CEO admitted the strategy had failed.", zh: "坦率；直言不諱" },
    { front: "prudence", pos: "n.", def: "careful good judgement that avoids unnecessary risks", example: "Financial prudence during the boom years saved the firm in the recession.", zh: "審慎" },
    { front: "discretion", pos: "n.", def: "the ability to keep sensitive information secret; careful judgement", example: "As a royal butler, absolute discretion was part of the job.", zh: "慎重；口風緊" },
    { front: "diligence", pos: "n.", def: "careful and persistent effort in your work", example: "Her diligence was rewarded with a scholarship to study abroad.", zh: "勤勉" },
    { front: "benevolence", pos: "n.", def: "kindness and generosity towards others", example: "The hospital wing was built thanks to the benevolence of an anonymous donor.", zh: "仁慈；善心" },
    { front: "malice", pos: "n.", def: "the desire to harm or hurt others", example: "The comment was thoughtless, but there was no malice behind it.", zh: "惡意" },
    { front: "resourcefulness", pos: "n.", def: "the ability to find quick, clever ways to overcome difficulties", example: "Stranded without tools, the hikers showed impressive resourcefulness.", zh: "隨機應變的能力" },
    { front: "hypocrisy", pos: "n.", def: "claiming to have moral standards that your own behaviour contradicts", example: "It is sheer hypocrisy to preach frugality while flying by private jet.", zh: "偽善" },
    { front: "altruism", pos: "n.", def: "unselfish concern for the well-being of others", example: "Pure altruism drove her to spend every weekend at the shelter.", zh: "利他主義；無私" },
    { front: "compassion", pos: "n.", def: "sympathy for the suffering of others, with a desire to help", example: "The nurses treated the dying man with extraordinary compassion.", zh: "憐憫；同情心" },
    { front: "decency", pos: "n.", def: "honest, polite behaviour that respects accepted moral standards", example: "He did not even have the decency to apologise for keeping us waiting.", zh: "正派；起碼的禮貌" },
    { front: "dignity", pos: "n.", def: "calm, serious behaviour that deserves respect", example: "She faced the hostile questions with quiet dignity.", zh: "尊嚴" },
    { front: "poise", pos: "n.", def: "calm, confident self-control in manner and behaviour", example: "The young pianist showed remarkable poise in front of the huge audience.", zh: "泰然自若；沉著" },
    { front: "aplomb", pos: "n.", def: "calm confidence, especially in a difficult situation", example: "She handled the hostile interview with remarkable aplomb.", zh: "沉著；泰然" },
    { front: "restraint", pos: "n.", def: "self-control that stops you acting on strong emotions", example: "The police were praised for showing restraint despite severe provocation.", zh: "克制" },
    { front: "tranquillity", pos: "n.", def: "a state of peaceful calm and quiet", example: "They moved to the countryside in search of tranquillity.", zh: "寧靜" },
    { front: "zeal", pos: "n.", def: "great energy and enthusiasm for a cause or aim", example: "The new inspector pursued tax evaders with missionary zeal.", zh: "熱忱；狂熱" },
    { front: "fervour", pos: "n.", def: "very strong and sincere feeling or enthusiasm", example: "The crowd sang the national anthem with patriotic fervour.", zh: "熱情；熱烈" },
    { front: "vigour", pos: "n.", def: "physical or mental strength and energy", example: "At seventy she still tackles the garden with astonishing vigour.", zh: "活力；精力" },
    { front: "gusto", pos: "n.", def: "energetic and enthusiastic enjoyment", example: "The choir launched into the final chorus with tremendous gusto.", zh: "興致勃勃" },
    { front: "acumen", pos: "n.", def: "the ability to make good judgements and quick decisions, especially in business", example: "Her legal acumen made her the obvious choice for the case.", zh: "敏銳的判斷力" },
    { front: "savvy", pos: "n.", def: "practical knowledge and good judgement in a particular area", example: "The campaign showed real political savvy in targeting undecided voters.", zh: "實務頭腦；精明" },
    { front: "foresight", pos: "n.", def: "the ability to predict what will happen and prepare for it", example: "Thanks to her foresight, the company had stockpiled parts before the shortage.", zh: "遠見" },
    { front: "hindsight", pos: "n.", def: "the understanding of a situation only after it has happened", example: "In hindsight, selling the house that year was a terrible mistake.", zh: "後見之明" },
    { front: "intuition", pos: "n.", def: "the ability to understand something instinctively without reasoning", example: "Her intuition told her something about the deal was not right.", zh: "直覺" },
    { front: "willpower", pos: "n.", def: "the mental strength to control your actions and resist temptation", example: "Giving up smoking took every ounce of willpower he possessed.", zh: "意志力" },
    { front: "resolve", pos: "n.", def: "strong determination to achieve something", example: "The setback only strengthened her resolve to qualify for the Olympics.", zh: "決心" },
    { front: "fortitude", pos: "n.", def: "courage and strength when facing pain or difficulty", example: "She bore the long illness with quiet fortitude.", zh: "堅忍" },
    { front: "bravado", pos: "n.", def: "a bold show of confidence intended to impress, often hiding fear", example: "His bravado vanished the moment the plane hit turbulence.", zh: "虛張聲勢" },
    { front: "folly", pos: "n.", def: "a foolish action or the quality of being foolish", example: "History judged the invasion to be an act of monumental folly.", zh: "愚蠢（的行為）" },
    { front: "complacency", pos: "n.", def: "a feeling of smug satisfaction that stops you seeing dangers", example: "The coach warned that complacency after two easy wins could cost them the title.", zh: "自滿；鬆懈" },
    { front: "indifference", pos: "n.", def: "a lack of interest or concern", example: "The proposal was met with complete indifference from the board.", zh: "漠不關心" },
    { front: "lethargy", pos: "n.", def: "a lack of energy and enthusiasm", example: "A heavy lunch and the summer heat plunged the office into lethargy.", zh: "無精打采；倦怠" },
    { front: "passivity", pos: "n.", def: "the tendency to accept what happens without acting or resisting", example: "Her passivity in meetings was often mistaken for agreement.", zh: "被動；消極" },
    { front: "legitimacy", pos: "n.", def: "the quality of being legal, acceptable or justifiable", example: "The disputed election undermined the legitimacy of the new government.", zh: "正當性；合法性" },
    { front: "transparency", pos: "n.", def: "openness that allows actions and decisions to be seen and checked", example: "Campaigners demand greater transparency in how public funds are spent.", zh: "透明度" },
    { front: "objectivity", pos: "n.", def: "the quality of judging fairly, without personal bias", example: "A journalist's objectivity is compromised by accepting gifts from sources.", zh: "客觀性" },
    { front: "bigotry", pos: "n.", def: "unreasonable and intolerant attachment to your own opinions or prejudices", example: "The organisation campaigns against bigotry in all its forms.", zh: "偏執；頑固的偏見" },
    { front: "solidarity", pos: "n.", def: "unity and mutual support within a group, especially in difficulty", example: "Workers across the industry went on strike in solidarity with the miners.", zh: "團結" },
    { front: "cohesion", pos: "n.", def: "the state of sticking together as a united whole", example: "Shared rituals help maintain social cohesion in the community.", zh: "凝聚力" },
    { front: "goodwill", pos: "n.", def: "friendly, helpful and cooperative feelings towards others", example: "The gesture generated enormous goodwill among the local residents.", zh: "善意；友好" },
    { front: "renown", pos: "n.", def: "the state of being famous and admired for an achievement", example: "The restaurant has won international renown for its tasting menu.", zh: "名望" },
    { front: "notoriety", pos: "n.", def: "fame for something bad", example: "The junction gained notoriety as the most dangerous crossing in the city.", zh: "惡名；聲名狼藉" },
    { front: "stigma", pos: "n.", def: "strong social disapproval attached to a circumstance or condition", example: "There is still a stigma surrounding mental illness in many workplaces.", zh: "汙名；恥辱" },
    { front: "deference", pos: "n.", def: "polite respect shown to someone because of their position or age", example: "The students treated the visiting professor with exaggerated deference.", zh: "敬重；順從" },
    { front: "subtlety", pos: "n.", def: "the quality of being delicate, precise and not obvious", example: "The film explores grief with great subtlety, never resorting to melodrama.", zh: "細膩；微妙之處" },
    { front: "nuance", pos: "n.", def: "a very slight difference in meaning, feeling or tone", example: "A good interpreter captures every nuance of the speaker's words.", zh: "細微差別" },
    { front: "a stroke of genius", pos: "idiom", def: "an exceptionally clever and original idea or action", example: "Moving the shop online just before lockdown was a stroke of genius.", zh: "神來之筆；天才之舉" },
    { front: "presence of mind", pos: "idiom", def: "the ability to stay calm and act sensibly in an emergency", example: "She had the presence of mind to grab the extinguisher before the fire spread.", zh: "臨危不亂；急中生智" },
    { front: "peace of mind", pos: "collocation", def: "a feeling of calm because you have no worries", example: "The extended warranty is expensive, but it buys you peace of mind.", zh: "安心；心安" },
    { front: "strength of character", pos: "collocation", def: "the inner quality of being determined, honest and reliable", example: "It took real strength of character to admit the error publicly.", zh: "堅毅的品格" },
    { front: "a sense of purpose", pos: "collocation", def: "a feeling that what you do is meaningful and directed at a goal", example: "Volunteering gave her a renewed sense of purpose after retirement.", zh: "使命感；目標感" },
    { front: "moral fibre", pos: "collocation", def: "the inner strength to do what is right", example: "He lacked the moral fibre to stand up to his corrupt colleagues.", zh: "道德勇氣；骨氣" },
    { front: "the moral high ground", pos: "idiom", def: "a position of moral superiority in an argument", example: "By refusing to insult her rival, she kept the moral high ground.", zh: "道德制高點" },
    { front: "with impunity", pos: "collocation", def: "without any risk of being punished", example: "For years the factory dumped waste into the river with impunity.", zh: "不受懲罰地；有恃無恐地" },
    { front: "a breach of trust", pos: "collocation", def: "an act that betrays the confidence someone has placed in you", example: "Reading her private diary was an unforgivable breach of trust.", zh: "背信；辜負信任" },
    { front: "a token gesture", pos: "collocation", def: "a small action done only for appearance, without real effect", example: "Critics dismissed the donation as a token gesture from a company facing scandal.", zh: "象徵性的表示" },
    { front: "a saving grace", pos: "idiom", def: "the one good quality that redeems something otherwise bad", example: "The film's saving grace is its spectacular cinematography.", zh: "可取之處；唯一的優點" },
    { front: "the benefit of the doubt", pos: "idiom", def: "a decision to believe someone even though you are not certain they are right", example: "It was his first mistake, so the manager gave him the benefit of the doubt.", zh: "姑且相信；無罪推定" },
    { front: "have the gall", pos: "idiom", def: "to have the rude boldness to do something offensive", example: "She had the gall to criticise my cooking after arriving two hours late.", zh: "厚著臉皮；竟敢" }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
