/* CAE Prep extra bank: vocab wave 2 */
(function () {
  var BANK = [
    // === Education & learning ===
    { front: "curriculum", pos: "n.", def: "the subjects and content taught at a school, college, or university", example: "The new curriculum places far greater emphasis on critical thinking than on memorisation.", zh: "課程（總體）" },
    { front: "syllabus", pos: "n.", def: "an outline of the topics covered in a particular course of study", example: "The professor handed out the syllabus in the first lecture so we knew what to expect each week.", zh: "教學大綱" },
    { front: "tuition", pos: "n.", def: "teaching or instruction, especially that paid for; also the fee for it", example: "Private tuition helped her close the gap in maths within a single term.", zh: "教學；學費" },
    { front: "dissertation", pos: "n.", def: "a long piece of academic writing based on original research, usually for a degree", example: "He spent his final year writing a dissertation on urban migration patterns.", zh: "學位論文" },
    { front: "plagiarism", pos: "n.", def: "the practice of using someone else's work or ideas and pretending they are your own", example: "The university expelled two students after software detected blatant plagiarism in their essays.", zh: "剽竊；抄襲" },
    { front: "literacy", pos: "n.", def: "the ability to read and write", example: "Adult literacy programmes have transformed employment prospects in the region.", zh: "識字能力；讀寫能力" },
    { front: "numeracy", pos: "n.", def: "the ability to understand and work with numbers", example: "Employers complain that school leavers often lack basic numeracy skills.", zh: "計算能力" },
    { front: "vocational", pos: "adj.", def: "relating to the skills needed for a particular job or trade", example: "She chose a vocational course in catering rather than a traditional academic route.", zh: "職業的；職業訓練的" },
    { front: "seminar", pos: "n.", def: "a class at university in which a small group discusses a topic with a tutor", example: "The weekly seminar gave students a chance to challenge the ideas raised in lectures.", zh: "研討課；專題討論" },
    { front: "undergraduate", pos: "n.", def: "a university student who has not yet taken a first degree", example: "As an undergraduate, she juggled two part-time jobs alongside her studies.", zh: "大學部學生" },
    { front: "postgraduate", pos: "adj.", def: "relating to study done after completing a first degree", example: "He is applying for postgraduate research funding in molecular biology.", zh: "研究所的；大學畢業後的" },
    { front: "faculty", pos: "n.", def: "a department or group of related departments in a university; the teaching staff", example: "The Faculty of Law is hosting a public lecture on constitutional reform.", zh: "（大學的）學院；全體教員" },
    { front: "enrolment", pos: "n.", def: "the act of officially registering to join a course or school", example: "Enrolment in evening language classes has doubled since the fees were reduced.", zh: "註冊；入學" },
    { front: "assessment", pos: "n.", def: "the process of testing and judging students' knowledge or ability", example: "The course relies on coursework rather than a single end-of-year assessment.", zh: "評量；評估" },
    { front: "comprehension", pos: "n.", def: "the ability to understand something fully", example: "The passage was so dense that it defied comprehension on a first reading.", zh: "理解；理解力" },
    { front: "retention", pos: "n.", def: "the ability to keep information in your memory", example: "Spaced repetition dramatically improves long-term retention of vocabulary.", zh: "記憶保持；保留" },
    { front: "cognitive", pos: "adj.", def: "connected with mental processes such as thinking, learning, and remembering", example: "Bilingual children often show enhanced cognitive flexibility.", zh: "認知的" },
    { front: "aptitude", pos: "n.", def: "a natural ability or talent for doing something", example: "The entrance test measures aptitude for abstract reasoning rather than learned knowledge.", zh: "天資；才能" },
    { front: "attainment", pos: "n.", def: "the level of success achieved, especially in education", example: "The report links low educational attainment to overcrowded classrooms.", zh: "成就；學業成績" },
    { front: "truancy", pos: "n.", def: "the practice of staying away from school without permission", example: "The council introduced fines for parents in an effort to curb truancy.", zh: "曠課；逃學" },
    { front: "expulsion", pos: "n.", def: "the act of forcing a student to leave a school permanently", example: "Repeated violent behaviour left the headteacher with no option but expulsion.", zh: "開除；驅逐" },
    { front: "pedagogy", pos: "n.", def: "the study and practice of methods of teaching", example: "Her research explores how digital tools are reshaping classroom pedagogy.", zh: "教學法；教育學" },
    { front: "rote", pos: "n.", def: "the process of memorising by repetition without real understanding", example: "Critics argue that learning by rote produces students who can recite but not reason.", zh: "死記硬背" },
    { front: "mentor", pos: "n.", def: "an experienced person who guides and advises someone less experienced", example: "A good mentor can shorten a new teacher's learning process by years.", zh: "導師；良師" },
    { front: "prodigy", pos: "n.", def: "a young person with exceptional talent or ability", example: "The twelve-year-old chess prodigy defeated three grandmasters in one weekend.", zh: "神童；奇才" },
    { front: "illiterate", pos: "adj.", def: "unable to read or write", example: "A century ago, a large share of the rural population was functionally illiterate.", zh: "文盲的；不識字的" },
    { front: "scholarly", pos: "adj.", def: "involving serious academic study; typical of scholars", example: "The book is scholarly in tone but still accessible to the general reader.", zh: "學術的；博學的" },
    { front: "academia", pos: "n.", def: "the world of universities, research, and scholarly work", example: "After a decade in industry, she returned to academia to teach engineering.", zh: "學術界" },
    { front: "thesis", pos: "n.", def: "a long piece of research writing for a university degree; a main argument", example: "His central thesis is that examinations reward compliance rather than curiosity.", zh: "論文；論點" },
    { front: "bursary", pos: "n.", def: "a sum of money given to a student to help pay for their studies", example: "She could only afford the course thanks to a bursary from a local charity.", zh: "助學金" },
    { front: "extracurricular", pos: "adj.", def: "outside the normal course of study at a school or college", example: "Universities increasingly weigh extracurricular activities alongside grades.", zh: "課外的" },
    { front: "invigilate", pos: "v.", def: "to supervise students during an examination", example: "Two members of staff were assigned to invigilate the morning paper.", zh: "監考" },
    { front: "cram", pos: "v.", def: "to study intensively just before an exam", example: "He stayed up all night cramming for the history final and could barely stay awake in it.", zh: "臨時抱佛腳；填鴨式硬讀" },
    { front: "compulsory", pos: "adj.", def: "required by law or rules; obligatory", example: "Attendance at the safety briefing is compulsory for all first-year students.", zh: "強制的；必修的" },
    { front: "sabbatical", pos: "n.", def: "a period of paid leave granted to a teacher or academic for study or travel", example: "The professor spent her sabbatical writing a book on medieval trade routes.", zh: "（學術）休假年" },
    { front: "diligent", pos: "adj.", def: "showing steady, careful, and persistent effort in work or study", example: "She was not the most gifted student in the class, but she was easily the most diligent.", zh: "勤勉的" },
    { front: "inquisitive", pos: "adj.", def: "eager to learn and ask questions about things", example: "An inquisitive child will turn any kitchen into a science laboratory.", zh: "好奇的；好問的" },
    { front: "attentive", pos: "adj.", def: "listening or watching carefully and with interest", example: "The lecturer rewarded attentive students with hints about the exam.", zh: "專注的；留心的" },
    { front: "instil", pos: "v.", def: "to gradually establish an idea or attitude in someone's mind", example: "Her first teacher instilled in her a lifelong love of poetry.", zh: "灌輸；逐漸培養" },
    { front: "assimilate", pos: "v.", def: "to fully understand and absorb new information or ideas", example: "Students need time to assimilate one concept before the next is introduced.", zh: "吸收（知識）；同化" },
    { front: "grasp", pos: "v.", def: "to understand something, especially something difficult", example: "It took me a whole term to grasp the basics of formal logic.", zh: "理解；掌握" },
    { front: "brush up on", pos: "phr. v.", def: "to improve your knowledge of something you learned before but have partly forgotten", example: "I need to brush up on my French before the conference in Lyon.", zh: "溫習；重新練習" },
    { front: "catch up on", pos: "phr. v.", def: "to do something you did not have time to do earlier", example: "She spent the weekend catching up on the reading she had missed while ill.", zh: "補上（落後的進度）" },
    { front: "fall behind", pos: "phr. v.", def: "to fail to keep level with others in progress or work", example: "Students who miss the first fortnight often fall behind and never quite recover.", zh: "落後；跟不上" },
    { front: "drop out", pos: "phr. v.", def: "to leave school or university before finishing your course", example: "He dropped out of law school to launch a software company.", zh: "輟學；中途退出" },
    { front: "hand in", pos: "phr. v.", def: "to give a piece of work to a teacher or authority", example: "All essays must be handed in by noon on Friday, without exception.", zh: "繳交" },
    { front: "hand out", pos: "phr. v.", def: "to distribute something to each member of a group", example: "The invigilator handed out the question papers face down.", zh: "分發" },
    { front: "go over", pos: "phr. v.", def: "to examine or review something carefully", example: "Let's go over the main arguments once more before the exam.", zh: "複習；仔細檢查" },
    { front: "run through", pos: "phr. v.", def: "to explain, read, or practise something quickly from beginning to end", example: "The tutor ran through the marking criteria at the start of the seminar.", zh: "快速講解；排練一遍" },
    { front: "read up on", pos: "phr. v.", def: "to read a lot about a subject in order to learn about it", example: "Before the interview, she read up on the company's history and rivals.", zh: "研讀；鑽研（某主題）" },
    { front: "swot up", pos: "phr. v.", def: "to study something intensively, especially for an exam (informal, British)", example: "I spent the whole of Sunday swotting up on organic chemistry.", zh: "苦讀；死K書" },
    { front: "sail through", pos: "phr. v.", def: "to pass a test or deal with something very easily", example: "Having prepared for months, she sailed through the oral exam.", zh: "輕鬆通過" },
    { front: "scrape through", pos: "phr. v.", def: "to only just succeed in passing an exam or test", example: "He scraped through the driving theory test with the minimum mark.", zh: "勉強通過" },
    { front: "breeze through", pos: "phr. v.", def: "to complete something quickly and without difficulty", example: "She breezed through the first two sections and saved her time for the essay.", zh: "輕而易舉地完成" },
    { front: "take in", pos: "phr. v.", def: "to understand and absorb information", example: "The lecture was so fast I could barely take in half of what was said.", zh: "理解；吸收" },
    { front: "pick up", pos: "phr. v.", def: "to learn a skill or language informally, without formal lessons", example: "He picked up Spanish just by working summers in Valencia.", zh: "（非正式地）學會" },
    { front: "drum into", pos: "phr. v.", def: "to make someone learn something by repeating it many times", example: "Our teacher drummed the irregular verbs into us until we recited them in our sleep.", zh: "反覆灌輸" },
    { front: "count towards", pos: "phr. v.", def: "to be included as part of a final total or result", example: "The mid-term test counts towards forty per cent of the overall grade.", zh: "計入（總成績）" },
    { front: "mull over", pos: "phr. v.", def: "to think carefully about something for a period of time", example: "She mulled over the essay question for an hour before writing a single word.", zh: "反覆思考" },
    { front: "get through", pos: "phr. v.", def: "to succeed in passing an exam or finishing a demanding task", example: "With her tutor's help, he finally got through the qualifying exam at the third attempt.", zh: "通過；完成" },
    { front: "learn by heart", pos: "idiom", def: "to memorise something so you can repeat it exactly", example: "As children we had to learn whole poems by heart.", zh: "背誦；熟記" },
    { front: "a steep learning curve", pos: "idiom", def: "a situation in which you must learn a great deal in a short time", example: "The new software involved a steep learning curve for the whole department.", zh: "陡峭的學習曲線；需短時間內大量學習" },
    { front: "pass with flying colours", pos: "idiom", def: "to succeed in an exam or test with a very high mark", example: "Despite her nerves, she passed the interpreting exam with flying colours.", zh: "以優異成績通過" },
    { front: "burn the midnight oil", pos: "idiom", def: "to work or study late into the night", example: "He burned the midnight oil all week to finish his dissertation on time.", zh: "熬夜苦讀（工作）" },
    { front: "hit the books", pos: "idiom", def: "to begin studying seriously (informal)", example: "The holidays are over, so it's time to hit the books again.", zh: "開始用功讀書" },
    { front: "sit an exam", pos: "collocation", def: "to take a formal examination", example: "Candidates will sit the exam in the main hall under strict conditions.", zh: "參加考試" },
    { front: "a gap year", pos: "collocation", def: "a year spent travelling or working between school and university", example: "During her gap year she taught English in rural Vietnam.", zh: "空檔年" },
    { front: "higher education", pos: "collocation", def: "education at universities and colleges after leaving school", example: "Access to higher education has widened, but costs have soared.", zh: "高等教育" },
    { front: "lifelong learning", pos: "collocation", def: "the continued development of skills and knowledge throughout life", example: "The government is funding lifelong learning schemes for workers over fifty.", zh: "終身學習" },
    { front: "continuous assessment", pos: "collocation", def: "judging students' progress through work done during the course rather than one final exam", example: "Many students prefer continuous assessment because it reduces exam pressure.", zh: "平時評量；持續性評量" },
    { front: "know something inside out", pos: "idiom", def: "to know a subject extremely well in every detail", example: "Ask her anything about Roman history — she knows the period inside out.", zh: "瞭若指掌" },
    { front: "play truant", pos: "collocation", def: "to stay away from school without permission", example: "He played truant so often that the school contacted his parents.", zh: "逃學" },
    { front: "teacher's pet", pos: "idiom", def: "a student who is favoured by the teacher, often disliked by classmates", example: "Nobody wanted to be labelled the teacher's pet, so we hid our enthusiasm.", zh: "老師的寵兒" },
    { front: "put your thinking cap on", pos: "idiom", def: "to start thinking seriously about how to solve a problem", example: "We need a title for the project by Friday, so put your thinking cap on.", zh: "開動腦筋認真思考" },
    { front: "get to grips with", pos: "idiom", def: "to begin to understand and deal with something difficult", example: "It took me a month to get to grips with the statistics software.", zh: "開始掌握；著手應付" },
    // === Law, justice & crime ===
    { front: "verdict", pos: "n.", def: "the official decision made by a jury or judge in a trial", example: "After two days of deliberation, the jury returned a unanimous verdict of guilty.", zh: "裁決；判決" },
    { front: "acquit", pos: "v.", def: "to decide officially in court that someone is not guilty", example: "The defendant was acquitted of all charges when the key witness withdrew.", zh: "宣判無罪" },
    { front: "conviction", pos: "n.", def: "an official judgement that someone is guilty of a crime", example: "A previous conviction for fraud made the jury doubt his testimony.", zh: "定罪；判罪" },
    { front: "defendant", pos: "n.", def: "the person accused of a crime in a court of law", example: "The defendant sat motionless as the charges were read out.", zh: "被告" },
    { front: "plaintiff", pos: "n.", def: "the person who brings a legal case against someone in a civil court", example: "The plaintiff is seeking damages for breach of contract.", zh: "原告" },
    { front: "prosecution", pos: "n.", def: "the lawyers who try to prove in court that someone is guilty; the process of charging someone", example: "The prosecution presented phone records placing him at the scene.", zh: "檢方；起訴" },
    { front: "testimony", pos: "n.", def: "a formal statement given in court by a witness", example: "Her testimony contradicted the account given by the arresting officer.", zh: "證詞" },
    { front: "testify", pos: "v.", def: "to give evidence as a witness in a court of law", example: "Three former employees agreed to testify against the company.", zh: "作證" },
    { front: "alibi", pos: "n.", def: "proof that someone was elsewhere when a crime was committed", example: "His alibi collapsed when the hotel confirmed he had checked out a day earlier.", zh: "不在場證明" },
    { front: "custody", pos: "n.", def: "the state of being held by the police; legal guardianship", example: "The suspect was taken into custody at the airport.", zh: "拘留；監護權" },
    { front: "bail", pos: "n.", def: "money paid so that an accused person can be released until their trial", example: "The judge set bail at fifty thousand pounds, which the family could not raise.", zh: "保釋金；保釋" },
    { front: "parole", pos: "n.", def: "the early release of a prisoner on condition of good behaviour", example: "He was released on parole after serving half of his sentence.", zh: "假釋" },
    { front: "probation", pos: "n.", def: "a period of supervision instead of prison, during which an offender must behave well", example: "The first-time offender was given two years' probation rather than a jail term.", zh: "緩刑" },
    { front: "felony", pos: "n.", def: "a serious crime such as murder or armed robbery", example: "In many jurisdictions, arson is classified as a felony.", zh: "重罪" },
    { front: "embezzlement", pos: "n.", def: "the crime of secretly stealing money you are trusted to manage", example: "The accountant was jailed for the embezzlement of charity funds.", zh: "侵占；挪用公款" },
    { front: "forgery", pos: "n.", def: "the crime of making false documents, signatures, or money", example: "The passport was such a skilled forgery that it fooled two border officers.", zh: "偽造；贗品" },
    { front: "arson", pos: "n.", def: "the crime of deliberately setting fire to property", example: "Investigators found traces of petrol and quickly suspected arson.", zh: "縱火罪" },
    { front: "burglary", pos: "n.", def: "the crime of entering a building illegally to steal", example: "A spate of burglaries has prompted residents to install alarms.", zh: "入室竊盜" },
    { front: "smuggling", pos: "n.", def: "the crime of moving goods or people illegally across a border", example: "Customs officers uncovered a cigarette smuggling operation at the port.", zh: "走私" },
    { front: "extortion", pos: "n.", def: "the crime of obtaining money through threats or force", example: "The gang was charged with extortion after threatening local shopkeepers.", zh: "勒索" },
    { front: "blackmail", pos: "n.", def: "the crime of demanding money by threatening to reveal secrets", example: "He resigned rather than give in to blackmail over the leaked emails.", zh: "敲詐；勒索" },
    { front: "bribery", pos: "n.", def: "the crime of giving money or gifts to influence someone's behaviour dishonestly", example: "The official was convicted of bribery after accepting cash for contracts.", zh: "賄賂" },
    { front: "perjury", pos: "n.", def: "the crime of lying under oath in court", example: "The witness now faces a perjury charge for inventing the alibi.", zh: "偽證罪" },
    { front: "libel", pos: "n.", def: "the crime of publishing false statements that damage someone's reputation", example: "The actor sued the newspaper for libel over the fabricated story.", zh: "書面誹謗" },
    { front: "slander", pos: "n.", def: "the crime of making false spoken statements that damage someone's reputation", example: "Calling him a thief in front of clients could amount to slander.", zh: "口頭誹謗" },
    { front: "vandalism", pos: "n.", def: "the crime of deliberately damaging public or private property", example: "The station was closed for repairs after a night of vandalism.", zh: "破壞公物" },
    { front: "trespass", pos: "v.", def: "to enter someone's land or property without permission", example: "The sign warned that anyone caught trespassing would be prosecuted.", zh: "非法侵入" },
    { front: "abduction", pos: "n.", def: "the crime of taking someone away illegally by force", example: "Police issued an alert within minutes of the child's abduction.", zh: "綁架；誘拐" },
    { front: "ransom", pos: "n.", def: "money demanded for the release of someone who has been kidnapped", example: "The kidnappers demanded a ransom of two million dollars.", zh: "贖金" },
    { front: "culprit", pos: "n.", def: "the person responsible for a crime or wrongdoing", example: "CCTV footage eventually identified the culprit behind the thefts.", zh: "罪犯；肇事者" },
    { front: "accomplice", pos: "n.", def: "a person who helps someone commit a crime", example: "The driver was charged as an accomplice to the robbery.", zh: "共犯" },
    { front: "lenient", pos: "adj.", def: "not as strict or severe as expected in punishment", example: "Critics condemned the sentence as far too lenient for such a violent offence.", zh: "寬大的；仁慈的" },
    { front: "jurisdiction", pos: "n.", def: "the official power of a court or authority to make legal decisions in an area", example: "The offence occurred at sea, outside the court's jurisdiction.", zh: "管轄權" },
    { front: "statutory", pos: "adj.", def: "decided, required, or controlled by law", example: "Employees have a statutory right to four weeks of paid leave.", zh: "法定的" },
    { front: "litigation", pos: "n.", def: "the process of taking legal action through the courts", example: "The company set aside millions to cover the cost of ongoing litigation.", zh: "訴訟" },
    { front: "sue", pos: "v.", def: "to take legal action against a person or organisation in a civil court", example: "She threatened to sue the clinic for negligence after the botched operation.", zh: "控告；提起訴訟" },
    { front: "exonerate", pos: "v.", def: "to officially declare that someone is not guilty of wrongdoing", example: "DNA evidence exonerated him after fifteen years in prison.", zh: "證明無罪；免除責任" },
    { front: "loophole", pos: "n.", def: "a gap in a law or rule that lets people avoid obeying it", example: "The firm exploited a tax loophole to shift profits offshore.", zh: "（法律）漏洞" },
    { front: "injunction", pos: "n.", def: "a court order requiring someone to do or stop doing something", example: "The singer obtained an injunction preventing publication of the photos.", zh: "禁制令" },
    { front: "warrant", pos: "n.", def: "an official document allowing the police to search, arrest, or seize", example: "Officers cannot search the premises without a warrant.", zh: "搜索令；逮捕令" },
    { front: "magistrate", pos: "n.", def: "a judicial officer who deals with minor cases in a lower court", example: "The magistrate fined him and ordered forty hours of unpaid work.", zh: "治安法官" },
    { front: "get away with", pos: "phr. v.", def: "to escape punishment for something wrong", example: "He got away with the fraud for years because nobody audited the accounts.", zh: "逃脫懲罰；僥倖成功" },
    { front: "let off", pos: "phr. v.", def: "to give someone little or no punishment for an offence", example: "The judge let her off with a warning as it was a first offence.", zh: "從輕發落；放過" },
    { front: "break into", pos: "phr. v.", def: "to enter a building illegally, usually by force", example: "Thieves broke into the gallery through a skylight and stole two paintings.", zh: "闖入；破門而入" },
    { front: "break out of", pos: "phr. v.", def: "to escape from a prison or other place of confinement", example: "Three inmates broke out of the high-security wing overnight.", zh: "越獄；逃出" },
    { front: "hold up", pos: "phr. v.", def: "to rob a bank, shop, or vehicle using threats or weapons", example: "Two masked men held up the post office in broad daylight.", zh: "持械搶劫" },
    { front: "tip off", pos: "phr. v.", def: "to secretly warn someone, especially the police, about something", example: "An anonymous caller tipped off the police about the planned robbery.", zh: "向……通風報信" },
    { front: "turn in", pos: "phr. v.", def: "to deliver someone, or yourself, to the police", example: "Racked with guilt, the driver eventually turned himself in.", zh: "（把某人）扭送警局；自首" },
    { front: "lock up", pos: "phr. v.", def: "to put someone in prison", example: "The public demanded that repeat offenders be locked up for longer.", zh: "監禁；關押" },
    { front: "put away", pos: "phr. v.", def: "to send someone to prison (informal)", example: "The detective vowed to put the gang leader away for good.", zh: "把……關進監獄" },
    { front: "make off with", pos: "phr. v.", def: "to steal something and escape with it quickly", example: "The burglars made off with jewellery worth thousands.", zh: "偷走；攜……逃走" },
    { front: "cover up", pos: "phr. v.", def: "to hide the truth about a crime or mistake", example: "Senior managers tried to cover up the safety failures for months.", zh: "掩蓋；隱瞞" },
    { front: "look into", pos: "phr. v.", def: "to investigate or examine a matter", example: "The ombudsman promised to look into the complaints about police conduct.", zh: "調查" },
    { front: "get off", pos: "phr. v.", def: "to escape punishment, or receive a lighter punishment than expected", example: "Thanks to a brilliant lawyer, he got off with a small fine.", zh: "逃過懲罰；獲輕判" },
    { front: "abide by", pos: "phr. v.", def: "to obey or follow a rule, decision, or agreement", example: "Both parties agreed to abide by the arbitrator's decision.", zh: "遵守" },
    { front: "comply with", pos: "phr. v.", def: "to act in accordance with a law, rule, or request", example: "Firms that fail to comply with the new regulations face heavy fines.", zh: "遵從；符合" },
    { front: "track down", pos: "phr. v.", def: "to find someone or something after a long search", example: "Interpol finally tracked down the fugitive in a remote fishing village.", zh: "追查到；追捕到" },
    { front: "hunt down", pos: "phr. v.", def: "to search for a person until you catch them", example: "Detectives spent a decade hunting down the members of the smuggling ring.", zh: "追捕；緝拿" },
    { front: "stamp out", pos: "phr. v.", def: "to end something bad or harmful completely", example: "The new commissioner pledged to stamp out corruption in the force.", zh: "根除；消滅" },
    { front: "hand down", pos: "phr. v.", def: "to announce a formal decision or sentence in court", example: "The court handed down the longest sentence in the country's history.", zh: "宣判；作出（判決）" },
    { front: "commit a crime", pos: "collocation", def: "to do something illegal", example: "Most burglaries are committed by a small number of repeat offenders.", zh: "犯罪" },
    { front: "press charges", pos: "collocation", def: "to formally accuse someone of a crime so they can be prosecuted", example: "The shop owner decided not to press charges against the teenager.", zh: "提出控告" },
    { front: "reach a verdict", pos: "collocation", def: "to come to an official decision about guilt or innocence", example: "The jury took less than an hour to reach a verdict.", zh: "作出裁決" },
    { front: "serve a sentence", pos: "collocation", def: "to spend time in prison as punishment", example: "He is serving a ten-year sentence for armed robbery.", zh: "服刑" },
    { front: "a custodial sentence", pos: "collocation", def: "a punishment that involves being sent to prison", example: "Given his age, the judge decided against a custodial sentence.", zh: "監禁刑" },
    { front: "take someone to court", pos: "collocation", def: "to start legal proceedings against someone", example: "The tenants took their landlord to court over the unsafe wiring.", zh: "把某人告上法庭" },
    { front: "behind bars", pos: "idiom", def: "in prison", example: "The fraudster will spend the next eight years behind bars.", zh: "在獄中" },
    { front: "above the law", pos: "idiom", def: "not subject to the law; able to ignore legal rules", example: "No official, however senior, should consider themselves above the law.", zh: "凌駕於法律之上" },
    { front: "take the law into your own hands", pos: "idiom", def: "to punish someone yourself instead of relying on the legal system", example: "Frustrated by police inaction, some villagers took the law into their own hands.", zh: "私自執法；動用私刑" },
    { front: "a miscarriage of justice", pos: "collocation", def: "a situation in which a court punishes an innocent person", example: "His release after twenty years exposed one of the worst miscarriages of justice on record.", zh: "誤判；司法不公" },
    { front: "caught red-handed", pos: "idiom", def: "discovered at the very moment of doing something wrong", example: "The pickpocket was caught red-handed with three wallets in his jacket.", zh: "當場被抓" },
    { front: "do time", pos: "idiom", def: "to spend a period in prison (informal)", example: "He did time for burglary in his twenties and has stayed clean since.", zh: "坐牢" },
    { front: "turn a blind eye", pos: "idiom", def: "to deliberately ignore wrongdoing", example: "For years the authorities turned a blind eye to illegal dumping.", zh: "視而不見" },
    { front: "circumstantial evidence", pos: "collocation", def: "indirect evidence that suggests but does not prove guilt", example: "The case rested entirely on circumstantial evidence, and the jury was unconvinced.", zh: "間接證據" },
    { front: "community service", pos: "collocation", def: "unpaid work for the public benefit given as a punishment", example: "Instead of a fine, the court ordered eighty hours of community service.", zh: "社區服務（刑罰）" },
    // === Travel & geography ===
    { front: "itinerary", pos: "n.", def: "a detailed plan of a journey, listing places and times", example: "Our itinerary was so packed that we barely had an hour free in Rome.", zh: "行程表" },
    { front: "excursion", pos: "n.", def: "a short trip made for pleasure, usually as part of a longer journey", example: "The hotel organises a daily excursion to the nearby hot springs.", zh: "短途旅行；遠足" },
    { front: "expedition", pos: "n.", def: "an organised journey with a particular purpose, often to a remote place", example: "The expedition to map the glacier took three gruelling months.", zh: "遠征；探險" },
    { front: "embark", pos: "v.", def: "to get on a ship or aircraft; to begin something new", example: "Passengers embarked at dawn for the crossing to the islands.", zh: "登船（機）；著手進行" },
    { front: "disembark", pos: "v.", def: "to leave a ship or aircraft at the end of a journey", example: "We disembarked at Piraeus and caught the first ferry to Hydra.", zh: "下船（機）" },
    { front: "stopover", pos: "n.", def: "a short stay somewhere between two parts of a journey", example: "The cheapest flight involved a twelve-hour stopover in Doha.", zh: "中途停留" },
    { front: "turbulence", pos: "n.", def: "sudden violent movements of air that shake an aircraft", example: "The captain warned of turbulence and switched on the seatbelt sign.", zh: "亂流" },
    { front: "altitude", pos: "n.", def: "height above sea level", example: "At this altitude, even a short walk leaves you breathless.", zh: "海拔；高度" },
    { front: "latitude", pos: "n.", def: "the distance of a place north or south of the equator", example: "Cities at the same latitude can have wildly different climates.", zh: "緯度" },
    { front: "terrain", pos: "n.", def: "an area of land considered in terms of its physical features", example: "The rocky terrain made the final stage of the hike treacherous.", zh: "地形" },
    { front: "plateau", pos: "n.", def: "a large area of high, fairly flat land", example: "The road climbs steeply before levelling out across a windswept plateau.", zh: "高原" },
    { front: "peninsula", pos: "n.", def: "a piece of land almost surrounded by water but joined to a larger area", example: "The peninsula juts out into the sea, dotted with fishing villages.", zh: "半島" },
    { front: "archipelago", pos: "n.", def: "a group of islands", example: "The archipelago consists of over a hundred islands, most of them uninhabited.", zh: "群島" },
    { front: "estuary", pos: "n.", def: "the wide part of a river where it meets the sea", example: "Thousands of migrating birds feed on the mudflats of the estuary.", zh: "河口" },
    { front: "tributary", pos: "n.", def: "a river or stream that flows into a larger river", example: "The expedition traced the river back along its smallest tributary.", zh: "支流" },
    { front: "glacier", pos: "n.", def: "a large mass of ice that moves slowly down a mountain valley", example: "The glacier has retreated more than a kilometre in thirty years.", zh: "冰河" },
    { front: "gorge", pos: "n.", def: "a deep, narrow valley with steep rocky sides", example: "A rope bridge swings precariously across the gorge.", zh: "峽谷" },
    { front: "ravine", pos: "n.", def: "a deep, narrow valley with steep sides, usually formed by running water", example: "The bus crawled along a road carved into the side of a ravine.", zh: "深谷；溪谷" },
    { front: "summit", pos: "n.", def: "the highest point of a mountain", example: "They reached the summit just as the clouds parted.", zh: "山頂；峰頂" },
    { front: "dune", pos: "n.", def: "a hill of sand formed by the wind, in a desert or near the sea", example: "We watched the sunset from the top of the highest dune.", zh: "沙丘" },
    { front: "tundra", pos: "n.", def: "vast, flat, treeless Arctic regions with permanently frozen subsoil", example: "In summer the tundra briefly blazes with tiny wildflowers.", zh: "凍原；苔原" },
    { front: "equator", pos: "n.", def: "the imaginary line around the middle of the Earth, equally distant from both poles", example: "Countries on the equator have little seasonal variation in daylight.", zh: "赤道" },
    { front: "hemisphere", pos: "n.", def: "one half of the Earth, especially north or south of the equator", example: "When it is winter in the northern hemisphere, Australians are at the beach.", zh: "半球" },
    { front: "coastal", pos: "adj.", def: "on or near the land beside the sea", example: "Erosion is slowly swallowing several coastal villages.", zh: "沿海的" },
    { front: "inland", pos: "adv.", def: "in or towards the interior of a country, away from the coast", example: "We drove inland for two hours before the landscape turned to vineyards.", zh: "向內陸；在內陸" },
    { front: "landlocked", pos: "adj.", def: "surrounded by land, with no coastline", example: "As a landlocked country, Bolivia depends on its neighbours for sea access.", zh: "內陸的；無海岸線的" },
    { front: "remote", pos: "adj.", def: "far away from towns and difficult to reach", example: "Supplies reach the remote settlement by boat once a month.", zh: "偏遠的" },
    { front: "picturesque", pos: "adj.", def: "attractive in an old-fashioned or charming way, like a picture", example: "The picturesque harbour is now overrun with souvenir stalls.", zh: "風景如畫的" },
    { front: "breathtaking", pos: "adj.", def: "extremely impressive or beautiful", example: "The view from the cliff path is simply breathtaking.", zh: "驚人的；令人屏息的" },
    { front: "secluded", pos: "adj.", def: "quiet, private, and away from other people", example: "We found a secluded cove that the tour boats never visit.", zh: "僻靜的" },
    { front: "bustling", pos: "adj.", def: "full of busy, noisy activity", example: "The bustling night market sells everything from silk to street food.", zh: "熙來攘往的" },
    { front: "nomadic", pos: "adj.", def: "moving from place to place rather than living in one location", example: "The herders still follow a nomadic way of life across the steppe.", zh: "游牧的" },
    { front: "pilgrimage", pos: "n.", def: "a journey to a holy place, or to a place of special personal significance", example: "Millions make the pilgrimage to the shrine every spring.", zh: "朝聖" },
    { front: "trek", pos: "n.", def: "a long, difficult journey on foot, especially in mountains or wild country", example: "The three-day trek to the base camp tested even seasoned hikers.", zh: "長途跋涉；健行" },
    { front: "wanderlust", pos: "n.", def: "a strong desire to travel and explore the world", example: "A childhood atlas was enough to spark her lifelong wanderlust.", zh: "旅行癖；流浪欲" },
    { front: "detour", pos: "n.", def: "a longer, indirect route taken to avoid something or visit somewhere", example: "We made a detour through the hills to see the abandoned monastery.", zh: "繞道；繞行路線" },
    { front: "scenic", pos: "adj.", def: "having beautiful natural views", example: "The scenic coastal railway is an attraction in itself.", zh: "風景優美的" },
    { front: "unspoilt", pos: "adj.", def: "not changed or damaged by tourism or development", example: "The island remains largely unspoilt, with no hotels above two storeys.", zh: "未受破壞的" },
    { front: "congestion", pos: "n.", def: "the state of being overcrowded, especially with traffic", example: "Congestion in the old town is worst when the cruise ships dock.", zh: "壅塞" },
    { front: "amenities", pos: "n.", def: "features that make a place comfortable or convenient, such as shops and pools", example: "The campsite is basic, but all essential amenities are within walking distance.", zh: "生活設施；便利設施" },
    { front: "sprawling", pos: "adj.", def: "spreading out over a large area in an untidy or uncontrolled way", example: "From the plane, the sprawling suburbs seemed to go on forever.", zh: "雜亂延伸的；佔地廣的" },
    { front: "set off", pos: "phr. v.", def: "to begin a journey", example: "We set off before sunrise to beat the heat on the climb.", zh: "出發；啟程" },
    { front: "stop over", pos: "phr. v.", def: "to stay somewhere briefly during a long journey", example: "On the way to Sydney we stopped over in Singapore for two nights.", zh: "中途停留" },
    { front: "see off", pos: "phr. v.", def: "to go to a station or airport to say goodbye to someone leaving", example: "The whole family came to the platform to see her off.", zh: "送行" },
    { front: "drop off", pos: "phr. v.", def: "to take someone or something to a place by car and leave them there", example: "The shuttle will drop you off right outside the terminal.", zh: "（開車）送到；放下" },
    { front: "touch down", pos: "phr. v.", def: "to land at an airport (of an aircraft)", example: "The plane touched down in Nairobi twenty minutes ahead of schedule.", zh: "降落" },
    { front: "get around", pos: "phr. v.", def: "to travel to different places within a city or area", example: "The metro is by far the easiest way to get around the capital.", zh: "四處走動；出行" },
    { front: "pull over", pos: "phr. v.", def: "to drive to the side of the road and stop", example: "We pulled over to photograph the valley spread out below us.", zh: "把車停靠路邊" },
    { front: "press on", pos: "phr. v.", def: "to continue a journey or task despite difficulty", example: "Despite the driving rain, the hikers pressed on towards the refuge.", zh: "繼續前進" },
    { front: "put up", pos: "phr. v.", def: "to provide someone with a place to stay; to stay somewhere for the night", example: "Friends in Lisbon offered to put us up for the weekend.", zh: "留宿；提供住宿" },
    { front: "turn back", pos: "phr. v.", def: "to return the way you came instead of continuing", example: "Deep snow forced the climbers to turn back just below the ridge.", zh: "折返" },
    { front: "head off", pos: "phr. v.", def: "to leave and start a journey towards a place", example: "After breakfast we headed off towards the border crossing.", zh: "動身前往" },
    { front: "branch off", pos: "phr. v.", def: "to leave a main road or path and follow a smaller one", example: "A dirt track branches off the highway and winds up to the lighthouse.", zh: "岔開；轉入岔路" },
    { front: "look out over", pos: "phr. v.", def: "to have a view of a place from above or from a distance", example: "Our balcony looked out over the terracotta rooftops of the old quarter.", zh: "俯瞰；眺望" },
    { front: "get in", pos: "phr. v.", def: "to arrive at a destination (of a train, plane, or traveller)", example: "The night train gets in at six, just in time for the fish market.", zh: "抵達" },
    { front: "while away", pos: "phr. v.", def: "to spend time in a relaxed, unhurried way", example: "We whiled away the afternoon in a café overlooking the canal.", zh: "消磨（時間）" },
    { front: "splash out", pos: "phr. v.", def: "to spend a lot of money on something enjoyable (informal)", example: "For our last night we splashed out on a suite with a sea view.", zh: "揮霍；大手筆花錢" },
    { front: "jet off", pos: "phr. v.", def: "to fly somewhere, especially for a holiday (informal)", example: "The moment term ended, they jetted off to the Canary Islands.", zh: "搭機飛往（度假）" },
    { front: "get away", pos: "phr. v.", def: "to go somewhere for a rest or holiday, escaping routine", example: "We try to get away for a long weekend at least twice a year.", zh: "外出度假；抽身" },
    { front: "pull in", pos: "phr. v.", def: "to arrive at a station or stop (of a train or bus)", example: "The overnight express pulled in just as the platform clock struck five.", zh: "（列車）進站" },
    { front: "off the beaten track", pos: "idiom", def: "in a place where few tourists go", example: "The guidebook is full of villages that are well off the beaten track.", zh: "人跡罕至；非熱門路線" },
    { front: "a whistle-stop tour", pos: "idiom", def: "a very quick trip with brief visits to many places", example: "We did a whistle-stop tour of five capitals in eight days.", zh: "走馬看花式的行程" },
    { front: "travel light", pos: "collocation", def: "to take very little luggage on a journey", example: "Experienced backpackers learn to travel light and wash clothes on the way.", zh: "輕裝旅行" },
    { front: "in the middle of nowhere", pos: "idiom", def: "in a place far from towns and other people", example: "The bus broke down in the middle of nowhere, hours from the nearest garage.", zh: "在偏僻荒涼的地方" },
    { front: "a tourist trap", pos: "collocation", def: "a crowded place that attracts visitors but is overpriced or of poor quality", example: "The waterfront restaurants are a tourist trap; locals eat two streets back.", zh: "觀光客陷阱" },
    { front: "hit the road", pos: "idiom", def: "to begin a journey (informal)", example: "We packed the van the night before so we could hit the road at dawn.", zh: "上路；出發" },
    { front: "itchy feet", pos: "idiom", def: "a strong desire to travel or move somewhere new", example: "After two years in the same job, she got itchy feet and booked a one-way ticket.", zh: "渴望旅行；待不住" },
    { front: "a far-flung destination", pos: "collocation", def: "a place that is a very long distance away", example: "Budget airlines have put once far-flung destinations within reach.", zh: "遙遠的目的地" },
    { front: "culture shock", pos: "collocation", def: "confusion felt when experiencing a very different way of life", example: "The biggest culture shock was not the food but the pace of life.", zh: "文化衝擊" },
    { front: "a package holiday", pos: "collocation", def: "a holiday arranged by a company that includes travel, accommodation, and sometimes meals", example: "A package holiday suits travellers who want everything organised in advance.", zh: "套裝旅遊" },
    { front: "densely populated", pos: "collocation", def: "having a very large number of people living in a small area", example: "The delta is one of the most densely populated regions on Earth.", zh: "人口稠密的" },
    { front: "a vantage point", pos: "collocation", def: "a position that gives a good, wide view of something", example: "The fortress offers a superb vantage point over the whole bay.", zh: "有利位置；瞭望點" },
    { front: "a once-in-a-lifetime experience", pos: "collocation", def: "something so special it is unlikely ever to be repeated", example: "Watching the migration cross the river was a once-in-a-lifetime experience.", zh: "一生一次的體驗" },
    { front: "a bumpy ride", pos: "collocation", def: "an uncomfortable journey; a difficult period", example: "The dirt road down to the falls made for a bumpy ride.", zh: "顛簸的路程；坎坷的過程" },
    { front: "a home from home", pos: "idiom", def: "a place where you feel as comfortable as in your own home", example: "After three visits, the little guesthouse has become a home from home.", zh: "賓至如歸的地方" },
    // === Personality & relationships ===
    { front: "amiable", pos: "adj.", def: "friendly, pleasant, and easy to like", example: "Our amiable host chatted with every guest as if they were old friends.", zh: "和藹可親的" },
    { front: "approachable", pos: "adj.", def: "friendly and easy to talk to", example: "Despite her seniority, the director is remarkably approachable.", zh: "平易近人的" },
    { front: "charismatic", pos: "adj.", def: "having a powerful personal charm that attracts and influences people", example: "The movement grew quickly around its charismatic young founder.", zh: "有領袖魅力的" },
    { front: "compassionate", pos: "adj.", def: "feeling and showing sympathy for people who are suffering", example: "The nurses were unfailingly compassionate during his final weeks.", zh: "富同情心的" },
    { front: "condescending", pos: "adj.", def: "behaving as if you are more intelligent or important than others", example: "His condescending tone made even simple advice hard to accept.", zh: "居高臨下的；帶優越感的" },
    { front: "conceited", pos: "adj.", def: "having too high an opinion of yourself", example: "Success at such a young age risked making him insufferably conceited.", zh: "自負的" },
    { front: "cynical", pos: "adj.", def: "believing that people act only out of self-interest", example: "Years in politics had left her deeply cynical about public promises.", zh: "憤世嫉俗的" },
    { front: "diplomatic", pos: "adj.", def: "skilled at dealing with people without offending them", example: "She gave a diplomatic answer that satisfied both sides of the argument.", zh: "圓融的；有外交手腕的" },
    { front: "gregarious", pos: "adj.", def: "enjoying the company of others; sociable", example: "Gregarious by nature, he knew half the town by their first names.", zh: "愛交際的" },
    { front: "hypocritical", pos: "adj.", def: "pretending to have beliefs or standards that you do not actually follow", example: "It is hypocritical to preach thrift while flying first class.", zh: "偽善的" },
    { front: "infatuated", pos: "adj.", def: "having intense but usually short-lived passion for someone", example: "He was so infatuated with her that he ignored every warning from his friends.", zh: "迷戀的" },
    { front: "malicious", pos: "adj.", def: "intending to hurt or upset others", example: "The rumours were not careless gossip but deliberately malicious.", zh: "惡意的" },
    { front: "naive", pos: "adj.", def: "lacking experience and too ready to believe or trust others", example: "It was naive of me to assume everyone would keep their word.", zh: "天真的" },
    { front: "obnoxious", pos: "adj.", def: "extremely unpleasant and offensive", example: "One obnoxious guest managed to insult the hosts, the food, and the other diners.", zh: "討人厭的；可憎的" },
    { front: "overbearing", pos: "adj.", def: "trying to control people in an unpleasant, domineering way", example: "Her overbearing manner left colleagues afraid to voice any objection.", zh: "專橫的" },
    { front: "perceptive", pos: "adj.", def: "quick to notice and understand things about people and situations", example: "A perceptive friend noticed something was wrong before I said a word.", zh: "觀察敏銳的" },
    { front: "possessive", pos: "adj.", def: "demanding all of someone's attention and unwilling to share them", example: "His possessive behaviour gradually cut her off from her friends.", zh: "佔有慾強的" },
    { front: "pragmatic", pos: "adj.", def: "dealing with problems in a practical rather than idealistic way", example: "She took a pragmatic view: the plan was imperfect, but it would work.", zh: "務實的" },
    { front: "rebellious", pos: "adj.", def: "resisting authority or control", example: "As a rebellious teenager, he questioned every rule in the house.", zh: "叛逆的" },
    { front: "reserved", pos: "adj.", def: "quiet and not showing feelings or opinions openly", example: "She seems reserved at first, but warms up once she trusts you.", zh: "內斂的；矜持的" },
    { front: "resourceful", pos: "adj.", def: "good at finding clever ways to solve problems", example: "A resourceful guide fixed the engine with little more than wire and tape.", zh: "足智多謀的" },
    { front: "ruthless", pos: "adj.", def: "showing no pity and doing anything necessary to achieve a goal", example: "He was a ruthless negotiator who never left money on the table.", zh: "冷酷無情的" },
    { front: "self-assured", pos: "adj.", def: "confident in your own abilities and judgement", example: "She gave a calm, self-assured performance at the interview.", zh: "自信的" },
    { front: "selfless", pos: "adj.", def: "caring more about others' needs than your own", example: "Her selfless devotion to her patients earned her a national award.", zh: "無私的" },
    { front: "temperamental", pos: "adj.", def: "having moods that change suddenly and unpredictably", example: "The chef is brilliant but temperamental, and the kitchen staff walk on eggshells.", zh: "喜怒無常的" },
    { front: "timid", pos: "adj.", def: "shy and easily frightened; lacking courage", example: "The timid new intern barely spoke during the first month of meetings.", zh: "膽小的" },
    { front: "vain", pos: "adj.", def: "too proud of your appearance or achievements", example: "He is so vain that he checks his reflection in every shop window.", zh: "自戀的；愛慕虛榮的" },
    { front: "vindictive", pos: "adj.", def: "determined to harm someone who has harmed you; unforgiving", example: "The review was less honest criticism than a vindictive attack.", zh: "有報復心的" },
    { front: "witty", pos: "adj.", def: "clever and amusing in the use of words", example: "Her witty remarks kept the whole dinner table laughing.", zh: "機智詼諧的" },
    { front: "estranged", pos: "adj.", def: "no longer in contact with a family member or spouse after a disagreement", example: "He reconciled with his estranged brother after twenty years of silence.", zh: "疏遠的；不相往來的" },
    { front: "devoted", pos: "adj.", def: "extremely loving and loyal", example: "They remained devoted to each other through fifty years of marriage.", zh: "深愛的；忠誠的" },
    { front: "acquaintance", pos: "n.", def: "a person you know slightly but who is not a close friend", example: "He is more an acquaintance than a friend; we only meet at conferences.", zh: "泛泛之交；熟人" },
    { front: "rapport", pos: "n.", def: "a friendly relationship in which people understand each other well", example: "The new coach built an instant rapport with the younger players.", zh: "融洽的關係" },
    { front: "animosity", pos: "n.", def: "a strong feeling of dislike or hatred", example: "Years after the lawsuit, the animosity between the two families persists.", zh: "敵意" },
    { front: "betrayal", pos: "n.", def: "the act of harming someone who trusted you", example: "Selling the story to the press felt like the ultimate betrayal.", zh: "背叛" },
    { front: "feud", pos: "n.", def: "a long and bitter quarrel between two people or groups", example: "A feud over land has divided the two villages for generations.", zh: "世仇；長期不和" },
    { front: "intimacy", pos: "n.", def: "a state of close personal connection and familiarity", example: "Long-distance couples work hard to preserve a sense of intimacy.", zh: "親密" },
    { front: "reconciliation", pos: "n.", def: "the restoring of friendly relations after a conflict", example: "The wedding became an unexpected occasion for family reconciliation.", zh: "和解" },
    { front: "rift", pos: "n.", def: "a serious break in friendly relations", example: "The inheritance dispute opened a rift between the sisters that never healed.", zh: "裂痕；不和" },
    { front: "extroverted", pos: "adj.", def: "energetic, outgoing, and enjoying being with other people", example: "Sales suited his extroverted personality perfectly.", zh: "外向的" },
    { front: "introverted", pos: "adj.", def: "quiet, inward-looking, and preferring time alone", example: "Introverted students often contribute more in writing than in discussion.", zh: "內向的" },
    { front: "fall for", pos: "phr. v.", def: "to fall in love with someone; to be deceived by a trick", example: "She fell for him the moment he made the whole room laugh.", zh: "愛上；上當" },
    { front: "ask out", pos: "phr. v.", def: "to invite someone on a date", example: "It took him three weeks to work up the courage to ask her out.", zh: "約（某人）出去" },
    { front: "settle down", pos: "phr. v.", def: "to start living a stable life, often with a partner or family", example: "After years of travelling, they finally settled down in a small coastal town.", zh: "安定下來" },
    { front: "drift apart", pos: "phr. v.", def: "to gradually become less close to someone", example: "We never argued; we simply drifted apart after university.", zh: "逐漸疏遠" },
    { front: "grow apart", pos: "phr. v.", def: "to slowly develop different interests and become less close", example: "The couple grew apart as their careers pulled them in different directions.", zh: "漸行漸遠" },
    { front: "look up to", pos: "phr. v.", def: "to admire and respect someone", example: "Younger players clearly look up to the veteran captain.", zh: "敬仰" },
    { front: "stand by", pos: "phr. v.", def: "to continue to support someone in a difficult time", example: "Her friends stood by her throughout the scandal.", zh: "支持；不離不棄" },
    { front: "stick up for", pos: "phr. v.", def: "to defend someone who is being criticised or attacked", example: "He always stuck up for his little sister in the playground.", zh: "為……辯護；挺身維護" },
    { front: "put down", pos: "phr. v.", def: "to criticise someone and make them feel foolish", example: "He constantly puts down his colleagues in front of clients.", zh: "貶低；奚落" },
    { front: "take after", pos: "phr. v.", def: "to resemble a parent or older relative in appearance or character", example: "She takes after her grandmother — stubborn, funny, and utterly fearless.", zh: "像（長輩）" },
    { front: "suck up to", pos: "phr. v.", def: "to flatter someone in authority to gain an advantage (informal)", example: "He spent the whole meeting sucking up to the new manager.", zh: "巴結；拍馬屁" },
    { front: "size up", pos: "phr. v.", def: "to form a judgement about a person or situation", example: "The two rivals sized each other up across the negotiating table.", zh: "打量；估量" },
    { front: "confide in", pos: "phr. v.", def: "to tell someone a secret because you trust them", example: "She confides in her sister about things she would never tell anyone else.", zh: "向……吐露心事" },
    { front: "lean on", pos: "phr. v.", def: "to depend on someone for support and encouragement", example: "After the divorce, he leaned on his oldest friends more than ever.", zh: "依靠" },
    { front: "gang up on", pos: "phr. v.", def: "to join together as a group against one person", example: "The older kids ganged up on him until a teacher intervened.", zh: "聯合起來對付" },
    { front: "reach out to", pos: "phr. v.", def: "to make an effort to communicate with or help someone", example: "After the argument, she was the first to reach out to him and apologise.", zh: "主動聯繫；伸出援手" },
    { front: "walk out on", pos: "phr. v.", def: "to suddenly leave a partner or family, abandoning responsibilities", example: "He walked out on his family when the children were still small.", zh: "拋棄（家人、伴侶）" },
    { front: "cut off", pos: "phr. v.", def: "to stop all contact or communication with someone", example: "She cut off everyone connected with her old life and started again abroad.", zh: "斷絕往來" },
    { front: "talk down to", pos: "phr. v.", def: "to speak to someone as if they were less intelligent than you", example: "Good doctors explain clearly without talking down to their patients.", zh: "以高姿態說話；輕視地說" },
    { front: "hit it off", pos: "idiom", def: "to like each other immediately on first meeting", example: "The two designers hit it off at the workshop and now run a studio together.", zh: "一見如故" },
    { front: "get on like a house on fire", pos: "idiom", def: "to become friendly with someone very quickly and get along extremely well", example: "My mother and my girlfriend got on like a house on fire from the first dinner.", zh: "一拍即合；相處極好" },
    { front: "see eye to eye", pos: "idiom", def: "to agree with someone or share their views", example: "We rarely see eye to eye on politics, but we never let it spoil the friendship.", zh: "看法一致" },
    { front: "at loggerheads", pos: "idiom", def: "in strong disagreement with someone", example: "The two departments have been at loggerheads over the budget for months.", zh: "爭執不下" },
    { front: "give someone the cold shoulder", pos: "idiom", def: "to deliberately ignore someone in an unfriendly way", example: "After the argument, she gave him the cold shoulder for a week.", zh: "冷落某人" },
    { front: "bury the hatchet", pos: "idiom", def: "to end a quarrel and become friendly again", example: "The former rivals buried the hatchet and even co-wrote a book.", zh: "言歸於好；捐棄前嫌" },
    { front: "a heart of gold", pos: "idiom", def: "a very kind and generous nature", example: "He grumbles constantly, but underneath he has a heart of gold.", zh: "菩薩心腸；心地善良" },
    { front: "wear your heart on your sleeve", pos: "idiom", def: "to show your emotions openly", example: "She wears her heart on her sleeve, so you always know when she is upset.", zh: "情感外露" },
    { front: "through thick and thin", pos: "idiom", def: "through both good times and bad", example: "They have supported each other through thick and thin for thirty years.", zh: "同甘共苦" },
    { front: "keep someone at arm's length", pos: "idiom", def: "to avoid becoming too close or friendly with someone", example: "He is polite to colleagues but keeps everyone at arm's length.", zh: "保持距離" },
    { front: "rub someone up the wrong way", pos: "idiom", def: "to annoy someone without intending to", example: "Something about his jokes rubs me up the wrong way.", zh: "無意間惹惱某人" },
    { front: "strike up a friendship", pos: "collocation", def: "to begin a friendship, often casually", example: "They struck up a friendship while queuing for the same delayed flight.", zh: "建立友誼" },
    { front: "mutual respect", pos: "collocation", def: "a feeling of admiration that two people have for each other", example: "The partnership survived every crisis because it was built on mutual respect.", zh: "相互尊重" },
    { front: "a love-hate relationship", pos: "collocation", def: "a relationship involving both strong affection and strong dislike", example: "She has a love-hate relationship with the city: exhausting, but impossible to leave.", zh: "又愛又恨的關係" },
    { front: "tie the knot", pos: "idiom", def: "to get married (informal)", example: "After a ten-year engagement, they finally tied the knot in a tiny chapel.", zh: "結婚" },
    // === Food & agriculture ===
    { front: "palatable", pos: "adj.", def: "pleasant to taste; acceptable", example: "A little honey makes the bitter medicine more palatable.", zh: "可口的；可接受的" },
    { front: "savoury", pos: "adj.", def: "having a salty or spicy taste rather than a sweet one", example: "I always choose the savoury pastries over the sweet ones at breakfast.", zh: "鹹味的；辛香的" },
    { front: "succulent", pos: "adj.", def: "juicy and delicious (of food, especially meat or fruit)", example: "The lamb was so succulent it fell apart at the touch of a fork.", zh: "多汁美味的" },
    { front: "bland", pos: "adj.", def: "lacking strong flavour or interest", example: "Hospital food has a reputation for being bland and overcooked.", zh: "清淡無味的" },
    { front: "pungent", pos: "adj.", def: "having a very strong, sharp taste or smell", example: "The pungent aroma of fermented tofu filled the entire alley.", zh: "刺鼻的；味道強烈的" },
    { front: "rancid", pos: "adj.", def: "tasting or smelling unpleasant because no longer fresh (of fatty food)", example: "The butter had gone rancid after a week out of the fridge.", zh: "腐臭的（油脂）" },
    { front: "appetising", pos: "adj.", def: "looking or smelling good enough to make you want to eat", example: "The stew did not look appetising, but it tasted wonderful.", zh: "促進食慾的" },
    { front: "delectable", pos: "adj.", def: "extremely delicious", example: "The bakery window displayed a row of delectable fruit tarts.", zh: "美味的" },
    { front: "gourmet", pos: "adj.", def: "relating to high-quality, sophisticated food and cooking", example: "The festival attracts gourmet food trucks from all over the country.", zh: "美食的；精緻烹飪的" },
    { front: "culinary", pos: "adj.", def: "connected with cooking or the kitchen", example: "She spent a year in Lyon honing her culinary skills.", zh: "烹飪的" },
    { front: "edible", pos: "adj.", def: "safe or suitable to be eaten", example: "Only a handful of these wild mushrooms are actually edible.", zh: "可食用的" },
    { front: "perishable", pos: "adj.", def: "likely to decay or spoil quickly (of food)", example: "Perishable goods are flown in daily and sold within hours.", zh: "易腐壞的" },
    { front: "preservative", pos: "n.", def: "a substance added to food to stop it decaying", example: "The jam contains no artificial preservatives, so keep it refrigerated.", zh: "防腐劑" },
    { front: "additive", pos: "n.", def: "a substance added to food to improve taste, colour, or shelf life", example: "Parents increasingly avoid snacks laden with artificial additives.", zh: "添加物" },
    { front: "seasoning", pos: "n.", def: "salt, herbs, or spices added to food to improve flavour", example: "Taste the sauce and adjust the seasoning before serving.", zh: "調味料" },
    { front: "marinade", pos: "n.", def: "a mixture of oil, spices, and liquids in which food is soaked before cooking", example: "Leave the chicken in the marinade overnight for the best flavour.", zh: "醃醬；醃漬汁" },
    { front: "garnish", pos: "v.", def: "to decorate food with a small amount of another food", example: "Garnish the soup with fresh coriander just before serving.", zh: "裝飾（菜餚）" },
    { front: "simmer", pos: "v.", def: "to cook gently in liquid just below boiling point", example: "Let the broth simmer for two hours until the flavours deepen.", zh: "用小火慢燉" },
    { front: "knead", pos: "v.", def: "to press and stretch dough with your hands", example: "Knead the dough for ten minutes until it turns smooth and elastic.", zh: "揉（麵團）" },
    { front: "drizzle", pos: "v.", def: "to pour a liquid slowly over food in a thin stream", example: "Drizzle olive oil over the salad and finish with sea salt.", zh: "淋上（少量液體）" },
    { front: "cultivation", pos: "n.", def: "the growing of crops or plants", example: "Rice cultivation shaped both the landscape and the culture of the valley.", zh: "耕作；栽培" },
    { front: "irrigation", pos: "n.", def: "the supply of water to land for growing crops", example: "Drip irrigation cut the farm's water use by more than half.", zh: "灌溉" },
    { front: "fertiliser", pos: "n.", def: "a substance added to soil to help plants grow", example: "Overuse of chemical fertiliser has degraded the soil downstream.", zh: "肥料" },
    { front: "arable", pos: "adj.", def: "suitable for growing crops (of land or farming)", example: "Only a narrow strip along the river is arable; the rest is scrubland.", zh: "可耕的" },
    { front: "livestock", pos: "n.", def: "farm animals such as cows, sheep, and pigs", example: "The drought forced many farmers to sell off their livestock early.", zh: "家畜" },
    { front: "poultry", pos: "n.", def: "birds such as chickens kept for eggs and meat", example: "The farm switched from poultry to organic vegetables a decade ago.", zh: "家禽" },
    { front: "orchard", pos: "n.", def: "a piece of land planted with fruit trees", example: "In spring the whole orchard turns white with apple blossom.", zh: "果園" },
    { front: "vineyard", pos: "n.", def: "a plantation of grapevines, usually for making wine", example: "The family has worked the same vineyard for six generations.", zh: "葡萄園" },
    { front: "yield", pos: "n.", def: "the amount of crops produced from an area of land", example: "The new seed variety promises a much higher yield per hectare.", zh: "產量" },
    { front: "subsistence", pos: "n.", def: "producing just enough food to live on, with nothing left to sell", example: "Most households in the region still rely on subsistence farming.", zh: "自給自足（農業）" },
    { front: "horticulture", pos: "n.", def: "the art and science of growing fruit, vegetables, and flowers", example: "She studied horticulture before opening her own nursery.", zh: "園藝學" },
    { front: "ripen", pos: "v.", def: "to become ripe and ready to eat", example: "The tomatoes ripen on the vine well into October.", zh: "成熟" },
    { front: "ferment", pos: "v.", def: "to change chemically through the action of yeast or bacteria", example: "The cabbage is left to ferment in brine for several weeks.", zh: "發酵" },
    { front: "pasteurise", pos: "v.", def: "to heat milk or other liquids to kill harmful bacteria", example: "By law, all milk sold in the supermarket must be pasteurised.", zh: "以巴氏法殺菌" },
    { front: "free-range", pos: "adj.", def: "relating to farm animals allowed to move around outdoors", example: "The café uses only free-range eggs from a farm up the road.", zh: "放養的；自由放牧的" },
    { front: "staple", pos: "n.", def: "a basic food that forms a large part of a diet", example: "Rice remains the staple across most of the continent.", zh: "主食" },
    { front: "forage", pos: "v.", def: "to search for wild food in nature", example: "Every autumn they forage for mushrooms in the beech woods.", zh: "覓食；採集野生食物" },
    { front: "glut", pos: "n.", def: "a supply of something that is much greater than needed", example: "A glut of tomatoes this summer sent prices tumbling.", zh: "供過於求" },
    { front: "malnutrition", pos: "n.", def: "poor health caused by not eating enough or eating the wrong things", example: "The clinic treats hundreds of children for malnutrition each year.", zh: "營養不良" },
    { front: "condiment", pos: "n.", def: "a sauce or seasoning added to food at the table", example: "Every table carried the same three condiments: soy sauce, vinegar, and chilli oil.", zh: "佐料；調味品" },
    { front: "intake", pos: "n.", def: "the amount of food, drink, or a substance that you consume", example: "The doctor advised him to reduce his daily salt intake.", zh: "攝取量" },
    { front: "whip up", pos: "phr. v.", def: "to prepare a meal or dish very quickly", example: "She whipped up a three-course dinner from whatever was in the fridge.", zh: "快速做出（餐點）" },
    { front: "polish off", pos: "phr. v.", def: "to finish food or drink quickly and completely (informal)", example: "The children polished off the entire cake before the guests arrived.", zh: "吃光；一掃而空" },
    { front: "wolf down", pos: "phr. v.", def: "to eat food very quickly and greedily", example: "He wolfed down his sandwich and rushed back to the meeting.", zh: "狼吞虎嚥" },
    { front: "pick at", pos: "phr. v.", def: "to eat only small amounts of a meal without appetite", example: "Too nervous to eat, she just picked at her salad.", zh: "沒胃口地吃；小口撥弄" },
    { front: "tuck into", pos: "phr. v.", def: "to start eating something with enthusiasm (informal)", example: "The hikers tucked into the stew the moment it hit the table.", zh: "津津有味地吃" },
    { front: "wash down", pos: "phr. v.", def: "to drink something with or after food", example: "We washed down the cheese with a glass of local red wine.", zh: "用飲料送（食物）" },
    { front: "dish up", pos: "phr. v.", def: "to put food onto plates ready to be eaten", example: "Sit down, everyone — I'm about to dish up.", zh: "上菜；盛菜" },
    { front: "live on", pos: "phr. v.", def: "to eat mainly a particular kind of food; to survive on a certain income", example: "As a student he lived on instant noodles and toast.", zh: "以……為主食；靠……過活" },
    { front: "fill up on", pos: "phr. v.", def: "to eat a lot of a particular food so you no longer feel hungry", example: "Don't fill up on bread before the main course arrives.", zh: "靠……吃飽" },
    { front: "cut back on", pos: "phr. v.", def: "to reduce the amount of something, especially food, drink, or spending", example: "Her doctor told her to cut back on caffeine and sugar.", zh: "減少（攝取、花費）" },
    { front: "boil over", pos: "phr. v.", def: "to rise and flow over the side of a pan; (of anger) to erupt", example: "The milk boiled over the moment I turned my back.", zh: "沸溢；（情緒）爆發" },
    { front: "throw together", pos: "phr. v.", def: "to make a meal quickly using whatever is available", example: "I threw together a pasta dish with leftovers and a tin of tomatoes.", zh: "隨手拼湊做出（餐點）" },
    { front: "pig out", pos: "phr. v.", def: "to eat a very large amount of food (informal)", example: "After the marathon we pigged out on pizza and ice cream.", zh: "大吃特吃" },
    { front: "go off", pos: "phr. v.", def: "to become too old to eat or drink; to spoil", example: "This milk smells like it has gone off.", zh: "（食物）壞掉" },
    { front: "water down", pos: "phr. v.", def: "to make a drink weaker by adding water; to weaken a proposal", example: "The bar was accused of watering down its spirits.", zh: "稀釋；淡化" },
    { front: "thin out", pos: "phr. v.", def: "to remove some plants so the rest have room to grow; to become less dense", example: "Thin out the seedlings once they reach a few centimetres tall.", zh: "疏苗；使稀疏" },
    { front: "plough through", pos: "phr. v.", def: "to slowly finish a large amount of food or work", example: "We ploughed through a mountain of dumplings and still ordered more.", zh: "費力吃（做）完" },
    { front: "dig in", pos: "phr. v.", def: "to start eating eagerly (informal)", example: "Everything is on the table, so dig in before it gets cold.", zh: "開動；開吃" },
    { front: "grow on", pos: "phr. v.", def: "to become gradually more liked by someone", example: "I hated olives as a child, but they have grown on me over the years.", zh: "逐漸讓人喜歡" },
    { front: "a staple diet", pos: "collocation", def: "the food that a person or group eats most regularly", example: "Fish and root vegetables form the staple diet of the island.", zh: "基本飲食；日常主食" },
    { front: "a square meal", pos: "collocation", def: "a complete, satisfying, and nourishing meal", example: "He looked as if he had not had a square meal in weeks.", zh: "一頓豐盛正餐" },
    { front: "a hearty meal", pos: "collocation", def: "a large, satisfying meal", example: "After the climb we were rewarded with a hearty meal at the lodge.", zh: "豐盛的一餐" },
    { front: "a bumper harvest", pos: "collocation", def: "an unusually large crop", example: "Perfect weather delivered a bumper harvest of wheat this year.", zh: "大豐收" },
    { front: "home-grown produce", pos: "collocation", def: "fruit and vegetables grown in your own garden or locally", example: "The market stalls overflow with home-grown produce every Saturday.", zh: "自家（本地）種植的農產品" },
    { front: "food security", pos: "collocation", def: "reliable access to enough affordable, nutritious food", example: "Climate change poses a direct threat to global food security.", zh: "糧食安全" },
    { front: "locally sourced", pos: "collocation", def: "obtained from producers near the place where it is used", example: "The menu is built around locally sourced ingredients.", zh: "在地採購的" },
    { front: "a voracious appetite", pos: "collocation", def: "an extremely strong desire for food (or, figuratively, for anything)", example: "Teenage swimmers have a voracious appetite after morning training.", zh: "旺盛的食慾" },
    { front: "have a sweet tooth", pos: "idiom", def: "to love eating sweet things", example: "She has such a sweet tooth that no dessert is ever safe near her.", zh: "愛吃甜食" },
    { front: "bite off more than you can chew", pos: "idiom", def: "to attempt more than you are able to manage", example: "Taking on three renovation projects at once, he bit off more than he could chew.", zh: "不自量力；貪多嚼不爛" },
    { front: "take something with a pinch of salt", pos: "idiom", def: "to not completely believe what someone says", example: "Take his fishing stories with a pinch of salt — the fish grow every retelling.", zh: "半信半疑；姑妄聽之" },
    { front: "sell like hot cakes", pos: "idiom", def: "to be bought quickly and in large numbers", example: "The limited-edition sauce sold like hot cakes and vanished within a day.", zh: "熱賣；搶購一空" },
    { front: "a recipe for disaster", pos: "idiom", def: "a combination of things certain to lead to serious trouble", example: "An inexperienced crew and an old boat in bad weather is a recipe for disaster.", zh: "災難的根源；注定出事" },
    { front: "the icing on the cake", pos: "idiom", def: "an extra good thing added to something already good", example: "The win was wonderful; doing it in front of home fans was the icing on the cake.", zh: "錦上添花" },
    { front: "out of season", pos: "collocation", def: "not available fresh at this time of year; outside the tourist period", example: "Strawberries taste of nothing when they are out of season.", zh: "非當季的；淡季的" },
    // === Sport & competition ===
    { front: "agility", pos: "n.", def: "the ability to move quickly and easily", example: "Goalkeepers need remarkable agility to reach shots in either corner.", zh: "敏捷" },
    { front: "stamina", pos: "n.", def: "the physical or mental strength to keep going for a long time", example: "Marathon running is less about speed than about sheer stamina.", zh: "耐力" },
    { front: "endurance", pos: "n.", def: "the ability to withstand prolonged physical effort or hardship", example: "The desert ultramarathon is the ultimate test of human endurance.", zh: "持久力；忍耐力" },
    { front: "perseverance", pos: "n.", def: "continued effort despite difficulty or delay in achieving success", example: "Years of perseverance finally earned her a place on the national team.", zh: "毅力" },
    { front: "tenacity", pos: "n.", def: "the determination to keep trying and never give up", example: "Two sets down, he showed extraordinary tenacity to win the match.", zh: "頑強；堅韌" },
    { front: "adversary", pos: "n.", def: "an opponent in a contest, dispute, or conflict", example: "The champion faces her oldest adversary in Saturday's final.", zh: "對手；敵手" },
    { front: "contender", pos: "n.", def: "a person or team with a realistic chance of winning", example: "After three straight victories, they are genuine title contenders.", zh: "有力競爭者" },
    { front: "underdog", pos: "n.", def: "the competitor expected to lose", example: "The crowd roared for the underdog, a club from the fourth division.", zh: "弱勢的一方；不被看好者" },
    { front: "forfeit", pos: "v.", def: "to lose a match or right as a penalty for breaking rules or failing to appear", example: "The team arrived late and was forced to forfeit the opening game.", zh: "（因違規）喪失；棄權" },
    { front: "disqualify", pos: "v.", def: "to officially remove someone from a competition for breaking the rules", example: "The sprinter was disqualified for a second false start.", zh: "取消資格" },
    { front: "exhilarating", pos: "adj.", def: "making you feel very excited and full of energy", example: "There is nothing quite as exhilarating as skiing fresh powder at dawn.", zh: "令人振奮的" },
    { front: "gruelling", pos: "adj.", def: "extremely tiring and demanding", example: "The riders face a gruelling mountain stage of over two hundred kilometres.", zh: "使人筋疲力盡的" },
    { front: "formidable", pos: "adj.", def: "inspiring respect or fear through being powerful or impressive", example: "The home side has built a formidable record: unbeaten in forty matches.", zh: "強大的；令人敬畏的" },
    { front: "invincible", pos: "adj.", def: "too strong to be defeated", example: "For two glorious seasons the team seemed utterly invincible.", zh: "無敵的" },
    { front: "comeback", pos: "n.", def: "a return to winning or success after falling behind or retiring", example: "Three goals down at half-time, they staged an astonishing comeback.", zh: "逆轉；復出" },
    { front: "rout", pos: "n.", def: "a defeat by a very large margin", example: "What was billed as a close contest turned into a 7–0 rout.", zh: "慘敗；大勝" },
    { front: "thrash", pos: "v.", def: "to defeat an opponent very easily and decisively (informal)", example: "The visitors were thrashed six-nil in front of their travelling fans.", zh: "痛宰；大敗（對手）" },
    { front: "sponsorship", pos: "n.", def: "financial support given to a team or event in return for advertising", example: "Losing its main sponsorship deal left the club in financial trouble.", zh: "贊助" },
    { front: "doping", pos: "n.", def: "the use of banned drugs to improve sporting performance", example: "The federation introduced random testing to combat doping.", zh: "使用禁藥" },
    { front: "hooliganism", pos: "n.", def: "violent and destructive behaviour by sports fans", example: "Stadium bans in the 1990s sharply reduced football hooliganism.", zh: "（球迷）暴力行為" },
    { front: "sportsmanship", pos: "n.", def: "fair, generous, and polite behaviour in sport", example: "She was applauded for her sportsmanship after conceding the disputed point.", zh: "運動家精神" },
    { front: "dexterity", pos: "n.", def: "skill in using your hands or body with quick, precise movements", example: "Table tennis at this level demands astonishing dexterity.", zh: "靈巧" },
    { front: "nimble", pos: "adj.", def: "quick and light in movement; agile", example: "The nimble winger slipped past three defenders in as many seconds.", zh: "敏捷的；靈活的" },
    { front: "hurdle", pos: "n.", def: "a barrier to jump over in a race; an obstacle to overcome", example: "Qualifying was only the first hurdle on the road to the final.", zh: "跨欄；障礙" },
    { front: "momentum", pos: "n.", def: "the force that keeps something moving or developing after it has started", example: "After two quick goals, the momentum swung entirely to the home side.", zh: "動能；氣勢" },
    { front: "morale", pos: "n.", def: "the level of confidence and enthusiasm of a person or group", example: "The captain's return gave a huge boost to team morale.", zh: "士氣" },
    { front: "grit", pos: "n.", def: "courage and determination in the face of difficulty", example: "It took real grit to finish the race on an injured ankle.", zh: "膽識；不屈不撓" },
    { front: "prowess", pos: "n.", def: "great skill or ability, especially in sport or fighting", example: "His sporting prowess earned him scholarships from three universities.", zh: "非凡的本領" },
    { front: "podium", pos: "n.", def: "the platform where the top three finishers stand to receive medals", example: "She finally reached the podium at her fourth Olympic Games.", zh: "頒獎台" },
    { front: "novice", pos: "n.", def: "a person who is new to and inexperienced in an activity", example: "The club runs separate sessions for novices and advanced rowers.", zh: "新手" },
    { front: "rookie", pos: "n.", def: "someone in their first year of a sport or job (informal)", example: "The rookie stunned the league by outscoring several veterans.", zh: "菜鳥；新秀" },
    { front: "relegation", pos: "n.", def: "the moving of a team down to a lower division", example: "A last-minute equaliser saved the club from relegation.", zh: "降級" },
    { front: "knockout", pos: "n.", def: "a blow that ends a boxing match; a competition stage where losers are eliminated", example: "The tournament moves to the knockout stage next week.", zh: "擊倒；淘汰賽" },
    { front: "rivalry", pos: "n.", def: "a state of ongoing competition between people or teams", example: "The rivalry between the two cities dates back over a century.", zh: "競爭；對抗" },
    { front: "surpass", pos: "v.", def: "to do or be better than someone or something", example: "Her time surpassed the national record by almost a second.", zh: "超越" },
    { front: "excel", pos: "v.", def: "to be extremely good at something", example: "He excels at long-distance events but struggles in sprints.", zh: "擅長；表現出色" },
    { front: "outperform", pos: "v.", def: "to perform better than someone or something else", example: "The academy players consistently outperform recruits from bigger clubs.", zh: "表現優於" },
    { front: "outdo", pos: "v.", def: "to be better than someone else at something, often competitively", example: "Each gymnast tried to outdo the last with an even riskier routine.", zh: "勝過；比……更出色" },
    { front: "spectator", pos: "n.", def: "a person who watches a sports event or show", example: "Over eighty thousand spectators packed the stadium for the final.", zh: "觀眾" },
    { front: "umpire", pos: "n.", def: "the official who enforces the rules in sports such as tennis and cricket", example: "The umpire overruled the line judge after checking the replay.", zh: "裁判（網球、板球等）" },
    { front: "taunt", pos: "v.", def: "to provoke or mock someone with insulting remarks", example: "Rival fans taunted the striker every time he touched the ball.", zh: "嘲弄；奚落" },
    { front: "warm up", pos: "phr. v.", def: "to prepare your body for exercise with gentle movements", example: "Always warm up thoroughly before attempting heavy lifts.", zh: "熱身" },
    { front: "knock out", pos: "phr. v.", def: "to eliminate an opponent from a competition; to make someone unconscious", example: "The holders were knocked out in the quarter-finals by a second-division side.", zh: "淘汰；擊昏" },
    { front: "bow out", pos: "phr. v.", def: "to retire or withdraw from an activity, especially with dignity", example: "The veteran captain bowed out of international rugby after the World Cup.", zh: "光榮退出；引退" },
    { front: "pull ahead", pos: "phr. v.", def: "to move into the lead in a race or contest", example: "On the final bend she pulled ahead and never looked back.", zh: "領先；超前" },
    { front: "lag behind", pos: "phr. v.", def: "to move or develop more slowly than others", example: "The team lagged behind early but closed the gap in the second half.", zh: "落後" },
    { front: "edge out", pos: "phr. v.", def: "to beat someone by a very small margin", example: "She edged out the defending champion by two hundredths of a second.", zh: "險勝" },
    { front: "face off", pos: "phr. v.", def: "to compete or confront each other directly", example: "The two unbeaten teams face off in Sunday's showpiece final.", zh: "對決" },
    { front: "go through", pos: "phr. v.", def: "to advance to the next stage of a competition", example: "A draw is enough for them to go through to the semi-finals.", zh: "晉級" },
    { front: "fight back", pos: "phr. v.", def: "to make an effort to recover from a losing position", example: "Two sets down, he fought back to force a deciding fifth set.", zh: "反擊；奮起直追" },
    { front: "pull off", pos: "phr. v.", def: "to succeed in doing something difficult", example: "Nobody believed they could pull off a win away from home, but they did.", zh: "成功做到；辦成" },
    { front: "shape up", pos: "phr. v.", def: "to improve your fitness, behaviour, or performance", example: "The coach warned the squad to shape up before the qualifiers.", zh: "改進；練出好狀態" },
    { front: "team up", pos: "phr. v.", def: "to join with someone to work or compete together", example: "The two former rivals teamed up to enter the doubles tournament.", zh: "合作；組隊" },
    { front: "try out", pos: "phr. v.", def: "to compete for a place on a team; to test something", example: "Hundreds of hopefuls tried out for the last three squad places.", zh: "選拔；試用" },
    { front: "sit out", pos: "phr. v.", def: "to not take part in a game or activity, often because of injury", example: "The striker will sit out the next two matches with a hamstring strain.", zh: "缺席；不上場" },
    { front: "cheer on", pos: "phr. v.", def: "to shout encouragement to a competitor or team", example: "Thousands lined the route to cheer on the runners.", zh: "為……加油" },
    { front: "ease off", pos: "phr. v.", def: "to reduce the intensity of effort or pressure", example: "Leading by twenty points, the champions eased off in the final quarter.", zh: "放鬆；減緩" },
    { front: "power through", pos: "phr. v.", def: "to keep going with strength and determination despite difficulty", example: "Exhausted and cramping, she powered through the last five kilometres.", zh: "咬牙撐過" },
    { front: "square up to", pos: "phr. v.", def: "to face an opponent or difficult situation with determination", example: "The challenger squared up to the champion at the weigh-in.", zh: "正面迎戰；直面" },
    { front: "walk away with", pos: "phr. v.", def: "to win something easily", example: "The favourites walked away with the trophy without conceding a single game.", zh: "輕鬆贏得" },
    { front: "move the goalposts", pos: "idiom", def: "to unfairly change the rules or conditions while something is in progress", example: "Every time we met the target, management moved the goalposts.", zh: "任意改變規則（標準）" },
    { front: "raise the bar", pos: "idiom", def: "to set a higher standard for others to reach", example: "Her flawless routine raised the bar for every gymnast who followed.", zh: "提高標準" },
    { front: "neck and neck", pos: "idiom", def: "level with each other in a race or competition", example: "The two candidates are neck and neck with a week to go.", zh: "並駕齊驅；不相上下" },
    { front: "against all odds", pos: "idiom", def: "despite very low chances of success", example: "Against all odds, the part-time players reached the cup final.", zh: "排除萬難；出乎意料地" },
    { front: "throw in the towel", pos: "idiom", def: "to admit defeat and stop trying", example: "Despite three failed attempts, she refuses to throw in the towel.", zh: "認輸；放棄" },
    { front: "the ball is in your court", pos: "idiom", def: "it is now your turn to act or respond", example: "We have made our final offer, so the ball is in their court.", zh: "輪到你決定（行動）" },
    { front: "keep your eye on the ball", pos: "idiom", def: "to stay focused on what is most important", example: "With so many distractions, the manager urged the team to keep their eye on the ball.", zh: "保持專注" },
    { front: "a whole new ball game", pos: "idiom", def: "a completely different situation from before", example: "Coaching juniors was fun, but managing professionals is a whole new ball game.", zh: "全新的局面" },
    { front: "a front runner", pos: "collocation", def: "the competitor considered most likely to win", example: "After her semi-final performance, she is the clear front runner for gold.", zh: "領先者；奪冠熱門" },
    { front: "set the pace", pos: "collocation", def: "to lead in a race or field, forcing others to match your speed or standard", example: "The Kenyan runners set the pace from the opening lap.", zh: "領跑；定調" },
    { front: "clinch the title", pos: "collocation", def: "to finally win a championship after a close contest", example: "A nervy one-nil victory was enough to clinch the title.", zh: "奪冠；鎖定冠軍" },
    { front: "home advantage", pos: "collocation", def: "the benefit a team gains from playing at its own ground", example: "Backed by a deafening crowd, they made full use of home advantage.", zh: "主場優勢" },
    { front: "a photo finish", pos: "collocation", def: "a race finish so close that a photograph is needed to decide the winner", example: "The hundred metres ended in a photo finish, decided by millimetres.", zh: "終點攝影判定的險勝" },
    { front: "a false start", pos: "collocation", def: "a start before the signal in a race; an unsuccessful beginning", example: "After two false starts, the sprinters were visibly on edge.", zh: "偷跑；失敗的開端" },
    { front: "jump the gun", pos: "idiom", def: "to act too soon, before the proper time", example: "Announcing the signing before the contract was signed was jumping the gun.", zh: "操之過急；搶先行動" }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
