/* CPE Prep extra bank: part2 wave 1 */
(function () {
  var BANK = [
    { text: "____ what may, she was determined to see the project through to completion.", answers: ["come"], explanation: "'Come what may' is a fixed subjunctive expression meaning 'whatever happens'." },
    { text: "The scheme, far ____ reducing congestion, has actually made traffic in the city centre worse.", answers: ["from"], explanation: "'Far from doing X' means 'instead of doing X at all', introducing a contrast." },
    { text: "He would sooner resign ____ compromise his principles.", answers: ["than"], explanation: "'Would sooner X than Y' expresses preference, parallel to 'would rather... than'." },
    { text: "Not ____ did the storm destroy the harvest, but it also left thousands without power.", answers: ["only"], explanation: "'Not only... but also' with inversion: 'Not only did the storm destroy...'." },
    { text: "____ regard to your recent enquiry, please find our brochure enclosed.", answers: ["with", "in"], explanation: "'With regard to' and 'in regard to' are both fixed formal expressions meaning 'concerning'." },
    { text: "The findings should be treated with caution, ____ the more so given the small sample size.", answers: ["all"], explanation: "'All the more so' intensifies a previous statement: 'even more, for this reason'." },
    { text: "Try ____ she might, she could not open the jar.", answers: ["as", "though"], explanation: "Concessive inversion 'Try as/though she might' means 'however hard she tried'." },
    { text: "No sooner ____ the curtain risen than a murmur ran through the audience.", answers: ["had"], explanation: "'No sooner had X happened than Y' — fronted negative adverbial forces inversion with 'had'." },
    { text: "It was only when the results were published ____ the full extent of the fraud became apparent.", answers: ["that"], explanation: "Cleft sentence: 'It was only when... that...' — 'that' introduces the focused clause." },
    { text: "____ being a gifted linguist, she is also an accomplished pianist.", answers: ["besides"], explanation: "'Besides being X, she is also Y' means 'in addition to being X'." },
    { text: "Much ____ I admire his tenacity, I cannot condone his methods.", answers: ["as", "though"], explanation: "'Much as/though I admire...' is a concessive structure meaning 'although I greatly admire'." },
    { text: "The concert was called ____ at the last minute owing to the soloist's illness.", answers: ["off"], explanation: "Phrasal verb 'call off' means 'cancel'." },
    { text: "She takes ____ her mother in more ways than one.", answers: ["after"], explanation: "'Take after someone' means to resemble a parent or relative." },
    { text: "The negotiations broke ____ amid mutual recriminations.", answers: ["down", "off"], explanation: "'Break down' (collapse) and 'break off' (be abruptly ended) both describe failed negotiations." },
    { text: "____ it not for her scholarship, she would be unable to continue her studies.", answers: ["were"], explanation: "Inverted second conditional: 'Were it not for X' = 'If it were not for X'." },
    { text: "Strange ____ it may seem, he had never once set foot outside his native village.", answers: ["as", "though"], explanation: "Concessive fronting: 'Strange as/though it may seem' = 'although it may seem strange'." },
    { text: "The minister declined to comment, ____ was to be expected.", answers: ["as", "which"], explanation: "Both 'as was to be expected' and 'which was to be expected' comment on the whole preceding clause." },
    { text: "By no ____ is the problem confined to urban areas.", answers: ["means"], explanation: "'By no means' = 'not at all'; fronted, it triggers inversion ('is the problem...')." },
    { text: "In no ____ should this document be construed as legal advice.", answers: ["way", "sense"], explanation: "'In no way/sense' is a fronted negative phrase forcing inversion with 'should'." },
    { text: "____ the fact that he had trained for months, he failed to finish the race.", answers: ["despite", "notwithstanding"], explanation: "'Despite/Notwithstanding the fact that...' introduces a concession before a noun clause." },
    { text: "The company's success is due in no small ____ to its loyal workforce.", answers: ["part", "measure", "degree"], explanation: "'In no small part/measure/degree' is an understated way of saying 'to a large extent'." },
    { text: "Suffice it to ____ that the meeting did not go as planned.", answers: ["say"], explanation: "'Suffice it to say' is a fixed formula meaning 'it is enough to say'." },
    { text: "He was, ____ it were, a prisoner of his own success.", answers: ["as"], explanation: "'As it were' is a fixed parenthetical meaning 'so to speak'." },
    { text: "I would rather you ____ not mention this to anyone just yet.", answers: ["did"], explanation: "'Would rather + subject' takes a past-tense verb for present reference: 'I'd rather you did not...'." },
    { text: "Rarely ____ so much been owed by so many to so few.", answers: ["has", "had"], explanation: "Fronted 'rarely' forces inversion of the perfect auxiliary: 'Rarely has/had so much been owed'." },
    { text: "The report stops ____ of recommending outright prohibition.", answers: ["short"], explanation: "'Stop short of doing X' means to almost do X but not quite." },
    { text: "____ of the three candidates impressed the panel, so the position was re-advertised.", answers: ["none"], explanation: "'None of the three' — 'neither' is impossible because there are more than two." },
    { text: "What with the strikes ____ the fuel shortages, the tourist season was a disaster.", answers: ["and"], explanation: "'What with X and Y' lists cumulative causes of a (usually negative) situation." },
    { text: "To all ____ and purposes, the negotiations are over.", answers: ["intents"], explanation: "'To all intents and purposes' is a fixed phrase meaning 'in effect, virtually'." },
    { text: "The witness's account was at ____ with the forensic evidence.", answers: ["odds", "variance"], explanation: "'At odds with' and 'at variance with' both mean 'in conflict with'." },
    { text: "Not until much later ____ she learn the truth about her inheritance.", answers: ["did"], explanation: "Fronted 'Not until...' forces inversion with the dummy auxiliary 'did' before the bare verb 'learn'." },
    { text: "The two sides remain poles ____ on the question of immigration.", answers: ["apart"], explanation: "'Poles apart' is a fixed expression meaning 'completely opposed'." },
    { text: "She has an uncanny knack ____ saying precisely the wrong thing.", answers: ["of", "for"], explanation: "'A knack of/for doing something' — both prepositions are standard after 'knack'." },
    { text: "It goes without ____ that punctuality is essential in this line of work.", answers: ["saying"], explanation: "'It goes without saying' is a fixed phrase meaning 'it is obvious'." },
    { text: "The paintings fetched far more at auction ____ anyone had predicted.", answers: ["than"], explanation: "The comparative 'far more' requires 'than' to introduce the comparison clause." },
    { text: "Only later ____ the significance of the discovery become clear.", answers: ["did"], explanation: "Fronted 'Only later' triggers inversion; the bare verb 'become' requires the auxiliary 'did'." },
    { text: "The government has ruled ____ any further tax increases this year.", answers: ["out"], explanation: "'Rule out' means to exclude something as a possibility." },
    { text: "I am writing ____ behalf of the residents' association.", answers: ["on"], explanation: "'On behalf of' means 'as the representative of'." },
    { text: "The distinction between the two terms is more apparent ____ real.", answers: ["than"], explanation: "'More X than Y' — the comparison of two adjectives requires 'than'." },
    { text: "____ a rule, applications received after the deadline are not considered.", answers: ["as"], explanation: "'As a rule' is a fixed phrase meaning 'generally, usually'." },
    { text: "He is nothing if ____ persistent.", answers: ["not"], explanation: "'Nothing if not X' is an emphatic way of saying 'extremely X'." },
    { text: "The bridge may be closed for repairs, ____ which case you should take the ferry.", answers: ["in"], explanation: "'In which case' refers back to the possibility just mentioned." },
    { text: "Her latest novel, ____ critics have hailed as her finest, took a decade to write.", answers: ["which"], explanation: "Non-defining relative clause with a fronted object: 'which critics have hailed as...'." },
    { text: "____ whom should I address my complaint?", answers: ["to"], explanation: "Formal fronted preposition: 'To whom should I address...' ('address something to someone')." },
    { text: "The scandal came to light ____ chance, during a routine audit.", answers: ["by"], explanation: "'By chance' is a fixed phrase meaning 'accidentally'." },
    { text: "All flights were grounded ____ account of the volcanic ash.", answers: ["on"], explanation: "'On account of' means 'because of'." },
    { text: "The strike, now in its third week, shows no sign ____ ending.", answers: ["of"], explanation: "'Show no sign of doing something' takes the preposition 'of' plus a gerund." },
    { text: "____ we to lower our prices, our margins would become unsustainable.", answers: ["were"], explanation: "Inverted hypothetical conditional: 'Were we to X' = 'If we were to X'." },
    { text: "You may borrow the car ____ long as you return it by Sunday.", answers: ["as", "so"], explanation: "'As long as' and 'so long as' both mean 'on condition that'." },
    { text: "He insisted ____ paying for the meal, despite our protests.", answers: ["on", "upon"], explanation: "'Insist on/upon doing something' is the required prepositional pattern." },
    { text: "There being no further business, the meeting was brought ____ a close.", answers: ["to"], explanation: "'Bring something to a close' is a fixed expression meaning 'end it'." },
    { text: "The committee comprises twelve members, all ____ whom are elected representatives.", answers: ["of"], explanation: "Quantifier + 'of whom' in a non-defining relative clause: 'all of whom'." },
    { text: "So absorbed ____ she in her book that she failed to notice the storm.", answers: ["was"], explanation: "Fronted 'So + adjective' forces inversion: 'So absorbed was she... that...'." },
    { text: "In the ____ of any concrete evidence, the case was dismissed.", answers: ["absence"], explanation: "'In the absence of' means 'because there was none'." },
    { text: "The two theories are not mutually exclusive; ____ the contrary, they complement each other.", answers: ["on", "quite"], explanation: "'On the contrary' (or 'quite the contrary') rejects the previous idea and asserts the opposite." },
    { text: "It is essential that every applicant ____ interviewed in person.", answers: ["be", "is"], explanation: "After 'essential that', the subjunctive 'be' is standard; British English also allows indicative 'is'." },
    { text: "Nowhere in the report ____ there any mention of the cost overruns.", answers: ["is", "was"], explanation: "Fronted negative 'Nowhere' forces inversion: 'Nowhere... is/was there any mention'." },
    { text: "The festival attracts visitors from far and ____.", answers: ["wide"], explanation: "'From far and wide' is a fixed phrase meaning 'from many different places'." },
    { text: "He has long ____ regarded as the finest pianist of his generation.", answers: ["been"], explanation: "Present perfect passive: 'has long been regarded as'." },
    { text: "Scarcely ____ the ink dried on the contract when the dispute began.", answers: ["had"], explanation: "'Scarcely had X happened when Y' — fronted 'scarcely' triggers inversion with 'had'." },
    { text: "Their objections notwithstanding, the merger went ____ as planned.", answers: ["ahead", "through"], explanation: "'Go ahead' and 'go through' both mean the deal proceeded/was completed as planned." },
    { text: "Success in this field depends as much on luck ____ on talent.", answers: ["as"], explanation: "The equative structure 'as much on X as on Y' requires a second 'as'." },
    { text: "____ from a brief stint in journalism, he has spent his entire career in academia.", answers: ["apart", "aside"], explanation: "'Apart from' and 'aside from' both mean 'except for'." },
    { text: "The manuscript is thought to date ____ to the twelfth century.", answers: ["back"], explanation: "'Date back to' means 'to have existed since'." },
    { text: "The lecture was pitched ____ a level that even novices could follow.", answers: ["at"], explanation: "'Pitch something at a level' means to set its degree of difficulty." },
    { text: "Little short ____ a miracle can save the company now.", answers: ["of"], explanation: "'Little/nothing short of a miracle' means 'almost/actually a miracle'." },
    { text: "The proposal met ____ fierce resistance from local farmers.", answers: ["with"], explanation: "'Meet with resistance/approval' means to receive that reaction." },
    { text: "The refugees were deprived ____ even the most basic amenities.", answers: ["of"], explanation: "'Deprive someone of something' is the required prepositional pattern." },
    { text: "____ no circumstances are visitors permitted beyond this point.", answers: ["under", "in"], explanation: "'Under/In no circumstances' is a fronted negative phrase triggering inversion ('are visitors permitted')." },
    { text: "It took years for the truth to come ____, and when it did, careers were ruined.", answers: ["out"], explanation: "'Come out' means 'become publicly known' (of the truth, a secret)." },
    { text: "He was arrested on suspicion ____ fraud.", answers: ["of"], explanation: "'On suspicion of' is the fixed legal phrase." },
    { text: "The town lies ____ easy reach of two international airports.", answers: ["within", "in"], explanation: "'Within (or in) easy reach of' means 'close enough to get to easily'." },
    { text: "Her success owes more to perseverance than ____ raw talent.", answers: ["to"], explanation: "Parallel structure: 'owes more to X than to Y'." },
    { text: "I have yet ____ meet anyone who can match her energy.", answers: ["to"], explanation: "'Have yet to do something' means 'have still not done it'." },
    { text: "The negotiations are at a delicate stage; on no ____ must the press get wind of them.", answers: ["account"], explanation: "'On no account' means 'absolutely not', and fronted it forces inversion with 'must'." },
    { text: "The painting turned out to be a forgery, as ____ many others in the collection.", answers: ["did", "were"], explanation: "Ellipsis after 'as': 'as did many others' (turned out) or 'as were many others' (forgeries)." },
    { text: "When all ____ said and done, it is the taxpayer who foots the bill.", answers: ["is"], explanation: "'When all is said and done' is a fixed phrase meaning 'ultimately'." },
    { text: "The chairman, ____ whose leadership the firm prospered, retires this year.", answers: ["under"], explanation: "'Under someone's leadership' — the preposition is fronted before 'whose' in the relative clause." },
    { text: "____ we not intervened, the two species would have vanished entirely.", answers: ["had"], explanation: "Inverted third conditional: 'Had we not intervened' = 'If we had not intervened'." },
    { text: "The new regulations apply to residents and visitors ____.", answers: ["alike"], explanation: "'X and Y alike' means 'both X and Y equally'." },
    { text: "He wormed his way ____ the manager's confidence.", answers: ["into"], explanation: "'Worm one's way into someone's confidence' means to gain their trust by cunning." },
    { text: "Nothing ____ of complete surrender would satisfy the invaders.", answers: ["short"], explanation: "'Nothing short of X' means 'only X, and no less'." },
    { text: "Many a scholar ____ tried and failed to decipher the script.", answers: ["has"], explanation: "'Many a + singular noun' takes a singular verb: 'Many a scholar has tried'." },
    { text: "We had no choice ____ to comply with the court order.", answers: ["but", "except"], explanation: "'No choice but/except to do something' means it was the only option." },
    { text: "The deal fell ____ at the eleventh hour over financing.", answers: ["through", "apart"], explanation: "'Fall through' (fail to be completed) and 'fall apart' (collapse) both fit a failed deal." },
    { text: "____ himself an outsider, he sympathised with the newcomers' plight.", answers: ["being"], explanation: "Participle clause giving a reason: 'Being himself an outsider, he...'." },
    { text: "Public opinion turned ____ the government once the scale of the losses emerged.", answers: ["against", "on"], explanation: "'Turn against/on someone' means to become hostile towards them." },
    { text: "The book is dedicated to his wife, without ____ unfailing support it would never have been written.", answers: ["whose"], explanation: "Possessive relative: 'without whose unfailing support' = 'without her unfailing support'." },
    { text: "It was with considerable reluctance ____ she agreed to testify.", answers: ["that"], explanation: "Cleft sentence: 'It was with X that she agreed' emphasises the adverbial phrase." },
    { text: "The expedition went remarkably smoothly, ____ for the odd equipment failure.", answers: ["save", "except", "but"], explanation: "'Save/except/but for' means 'apart from', introducing the only exception." },
    { text: "Rumour has ____ that the CEO is about to resign.", answers: ["it"], explanation: "'Rumour has it that...' is a fixed phrase meaning 'people are saying that'." },
    { text: "The two countries are technically still ____ war, six decades after the armistice.", answers: ["at"], explanation: "'At war' is the fixed prepositional phrase for a state of conflict." },
    { text: "She would go to any lengths, by fair means or ____, to secure the contract.", answers: ["foul"], explanation: "'By fair means or foul' is a fixed phrase meaning 'by any method, honest or not'." },
    { text: "The audit brought to ____ a series of financial irregularities.", answers: ["light"], explanation: "'Bring something to light' means to reveal it." },
    { text: "You can't help ____ admire her audacity.", answers: ["but"], explanation: "'Can't help but + bare infinitive' means 'cannot avoid doing'." },
    { text: "The higher the stakes, ____ greater the temptation to cheat.", answers: ["the"], explanation: "Correlative comparative: 'The higher X, the greater Y'." },
    { text: "He is by ____ the most experienced member of the team.", answers: ["far"], explanation: "'By far' intensifies a superlative." },
    { text: "The theory has since been called ____ question by new findings.", answers: ["into", "in"], explanation: "'Call into question' (also 'call in question') means to cast doubt on." },
    { text: "____ the event of fire, do not use the lifts.", answers: ["in"], explanation: "'In the event of' means 'if X happens'." },
    { text: "The soprano's performance was, quite simply, second to ____.", answers: ["none"], explanation: "'Second to none' means 'the best; inferior to nobody'." },
    { text: "Their demands were dismissed out of ____.", answers: ["hand"], explanation: "'Dismiss something out of hand' means to reject it immediately without consideration." },
    { text: "It stands ____ reason that prevention is better than cure.", answers: ["to"], explanation: "'It stands to reason that...' means 'it is logical that'." },
    { text: "The witness swore that at no ____ had she left the building.", answers: ["point", "time", "stage"], explanation: "'At no point/time/stage' is a fronted negative phrase triggering inversion ('had she left')." },
    { text: "We arrived early ____ as to secure good seats.", answers: ["so"], explanation: "'So as to + infinitive' expresses purpose." },
    { text: "____ small the donation, every contribution is gratefully received.", answers: ["however"], explanation: "'However + adjective' means 'no matter how small'." },
    { text: "The project was abandoned, largely ____ to a shortage of funds.", answers: ["due", "owing"], explanation: "'Due to' and 'owing to' both mean 'because of'." },
    { text: "He talked at length about his travels, most of ____ I had heard before.", answers: ["which"], explanation: "Quantifier + 'of which' referring back to the things he said: 'most of which'." },
    { text: "Not for one moment ____ I doubt her sincerity when she made that promise.", answers: ["did"], explanation: "Fronted 'Not for one moment' forces inversion with the past auxiliary 'did'." },
    { text: "So poorly ____ the campaign managed that the party lost even its safest seats.", answers: ["was"], explanation: "Fronted 'So + adverb' forces inversion: 'So poorly was the campaign managed'." },
    { text: "In answer ____ your question, the results will be published in May.", answers: ["to"], explanation: "'In answer to' is the fixed phrase for responding to a question." },
    { text: "Whether by accident or ____, the file had been deleted.", answers: ["design"], explanation: "'By accident or design' means 'whether intentionally or not'." },
    { text: "____ whatever reason, he never claimed the prize money.", answers: ["for"], explanation: "'For whatever reason' means 'whatever the cause may have been'." },
    { text: "The mayor's promises came to ____ once the election was over.", answers: ["nothing", "naught", "nought"], explanation: "'Come to nothing/naught' means to fail to produce any result." },
    { text: "Never ____ met her before, I was struck by how familiar she seemed.", answers: ["having"], explanation: "Negative perfect participle clause: 'Never having met her before' = 'Although I had never met her'." },
    { text: "The costs, ____ estimates suggest could reach billions, will be borne by taxpayers.", answers: ["which"], explanation: "Relative clause with an embedded reporting verb: 'which (estimates suggest) could reach billions'." },
    { text: "He put his success ____ to sheer luck.", answers: ["down"], explanation: "'Put something down to' means to attribute it to a cause." },
    { text: "Not once ____ the entire journey did he complain.", answers: ["during", "in", "throughout"], explanation: "A preposition of duration completes 'Not once during/in/throughout the journey', with inversion following." },
    { text: "Time and ____, history has shown that such measures fail.", answers: ["again"], explanation: "'Time and again' means 'repeatedly'." },
    { text: "His promises, more often than ____, come to nothing.", answers: ["not"], explanation: "'More often than not' means 'usually'." },
    { text: "Far ____ it from me to criticise, but the accounts simply don't add up.", answers: ["be"], explanation: "'Far be it from me to...' is a fixed subjunctive formula disclaiming any wish to do something." }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part2 = QUESTIONS.part2.concat(BANK);
})();
