/* CPE Prep extra vocab wave 3 */
(function () {
  var BANK = [
  { front: "prevaricate", pos: "v.", def: "speak evasively to avoid telling the truth", example: "The minister prevaricated when pressed on the leaked memo.", zh: "支吾其詞、閃爍其詞" },
  { front: "proclivity", pos: "n.", def: "a natural tendency towards something", example: "His proclivity for risk unnerved the more cautious board members.", zh: "傾向、癖好" },
  { front: "prodigious", pos: "adj.", def: "remarkably great in extent or ability", example: "She composed a prodigious body of work before turning thirty.", zh: "驚人的、龐大的" },
  { front: "promulgate", pos: "v.", def: "promote or make widely known officially", example: "The regime promulgated decrees restricting foreign broadcasts.", zh: "頒布、公布" },
  { front: "protracted", pos: "adj.", def: "lasting longer than expected or necessary", example: "Protracted negotiations sapped the union's bargaining power.", zh: "拖延的、曠日廢時的" },
  { front: "prowess", pos: "n.", def: "exceptional skill or ability", example: "Her diplomatic prowess averted an embarrassing rupture between the allies.", zh: "高超技藝、本領" },
  { front: "puerile", pos: "adj.", def: "childishly silly and immature", example: "Critics dismissed the satire as puerile rather than incisive.", zh: "幼稚的、孩子氣的" },
  { front: "pugnacious", pos: "adj.", def: "eager or quick to argue or fight", example: "His pugnacious interviewing style alienated several guests.", zh: "好鬥的、好爭論的" },
  { front: "punctilious", pos: "adj.", def: "showing great attention to correct behaviour or detail", example: "A punctilious editor caught the misattributed quotation at once.", zh: "一絲不苟的、拘泥細節的" },
  { front: "pundit", pos: "n.", def: "an expert who gives opinions publicly", example: "Television pundits confidently predicted a landslide that never materialised.", zh: "權威評論家、名嘴" },
  { front: "punitive", pos: "adj.", def: "intended as punishment; unduly harsh", example: "Punitive tariffs did little but inflame the trade dispute.", zh: "懲罰性的" },
  { front: "purloin", pos: "v.", def: "steal, especially something of small value", example: "He was caught purloining stationery from the supply cupboard.", zh: "偷竊、竊取" },
  { front: "pusillanimous", pos: "adj.", def: "lacking courage; timid", example: "The editorial branded the cabinet's retreat pusillanimous.", zh: "膽怯的、懦弱的" },
  { front: "putative", pos: "adj.", def: "generally supposed or assumed to be", example: "The putative author of the pamphlet was never conclusively identified.", zh: "推定的、公認的" },
  { front: "quagmire", pos: "n.", def: "a difficult, entangled situation", example: "The intervention degenerated into a diplomatic quagmire.", zh: "困境、泥沼" },
  { front: "qualm", pos: "n.", def: "an uneasy feeling of doubt or misgiving", example: "She had no qualms about exposing her employer's malpractice.", zh: "疑慮、不安" },
  { front: "quandary", pos: "n.", def: "a state of uncertainty over a choice", example: "The verdict left regulators in a quandary about enforcement.", zh: "左右為難、困惑" },
  { front: "quash", pos: "v.", def: "reject as invalid; suppress completely", example: "The appeal court quashed the conviction on procedural grounds.", zh: "撤銷、鎮壓" },
  { front: "quell", pos: "v.", def: "put an end to, typically by force", example: "Troops were deployed to quell the escalating unrest.", zh: "平息、鎮壓" },
  { front: "querulous", pos: "adj.", def: "habitually complaining in a petulant way", example: "His querulous letters to the council went unanswered.", zh: "愛抱怨的、牢騷滿腹的" },
  { front: "quibble", pos: "v.", def: "argue about trivial matters", example: "Let us not quibble over semantics when the principle is clear.", zh: "吹毛求疵、爭辯瑣事" },
  { front: "quiescent", pos: "adj.", def: "inactive or dormant for a period", example: "The volcano has remained quiescent for over a century.", zh: "靜止的、休眠的" },
  { front: "quotidian", pos: "adj.", def: "ordinary and occurring every day", example: "The novel elevates quotidian routines into something luminous.", zh: "日常的、平凡的" },
  { front: "rancour", pos: "n.", def: "bitter, long-lasting resentment", example: "The settlement was reached without apparent rancour on either side.", zh: "積怨、怨恨" },
  { front: "rankle", pos: "v.", def: "cause continuing annoyance or resentment", example: "The snub still rankles with her a decade later.", zh: "使耿耿於懷、令人怨恨" },
  { front: "rapacious", pos: "adj.", def: "aggressively greedy or grasping", example: "Rapacious lenders preyed on households already in arrears.", zh: "貪婪的、強取豪奪的" },
  { front: "rapprochement", pos: "n.", def: "a resumption of harmonious relations", example: "The summit signalled a cautious rapprochement between the estranged powers.", zh: "恢復邦交、和解" },
  { front: "raucous", pos: "adj.", def: "harshly loud and disorderly", example: "A raucous crowd drowned out the visiting speaker.", zh: "沙啞刺耳的、喧鬧的" },
  { front: "ravage", pos: "v.", def: "cause severe and extensive damage to", example: "Successive droughts have ravaged the region's smallholdings.", zh: "蹂躪、嚴重破壞" },
  { front: "raze", pos: "v.", def: "completely destroy a building or town", example: "Entire districts were razed to make way for the expressway.", zh: "夷為平地、徹底摧毀" },
  { front: "rebuff", pos: "v.", def: "reject an offer or advance bluntly", example: "The board rebuffed the takeover bid without deliberation.", zh: "斷然拒絕、回絕" },
  { front: "rebuke", pos: "v.", def: "criticise or reprimand sharply", example: "The judge rebuked counsel for the theatrical outburst.", zh: "斥責、指責" },
  { front: "recant", pos: "v.", def: "formally withdraw a previously held belief", example: "Under duress, the scientist recanted his heretical findings.", zh: "公開撤回、翻供" },
  { front: "recidivism", pos: "n.", def: "the tendency to relapse into crime", example: "Vocational training measurably reduced recidivism among young offenders.", zh: "再犯、累犯行為" },
  { front: "reclusive", pos: "adj.", def: "avoiding the company of others", example: "The reclusive novelist declined every interview for forty years.", zh: "隱居的、遁世的" },
  { front: "recrimination", pos: "n.", def: "an accusation made in response to another", example: "The failed merger dissolved into mutual recrimination.", zh: "反責、互相指責" },
  { front: "rectitude", pos: "n.", def: "morally correct behaviour or thinking", example: "Her reputation for rectitude made the allegations scarcely credible.", zh: "正直、公正" },
  { front: "redolent", pos: "adj.", def: "strongly reminiscent or suggestive of something", example: "The prose is redolent of a vanished colonial era.", zh: "使人聯想的、散發氣息的" },
  { front: "redoubtable", pos: "adj.", def: "formidable and worthy of respect", example: "She proved a redoubtable adversary in cross-examination.", zh: "可敬可畏的、難對付的" },
  { front: "redress", pos: "n.", def: "remedy or compensation for a wrong", example: "Victims of the scheme have little hope of legal redress.", zh: "賠償、糾正" },
  { front: "refractory", pos: "adj.", def: "stubbornly resistant to control or treatment", example: "The infection proved refractory to every standard antibiotic.", zh: "難駕馭的、頑固的" },
  { front: "refute", pos: "v.", def: "prove a statement or theory wrong", example: "The data comprehensively refute the claim of spontaneous recovery.", zh: "駁斥、反駁" },
  { front: "regale", pos: "v.", def: "entertain lavishly with stories or food", example: "He regaled the delegates with anecdotes from his ambassadorial days.", zh: "以趣事款待、使盡興" },
  { front: "rejoinder", pos: "n.", def: "a sharp or witty reply", example: "Her withering rejoinder silenced the heckler instantly.", zh: "機智的回答、反駁" },
  { front: "relegate", pos: "v.", def: "consign to an inferior rank or position", example: "The once-celebrated theory has been relegated to a footnote.", zh: "使降級、貶謫" },
  { front: "remiss", pos: "adj.", def: "negligent in performing a duty", example: "I would be remiss not to acknowledge my collaborators.", zh: "疏忽的、怠惰的" },
  { front: "remonstrate", pos: "v.", def: "protest forcefully against something", example: "Parents remonstrated with the governors over the abrupt closure.", zh: "抗議、規勸" },
  { front: "remuneration", pos: "n.", def: "payment for work or services", example: "Executive remuneration bore little relation to the firm's performance.", zh: "報酬、薪酬" },
  { front: "renege", pos: "v.", def: "go back on a promise or commitment", example: "The developer reneged on its pledge to fund the school.", zh: "違背諾言、食言" },
  { front: "renounce", pos: "v.", def: "formally give up a claim or belief", example: "He renounced his citizenship rather than serve the junta.", zh: "宣布放棄、棄絕" },
  { front: "replete", pos: "adj.", def: "filled or well supplied with something", example: "The archive is replete with unpublished correspondence.", zh: "充滿的、裝滿的" },
  { front: "reprehensible", pos: "adj.", def: "deserving strong condemnation", example: "Concealing the safety data was morally reprehensible.", zh: "應受譴責的" },
  { front: "reprieve", pos: "n.", def: "a temporary escape from punishment or trouble", example: "The funding extension offered the clinic only a brief reprieve.", zh: "暫緩、緩刑" },
  { front: "reproach", pos: "v.", def: "express disapproval or disappointment to someone", example: "She reproached herself for ignoring the early warnings.", zh: "責備、指摘" },
  { front: "reprobate", pos: "n.", def: "an unprincipled or immoral person", example: "The memoir paints his grandfather as a charming reprobate.", zh: "無賴、墮落者" },
  { front: "repudiate", pos: "v.", def: "refuse to accept or be associated with", example: "The party leadership repudiated the candidate's inflammatory remarks.", zh: "否認、拒絕接受" },
  { front: "repugnant", pos: "adj.", def: "extremely distasteful; abhorrent", example: "The court found the clause repugnant to basic fairness.", zh: "令人厭惡的、牴觸的" },
  { front: "rescind", pos: "v.", def: "revoke or cancel a law or agreement", example: "The university rescinded the honorary degree amid the scandal.", zh: "廢除、撤銷" },
  { front: "resolute", pos: "adj.", def: "admirably determined and unwavering", example: "She remained resolute despite mounting calls for her resignation.", zh: "堅決的、剛毅的" },
  { front: "resplendent", pos: "adj.", def: "attractive and impressive through being richly colourful", example: "The delegates arrived resplendent in ceremonial dress.", zh: "光彩奪目的、華麗的" },
  { front: "restive", pos: "adj.", def: "restless and difficult to control", example: "The restive electorate punished both established parties.", zh: "焦躁不安的、難管束的" },
  { front: "reticent", pos: "adj.", def: "reluctant to reveal one's thoughts", example: "He was famously reticent about his wartime service.", zh: "沉默寡言的、有所保留的" },
  { front: "retract", pos: "v.", def: "withdraw a statement as untrue or unjustified", example: "The journal retracted the paper after the fabrication came to light.", zh: "撤回、收回" },
  { front: "retrench", pos: "v.", def: "reduce costs or spending in response to difficulty", example: "Falling advertising revenue forced the broadcaster to retrench.", zh: "緊縮開支、裁減" },
  { front: "reverberate", pos: "v.", def: "have continuing serious effects; echo repeatedly", example: "The ruling will reverberate through employment law for decades.", zh: "迴盪、產生深遠影響" },
  { front: "reverie", pos: "n.", def: "a state of pleasantly dreamy thought", example: "The doorbell jolted her out of a mid-afternoon reverie.", zh: "幻想、白日夢" },
  { front: "revile", pos: "v.", def: "criticise in an abusive, insulting manner", example: "The collaborationist government was reviled long after the war.", zh: "辱罵、痛斥" },
  { front: "rife", pos: "adj.", def: "widespread, especially of something undesirable", example: "Speculation was rife that the chairman would be ousted.", zh: "盛行的、充斥的" },
  { front: "rift", pos: "n.", def: "a serious break in friendly relations", example: "The leaked cables exposed a deepening rift within the alliance.", zh: "裂痕、不和" },
  { front: "risible", pos: "adj.", def: "so unreasonable as to provoke laughter", example: "The official explanation was risible on its face.", zh: "可笑的、荒謬的" },
  { front: "roil", pos: "v.", def: "make turbulent or greatly disturbed", example: "Rumours of default continued to roil the bond markets.", zh: "使動盪、攪亂" },
  { front: "ruminate", pos: "v.", def: "think deeply about something", example: "He ruminated for weeks before tendering his resignation.", zh: "反覆思考、沉思" },
  { front: "ruse", pos: "n.", def: "a cunning stratagem to deceive", example: "The job advertisement was merely a ruse to gather personal data.", zh: "詭計、計謀" },
  { front: "saccharine", pos: "adj.", def: "excessively sweet or sentimental", example: "The film's saccharine ending betrays its unflinching first act.", zh: "過分甜膩的、濫情的" },
  { front: "sacrosanct", pos: "adj.", def: "regarded as too important to interfere with", example: "Ministers insisted the pension guarantee remained sacrosanct.", zh: "神聖不可侵犯的" },
  { front: "sagacious", pos: "adj.", def: "having keen judgement; wise", example: "Her sagacious counsel steered the firm through the crash.", zh: "睿智的、有遠見的" },
  { front: "salubrious", pos: "adj.", def: "healthy or pleasant, especially of surroundings", example: "They retired to a more salubrious quarter of the city.", zh: "有益健康的、宜人的" },
  { front: "salutary", pos: "adj.", def: "beneficial, though often unwelcome, in effect", example: "The near-bankruptcy was a salutary lesson in fiscal discipline.", zh: "有益的（雖不好受）" },
  { front: "sanctimonious", pos: "adj.", def: "making a hypocritical show of moral superiority", example: "His sanctimonious lectures on thrift rang hollow, given his expenses.", zh: "假裝虔誠的、道貌岸然的" },
  { front: "sanguine", pos: "adj.", def: "optimistic, especially in a bad situation", example: "Analysts remain sanguine about the sector's long-term prospects.", zh: "樂觀的、自信的" },
  { front: "sardonic", pos: "adj.", def: "grimly mocking or cynical", example: "He greeted the award with a sardonic bow.", zh: "譏諷的、冷嘲的" },
  { front: "sartorial", pos: "adj.", def: "relating to clothes or style of dress", example: "The ambassador's sartorial elegance was legendary in diplomatic circles.", zh: "服裝的、衣著上的" },
  { front: "satiate", pos: "v.", def: "satisfy fully or to excess", example: "No amount of acclaim could satiate his craving for recognition.", zh: "使饜足、使滿足" },
  { front: "saturnine", pos: "adj.", def: "gloomy and slow in temperament", example: "His saturnine demeanour concealed a mordant wit.", zh: "陰鬱的、憂鬱的" },
  { front: "savvy", pos: "adj.", def: "shrewd and knowledgeable about practical matters", example: "Savvy investors had quietly exited the fund months earlier.", zh: "精明的、有見識的" },
  { front: "scapegoat", pos: "n.", def: "a person blamed for others' wrongdoings", example: "The junior trader became a convenient scapegoat for systemic failings.", zh: "代罪羔羊、替罪羊" },
  { front: "schism", pos: "n.", def: "a split between strongly opposed factions", example: "The vote precipitated a schism within the ruling coalition.", zh: "分裂、分歧" },
  { front: "scintillating", pos: "adj.", def: "brilliantly clever and lively", example: "Her scintillating repartee made her the toast of the salon.", zh: "妙趣橫生的、才華洋溢的" },
  { front: "scoff", pos: "v.", def: "speak about something derisively", example: "Economists scoffed at the promise of painless austerity.", zh: "嘲笑、譏笑" },
  { front: "scour", pos: "v.", def: "search a place thoroughly", example: "Investigators scoured the archives for the missing ledger.", zh: "四處搜索、細查" },
  { front: "scrupulous", pos: "adj.", def: "diligently careful and morally principled", example: "She was scrupulous in declaring even trivial conflicts of interest.", zh: "一絲不苟的、審慎正直的" },
  { front: "scurrilous", pos: "adj.", def: "spreading scandalous claims to damage a reputation", example: "The scurrilous pamphlet accused the mayor of embezzlement.", zh: "誹謗的、中傷的" },
  { front: "scuttle", pos: "v.", def: "deliberately cause a plan to fail", example: "Last-minute objections scuttled the ceasefire talks.", zh: "使（計畫）失敗、破壞" },
  { front: "sedentary", pos: "adj.", def: "involving much sitting and little exercise", example: "Sedentary occupations carry well-documented cardiovascular risks.", zh: "久坐的、缺乏運動的" },
  { front: "sedition", pos: "n.", def: "conduct inciting rebellion against authority", example: "The playwright was imprisoned on a trumped-up charge of sedition.", zh: "煽動叛亂、叛國言論" },
  { front: "sedulous", pos: "adj.", def: "showing dedication and persistent diligence", example: "His sedulous cultivation of donors funded the entire wing.", zh: "勤勉的、孜孜不倦的" },
  { front: "self-effacing", pos: "adj.", def: "modest; not drawing attention to oneself", example: "The self-effacing laureate credited her entire laboratory.", zh: "謙遜的、不愛出風頭的" },
  { front: "seminal", pos: "adj.", def: "strongly influencing later developments", example: "Her seminal paper reshaped the field of behavioural economics.", zh: "開創性的、影響深遠的" },
  { front: "sententious", pos: "adj.", def: "given to pompous moralising", example: "The review dismissed the novel as sententious and overwrought.", zh: "說教的、故作莊重的" },
  { front: "sequester", pos: "v.", def: "isolate or hide away; seize legally", example: "The jury was sequestered for the duration of the trial.", zh: "使隔離、扣押" },
  { front: "serendipity", pos: "n.", def: "the occurrence of happy events by chance", example: "The antibiotic's discovery owed as much to serendipity as to design.", zh: "機緣巧合、意外的幸運" },
  { front: "serpentine", pos: "adj.", def: "winding and twisting like a snake", example: "The bill's serpentine progress through committee took two years.", zh: "蜿蜒的、迂迴的" },
  { front: "servile", pos: "adj.", def: "excessively willing to serve or please", example: "His servile deference to the chairman embarrassed the whole board.", zh: "卑躬屈膝的、奴性的" },
  { front: "shirk", pos: "v.", def: "avoid a duty or responsibility", example: "The report accuses regulators of shirking their statutory obligations.", zh: "逃避（責任）、偷懶" },
  { front: "shrewd", pos: "adj.", def: "having sharp practical judgement", example: "It was a shrewd move to secure the patents early.", zh: "精明的、敏銳的" },
  { front: "sinecure", pos: "n.", def: "a paid position requiring little work", example: "The directorship was widely regarded as a sinecure for party loyalists.", zh: "閒差、掛名職位" },
  { front: "sinuous", pos: "adj.", def: "gracefully curving and winding", example: "The road traced a sinuous path through the gorge.", zh: "蜿蜒的、曲折的" },
  { front: "skirmish", pos: "n.", def: "a minor fight or dispute", example: "The tariff row was merely the first skirmish in a longer trade war.", zh: "小衝突、前哨戰" },
  { front: "skittish", pos: "adj.", def: "nervous and easily frightened; unpredictable", example: "Skittish investors fled to gold at the first hint of contagion.", zh: "易受驚的、善變的" },
  { front: "slake", pos: "v.", def: "satisfy thirst or a desire", example: "No conquest could slake the emperor's ambition.", zh: "解（渴）、滿足" },
  { front: "slipshod", pos: "adj.", def: "carelessly done or arranged", example: "Slipshod bookkeeping concealed the fraud for years.", zh: "馬虎的、草率的" },
  { front: "slovenly", pos: "adj.", def: "untidy and careless in appearance or habits", example: "The inspector condemned the kitchen's slovenly hygiene practices.", zh: "邋遢的、懶散的" },
  { front: "smattering", pos: "n.", def: "a slight superficial knowledge or small amount", example: "He conducts business abroad with only a smattering of Mandarin.", zh: "略知皮毛、少量" },
  { front: "solace", pos: "n.", def: "comfort in sorrow or distress", example: "She found solace in music after the bereavement.", zh: "慰藉、安慰" },
  { front: "solicitous", pos: "adj.", def: "showing attentive care and concern", example: "The staff were solicitous to the point of intrusiveness.", zh: "殷勤關切的、掛念的" },
  { front: "sombre", pos: "adj.", def: "dark, gloomy, or grave in tone", example: "The anniversary was marked in appropriately sombre fashion.", zh: "陰沉的、憂鬱的" },
  { front: "somnolent", pos: "adj.", def: "sleepy; inducing drowsiness", example: "The somnolent provincial town stirred only on market days.", zh: "昏昏欲睡的、沉寂的" },
  { front: "soporific", pos: "adj.", def: "tending to induce sleep; tediously boring", example: "The minister's soporific delivery emptied the chamber.", zh: "催眠的、令人昏睡的" },
  { front: "sordid", pos: "adj.", def: "involving immoral or dishonourable actions", example: "The tabloids feasted on every sordid detail of the affair.", zh: "卑鄙的、骯髒的" },
  { front: "spartan", pos: "adj.", def: "austere; lacking comfort or luxury", example: "The training camp's spartan conditions weeded out the uncommitted.", zh: "簡樸的、艱苦的" },
  { front: "spate", pos: "n.", def: "a sudden large number of similar events", example: "A spate of resignations followed the auditor's report.", zh: "一連串、大量湧現" },
  { front: "specious", pos: "adj.", def: "superficially plausible but actually wrong", example: "The defence rested on a specious analogy that soon collapsed.", zh: "似是而非的" },
  { front: "sporadic", pos: "adj.", def: "occurring at irregular intervals", example: "Sporadic gunfire could still be heard after the ceasefire.", zh: "零星的、偶發的" },
  { front: "spurn", pos: "v.", def: "reject with disdain", example: "She spurned every overture from the rival network.", zh: "唾棄、不屑接受" },
  { front: "squalid", pos: "adj.", def: "extremely dirty and unpleasant; morally degraded", example: "Migrant workers were housed in squalid dormitories.", zh: "骯髒的、悲慘的" },
  { front: "staid", pos: "adj.", def: "sedate, respectable, and unadventurous", example: "The appointment shook up a famously staid institution.", zh: "古板的、一本正經的" },
  { front: "stagnate", pos: "v.", def: "cease developing; become inactive", example: "Wages have stagnated even as productivity has soared.", zh: "停滯、不景氣" },
  { front: "stalwart", pos: "adj.", def: "loyal, reliable, and hard-working", example: "She remained a stalwart defender of the public broadcaster.", zh: "堅定忠誠的、健壯的" },
  { front: "stark", pos: "adj.", def: "severe or bare; unpleasantly clear", example: "The report lays out the stark arithmetic of the deficit.", zh: "嚴峻的、鮮明的" },
  { front: "steadfast", pos: "adj.", def: "resolutely firm and unwavering", example: "He remained steadfast in his refusal to name sources.", zh: "堅定不移的" },
  { front: "stentorian", pos: "adj.", def: "extremely loud and powerful in voice", example: "The usher's stentorian announcement silenced the foyer.", zh: "聲音洪亮的" },
  { front: "stickler", pos: "n.", def: "a person insisting on exact observance of rules", example: "The registrar is a stickler for correctly completed forms.", zh: "堅持細節的人、一板一眼者" },
  { front: "stifle", pos: "v.", def: "suppress or restrain; smother", example: "Heavy-handed regulation risks stifling innovation in the sector.", zh: "扼殺、抑制" },
  { front: "stigma", pos: "n.", def: "a mark of disgrace attached to something", example: "Campaigners work to erase the stigma surrounding mental illness.", zh: "污名、恥辱" },
  { front: "stilted", pos: "adj.", def: "stiff and unnatural in manner or expression", example: "The dubbed dialogue felt stilted and unconvincing.", zh: "生硬的、不自然的" },
  { front: "stipulate", pos: "v.", def: "demand or specify as part of an agreement", example: "The contract stipulates that disputes be settled by arbitration.", zh: "規定、明文要求" },
  { front: "stoic", pos: "adj.", def: "enduring hardship without complaint", example: "She bore the diagnosis with stoic composure.", zh: "堅忍的、淡然的" },
  { front: "stolid", pos: "adj.", def: "calm and showing little emotion", example: "The defendant remained stolid as the verdict was read.", zh: "無動於衷的、遲鈍的" },
  { front: "strident", pos: "adj.", def: "loud, harsh, and unpleasantly forceful", example: "The campaign's strident rhetoric alienated moderate voters.", zh: "尖銳刺耳的、咄咄逼人的" },
  { front: "stringent", pos: "adj.", def: "strict, precise, and exacting", example: "The new emissions standards are the most stringent in Asia.", zh: "嚴格的、嚴厲的" },
  { front: "stupefy", pos: "v.", def: "astonish or shock into helplessness", example: "The scale of the losses stupefied even seasoned auditors.", zh: "使目瞪口呆、使麻木" },
  { front: "stultify", pos: "v.", def: "cause to lose enthusiasm through tedium", example: "Rote memorisation stultifies genuine intellectual curiosity.", zh: "使僵化、使失去活力" },
  { front: "stymie", pos: "v.", def: "prevent or hinder the progress of", example: "Bureaucratic inertia stymied the reconstruction effort for years.", zh: "阻礙、使受挫" },
  { front: "suave", pos: "adj.", def: "charming, confident, and elegant in manner", example: "The suave negotiator disarmed his opponents with flattery.", zh: "溫文爾雅的、圓滑的" },
  { front: "subjugate", pos: "v.", def: "bring under domination or control", example: "The empire subjugated the coastal kingdoms within a decade.", zh: "征服、使屈服" },
  { front: "subservient", pos: "adj.", def: "excessively obedient or submissive", example: "The regulator had grown subservient to the industry it policed.", zh: "屈從的、卑躬的" },
  { front: "substantiate", pos: "v.", def: "provide evidence to support a claim", example: "The whistleblower produced documents to substantiate her allegations.", zh: "證實、提出證據支持" },
  { front: "subterfuge", pos: "n.", def: "deceit used to achieve a goal", example: "The shell companies were an elaborate subterfuge to evade sanctions.", zh: "詭計、託辭" },
  { front: "subsume", pos: "v.", def: "include or absorb within something larger", example: "The agency was subsumed into a sprawling new ministry.", zh: "併入、歸入" },
  { front: "subvert", pos: "v.", def: "undermine the power of an established system", example: "The novel subverts every convention of the detective genre.", zh: "顛覆、破壞" },
  { front: "succinct", pos: "adj.", def: "briefly and clearly expressed", example: "Her succinct summary distilled a decade of research into two pages.", zh: "簡潔的、扼要的" },
  { front: "succumb", pos: "v.", def: "fail to resist pressure, temptation, or illness", example: "Even the holdouts eventually succumbed to commercial pressure.", zh: "屈服、抵擋不住" },
  { front: "suffuse", pos: "v.", def: "gradually spread through or over", example: "A quiet melancholy suffuses the composer's late quartets.", zh: "瀰漫、充滿" },
  { front: "sullen", pos: "adj.", def: "bad-tempered and gloomily silent", example: "The team trudged off to sullen jeers from the terraces.", zh: "慍怒的、悶悶不樂的" },
  { front: "sully", pos: "v.", def: "damage the purity or reputation of", example: "One indiscretion sullied an otherwise unblemished career.", zh: "玷污、敗壞" },
  { front: "sumptuous", pos: "adj.", def: "splendid and expensive-looking", example: "The delegates dined in the palace's sumptuous banqueting hall.", zh: "豪華的、奢侈的" },
  { front: "sundry", pos: "adj.", def: "of various kinds; several", example: "The levy covers insurance, maintenance and sundry administrative costs.", zh: "各式各樣的、雜項的" },
  { front: "supercilious", pos: "adj.", def: "behaving as though superior to others", example: "The maître d's supercilious glance said everything about our attire.", zh: "傲慢的、目中無人的" },
  { front: "superfluous", pos: "adj.", def: "unnecessary; more than is needed", example: "The editor excised every superfluous adjective from the manuscript.", zh: "多餘的、過剩的" },
  { front: "supplant", pos: "v.", def: "replace, often by underhand means", example: "Streaming has all but supplanted physical media.", zh: "取代、排擠" },
  { front: "supplicate", pos: "v.", def: "ask or beg humbly and earnestly", example: "Petitioners supplicated the emperor for clemency.", zh: "懇求、哀求" },
  { front: "surfeit", pos: "n.", def: "an excessive amount of something", example: "A surfeit of committees produced a deficit of decisions.", zh: "過量、過剩" },
  { front: "surly", pos: "adj.", def: "bad-tempered and unfriendly", example: "A surly border guard scrutinised our papers at length.", zh: "脾氣暴躁的、不友善的" },
  { front: "surmise", pos: "v.", def: "suppose without certain evidence", example: "From the shuttered windows she surmised the family had fled.", zh: "推測、臆測" },
  { front: "surmount", pos: "v.", def: "overcome a difficulty or obstacle", example: "The expedition surmounted hazards that had defeated all predecessors.", zh: "克服、越過" },
  { front: "surreptitious", pos: "adj.", def: "done secretly to avoid notice", example: "He cast a surreptitious glance at his rival's notes.", zh: "偷偷摸摸的、暗中的" },
  { front: "swindle", pos: "v.", def: "obtain money from someone by fraud", example: "The scheme swindled pensioners out of their life savings.", zh: "詐騙、騙取" },
  { front: "sycophant", pos: "n.", def: "a person who flatters to gain advantage", example: "The chairman surrounded himself with sycophants and yes-men.", zh: "諂媚者、馬屁精" },
  { front: "taint", pos: "v.", def: "contaminate or spoil, especially a reputation", example: "The doping revelations tainted every record he had set.", zh: "玷污、污染" },
  { front: "tangential", pos: "adj.", def: "only slightly relevant; diverging from the point", example: "Counsel objected that the question was tangential to the case.", zh: "離題的、關係不大的" },
  { front: "tantalize", pos: "v.", def: "torment with the sight of something unobtainable", example: "The trailer tantalizes viewers with glimpses of the lost footage.", zh: "逗弄、吊胃口" },
  { front: "tantamount", pos: "adj.", def: "equivalent in effect to something bad", example: "Silence in such circumstances is tantamount to complicity.", zh: "等同於、無異於" },
  { front: "tarnish", pos: "v.", def: "make less valuable or respected; dull", example: "The bribery scandal tarnished the games' legacy irreparably.", zh: "使失去光彩、敗壞" },
  { front: "taut", pos: "adj.", def: "stretched tight; tense and controlled", example: "The thriller's taut plotting never slackens for a page.", zh: "繃緊的、緊湊的" },
  { front: "tawdry", pos: "adj.", def: "showy but cheap; sordid", example: "The resort's tawdry glamour had faded by the nineties.", zh: "俗麗的、低劣的" },
  { front: "teem", pos: "v.", def: "be full of or swarming with", example: "The estuary teems with migratory birds each autumn.", zh: "充滿、大量湧現" },
  { front: "temerity", pos: "n.", def: "excessive boldness; audacity", example: "She had the temerity to correct the professor mid-lecture.", zh: "魯莽、冒失" },
  { front: "tempestuous", pos: "adj.", def: "characterised by strong turbulent emotion", example: "Their tempestuous partnership produced three masterpieces and two lawsuits.", zh: "狂暴的、波折不斷的" },
  { front: "temporize", pos: "v.", def: "delay a decision to gain time", example: "The governor temporized while the factions exhausted themselves.", zh: "拖延、敷衍以爭取時間" },
  { front: "tenacious", pos: "adj.", def: "persistent; keeping a firm hold", example: "A tenacious reporter finally traced the offshore accounts.", zh: "堅韌不拔的、頑強的" },
  { front: "tendentious", pos: "adj.", def: "promoting a controversial viewpoint; biased", example: "The documentary was criticised as tendentious and selectively edited.", zh: "有偏見的、傾向性的" },
  { front: "tenet", pos: "n.", def: "a principle or belief held as true", example: "Judicial independence is a central tenet of the constitution.", zh: "信條、原則" },
  { front: "tepid", pos: "adj.", def: "lukewarm; showing little enthusiasm", example: "The manifesto received a tepid reception from the party faithful.", zh: "溫吞的、不熱烈的" },
  { front: "terse", pos: "adj.", def: "sparing in words; abrupt", example: "The palace issued a terse statement confirming the abdication.", zh: "簡短生硬的、精練的" },
  { front: "thrall", pos: "n.", def: "the state of being under another's power", example: "The court remained in thrall to the charismatic chancellor.", zh: "受制、束縛" },
  { front: "threadbare", pos: "adj.", def: "worn out; overused and no longer convincing", example: "The government trotted out the same threadbare excuses.", zh: "破舊的、陳腐的" },
  { front: "thwart", pos: "v.", def: "prevent someone from accomplishing something", example: "Vigilant customs officers thwarted the smuggling attempt.", zh: "阻撓、挫敗" },
  { front: "timorous", pos: "adj.", def: "showing nervousness or lack of confidence", example: "A timorous board postponed the decision yet again.", zh: "膽小的、畏怯的" },
  { front: "tirade", pos: "n.", def: "a long, angry speech of criticism", example: "He launched into a tirade against the assembled journalists.", zh: "長篇激烈抨擊、謾罵" },
  { front: "toady", pos: "n.", def: "a person who flatters others servilely", example: "Promotion seemed reserved for toadies rather than talents.", zh: "諂媚者、拍馬屁的人" },
  { front: "tome", pos: "n.", def: "a large, scholarly book", example: "The judge's ruling runs to a nine-hundred-page tome.", zh: "巨著、大部頭書" },
  { front: "torpor", pos: "n.", def: "a state of physical or mental inactivity", example: "The August heat plunged the capital into bureaucratic torpor.", zh: "遲鈍、萎靡不振" },
  { front: "tortuous", pos: "adj.", def: "full of twists; excessively complex", example: "The bill's tortuous passage took three parliamentary sessions.", zh: "曲折的、繞圈子的" },
  { front: "tout", pos: "v.", def: "promote or praise energetically", example: "The device was touted as a revolution in home diagnostics.", zh: "吹捧、兜售" },
  { front: "tractable", pos: "adj.", def: "easy to control, manage, or solve", example: "Framed differently, the dispute became far more tractable.", zh: "易處理的、溫順的" },
  { front: "transgress", pos: "v.", def: "go beyond the bounds of law or morality", example: "Artists have always transgressed the boundaries of propriety.", zh: "違反、逾越" },
  { front: "transient", pos: "adj.", def: "lasting only a short time", example: "Fame in the digital age is notoriously transient.", zh: "短暫的、轉瞬即逝的" },
  { front: "travail", pos: "n.", def: "painful or laborious effort", example: "The memoir chronicles the travails of resettlement.", zh: "艱辛勞苦、磨難" },
  { front: "travesty", pos: "n.", def: "a distorted or absurd imitation", example: "Observers denounced the trial as a travesty of justice.", zh: "拙劣的模仿、歪曲" },
  { front: "treacherous", pos: "adj.", def: "guilty of betrayal; hazardously unreliable", example: "Black ice made the mountain pass treacherous.", zh: "背叛的、危險的" },
  { front: "tremulous", pos: "adj.", def: "shaking slightly; timid", example: "In a tremulous voice she read the names of the fallen.", zh: "顫抖的、怯懦的" },
  { front: "trenchant", pos: "adj.", def: "vigorously incisive and effective", example: "Her trenchant critique demolished the report's methodology.", zh: "犀利的、一針見血的" },
  { front: "trite", pos: "adj.", def: "overused and consequently lacking originality", example: "The eulogy avoided the trite consolations of such occasions.", zh: "陳腔濫調的" },
  { front: "truncate", pos: "v.", def: "shorten by cutting off a part", example: "The ceremony was truncated when the heavens opened.", zh: "截短、縮短" },
  { front: "tumultuous", pos: "adj.", def: "loud and disorderly; full of upheaval", example: "The reforms passed after a tumultuous overnight sitting.", zh: "騷亂的、動盪的" },
  { front: "turbid", pos: "adj.", def: "cloudy or muddy; confused", example: "Turbid floodwater rendered the wells unusable.", zh: "混濁的、紊亂的" },
  { front: "turgid", pos: "adj.", def: "pompously written; swollen", example: "Reviewers savaged the biography's turgid prose.", zh: "浮誇冗贅的、腫脹的" },
  { front: "turpitude", pos: "n.", def: "depraved or wicked behaviour", example: "He was disbarred for conduct amounting to moral turpitude.", zh: "卑鄙、墮落" },
  { front: "tutelage", pos: "n.", def: "protection and instruction of a pupil", example: "Under her tutelage the ensemble reached international standard.", zh: "指導、監護" },
  { front: "umbrage", pos: "n.", def: "offence or annoyance taken at something", example: "He took umbrage at the implication of favouritism.", zh: "不悅、慍怒" },
  { front: "unabashed", pos: "adj.", def: "not embarrassed or ashamed", example: "She is an unabashed admirer of the baroque.", zh: "毫不害臊的、坦然的" },
  { front: "unassailable", pos: "adj.", def: "unable to be attacked or defeated", example: "Three goals gave the champions an unassailable lead.", zh: "無懈可擊的、不可動搖的" },
  { front: "unassuming", pos: "adj.", def: "modest; not pretentious", example: "The laureate remained unassuming despite the global acclaim.", zh: "謙遜的、不張揚的" },
  { front: "uncanny", pos: "adj.", def: "strange in an unsettling way", example: "She has an uncanny knack for anticipating market turns.", zh: "離奇的、不可思議的" },
  { front: "unconscionable", pos: "adj.", def: "not right or reasonable; excessive", example: "The court struck down the loan's unconscionable terms.", zh: "不合情理的、昧著良心的" },
  { front: "unctuous", pos: "adj.", def: "excessively flattering and insincere", example: "The salesman's unctuous charm put us instantly on guard.", zh: "油腔滑調的、虛情假意的" },
  { front: "undulate", pos: "v.", def: "move with a smooth wavelike motion", example: "Wheat fields undulated to the horizon in the summer wind.", zh: "波動、起伏" },
  { front: "unflagging", pos: "adj.", def: "tireless and persistently energetic", example: "Her unflagging advocacy finally secured the treaty's ratification.", zh: "不懈的、不屈不撓的" },
  { front: "unflappable", pos: "adj.", def: "calm in a crisis; not easily upset", example: "The unflappable pilot narrated the emergency as if reading weather.", zh: "處變不驚的、鎮定的" },
  { front: "unfounded", pos: "adj.", def: "having no basis in fact", example: "The audit proved the allegations entirely unfounded.", zh: "毫無根據的" },
  { front: "ungainly", pos: "adj.", def: "awkward and clumsy in movement", example: "The prototype was ungainly but astonishingly efficient.", zh: "笨拙的、不雅觀的" },
  { front: "unimpeachable", pos: "adj.", def: "beyond doubt or reproach", example: "The testimony came from a witness of unimpeachable integrity.", zh: "無可指責的、無可懷疑的" },
  { front: "unremitting", pos: "adj.", def: "never relaxing or slackening", example: "Unremitting rainfall turned the festival grounds into a bog.", zh: "不間斷的、持續的" },
  { front: "unrequited", pos: "adj.", def: "not returned, especially of love", example: "The sonnets chart decades of unrequited devotion.", zh: "得不到回報的、單戀的" },
  { front: "unruly", pos: "adj.", def: "disorderly and difficult to control", example: "The speaker struggled to bring the unruly chamber to order.", zh: "不守規矩的、難駕馭的" },
  { front: "unsavoury", pos: "adj.", def: "disagreeable; morally offensive", example: "The developer's unsavoury business associates raised red flags.", zh: "令人反感的、聲名狼藉的" },
  { front: "unscathed", pos: "adj.", def: "without suffering any injury or harm", example: "Remarkably, the gallery's collection emerged unscathed from the fire.", zh: "毫髮無傷的" },
  { front: "untoward", pos: "adj.", def: "unexpected and inconvenient or improper", example: "The inspectors found nothing untoward in the accounts.", zh: "不順利的、不妥的" },
  { front: "unwieldy", pos: "adj.", def: "hard to manage because of size or complexity", example: "The coalition's unwieldy decision-making paralysed the response.", zh: "笨重的、難以運作的" },
  { front: "unwitting", pos: "adj.", def: "unaware of the full situation; unintentional", example: "Thousands became unwitting participants in the data experiment.", zh: "不知情的、無意的" },
  { front: "upbraid", pos: "v.", def: "scold or criticise severely", example: "The coach upbraided the squad for their complacent first half.", zh: "訓斥、責罵" },
  { front: "urbane", pos: "adj.", def: "courteous and refined in manner", example: "The urbane diplomat charmed even his fiercest critics.", zh: "溫文儒雅的、老練的" },
  { front: "usurp", pos: "v.", def: "seize a position or power illegally", example: "The regent gradually usurped the powers of the crown.", zh: "篡奪、僭越" },
  { front: "vacillate", pos: "v.", def: "waver between different opinions or actions", example: "The cabinet vacillated for weeks while the crisis deepened.", zh: "猶豫不決、搖擺" },
  { front: "vacuous", pos: "adj.", def: "showing a lack of thought or intelligence", example: "The debate degenerated into an exchange of vacuous slogans.", zh: "空洞的、無知的" },
  { front: "vagary", pos: "n.", def: "an unpredictable change or whim", example: "Harvests remain hostage to the vagaries of the monsoon.", zh: "變幻莫測、反覆無常" },
  { front: "vainglorious", pos: "adj.", def: "excessively boastful about one's achievements", example: "The vainglorious memoir credits him with every reform of the era.", zh: "自負的、虛榮的" },
  { front: "vanguard", pos: "n.", def: "the leading position in a movement", example: "The university stands in the vanguard of quantum research.", zh: "先鋒、前驅" },
  { front: "vapid", pos: "adj.", def: "offering no stimulation; dull", example: "The interview elicited only vapid pleasantries.", zh: "乏味的、無趣的" },
  { front: "variegated", pos: "adj.", def: "showing varied colours or diversity", example: "The city's variegated architecture records five centuries of conquest.", zh: "斑駁的、多樣化的" },
  { front: "vaunted", pos: "adj.", def: "widely praised, often unjustifiably", example: "The team's vaunted defence crumbled within twenty minutes.", zh: "備受吹噓的" },
  { front: "venal", pos: "adj.", def: "open to bribery; corruptible", example: "Venal officials waved the contraband through for a fee.", zh: "貪贓枉法的、唯利是圖的" },
  { front: "vendetta", pos: "n.", def: "a prolonged bitter quarrel or campaign", example: "He accused the tabloid of waging a personal vendetta.", zh: "宿怨、尋仇" },
  { front: "venerate", pos: "v.", def: "regard with great respect", example: "Generations of physicists venerate her foundational experiments.", zh: "尊崇、敬仰" },
  { front: "abide by", pos: "phrasal v.", def: "accept and act in accordance with", example: "Signatories must abide by the tribunal's rulings, however unwelcome.", zh: "遵守、信守" },
  { front: "bear down on", pos: "phrasal v.", def: "move threateningly towards; exert pressure on", example: "Regulators are bearing down on undisclosed cryptocurrency promotions.", zh: "逼近、施壓" },
  { front: "beaver away", pos: "phrasal v.", def: "work hard and steadily", example: "She beavered away at the translation for three winters.", zh: "埋頭苦幹" },
  { front: "beef up", pos: "phrasal v.", def: "strengthen or make more substantial", example: "Airports beefed up security ahead of the summit.", zh: "加強、充實" },
  { front: "blow over", pos: "phrasal v.", def: "pass without serious consequences", example: "Advisers assured him the scandal would blow over within a week.", zh: "（風波）平息" },
  { front: "blurt out", pos: "phrasal v.", def: "say suddenly and without thinking", example: "Under questioning she blurted out the informant's name.", zh: "脫口而出" },
  { front: "bog down", pos: "phrasal v.", def: "become stuck and unable to progress", example: "The talks bogged down over the question of verification.", zh: "陷入僵局、停滯" },
  { front: "bottom out", pos: "phrasal v.", def: "reach the lowest point before improving", example: "Analysts believe property prices have finally bottomed out.", zh: "觸底、跌到谷底" },
  { front: "bounce back", pos: "phrasal v.", def: "recover quickly from a setback", example: "The economy bounced back faster than any forecaster predicted.", zh: "迅速恢復、反彈" },
  { front: "bowl over", pos: "phrasal v.", def: "impress or astonish greatly", example: "The jury was bowled over by the debutant's audacious design.", zh: "使大為驚豔" },
  { front: "branch out", pos: "phrasal v.", def: "extend activities into new areas", example: "The vineyard branched out into boutique accommodation.", zh: "拓展業務、開闢新領域" },
  { front: "brazen out", pos: "phrasal v.", def: "endure an embarrassing situation with defiant confidence", example: "Rather than resign, the minister chose to brazen it out.", zh: "厚著臉皮硬撐" },
  { front: "brush up on", pos: "phrasal v.", def: "improve existing knowledge of something", example: "I must brush up on my statistics before the viva.", zh: "溫習、重新熟悉" },
  { front: "buoy up", pos: "phrasal v.", def: "keep cheerful or keep prices high", example: "Record exports buoyed up an otherwise anaemic economy.", zh: "使振奮、支撐" },
  { front: "cash in on", pos: "phrasal v.", def: "exploit a situation for profit", example: "Merchandisers cashed in on the team's improbable cup run.", zh: "趁機牟利、利用" },
  { front: "chance upon", pos: "phrasal v.", def: "find or meet by accident", example: "Archivists chanced upon the lost score in a mislabelled crate.", zh: "偶然發現、巧遇" },
  { front: "chase up", pos: "phrasal v.", def: "pursue someone for an overdue response", example: "Could you chase up the supplier about the missing consignment?", zh: "催辦、追問" },
  { front: "close in on", pos: "phrasal v.", def: "gradually surround or approach", example: "Investigators were closing in on the syndicate's paymaster.", zh: "逼近、包圍" },
  { front: "come across as", pos: "phrasal v.", def: "give a particular impression", example: "In interviews he comes across as guarded, almost brittle.", zh: "給人某種印象" },
  { front: "come around to", pos: "phrasal v.", def: "gradually accept an idea after resistance", example: "The board eventually came around to the merger's logic.", zh: "逐漸接受、改變想法" },
  { front: "come up against", pos: "phrasal v.", def: "encounter a difficulty or opposition", example: "The reform came up against entrenched provincial interests.", zh: "遭遇（困難、阻力）" },
  { front: "dip into", pos: "phrasal v.", def: "use part of one's savings; read casually", example: "They dipped into their reserves to cover the shortfall.", zh: "動用（存款）、隨意翻閱" },
  { front: "drift apart", pos: "phrasal v.", def: "gradually become less close", example: "The wartime allies drifted apart once the common threat receded.", zh: "逐漸疏遠" },
  { front: "dwell on", pos: "phrasal v.", def: "think or talk at length about something unpleasant", example: "She refused to dwell on the injury that ended her career.", zh: "老是想著、糾結於" },
  { front: "explain away", pos: "phrasal v.", def: "minimise something's significance with excuses", example: "No statistic could explain away the widening mortality gap.", zh: "辯解、搪塞" },
  { front: "ferret out", pos: "phrasal v.", def: "discover information through persistent searching", example: "Auditors ferreted out irregularities buried in the subsidiary accounts.", zh: "查出、搜出" },
  { front: "follow through on", pos: "phrasal v.", def: "complete what one has promised or begun", example: "Donors rarely follow through on pledges made at summits.", zh: "貫徹、落實" },
  { front: "forge ahead", pos: "phrasal v.", def: "make rapid, determined progress", example: "The consortium forged ahead with the tunnel despite the injunction.", zh: "奮力前進、大力推展" },
  { front: "frown upon", pos: "phrasal v.", def: "disapprove of something", example: "Openly canvassing for promotion is frowned upon here.", zh: "不贊成、看不慣" },
  { front: "gang up on", pos: "phrasal v.", def: "join together against someone", example: "Smaller shareholders ganged up on the founding family.", zh: "聯合對付、圍攻" },
  { front: "get around to", pos: "phrasal v.", def: "finally do something after delay", example: "I never got around to reading his collected letters.", zh: "終於抽空做" },
  { front: "grind down", pos: "phrasal v.", def: "wear someone down through sustained pressure", example: "Years of casework had ground down even the idealists.", zh: "折磨、消磨" },
  { front: "grow on", pos: "phrasal v.", def: "become gradually more appealing to", example: "The atonal score grows on you with repeated listening.", zh: "逐漸讓人喜歡" },
  { front: "hand down", pos: "phrasal v.", def: "pass to a successor; announce a verdict", example: "The court handed down its judgment after a year's deliberation.", zh: "傳承、宣判" },
  { front: "hanker after", pos: "phrasal v.", def: "feel a persistent longing for", example: "Expatriates hanker after flavours no import shop can supply.", zh: "渴望、念念不忘" },
  { front: "harp on about", pos: "phrasal v.", def: "talk repeatedly and tediously about", example: "He keeps harping on about the good old analogue days.", zh: "喋喋不休、老調重彈" },
  { front: "hem in", pos: "phrasal v.", def: "surround and restrict the movement of", example: "The old town is hemmed in by motorways on three sides.", zh: "包圍、限制" },
  { front: "hinge on", pos: "phrasal v.", def: "depend entirely on", example: "The verdict hinges on the reliability of a single witness.", zh: "取決於" },
  { front: "hold forth", pos: "phrasal v.", def: "talk lengthily and tediously", example: "He held forth on monetary policy for the entire dinner.", zh: "滔滔不絕地講" },
  { front: "hush up", pos: "phrasal v.", def: "prevent something from becoming publicly known", example: "Executives conspired to hush up the contamination report.", zh: "掩蓋、封鎖消息" },
  { front: "keel over", pos: "phrasal v.", def: "collapse or fall over suddenly", example: "A steward keeled over in the stifling committee room.", zh: "突然倒下、翻覆" },
  { front: "knuckle down", pos: "phrasal v.", def: "begin working earnestly", example: "With finals looming, she finally knuckled down to revision.", zh: "開始認真苦幹" },
  { front: "lag behind", pos: "phrasal v.", def: "fail to keep pace with others", example: "Rural broadband still lags far behind urban provision.", zh: "落後" },
  { front: "lay into", pos: "phrasal v.", def: "attack violently with words or blows", example: "The columnist laid into the budget's optimistic assumptions.", zh: "痛斥、猛烈抨擊" },
  { front: "let on", pos: "phrasal v.", def: "reveal secret information", example: "She knew far more than she ever let on.", zh: "洩漏、透露" },
  { front: "make off with", pos: "phrasal v.", def: "steal and hurry away with", example: "Thieves made off with two Renaissance bronzes.", zh: "偷走、攜…潛逃" },
  { front: "mop up", pos: "phrasal v.", def: "deal with remaining matters; absorb", example: "The central bank mopped up excess liquidity through bond sales.", zh: "收拾殘局、吸收" },
  { front: "pack in", pos: "phrasal v.", def: "give up an activity or job", example: "He packed in a lucrative practice to teach in the highlands.", zh: "放棄、辭掉" },
  { front: "patch up", pos: "phrasal v.", def: "repair hastily; settle a quarrel", example: "The rivals patched up their differences before the party conference.", zh: "修補、和解" },
  { front: "peter out", pos: "phrasal v.", def: "gradually diminish and come to an end", example: "Public enthusiasm for the reforms petered out within months.", zh: "逐漸消失、不了了之" },
  { front: "pick up on", pos: "phrasal v.", def: "notice and react to something subtle", example: "A sharp-eyed clerk picked up on the discrepancy in dates.", zh: "察覺、注意到" },
  { front: "pore over", pos: "phrasal v.", def: "study or examine with close attention", example: "Scholars still pore over the marginalia in his notebooks.", zh: "仔細研讀、鑽研" },
  { front: "press ahead with", pos: "phrasal v.", def: "continue with a plan despite difficulty", example: "The council pressed ahead with the demolition despite protests.", zh: "堅決推進" },
  { front: "prop up", pos: "phrasal v.", def: "support something that would otherwise fail", example: "Subsidies propped up the shipyards for another decade.", zh: "扶持、支撐" },
  { front: "ramp up", pos: "phrasal v.", def: "increase the level or amount of rapidly", example: "Factories ramped up production of vaccines within weeks.", zh: "迅速增加、加大力度" },
  { front: "seize on", pos: "phrasal v.", def: "take eager advantage of something", example: "The opposition seized on the gaffe within minutes.", zh: "抓住（把柄、機會）" },
  { front: "shore up", pos: "phrasal v.", def: "support or strengthen something weakening", example: "Emergency lending shored up confidence in the banking system.", zh: "支撐、鞏固" },
  { front: "shy away from", pos: "phrasal v.", def: "avoid through nervousness or reluctance", example: "The biography does not shy away from its subject's cruelties.", zh: "迴避、退縮" },
  { front: "size up", pos: "phrasal v.", def: "form a judgement about someone or something", example: "The negotiators spent the first session sizing each other up.", zh: "打量、估量" },
  { front: "soldier on", pos: "phrasal v.", def: "persevere doggedly despite difficulty", example: "Though underfunded, the clinic soldiered on through the epidemic.", zh: "咬牙堅持" },
  { front: "sound out", pos: "phrasal v.", def: "cautiously discover someone's opinions or intentions", example: "Envoys were sent to sound out the junta on elections.", zh: "試探、摸底" },
  { front: "squirrel away", pos: "phrasal v.", def: "hide or store for future use", example: "He had squirrelled away a fortune in offshore accounts.", zh: "私藏、積攢" },
  { front: "stamp out", pos: "phrasal v.", def: "eradicate or suppress completely", example: "The campaign aims to stamp out match-fixing at every level.", zh: "根除、撲滅" },
  { front: "tease out", pos: "phrasal v.", def: "extract information or meaning with effort", example: "The study teases out the effects of income from those of education.", zh: "梳理出、探究出" },
  { front: "usher in", pos: "phrasal v.", def: "mark the beginning of something new", example: "The treaty ushered in a decade of unprecedented cooperation.", zh: "開創、迎來" },
  { front: "a baptism of fire", pos: "idiom", def: "a difficult introduction to a new role", example: "Chairing the emergency session was a baptism of fire for the new envoy.", zh: "嚴酷的考驗、初試即遇難關" },
  { front: "a dark horse", pos: "idiom", def: "a little-known person who unexpectedly succeeds", example: "The provincial senator proved the dark horse of the primaries.", zh: "黑馬、深藏不露的人" },
  { front: "a feather in one's cap", pos: "idiom", def: "an achievement to be proud of", example: "Landing the Vienna premiere was a feather in her cap.", zh: "值得驕傲的成就" },
  { front: "a flash in the pan", pos: "idiom", def: "a brief success unlikely to be repeated", example: "Sceptics dismissed the startup's stellar quarter as a flash in the pan.", zh: "曇花一現" },
  { front: "a labour of love", pos: "idiom", def: "work done for pleasure, not reward", example: "Restoring the lighthouse was a decade-long labour of love.", zh: "心甘情願的辛勞、愛的結晶" },
  { front: "a law unto oneself", pos: "idiom", def: "someone who ignores rules and conventions", example: "The maestro was a law unto himself in rehearsals.", zh: "我行我素的人" },
  { front: "a leap in the dark", pos: "idiom", def: "an action whose consequences are unknown", example: "Privatising the railways was a leap in the dark.", zh: "冒險之舉、前途未卜的行動" },
  { front: "a mixed blessing", pos: "idiom", def: "something with both advantages and disadvantages", example: "The tourist boom proved a mixed blessing for the fishing village.", zh: "利弊參半的事、有利有弊" },
  { front: "a necessary evil", pos: "idiom", def: "something undesirable but unavoidable", example: "Most citizens regard airport security queues as a necessary evil.", zh: "必要之惡" },
  { front: "a pipe dream", pos: "idiom", def: "an unrealistic hope or fantastic plan", example: "Universal fusion power remains, for now, a pipe dream.", zh: "白日夢、不切實際的空想" },
  { front: "a sacred cow", pos: "idiom", def: "an idea unreasonably immune from criticism", example: "No fiscal sacred cow escaped the commission's scrutiny.", zh: "不容批評的事物、禁忌" },
  { front: "a sea change", pos: "idiom", def: "a profound transformation", example: "The verdict marks a sea change in attitudes to corporate liability.", zh: "重大轉變" },
  { front: "a slap on the wrist", pos: "idiom", def: "a punishment far too mild", example: "The derisory fine amounted to a slap on the wrist.", zh: "不痛不癢的處罰" },
  { front: "a stone's throw", pos: "idiom", def: "a very short distance away", example: "The gallery sits a stone's throw from the cathedral.", zh: "近在咫尺" },
  { front: "a tall order", pos: "idiom", def: "a task very difficult to accomplish", example: "Halving emissions by 2030 is a tall order for any government.", zh: "艱鉅的任務、難以達成的要求" },
  { front: "a taste of one's own medicine", pos: "idiom", def: "the same unpleasant treatment one gives others", example: "The heckler got a taste of his own medicine from the comedian.", zh: "以其人之道還治其人之身" },
  { front: "a tough nut to crack", pos: "idiom", def: "a problem or person hard to deal with", example: "The rural vote remains a tough nut to crack for the party.", zh: "難啃的硬骨頭、棘手難題" },
  { front: "against all odds", pos: "idiom", def: "despite very low probability of success", example: "Against all odds, the appeal succeeded at the final hearing.", zh: "克服萬難、出乎意料地" },
  { front: "at one's wits' end", pos: "idiom", def: "so worried one does not know what to do", example: "Carers of dementia patients are often at their wits' end.", zh: "束手無策、智窮計盡" },
  { front: "at the eleventh hour", pos: "idiom", def: "at the last possible moment", example: "A compromise was brokered at the eleventh hour.", zh: "在最後關頭" },
  { front: "beat about the bush", pos: "idiom", def: "avoid talking about the main point", example: "Stop beating about the bush and tell me the prognosis.", zh: "拐彎抹角、兜圈子" },
  { front: "beyond the pale", pos: "idiom", def: "outside the bounds of acceptable behaviour", example: "Even his allies deemed the remarks beyond the pale.", zh: "越界的、令人無法接受的" },
  { front: "blow hot and cold", pos: "idiom", def: "keep changing one's attitude or enthusiasm", example: "Investors have blown hot and cold on emerging markets all year.", zh: "反覆無常、忽冷忽熱" },
  { front: "blow one's own trumpet", pos: "idiom", def: "boast about one's own achievements", example: "She is too modest to blow her own trumpet, so I shall.", zh: "自吹自擂" },
  { front: "burn the midnight oil", pos: "idiom", def: "work late into the night", example: "The drafting team burned the midnight oil before the summit.", zh: "挑燈夜戰、熬夜工作" },
  { front: "bursting at the seams", pos: "idiom", def: "extremely full or overcrowded", example: "The archive is bursting at the seams with uncatalogued papers.", zh: "爆滿、擁擠不堪" },
  { front: "by hook or by crook", pos: "idiom", def: "by any means necessary", example: "He vowed to secure the nomination by hook or by crook.", zh: "不擇手段、千方百計" },
  { front: "carry the can", pos: "idiom", def: "take the blame for a collective failure", example: "Junior staff carried the can for decisions taken upstairs.", zh: "背黑鍋、承擔責任" },
  { front: "change tack", pos: "idiom", def: "adopt a different approach", example: "When persuasion failed, the campaign changed tack to litigation.", zh: "改變策略、轉換方針" },
  { front: "come full circle", pos: "idiom", def: "return to the original position or situation", example: "Fashion in urban planning has come full circle to dense, walkable streets.", zh: "繞了一圈回到原點" },
  { front: "cross swords with", pos: "idiom", def: "argue or clash with someone", example: "She first crossed swords with the chancellor over tuition fees.", zh: "與…交鋒、發生爭執" },
  { front: "cry wolf", pos: "idiom", def: "raise false alarms so real ones are ignored", example: "Forecasters who cry wolf risk being ignored when disaster truly looms.", zh: "狼來了、謊報險情" },
  { front: "curry favour with", pos: "idiom", def: "ingratiate oneself through flattery", example: "The colonies' governors curried favour with the court through lavish gifts.", zh: "討好、巴結" },
  { front: "cut one's losses", pos: "idiom", def: "abandon a failing endeavour before losing more", example: "The studio cut its losses and shelved the franchise.", zh: "及時止損" },
  { front: "cut the mustard", pos: "idiom", def: "meet the required standard", example: "Half-hearted apologies simply do not cut the mustard anymore.", zh: "達到標準、夠格" },
  { front: "drive a hard bargain", pos: "idiom", def: "negotiate aggressively for favourable terms", example: "The union drove a hard bargain over pension protections.", zh: "極力討價還價" },
  { front: "eat humble pie", pos: "idiom", def: "admit one's error and apologise", example: "The pundit ate humble pie after his guaranteed prediction failed.", zh: "低頭認錯、忍辱謝罪" },
  { front: "err on the side of caution", pos: "idiom", def: "choose the safest available course", example: "Given the seismic data, engineers erred on the side of caution.", zh: "寧可謹慎行事" },
  { front: "face the music", pos: "idiom", def: "accept unpleasant consequences of one's actions", example: "After the audit, the treasurer finally had to face the music.", zh: "承擔後果、接受責罰" },
  { front: "fall between two stools", pos: "idiom", def: "fail by trying to combine two approaches", example: "The film falls between two stools, neither thriller nor satire.", zh: "兩頭落空" },
  { front: "feel the pinch", pos: "idiom", def: "experience financial hardship", example: "Small exporters felt the pinch as the currency strengthened.", zh: "感到手頭拮据" },
  { front: "fight a losing battle", pos: "idiom", def: "struggle against something with no hope of winning", example: "Librarians fight a losing battle against dwindling attention spans.", zh: "打一場注定失敗的仗" },
  { front: "give someone short shrift", pos: "idiom", def: "dismiss someone curtly without consideration", example: "The committee gave the lobbyists' objections short shrift.", zh: "冷落打發、不予理會" },
  { front: "go through the motions", pos: "idiom", def: "do something mechanically without genuine effort", example: "By the final round the exhausted candidates were merely going through the motions.", zh: "敷衍了事、走過場" },
  { front: "have an axe to grind", pos: "idiom", def: "have a private, often selfish, motive", example: "As a displaced former director, he clearly has an axe to grind.", zh: "別有用心、另有所圖" },
  { front: "ride roughshod over", pos: "idiom", def: "ignore others' wishes or rights carelessly", example: "The developers rode roughshod over the residents' objections.", zh: "橫行霸道、恣意踐踏" },
  { front: "smell a rat", pos: "idiom", def: "suspect deception or trickery", example: "When the returns doubled overnight, the auditors smelled a rat.", zh: "察覺有詐、起疑心" },
  { front: "take the wind out of someone's sails", pos: "idiom", def: "make someone less confident by preempting them", example: "The rival's early concession took the wind out of his sails.", zh: "使洩氣、挫其銳氣" },
  { front: "the lion's share", pos: "idiom", def: "the largest portion of something", example: "Defence consumed the lion's share of the emergency budget.", zh: "最大的一份" },
  { front: "the writing on the wall", pos: "idiom", def: "clear signs of impending failure", example: "Falling subscriptions were the writing on the wall for the print edition.", zh: "不祥之兆、大勢已去的徵兆" },
  { front: "adverse effects", pos: "collocation", def: "harmful or unfavourable results", example: "The trial was halted after adverse effects emerged in older patients.", zh: "不良影響、副作用" },
  { front: "ample opportunity", pos: "collocation", def: "more than enough chance to do something", example: "Defendants were given ample opportunity to contest the evidence.", zh: "充分的機會" },
  { front: "binding agreement", pos: "collocation", def: "a contract that must legally be honoured", example: "The memorandum falls short of a binding agreement.", zh: "具約束力的協議" },
  { front: "blistering pace", pos: "collocation", def: "an extremely fast speed", example: "The renovation proceeded at a blistering pace to meet the deadline.", zh: "飛快的速度" },
  { front: "budding entrepreneur", pos: "collocation", def: "a person beginning to develop in business", example: "The incubator mentors budding entrepreneurs from rural provinces.", zh: "嶄露頭角的創業家" },
  { front: "bumper harvest", pos: "collocation", def: "an unusually large crop yield", example: "A bumper harvest depressed grain prices across the region.", zh: "大豐收" },
  { front: "captive audience", pos: "collocation", def: "listeners unable to leave and thus attentive", example: "Airline passengers are a captive audience for onboard advertising.", zh: "被動的聽眾、走不開的觀眾" },
  { front: "casting vote", pos: "collocation", def: "a deciding vote when others are tied", example: "The chair's casting vote settled the deadlocked motion.", zh: "關鍵一票、決定票" },
  { front: "collateral damage", pos: "collocation", def: "unintended harm caused alongside an action", example: "Small suppliers became collateral damage in the price war.", zh: "附帶損害、波及的傷害" },
  { front: "commanding lead", pos: "collocation", def: "a large, dominant advantage", example: "The incumbent holds a commanding lead in every province.", zh: "遙遙領先的優勢" },
  { front: "consummate professional", pos: "collocation", def: "a person showing supreme skill and conduct", example: "Even amid the chaos backstage, she remained a consummate professional.", zh: "無可挑剔的專業人士" },
  { front: "cut-throat competition", pos: "collocation", def: "ruthlessly intense rivalry", example: "Cut-throat competition drove margins in the sector to near zero.", zh: "割喉式競爭" },
  { front: "deciding factor", pos: "collocation", def: "the element that determines an outcome", example: "Price, not loyalty, proved the deciding factor for most customers.", zh: "決定性因素" },
  { front: "defining moment", pos: "collocation", def: "an event revealing something's essential character", example: "The flood response became the defining moment of her premiership.", zh: "關鍵時刻、決定性時刻" },
  { front: "derisory offer", pos: "collocation", def: "an offer so small as to be insulting", example: "The union rejected the derisory offer of a one percent rise.", zh: "低得可笑的報價" },
  { front: "diminishing returns", pos: "collocation", def: "progressively smaller benefits from continued effort", example: "Beyond ten hours of revision a day, students hit diminishing returns.", zh: "報酬遞減" },
  { front: "dizzying heights", pos: "collocation", def: "an extremely high or successful level", example: "Share prices climbed to dizzying heights before the correction.", zh: "令人暈眩的高度、巔峰" },
  { front: "dogged determination", pos: "collocation", def: "stubborn, persistent resolve", example: "Her dogged determination finally overturned the wrongful conviction.", zh: "頑強的決心" },
  { front: "emphatic victory", pos: "collocation", def: "a decisive, unambiguous win", example: "The referendum delivered an emphatic victory for the reformists.", zh: "壓倒性勝利" },
  { front: "enduring appeal", pos: "collocation", def: "attractiveness that lasts over time", example: "The novella's enduring appeal defies each generation of critics.", zh: "歷久不衰的魅力" },
  { front: "extenuating circumstances", pos: "collocation", def: "factors that partially excuse wrongdoing", example: "The tribunal reduced the penalty in view of extenuating circumstances.", zh: "情有可原的情況" },
  { front: "faint praise", pos: "collocation", def: "approval so weak it implies criticism", example: "Calling the design 'serviceable' was damning it with faint praise.", zh: "不冷不熱的稱讚" },
  { front: "fertile ground", pos: "collocation", def: "conditions favourable for something to develop", example: "Economic grievance is fertile ground for populist movements.", zh: "溫床、沃土" },
  { front: "fitting tribute", pos: "collocation", def: "an appropriately respectful act of honour", example: "The scholarship fund is a fitting tribute to her mentorship.", zh: "恰如其分的致敬" },
  { front: "flat refusal", pos: "collocation", def: "a direct, unqualified rejection", example: "The request for an extension met with a flat refusal.", zh: "斷然拒絕" },
  { front: "glittering career", pos: "collocation", def: "a brilliantly successful professional life", example: "An injury at twenty-nine ended a glittering career.", zh: "輝煌的職業生涯" },
  { front: "grinding poverty", pos: "collocation", def: "severe, unrelenting deprivation", example: "The memoir recalls a childhood of grinding poverty in the delta.", zh: "赤貧、磨人的貧困" },
  { front: "gruelling schedule", pos: "collocation", def: "an exhaustingly demanding timetable", example: "The tour's gruelling schedule left the orchestra depleted.", zh: "累人的行程" },
  { front: "hefty fine", pos: "collocation", def: "a large monetary penalty", example: "The regulator imposed a hefty fine for the data breach.", zh: "鉅額罰款" },
  { front: "hostile takeover", pos: "collocation", def: "an acquisition opposed by the target's management", example: "The family firm fended off a hostile takeover by a private equity fund.", zh: "敵意併購" },
  { front: "inclement weather", pos: "collocation", def: "unpleasantly cold or stormy conditions", example: "The unveiling was postponed owing to inclement weather.", zh: "惡劣天氣" },
  { front: "impeccable credentials", pos: "collocation", def: "flawless qualifications and background", example: "Despite impeccable credentials, she was passed over twice.", zh: "無可挑剔的資歷" },
  { front: "landslide victory", pos: "collocation", def: "an overwhelming electoral win", example: "The opposition swept to a landslide victory on record turnout.", zh: "壓倒性勝選" },
  { front: "last-ditch attempt", pos: "collocation", def: "a final desperate effort", example: "Mediators flew in for a last-ditch attempt to save the talks.", zh: "最後一搏、孤注一擲的嘗試" },
  { front: "lingering doubt", pos: "collocation", def: "a doubt that persists over time", example: "The acquittal failed to dispel lingering doubts about the evidence.", zh: "揮之不去的疑慮" },
  { front: "nagging suspicion", pos: "collocation", def: "a persistent, troubling feeling of distrust", example: "She could not shake the nagging suspicion that the figures were massaged.", zh: "縈繞心頭的懷疑" },
  { front: "polar opposites", pos: "collocation", def: "two things completely different in nature", example: "In temperament the twin sisters are polar opposites.", zh: "截然相反的兩極" },
  { front: "rapt attention", pos: "collocation", def: "complete, fascinated concentration", example: "The pupils listened with rapt attention to the astronaut's account.", zh: "全神貫注" },
  { front: "roaring trade", pos: "collocation", def: "very brisk and profitable business", example: "Street vendors did a roaring trade during the festival.", zh: "生意興隆" },
  { front: "rousing speech", pos: "collocation", def: "a speech that stirs enthusiasm", example: "The captain's rousing speech transformed the second-half performance.", zh: "激勵人心的演說" },
  { front: "salutary lesson", pos: "collocation", def: "a beneficial though painful learning experience", example: "The recall was a salutary lesson in cutting corners on testing.", zh: "有益的教訓" },
  { front: "scorching heat", pos: "collocation", def: "extremely high temperature", example: "Labourers toiled in scorching heat to finish the stadium.", zh: "酷熱、灼人的高溫" },
  { front: "searching questions", pos: "collocation", def: "probing enquiries that test thoroughly", example: "The panel put searching questions to the nominee for three hours.", zh: "尖銳深入的提問" },
  { front: "searing pain", pos: "collocation", def: "an intense burning sensation", example: "A searing pain in his shoulder forced an early retirement from the match.", zh: "劇痛、灼痛" },
  { front: "sketchy details", pos: "collocation", def: "incomplete or vague information", example: "Only sketchy details of the agreement have so far emerged.", zh: "粗略不全的細節" },
  { front: "slender majority", pos: "collocation", def: "a very small margin of superiority in votes", example: "The bill passed by a slender majority of three.", zh: "些微多數、勉強過半" },
  { front: "smear campaign", pos: "collocation", def: "an organised effort to damage a reputation", example: "She attributed the leaked rumours to a coordinated smear campaign.", zh: "抹黑行動" },
  { front: "steep learning curve", pos: "collocation", def: "a period requiring rapid acquisition of skills", example: "New clerks face a steep learning curve in their first term.", zh: "陡峭的學習曲線" },
  { front: "sterling work", pos: "collocation", def: "excellent, dependable effort", example: "Volunteers did sterling work in the flood-hit villages.", zh: "出色的工作表現" },
  { front: "stiff opposition", pos: "collocation", def: "strong, determined resistance", example: "The zoning proposal met stiff opposition from local businesses.", zh: "強烈反對、頑強抵抗" },
  { front: "stinging rebuke", pos: "collocation", def: "a sharply hurtful reprimand", example: "The ruling delivered a stinging rebuke to the prosecution's tactics.", zh: "嚴厲斥責" },
  { front: "stony silence", pos: "collocation", def: "a hostile, unresponsive quiet", example: "The announcement was received in stony silence by the workforce.", zh: "冷漠的沉默" },
  { front: "thinly veiled threat", pos: "collocation", def: "a threat barely disguised as something else", example: "The memo contained a thinly veiled threat of redundancies.", zh: "不加掩飾的威脅" },
  { front: "torrential rain", pos: "collocation", def: "extremely heavy rainfall", example: "Torrential rain washed out the third day of the test match.", zh: "傾盆大雨" },
  { front: "towering figure", pos: "collocation", def: "a person of immense influence in a field", example: "She remains a towering figure in post-war architecture.", zh: "泰斗、舉足輕重的人物" },
  { front: "unanimous verdict", pos: "collocation", def: "a decision agreed by everyone", example: "The jury returned a unanimous verdict within the hour.", zh: "一致裁決" },
  { front: "unfettered access", pos: "collocation", def: "completely unrestricted entry or use", example: "Inspectors demanded unfettered access to the enrichment facilities.", zh: "不受限制的進出／使用權" },
  { front: "unpalatable truth", pos: "collocation", def: "a fact that is hard to accept", example: "The report confronts voters with unpalatable truths about pension costs.", zh: "難以接受的事實" },
  { front: "untimely demise", pos: "collocation", def: "a death or end occurring too soon", example: "The magazine's untimely demise left a gap in literary criticism.", zh: "英年早逝、過早消亡" },
  { front: "vantage point", pos: "collocation", def: "a position giving a good view or perspective", example: "From today's vantage point, the panic seems wildly overdone.", zh: "有利位置、觀察角度" },
  { front: "whirlwind romance", pos: "collocation", def: "a rapid, intense love affair", example: "Their whirlwind romance culminated in a wedding within three months.", zh: "旋風式戀情、閃電戀愛" },
  { front: "wistful", pos: "adj.", def: "full of yearning tinged with sadness", example: "He cast a wistful glance at the shuttered family theatre.", zh: "惆悵的、渴望而傷感的" },
  { front: "wry", pos: "adj.", def: "showing dry, mocking humour", example: "She recounted the fiasco with a wry smile.", zh: "苦笑的、揶揄的" },
  { front: "zenith", pos: "n.", def: "the highest point of power or success", example: "The dynasty reached its zenith under the third emperor.", zh: "頂點、鼎盛時期" },
  { front: "windfall", pos: "n.", def: "an unexpected piece of good fortune, especially money", example: "Energy firms faced a levy on their wartime windfall profits.", zh: "意外之財" },
  { front: "taper off", pos: "phrasal v.", def: "gradually decrease in amount or intensity", example: "Attendance tapered off once the novelty wore thin.", zh: "逐漸減少" },
  { front: "track down", pos: "phrasal v.", def: "find after a thorough search", example: "Researchers tracked down the last surviving eyewitness in Uruguay.", zh: "追查到、找到" },
  { front: "wriggle out of", pos: "phrasal v.", def: "avoid an obligation by cunning means", example: "The contractor wriggled out of the warranty on a technicality.", zh: "設法逃避、耍賴脫身" },
  { front: "a household name", pos: "idiom", def: "a person or brand known by everyone", example: "One viral performance made the busker a household name.", zh: "家喻戶曉的名字" },
  { front: "a long shot", pos: "idiom", def: "an attempt with little chance of success", example: "The appeal is a long shot, but the family insists on trying.", zh: "希望渺茫的嘗試" },
  { front: "find one's feet", pos: "idiom", def: "become confident in a new situation", example: "It took the transferred diplomat a year to find her feet in Brussels.", zh: "站穩腳步、適應新環境" },
  { front: "fit the bill", pos: "idiom", def: "be exactly suitable for a purpose", example: "We needed a discreet venue, and the old library fitted the bill.", zh: "正合需求、恰到好處" },
  { front: "follow suit", pos: "idiom", def: "do the same as someone else has done", example: "Once one airline scrapped the fee, its rivals followed suit.", zh: "跟進、如法炮製" },
  { front: "get a foot in the door", pos: "idiom", def: "gain an initial entry into an organisation", example: "An unpaid internship was his only way to get a foot in the door.", zh: "取得入門機會" },
  { front: "go the extra mile", pos: "idiom", def: "make more effort than is expected", example: "The concierge went the extra mile to reunite us with the manuscript.", zh: "加倍努力、多盡一份心力" },
  { front: "in the same boat", pos: "idiom", def: "in the same difficult situation as others", example: "Renters and mortgaged owners alike are in the same boat this winter.", zh: "同病相憐、處境相同" },
  { front: "jump ship", pos: "idiom", def: "abandon an organisation for a rival", example: "Two senior partners jumped ship to the American firm.", zh: "跳槽、棄船而去" },
  { front: "know the ropes", pos: "idiom", def: "be familiar with how something is done", example: "Shadow a senior clerk until you know the ropes.", zh: "熟門熟路、懂得訣竅" },
  { front: "let the cat out of the bag", pos: "idiom", def: "reveal a secret carelessly", example: "The junior minister let the cat out of the bag about the reshuffle.", zh: "洩露祕密、說溜嘴" },
  { front: "make headway", pos: "idiom", def: "make progress despite difficulty", example: "Negotiators made little headway on the fisheries chapter.", zh: "取得進展" },
  { front: "move heaven and earth", pos: "idiom", def: "do everything possible to achieve something", example: "Her lawyers moved heaven and earth to secure the retrial.", zh: "竭盡全力、排除萬難" },
  { front: "on a shoestring", pos: "idiom", def: "with a very small budget", example: "The award-winning documentary was shot on a shoestring.", zh: "以極少的預算" },
  { front: "pass muster", pos: "idiom", def: "be accepted as adequate after inspection", example: "The hurried translation would never pass muster with the examiners.", zh: "通過檢驗、合格" },
  { front: "raise the bar", pos: "idiom", def: "set a higher standard for others", example: "The Norwegian entry raised the bar for the whole competition.", zh: "提高標準" },
  { front: "up the ante", pos: "idiom", def: "increase the stakes or demands", example: "The strikers upped the ante by calling for an indefinite walkout.", zh: "提高賭注、加碼" },
  { front: "flurry of activity", pos: "collocation", def: "a short burst of intense action", example: "The deadline triggered a flurry of activity in the chancery.", zh: "一陣忙亂、短暫的熱潮" },
  { front: "wealth of experience", pos: "collocation", def: "a very large amount of accumulated knowledge", example: "She brings a wealth of experience from three central banks.", zh: "豐富的經驗" },
  { front: "barrage of criticism", pos: "collocation", def: "an overwhelming stream of disapproval", example: "The rebranding met a barrage of criticism from loyal customers.", zh: "排山倒海的批評" },
  { front: "torrent of abuse", pos: "collocation", def: "a rapid outpouring of insults", example: "The referee endured a torrent of abuse from the terraces.", zh: "如潮的辱罵" },
  { front: "lifelong ambition", pos: "collocation", def: "a goal held throughout one's life", example: "Summiting Everest fulfilled a lifelong ambition.", zh: "畢生的抱負" },
  { front: "string of setbacks", pos: "collocation", def: "a series of successive failures", example: "A string of setbacks delayed the probe's launch by four years.", zh: "接二連三的挫敗" },
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
