/* CPE Prep extra vocab wave 4 */
(function () {
  var BANK = [
    { front: "abstemious", pos: "adj.", def: "moderate and sparing, especially with food or drink", example: "His abstemious habits stood in stark contrast to his brother's excesses.", zh: "有節制的；飲食簡樸的" },
    { front: "accretion", pos: "n.", def: "gradual growth or accumulation over time", example: "The law evolved through the slow accretion of precedent rather than reform.", zh: "逐漸累積；添加物" },
    { front: "acumen", pos: "n.", def: "keen insight and sound judgement in a field", example: "Her business acumen turned a failing shop into a national chain.", zh: "敏銳的眼光；精明才幹" },
    { front: "adulation", pos: "n.", def: "excessive, uncritical admiration or flattery", example: "The young star found the public's adulation suffocating rather than gratifying.", zh: "過度的吹捧；諂媚式崇拜" },
    { front: "affable", pos: "adj.", def: "friendly, warm and easy to talk to", example: "Beneath his affable exterior lay a fiercely competitive negotiator.", zh: "和藹可親的；平易近人的" },
    { front: "affront", pos: "n.", def: "an open insult or deliberate offence", example: "She regarded the tribunal's verdict as a personal affront to her integrity.", zh: "公然侮辱；冒犯" },
    { front: "aggrieved", pos: "adj.", def: "feeling wronged or unfairly treated", example: "Aggrieved shareholders demanded the resignation of the entire board.", zh: "感到委屈的；受到不公對待的" },
    { front: "alleviate", pos: "v.", def: "make pain or difficulty less severe", example: "The new bypass did little to alleviate congestion in the town centre.", zh: "減輕；緩和" },
    { front: "aloof", pos: "adj.", def: "distant and uninvolved; not friendly", example: "Critics accused the minister of remaining aloof from the concerns of ordinary voters.", zh: "冷淡疏離的；置身事外的" },
    { front: "altruistic", pos: "adj.", def: "showing selfless concern for others' welfare", example: "His motives were far from altruistic; the donation bought him considerable influence.", zh: "利他的；無私的" },
    { front: "amiable", pos: "adj.", def: "pleasant, friendly and good-natured", example: "Their amiable banter concealed a rivalry of long standing.", zh: "親切友善的；和藹的" },
    { front: "anodyne", pos: "adj.", def: "deliberately inoffensive and therefore dull", example: "The spokesperson offered only anodyne reassurances that satisfied nobody.", zh: "四平八穩而乏味的；不得罪人的" },
    { front: "apex", pos: "n.", def: "the highest point or peak of something", example: "Winning the Nobel Prize marked the apex of her scientific career.", zh: "頂點；巔峰" },
    { front: "apposite", pos: "adj.", def: "strikingly appropriate or relevant", example: "Her apposite quotation from Keats brought the lecture to an elegant close.", zh: "貼切的；恰當的" },
    { front: "apprise", pos: "v.", def: "inform someone formally of something", example: "Counsel was duly apprised of the new evidence before the hearing resumed.", zh: "正式告知；通知" },
    { front: "approbation", pos: "n.", def: "formal approval or praise", example: "The scheme met with the unanimous approbation of the planning committee.", zh: "嘉許；正式認可" },
    { front: "arbiter", pos: "n.", def: "a person with authority to settle disputes", example: "The court remains the final arbiter of what the constitution permits.", zh: "仲裁者；裁決者" },
    { front: "ardent", pos: "adj.", def: "passionately enthusiastic or devoted", example: "An ardent conservationist, she chained herself to the threatened oak.", zh: "熱切的；狂熱的" },
    { front: "ascendancy", pos: "n.", def: "a position of dominance or controlling influence", example: "The reformist faction gradually gained ascendancy within the party.", zh: "支配地位；優勢" },
    { front: "assuage", pos: "v.", def: "make an unpleasant feeling less intense", example: "No amount of official apology could assuage the families' grief.", zh: "緩和；平息（情緒）" },
    { front: "attenuate", pos: "v.", def: "reduce in force, effect or value", example: "Thick walls attenuate the signal, so coverage indoors is patchy.", zh: "使減弱；使稀薄" },
    { front: "avuncular", pos: "adj.", def: "kind and friendly like an uncle", example: "The presenter's avuncular manner made even grim news feel bearable.", zh: "如慈祥長輩般的；和藹的" },
    { front: "awash", pos: "adj.", def: "flooded or overflowing with something", example: "By the nineties the market was awash with cheap imitations.", zh: "充斥的；氾濫的" },
    { front: "badger", pos: "v.", def: "pester someone repeatedly to do something", example: "Reporters badgered the chairman for a comment as he left the courtroom.", zh: "糾纏；一再煩擾" },
    { front: "baleful", pos: "adj.", def: "menacing; threatening harm", example: "He fixed the intruder with a baleful stare.", zh: "凶狠的；帶有惡意的" },
    { front: "balmy", pos: "adj.", def: "pleasantly warm and mild (of weather)", example: "They dined on the terrace, savouring the balmy evening air.", zh: "（天氣）溫和宜人的" },
    { front: "bastion", pos: "n.", def: "an institution strongly defending a principle", example: "The college remained a bastion of tradition long after its rivals modernised.", zh: "堡壘；捍衛者" },
    { front: "bedlam", pos: "n.", def: "a scene of uproar and confusion", example: "It was utter bedlam in the terminal when all flights were grounded.", zh: "混亂喧鬧的場面" },
    { front: "beget", pos: "v.", def: "cause or bring about something", example: "History teaches that violence merely begets further violence.", zh: "引起；導致" },
    { front: "behest", pos: "n.", def: "an authoritative order or request", example: "The inquiry was launched at the behest of the prime minister.", zh: "命令；要求" },
    { front: "beholden", pos: "adj.", def: "owing gratitude or obligation to someone", example: "She refused the loan, unwilling to be beholden to her in-laws.", zh: "欠人情的；受恩於人的" },
    { front: "bemoan", pos: "v.", def: "complain about or lament something", example: "Purists bemoan the creeping commercialisation of the festival.", zh: "哀嘆；抱怨" },
    { front: "bemused", pos: "adj.", def: "puzzled, confused or bewildered", example: "The tourists looked on, bemused, as the locals argued in dialect.", zh: "困惑不解的" },
    { front: "benign", pos: "adj.", def: "gentle and harmless; not threatening", example: "What seemed a benign clause proved ruinous once the contract was signed.", zh: "良性的；溫和無害的" },
    { front: "bereft", pos: "adj.", def: "deprived of or lacking something needed", example: "After the factory closed, the town seemed bereft of purpose.", zh: "喪失的；缺乏的" },
    { front: "besiege", pos: "v.", def: "overwhelm someone with requests or attention", example: "The helpline was besieged with calls within minutes of the announcement.", zh: "圍攻；（要求）蜂擁而至" },
    { front: "besmirch", pos: "v.", def: "damage someone's reputation; tarnish", example: "He sued the tabloid for besmirching his professional reputation.", zh: "玷污（名譽）" },
    { front: "bespoke", pos: "adj.", def: "made to order for a particular customer", example: "The consultancy designs bespoke software for boutique investment firms.", zh: "訂製的；量身打造的" },
    { front: "blight", pos: "n.", def: "something that spoils or damages severely", example: "Youth unemployment remains a blight on the region's prospects.", zh: "禍害；破壞性因素" },
    { front: "bluster", pos: "v.", def: "talk loudly and aggressively with little effect", example: "The colonel blustered about consequences but ultimately backed down.", zh: "咆哮；虛張聲勢" },
    { front: "bode", pos: "v.", def: "be an omen of a particular outcome", example: "The plummeting pound bodes ill for import-dependent businesses.", zh: "預示；是……之兆" },
    { front: "account for", pos: "phrasal v.", def: "explain the cause of; constitute a proportion", example: "Renewables now account for a third of the nation's electricity.", zh: "解釋；佔（比例）" },
    { front: "act up", pos: "phrasal v.", def: "behave badly or function erratically", example: "The printer started acting up just as the deadline loomed.", zh: "耍脾氣；（機器）出毛病" },
    { front: "back out of", pos: "phrasal v.", def: "withdraw from a commitment or agreement", example: "The investors backed out of the deal at the eleventh hour.", zh: "退出；反悔" },
    { front: "bargain for", pos: "phrasal v.", def: "expect or be prepared for something", example: "The scandal generated far more publicity than the agency had bargained for.", zh: "預料到；料想到" },
    { front: "bear up", pos: "phrasal v.", def: "remain strong despite difficulty", example: "She bore up remarkably well under relentless cross-examination.", zh: "撐住；堅強面對" },
    { front: "break off", pos: "phrasal v.", def: "end a relationship or stop abruptly", example: "The two countries broke off diplomatic relations after the incident.", zh: "中斷；斷絕（關係）" },
    { front: "brood over", pos: "phrasal v.", def: "think anxiously or resentfully about something", example: "He spent the winter brooding over the injustice of his dismissal.", zh: "耿耿於懷；憂思" },
    { front: "brush off", pos: "phrasal v.", def: "dismiss someone or something curtly", example: "The CEO brushed off questions about the impending merger.", zh: "不予理會；敷衍打發" },
    { front: "buckle under", pos: "phrasal v.", def: "collapse or yield under pressure", example: "Several small suppliers buckled under the strain of late payments.", zh: "屈服；不堪重負而垮掉" },
    { front: "cast about for", pos: "phrasal v.", def: "search around for something, often desperately", example: "The party is casting about for a credible successor to its ageing leader.", zh: "四處尋找；搜尋" },
    { front: "cater to", pos: "phrasal v.", def: "provide what someone wants or needs", example: "The resort caters unashamedly to the whims of the ultra-rich.", zh: "迎合；滿足需求" },
    { front: "chip in", pos: "phrasal v.", def: "contribute money or add a remark", example: "Colleagues chipped in to cover her travel costs to the conference.", zh: "湊錢；插話" },
    { front: "a bolt from the blue", pos: "idiom", def: "a sudden and completely unexpected event", example: "Her resignation came as a bolt from the blue to everyone in the department.", zh: "晴天霹靂；突如其來的事" },
    { front: "a busman's holiday", pos: "idiom", def: "leisure time spent doing one's usual work", example: "For the chef, cooking at the charity gala was a busman's holiday.", zh: "照樣做本行工作的假期" },
    { front: "a case in point", pos: "idiom", def: "a clear example of what is being discussed", example: "Rising rents are pricing out young families; Camden is a case in point.", zh: "恰當的例子；例證" },
    { front: "a close shave", pos: "idiom", def: "a narrow escape from danger or failure", example: "The near-collision on the runway was described as a very close shave.", zh: "千鈞一髮；死裡逃生" },
    { front: "a cog in the machine", pos: "idiom", def: "a minor, easily replaced member of an organisation", example: "He resigned, weary of feeling like a mere cog in the machine.", zh: "大機器裡的小螺絲釘" },
    { front: "a far cry from", pos: "idiom", def: "very different from something", example: "The cramped flat was a far cry from the mansion of her childhood.", zh: "與……相去甚遠" },
    { front: "a fool's errand", pos: "idiom", def: "a task certain to be fruitless", example: "Seeking consensus among the warring factions proved a fool's errand.", zh: "徒勞無功的差事" },
    { front: "a grey area", pos: "idiom", def: "an ill-defined situation lacking clear rules", example: "The legality of scraping public data remains a grey area.", zh: "模糊地帶；灰色地帶" },
    { front: "a mine of information", pos: "idiom", def: "a rich source of useful knowledge", example: "The retired archivist is a mine of information on local history.", zh: "知識寶庫；消息靈通的來源" },
    { front: "a poisoned chalice", pos: "idiom", def: "an appealing role that brings serious trouble", example: "The chairmanship of the ailing club proved a poisoned chalice.", zh: "看似誘人實則燙手的職位" },
    { front: "a rough diamond", pos: "idiom", def: "a person of good character but unpolished manners", example: "The young striker is a rough diamond whom the coach intends to refine.", zh: "未經雕琢的璞玉" },
    { front: "abysmal record", pos: "collocation", def: "an extremely bad history of performance", example: "The airline's abysmal record on punctuality finally cost it the contract.", zh: "極差的紀錄" },
    { front: "blazing row", pos: "collocation", def: "a very heated, angry argument", example: "Neighbours reported hearing a blazing row shortly before midnight.", zh: "激烈爭吵" },
    { front: "blind faith", pos: "collocation", def: "unquestioning trust without evidence", example: "Investors placed blind faith in the founder's ever-grander promises.", zh: "盲目的信任" },
    { front: "buoyant economy", pos: "collocation", def: "an economy that is thriving and confident", example: "A buoyant economy masked the structural weaknesses in the banking sector.", zh: "蓬勃的經濟" },
    { front: "bumpy ride", pos: "collocation", def: "a difficult period with many problems", example: "Analysts predict a bumpy ride for retailers this quarter.", zh: "顛簸的歷程；坎坷的過程" },
    { front: "burning ambition", pos: "collocation", def: "an intense, driving desire to achieve something", example: "Her burning ambition to conduct at La Scala never dimmed.", zh: "熾熱的抱負" },
    { front: "calculated risk", pos: "collocation", def: "a risk taken after careful assessment", example: "Launching before Christmas was a calculated risk that paid off handsomely.", zh: "經過盤算的風險" },
    { front: "cardinal rule", pos: "collocation", def: "a fundamental principle that must not be broken", example: "Never invest what you cannot afford to lose is the cardinal rule.", zh: "基本原則；金科玉律" },
    { front: "catalogue of errors", pos: "collocation", def: "a long series of mistakes", example: "The inquiry exposed a catalogue of errors stretching back a decade.", zh: "一連串的錯誤" },
    { front: "cast-iron guarantee", pos: "collocation", def: "an absolutely firm and reliable promise", example: "The minister gave a cast-iron guarantee that the hospital would stay open.", zh: "鐵一般的保證" },
    { front: "chilling effect", pos: "collocation", def: "a discouraging influence on legitimate activity", example: "The libel ruling had a chilling effect on investigative journalism.", zh: "寒蟬效應" },
    { front: "boisterous", pos: "adj.", def: "noisy, energetic and cheerful; rowdy", example: "A boisterous crowd of freshers spilled out of the union bar.", zh: "喧鬧的；活蹦亂跳的" },
    { front: "bona fide", pos: "adj.", def: "genuine; made in good faith", example: "Only bona fide residents are entitled to the parking permit.", zh: "真實的；善意的" },
    { front: "bravado", pos: "n.", def: "a bold show of courage masking fear", example: "His bravado deserted him the moment the judge entered.", zh: "虛張聲勢；逞英雄" },
    { front: "brevity", pos: "n.", def: "concise use of words; shortness", example: "The report's brevity was welcome after months of bloated memoranda.", zh: "簡潔；簡短" },
    { front: "broach", pos: "v.", def: "raise a sensitive subject for discussion", example: "She waited until dessert to broach the question of his retirement.", zh: "提起（敏感話題）" },
    { front: "browbeat", pos: "v.", def: "intimidate someone into doing something", example: "Junior staff were browbeaten into signing the amended contracts.", zh: "威嚇；恫嚇使就範" },
    { front: "buttress", pos: "v.", def: "support or strengthen an argument or position", example: "The defence buttressed its case with newly discovered correspondence.", zh: "支撐；強化" },
    { front: "byword", pos: "n.", def: "a name synonymous with a particular quality", example: "The label has become a byword for understated luxury.", zh: "代名詞；典型" },
    { front: "calamity", pos: "n.", def: "an event causing great damage or distress", example: "The dam's failure was a calamity from which the valley never recovered.", zh: "災難；不幸" },
    { front: "callow", pos: "adj.", def: "inexperienced and immature", example: "He joined the paper as a callow graduate and left as its editor.", zh: "乳臭未乾的；不成熟的" },
    { front: "canny", pos: "adj.", def: "shrewd and careful, especially in business", example: "A canny investor, she sold her holdings weeks before the crash.", zh: "精明的；謹慎的" },
    { front: "cantankerous", pos: "adj.", def: "bad-tempered and argumentative", example: "The cantankerous landlord quarrelled with every tenant he ever had.", zh: "脾氣壞的；愛爭吵的" },
    { front: "cataclysmic", pos: "adj.", def: "involving sudden, violent upheaval", example: "The referendum triggered a cataclysmic realignment of party politics.", zh: "劇變的；災難性的" },
    { front: "catharsis", pos: "n.", def: "emotional release through expressing strong feelings", example: "Writing the memoir was a catharsis after decades of silence.", zh: "情感宣洩；淨化" },
    { front: "caveat", pos: "n.", def: "a warning or condition to consider", example: "The findings are promising, with the caveat that the sample was small.", zh: "但書；警語" },
    { front: "cede", pos: "v.", def: "give up power or territory formally", example: "The treaty obliged the empire to cede its coastal provinces.", zh: "割讓；讓出" },
    { front: "chastise", pos: "v.", def: "criticise or rebuke someone severely", example: "The referee was chastised in the press for his baffling decisions.", zh: "嚴厲斥責" },
    { front: "chide", pos: "v.", def: "scold or rebuke mildly", example: "She chided him gently for forgetting their anniversary yet again.", zh: "責備；數落" },
    { front: "churlish", pos: "adj.", def: "rude and ungracious", example: "It would be churlish to deny the team credit for a spirited comeback.", zh: "無禮的；不領情的" },
    { front: "circumlocution", pos: "n.", def: "using many words to avoid speaking directly", example: "The minister's circumlocution failed to conceal the simple fact of failure.", zh: "拐彎抹角的說法" },
    { front: "clout", pos: "n.", def: "power or influence, especially political", example: "The union still wields considerable clout in the northern constituencies.", zh: "影響力；勢力" },
    { front: "cloying", pos: "adj.", def: "sickeningly sweet or sentimental", example: "The film's cloying finale undid two hours of careful restraint.", zh: "甜膩的；令人生膩的" },
    { front: "coax", pos: "v.", def: "persuade gently and patiently", example: "It took an hour to coax the frightened cat down from the roof.", zh: "哄勸；勸誘" },
    { front: "cognizant", pos: "adj.", def: "aware of; having knowledge of", example: "The board was fully cognizant of the risks when it approved the venture.", zh: "知悉的；意識到的" },
    { front: "complicit", pos: "adj.", def: "involved in wrongdoing with others", example: "By staying silent, the auditors were complicit in the deception.", zh: "共謀的；同流合污的" },
    { front: "concomitant", pos: "adj.", def: "naturally occurring together with something", example: "Rapid growth brought a concomitant rise in pollution.", zh: "伴隨而來的" },
    { front: "condescending", pos: "adj.", def: "showing patronising superiority", example: "Her condescending tone alienated the very voters she hoped to win.", zh: "居高臨下的；傲慢的" },
    { front: "conflagration", pos: "n.", def: "a large destructive fire; a violent conflict", example: "A border skirmish threatened to ignite a regional conflagration.", zh: "大火；大規模衝突" },
    { front: "confluence", pos: "n.", def: "a coming together of factors, ideas or rivers", example: "The crisis arose from a confluence of drought, debt and misrule.", zh: "匯流；多重因素交會" },
    { front: "consign", pos: "v.", def: "put someone or something in an unwanted position", example: "The defeat consigned the party to another decade in opposition.", zh: "使淪落；打入（某處境）" },
    { front: "coterie", pos: "n.", def: "a small exclusive group with shared interests", example: "Policy was decided by a coterie of unelected advisers.", zh: "小圈子；核心集團" },
    { front: "covert", pos: "adj.", def: "secret or hidden; not openly acknowledged", example: "The agency ran a covert operation to monitor the arms shipments.", zh: "祕密的；隱蔽的" },
    { front: "cower", pos: "v.", def: "crouch or shrink back in fear", example: "The dog cowered under the table throughout the thunderstorm.", zh: "畏縮；蜷縮" },
    { front: "crass", pos: "adj.", def: "showing gross insensitivity or stupidity", example: "His crass joke about the layoffs stunned the room into silence.", zh: "粗俗愚鈍的；不得體的" },
    { front: "credence", pos: "n.", def: "belief in or acceptance of something as true", example: "The leaked memo lends credence to claims of a cover-up.", zh: "相信；可信性" },
    { front: "crestfallen", pos: "adj.", def: "sad and disappointed after a failure", example: "The crestfallen candidate thanked her supporters and conceded defeat.", zh: "垂頭喪氣的" },
    { front: "cronyism", pos: "n.", def: "favouritism shown to friends in appointments", example: "The audit exposed rampant cronyism in the awarding of contracts.", zh: "任人唯親；裙帶關係" },
    { front: "cull", pos: "v.", def: "select and remove; reduce numbers selectively", example: "The editor culled the weakest chapters from the sprawling manuscript.", zh: "篩除；淘汰" },
    { front: "dapper", pos: "adj.", def: "neat and stylish in dress (of a man)", example: "The dapper octogenarian never left home without a silk pocket square.", zh: "衣著整潔講究的" },
    { front: "dawdle", pos: "v.", def: "move or act slowly; waste time", example: "Stop dawdling over breakfast or we shall miss the train.", zh: "磨蹭；拖拖拉拉" },
    { front: "debonair", pos: "adj.", def: "confident, stylish and charming (of a man)", example: "He cultivated the debonair air of a 1950s matinee idol.", zh: "溫文瀟灑的" },
    { front: "clamour for", pos: "phrasal v.", def: "demand something loudly and insistently", example: "Fans clamoured for the striker's inclusion in the starting eleven.", zh: "大聲疾呼要求" },
    { front: "claw back", pos: "phrasal v.", def: "recover money or advantage with difficulty", example: "The treasury moved to claw back the bonuses paid in error.", zh: "追回；奪回" },
    { front: "come by", pos: "phrasal v.", def: "manage to obtain something", example: "Reliable statistics on the informal economy are hard to come by.", zh: "獲得；弄到" },
    { front: "crack on with", pos: "phrasal v.", def: "continue working on something briskly", example: "With the deadline looming, we cracked on with the final edits.", zh: "加緊進行" },
    { front: "cry off", pos: "phrasal v.", def: "withdraw from an arrangement at short notice", example: "Two speakers cried off the day before the symposium.", zh: "臨時取消；打退堂鼓" },
    { front: "cut back on", pos: "phrasal v.", def: "reduce spending or consumption of something", example: "Households are cutting back on non-essentials as prices soar.", zh: "削減；縮減" },
    { front: "defer to", pos: "phrasal v.", def: "yield to another's judgement or authority", example: "On matters of protocol, the ambassador deferred to his seasoned attaché.", zh: "聽從；尊重（他人意見）" },
    { front: "dispense with", pos: "phrasal v.", def: "do without; get rid of something unnecessary", example: "The new format dispenses with the tedious opening ceremony altogether.", zh: "省去；免除" },
    { front: "dote on", pos: "phrasal v.", def: "love and indulge someone excessively", example: "She dotes on her grandchildren, spoiling them at every visit.", zh: "溺愛；寵愛" },
    { front: "draw on", pos: "phrasal v.", def: "use a resource or experience for help", example: "The novelist drew on her years at sea for the book's vivid detail.", zh: "汲取；利用" },
    { front: "dream up", pos: "phrasal v.", def: "invent an idea, often an impractical one", example: "Marketing dreamt up an elaborate stunt involving a hot-air balloon.", zh: "憑空想出；構想出" },
    { front: "dress down", pos: "phrasal v.", def: "reprimand someone severely", example: "The sergeant dressed down the recruits for their slovenly kit.", zh: "訓斥；斥責" },
    { front: "a sitting duck", pos: "idiom", def: "an easy, defenceless target", example: "Without air cover, the convoy was a sitting duck.", zh: "活靶子；易受攻擊的目標" },
    { front: "a sticking point", pos: "idiom", def: "an issue that blocks progress in negotiations", example: "Pension reform remains the main sticking point in the coalition talks.", zh: "癥結；僵持點" },
    { front: "at face value", pos: "idiom", def: "accepting something as it appears, without scrutiny", example: "Seasoned reporters never take official casualty figures at face value.", zh: "照表面意思接受" },
    { front: "at the drop of a hat", pos: "idiom", def: "immediately, without hesitation", example: "He would abandon any meeting at the drop of a hat to watch cricket.", zh: "毫不猶豫地；隨時" },
    { front: "at the end of one's tether", pos: "idiom", def: "having no patience or endurance left", example: "After months of sleepless nights, the new parents were at the end of their tether.", zh: "忍無可忍；精疲力竭" },
    { front: "back the wrong horse", pos: "idiom", def: "support a person or plan that fails", example: "Investors who backed the wrong horse in the format war lost millions.", zh: "押錯寶；支持錯對象" },
    { front: "be in one's element", pos: "idiom", def: "be doing what one enjoys and does best", example: "Surrounded by rare manuscripts, the archivist was in her element.", zh: "如魚得水" },
    { front: "beat a hasty retreat", pos: "idiom", def: "leave quickly to avoid trouble", example: "Seeing the bill, the freeloaders beat a hasty retreat.", zh: "倉皇撤退；趕緊溜走" },
    { front: "behind closed doors", pos: "idiom", def: "in private, away from public view", example: "The settlement was thrashed out behind closed doors.", zh: "閉門地；不公開地" },
    { front: "bide one's time", pos: "idiom", def: "wait patiently for the right opportunity", example: "The deposed chairman bided his time, courting allies on the board.", zh: "等待時機" },
    { front: "bring to light", pos: "idiom", def: "reveal something previously hidden", example: "The audit brought to light a web of undisclosed payments.", zh: "揭露；使曝光" },
    { front: "close-knit community", pos: "collocation", def: "a group whose members support each other closely", example: "News travels fast in a close-knit community like this.", zh: "關係緊密的社區" },
    { front: "come to fruition", pos: "collocation", def: "be realised or achieved after effort", example: "Plans for the coastal railway finally came to fruition after thirty years.", zh: "開花結果；實現" },
    { front: "fever pitch", pos: "collocation", def: "a state of extreme excitement", example: "Speculation about the transfer reached fever pitch on deadline day.", zh: "極度狂熱；沸點" },
    { front: "freak accident", pos: "collocation", def: "a highly unusual and unpredictable mishap", example: "The climber died in a freak accident involving a falling icicle.", zh: "離奇的意外" },
    { front: "grind to a halt", pos: "collocation", def: "gradually stop working or moving completely", example: "Production ground to a halt when the chip supply dried up.", zh: "逐漸停擺" },
    { front: "gross misconduct", pos: "collocation", def: "behaviour serious enough to justify dismissal", example: "Falsifying safety records constitutes gross misconduct under the code.", zh: "重大失職；嚴重不當行為" },
    { front: "grudging respect", pos: "collocation", def: "admiration given reluctantly", example: "Even his fiercest critics developed a grudging respect for his stamina.", zh: "勉強的敬意" },
    { front: "hatch a plot", pos: "collocation", def: "secretly devise a scheme", example: "The conspirators hatched a plot to oust the founder at the AGM.", zh: "密謀策劃" },
    { front: "heap praise on", pos: "collocation", def: "praise someone lavishly", example: "Critics heaped praise on the debut novel's audacious structure.", zh: "大加讚揚" },
    { front: "hotly contested", pos: "collocation", def: "fought over with great intensity", example: "The seat has been hotly contested at every election since 1997.", zh: "競爭激烈的" },
    { front: "incandescent with rage", pos: "collocation", def: "extremely angry", example: "The manager was incandescent with rage at the disallowed goal.", zh: "怒不可遏" },
    { front: "decadent", pos: "adj.", def: "marked by moral or cultural decline; self-indulgent", example: "The critics dismissed the banquet scene as decadent excess.", zh: "頹廢的；奢靡的" },
    { front: "decimate", pos: "v.", def: "destroy a large proportion of something", example: "Disease decimated the region's olive groves within two seasons.", zh: "大量毀滅；重創" },
    { front: "decrepit", pos: "adj.", def: "worn out or ruined by age and neglect", example: "The decrepit pier was finally condemned as unsafe.", zh: "破舊的；老朽的" },
    { front: "defame", pos: "v.", def: "damage someone's good reputation with false statements", example: "The actor claimed the article defamed him and demanded a retraction.", zh: "誹謗；中傷" },
    { front: "defunct", pos: "adj.", def: "no longer existing or functioning", example: "The archive preserves recordings from long-defunct radio stations.", zh: "已不存在的；停辦的" },
    { front: "delude", pos: "v.", def: "make someone believe something false", example: "He deluded himself into thinking the debts would simply vanish.", zh: "欺騙；使產生錯覺" },
    { front: "deluge", pos: "n.", def: "an overwhelming flood or quantity of something", example: "The helpdesk faced a deluge of complaints after the botched update.", zh: "洪水；蜂擁而至的大量事物" },
    { front: "demagogue", pos: "n.", def: "a leader who exploits prejudice rather than reason", example: "The pamphlet warned that economic despair breeds demagogues.", zh: "煽動家；蠱惑民心的政客" },
    { front: "demure", pos: "adj.", def: "reserved, modest and shy in manner", example: "Her demure appearance belied a razor-sharp courtroom style.", zh: "嫻靜端莊的" },
    { front: "denizen", pos: "n.", def: "an inhabitant or frequenter of a place", example: "The nocturnal denizens of the harbour district knew him well.", zh: "居民；常客" },
    { front: "depose", pos: "v.", def: "remove a ruler or leader from power", example: "The generals deposed the president in a bloodless coup.", zh: "罷黜；推翻" },
    { front: "derelict", pos: "adj.", def: "abandoned and in a state of disrepair", example: "Artists converted the derelict warehouse into studios.", zh: "廢棄的；荒廢的" },
    { front: "desecrate", pos: "v.", def: "treat a sacred place or thing with violent disrespect", example: "Vandals desecrated the war memorial on the eve of the ceremony.", zh: "褻瀆；汙損（聖地）" },
    { front: "despot", pos: "n.", def: "a ruler who wields absolute, often cruel power", example: "The archives reveal how the despot micromanaged even village affairs.", zh: "暴君；專制者" },
    { front: "dilatory", pos: "adj.", def: "slow to act; intended to cause delay", example: "The defence's dilatory tactics stretched the trial into a third year.", zh: "拖延的；磨蹭的" },
    { front: "dilettante", pos: "n.", def: "a dabbler lacking serious commitment to a subject", example: "Serious collectors dismissed him as a dilettante with deep pockets.", zh: "業餘涉獵者；半吊子" },
    { front: "disavow", pos: "v.", def: "deny any responsibility for or connection with", example: "The party leadership swiftly disavowed the councillor's remarks.", zh: "否認；撇清關係" },
    { front: "disconcerting", pos: "adj.", def: "unsettling; causing one to feel unsure", example: "She had the disconcerting habit of quoting your own words back at you.", zh: "令人不安的；使人慌亂的" },
    { front: "discordant", pos: "adj.", def: "clashing; not in harmony", example: "His flippant tone struck a discordant note at the memorial.", zh: "不和諧的；刺耳的" },
    { front: "disgruntled", pos: "adj.", def: "annoyed and dissatisfied", example: "Disgruntled season-ticket holders staged a protest outside the ground.", zh: "不滿的；憤懣的" },
    { front: "dishevelled", pos: "adj.", def: "untidy in appearance; unkempt", example: "He arrived dishevelled and breathless, minutes after the vote had closed.", zh: "凌亂的；不修邊幅的" },
    { front: "dissemble", pos: "v.", def: "conceal one's true motives or feelings", example: "A skilled diplomat must sometimes dissemble without actually lying.", zh: "掩飾；裝糊塗" },
    { front: "dissipate", pos: "v.", def: "disperse or gradually disappear; squander", example: "The initial euphoria dissipated as the practical difficulties emerged.", zh: "消散；揮霍" },
    { front: "dither", pos: "v.", def: "be indecisive; hesitate", example: "While the committee dithered, rival cities snapped up the investment.", zh: "猶豫不決" },
    { front: "divisive", pos: "adj.", def: "causing disagreement or hostility between people", example: "Few issues are as divisive as the proposed toll on the old bridge.", zh: "引起分裂的；造成對立的" },
    { front: "doleful", pos: "adj.", def: "expressing sorrow; mournful", example: "The bloodhound regarded us with doleful, drooping eyes.", zh: "悲哀的；愁苦的" },
    { front: "droll", pos: "adj.", def: "amusing in an odd, dry way", example: "Her droll asides enlivened an otherwise soporific seminar.", zh: "冷面滑稽的；詼諧的" },
    { front: "duress", pos: "n.", def: "threats or force used to compel someone", example: "The court ruled that the confession had been obtained under duress.", zh: "脅迫；威逼" },
    { front: "earmark", pos: "v.", def: "designate funds or resources for a specific purpose", example: "Half the windfall has been earmarked for flood defences.", zh: "指定用途；預留" },
    { front: "edict", pos: "n.", def: "an official order issued by an authority", example: "By imperial edict, all printing presses required a licence.", zh: "法令；敕令" },
    { front: "effervescent", pos: "adj.", def: "vivacious and enthusiastic; bubbly", example: "Her effervescent stage presence carried an otherwise pedestrian script.", zh: "熱情洋溢的；冒泡的" },
    { front: "elated", pos: "adj.", def: "extremely happy and excited", example: "The elated crew watched the probe's first signals arrive from Mars.", zh: "興高采烈的" },
    { front: "embezzle", pos: "v.", def: "steal money entrusted to one's care", example: "The treasurer embezzled donations over more than a decade.", zh: "侵占；挪用（公款）" },
    { front: "encapsulate", pos: "v.", def: "express the essence of something concisely", example: "The slogan neatly encapsulates the city's ambivalence towards tourism.", zh: "概括；濃縮呈現" },
    { front: "enclave", pos: "n.", def: "a distinct territory or group within a larger one", example: "The old quarter survives as an enclave of artisan workshops.", zh: "飛地；聚居區" },
    { front: "encumber", pos: "v.", def: "burden or impede someone or something", example: "The expedition was encumbered by equipment it never used.", zh: "拖累；妨礙" },
    { front: "engrossed", pos: "adj.", def: "having all one's attention absorbed", example: "Engrossed in the manuscript, she failed to notice the fire alarm.", zh: "全神貫注的" },
    { front: "enliven", pos: "v.", def: "make more interesting or lively", example: "Anecdotes from his consular days enlivened the dry lecture.", zh: "使生動；使活躍" },
    { front: "enormity", pos: "n.", def: "the extreme seriousness or scale of something bad", example: "Only later did the enormity of the security breach become clear.", zh: "（惡行的）嚴重性；巨大" },
    { front: "ensnare", pos: "v.", def: "trap or catch someone by trickery", example: "The sting operation ensnared officials at the highest levels.", zh: "誘捕；使落入圈套" },
    { front: "ensue", pos: "v.", def: "happen afterwards as a result", example: "A furious row ensued when the minutes were leaked.", zh: "隨之發生；接踵而至" },
    { front: "drone on", pos: "phrasal v.", def: "talk tediously at length", example: "The chairman droned on about procedure while the market crashed.", zh: "喋喋不休；單調地說個不停" },
    { front: "duck out of", pos: "phrasal v.", def: "avoid a duty or commitment", example: "He ducked out of the panel discussion, pleading a diary clash.", zh: "逃避；開溜" },
    { front: "dumb down", pos: "phrasal v.", def: "make something simpler and less intellectually demanding", example: "Educators accused the network of dumbing down its science coverage.", zh: "淺薄化；降低知識水準" },
    { front: "embark on", pos: "phrasal v.", def: "begin a new project or course of action", example: "At sixty she embarked on a second career as a mediator.", zh: "著手進行；展開" },
    { front: "fall out with", pos: "phrasal v.", def: "quarrel and stop being friendly with someone", example: "The co-founders fell out with each other over the licensing deal.", zh: "鬧翻；不和" },
    { front: "fish for", pos: "phrasal v.", def: "try to obtain praise or information indirectly", example: "He kept mentioning his award, transparently fishing for compliments.", zh: "拐彎抹角地探求" },
    { front: "fret over", pos: "phrasal v.", def: "worry persistently about something", example: "Stop fretting over details the examiners will never notice.", zh: "為……煩惱不已" },
    { front: "glaze over", pos: "phrasal v.", def: "become dull or inattentive (of eyes or expression)", example: "Mention pension regulations and most listeners' eyes glaze over.", zh: "（眼神）呆滯；失去興趣" },
    { front: "gravitate towards", pos: "phrasal v.", def: "be naturally drawn to something or someone", example: "Ambitious graduates gravitate towards the capital's tech quarter.", zh: "自然而然地傾向；被吸引" },
    { front: "hammer home", pos: "phrasal v.", def: "emphasise a point forcefully and repeatedly", example: "The campaign hammered home the link between speed and fatalities.", zh: "反覆強調" },
    { front: "kowtow to", pos: "phrasal v.", def: "be excessively submissive towards someone", example: "The editor refused to kowtow to advertisers' demands.", zh: "卑躬屈膝；唯命是從" },
    { front: "pander to", pos: "phrasal v.", def: "gratify base desires or unreasonable expectations", example: "The tabloid panders to its readers' appetite for scandal.", zh: "迎合（低俗需求）" },
    { front: "call it a day", pos: "idiom", def: "stop working, temporarily or permanently", example: "After forty years behind the counter, the barber decided to call it a day.", zh: "到此為止；收工" },
    { front: "call someone's bluff", pos: "idiom", def: "challenge someone to carry out an empty threat", example: "The union called management's bluff and the lockout never materialised.", zh: "戳穿虛張聲勢；將對方一軍" },
    { front: "cast aspersions on", pos: "idiom", def: "make critical or damaging remarks about", example: "Counsel objected to attempts to cast aspersions on the witness's character.", zh: "中傷；詆毀" },
    { front: "caught red-handed", pos: "idiom", def: "discovered in the act of doing wrong", example: "The forger was caught red-handed with the plates still inked.", zh: "當場被逮；人贓俱獲" },
    { front: "cut both ways", pos: "idiom", def: "have both advantages and disadvantages", example: "Transparency cuts both ways: it exposes rivals' flaws and your own.", zh: "利弊互見；雙面刃" },
    { front: "draw the line at", pos: "idiom", def: "refuse to go beyond a certain point", example: "She tolerated long hours but drew the line at working Christmas Day.", zh: "劃清底線；拒絕逾越" },
    { front: "fall foul of", pos: "idiom", def: "come into conflict with rules or authority", example: "The advert fell foul of regulations on health claims.", zh: "觸犯；與……發生衝突" },
    { front: "fall on hard times", pos: "idiom", def: "experience a period of poverty or misfortune", example: "The once-grand hotel fell on hard times after the resort declined.", zh: "陷入困頓；家道中落" },
    { front: "feather one's own nest", pos: "idiom", def: "enrich oneself dishonestly using one's position", example: "The trustee stood accused of feathering his own nest with charity funds.", zh: "中飽私囊" },
    { front: "get a word in edgeways", pos: "idiom", def: "manage to speak amid others' constant talking", example: "With both aunts in full flow, nobody else could get a word in edgeways.", zh: "插得上話" },
    { front: "get down to brass tacks", pos: "idiom", def: "start discussing the essential practical details", example: "Pleasantries over, the negotiators got down to brass tacks.", zh: "言歸正傳；談實質問題" },
    { front: "irrevocable decision", pos: "collocation", def: "a decision that cannot be changed or reversed", example: "Signing the waiver is an irrevocable decision, so read it carefully.", zh: "不可撤回的決定" },
    { front: "litany of complaints", pos: "collocation", def: "a long, repetitive list of grievances", example: "The ombudsman received a litany of complaints about the billing system.", zh: "連篇累牘的抱怨" },
    { front: "maiden voyage", pos: "collocation", def: "a ship's or venture's first journey", example: "The liner sank on her maiden voyage, a fact etched into maritime lore.", zh: "處女航；首航" },
    { front: "make or break", pos: "collocation", def: "decisive for success or failure", example: "The Christmas season is make or break for small retailers.", zh: "成敗攸關" },
    { front: "meagre wages", pos: "collocation", def: "very low pay, barely sufficient to live on", example: "Pickers toil twelve-hour days for meagre wages.", zh: "微薄的工資" },
    { front: "momentous decision", pos: "collocation", def: "a decision of great importance and consequence", example: "The cabinet faced the momentous decision of whether to devalue.", zh: "重大的決定" },
    { front: "moral high ground", pos: "collocation", def: "a position of ethical superiority in a dispute", example: "By disclosing its own errors first, the firm claimed the moral high ground.", zh: "道德制高點" },
    { front: "muted response", pos: "collocation", def: "a restrained, unenthusiastic reaction", example: "The peace initiative drew a muted response from both capitals.", zh: "冷淡的回應" },
    { front: "nail-biting finish", pos: "collocation", def: "an extremely tense, close conclusion", example: "The relay came down to a nail-biting finish decided by hundredths.", zh: "扣人心弦的結局" },
    { front: "paradigm shift", pos: "collocation", def: "a fundamental change in approach or assumptions", example: "The discovery forced a paradigm shift in theories of human migration.", zh: "典範轉移" },
    { front: "pent-up frustration", pos: "collocation", def: "suppressed annoyance that has accumulated", example: "Years of pent-up frustration erupted at the shareholders' meeting.", zh: "積壓已久的不滿" },
    { front: "entreat", pos: "v.", def: "beg someone earnestly to do something", example: "She entreated the tribunal to consider her client's failing health.", zh: "懇求；乞求" },
    { front: "enunciate", pos: "v.", def: "pronounce clearly; state precisely", example: "The coach taught the debaters to enunciate every syllable.", zh: "清晰發音；闡明" },
    { front: "envisage", pos: "v.", def: "imagine or foresee as a future possibility", example: "The planners envisage a car-free city centre within a decade.", zh: "設想；預見" },
    { front: "epiphany", pos: "n.", def: "a sudden moment of profound insight", example: "Watching the gulls, he had an epiphany about wing design.", zh: "頓悟；豁然開朗" },
    { front: "eulogy", pos: "n.", def: "a speech praising someone, especially the deceased", example: "Her eulogy captured both his brilliance and his mischief.", zh: "悼詞；頌詞" },
    { front: "evince", pos: "v.", def: "show or reveal a quality or feeling clearly", example: "The committee evinced little enthusiasm for yet another restructuring.", zh: "表明；顯示" },
    { front: "exhort", pos: "v.", def: "urge someone strongly to do something", example: "The captain exhorted her weary crew to one final effort.", zh: "力勸；敦促" },
    { front: "extant", pos: "adj.", def: "still in existence; surviving", example: "Only three extant copies of the first folio are in private hands.", zh: "現存的；尚存的" },
    { front: "extricate", pos: "v.", def: "free someone or something from a difficulty", example: "The firm struggled to extricate itself from the ruinous joint venture.", zh: "使脫身；解脫" },
    { front: "exult", pos: "v.", def: "rejoice triumphantly", example: "The home crowd exulted as the final wicket fell.", zh: "歡欣鼓舞；狂喜" },
    { front: "falter", pos: "v.", def: "lose strength or momentum; hesitate", example: "Her voice faltered as she read the names of the missing.", zh: "衰退；支吾；蹣跚" },
    { front: "feisty", pos: "adj.", def: "spirited, determined and combative", example: "The feisty backbencher refused to be silenced by the whips.", zh: "精力充沛而好爭的；潑辣的" },
    { front: "feral", pos: "adj.", def: "wild, especially after escaping domestication", example: "Feral goats have stripped the island's native vegetation.", zh: "野化的；野性的" },
    { front: "fester", pos: "v.", def: "worsen through neglect (of wounds or resentment)", example: "Allowed to fester, the border dispute poisoned relations for decades.", zh: "潰爛；（積怨）加深" },
    { front: "figurehead", pos: "n.", def: "a nominal leader without real power", example: "The monarch is a figurehead; ministers wield the actual authority.", zh: "有名無實的領袖" },
    { front: "finesse", pos: "n.", def: "refined skill and delicacy in handling matters", example: "Defusing the diplomatic row required considerable finesse.", zh: "手腕；技巧" },
    { front: "flamboyant", pos: "adj.", def: "confidently showy and attention-grabbing", example: "His flamboyant courtroom style delighted reporters and irritated judges.", zh: "浮誇炫麗的；招搖的" },
    { front: "fluke", pos: "n.", def: "a lucky chance occurrence", example: "Sceptics dismissed the record-breaking run as a statistical fluke.", zh: "僥倖；偶然的好運" },
    { front: "forage", pos: "v.", def: "search widely for food or provisions", example: "Volunteers foraged for edible fungi under the ranger's supervision.", zh: "覓食；搜尋" },
    { front: "foreboding", pos: "n.", def: "a feeling that something bad will happen", example: "She boarded the night train with a growing sense of foreboding.", zh: "不祥的預感" },
    { front: "forthright", pos: "adj.", def: "direct and outspoken", example: "His forthright assessment of the merger ruffled feathers upstairs.", zh: "直率的；坦言不諱的" },
    { front: "fracas", pos: "n.", def: "a noisy disturbance or quarrel", example: "Two players were suspended after the touchline fracas.", zh: "打鬧；騷亂" },
    { front: "furore", pos: "n.", def: "an outbreak of public anger or excitement", example: "The casting decision provoked a furore among purist fans.", zh: "群情激憤；軒然大波" },
    { front: "gaudy", pos: "adj.", def: "showy in a tasteless, brightly coloured way", example: "The lobby's gaudy chandeliers clashed with the building's austere facade.", zh: "俗豔的；花俏的" },
    { front: "gingerly", pos: "adv.", def: "very carefully and cautiously", example: "He stepped gingerly across the frost-covered footbridge.", zh: "小心翼翼地" },
    { front: "glean", pos: "v.", def: "gather information gradually from various sources", example: "Analysts gleaned the plant's output from satellite imagery.", zh: "蒐集；拾取（資訊）" },
    { front: "glut", pos: "n.", def: "an excessive supply of something", example: "A glut of unsold apartments dragged prices down across the city.", zh: "供過於求；過剩" },
    { front: "goad", pos: "v.", def: "provoke someone into action or anger", example: "Hecklers tried to goad the speaker into an unguarded outburst.", zh: "刺激；激怒使行動" },
    { front: "grievous", pos: "adj.", def: "very serious or severe (of harm)", example: "He was convicted of inflicting grievous bodily harm.", zh: "重大的；令人痛心的" },
    { front: "grovel", pos: "v.", def: "act with excessive humility to gain favour", example: "He grovelled before the editor, desperate to keep his column.", zh: "卑躬屈膝；搖尾乞憐" },
    { front: "gumption", pos: "n.", def: "shrewd initiative and courage", example: "It took real gumption to challenge the auditors' findings publicly.", zh: "膽識；進取心" },
    { front: "gusto", pos: "n.", def: "great enjoyment and energy in doing something", example: "The choir attacked the finale with tremendous gusto.", zh: "興致勃勃；熱情" },
    { front: "hallowed", pos: "adj.", def: "greatly revered; made holy", example: "Few amateurs ever bowl on the hallowed turf of Lord's.", zh: "神聖的；備受尊崇的" },
    { front: "hamstring", pos: "v.", def: "severely restrict the efficiency of someone", example: "The agency is hamstrung by a budget frozen since 2019.", zh: "使束手無策；嚴重掣肘" },
    { front: "haphazard", pos: "adj.", def: "lacking any order or plan; random", example: "Records were kept in such a haphazard fashion that audits proved impossible.", zh: "雜亂無章的；隨意的" },
    { front: "headstrong", pos: "adj.", def: "self-willed and refusing advice", example: "The headstrong heiress ignored every warning about her business partner.", zh: "剛愎任性的" },
    { front: "heady", pos: "adj.", def: "exhilarating and intoxicating", example: "Those were heady days, when every start-up seemed destined for glory.", zh: "令人陶醉的；使人興奮的" },
    { front: "heckle", pos: "v.", def: "interrupt a public speaker with rude shouts", example: "Protesters heckled the minister throughout her keynote address.", zh: "起鬨；喝倒采" },
    { front: "heresy", pos: "n.", def: "an opinion profoundly at odds with accepted belief", example: "Questioning the free market was heresy in that department.", zh: "異端邪說" },
    { front: "hiatus", pos: "n.", def: "a pause or gap in continuity", example: "The band reunited after a hiatus of nearly twenty years.", zh: "中斷；空檔" },
    { front: "hoard", pos: "v.", def: "accumulate and hide away supplies or money", example: "Panicked shoppers hoarded fuel despite official reassurances.", zh: "囤積" },
    { front: "pass over", pos: "phrasal v.", def: "ignore someone's claim for promotion or attention", example: "Passed over for partnership twice, she took her clients elsewhere.", zh: "忽略；未予擢升" },
    { front: "pick apart", pos: "phrasal v.", def: "criticise by analysing in minute detail", example: "Reviewers picked apart the study's sampling methodology.", zh: "逐點批駁；挑毛病" },
    { front: "pine for", pos: "phrasal v.", def: "long deeply for someone or something absent", example: "Exiled in the capital, he pined for the mists of his island home.", zh: "苦苦思念；渴望" },
    { front: "play up", pos: "phrasal v.", def: "emphasise something; cause trouble", example: "The brochure plays up the resort's seclusion and glosses over the airport noise.", zh: "強調渲染；作怪" },
    { front: "plump for", pos: "phrasal v.", def: "choose one option decisively after hesitation", example: "After weeks of dithering, the committee plumped for the cheaper design.", zh: "最終選定" },
    { front: "polish off", pos: "phrasal v.", def: "finish something quickly and completely", example: "He polished off the remaining paperwork before lunch.", zh: "迅速解決；吃光" },
    { front: "prey on", pos: "phrasal v.", def: "exploit the vulnerable; trouble one's mind", example: "Fraudsters prey on pensioners unfamiliar with online banking.", zh: "捕食；坑害；縈繞心頭" },
    { front: "pry into", pos: "phrasal v.", def: "inquire intrusively into someone's private affairs", example: "She resented journalists prying into her family's finances.", zh: "窺探；打探" },
    { front: "rake in", pos: "phrasal v.", def: "earn large amounts of money easily", example: "The franchise rakes in millions from merchandise alone.", zh: "大把撈錢" },
    { front: "rally round", pos: "phrasal v.", def: "unite to support someone in difficulty", example: "When the shop burned down, the whole village rallied round.", zh: "團結支援" },
    { front: "read up on", pos: "phrasal v.", def: "study a subject thoroughly by reading", example: "She read up on maritime law before accepting the brief.", zh: "研讀；惡補" },
    { front: "reel from", pos: "phrasal v.", def: "be shaken or staggered by a shock", example: "Markets were still reeling from the bank's sudden collapse.", zh: "因……而震盪；深受打擊" },
    { front: "get off on the wrong foot", pos: "idiom", def: "begin a relationship badly", example: "The new director got off on the wrong foot by cancelling the staff bonus.", zh: "一開始就不順；出師不利" },
    { front: "get to the bottom of", pos: "idiom", def: "discover the true cause of a problem", example: "Auditors were brought in to get to the bottom of the missing funds.", zh: "查明真相；追根究柢" },
    { front: "give free rein to", pos: "idiom", def: "allow complete freedom of action or expression", example: "The studio gave the director free rein to reimagine the classic.", zh: "放手讓……自由發揮" },
    { front: "go out on a limb", pos: "idiom", def: "take a risky, unsupported position", example: "I'll go out on a limb and predict the merger collapses by June.", zh: "冒險表態；孤注一擲" },
    { front: "go to great lengths", pos: "idiom", def: "make extraordinary efforts to achieve something", example: "The palace went to great lengths to keep the engagement secret.", zh: "不遺餘力；煞費苦心" },
    { front: "have a bone to pick with", pos: "idiom", def: "have a grievance to discuss with someone", example: "I have a bone to pick with whoever rescheduled the meeting to Friday evening.", zh: "有帳要算；有意見要理論" },
    { front: "hedge one's bets", pos: "idiom", def: "avoid committing to a single option", example: "The publisher hedged its bets by releasing print and digital editions simultaneously.", zh: "兩面下注；分散風險" },
    { front: "hit a brick wall", pos: "idiom", def: "reach a point where progress is impossible", example: "The investigation hit a brick wall when the key witness emigrated.", zh: "碰壁；陷入僵局" },
    { front: "hold sway over", pos: "idiom", def: "have controlling influence over", example: "Superstition still holds sway over parts of the fishing community.", zh: "支配；左右" },
    { front: "in the offing", pos: "idiom", def: "likely to happen soon", example: "With profits soaring, a takeover bid was clearly in the offing.", zh: "即將發生；在望" },
    { front: "in the pipeline", pos: "idiom", def: "being planned or developed", example: "Several stricter regulations are already in the pipeline.", zh: "在籌劃中；醞釀中" },
    { front: "raft of measures", pos: "collocation", def: "a large collection of policies or actions", example: "The chancellor unveiled a raft of measures to curb inflation.", zh: "一系列措施" },
    { front: "rave reviews", pos: "collocation", def: "extremely enthusiastic critical appraisals", example: "The revival opened to rave reviews in the weekend papers.", zh: "如潮好評" },
    { front: "redouble one's efforts", pos: "collocation", def: "try much harder than before", example: "Rescue teams redoubled their efforts as the weather window narrowed.", zh: "加倍努力" },
    { front: "riddled with errors", pos: "collocation", def: "full of mistakes throughout", example: "The first translation was riddled with errors and hastily withdrawn.", zh: "錯誤百出" },
    { front: "roundly condemn", pos: "collocation", def: "criticise in a forthright, emphatic manner", example: "The resolution was roundly condemned by every opposition party.", zh: "同聲譴責；嚴厲抨擊" },
    { front: "runaway success", pos: "collocation", def: "an unexpectedly huge success", example: "The podcast became a runaway success within months of launching.", zh: "空前的成功；一炮而紅" },
    { front: "sharp downturn", pos: "collocation", def: "a sudden, steep economic decline", example: "The sharp downturn in orders forced the plant onto short shifts.", zh: "急遽下滑" },
    { front: "shrouded in mystery", pos: "collocation", def: "kept completely secret or unexplained", example: "The benefactor's identity remains shrouded in mystery.", zh: "籠罩在神祕之中" },
    { front: "skeleton staff", pos: "collocation", def: "the minimum number of employees needed", example: "Over the holidays the embassy operates with a skeleton staff.", zh: "最低限度人力" },
    { front: "sluggish growth", pos: "collocation", def: "slow, weak economic expansion", example: "Years of sluggish growth eroded confidence in the reform programme.", zh: "成長遲緩" },
    { front: "snap decision", pos: "collocation", def: "a decision made instantly without deliberation", example: "Pilots are trained to make snap decisions under extreme pressure.", zh: "倉促的決定；當機立斷" },
    { front: "hone", pos: "v.", def: "refine or perfect a skill over time", example: "She honed her advocacy skills at the moot court society.", zh: "磨練；精進" },
    { front: "humdrum", pos: "adj.", def: "monotonously dull and routine", example: "He escaped his humdrum office existence through amateur dramatics.", zh: "單調乏味的" },
    { front: "illustrious", pos: "adj.", def: "highly distinguished and admired", example: "She joined the illustrious ranks of laureates from that small college.", zh: "顯赫的；傑出的" },
    { front: "imbibe", pos: "v.", def: "absorb ideas; drink, especially alcohol", example: "Students imbibe the institution's values long before they can articulate them.", zh: "吸收（思想）；飲用" },
    { front: "immaculate", pos: "adj.", def: "perfectly clean or flawless", example: "The vintage Bentley was in immaculate condition.", zh: "潔淨無瑕的；完美的" },
    { front: "impertinent", pos: "adj.", def: "rude and disrespectful; not showing due respect", example: "The judge rebuked counsel for an impertinent line of questioning.", zh: "無禮的；冒失的" },
    { front: "imperil", pos: "v.", def: "put something at risk of harm", example: "The leak imperilled months of delicate negotiations.", zh: "危及；使陷於危險" },
    { front: "implore", pos: "v.", def: "beg someone desperately to do something", example: "Aid agencies implored donors not to let fatigue set in.", zh: "哀求；懇求" },
    { front: "incarcerate", pos: "v.", def: "imprison someone", example: "Thousands were incarcerated without trial during the emergency.", zh: "監禁；關押" },
    { front: "incensed", pos: "adj.", def: "extremely angry", example: "Incensed commuters besieged the rail operator's offices.", zh: "極為憤怒的" },
    { front: "incipient", pos: "adj.", def: "just beginning to develop", example: "The central bank moved swiftly to quash incipient inflation.", zh: "初期的；剛萌芽的" },
    { front: "incumbent", pos: "adj.", def: "currently holding office; obligatory upon", example: "It is incumbent upon directors to disclose any conflict of interest.", zh: "在任的；有義務的" },
    { front: "inebriated", pos: "adj.", def: "drunk; intoxicated", example: "An inebriated guest attempted to conduct the wedding orchestra.", zh: "酒醉的" },
    { front: "inert", pos: "adj.", def: "lacking the ability or will to move or act", example: "Parliament remained inert while the crisis deepened.", zh: "惰性的；無生氣的" },
    { front: "ingrained", pos: "adj.", def: "firmly established and hard to change", example: "Deference to seniority is deeply ingrained in the firm's culture.", zh: "根深柢固的" },
    { front: "injunction", pos: "n.", def: "a court order requiring or forbidding an action", example: "The developer obtained an injunction halting the protest camp.", zh: "禁制令" },
    { front: "insolvent", pos: "adj.", def: "unable to pay one's debts", example: "The auditors declared the shipping line insolvent.", zh: "無力償債的；破產的" },
    { front: "instil", pos: "v.", def: "gradually establish an idea or attitude in someone", example: "Her mentor instilled in her a horror of sloppy footnotes.", zh: "灌輸；逐漸培養" },
    { front: "intangible", pos: "adj.", def: "unable to be touched or precisely measured", example: "Brand loyalty is an intangible asset that rarely appears on balance sheets.", zh: "無形的；難以捉摸的" },
    { front: "interloper", pos: "n.", def: "an intruder in a place or sphere not their own", example: "The old guard treated the young analysts as interlopers.", zh: "闖入者；外來干涉者" },
    { front: "invigorate", pos: "v.", def: "give strength, energy and vitality to", example: "The new signing invigorated a squad that had grown complacent.", zh: "使充滿活力；激勵" },
    { front: "irate", pos: "adj.", def: "very angry", example: "Irate listeners flooded the switchboard after the presenter's gaffe.", zh: "憤怒的" },
    { front: "irrefutable", pos: "adj.", def: "impossible to disprove", example: "The prosecution presented what it called irrefutable forensic evidence.", zh: "無可辯駁的" },
    { front: "irreverent", pos: "adj.", def: "disrespectful in an amusing way towards things taken seriously", example: "The magazine's irreverent take on royal protocol delighted younger readers.", zh: "不敬的；戲謔的" },
    { front: "jaundiced", pos: "adj.", def: "bitter or cynical from bad experience", example: "Years in tabloid journalism left him with a jaundiced view of fame.", zh: "偏見的；憤世嫉俗的" },
    { front: "jeopardise", pos: "v.", def: "put something at risk of loss or failure", example: "One careless tweet jeopardised the entire sponsorship deal.", zh: "危及；損害" },
    { front: "jostle", pos: "v.", def: "push roughly against others; compete for position", example: "Lobbyists jostled for the minister's attention at the reception.", zh: "推擠；爭奪" },
    { front: "juggernaut", pos: "n.", def: "a huge, unstoppable force or institution", example: "Independent bookshops struggle against the online retail juggernaut.", zh: "勢不可擋的龐然大物" },
    { front: "lacklustre", pos: "adj.", def: "lacking energy, brilliance or conviction", example: "The champion's lacklustre defence of her title surprised commentators.", zh: "乏善可陳的；黯淡的" },
    { front: "lampoon", pos: "v.", def: "publicly ridicule through satire", example: "The cartoonist lampooned the cabinet as squabbling schoolboys.", zh: "諷刺；嘲弄" },
    { front: "lavish", pos: "adj.", def: "sumptuously rich; generously given", example: "The premiere was followed by a lavish reception at the embassy.", zh: "奢華的；慷慨的" },
    { front: "lax", pos: "adj.", def: "not sufficiently strict or careful", example: "Lax oversight allowed the trader to conceal his losses for years.", zh: "鬆散的；不嚴格的" },
    { front: "levity", pos: "n.", def: "humour or lack of seriousness, especially inappropriately", example: "A moment of levity broke the tension in the operating theatre.", zh: "輕率；詼諧" },
    { front: "liaise", pos: "v.", def: "cooperate and exchange information between groups", example: "The charity liaises closely with local clinics on vaccination drives.", zh: "聯繫協調" },
    { front: "linchpin", pos: "n.", def: "the essential element holding something together", example: "The veteran midfielder remains the linchpin of the side.", zh: "關鍵人物；樞紐" },
    { front: "listless", pos: "adj.", def: "lacking energy or enthusiasm", example: "The heatwave left the whole office listless by mid-afternoon.", zh: "無精打采的" },
    { front: "livid", pos: "adj.", def: "furiously angry", example: "She was livid when the airline lost her cello for the second time.", zh: "大發雷霆的" },
    { front: "loath", pos: "adj.", def: "reluctant or unwilling to do something", example: "The board was loath to abandon a project it had championed so publicly.", zh: "不情願的" },
    { front: "lofty", pos: "adj.", def: "elevated in character; haughty; very high", example: "The charter's lofty ideals soon collided with budgetary reality.", zh: "崇高的；高傲的" },
    { front: "maelstrom", pos: "n.", def: "a turbulent, confused situation; a whirlpool", example: "The young diplomat was plunged into the maelstrom of coalition politics.", zh: "大漩渦；動盪混亂" },
    { front: "magnate", pos: "n.", def: "a wealthy, influential business person", example: "A shipping magnate quietly acquired the ailing newspaper group.", zh: "大亨；巨頭" },
    { front: "resign oneself to", pos: "phrasal v.", def: "accept something unpleasant as inevitable", example: "She resigned herself to another winter of commuting in the dark.", zh: "認命接受；聽天由命" },
    { front: "revel in", pos: "phrasal v.", def: "take great pleasure in something", example: "The playwright revelled in the controversy her work provoked.", zh: "陶醉於；盡情享受" },
    { front: "round on", pos: "phrasal v.", def: "turn and attack someone suddenly, especially verbally", example: "The minister rounded on reporters who questioned her figures.", zh: "突然斥責；反咬一口" },
    { front: "rub off on", pos: "phrasal v.", def: "transfer one's qualities to someone through contact", example: "The captain's composure gradually rubbed off on the younger players.", zh: "耳濡目染地影響" },
    { front: "rustle up", pos: "phrasal v.", def: "prepare or find something quickly", example: "She rustled up a respectable supper from leftovers and tinned fish.", zh: "迅速張羅；湊出" },
    { front: "scrape by", pos: "phrasal v.", def: "manage to live with barely enough money", example: "On a stipend that meagre, the researchers barely scraped by.", zh: "勉強度日" },
    { front: "see through", pos: "phrasal v.", def: "recognise someone's deception; complete a task", example: "The examiner saw through the candidate's rehearsed answers at once.", zh: "看穿；堅持完成" },
    { front: "shoot down", pos: "phrasal v.", def: "reject an idea or argument forcefully", example: "Every proposal for reform was shot down by the standing committee.", zh: "駁斥；否決" },
    { front: "sift through", pos: "phrasal v.", def: "examine a mass of material carefully", example: "Investigators sifted through thousands of emails for evidence of collusion.", zh: "細細篩查" },
    { front: "slack off", pos: "phrasal v.", def: "work less hard than one should", example: "Productivity data suggested the night shift had been slacking off.", zh: "偷懶；鬆懈" },
    { front: "slip up", pos: "phrasal v.", def: "make a careless mistake", example: "The forger slipped up by using paper manufactured decades too late.", zh: "出差錯；失手" },
    { front: "snap up", pos: "phrasal v.", def: "buy or seize something quickly and eagerly", example: "Collectors snapped up every lot within the first hour of the auction.", zh: "搶購；搶先弄到手" },
    { front: "keep abreast of", pos: "idiom", def: "stay informed about the latest developments", example: "Clinicians struggle to keep abreast of the torrent of new research.", zh: "隨時掌握最新動態" },
    { front: "keep one's nose to the grindstone", pos: "idiom", def: "work hard and continuously", example: "She kept her nose to the grindstone and qualified two years early.", zh: "埋頭苦幹" },
    { front: "keep up appearances", pos: "idiom", def: "maintain an outward show of prosperity or normality", example: "Long after the money ran out, the family kept up appearances.", zh: "維持體面；撐場面" },
    { front: "kick up a fuss", pos: "idiom", def: "complain loudly and cause a commotion", example: "Passengers kicked up a fuss when the surcharge appeared unannounced.", zh: "大吵大鬧；抗議" },
    { front: "leave to one's own devices", pos: "idiom", def: "leave someone alone to do as they wish", example: "Left to their own devices, the interns produced remarkably inventive work.", zh: "任其自便；放任不管" },
    { front: "live hand to mouth", pos: "idiom", def: "spend all one earns on basic survival", example: "Between commissions, the sculptor lived hand to mouth for years.", zh: "勉強糊口" },
    { front: "make a beeline for", pos: "idiom", def: "go directly and quickly towards", example: "The delegates made a beeline for the buffet the moment the session ended.", zh: "直奔；逕自走向" },
    { front: "make ends meet", pos: "idiom", def: "earn just enough to cover living costs", example: "Even with two jobs she struggled to make ends meet in the capital.", zh: "使收支相抵；餬口" },
    { front: "make light of", pos: "idiom", def: "treat something serious as unimportant", example: "He made light of the diagnosis, joking with the nurses.", zh: "對……輕描淡寫" },
    { front: "not up to scratch", pos: "idiom", def: "below the required standard", example: "Two of the submissions were simply not up to scratch and were rejected.", zh: "不合格；未達標準" },
    { front: "on the back burner", pos: "idiom", def: "postponed; given low priority", example: "Expansion plans were put on the back burner during the downturn.", zh: "暫時擱置" },
    { front: "sorely lacking", pos: "collocation", def: "conspicuously absent or deficient", example: "Imagination was sorely lacking in the committee's final report.", zh: "嚴重欠缺" },
    { front: "spare no expense", pos: "collocation", def: "spend whatever is necessary without limit", example: "The oligarch spared no expense in restoring the palazzo.", zh: "不惜血本" },
    { front: "sprawling metropolis", pos: "collocation", def: "a vast, spread-out city", example: "The fishing village has grown into a sprawling metropolis of twelve million.", zh: "幅員遼闊的大都會" },
    { front: "stroke of genius", pos: "collocation", def: "an exceptionally brilliant idea or act", example: "Casting the unknown understudy proved a stroke of genius.", zh: "神來之筆；天才之舉" },
    { front: "strained relations", pos: "collocation", def: "tense, unfriendly dealings between parties", example: "The espionage scandal further strained relations between the two allies.", zh: "緊張的關係" },
    { front: "take centre stage", pos: "collocation", def: "become the focus of attention", example: "Climate policy took centre stage in the leaders' debate.", zh: "成為焦點" },
    { front: "teeter on the brink", pos: "collocation", def: "be extremely close to disaster", example: "The lender teetered on the brink of collapse until the bailout.", zh: "瀕臨（崩潰）邊緣" },
    { front: "tender one's resignation", pos: "collocation", def: "formally offer to resign", example: "The permanent secretary tendered her resignation the following morning.", zh: "提出辭呈" },
    { front: "thankless task", pos: "collocation", def: "necessary work that earns no gratitude", example: "Moderating the online forum is a thankless task.", zh: "吃力不討好的工作" },
    { front: "thunderous applause", pos: "collocation", def: "extremely loud clapping", example: "The soprano took her curtain call to thunderous applause.", zh: "如雷的掌聲" },
    { front: "token gesture", pos: "collocation", def: "a small act done merely for show", example: "Critics dismissed the fee waiver as a token gesture.", zh: "象徵性的表示" },
    { front: "malinger", pos: "v.", def: "feign illness to avoid work or duty", example: "The medic suspected several conscripts of malingering.", zh: "裝病逃避工作" },
    { front: "masquerade", pos: "v.", def: "pretend to be something one is not", example: "The scheme masqueraded as a charity while funnelling money offshore.", zh: "偽裝；假冒" },
    { front: "meritocracy", pos: "n.", def: "a system where advancement depends on ability", example: "The firm styles itself a meritocracy, yet every partner attended the same three schools.", zh: "菁英領導制；唯才是用" },
    { front: "mesmerise", pos: "v.", def: "capture someone's complete fascinated attention", example: "The illusionist mesmerised the audience for two full hours.", zh: "使著迷；使入神" },
    { front: "miserly", pos: "adj.", def: "extremely reluctant to spend money; meagre", example: "The heiress was notoriously miserly with her staff's wages.", zh: "吝嗇的；少得可憐的" },
    { front: "mundane", pos: "adj.", def: "ordinary, dull and unexciting", example: "The documentary finds poetry in the most mundane routines.", zh: "平凡乏味的；世俗的" },
    { front: "murky", pos: "adj.", def: "dark and dirty; obscure or dishonest", example: "The consultancy's murky finances attracted the regulator's attention.", zh: "混濁的；曖昧不明的" },
    { front: "negligible", pos: "adj.", def: "so small as to be insignificant", example: "The tax change will have a negligible effect on most households.", zh: "微不足道的" },
    { front: "nepotism", pos: "n.", def: "favouritism shown to relatives in appointments", example: "Accusations of nepotism dogged the mayor after his nephew's promotion.", zh: "裙帶關係；任用親信" },
    { front: "nondescript", pos: "adj.", def: "lacking distinctive features; unremarkable", example: "The safe house was a nondescript terrace in an anonymous suburb.", zh: "不起眼的；毫無特色的" },
    { front: "onus", pos: "n.", def: "the burden of responsibility or proof", example: "The onus is on the manufacturer to demonstrate the additive is safe.", zh: "責任；舉證義務" },
    { front: "oust", pos: "v.", def: "force someone out of a position or place", example: "Shareholders moved to oust the chairman at the annual meeting.", zh: "罷黜；逐出" },
    { front: "outlandish", pos: "adj.", def: "bizarre and unfamiliar; wildly unconventional", example: "His outlandish theories eventually earned grudging scientific acceptance.", zh: "古怪的；離奇的" },
    { front: "outstrip", pos: "v.", def: "exceed or surpass something", example: "Demand for the vaccine rapidly outstripped supply.", zh: "超過；勝過" },
    { front: "overhaul", pos: "v.", def: "thoroughly examine and repair or revise", example: "The commission recommended overhauling the entire licensing regime.", zh: "徹底翻修；全面改革" },
    { front: "pinnacle", pos: "n.", def: "the most successful point; the culmination", example: "For many sopranos, singing at Bayreuth represents the pinnacle of achievement.", zh: "頂峰；極致" },
    { front: "pique", pos: "v.", def: "arouse interest; wound someone's pride", example: "A footnote in the archives piqued the historian's curiosity.", zh: "激起（興趣）；使不悅" },
    { front: "pittance", pos: "n.", def: "a very small, inadequate amount of money", example: "The interns were paid a pittance for eighty-hour weeks.", zh: "微薄的收入" },
    { front: "ploy", pos: "n.", def: "a cunning plan to gain an advantage", example: "The price cut was merely a ploy to lure customers from rivals.", zh: "手段；花招" },
    { front: "preclude", pos: "v.", def: "prevent something from happening; make impossible", example: "His criminal record precludes employment in the financial sector.", zh: "排除；使不可能" },
    { front: "precocious", pos: "adj.", def: "developing abilities unusually early", example: "The precocious violinist performed with the philharmonic at eleven.", zh: "早熟的" },
    { front: "predicament", pos: "n.", def: "a difficult, embarrassing situation", example: "The stranded expedition's predicament worsened as supplies dwindled.", zh: "困境；窘境" },
    { front: "prescient", pos: "adj.", def: "showing accurate knowledge of events before they happen", example: "Her prescient warnings about the housing bubble went unheeded.", zh: "有先見之明的" },
    { front: "pretext", pos: "n.", def: "a false reason given to hide the real one", example: "The inspection was a pretext for gathering intelligence on the facility.", zh: "藉口；託辭" },
    { front: "pristine", pos: "adj.", def: "in perfect, unspoiled condition", example: "The manuscript survived in pristine condition inside the sealed vault.", zh: "嶄新的；未受破壞的" },
    { front: "procrastinate", pos: "v.", def: "delay doing something that should be done", example: "He procrastinated over the thesis until the deadline became unmissable.", zh: "拖延" },
    { front: "prolific", pos: "adj.", def: "producing many works, results or offspring", example: "A prolific essayist, she published in three languages simultaneously.", zh: "多產的" },
    { front: "quaint", pos: "adj.", def: "attractively old-fashioned or unusual", example: "Tourists flock to the quaint fishing villages along the peninsula.", zh: "古雅的；別致的" },
    { front: "quip", pos: "n.", def: "a witty, clever remark", example: "His quip about the budget defused an increasingly tense press conference.", zh: "妙語；俏皮話" },
    { front: "rebut", pos: "v.", def: "argue against a claim with evidence", example: "The defence called three experts to rebut the prosecution's timeline.", zh: "反駁；駁斥" },
    { front: "rectify", pos: "v.", def: "correct something wrong", example: "The bank promised to rectify the error and compensate affected customers.", zh: "矯正；改正" },
    { front: "reiterate", pos: "v.", def: "say something again for emphasis", example: "The governor reiterated that rates would stay unchanged until spring.", zh: "重申" },
    { front: "reminisce", pos: "v.", def: "indulge in enjoyable recollection of the past", example: "The veterans reminisced about their touring days over long lunches.", zh: "追憶；緬懷" },
    { front: "reprimand", pos: "v.", def: "rebuke someone officially for a fault", example: "The officer was formally reprimanded for breaching protocol.", zh: "申誡；訓斥" },
    { front: "resurgence", pos: "n.", def: "a revival after a period of decline", example: "Vinyl's unexpected resurgence has revived the town's pressing plant.", zh: "復甦；再起" },
    { front: "retort", pos: "n.", def: "a sharp, witty or angry reply", example: "Her withering retort silenced the heckler instantly.", zh: "反駁；回嘴" },
    { front: "revoke", pos: "v.", def: "officially cancel a decree, licence or privilege", example: "The authority revoked the club's licence after repeated violations.", zh: "撤銷；廢除" },
    { front: "rudimentary", pos: "adj.", def: "basic and undeveloped", example: "With only rudimentary tools, the islanders built remarkably seaworthy boats.", zh: "初步的；簡陋的" },
    { front: "sacrilege", pos: "n.", def: "gross disrespect towards something sacred or cherished", example: "To purists, remixing the maestro's recordings borders on sacrilege.", zh: "褻瀆" },
    { front: "semblance", pos: "n.", def: "an outward appearance, often misleading", example: "After the riots, the city slowly regained a semblance of normality.", zh: "表象；外貌" },
    { front: "sham", pos: "n.", def: "something false presented as genuine", example: "Observers denounced the election as an elaborate sham.", zh: "騙局；假貨" },
    { front: "spark off", pos: "phrasal v.", def: "trigger a sudden event or reaction", example: "The verdict sparked off protests in a dozen cities.", zh: "引發；觸發" },
    { front: "spill over", pos: "phrasal v.", def: "spread beyond original limits, especially conflict", example: "Analysts fear the border clashes could spill over into full war.", zh: "外溢；蔓延" },
    { front: "spur on", pos: "phrasal v.", def: "encourage someone to greater effort", example: "Spurred on by the home crowd, she shattered the national record.", zh: "激勵；鞭策" },
    { front: "stem from", pos: "phrasal v.", def: "originate or be caused by something", example: "Much of the distrust stems from the botched privatisation of the nineties.", zh: "源自；起因於" },
    { front: "step down", pos: "phrasal v.", def: "resign from an important position", example: "The founder stepped down as chief executive after the data scandal.", zh: "辭職；退位" },
    { front: "stir up", pos: "phrasal v.", def: "deliberately provoke trouble or strong feeling", example: "The pamphlet was designed to stir up resentment against the settlers.", zh: "煽動；挑起" },
    { front: "swear by", pos: "phrasal v.", def: "have complete confidence in something's effectiveness", example: "My grandmother swore by cider vinegar for practically every ailment.", zh: "極為信賴；篤信" },
    { front: "take aback", pos: "phrasal v.", def: "surprise or shock someone", example: "The interviewer was visibly taken aback by the candidate's candour.", zh: "使吃驚" },
    { front: "tamper with", pos: "phrasal v.", def: "interfere with something so as to damage it", example: "The seals showed the ballot boxes had been tampered with.", zh: "擅自竄改；動手腳" },
    { front: "tap into", pos: "phrasal v.", def: "gain access to and exploit a resource", example: "The campaign tapped into widespread anxiety about job security.", zh: "利用；發掘" },
    { front: "vouch for", pos: "phrasal v.", def: "confirm the truth or reliability of someone", example: "Two senior colleagues vouched for her integrity at the hearing.", zh: "為……擔保" },
    { front: "win over", pos: "phrasal v.", def: "persuade someone to support you", example: "The mayor's candour gradually won over even her fiercest critics.", zh: "爭取到支持；說服" },
    { front: "play it by ear", pos: "idiom", def: "improvise rather than follow a fixed plan", example: "With the schedule in chaos, we simply played it by ear.", zh: "見機行事；隨機應變" },
    { front: "play second fiddle", pos: "idiom", def: "take a subordinate role to someone", example: "Tired of playing second fiddle to the star anchor, he moved networks.", zh: "當副手；屈居次位" },
    { front: "pull one's weight", pos: "idiom", def: "do one's fair share of work", example: "Resentment grew towards partners who no longer pulled their weight.", zh: "盡本分；分擔工作" },
    { front: "rise to the occasion", pos: "idiom", def: "perform well in a demanding situation", example: "Thrust into the lead role at short notice, the understudy rose to the occasion.", zh: "臨場發揮出色；不負重任" },
    { front: "see eye to eye", pos: "idiom", def: "agree fully with someone", example: "The two editors rarely saw eye to eye on questions of taste.", zh: "看法一致" },
    { front: "set the record straight", pos: "idiom", def: "correct a misunderstanding publicly", example: "She wrote her memoirs chiefly to set the record straight.", zh: "澄清事實" },
    { front: "speak volumes", pos: "idiom", def: "convey a great deal without words", example: "The empty seats at the launch spoke volumes about investor confidence.", zh: "意味深長；不言而喻" },
    { front: "test the waters", pos: "idiom", def: "cautiously assess reactions before committing", example: "The label released a single to test the waters before funding the album.", zh: "試水溫" },
    { front: "through thick and thin", pos: "idiom", def: "in spite of all difficulties; loyally", example: "Her agent stood by her through thick and thin.", zh: "同甘共苦；不離不棄" },
    { front: "wide of the mark", pos: "idiom", def: "inaccurate; far from the truth", example: "Early estimates of the cleanup cost proved wildly wide of the mark.", zh: "離譜；大錯特錯" },
    { front: "win hands down", pos: "idiom", def: "win easily and decisively", example: "In any blind tasting, the cheaper vintage wins hands down.", zh: "輕鬆獲勝" },
    { front: "treasure trove", pos: "collocation", def: "a valuable collection or rich source", example: "The attic proved a treasure trove of unpublished correspondence.", zh: "寶庫；寶藏" },
    { front: "trumped-up charges", pos: "collocation", def: "false accusations invented to convict someone", example: "The dissident was jailed on trumped-up charges of embezzlement.", zh: "捏造的罪名" },
    { front: "undue influence", pos: "collocation", def: "improper pressure affecting someone's decisions", example: "The will was contested on grounds of undue influence.", zh: "不當影響" },
    { front: "unsung hero", pos: "collocation", def: "someone whose contributions go unrecognised", example: "The film honours the unsung heroes of the wartime code rooms.", zh: "無名英雄" },
    { front: "untold damage", pos: "collocation", def: "harm too great to be measured", example: "The leak did untold damage to the agency's credibility.", zh: "難以估計的損害" },
    { front: "vote of confidence", pos: "collocation", def: "an expression of continued support", example: "The board's public vote of confidence failed to reassure the markets.", zh: "信任表決；力挺" },
    { front: "window of opportunity", pos: "collocation", def: "a limited period when action is possible", example: "The ceasefire offered a narrow window of opportunity for aid convoys.", zh: "機會之窗" },
    { front: "with bated breath", pos: "collocation", def: "in anxious, suspenseful anticipation", example: "Astronomers waited with bated breath for the telescope's first images.", zh: "屏息以待" },
    { front: "withering look", pos: "collocation", def: "a scornful glance intended to humiliate", example: "She silenced the interrupting junior with a withering look.", zh: "輕蔑的一瞥" },
    { front: "woefully inadequate", pos: "collocation", def: "completely insufficient for what is needed", example: "The shelter's provisions proved woefully inadequate for the influx.", zh: "嚴重不足的" },
    { front: "unprecedented scale", pos: "collocation", def: "a size or extent never seen before", example: "The evacuation was carried out on an unprecedented scale.", zh: "史無前例的規模" },
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
